/* =========================================================================
   data_2022_12.js — JLPT N2 2022年12月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2022_12", label:"12/2022", title:"JLPT N2 — 2022年12月 (12/2022)", file:"data_2022_12.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{ tab:"文字・語彙", section:"問題1 漢字読み",
  instruction:"＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f1-1", passage:"", audioUrl:"", question:"1. 建物の入り口に<u>警備</u>の人がいます。", options:["けいひ","けいび","げんひ","げんび"], answer:1,
    translation:"Ở lối vào toà nhà có người bảo vệ.", explanation:"警備 = けいび: bảo vệ, canh gác. けいひ/げんひ/げんび không phải âm đọc của 警備." },
  { id:"f1-2", passage:"", audioUrl:"", question:"2. 絵を見て、<u>想像力</u>が刺激されました。", options:["そうぞうりょく","そうぞうりき","しょうぞうりょく","ぞうぞうりょく"], answer:0,
    translation:"Nhìn bức tranh, trí tưởng tượng của tôi được kích thích.", explanation:"想像力 = そうぞうりょく: trí tưởng tượng. （⚠️ File gốc OCR phần này bị lỗi/sai lệch — câu 2 trong bảng đáp án là ④ với từ gạch chân 刺激=しげき; ở đây ghi theo câu 2 nguyên văn của đề.）" },
  { id:"f1-3", passage:"", audioUrl:"", question:"3. ここが<u>外れて</u>いますけど、どうしたんですか。", options:["はずれて","みだれて","やぶれて","つぶれて"], answer:0,
    translation:"Chỗ này bị bung ra rồi, có chuyện gì vậy?", explanation:"外れる = はずれる: bung ra, lệch ra, tuột ra. 乱れる (rối), 破れる (rách), 潰れる (bẹp) không hợp." },
  { id:"f1-4", passage:"", audioUrl:"", question:"4. 私は<u>世間</u>の目を気にしすぎていたようだ。", options:["せかん","せけん","せいかん","せいけん"], answer:1,
    translation:"Có vẻ tôi đã quá để ý đến con mắt của thiên hạ.", explanation:"世間 = せけん: thế gian, thiên hạ, xã hội." },
  { id:"f1-5", passage:"", audioUrl:"", question:"5. 本田さんはとても<u>勇ましい</u>んだ。", options:["たくましい","やかましい","いさましい","あつかましい"], answer:2,
    translation:"Anh Honda rất dũng cảm/mạnh mẽ.", explanation:"勇ましい = いさましい: dũng mãnh, gan dạ. たくましい (vạm vỡ), やかましい (ồn ào), あつかましい (trơ tráo) không đúng." }
]},
{ tab:"文字・語彙", section:"問題2 表記",
  instruction:"＿＿＿の言葉を漢字で書くとき、最もよいものを1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f2-1", passage:"", audioUrl:"", question:"6. 彼にはお金持ちになりたいという<u>よく</u>がない。", options:["欲","望","求","情"], answer:0,
    translation:"Anh ta không có lòng tham muốn trở thành người giàu.", explanation:"よく = 欲: dục vọng, lòng tham. 望 (mong), 求 (cầu), 情 (tình) không đọc là よく trong nghĩa này." },
  { id:"f2-2", passage:"", audioUrl:"", question:"7. 私の職業は、<u>はいゆう</u>です。", options:["排憂","排優","俳憂","俳優"], answer:3,
    translation:"Nghề của tôi là diễn viên.", explanation:"はいゆう = 俳優: diễn viên (sân khấu, phim)." },
  { id:"f2-3", passage:"", audioUrl:"", question:"8. 中山さんは、家族と<u>はなれて</u>、一人で暮らしているらしい。", options:["逃れて","別れて","離れて","避けて"], answer:2,
    translation:"Nghe nói anh Nakayama sống một mình, xa gia đình.", explanation:"はなれる = 離れる: rời xa, tách khỏi (khoảng cách vật lý/địa lý). 逃れる (trốn khỏi), 別れる (chia tay), 避ける (tránh) không hợp nghĩa 'sống xa gia đình'." },
  { id:"f2-4", passage:"", audioUrl:"", question:"9. 病院で医師の<u>しんだん</u>を受けた。", options:["身断","診断","身談","診談"], answer:1,
    translation:"Tôi đã được bác sĩ chẩn đoán ở bệnh viện.", explanation:"しんだん = 診断: chẩn đoán." },
  { id:"f2-5", passage:"", audioUrl:"", question:"10. AとBは、大きさが<u>ひとしい</u>。", options:["並しい","等しい","似しい","比しい"], answer:1,
    translation:"A và B có kích thước bằng nhau.", explanation:"ひとしい = 等しい: bằng nhau, ngang nhau." }
]},
{ tab:"文字・語彙", section:"問題3 語形成",
  instruction:"（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f3-1", passage:"", audioUrl:"", question:"11. （ ）制度には、大きな問題があります。", options:["近","在","常","現"], answer:3,
    translation:"Chế độ hiện hành có vấn đề lớn.", explanation:"現制度 (げんせいど): chế độ hiện hành. 現 = hiện tại." },
  { id:"f3-2", passage:"", audioUrl:"", question:"12. 伯父は、電車の中で財布を盗まれてから用心（ ）なった。", options:["濃く","強く","深く","高く"], answer:2,
    translation:"Bác tôi từ sau khi bị móc ví trên tàu điện thì trở nên cảnh giác hơn.", explanation:"用心深い (ようじんぶかい): hết sức cảnh giác, cẩn thận. ～深い = sâu, mức độ cao." },
  { id:"f3-3", passage:"", audioUrl:"", question:"13. このアンケートでは、（ ）団体の活動についてお尋ねします。", options:["貴","尊","敬","偉"], answer:0,
    translation:"Trong bảng khảo sát này, chúng tôi xin hỏi về hoạt động của quý đoàn thể.", explanation:"貴団体 (きだんたい): quý đoàn thể — cách nói kính ngữ lịch sự trong văn bản hành chính." }
]},
{ tab:"文字・語彙", section:"問題4 文脈規定",
  instruction:"（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f4-1", passage:"", audioUrl:"", question:"14. 規則に（ ）した場合は、罰金を払わなければならない。", options:["相違","対決","違反","対抗"], answer:2,
    translation:"Trường hợp vi phạm quy định thì phải nộp phạt.", explanation:"違反する: vi phạm (quy định, luật). 相違 (khác biệt), 対決 (đối đầu), 対抗 (đối kháng) không hợp." },
  { id:"f4-2", passage:"", audioUrl:"", question:"15. この体育館は、ロッカーやシャワーなどの（ ）がそろっている。", options:["用具","物体","設備","容器"], answer:2,
    translation:"Nhà thể dục này có đầy đủ trang thiết bị như tủ đồ, vòi sen…", explanation:"設備 (せつび): trang thiết bị, cơ sở vật chất. 用具 (dụng cụ), 物体 (vật thể), 容器 (vật chứa) không hợp." },
  { id:"f4-3", passage:"", audioUrl:"", question:"16. 化粧品メーカーが健康食品の分野に（ ）して成功した例もある。", options:["到達","転勤","直行","進出"], answer:3,
    translation:"Cũng có ví dụ hãng mỹ phẩm tiến vào lĩnh vực thực phẩm sức khoẻ và thành công.", explanation:"進出する: tiến vào, mở rộng sang (lĩnh vực/thị trường mới). 到達 (đạt tới), 転勤 (chuyển công tác), 直行 (đi thẳng) không hợp." },
  { id:"f4-4", passage:"", audioUrl:"", question:"17. この時期に雪が降ることはあるが、積もることは（ ）だ。", options:["まれ","なだらか","ささやか","かすか"], answer:0,
    translation:"Thời điểm này có thể có tuyết rơi, nhưng tích tụ lại thì hiếm.", explanation:"まれ (稀): hiếm, ít khi. なだらか (thoải), ささやか (nhỏ nhặt), かすか (mờ nhạt) không hợp." },
  { id:"f4-5", passage:"", audioUrl:"", question:"18. 家の隣で夜遅くまでマンション建設工事が行われてうるさいので、建設会社に（ ）の電話をした。", options:["悪口","苦情","反論","皮肉"], answer:1,
    translation:"Vì công trình xây chung cư bên cạnh làm ồn đến tận đêm khuya nên tôi đã gọi điện phàn nàn với công ty xây dựng.", explanation:"苦情 (くじょう): lời phàn nàn, khiếu nại. 悪口 (lời nói xấu), 反論 (phản bác), 皮肉 (mỉa mai) không hợp." },
  { id:"f4-6", passage:"", audioUrl:"", question:"19. 箱の中には、隙間なく（ ）お菓子が詰まっていた。", options:["どしどし","どっしり","うじゃうじゃ","ぎっしり"], answer:3,
    translation:"Trong hộp, bánh kẹo được xếp chặt kín không còn khe hở.", explanation:"ぎっしり: chặt kín, đầy ắp không có khe hở. どしどし (ầm ầm), どっしり (vững chãi), うじゃうじゃ (lúc nhúc) không hợp." },
  { id:"f4-7", passage:"", audioUrl:"", question:"20. 私は前回の実験の結果にずっと疑問を（ ）いる。", options:["いだいて","にぎって","たもって","そなえて"], answer:0,
    translation:"Tôi luôn ôm mối nghi ngờ về kết quả thí nghiệm lần trước.", explanation:"疑問を抱く (いだく): ôm mối nghi ngờ — cách nói cố định. 握る (nắm), 保つ (giữ), 備える (chuẩn bị) không tạo cụm đúng." }
]},
{ tab:"文字・語彙", section:"問題5 言い換え類義",
  instruction:"＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f5-1", passage:"", audioUrl:"", question:"21. あの選手には<u>テクニック</u>がある。", options:["自信","技術","経験","体力"], answer:1,
    translation:"Vận động viên đó có kỹ thuật.", explanation:"テクニック = 技術: kỹ thuật, kỹ năng. 自信 (tự tin), 経験 (kinh nghiệm), 体力 (thể lực) không đúng." },
  { id:"f5-2", passage:"", audioUrl:"", question:"22. ここには大量の<u>書籍</u>が収められている。", options:["新聞","絵","本","手紙"], answer:2,
    translation:"Ở đây lưu trữ một lượng lớn sách.", explanation:"書籍 = 本: sách (cách nói trang trọng)." },
  { id:"f5-3", passage:"", audioUrl:"", question:"23. 今年になって国の方針が<u>一転した</u>。", options:["すっかり変わった","少し変わった","やっと決まった","すぐに決まった"], answer:0,
    translation:"Bước sang năm nay, phương châm của quốc gia đã thay đổi hoàn toàn.", explanation:"一転する = すっかり変わる: đổi hẳn, xoay 180 độ." },
  { id:"f5-4", passage:"", audioUrl:"", question:"24. この道具は先が<u>とがっている</u>。", options:["柔らかくなって","細くなって","硬くなって","太くなって"], answer:1,
    translation:"Dụng cụ này có đầu nhọn (thuôn nhỏ lại).", explanation:"とがる = nhọn, thon nhỏ dần về phía đầu ⇒ 細くなって. （File gốc OCR có sai lệch chữ ở phương án này.）" },
  { id:"f5-5", passage:"", audioUrl:"", question:"25. 彼がしていることは<u>くだらない</u>。", options:["効果がない","目的ない","変化がない","価値がない"], answer:3,
    translation:"Việc anh ta đang làm thật vô nghĩa.", explanation:"くだらない = 価値がない: vô giá trị, nhảm nhí, vô nghĩa." }
]},
/* ================= TAB 2: 用法 ================= */
{ tab:"用法", section:"問題6 用法",
  instruction:"次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f6-1", passage:"", audioUrl:"", question:"26. 頑固",
    options:["木村さんはとても頑固で、自分の考えを変えない。","瓶のふたが頑固で、いくら力を入れても開かない。","兄は体が頑固なので、風邪をほとんどひかない。","相手チームの守りがとても頑固で、手が取れない。"], answer:0,
    translation:"Anh Kimura rất bảo thủ, không chịu thay đổi suy nghĩ của mình.",
    explanation:"頑固 = bảo thủ, cố chấp (tính cách con người) ✓. Không dùng cho nắp chai (固い), sức khoẻ (丈夫), hay hàng phòng thủ (堅い)." },
  { id:"f6-2", passage:"", audioUrl:"", question:"27. 打ち合わせ",
    options:["本日11時から、来月の講演会の打ち合わせを行います。","高校生のころはよく、親友と互いの悩みの打ち合わせをしました。","ホテルに電話をして、眼鏡の忘れ物がないか打ち合わせをしました。","実験の後、失敗の原因について打ち合わせを行いました。"], answer:0,
    translation:"Từ 11 giờ hôm nay, chúng tôi sẽ họp bàn (trao đổi trước) về buổi diễn thuyết tháng sau.",
    explanation:"打ち合わせ = cuộc trao đổi/bàn bạc trước về công việc ✓ (打ち合わせを行う). Không dùng cho 'chia sẻ nỗi lo' (相談), 'hỏi' (問い合わせ), 'thảo luận tìm nguyên nhân' (検討/話し合い)." },
  { id:"f6-3", passage:"", audioUrl:"", question:"28. 中断",
    options:["急に仕事が入ってしまい、レストランの予約を中断した。","部屋のカーテンを閉めて、太陽の光を中断した。","雨が強くなってきたので、やむまで試合を中断した。","今日は用事があるため、友人からの誘いを中断した。"], answer:2,
    translation:"Vì mưa mạnh lên nên trận đấu bị tạm dừng cho đến khi tạnh.",
    explanation:"中断する = tạm dừng giữa chừng một việc đang diễn ra ✓. Không dùng cho 'huỷ đặt bàn' (キャンセル), 'chặn ánh sáng' (遮る), 'từ chối lời mời' (断る)." },
  { id:"f6-4", passage:"", audioUrl:"", question:"29. ベテラン",
    options:["あのベテランの電車は、今まで多くのお客さんを乗せてきた。","大野先生は、この学校で昔から教えているベテランの先生だ。","このベテランの時計は、もう生産していないので貴重だ。","ここは、私が生まれる前からあるベテランのレストランだ。"], answer:1,
    translation:"Thầy Ōno là giáo viên lão luyện, đã dạy ở trường này từ lâu.",
    explanation:"ベテラン = người lão luyện, có kinh nghiệm lâu năm (dùng cho NGƯỜI) ✓. Không dùng cho tàu điện, đồng hồ, nhà hàng." },
  { id:"f6-5", passage:"", audioUrl:"", question:"30. 荒れる",
    options:["この靴は10年間も履き続けているから、かなり荒れている。","入院で仕事を休んでいたので、営業成績は荒れてしまった。","冷蔵庫に入れておいたのに、りんごが荒れてしまった。","今日は海が荒れていて、船で釣りに行くことはできない。"], answer:3,
    translation:"Hôm nay biển động nên không thể đi câu bằng thuyền.",
    explanation:"荒れる = trở nên dữ dội/động (thời tiết, biển, sóng gió) ✓. Không dùng cho giày (傷む), thành tích (落ちる), táo (腐る)." }
]},
/* ================= TAB 3: 文法 ================= */
{ tab:"文法", section:"問題7 文の文法1",
  instruction:"次の文の（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f7-1", passage:"", audioUrl:"", question:"31. 先週末は、（ ）かけだった3冊の本をすべて最後まで読んだ。", options:["読む","読み","読んで","読んだ"], answer:1,
    translation:"Cuối tuần trước, tôi đã đọc hết cả 3 cuốn sách đang đọc dở.",
    explanation:"～かけだ／～かけの: đang làm dở. 読みかけ = đọc dở (Vます-bỏます + かけ)." },
  { id:"f7-2", passage:"", audioUrl:"", question:"32. 子供のころはピーマンが嫌いだったが、今は嫌いではない。（ ）好きな野菜の一つだ。", options:["むしろ","いったい","そのうち","ちっとも"], answer:0,
    translation:"Hồi nhỏ tôi ghét ớt chuông, nhưng giờ không ghét nữa — mà còn nói đúng hơn là một trong những loại rau tôi thích.",
    explanation:"むしろ: nói đúng hơn thì, mà còn là. いったい (rốt cuộc), そのうち (một lúc nào đó), ちっとも (chẳng chút nào) không hợp." },
  { id:"f7-3", passage:"", audioUrl:"", question:"33. 来年3月の完成（ ）、新しい体育館の建設工事が着々と進んでいる。", options:["を込めて","に際して","を通じて","に向けて"], answer:3,
    translation:"Hướng tới ngày hoàn thành tháng 3 năm sau, công trình xây nhà thể dục mới đang tiến triển đều đặn.",
    explanation:"～に向けて: hướng tới, nhằm mục tiêu (mốc thời gian/mục đích). を込めて (gửi gắm), に際して (nhân dịp), を通じて (thông qua) không hợp." },
  { id:"f7-4", passage:"", audioUrl:"", question:"34. （携帯電話の店で）父「どれにしようかな。通話ができれば十分なんだけど。」息子「通話ができるだけ（ ）、これにしたら？」",
    options:["がいいと","でいいなら","でいいけど","がいいのに"], answer:1,
    translation:"(Ở cửa hàng điện thoại) Bố: \"Chọn cái nào nhỉ, chỉ cần gọi được là đủ rồi.\" Con: \"Nếu chỉ cần gọi được là được thì lấy cái này đi?\"",
    explanation:"～でいいなら: nếu (chỉ cần) ~ là được thì. 通話ができるだけでいいなら… ✓" },
  { id:"f7-5", passage:"", audioUrl:"", question:"35. 課長に、次の会議までにこの資料を（ ）言われた。", options:["読んでおくよう","読んでおきなさい","読んでくるか","読んでこい"], answer:0,
    translation:"Tôi được trưởng phòng bảo là hãy đọc tài liệu này trước cuộc họp tới.",
    explanation:"～ように言われた: được bảo là hãy… (gián tiếp). Trực tiếp sẽ là 読みなさい/読んでおきなさい nhưng không đi với 言われた." },
  { id:"f7-6", passage:"", audioUrl:"", question:"36. （ ）昼過ぎまで寝ているのはよくないと思う。", options:["休みの日どころか","休みの日かというと","休みの日にしては","休みの日だからといって"], answer:3,
    translation:"Tôi nghĩ dù là ngày nghỉ thì ngủ đến quá trưa cũng không tốt.",
    explanation:"～だからといって: dù là… thì cũng (không có nghĩa là được phép)." },
  { id:"f7-7", passage:"", audioUrl:"", question:"37. 先月から食堂でアルバイトを始めた。お客さんがおいしいと（ ）、うれしくなり、もっと頑張ろうと思える。", options:["言ってあげるたびに","言ってあげるように","言ってくれるたびに","言ってくれるように"], answer:2,
    translation:"Tôi bắt đầu làm thêm ở căng tin từ tháng trước. Mỗi lần khách nói 'ngon', tôi lại thấy vui và muốn cố gắng hơn.",
    explanation:"～てくれる: (người khác) làm cho mình; ～たびに: mỗi khi. 言ってくれるたびに ✓" },
  { id:"f7-8", passage:"", audioUrl:"", question:"38. （映画館で）夫「席の番号、忘れちゃった。何番（ ）？」妻「Jの14と15だよ。」", options:["だったようね","だって","じゃなかったの","なんじゃないか"], answer:1,
    translation:"(Ở rạp phim) Chồng: \"Quên mất số ghế rồi. Số mấy ấy nhỉ?\" Vợ: \"J14 và J15 đấy.\"",
    explanation:"～だっけ／～だって: dùng khi hỏi lại điều mình đã quên (khẩu ngữ)." },
  { id:"f7-9", passage:"", audioUrl:"", question:"39. 「倉庫の中を片付けなければ」と前からずっと思っているのだが、忙しくてなかなか（ ）。", options:["できずにいる","できるだろうか","できないこともない","できるのではないか"], answer:0,
    translation:"Tôi đã nghĩ mãi là phải dọn kho, nhưng bận quá nên cứ chưa làm được.",
    explanation:"～ずにいる: cứ ở trong trạng thái không làm (mặc dù muốn/đáng lẽ phải làm)." },
  { id:"f7-10", passage:"", audioUrl:"", question:"40. （劇場内のアナウンスで）スタッフ「お客様にご案内（ ）。ただいま、1階ロビーにおいて、公演パンフレットを販売しております。ぜひご利用ください。」",
    options:["なさいます","うけたまわります","申し上げます","おっしゃいます"], answer:2,
    translation:"(Thông báo trong nhà hát) Nhân viên: \"Xin thông báo tới quý khách. Hiện tại, ở sảnh tầng 1 đang bán pamphlet của buổi diễn. Kính mời quý khách.\"",
    explanation:"ご案内申し上げます = khiêm nhường ngữ, 'xin được thông báo'. なさいます/おっしゃいます là tôn kính ngữ (dùng cho người khác), うけたまわります là 'xin tiếp nhận'." },
  { id:"f7-11", passage:"", audioUrl:"", question:"41. 昨日はかなり風が強くて、何度も帽子を（ ）。", options:["飛ばされたところだ","飛んでいったところだ","飛ばされそうになった","飛んでいきそうになった"], answer:2,
    translation:"Hôm qua gió khá mạnh, tôi đã nhiều lần suýt bị thổi bay mũ.",
    explanation:"～そうになる: suýt thì (bị làm gì). 帽子を飛ばされそうになった ✓ (bị động + そうになる)." },
  { id:"f7-12", passage:"", audioUrl:"", question:"42. 昨日、最近評判のレストランに行った。サービスと雰囲気はとてもよかったが、味は（ ）。", options:["期待していなかったせいだ","期待していたからではなかった","期待していなかったはずだ","期待していたほどではなかった"], answer:3,
    translation:"Hôm qua tôi đến nhà hàng đang được đồn đại. Dịch vụ và không khí rất tốt, nhưng hương vị thì không đến mức như tôi kỳ vọng.",
    explanation:"～ほどではなかった: không đến mức như… 期待していたほどではなかった ✓" }
]},
{ tab:"文法", section:"問題8 文の文法2 (sắp xếp - ★)",
  instruction:"次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f8-1", passage:"", audioUrl:"", question:"43. 私は、とにかく勉強が嫌いで、学校があまり好きではない子供だった。そんな ＿＿＿ ★ ＿＿＿ ＿＿＿ きっかけだった。［1 ある先生との / 2 教師になりたいと思ったのは / 3 私が / 4 出会いが］",
    options:["ある先生との","教師になりたいと思ったのは","私が","出会いが"], answer:0,
    translation:"Tôi vốn là đứa trẻ ghét học, không thích trường. Cơ duyên khiến tôi muốn trở thành giáo viên chính là cuộc gặp gỡ với một thầy giáo.",
    explanation:"Thứ tự đúng: ③ 私が → ② 教師になりたいと思ったのは → ① ある先生との → ④ 出会いが. ★ = ① ある先生との → đáp án 1. （Bảng đáp án in trong file ghi ② cho câu này, nhưng theo cấu trúc câu thì ★ là ①.）" },
  { id:"f8-2", passage:"", audioUrl:"", question:"44. 若いときに努力して ＿＿＿ ＿＿＿ ★ ＿＿＿ なって必ず将来役に立つと思う。［1 経験は / 2 目標を / 3 自信と / 4 達成した］",
    options:["経験は","目標を","自信と","達成した"], answer:0,
    translation:"Tôi nghĩ kinh nghiệm nỗ lực và đạt được mục tiêu khi còn trẻ sẽ trở thành sự tự tin và chắc chắn có ích cho tương lai.",
    explanation:"Thứ tự đúng: ② 目標を → ④ 達成した → ① 経験は → ③ 自信と. ★ = ① 経験は → đáp án 1." },
  { id:"f8-3", passage:"", audioUrl:"", question:"45. この町では、都心で家を借りる ＿＿＿ ＿＿＿ ★ ＿＿＿ 家が借りられる。［1 場合 / 2 半分程度の / 3 家賃で / 4 と比べて］",
    options:["場合","半分程度の","家賃で","と比べて"], answer:1,
    translation:"Ở thị trấn này, so với việc thuê nhà ở trung tâm, có thể thuê nhà với giá chỉ bằng khoảng một nửa.",
    explanation:"Thứ tự đúng: ① 場合 → ④ と比べて → ② 半分程度の → ③ 家賃で. ★ = ② 半分程度の → đáp án 2." },
  { id:"f8-4", passage:"", audioUrl:"", question:"46. ＿＿＿ ＿＿＿ ★ ＿＿＿ 酸素や栄養が十分に細胞に届かなくなってしまう。［1 運ばれる / 2 悪くなると / 3 血液の流れが / 4 血液によって］",
    options:["運ばれる","悪くなると","血液の流れが","血液によって"], answer:3,
    translation:"Khi dòng chảy của máu trở nên xấu đi, oxy và dinh dưỡng được máu vận chuyển sẽ không đến được tế bào đầy đủ.",
    explanation:"Thứ tự đúng: ③ 血液の流れが → ② 悪くなると → ④ 血液によって → ① 運ばれる. ★ = ④ → đáp án 4." },
  { id:"f8-5", passage:"", audioUrl:"", question:"47. さくら駅周辺の再開発事業を行う ＿＿＿ ＿＿＿ ★ ＿＿＿ 予定だ。［1 さくら市は / 2 に先立って / 3 関係者に対する / 4 説明会を開催する］",
    options:["さくら市は","に先立って","関係者に対する","説明会を開催する"], answer:2,
    translation:"Trước khi tiến hành dự án tái phát triển quanh ga Sakura, thành phố Sakura dự định tổ chức buổi giải thích cho các bên liên quan.",
    explanation:"Thứ tự đúng: ② に先立って → ① さくら市は → ③ 関係者に対する → ④ 説明会を開催する. ★ = ③ → đáp án 3." }
]},
{ tab:"文法", section:"問題9 文章の文法 (điền vào đoạn văn)",
  instruction:"次の文章を読んで、文章全体の内容を考えて、48から51の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"f9-1", passage:"現代の人は座りすぎたとよく言われます。皆がずっと席に座ってパソコンで作業をしているという職場も珍しくないのではないでしょうか。座りすぎがさまざまな体の不調の原因になるという研究報告も【48】。座りすぎは、日本人の4人に1人が抱えているという腰の痛みの原因にもなると考えられています。<br><br>座っている姿勢は体にあまり負担がかかっていないと思うかもしれません。【49】、座り方によっては、実は立っているときの2倍もの負担が腰にかかるのだそうです。座っている時間が長くなるほど、腰への負担も大きくなり、それが腰痛につながります。かといって、ずっと立ったまま仕事をするというのも現実的ではありません。長時間立っていると、足に疲れがたまってしまうという問題もあります。大切なのは、【50】姿勢を長く続けないことです。理想は30分に一回、少なくとも1時間に一回は立って、少し動くのがいいとされています。<br><br>実際に、仕事中に時々立って動くようにしてみた人の多くが、腰痛の改善や疲れを感じにくいといった効果を感じているようです。座りっぱなしを避け、時々立って体を動かすことは、気軽にできる腰痛対策であり、仕事中の集中力維持にもつながります。職場で座っている時間が長い人は、【51】。",
    audioUrl:"", question:"48. 座りすぎがさまざまな体の不調の原因になるという研究報告も【48】。", options:["増えそうでした","増えてきました","増えていきました","増えたところでした"], answer:1,
    translation:"Người ta thường nói người hiện đại ngồi quá nhiều. Không hiếm nơi làm việc mà mọi người cứ ngồi suốt ngày làm việc trên máy tính. Các báo cáo nghiên cứu cho rằng ngồi nhiều là nguyên nhân gây nhiều chứng bất ổn cơ thể đang ngày càng tăng. Người ta cho rằng ngồi nhiều cũng là nguyên nhân gây đau lưng — chứng mà 1/4 người Nhật mắc phải.<br>Có thể bạn nghĩ tư thế ngồi không gây nhiều gánh nặng cho cơ thể. Nhưng thực tế, tuỳ cách ngồi, gánh nặng lên lưng có thể gấp đôi khi đứng. Ngồi càng lâu, gánh nặng lên lưng càng lớn và dẫn đến đau lưng. Tuy vậy, làm việc đứng suốt cũng không thực tế; đứng lâu sẽ tích mệt ở chân. Điều quan trọng là không giữ mãi một tư thế. Lý tưởng là cứ 30 phút, ít nhất 1 giờ đứng lên và vận động một chút.<br>Thực tế, nhiều người thử đứng lên vận động trong giờ làm đã cảm nhận được hiệu quả như giảm đau lưng, bớt mệt. Tránh ngồi lì, thỉnh thoảng đứng lên vận động là biện pháp chống đau lưng dễ làm và còn giúp duy trì tập trung khi làm việc. Những người ngồi nhiều ở nơi làm việc thì…",
    explanation:"【48】= ② 増えてきました: '(báo cáo) đang ngày càng tăng lên' — diễn tả xu hướng kéo dài đến hiện tại. 増えそうでした (có vẻ sẽ tăng), 増えていきました (đã tăng dần trong quá khứ), 増えたところでした (vừa mới tăng) không hợp." },
  { id:"f9-2", passage:"", audioUrl:"", question:"49. 座っている姿勢は体にあまり負担がかかっていないと思うかもしれません。【49】、座り方によっては、実は立っているときの2倍もの負担が腰にかかるのだそうです。", options:["つまり","しかも","ところが","というのは"], answer:2,
    translation:"(Xem bản dịch ở câu 48) / 'Tuy nhiên/Nhưng trái lại, tuỳ cách ngồi, gánh nặng lên lưng có thể gấp đôi khi đứng.'",
    explanation:"【49】= ③ ところが: 'thế nhưng' — nối hai ý tương phản (tưởng nhẹ nhưng thực ra nặng gấp đôi). つまり (nghĩa là), しかも (hơn nữa), というのは (là vì) không hợp." },
  { id:"f9-3", passage:"", audioUrl:"", question:"50. 大切なのは、【50】姿勢を長く続けないことです。", options:["同じ","違う","この","以下の"], answer:0,
    translation:"(Xem bản dịch ở câu 48) / 'Điều quan trọng là không giữ mãi MỘT tư thế trong thời gian dài.'",
    explanation:"【50】= ① 同じ: 'cùng một (tư thế)'. 同じ姿勢を長く続けない ✓. 違う/この/以下の không tạo nghĩa đúng." },
  { id:"f9-4", passage:"", audioUrl:"", question:"51. 職場で座っている時間が長い人は、【51】。", options:["試してみてもいいですか","試してみたらいいのでしょうか","試してみればよかったですか","試してはいかがでしょうか"], answer:3,
    translation:"(Xem bản dịch ở câu 48) / 'Những người ngồi nhiều ở nơi làm việc — hãy thử xem sao?'",
    explanation:"【51】= ④ 試してはいかがでしょうか: 'hãy thử… thì thế nào?' — lời khuyên/đề nghị ở cuối bài. Các phương án hỏi lại/tiếc nuối không hợp văn phong." }
]},
/* ================= TAB 4: 読解 ================= */
{ tab:"読解", section:"問題10 内容理解・短文",
  instruction:"次の(1)から(5)の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"g10-1", passage:"恐怖、恥ずかしい、淋しい、腹が立つ、などなどは、不快な感情ではありますが、単に取り除かればよいもの、存在しなければよいものではありません。それらが一切存在しない理想の人生があると考えるのは間違いで、それらには存在する理由があるのです。どんなに恵まれた人生でも、恐いことはありますし、恥ずかしいこと、淋しいこと、腹が立つことはあります。むしろそういう感情があることが豊かな人生だとさえ言えます。",
    audioUrl:"", question:"52. 筆者の考えに合うのはどれか。",
    options:["不快な感情を持てば持つほど、人生はより豊かになる","不快な感情を取り除ければ、理想の人生が送れる","不快な感情が存在する理由を考えることで、人生は豊かになる","不快な感情があるからこそ、人生は豊かになる"], answer:3,
    translation:"Sợ hãi, xấu hổ, cô đơn, tức giận… đều là những cảm xúc khó chịu, nhưng không phải là thứ chỉ cần loại bỏ hay không nên tồn tại. Nghĩ rằng có một cuộc đời lý tưởng không có chút cảm xúc nào như thế là sai, vì chúng có lý do để tồn tại. Dù cuộc đời may mắn đến đâu vẫn có điều đáng sợ, đáng xấu hổ, cô đơn, tức giận. Trái lại, có thể nói chính vì có những cảm xúc ấy mà cuộc đời mới phong phú.",
    explanation:"Đáp án 4. Câu cuối khẳng định 'chính vì có những cảm xúc ấy mà cuộc đời phong phú' ⇒ 不快な感情があるからこそ人生は豊か. Phương án 1 sai (bài không nói 'càng nhiều càng tốt'), 2 ngược với bài, 3 sai (bài không nói 'suy nghĩ về lý do' mới làm cuộc đời phong phú)." },
  { id:"g10-2", passage:"（山森大学ホームページのお知らせ）<br><b>移転作業に伴うパソコン自習室の利用について</b><br>先日お知らせしたように、キャンパスの整備にあたり、現在2号館のパソコン自習室が4号館に移転します。移転作業に伴い、利用が9月5日までになるとお知らせしましたが、工事期間の変更により8月31日に閉室することになりました。移転先の利用開始は10月1日で変更ありません。<br>移転が完了するまでは、6号館のパソコン自習室、および図書館の情報検索室をご利用ください。",
    audioUrl:"", question:"53. このお知らせで伝えたいことは何か。",
    options:["9月5日から2号館のパソコン自習室が利用できなくなること","10月1日から6号館のパソコン自習室が利用できること","2号館のパソコン自習室の閉室日が早まったこと","4号館のパソコン自習室の利用開始日が早まったこと"], answer:2,
    translation:"(Thông báo trên trang chủ ĐH Yamamori) Về việc sử dụng phòng tự học máy tính kèm theo công tác di dời: Như đã thông báo, phòng tự học máy tính ở toà nhà số 2 sẽ chuyển sang toà nhà số 4. Ban đầu thông báo có thể dùng đến 5/9, nhưng do thay đổi thời gian thi công nên sẽ đóng phòng vào 31/8. Ngày bắt đầu sử dụng ở nơi mới vẫn là 1/10. Trong thời gian chờ hoàn tất di dời, xin dùng phòng tự học toà nhà số 6 và phòng tra cứu thông tin của thư viện.",
    explanation:"Đáp án 3. Trọng tâm thông báo: ngày đóng cửa phòng tự học toà nhà số 2 bị đẩy sớm lên (từ 5/9 → 31/8)." },
  { id:"g10-3", passage:"（金魚の飼い方）水温が下がると消化機能も低下するので、エサをあまり多く与えると消化不良を起こして体調をくずしてしまいます。屋内の水槽で飼育している場合でも、水温が10度以下になると金魚の動きは鈍くなり、えさもあまりほしがらなくなります。ヒーターを入れて、飼育水の温度を18～20度に保てば、金魚は活発に泳いでえさもよく食べるようになり、一年じゅう元気な金魚と接することができます。",
    audioUrl:"", question:"54. 金魚の飼い方について、筆者の説明に合うのはどれか。",
    options:["えさの量を適切に調整すれば、金魚は活発に泳ぐ。","屋内より屋外で飼ったほうが、金魚はえさをよく食べる。","水温を適切にしておけば、金魚はえさをよく食べる。","水温とえさの量を一定に保てば、金魚は活発に泳ぐ。"], answer:2,
    translation:"(Cách nuôi cá vàng) Khi nhiệt độ nước giảm thì chức năng tiêu hoá cũng giảm, nên cho ăn quá nhiều sẽ gây khó tiêu và cá yếu. Ngay cả khi nuôi trong bể trong nhà, nếu nước xuống dưới 10 độ cá vàng sẽ lờ đờ và không muốn ăn. Nếu dùng máy sưởi giữ nước ở 18–20 độ thì cá vàng sẽ bơi linh hoạt, ăn khoẻ, quanh năm khoẻ mạnh.",
    explanation:"Đáp án 3. Bài khẳng định: giữ nhiệt độ nước 18–20 độ ⇒ cá bơi khoẻ và ăn tốt. Phương án 1, 4 nói về lượng thức ăn là nguyên nhân chính (bài không nói vậy), 2 không được đề cập." },
  { id:"g10-4", passage:"（社員が受け取ったメール）<br>営業課 高原様 —— 企画課の山下です。部長から発表がありましたとおり、12日から新モデル発売に向けての営業課・企画課合同の会議を始めます。12日は初回となりますので、営業課では旧モデルの売り上げについての資料をご準備ください。昨年度分だけでなく、販売開始以降のものすべてをお願いします。初回の会議では、まずこちらから新モデルの概要と今後のスケジュール案を示しご説明しますので、営業課の皆さんのご意見をお聞かせください。",
    audioUrl:"", question:"55. 高原さんは、初回の会議までに何をしなければならないか。",
    options:["旧モデルのこれまでの販売実績が分かる資料を作成する。","旧モデルと新モデルの相違点をまとめた資料を作成する。","新モデルの概要と今後のスケジュール案を作成する。","企画課が作成したスケジュール案について、営業課の意見をまとめる。"], answer:0,
    translation:"Kính gửi anh Takahara phòng Kinh doanh — Tôi là Yamashita phòng Kế hoạch. Như trưởng phòng đã thông báo, từ ngày 12 chúng ta bắt đầu cuộc họp liên phòng Kinh doanh – Kế hoạch cho việc ra mắt model mới. Ngày 12 là buổi đầu nên phòng Kinh doanh hãy chuẩn bị tài liệu về doanh số của model cũ — không chỉ năm ngoái mà tất cả số liệu từ khi bắt đầu bán. Trong buổi đầu, phía chúng tôi sẽ trình bày tổng quan model mới và dự thảo lịch trình, xin các anh chị phòng Kinh doanh cho ý kiến.",
    explanation:"Đáp án 1. Mail yêu cầu phòng Kinh doanh chuẩn bị 'tài liệu về doanh số model cũ từ khi bắt đầu bán đến nay'." },
  { id:"g10-5", passage:"自分がのめりこんだことが、仕事として成立したなら、これほど楽しいことはないだろう。もしいたしたらその感覚は、世の中の常識とは順番が逆なのかもしれない。本来はまず仕事ありきなのだろう。与えられた仕事をどう楽しめるかと考えるのがふつうなのかもしれない。でも仕事がただ与えられるだけのものだったら、やっぱり面白くするにも限界がある。自分が何を面白いと感じるか。まずそれありきで仕事を考えた方がいいと思うのだ。",
    audioUrl:"", question:"56. 筆者が言いたいことは何か。",
    options:["与えられた仕事を楽しむことが大切だ。","興味のあることを仕事にするのがいい。","面白い仕事を与えられることが重要だ。","どんな仕事でも続けていれば楽しくなる。"], answer:1,
    translation:"Nếu điều mình say mê lại trở thành công việc thì không gì vui hơn. Nếu vậy, cảm giác ấy có thể ngược với thứ tự thông thường của xã hội: lẽ thường là công việc phải có trước, và ta nghĩ cách để thấy vui với công việc được giao. Nhưng nếu công việc chỉ là thứ được giao thì việc làm cho nó thú vị cũng có giới hạn. Mình thấy điều gì thú vị — nên lấy đó làm tiền đề để nghĩ về công việc.",
    explanation:"Đáp án 2. Câu chốt: 'nên lấy điều mình thấy thú vị làm tiền đề để nghĩ về công việc' ⇒ biến điều mình hứng thú thành công việc." }
]},
{ tab:"読解", section:"問題11 内容理解・中文",
  instruction:"次の(1)から(4)の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"g11-1", passage:"（スポーツの指導者に向けた文章）物事は、タイミングがすべてです。同じことを伝えるにしても、タイミングによって効果が変わります。まず、初めて会った時の相手に与える印象に気をつけましょう。相手に自分の第一印象を与えるチャンスは最初の一回だけです。話す相手が誰であろうと、あなたのメッセージの中で最初の一分が一番重要なのです。初めて指導する参加者に会うことがわかっているときには、最初に何を話すのかをよく考えて計画することはとても効果的です。<br><br>また、メッセージは即座に送ることです。しかし問題が起こって、自分が感情的になり、生産的にメッセージを伝えられないと判断したときは、少し間を置く必要もあるでしょう。大事な試合を落とした直後は選手も興奮、落胆などさまざまな感情が入り交じっていて、生産的な話し合いは不可能なので、一日おいて話す方がよいでしょう。",
    audioUrl:"", question:"57. 筆者によると、初めて選手に会うときに大切なことは何か。",
    options:["指導の計画を立てておく。","最初に話すことを考えておく。","相手のことをよく調べておく。","一分で話せるように準備しておく。"], answer:1,
    translation:"(Dành cho huấn luyện viên thể thao) Mọi việc đều nằm ở thời điểm. Cùng một thông điệp, hiệu quả thay đổi theo thời điểm. Trước hết hãy chú ý ấn tượng mình tạo ra khi gặp người khác lần đầu — cơ hội tạo ấn tượng ban đầu chỉ có một lần. Dù nói với ai, một phút đầu tiên trong thông điệp của bạn là quan trọng nhất. Khi biết trước sẽ gặp người mới, việc suy nghĩ kỹ và lên kế hoạch nói gì trước là rất hiệu quả.<br>Ngoài ra, thông điệp nên gửi ngay. Nhưng khi có vấn đề, bản thân xúc động và không thể truyền đạt hiệu quả thì cần chờ một chút. Ngay sau khi thua trận quan trọng, vận động viên đang lẫn lộn nhiều cảm xúc nên không thể thảo luận hiệu quả; tốt hơn là để một ngày rồi nói.",
    explanation:"Đáp án 2. Bài nói: khi biết sẽ gặp học viên mới, 'suy nghĩ kỹ sẽ nói gì trước' là rất hiệu quả ⇒ 最初に話すことを考えておく." },
  { id:"g11-2", passage:"", audioUrl:"", question:"58. 筆者によると、選手が大事な試合に負けた時は、指導者はどうしたらよいのか。",
    options:["選手に役立つメッセージをすぐに伝える。","選手を批判せず、感情を受け入れてなぐさめる。","時間をあけてから、選手と話し合いをする。","その場で問題点を指摘したあと、選手自身に考えさせる。"], answer:2,
    translation:"(Xem bản dịch ở câu 57)",
    explanation:"Đáp án 3. Bài nói: sau trận thua quan trọng, nên '一日おいて話す' → chờ một thời gian rồi mới trao đổi." },
  { id:"g11-3", passage:"（読書感想文について）小中学校時代、私はかなりな読書家だった。しかし、さあ読書感想文を書けと言われても、いっこうに書けない。つい先日、その永年の疑問が氷解した。私は、読書感想文が書けるような本を読んでいなかったのだ。私が主に読んでいたのは、汽車の時刻表、地図帳、人名事典、旅行案内、百科事典、美術写真集、植物図鑑などの類である。<br><br>世の中には、読むための本と、調べるための本がある。読むための本は最初から最後まで読まなければならない。たいてい、一人の人間が最初から最後まで書いている。一度退屈したら、挫折するしかない。小説や読み物はそのようなものだ。そうして、それが読書感想文の扱える典型的な本なのだ。",
    audioUrl:"", question:"59. 筆者によると、読書感想文が書ける本とはどのような本か。",
    options:["子どもには理解するのが難しい本","子供でも退屈しないで読める本","最後まで読む必要がある本","疑問を解決してくれる本"], answer:2,
    translation:"Hồi tiểu học/trung học, tôi khá mê đọc sách. Vậy mà khi bảo viết cảm nhận về sách thì tôi hoàn toàn không viết được. Mới gần đây, nghi vấn bao năm ấy được giải đáp: tôi chưa từng đọc loại sách có thể viết cảm nhận. Tôi chủ yếu đọc thời gian biểu tàu hoả, tập bản đồ, từ điển nhân danh, cẩm nang du lịch, bách khoa toàn thư, sách ảnh mỹ thuật, giám định thực vật…<br>Trên đời có sách để ĐỌC và sách để TRA CỨU. Sách để đọc phải đọc từ đầu đến cuối, thường do một người viết trọn vẹn; một lần thấy nhàm chán là chỉ còn cách bỏ. Tiểu thuyết, truyện đọc là như vậy — và đó mới là loại sách điển hình có thể viết cảm nhận.",
    explanation:"Đáp án 3. Bài nói sách để viết cảm nhận là 'sách để đọc', phải đọc từ đầu đến cuối ⇒ 最後まで読む必要がある本." },
  { id:"g11-4", passage:"", audioUrl:"", question:"60. 子どもと読書について、筆者の考えに合うのはどれか。",
    options:["本の種類に関係なく、興味のある本を読めばいい。","読みたくなければ、無理に本を読まなくてもいい。","できるだけ多くの種類の本を読んだほうがいい。","最初は読み物よりもカタログなどを読めばいい。"], answer:0,
    translation:"(Xem bản dịch ở câu 59) / Đoạn cuối bài: nhiều trẻ bị coi là ghét đọc; cha mẹ cố mua truyện cho con, nhưng cũng có đứa thấy truyện nhàm chán; dù vậy chúng có thể thích catalogue khủng long hay sách bài hát. 'Điều quan trọng là thân thiết với những thứ có hình dạng cuốn sách.'",
    explanation:"Đáp án 1. Ý tác giả: quan trọng là trẻ thân thiết với 'thứ có hình dạng cuốn sách' — không nhất thiết cứ phải là truyện ⇒ 本の種類に関係なく、興味のある本を読めばいい." },
  { id:"g11-5", passage:"（映像作品について）映像作品においては、作者が意識していることや認識していることが、見る者に必ずそのまま伝達されるわけではない。会話のような双方向的なやりとりであれば、理解できなかった場合には質問が戻ってくる。ところが映像による表現は、印刷物と同じく、基本的に一方向的な伝達である。ゆえに映像の作者は、目の前にいない受け手がどのように理解するかを考えて制作を行う必要がある。<br><br>作者は自らの思考や意志のもとに作品を加工していくが、あつかう内容を作者自身は十分に知っているため、説明の不足や整理の不十分さに気づかない場合がある。この問題を解決するためには、見る者はなにも知らない状態で見ているという認識を、作者はもつべきである。<br><br>しかし相手がなにも知らないからといって、すべて説明しなければならないわけでもない。細かすぎる地図が必ずしもわかりやすい地図ではないのと同じで、必要なことだけ整理して伝えるべきなのだ。",
    audioUrl:"", question:"61. 筆者によると、映像作品の作者はどのような姿勢で作品を作らなければならないか。",
    options:["会話のように見る者とのやりとりを意識する。","見るものが楽しめる内容をあつかうようにする。","見る者が自分と同じ思考をもてるようにする。","見る者がなにも知らないことを前提にする。"], answer:3,
    translation:"Trong tác phẩm hình ảnh, điều tác giả ý thức/nhận biết không nhất thiết được truyền đạt nguyên vẹn đến người xem. Nếu là trao đổi hai chiều như hội thoại, khi người nghe không hiểu sẽ hỏi lại; nhưng thể hiện bằng hình ảnh cơ bản là truyền đạt một chiều, giống như ấn phẩm. Vì vậy tác giả phải suy nghĩ xem người nhận — không ở trước mặt — sẽ hiểu thế nào để làm tác phẩm.<br>Tác giả chỉnh sửa tác phẩm theo tư duy/ý chí của mình, nhưng vì bản thân đã hiểu quá rõ nội dung nên có khi không nhận ra sự thiếu giải thích hay sắp xếp thiếu. Để giải quyết vấn đề này, tác giả cần nhận thức rằng người xem đang xem trong trạng thái không biết gì.<br>Tuy nhiên không phải vì đối phương không biết gì mà phải giải thích tất cả. Giống như bản đồ quá chi tiết chưa chắc đã dễ hiểu, chỉ nên sắp xếp và truyền đạt những điều cần thiết.",
    explanation:"Đáp án 4. Bài nói rõ: tác giả nên có nhận thức 'người xem đang xem trong trạng thái không biết gì' ⇒ lấy đó làm tiền đề khi làm tác phẩm." },
  { id:"g11-6", passage:"", audioUrl:"", question:"62. 筆者によると、映像作品の制作で目指すことと、上手に話をすることの似ている点はなにか。",
    options:["すべてを説明するのではなく、必要な情報を整理して伝えること","相手が知らない多くの情報を、できるだけ整理して伝えること","わかりやすくするだけではなく、内容を詳しく伝えること","言葉の意味に注意を払うよりも、順番を考えて伝えること"], answer:0,
    translation:"(Xem bản dịch ở câu 61)",
    explanation:"Đáp án 1. Đoạn cuối: 'giống như khi muốn nói giỏi thì chọn từ và nghĩ thứ tự câu chuyện' ⇒ cần sắp xếp và truyền đạt chỉ những thông tin cần thiết." },
  { id:"g11-7", passage:"（夢について）そもそも大人が「夢」を子どもに問うとき、「高い目標に向かって突き進め。そして必ず成功しろ」という期待を押しつけている感じがします。「夢＝成功すること」になってしまっている。そういう大人の意図を、子どもは敏感に察知します。<br><br>本来、「夢」という言葉は、もっと広い意味のはず。「職業」だけでなく、「どんな人間になりたいか」「どんな暮らしをしたいか」という願いも含んでいます。そのほうがずっと具体的で、その子が今持っている思いや願いや時には悩みを含んでいることだってあります。<br><br>「夢は何？」という問いへの子どもの答えにもっと耳を傾け、深く掘り下げて語り合いましょう。子どもが語る「夢」に含まれる小さなつぶやきや、表に出てきづらい願いを、無視しないでください。親子で夢について深く語り合うことで、子どもの気持ちがよくわかってきます。",
    audioUrl:"", question:"63. 大人が子どもに夢を問うときの問題点について、筆者はどのように述べているか。",
    options:["大人がいいと考える目標を求めがちだ。","大人でも実現できない目標を求めがちだ。","子どもが思いつかない目標を求めがちだ。","子どもが興味を示さない目標を求めがちだ。"], answer:0,
    translation:"Vốn dĩ khi người lớn hỏi trẻ 'ước mơ của con là gì', có cảm giác họ đang áp đặt kỳ vọng 'hãy lao tới mục tiêu cao và nhất định phải thành công' — 'ước mơ = thành công'. Trẻ nhạy bén nhận ra ý đồ đó của người lớn.<br>Đáng lẽ 'ước mơ' phải rộng hơn: không chỉ 'nghề nghiệp' mà còn 'muốn trở thành con người thế nào', 'muốn sống ra sao'. Như thế cụ thể hơn nhiều, và đôi khi chứa cả nỗi lo hiện tại của đứa trẻ.<br>Hãy lắng nghe và đào sâu hơn câu trả lời của trẻ; đừng bỏ qua những lời lẩm bẩm nhỏ hay mong muốn khó nói. Trò chuyện sâu với con về ước mơ giúp hiểu rõ tình cảm của con.",
    explanation:"Đáp án 1. Vấn đề: người lớn áp đặt kỳ vọng theo mục tiêu mà NGƯỜI LỚN cho là tốt (thành công, mục tiêu cao) ⇒ 大人がいいと考える目標を求めがち." },
  { id:"g11-8", passage:"", audioUrl:"", question:"64. 筆者が最も言いたいことは何か。",
    options:["大人は子どもに夢とは何かを伝えることが必要だ。","大人は子どもに夢の実現のしかたを教えてあげることが大切だ。","大人は子どもの夢に含まれる思いを理解することが大切だ。","大人は夢を語り合う前に、子どもの不安を取り除くことが必要だ。"], answer:2,
    translation:"(Xem bản dịch ở câu 63)",
    explanation:"Đáp án 3. Câu chốt: hãy đọc/đào sâu những suy nghĩ, nguyện vọng đằng sau câu trả lời của trẻ ⇒ 大人は子どもの夢に含まれる思いを理解することが大切." }
]},
{ tab:"読解", section:"問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction:"次のAとBの文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"g12-1", passage:"【A】面接や発表などで、緊張を恐れるあまり、ますます緊張してしまう人がいる。適度に緊張している状態は、集中力を高める効果があるので、緊張を無くそうとする必要はない。それより、緊張している状態でも自分の力を出せるようにしたほうがいい。緊張しているときに大事なのは、うまくできた状況を思い描くことだ。繰り返しイメージすることで、実際にうまくできるように思えてくる。失敗したときのことを考えるのは、緊張が増すだけだからやめたほうがいい。<br><br>【B】面接や発表などの際は、なぜ緊張するのだろうか。それは「能力があるように見られたい」という思いが強すぎることが大きな原因だ。他人によい姿を見せたいと思っていると、失敗するのが怖くなり緊張してしまう。できるだけ緊張しないようにするには、他人を意識しないことが大事だ。自分をよく見せることではなく、伝えたいことをきちんと伝えることに意識を向ければ、気持ちが落ちついてくる。また、よく緊張してはいけないと思う人がいるが、緊張している姿から真剣さが伝わり、逆に好印象を与えることがある。だから、緊張を恐れなくてもいい。",
    audioUrl:"", question:"65. 緊張することについて、AとBが共通して述べていることは何か。",
    options:["緊張するのは悪いことではない。","緊張しない方法を考えても意味がない。","緊張しているほうが自分の力が出せる。","失敗を防ぐには、できるだけ緊張しないほうがいい。"], answer:0,
    translation:"【A】Trong phỏng vấn hay thuyết trình, có người vì quá sợ hồi hộp mà càng hồi hộp. Căng thẳng vừa phải có tác dụng nâng cao tập trung nên không cần loại bỏ nó; thay vào đó hãy để bản thân phát huy thực lực ngay cả khi hồi hộp. Điều quan trọng khi hồi hộp là hình dung tình huống mình làm tốt; lặp lại hình ảnh đó sẽ thấy như mình làm được. Nghĩ đến lúc thất bại chỉ làm tăng căng thẳng nên bỏ.<br>【B】Vì sao lại hồi hộp? Nguyên nhân lớn là ham muốn 'trông có năng lực' quá mạnh. Muốn cho người khác thấy mình tốt thì sợ thất bại mà hồi hộp. Để bớt hồi hộp, đừng để ý đến người khác; hướng ý thức vào việc truyền đạt điều muốn nói thay vì phô diễn bản thân. Ngoài ra, hình ảnh hồi hộp lại truyền tải sự nghiêm túc, có khi gây ấn tượng tốt; nên không cần sợ hồi hộp.",
    explanation:"Đáp án 1. A: 'không cần loại bỏ căng thẳng' (vì nó nâng cao tập trung); B: 'hồi hộp có khi gây ấn tượng tốt, không cần sợ' ⇒ cả hai đều cho rằng hồi hộp không phải điều xấu." },
  { id:"g12-2", passage:"", audioUrl:"", question:"66. AとBは、緊張していると感じたときに、どうしたらいいと述べているか。",
    options:["AもBも、できるだけ結果のことを考えないようにしたほうがいいと述べている。","AもBも、必要以上に格好をつけようと思うのをやめたほうがいいと述べている。","Aは失敗した状況をイメージしないほうがいいと述べ、Bは自分がなぜ緊張しているのか考えたほうがいいと述べている。","Aは成功した自分を想像したほうがいいと述べ、Bは自分をよく見せようと考えるのをやめたほうがいいと述べている。"], answer:3,
    translation:"(Xem bản dịch ở câu 65)",
    explanation:"Đáp án 4. A: nên hình dung tình huống mình làm tốt/ thành công; B: đừng cố phô diễn bản thân, hãy tập trung vào việc truyền đạt." }
]},
{ tab:"読解", section:"問題13 主張理解・長文",
  instruction:"次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"g13-1", passage:"決断力がないと、いつも誰かの指示や命令に黙って従って生きていくしかない。そんな人生は誰も望まないだろう。若いうちは人の上に立つ機会は少ないが、決断力のある人をよく観察して、「なるほど、ああいうふうにすればいいのか」などと参考にしたほうがいい。とにかく早くから決断するクセをつけておくことだ。<br><br>どうやって決断力を磨くか。これは難しい問題のようだが、実は簡単で、決断力とは「決断すればいい」だけのこと。要は決断の勇気があるかどうかなのである。たとえば、「行く」「行かない」「断る」など、すべてその場で決める勇気なのだ。<br><br>このことを理解するためには、逆に、なかなか決断できない人を考えてみればいい。決断しなければならない場面で決断できない人は、何を考えているのだろうか。「行く」か「行かない」かを決断するときに、その見通しをつけたいと思っているのだ。行けばどうなるか、行かないとどうか。つまり「正しい決断をしたい」と思っているのだ。だが、この気持ちこそが決断を遅らせる最大の原因である。<br><br>（中略）わからないことをわかろうと無理する必要はない。エイヤッと決めてしまえばそれですむ。哲学者のアミエルは「決心する前に、完全な見通しをつけようとする者は、決心することができない」といっている。決断で大切なことは、さっさと自分で決断することのみである。<br><br>A社かB社かで悩んだ就活生がB社を選んだとする。三年で退職する羽目になった。すると「A社にしておけばよかった」と思うだろう。だが、A社を選んで同じ結果が出れば「B社にすればよかった」と思うに決まっている。どっちを選んでも後悔しているのだ。うまくいかなかった原因は決断にあったのではなく、その後のやり方が悪かったからだ。決断ですべてが決まるわけではない。決断した後の考え方や行動が大切。だが、決断しないことには何事もはじまらない。何がいけないといって、決断すべきときに決断しないのがいちばんいけない。",
    audioUrl:"", question:"67. なかなか決断できない人とあるが、なぜ決断できないのか。",
    options:["自分が正しい決断ができるとは思えないから","一度決断したら変えられないと思って迷うから","その場で決断すべきことかどうかわからないから","間違った決断をしたくないと思って考えすぎるから"], answer:3,
    translation:"Không có khả năng quyết đoán thì chỉ còn cách im lặng tuân theo chỉ thị, mệnh lệnh của người khác. Không ai mong cuộc đời như thế. Khi còn trẻ ít có cơ hội đứng trên người khác, nhưng nên quan sát người quyết đoán để tham khảo. Hãy tập thói quen quyết định sớm.<br>Luyện khả năng quyết đoán thế nào? Nghe khó nhưng thực ra đơn giản: chỉ cần 'quyết định'. Cốt lõi là có dũng khí quyết định — quyết ngay tại chỗ 'đi', 'không đi', 'từ chối'…<br>Ngược lại, hãy xét người khó quyết định: khi phải quyết 'đi hay không đi', họ muốn thấy trước kết quả, tức muốn 'quyết định cho đúng'. Nhưng chính điều này là nguyên nhân lớn nhất khiến quyết định bị trì hoãn.<br>Không cần cố hiểu điều không thể hiểu. Cứ liều quyết một cái là xong. Nhà triết học Amiel nói: 'Kẻ muốn có cái nhìn toàn vẹn trước khi quyết tâm thì không thể quyết tâm'. Điều quan trọng là mau chóng tự quyết.<br>Một sinh viên tìm việc phân vân giữa công ty A và B, chọn B rồi phải nghỉ việc sau 3 năm; ắt sẽ nghĩ 'giá mà chọn A'. Nhưng chọn A mà kết quả cũng vậy thì lại nghĩ 'giá mà chọn B'. Chọn bên nào cũng hối tiếc. Nguyên nhân không nằm ở quyết định mà ở cách xử lý sau đó. Quyết định không quyết định tất cả; cách nghĩ và hành động sau khi quyết mới quan trọng. Nhưng không quyết thì không gì bắt đầu. Điều tệ nhất là không quyết khi cần quyết.",
    explanation:"Đáp án 4. Bài nói người khó quyết định 'muốn quyết cho đúng', muốn thấy trước kết quả ⇒ vì không muốn quyết sai mà suy nghĩ quá nhiều." },
  { id:"g13-2", passage:"", audioUrl:"", question:"68. 就活生の例を挙げて、筆者が問題だと述べていることは何か。",
    options:["人の意見を聞いて決断すればよかったと思うこと","悪い結果になったとき、それを認めようとしないこと","決断を間違えたせいで悪い結果になったと思うこと","決断は正しかったにもかかわらず、後悔をしていること"], answer:1,
    translation:"(Xem bản dịch ở câu 67)",
    explanation:"Đáp án 2. Tác giả nêu ví dụ để chỉ ra điều đáng nói: dù chọn bên nào cũng đổ lỗi/hối tiếc cho quyết định, không nhìn nhận đúng nguyên nhân (cách xử lý sau đó) ⇒ không thừa nhận vấn đề thực sự (đáp án theo bảng đáp án trong file: ②)." },
  { id:"g13-3", passage:"", audioUrl:"", question:"69. この文章で筆者が言いたいことは何か。",
    options:["必要なときに決断したうえで、どのように対応するかが重要だ。","決断する前に、うまくいかなかった場合の対応を考えておくべきだ。","正しい決断ができるようになるには、決断するという経験を積むべきだ。","どんな結果になっても後悔しないように、よく考えて決断することが重要だ。"], answer:3,
    translation:"(Xem bản dịch ở câu 67)",
    explanation:"Đáp án 4 (theo bảng đáp án trong file). Nội dung bài nhấn mạnh: đừng trì hoãn vì sợ quyết sai, hãy quyết và không hối tiếc về quyết định; điều tệ nhất là không quyết khi cần quyết." }
]},
{ tab:"読解", section:"問題14 情報検索",
  instruction:"右のページは、あるテニススクールの入会案内である。下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"g14-1", passage:"<b>秋原テニススクール 入会案内</b><br><b>コース・クラス</b>（中学生以上受講可／1クラス定員10名／レッスン60分）<br><table class='info-tbl'><tr><th>コース</th><th>受講料（週1回・1か月分）</th></tr><tr><td>A. 平日昼間（初心者）</td><td>8,800円</td></tr><tr><td>B. 平日昼間（中・上級者）</td><td>12,000円</td></tr><tr><td>C. 平日夜間・土日（初心者）</td><td>9,300円</td></tr><tr><td>D. 平日夜間・土日（中・上級者）</td><td>12,500円</td></tr></table><br><b>入会時のお支払い</b>：入会金（6,600円）、年会費（2,200円）、受講料1ヶ月分を現金で。<br><br><b>割引制度</b>（複数の割引は同時に適用できず、いちばん条件のいい割引が一つ適用）<br>・学生割引：中学生・高校生 → 毎月の受講料を10%割引<br>・複数コース・クラス割引：複数受講 → 二つ目以降のコース・クラスの毎月の受講料を50%割引<br>・家族割引：ご家族に本スクールの受講生がいる方 → 入会金無料、毎月の受講料を15%割引<br><br><b>各種手続き</b>（変更＝変更したい月の前月10日まで／退会＝最終受講の前月月末まで／休会＝休会したい月の前月20日まで）※手数料550円（入会後3ヶ月以内は無料）",
    audioUrl:"", question:"70. 高校生の村田さんは「C.平日夜間・土日（初心者）コース」に入会したいと思っている。姉がすでに同じコースを受講しているが、入会時に支払うものは何か。",
    options:["入会金、年会費、10%割引された受講料。","入会金、年会費、15%割引された受講料。","年会費、15%割引された受講料。","年会費、50%割引された受講料。"], answer:2,
    translation:"(Bảng hướng dẫn nhập học trường quần vợt Akihara) 4 khoá học với học phí tháng (1 buổi/tuần); lớp tối đa 10 người, 60 phút. Khi nhập học trả: phí nhập học 6.600 yên, phí thường niên 2.200 yên, học phí 1 tháng bằng tiền mặt (từ tháng thứ 2 trừ qua tài khoản). Giảm giá (không dùng đồng thời, chỉ áp dụng 1 loại có lợi nhất): giảm học sinh 10% (THCS/THPT); giảm học nhiều khoá 50% cho khoá thứ 2 trở đi; giảm gia đình (có người thân đang học) → miễn phí nhập học + giảm 15% học phí tháng. Thủ tục: đổi khoá/lớp trước ngày 10 tháng trước; nghỉ hẳn trước cuối tháng trước buổi cuối; tạm nghỉ trước ngày 20 tháng trước. Phí thủ tục 550 yên (miễn phí nếu trong 3 tháng đầu).",
    explanation:"Đáp án 3. Murata (học sinh cấp 3) hội đủ cả 学生割引 (10%) và 家族割引 (15% + miễn phí nhập học) nhưng quy định chỉ áp dụng MỘT loại có lợi nhất ⇒ chọn 家族割引: miễn 入会金, vẫn trả 年会費, học phí giảm 15%." },
  { id:"g14-2", passage:"", audioUrl:"", question:"71. リナさんは、このテニススクールに1か月前に入会し、現在「B.平日昼間（中・上級者）コース」を受講している。5月から「D.平日夜間・土日（中・上級者）コース」に変わりたいと思っているが、リナさんはどうしなければならないか。今日は3月15日である。",
    options:["4月10日までに、手数料550円を支払い、手続きをする。","4月10日までに手続きをする。手数料は必要ない。","4月20日までに、手数料550円を支払い、手続きをする。","4月20日までに手続きをする。手数料は必要ない。"], answer:1,
    translation:"(Bảng hướng dẫn: xem câu 70)",
    explanation:"Đáp án 2. Đổi khoá ⇒ hạn là ngày 10 của tháng trước tháng muốn đổi: muốn đổi từ tháng 5 ⇒ hạn 10/4 ✓. Rina nhập học 1 tháng trước (trong vòng 3 tháng) ⇒ miễn phí thủ tục 550 yên ✓" }
]},
/* ================= TAB 5: 聴解 ================= */
{ tab:"聴解", section:"問題1 課題理解",
  instruction:"まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File đề không có audio/transcript — chỉ có phần in trên giấy + đáp án theo bảng đáp án.)",
  questions:[
  { id:"h1-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe; chỉ có các lựa chọn in trên giấy.", audioUrl:"", question:"1番", options:["出発時間のへんこうをバス会社に伝える","コーチに集合時間を伝える","着く時間をペンションに伝える","クラブのみんなに持ち物を伝える"], answer:2,
    translation:"Không thể dịch nghĩa đầy đủ do thiếu nội dung audio (đề không có transcript).",
    explanation:"Đáp án theo bảng đáp án trong file: ③ 着く時間をペンションに伝える. ⚠️ THIẾU DỮ LIỆU TRONG FILE (phần bài nghe)." },
  { id:"h1-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: phần lựa chọn là hình ảnh minh hoạ, không có nội dung chữ & không có audio.", audioUrl:"", question:"2番", options:["① (hình minh hoạ trong file)","② (hình minh hoạ trong file)","③ (hình minh hoạ trong file)","④ (hình minh hoạ trong file)"], answer:0,
    translation:"Không thể dịch do thiếu nội dung audio và hình ảnh bị mất trong file.",
    explanation:"Đáp án theo bảng đáp án trong file: ①. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h1-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"3番", options:["ターゲットをする時代","箱のデザイン","設定価格","発売する時期"], answer:1,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ② 箱のデザイン. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h1-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"4番", options:["ケースをそうじする回数を増やす","ケースに入れる貝を増やす","ケースに入れるえさを減らす","ケースを移動する"], answer:3,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ④ ケースを移動する. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h1-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"5番", options:["かんい説明書の文字を大きくする","かんい説明書の内容を減らす","動画を短くまとめる","動画にじまくをつける"], answer:1,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ② かんい説明書の内容を減らす. ⚠️ THIẾU DỮ LIỆU TRONG FILE." }
]},
{ tab:"聴解", section:"問題2 ポイント理解",
  instruction:"まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File đề không có audio/transcript.)",
  questions:[
  { id:"h2-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"1番", options:["印象的な音楽","美しい海の映像","希望が持てるラストシーン","主役の男の子の演技力"], answer:2,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ③ 希望が持てるラストシーン. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h2-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"2番", options:["毎日運動をしている人","一日に6時間以上寝ている人","毎日30分程度動画を見ている人","過去に実現に参加したことがある人"], answer:1,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ② 一日に6時間以上寝ている人. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h2-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"3番", options:["会社から行きやすい場所にあるから","ひとクラスの人数が少ないから","じゅぎょう料が安いから","しかく試験の合格りつが高いから"], answer:1,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ② ひとクラスの人数が少ないから. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h2-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"4番", options:["高校でサッカーのコーチとして働く","プロのサッカー選手を目指す","大学でサッカーのしどう法を研究する","子ども向けのサッカー教室を開く"], answer:0,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ① 高校でサッカーのコーチとして働く. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h2-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"5番", options:["子どもの安全に注意すること","子どもにわかりやすく指示すること","子どもと目の高さを合わせて話すこと","明るく元気にあいさつすること"], answer:2,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ③ 子どもと目の高さを合わせて話すこと. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h2-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có audio/bài nghe.", audioUrl:"", question:"6番", options:["はんばい価格を下げる","そうざいの種類を増やす","宅配サービスを行う","店に置く魚の種類を増やす"], answer:3,
    translation:"Không thể dịch đầy đủ do thiếu nội dung audio.",
    explanation:"Đáp án theo bảng đáp án trong file: ④ 店に置く魚の種類を増やす. ⚠️ THIẾU DỮ LIỆU TRONG FILE." }
]},
{ tab:"聴解", section:"問題3 概要理解",
  instruction:"問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"h3-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — toàn bộ nội dung & lựa chọn nằm trong audio, không có trong file đề.", audioUrl:"", question:"1番（lựa chọn 1〜4 đều trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:2,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ③. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h3-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"2番", options:["① audio","② audio","③ audio","④ audio"], answer:2,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ③. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h3-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"3番", options:["① audio","② audio","③ audio","④ audio"], answer:0,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ①. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h3-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"4番", options:["① audio","② audio","③ audio","④ audio"], answer:3,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ④. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h3-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"5番", options:["① audio","② audio","③ audio","④ audio"], answer:1,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ②. ⚠️ THIẾU DỮ LIỆU TRONG FILE." }
]},
{ tab:"聴解", section:"問題4 即時応答",
  instruction:"問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"h4-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"1番（lựa chọn 1〜3 trong audio）", options:["① audio","② audio","③ audio"], answer:1,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ②. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"2番", options:["① audio","② audio","③ audio"], answer:2,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ③. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"3番", options:["① audio","② audio","③ audio"], answer:0,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ①. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"4番", options:["① audio","② audio","③ audio"], answer:2,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ③. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"5番", options:["① audio","② audio","③ audio"], answer:1,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ②. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"6番", options:["① audio","② audio","③ audio"], answer:0,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ①. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-7", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"7番", options:["① audio","② audio","③ audio"], answer:2,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ③. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-8", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"8番", options:["① audio","② audio","③ audio"], answer:0,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ①. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-9", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"9番", options:["① audio","② audio","③ audio"], answer:2,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ③. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-10", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"10番", options:["① audio","② audio","③ audio"], answer:1,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ②. ⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h4-11", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"11番", options:["① audio","② audio","③ audio"], answer:0,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"Đáp án theo bảng đáp án trong file: ①. ⚠️ THIẾU DỮ LIỆU TRONG FILE." }
]},
{ tab:"聴解", section:"問題5 統合理解",
  instruction:"長めの話を聞きます。この問題には練習はありません。問題用紙にメモをとってkaまいません。",
  questions:[
  { id:"h5-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — nội dung & đáp án không xác định được từ file.", audioUrl:"", question:"1番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE: bảng đáp án ghi '問題5: 424' nhưng không đủ dữ liệu để map thành đáp án 1 lựa chọn." },
  { id:"h5-2", passage:"2番: phần in trên giấy có 質問1 và 質問2 (mỗi câu 4 lựa chọn: 10月／11月／12月／2月 và 10月／11月／12月／1月). ⚠️ Không có audio nên không thể xác định đáp án.", audioUrl:"", question:"2番（質問1）", options:["10月","11月","12月","2月"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE." },
  { id:"h5-3", passage:"", audioUrl:"", question:"2番（質問2）", options:["10月","11月","12月","1月"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE." }
]}
]});