/* =========================================================================
   data_2018_07.js — JLPT N2 2018年7月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   Nguồn: pdf_data/2018_7.pdf — bản scan 30 trang (đề 1–16, bảng 正解表 trang 17,
   trang 详解 18–24, 台本 phần 聴解 25–30).
   Toàn bộ đáp án dưới đây đã được đối chiếu với bảng 正解表 của file đề.
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2018_07", label:"07/2018", title:"JLPT N2 — 2018年7月 (07/2018)", file:"data_2018_07.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{ tab:"文字・語彙", section:"問題1 漢字読み",
  instruction:"＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a1-1", passage:"", audioUrl:"", question:"1. 私は少し<u>怖い</u>と思いました。", options:["つらい","きつい","ゆるい","こわい"], answer:3,
    translation:"Tôi cảm thấy hơi sợ.",
    explanation:"怖い = こわい: đáng sợ, sợ hãi. 辛い (つらい: cay đắng, vất vả)・きつい (chặt, nghiêm khắc)・ゆるい (緩い: lỏng, chùng) đều sai nghĩa/âm. ⇒ ④こわい." },
  { id:"a1-2", passage:"", audioUrl:"", question:"2. この食品は<u>冷蔵庫</u>で保存してください。", options:["れいとうこ","れいぞうこう","れいぞうこ","れいとうこう"], answer:2,
    translation:"Hãy bảo quản thực phẩm này trong tủ lạnh.",
    explanation:"冷蔵庫 = れいぞうこ: tủ lạnh. 冷凍庫 (れいとうこ: tủ đông)・れいぞうこう・れいとうこう đều sai âm. ⇒ ③れいぞうこ." },
  { id:"a1-3", passage:"", audioUrl:"", question:"3. 今年の支出は<u>総額</u>で5,300万円だった。", options:["こうがく","そうがく","そうかく","こうかく"], answer:1,
    translation:"Chi tiêu của năm nay tổng cộng là 53 triệu yên.",
    explanation:"総額 = そうがく: tổng số, tổng cộng. 工学 (こうがく: kỹ thuật học)・総画 (そうかく: tổng số nét)・口角 (こうかく: khóe miệng) sai. ⇒ ②そうがく." },
  { id:"a1-4", passage:"", audioUrl:"", question:"4. まだ<u>湿って</u>いるから、もう少し待ちましょう。", options:["こおって","にごって","しめって","たまって"], answer:2,
    translation:"Vì vẫn còn ẩm nên hãy đợi thêm một chút.",
    explanation:"湿る = しめって (ẩm, ỉu ướt). 凍って (こおって: đông lại)・濁って (にごって: vẩn đục)・溜まって (たまって: tích tụ) sai. ⇒ ③しめって." },
  { id:"a1-5", passage:"", audioUrl:"", question:"5. 応募者には<u>抽選</u>でプレゼントが当たります。", options:["ちゅうせん","ちゅうぜん","つうせん","つうぜん"], answer:0,
    translation:"Người ứng tuyển sẽ được tặng quà bằng cách bốc thăm.",
    explanation:"抽選 = ちゅうせん: bốc thăm, rút thăm. ちゅうぜん・通船 (つうせん: tàu thuyền qua lại)・つうぜん sai. ⇒ ①ちゅうせん." },
]},
{ tab:"文字・語彙", section:"問題2 表記",
  instruction:"＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a2-1", passage:"", audioUrl:"", question:"6. この国にはまだ<u>ゆたか</u>な自然が残されている。", options:["恵か","富か","豊か","満か"], answer:2,
    translation:"Ở đất nước này vẫn còn lại thiên nhiên phong phú.",
    explanation:"ゆたか = 豊か: phong phú, giàu có, dồi dào. 恵か・富か・満か là chữ ghép không đúng. ⇒ ③豊か." },
  { id:"a2-2", passage:"", audioUrl:"", question:"7. このセミナーの目標は、「自分で考える力」を<u>やしなう</u>ことです。", options:["得う","築う","育う","養う"], answer:3,
    translation:"Mục tiêu của seminar này là nuôi dưỡng \"khả năng tự suy nghĩ\".",
    explanation:"やしなう = 養う: nuôi dưỡng, bồi dưỡng, rèn luyện. 得う (得る: đạt được)・築う (築く: xây)・育う (育つ: lớn lên) đều sai. ⇒ ④養う." },
  { id:"a2-3", passage:"", audioUrl:"", question:"8. ガラスの<u>はへん</u>を踏まないように気をつけてください。", options:["破片","被片","破辺","被辺"], answer:0,
    translation:"Hãy cẩn thận đừng giẫm lên mảnh vỡ thủy tinh.",
    explanation:"破片 = はへん: mảnh vỡ, mảnh vụn. 被片・破辺・被辺 là chữ ghép không đúng. ⇒ ①破片." },
  { id:"a2-4", passage:"", audioUrl:"", question:"9. 工場の入り口には夜間でも<u>けいび</u>の人がいる。", options:["警秘","警備","係備","係秘"], answer:1,
    translation:"Ở cổng nhà máy, dù ban đêm vẫn có người bảo vệ.",
    explanation:"警備 = けいび: bảo vệ, canh gác, cảnh bị. 警秘・係備・係秘 là chữ ghép không đúng. ⇒ ②警備." },
  { id:"a2-5", passage:"", audioUrl:"", question:"10. 時間がないので、詳しい説明は<u>はぶきます</u>。", options:["略きます","除きます","省きます","抜きます"], answer:2,
    translation:"Vì không có thời gian nên tôi lược bỏ phần giải thích chi tiết.",
    explanation:"省く = はぶく ⇒ はぶきます: lược bỏ, bỏ bớt. 略す (りゃくす)・除く (のぞく: loại trừ)・抜く (ぬく: rút ra) tuy gần nghĩa nhưng không đọc はぶく. ⇒ ③省きます." },
]},
{ tab:"文字・語彙", section:"問題3 語形成",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a3-1", passage:"", audioUrl:"", question:"11. 正月もスキー（　）は、人でいっぱいだ。", options:["所","場","区","地"], answer:1,
    translation:"Ngay cả dịp Tết, sân trượt tuyết cũng đầy ắp người.",
    explanation:"スキー場 = スキーじょう: sân (bãi) trượt tuyết. 所・区・地 không tạo thành từ chỉ nơi chốn đúng. ⇒ ②場." },
  { id:"a3-2", passage:"", audioUrl:"", question:"12. （　）学期から新しいプログラムが始まる。", options:["明","近","隣","来"], answer:3,
    translation:"Từ học kỳ tới, chương trình mới sẽ bắt đầu.",
    explanation:"来学期 = らいがっき: học kỳ tới. 明・近・隣 không đọc らい và không hợp nghĩa. ⇒ ④来." },
  { id:"a3-3", passage:"", audioUrl:"", question:"13. この高校は進学（　）が非常に高く、ほとんどの生徒が大学に進む。", options:["量","値","率","割"], answer:2,
    translation:"Trường cấp ba này có tỷ lệ học lên rất cao, hầu hết học sinh đều vào đại học.",
    explanation:"進学率 = しんがくりつ: tỷ lệ học lên cao. 量 (りょう)・値 (ち)・割 (わり) sai. ⇒ ③率 (りつ)." },
  { id:"a3-4", passage:"", audioUrl:"", question:"14. 大臣の下に二人の（　）大臣がいるのが一般的です。", options:["補","助","次","副"], answer:3,
    translation:"Thông thường dưới bộ trưởng có hai thứ trưởng.",
    explanation:"副大臣 = ふくだいじん: thứ trưởng, phó đại thần. 補 (警部補)・助・次 không hợp. ⇒ ④副 (ふく)." },
  { id:"a3-5", passage:"", audioUrl:"", question:"15. スポーツテストの結果を学年（　）に見ると、一年生だけが昨年を上回っていた。", options:["別","境","段","節"], answer:0,
    translation:"Nhìn kết quả kiểm tra thể thao theo từng khối lớp thì chỉ có học sinh năm nhất là tăng so với năm ngoái.",
    explanation:"学年別 = がくねんべつ: phân theo khối lớp. 境 (きょう)・段 (だん)・節 (せつ) sai. ⇒ ①別 (べつ)." },
]},
{ tab:"文字・語彙", section:"問題4 文脈規定",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a4-1", passage:"", audioUrl:"", question:"16. 昨日の試合では実力を（　）できず、一試合目で負けてしまった。", options:["表現","明示","公開","発揮"], answer:3,
    translation:"Trong trận đấu hôm qua, tôi đã không thể phát huy được thực lực nên thua ngay trận đầu.",
    explanation:"実力を発揮する = phát huy thực lực. 表現 (biểu đạt)・明示 (nêu rõ)・公開 (công khai) đều không kết hợp với 「実力を」. ⇒ ④発揮." },
  { id:"a4-2", passage:"", audioUrl:"", question:"17. 料理本を見ながら、自分の好みに合うように味付けを（　）する。", options:["コメント","デザイン","アレンジ","ケア"], answer:2,
    translation:"Vừa xem sách nấu ăn, tôi vừa điều chỉnh (biến tấu) cách nêm nếm cho hợp khẩu vị của mình.",
    explanation:"アレンジする = sắp xếp lại, biến tấu, điều chỉnh theo ý mình. コメント (bình luận)・デザイン (thiết kế)・ケア (chăm sóc) sai nghĩa. ⇒ ③アレンジ." },
  { id:"a4-3", passage:"", audioUrl:"", question:"18. あの人が描く絵には、ほかの人の絵にはない（　）の雰囲気がある。", options:["専属","独特","限定","孤立"], answer:1,
    translation:"Tranh của người đó mang một bầu không khí độc đáo mà tranh người khác không có.",
    explanation:"独特の雰囲気 = bầu không khí độc đáo, riêng biệt. 専属 (chuyên thuộc)・限定 (hạn định)・孤立 (cô lập) sai nghĩa. ⇒ ②独特." },
  { id:"a4-4", passage:"", audioUrl:"", question:"19. 父は、どんなに忙しいときでも、朝の運動を（　）。", options:["空けない","離さない","奪わない","欠かさない"], answer:3,
    translation:"Bố tôi dù bận thế nào cũng không bao giờ bỏ buổi tập thể dục buổi sáng.",
    explanation:"欠かさない = không bỏ sót, không gián đoạn (欠かす: thiếu, bỏ). 空けない (không bỏ trống)・離さない (không rời)・奪わない (không cướp) không hợp. ⇒ ④欠かさない." },
  { id:"a4-5", passage:"", audioUrl:"", question:"20. クイズの答えが分からなくて（　）答えたのに、正解だった。", options:["でたらめに","わがままに","ぎざぎざに","ごちゃごちゃに"], answer:0,
    translation:"Không biết đáp án câu đố nên tôi trả lời bừa, vậy mà lại đúng.",
    explanation:"でたらめに = bừa bãi, tùy tiện, không căn cứ. わがままに (ích kỷ)・ぎざぎざに (lởm chởm)・ごちゃごちゃに (lộn xộn) sai nghĩa. ⇒ ①でたらめに." },
  { id:"a4-6", passage:"", audioUrl:"", question:"21. 昨夜はこの冬でいちばんの寒さとなり、最低気温はマイナス20度に（　）。", options:["減った","達した","通じた","沈んだ"], answer:1,
    translation:"Đêm qua trở thành đêm lạnh nhất mùa đông này, nhiệt độ thấp nhất đã đạt tới âm 20 độ.",
    explanation:"～に達する = đạt tới (mức nào đó). 減った (giảm)・通じた (thông suốt)・沈んだ (chìm) không hợp với 「マイナス20度に」. ⇒ ②達した." },
  { id:"a4-7", passage:"", audioUrl:"", question:"22. 来月の結婚式に向けて準備が（　）進んでいる。", options:["着々と","慎重に","いちいち","ぐんぐん"], answer:0,
    translation:"Công tác chuẩn bị cho đám cưới tháng sau đang được tiến hành đều đặn, thuận lợi.",
    explanation:"着々と (ちゃくちゃくと) = đều đặn, từng bước chắc chắn. 慎重に (thận trọng)・いちいち (từng cái một)・ぐんぐん (nhanh, mạnh) không hợp. ⇒ ①着々と." },
]},
{ tab:"文字・語彙", section:"問題5 言い換え類義",
  instruction:"＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a5-1", passage:"", audioUrl:"", question:"23. 車にボールを<u>当てて</u>、しかられた。", options:["ぶつけて","隠して","落として","詰めて"], answer:0,
    translation:"Tôi ném trúng quả bóng vào xe nên bị mắng.",
    explanation:"当てる (đánh/ném trúng) = ぶつける (đâm, ném vào, va vào). 隠す (giấu)・落とす (đánh rơi)・詰める (nhồi, chật) sai nghĩa. ⇒ ①ぶつけて." },
  { id:"a5-2", passage:"", audioUrl:"", question:"24. その作家は<u>あわれな</u>人生を送った。", options:["退屈な","おかしな","かわいそうな","不安な"], answer:2,
    translation:"Nhà văn đó đã sống một cuộc đời đáng thương.",
    explanation:"あわれ(哀れ) = đáng thương, bi thảm = かわいそう. 退屈な (buồn tẻ)・おかしな (kì lạ)・不安な (bất an) sai nghĩa. ⇒ ③かわいそうな." },
  { id:"a5-3", passage:"", audioUrl:"", question:"25. <u>当分</u>は使わない予定です。", options:["これから","全部","今回","しばらく"], answer:3,
    translation:"Dự định sẽ không dùng trong một thời gian.",
    explanation:"当分 (とうぶん) = nhất thời, trong một thời gian = しばらく. これから (từ nay)・全部 (toàn bộ)・今回 (lần này) sai nghĩa. ⇒ ④しばらく." },
  { id:"a5-4", passage:"", audioUrl:"", question:"26. 留学の話が<u>一転した</u>。", options:["急に止まった","すっかり変わった","少し進んだ","とうとう許された"], answer:1,
    translation:"Chuyện du học đã hoàn toàn thay đổi (đột ngột đảo chiều).",
    explanation:"一転する (いってん) = đột ngột biến chuyển = すっかり変わった. 急に止まった (đột ngột dừng)・少し進んだ (tiến chút)・とうとう許された (cuối cùng được cho phép) sai nghĩa. ⇒ ②すっかり変わった." },
  { id:"a5-5", passage:"", audioUrl:"", question:"27. テストの前日になって<u>じたばたしても</u>しかたない。", options:["慌てても","心配しても","緊張しても","悩んでも"], answer:0,
    translation:"Đến tận ngày trước kỳ thi mới cuống cuồng lên thì cũng vô ích.",
    explanation:"じたばたする = luống cuống, vùng vẫy lo lắng (không ích gì) = 慌てる (cuống). 心配する (lo)・緊張する (căng thẳng)・悩む (phiền não) không sát. ⇒ ①慌てても." },
]},
/* ================= TAB 2: 用法 ================= */
{ tab:"用法", section:"問題6 用法",
  instruction:"次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a6-1", passage:"", audioUrl:"", question:"28. 役目", options:["次の公演で、私は医者の役目を演じる。","健康のために、毎朝散歩することが役目になっている。","池田さんが今日の掃除の役目だ。","部下に仕事を教えるのは課長の役目の一つだ。"], answer:3,
    translation:"Việc dạy công việc cho cấp dưới là một trong những nhiệm vụ (vai trò) của trưởng phòng.",
    explanation:"役目 (やくめ) = nhiệm vụ, chức trách ⇒ 「課長の役目の一つ」✓. ① vai diễn phải dùng 役 (やく), ② phải dùng 習慣 (しゅうかん), ③ phải dùng 当番 (とうばん: người trực). ⇒ ④." },
  { id:"a6-2", passage:"", audioUrl:"", question:"29. 最寄り", options:["最寄りの店までは、歩いて30分だ。","彼女は私の最寄りの友達だ。","最寄りの試験は来月にある。","電車の中で最寄りの人に足を踏まれた。"], answer:0,
    translation:"Đến cửa hàng gần nhất phải đi bộ 30 phút.",
    explanation:"最寄り (もより) = gần nhất ⇒ 「最寄りの店」✓. ② phải dùng 一番 (いちばん), ③ phải dùng 最初 (さいしょ), ④ phải dùng 隣 (となり). ⇒ ①." },
  { id:"a6-3", passage:"", audioUrl:"", question:"30. 解約", options:["大臣は、内容に誤りがあったと述べ、昨日の発言を解約した。","1年の留学を終えて国へ帰るので、銀行の口座を解約した。","やむをえない理由により、A社との面会を解約した。","あの会社は今年は赤字を解約することができた。"], answer:1,
    translation:"Vì kết thúc một năm du học và trở về nước nên tôi đã hủy (đóng) tài khoản ngân hàng.",
    explanation:"解約 (かいやく) = hủy bỏ hợp đồng/khế ước ⇒ 「口座を解約した」✓. ① phát ngôn phải dùng 撤回 (てっかい), ③ cuộc gặp phải dùng 取り消す (とりけす), ④ khoản lỗ phải dùng 解消 (かいしょう). ⇒ ②." },
  { id:"a6-4", passage:"", audioUrl:"", question:"31. 演説", options:["卒業生代表の森さんは卒業式での演説で、先生方への感謝の気持ちを述べた。","首相は昨日の国会での演説で、経済対策を最優先するとの決意を述べた。","決勝進出が決まった中島選手は試合後の演説で、必ず優勝すると述べた。","A社の社長は記者会見の演説で、今後の事業方針について述べた。"], answer:1,
    translation:"Thủ tướng trong bài diễn văn tại Quốc hội hôm qua đã nêu quyết tâm đặt biện pháp kinh tế lên ưu tiên số một.",
    explanation:"演説 (えんぜつ) = diễn văn, diễn thuyết trình bày chủ trương ⇒ 「国会での演説」✓. ① phải dùng スピーチ, ③ phải dùng インタビュー, ④ phải dùng 発言. ⇒ ②." },
  { id:"a6-5", passage:"", audioUrl:"", question:"32. きっぱり", options:["めがねをかけると、遠くの物もきっぱり見えるようになる。","このラーメンはもう何度も食べたので、きっぱり飽きてしまった。","鈴木さんは石川さんからのデートの誘いをきっぱり断った。","むかしのことはなかなかきっぱり思い出せない。"], answer:2,
    translation:"Anh Suzuki đã dứt khoát từ chối lời rủ đi hẹn hò của chị Ishikawa.",
    explanation:"きっぱり = dứt khoát, thẳng thừng, kiên quyết ⇒ 「きっぱり断った」✓. ① phải dùng はっきり (rõ ràng), ② phải dùng すっかり (hoàn toàn), ④ phải dùng はっきり/ぱっと. ⇒ ③." },
]},
/* ================= TAB 3: 文法 ================= */
{ tab:"文法", section:"問題7 文の文法1",
  instruction:"次の文の（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a7-1", passage:"", audioUrl:"", question:"33. 昨日泊まったホテルの部屋は、シングルルーム（　）広かった。", options:["ばかりか","をとわず","にしては","かというと"], answer:2,
    translation:"Phòng khách sạn tôi ở hôm qua, so với phòng đơn thì khá rộng.",
    explanation:"～にしては: so với… thì (nêu chuẩn đánh giá, thường trái dự đoán) ⇒ 「シングルルームにしては広かった」✓. ばかりか (không chỉ… mà còn), をとわず (bất kể), かというと (nói đến việc có… hay không) sai. ⇒ ③." },
  { id:"a7-2", passage:"", audioUrl:"", question:"34. 「店の前で」客「すみません、開店はまだですか。」<br>店員「（　）開店いたしますので、もう少々お待ちください。」", options:["いまにも","まもなく","ほとんど","いつのまに"], answer:1,
    translation:"(Trước cửa hàng) Khách: \"Xin lỗi, vẫn chưa mở cửa ạ?\" Nhân viên: \"Chúng tôi sắp mở cửa nên xin quý khách đợi thêm chút nữa.\"",
    explanation:"まもなく: chẳng bao lâu, sắp tới, lát nữa ⇒ 「まもなく開店いたします」✓. いまにも (sắp sửa ngay — hay đi với そうだ), ほとんど (hầu hết, gần như), いつのまに (không biết từ lúc nào) sai. ⇒ ②." },
  { id:"a7-3", passage:"", audioUrl:"", question:"35. 北山には、初心者でも楽しめるハイキングコースや上級者（　）コースなど、いくつかの登山コースがあります。", options:["ほどの","向けの","きりの","どおりの"], answer:1,
    translation:"Ở Kitayama có một số tuyến leo núi, nào là đường dạo bộ mà cả người mới cũng tận hưởng được, nào là đường dành cho người cao cấp.",
    explanation:"～向けの: dành cho…, hướng đến… ⇒ 「上級者向けのコース」✓. ほどの (đến mức), きりの (chỉ, chỉ có), どおりの (đúng như) sai. ⇒ ②." },
  { id:"a7-4", passage:"", audioUrl:"", question:"36. 昨日、高熱が出たので病院に行った（　）、インフルエンザと診断された。", options:["場合","以上","ことに","ところ"], answer:3,
    translation:"Hôm qua vì sốt cao nên tôi đi bệnh viện, kết quả là được chẩn đoán bị cúm.",
    explanation:"～たところ: sau khi làm… thì (phát hiện/phát sinh kết quả) ⇒ 「病院に行ったところ、インフルエンザと診断された」✓. 場合 (trường hợp), 以上 (một khi đã…), ことに (thật là… — bày tỏ cảm xúc) sai. ⇒ ④." },
  { id:"a7-5", passage:"", audioUrl:"", question:"37. 散歩が大好きなうちの犬が、今日は散歩に（　）。具合でも悪いのだろうか。", options:["行きたがらなかった","行かなければよかった","行ってほしくなかった","行きたくなかった"], answer:0,
    translation:"Con chó nhà tôi rất thích đi dạo vậy mà hôm nay lại tỏ ra không muốn đi dạo. Không lẽ nó bị ốm.",
    explanation:"～がる: tỏ ra muốn/ghét (dùng cho người thứ ba) ⇒ 「散歩に行きたがらなかった」✓. 行かなければよかった (giá mà đừng đi), 行ってほしくなかった (không muốn nó đi), 行きたくなかった (chính mình không muốn đi) sai chủ thể. ⇒ ①." },
  { id:"a7-6", passage:"", audioUrl:"", question:"38. 市長は、記者会見で「高速道路建設に反対している市民も少なくないのだから、市長として、そのことを無視して建設計画を（　）。」と述べた。", options:["進めそうにない","進めてもかまわない","進めずにはいられない","進めるわけにはいかない"], answer:3,
    translation:"Thị trưởng phát biểu tại họp báo: \"Vì có không ít người dân phản đối việc xây đường cao tốc, với tư cách thị trưởng, tôi không thể làm ngơ điều đó mà đẩy tiến kế hoạch xây dựng được.\"",
    explanation:"～わけにはいかない: không thể… (vì trách nhiệm, đạo lý) ⇒ 「無視して建設計画を進めるわけにはいかない」✓. 進めそうにない (có vẻ không tiến được), 進めてもかまわない (tiến cũng không sao), 進めずにはいられない (không tiến không được) sai nghĩa. ⇒ ④." },
  { id:"a7-7", passage:"", audioUrl:"", question:"39. 「スピーチで」「本日は弊社創立50周年記念パーティーにお越しくださりありがとうございます。社長の小林でございます。弊社を代表して、私から一言ごあいさつ（　）。」", options:["されます","うかがいます","申し上げます","おっしゃいます"], answer:2,
    translation:"(Trong bài phát biểu) Cảm ơn quý vị đã đến dự tiệc kỷ niệm 50 năm thành lập công ty chúng tôi. Tôi là Kobayashi, giám đốc. Thay mặt công ty, tôi xin được gửi tới mọi người một lời chào.",
    explanation:"申し上げます là khiêm nhường ngữ của 言う (nói) ⇒ 「ごあいさつ申し上げます」✓. されます (bị động), うかがいます (khiêm nhường ngữ của 聞く/thăm hỏi), おっしゃいます (tôn kính ngữ của 言う — dùng cho người khác) sai vai. ⇒ ③." },
  { id:"a7-8", passage:"", audioUrl:"", question:"40. そのバッグは、どこにでもあるような物なのに、人気歌手が愛用している（　）、1万個も売れたそうだ。", options:["とすること","というだけ","とすることを","というだけで"], answer:3,
    translation:"Chiếc túi đó vốn là thứ có ở đâu cũng có, vậy mà nghe nói chỉ vì được một ca sĩ nổi tiếng ưa dùng mà bán được tới 1 vạn cái.",
    explanation:"～というだけで: chỉ vì (lý do) cho rằng… ⇒ 「愛用しているというだけで、1万個も売れた」✓. とすること・とすることを (coi như…), というだけ (chỉ nói là…) không khớp ngữ pháp. ⇒ ④." },
  { id:"a7-9", passage:"", audioUrl:"", question:"41. ホテルのフロント係として働き始めたころは、「どんなに忙しくてもお客様には疲れた顔を（　）。」と先輩によく注意された。", options:["見せないために","見えないこと","見せないように","見えないもの"], answer:2,
    translation:"Khi mới bắt đầu làm nhân viên lễ tân khách sạn, tôi thường bị tiền bối nhắc: \"Dù bận thế nào cũng đừng để khách thấy vẻ mặt mệt mỏi.\"",
    explanation:"～ないように: (nhắc) đừng…, để không… ⇒ 「お客様には疲れた顔を見せないように」✓. 見せないために (để không cho thấy), 見えないこと (việc không thấy), 見えないもの (thứ không thấy) sai. ⇒ ③." },
  { id:"a7-10", passage:"", audioUrl:"", question:"42. 母「たかし、寝る前に必ず明日の準備を（　）。朝、慌てて準備すると絶対忘れ物するから。」<br>たかし「大丈夫、もう終わってるよ。」", options:["してあるんだよ","しておきなさいよ","してあるんじゃないの","しておいたの"], answer:1,
    translation:"Mẹ: 「Takashi, trước khi ngủ nhất định phải chuẩn bị sẵn đồ cho ngày mai nhé. Vì sáng ra luống cuống chuẩn bị thể nào cũng quên đồ.」 Takashi: 「Không sao, con xong rồi.」",
    explanation:"～ておきなさい: (mệnh lệnh nhẹ) hãy làm sẵn… trước ⇒ 「準備をしておきなさいよ」✓. してあるんだよ (đã làm sẵn rồi đấy — miêu tả trạng thái), してあるんじゃないの, しておいたの đều sai sắc thái mệnh lệnh. ⇒ ②." },
  { id:"a7-11", passage:"", audioUrl:"", question:"43. X社に入社すると、新入社員は、まず電話の応対の練習を2週間（　）。", options:["させられるそうだ","させるつもりだ","させられたままだ","させているところだ"], answer:0,
    translation:"Nghe nói khi vào công ty X, nhân viên mới trước tiên sẽ bị bắt luyện tập ứng đáp điện thoại trong 2 tuần.",
    explanation:"～させられる (bị bắt làm) + そうだ (nghe nói) ⇒ 「練習を2週間させられるそうだ」✓. させるつもりだ (định cho làm), させられたままだ (bị bắt làm rồi vẫn thế), させているところだ (đang cho làm) sai. ⇒ ①." },
  { id:"a7-12", passage:"", audioUrl:"", question:"44. 田中「次回の勉強会のテーマは何にしましょうか。」<br>山下「私は消費者心理に興味があります。」<br>石川「それも面白そうですが、私はアンケートの分析方法を（　）。」", options:["取り上げようとするでしょうか","取り上げるようになるでしょうか","取り上げたいのだろうと思います","取り上げてみてはどうかと思います"], answer:3,
    translation:"Tanaka: 「Chủ đề buổi học nhóm lần sau nên là gì nhỉ?」 Yamashita: 「Tôi hứng thú với tâm lý người tiêu dùng.」 Ishikawa: 「Điều đó cũng có vẻ thú vị, nhưng tôi nghĩ hay là thử đưa ra phương pháp phân tích bảng hỏi thì sao.」",
    explanation:"～てみてはどうかと思う: nghĩ rằng hay là thử… thì sao (đề xuất ý kiến) ⇒ 「分析方法を取り上げてみてはどうかと思います」✓. Các phương án còn lại không diễn tả mong muốn đề xuất của bản thân, cũng không dùng cho chính mình. ⇒ ④." },
]},
{ tab:"文法", section:"問題8 文の文法2 (sắp xếp - ★)",
  instruction:"次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a8-1", passage:"", audioUrl:"", question:"45. どんなスポーツでも、日々の練習が ＿＿ ＿＿★ ＿＿ ＿＿ 行うと時間をかけてもなかなか上達しない。［1 もちろんだが / 2 欠かせないのは / 3 上達に / 4 間違った方法で］", options:["もちろんだが","欠かせないのは","上達に","間違った方法で"], answer:1,
    translation:"Dù là môn thể thao nào, việc luyện tập hằng ngày là không thể thiếu để tiến bộ thì đương nhiên, nhưng nếu tập sai phương pháp thì dù tốn thời gian cũng khó tiến bộ.",
    explanation:"Thứ tự đúng: ③上達に → ②欠かせないのは → ①もちろんだが → ④間違った方法で: 「日々の練習が上達に欠かせないのはもちろんだが、間違った方法で行うと時間をかけてもなかなか上達しない」。★ là ô thứ 2 ⇒ đáp án ②欠かせないのは. ～に欠かせない: không thể thiếu đối với…; ～はもちろん: … thì đương nhiên." },
  { id:"a8-2", passage:"", audioUrl:"", question:"46. 姉は歌手の赤川ケイの大ファンで、彼女の ＿＿ ＿＿★ ＿＿ ＿＿ 知りたいと言っている。［1 ことなら / 2 小さな / 3 ことでも / 4 どんなに］", options:["ことなら","小さな","ことでも","どんなに"], answer:1,
    translation:"Chị tôi là fan cuồng của ca sĩ Akagawa Kei, chị ấy nói rằng chuyện gì của cô ấy dù nhỏ nhặt đến đâu cũng muốn biết.",
    explanation:"Thứ tự đúng: ①ことなら → ④どんなに → ②小さな → ③ことでも: 「彼女のことなら、どんなに小さなことでも知りたいと言っている」。★ là ô thứ 3 ⇒ đáp án ②小さな. ～なら: nếu là…; どんなに～ても: dù… đến mức nào." },
  { id:"a8-3", passage:"", audioUrl:"", question:"47. 明日の夕方が締め切りのレポートがまだ終わっていない。明日は一日中授業があって時間がとれないので、今晩 ＿＿ ＿＿★ ＿＿ ＿＿ いけない。［1 終わらせて / 2 徹夜して / 3 しまわないと / 4 でも］", options:["終わらせて","徹夜して","しまわないと","でも"], answer:0,
    translation:"Báo cáo có hạn chót là chiều tối mai vẫn chưa xong. Ngày mai cả ngày có tiết học nên không có thời gian, vì vậy tối nay dù phải thức trắng đêm cũng phải làm cho xong.",
    explanation:"Thứ tự đúng: ②徹夜して → ④でも → ①終わらせて → ③しまわないと: 「今晩徹夜してでも終わらせてしまわないといけない」。★ là ô thứ 3 ⇒ đáp án ①終わらせて. ～てでも: dù phải… (cũng); ～てしまわないといけない: phải làm cho xong." },
  { id:"a8-4", passage:"", audioUrl:"", question:"48. 田中さんは ＿＿ ＿＿★ ＿＿ ＿＿ 、冬はいつもみかんを大量に買うそうだ。［1 食べ出すと / 2 一度 / 3 みかんが好きらしく / 4 止まらないほど］", options:["食べ出すと","一度","みかんが好きらしく","止まらないほど"], answer:3,
    translation:"Nghe nói anh Tanaka có vẻ rất thích quýt, một khi đã ăn là ăn đến mức không dừng lại được, nên mùa đông lúc nào cũng mua một lượng lớn quýt.",
    explanation:"Thứ tự đúng: ③みかんが好きらしく → ②一度 → ①食べ出すと → ④止まらないほど: 「みかんが好きらしく、一度食べ出すと止まらないほど、冬はいつもみかんを大量に買うそうだ」。★ là ô thứ 3 ⇒ đáp án ④止まらないほど. ～ほど: đến mức; ～らしい: hình như/nghe nói." },
  { id:"a8-5", passage:"", audioUrl:"", question:"49. 私は、中学生になったころから ＿＿ ＿＿★ ＿＿ ＿＿ 医者になろうと決めていた。［1 将来 / 2 医学に興味を持ち始め / 3 高校に入ったときには / 4 次第に］", options:["将来","医学に興味を持ち始め","高校に入ったときには","次第に"], answer:2,
    translation:"Từ khoảng khi lên trung học cơ sở, tôi dần bắt đầu hứng thú với y học, và đến khi vào cấp ba thì đã quyết định sau này sẽ trở thành bác sĩ.",
    explanation:"Thứ tự đúng: ④次第に → ②医学に興味を持ち始め → ③高校に入ったときには → ①将来: 「中学生になったころから次第に医学に興味を持ち始め、高校に入ったときには将来医者になろうと決めていた」。★ là ô thứ 3 ⇒ đáp án ③高校に入ったときには. 次第に (しだいに): dần dần." },
]},
{ tab:"文法", section:"問題9 文章の文法 (điền vào đoạn văn)",
  instruction:"次の文章を読んで、文章全体の内容を考えて、（50）から（54）の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a9-1", passage:"以下は、道路について書かれた文章である。<br><br>道路のひみつ<br><br>仕事、買い物、遊びに行くとき、誰でも必ずお世話になるものがある。（50）だ。当たり前のように存在し、多くの人に利用されているが、様々な工夫がされていることはあまり知られていない。<br><br>例えば、高速道路や大きな道路の多くで雨水が道路上にたまりにくい設計になっていることは（51）。道路表面に小さな無数の穴があり、水が舗装の下に抜けるという仕組みだ。高速道路で雨の日に事故が多かった地点も、この舗装にした後、雨の日の事故が約80％減少したという。<br><br>（52）、寒い地域では雪や氷が原因でスリップ事故が多発する。そのため、雪や氷を砕く機能をもった道路が開発されている。粒状のゴムなど、柔軟性のある小さな素材を道路に埋め込み、車の重みで道路をわずかに変形させて雪や氷を砕く。カーブや坂道などをそういう舗装にすれば、道路に雪や氷が密着するのを防ぐことができ、スリップの危険性が減る。<br><br>道路表面の温度を下げる（53）。道路は太陽に熱せられ、夏は特に熱くなりやすい。そこで、太陽光線の吸収を防ぐ物質を表面に塗ることで温度上昇を抑えている。この舗装により、道路の温度は最大10度以上も下がる。人やペットが歩く公園や歩道にぴったりだ。<br><br>これら以外にも、様々な機能の道路が日々開発され、利用されている。道路の違いは見た目にはよくわからないかもしれない。しかし、人々がより安全で快適に暮らせるよう、足元で（54）。", audioUrl:"", question:"50. 仕事、買い物、遊びに行くとき、誰でも必ずお世話になるものがある。（50）だ。", options:["道路","ある道路","その道路","こんな道路"], answer:0,
    translation:"Có một thứ mà ai cũng nhất định phải nhờ tới khi đi làm, đi mua sắm hay đi chơi. Đó là đường. Nó tồn tại như một điều hiển nhiên, được nhiều người sử dụng, nhưng ít ai biết rằng nó chứa đựng nhiều sự khéo léo.",
    explanation:"【50】= 道路: 「誰でも必ずお世話になるものがある。道路だ。」— trực tiếp nêu ra sự vật được nói tới ở câu trước, mở đầu dứt khoát. ある道路 (một con đường nào đó)・その道路 (con đường đó)・こんな道路 (con đường như thế này) đều lệch mạch. ⇒ ①道路." },
  { id:"a9-2", passage:"", audioUrl:"", question:"51. 例えば、高速道路や大きな道路の多くで雨水が道路上にたまりにくい設計になっていることは（51）。", options:["ご存じだ","ご存じのようだ","ご存じだろうか","ご存じなのだろう"], answer:2,
    translation:"Ví dụ, quý vị có biết rằng phần lớn đường cao tốc và đường lớn được thiết kế để nước mưa khó đọng lại trên mặt đường không?",
    explanation:"【51】= ご存じだろうか: quý vị có biết… không? (câu hỏi hướng tới người đọc, phù hợp vì trước đó nói nhiều người không biết về đường). ご存じだ (ngài biết — không nên tự phán đoán người khác)・ご存じのようだ (có vẻ biết)・ご存じなのだろう (chắc là biết) sai sắc thái. ⇒ ③ご存じだろうか." },
  { id:"a9-3", passage:"", audioUrl:"", question:"52. （52）、寒い地域では雪や氷が原因でスリップ事故が多発する。", options:["また","すると","こうして","したがって"], answer:0,
    translation:"Ngoài ra, ở vùng lạnh, tai nạn trượt do tuyết và băng xảy ra nhiều.",
    explanation:"【52】= また: ngoài ra, hơn nữa (nối hai đoạn mang tính liệt kê, bổ sung). すると (thế là)・こうして (như thế này)・したがって (do đó) sai quan hệ. ⇒ ①また." },
  { id:"a9-4", passage:"", audioUrl:"", question:"53. 道路表面の温度を下げる（53）。", options:["工夫だと言える","工夫も考えられる","工夫だと思われる","工夫も見られる"], answer:3,
    translation:"Người ta cũng thấy có phương pháp hạ nhiệt độ bề mặt đường.",
    explanation:"【53】= 工夫も見られる: cũng có thể thấy một sự khéo léo/cách làm (diễn tả trạng thái đã tồn tại thực tế, rồi từ đó triển khai giải thích tiếp). 工夫も考えられる (có thể nghĩ ra — chỉ là suy nghĩ, không khớp diễn giải sau)・工夫だと言える/工夫だと思われる lệch mạch. ⇒ ④工夫も見られる." },
  { id:"a9-5", passage:"", audioUrl:"", question:"54. しかし、人々がより安全で快適に暮らせるよう、足元で（54）。", options:["支えてくれているはずだった","支えてくれているわけだ","支えてくれているからだった","支えてくれているおかげだ"], answer:1,
    translation:"Tuy nhiên, để con người có thể sống an toàn và thoải mái hơn, chính là nhờ ở ngay dưới chân ta, con đường đang âm thầm nâng đỡ.",
    explanation:"【54】= 支えてくれているわけだ: hóa ra là… (kết câu diễn tả sự thật hiển nhiên, có sắc thái 'là vì thế'). ～はずだった (lẽ ra phải)・～からだった (là vì — không khớp)・～おかげだ (nhờ ơn — lệch mạch) sai. ⇒ ②支えてくれているわけだ." },
]},
/* ================= TAB 4: 読解 ================= */
{ tab:"読解", section:"問題10 内容理解・短文",
  instruction:"次の（1）から（5）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b10-1", passage:"(1) 以下は、ある旅行会社に届いたメールである。<br><br>宛先：t_kigawa@btbtravel.co.jp<br>件名：ゼミ旅行の見積書について（北山大学）<br>日時：2018年6月25日 11:30<br><br>BTB旅行社 団体担当<br>木川友子様<br><br>お世話になっております。北山大学の大村光一です。<br><br>せっかく見積書を作成していただいたのですが、変更をお願いしたい点がございます。<br><br>諸事情により、8月6日（月）に出発することができなくなってしまったので、出発日を8月20日（月）に変更して、再度見積書を作成していただけないでしょうか。料金は今回の見積書の金額を超えないようにお願いいたします。ホテルは変更になってもかまいませんが、同じ1泊2日の日程でお願いいたします。<br><br>どうぞよろしくお願いいたします。<br><br>北山大学<br>大村光一", audioUrl:"", question:"55. 見積書について、このメールで依頼していることは何か。", options:["料金が上がってもいいので、出発日を変更してほしい。","料金を上げずに、出発日を変更してほしい。","宿泊先は変わってもいいので、出発日と日数を変更してほしい。","宿泊先は変えずに、出発日と日数を変更してほしい。"], answer:1,
    translation:"Thư này yêu cầu gì về bảng báo giá? — Đổi ngày khởi hành nhưng không tăng giá.",
    explanation:"Câu then chốt: 「出発日を8月20日に変更して、再度見積書を作成していただけないでしょうか。料金は今回の見積書の金額を超えないように…同じ1泊2日の日程で」⇒ đổi ngày đi, giữ nguyên phí và lịch trình ⇒ ② không tăng phí, đổi ngày khởi hành. ① sai (có nói phí không được tăng), ③④ sai vì lịch trình vẫn 1 đêm 2 ngày (không đổi số ngày) và khách sạn đổi cũng được. ⇒ ②." },
  { id:"b10-2", passage:"(2) 他者に意志を伝えるとき、「高さ」は相当に大事な要素となる。学生や聴衆より一段高いところに立って話す。するとびっくりするほど場の隅々まで見通せるのだが、聞き手からの反応は鈍くなる。意見を「申し上げる」体になるためか。一方で、平坦なところから、即ち同一の目線で話しかけると、活発な意見交換が期待できる。ところが今度は全体に目が配れない。<br><br>（注1）聴衆：話を聞く人たち<br>（注2）～体：～ような形<br>（注3）平坦な：ここでは、同じ高さの<br>（注4）目を配る：注意を向ける", audioUrl:"", question:"56. 話すときの高さについて、筆者の考えに合うのはどれか。", options:["高い場所から話すと、聞き手の反応が見にくい。","高い場所から話すと、聞き手が反対意見を言いやすくなる。","同じ高さで話すと、聞き手が反応しにくい。","同じ高さで話すと、聞き手が発言しやすくなる。"], answer:3,
    translation:"Về độ cao khi nói, đâu là điều hợp với suy nghĩ của tác giả? — Nói cùng độ cao thì người nghe dễ phát biểu hơn.",
    explanation:"「平坦なところから、即ち同一の目線で話しかけると、活発な意見交換が期待できる」⇒ cùng tầm mắt thì người nghe dễ trao đổi/phát biểu ⇒ ④. ① sai (đứng cao thì khó thấy phản ứng — đúng theo bài, nhưng đó không phải trọng tâm 'ý tác giả' so với ④; thực ra bài nói đứng cao thấy toàn cảnh nhưng phản ứng mờ nhạt, còn ① diễn đạt thành 'khó thấy phản ứng của người nghe' cũng đúng ý — tuy nhiên đáp án chuẩn là ④). ② ngược nghĩa (đứng cao phản ứng chậm, không phải dễ phản đối), ③ ngược nghĩa (cùng độ cao thì phản ứng sôi nổi). ⇒ ④." },
  { id:"b10-3", passage:"(3) 言うまでもなく、深く思考した者は競争相手より有利な立場に立てる。しかし行動を止めてまでして考えるのは避けよう。行動があなたの思考を止めることはない。むしろ思考を加速させ、改善させる効果があることを知ってほしい。行動し、変化する状況の中で考えつづけることを実践するのはかなり勇気が要るだろう。予期しないことが起こるかもしれない。リスクもある。しかし、そうすることで最速の思考が生み出されるのだ。<br><br>（注1）言うまでもなく：わざわざ言う必要もないが<br>（注2）リスク：危険", audioUrl:"", question:"57. 筆者の考えに合うのはどれか。", options:["行動を止めずに考えつづけることで、思考はより加速する。","行動を止めて、深く思考することも必要だ。","変化する状況の中で、行動を加速することが大切だ。","考えつづけていれば、さらに勇気が持てるようになる。"], answer:0,
    translation:"Đâu là điều hợp với suy nghĩ của tác giả? — Không ngừng hành động mà tiếp tục suy nghĩ thì tư duy càng được tăng tốc.",
    explanation:"「行動があなたの思考を止めることはない。むしろ思考を加速させ、改善させる」「変化する状況の中で考えつづける…そうすることで最速の思考が生み出される」⇒ ①. ② ngược (bài nói nên tránh việc dừng hành động để suy nghĩ), ③ bài không nói 'tăng tốc hành động', ④ bài chỉ nói cần dũng khí, không nói tiếp tục suy nghĩ thì có thêm dũng khí. ⇒ ①." },
  { id:"b10-4", passage:"(4) 以下は、ある会社の社内文書である。<br><br>2018年4月2日<br>社員各位<br>総務課長<br><br>定期健康診断について<br><br>これまで定期健康診断は毎年9月にアラキ医療センターで実施してきましたが、今年度より各自で指定の医療機関の中から選んで受診していただくことになりました。4月から翌年3月までの間で受診日を決め、直接医療機関に予約を入れて受診するようにしてください。なお、検査項目につきましては、これまで通りです。<br><br>指定機関と予約方法の詳細は、後日お配りする資料でご確認ください。<br><br>どうぞよろしくお願いいたします。<br>以上", audioUrl:"", question:"58. この知らせによると、定期健康診断の受け方はどのように変わったか。", options:["アラキ医療センターに各自で予約を入れ、受診するようになった。","アラキ医療センターで4月から翌年3月までの指定日に受診するようになった。","各自で医療機関と日を決めて予約し、受診するようになった。","各自で医療機関と日と検査項目を決めて予約し、受診するようになった。"], answer:2,
    translation:"Theo thông báo này, cách khám sức khỏe định kỳ đã thay đổi thế nào? — Mỗi người tự chọn cơ sở y tế và tự quyết định ngày rồi đặt hẹn để đi khám.",
    explanation:"「今年度より各自で指定の医療機関の中から選んで受診」「4月から翌年3月までの間で受診日を決め、直接医療機関に予約を入れて」⇒ tự chọn cơ sở và ngày rồi đặt hẹn ⇒ ③. ①② sai vì không còn cố định ở アラキ医療センター, ④ sai vì 「検査項目はこれまで通り」(hạng mục khám không đổi). ⇒ ③." },
  { id:"b10-5", passage:"(5) 成功例にできるだけ忠実に従って努力すれば、やみくもに努力するよりも、成功する確率はかなり高い。もちろん、人の成功を見て、それを全面的に「真似る」のは、アイデアを盗んだとか、猿真似をしたとかいわれて、非難されても仕方がない。<br><br>しかしながら、人のいいところを参考にして、自分なりの方法を工夫して努力していくのは、まともな人のすることである。そこには、単に真似るのではなく、先達から「学ぶ」という姿勢がある。<br><br>（注1）忠実に：ここでは、正確に<br>（注2）やみくもに：ここでは、何も考えずに、ただ<br>（注3）まともな：ここでは、常識のある<br>（注4）先達：先輩", audioUrl:"", question:"59. 筆者の考えに合うのはどれか。", options:["成功を目指して何も考えずに努力することが大切だ。","人の成功例は参考にしないほうがいい。","人の真似を続けていけば、必ず成功できる。","人のいいところを見て工夫すれば、成功につながる。"], answer:3,
    translation:"Đâu là điều hợp với suy nghĩ của tác giả? — Nhìn vào điểm tốt của người khác mà sáng tạo, biến hóa theo cách riêng thì sẽ dẫn đến thành công.",
    explanation:"「人のいいところを参考にして、自分なりの方法を工夫して努力していく」⇒ học hỏi điểm hay của người khác rồi tìm cách riêng ⇒ ④. ① bài phản đối 'やみくもに努力' (nỗ lực vô định), ② ngược nghĩa, ③ sai (chỉ bắt chước hoàn toàn thì có thể bị chê, và không đảm bảo thành công). ⇒ ④." },
]},
{ tab:"読解", section:"問題11 内容理解・中文",
  instruction:"次の（1）から（3）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b11-1", passage:"(1) 大学の先生のイメージとは、一般的にはどのようなものだろうか。理系だと白衣を着て難しい話ばかりする人、文系だと研究室に閉じこもって文学作品を読んでいる人、という声が周囲から聞こえてきた。確かにそれに近い人はいるのだが、もちろんそうでない人も多い。これは政治家、警察官、医者などにも当てはまることであり、私たちはどうしても先入観を持ってしまうため、それが誤解を生む原因になるのだ。<br><br>誤解は相手の先入観だけでなく、自分が原因であることも多い。その大きなものが、話す際の省略である。時間がないときなど、どうしても内容を一部省略して報告する必要がでてくる。時間があっても全ての情報をきちんと伝えるのは無理であろう。そうなると相手は自分の意図とは異なる形で補うために誤解につながっていくのだ。<br><br>（中略）<br><br>省略が多くなるメールは特に注意が必要で、込み入った内容を伝える場合はできるだけ直接会った方がよい。会うのは時間をとられて面倒だと感じるかもしれないが、その方が結局、問題が早く片付くこともあるのだ。<br><br>また、誤解のプラスといえる面にも気が付いた。それは誤解によって人々の考えに自然に多様性が生まれるということだ。様々な意見があることは、健全な社会のための重要な要素である。誤解は一般的には悪者扱いであるが、多様性をつくる仕掛けだと思えば少し見方も変わってくるのではないだろうか。<br><br>（注1）閉じこもって：入ったまま<br>（注2）先入観：思い込み<br>（注3）込み入った：複雑な<br>（注4）健全な：正常な<br>（注5）仕掛け：仕組み", audioUrl:"", question:"60. 大学の先生の例を挙げて、筆者が述べていることは何か。", options:["職業の一般的なイメージは実態と合っている。","周囲と違うイメージを持つと誤解が生まれる。","思い込みから誤解が生まれる。","誰でも誤解をしてしまうことがある。"], answer:2,
    translation:"Qua ví dụ về giảng viên đại học, tác giả muốn nói điều gì? — Chính sự thành kiến (định kiến có sẵn) sinh ra hiểu lầm.",
    explanation:"Câu tổng kết đoạn 1: 「私たちはどうしても先入観を持ってしまうため、それが誤解を生む原因になるのだ」⇒ định kiến là nguyên nhân nảy sinh hiểu lầm ⇒ ③. ① sai (bài không nói hình ảnh chung khớp thực tế), ② sai (không phải 'khác với xung quanh'), ④ lệch (trọng tâm là 'định kiến' chứ không chỉ 'ai cũng hiểu lầm'). ⇒ ③." },
  { id:"b11-2", passage:"", audioUrl:"", question:"61. 話す際の省略が誤解を生むのはなぜか。", options:["聞いた人の思い込みが強くなりすぎるから","聞いた人が省略された内容を補おうとしないから","聞いた人が省略された内容があることに気が付かないから","聞いた人が省略された内容とは違うことを補って理解するから"], answer:3,
    translation:"Vì sao việc lược bỏ khi nói lại sinh ra hiểu lầm? — Vì người nghe bù đắp (suy diễn) phần bị lược bỏ theo cách khác với ý người nói.",
    explanation:"「相手は自分の意図とは異なる形で補うために誤解につながっていくのだ」⇒ người nghe bù vào theo cách khác ý người nói ⇒ ④. ①②③ không khớp với '補う（bù đắp）' sai khác. ⇒ ④." },
  { id:"b11-3", passage:"", audioUrl:"", question:"62. 筆者によると、誤解の良い点はどのようなことか。", options:["いろいろな考えが生まれることになる。","自分の考えの誤りに気付くことができる。","人に対する間違った見方が変えられる。","多様な考えを自然に受け入れられるようになる。"], answer:0,
    translation:"Theo tác giả, điểm tốt của hiểu lầm là gì? — Nó khiến nảy sinh nhiều cách nghĩ khác nhau.",
    explanation:"「誤解によって人々の考えに自然に多様性が生まれるということだ」⇒ hiểu lầm tạo ra tính đa dạng trong suy nghĩ ⇒ ①. ②③④ đều là suy diễn không có trong bài. ⇒ ①." },
  { id:"b11-4", passage:"(2) 昔の小中学生は、遠足や修学旅行のとき、車窓の風景を真剣に眺めていたものだ。見知らぬ土地の風物に、興味をかきたてられていたのである。<br><br>ところが、最近の小中学生は、乗り物の窓の外を眺めようとはせず、バスの中ではマイクをにぎって歌に夢中になっているらしい。あるいはクイズやゲームを楽しんでいるという。そんな話を、諏訪に講演に行ったとき、小学校の校長先生からうかがった。<br><br>わたしは、それを「目的地主義」と名づけようと思う。最近の人々の考えでは、旅は目的地に着いてからはじまる。目的地に到着するまでの移動の時間は、どうも無駄な時間に感じられている。それをなんとか工夫して楽しくしようというのが、車内におけるカラオケやゲームである。（中略）<br><br>かつての旅は、道中が楽しかった。弥次喜多の東海道中も、水戸黄門の漫遊も、むしろ道中そのものに意義があった。ところが、新幹線や空の旅になると、旅の途中は退屈に感じられる。とくに空の旅は、途中はなんにもない。それで、わたしたちの旅の意識が、目的地主義になってしまったようだ。<br><br>旅の意識が変わるだけならまだいい。恐ろしいのは、わたしたちの人生に対する態度が、目的地主義になってはいないかという心配である。人生は「道中」が大事だ。高校生であれば、高校の三年間の毎日を大切にせねばならない。目的地は大学だから、大学に入ってから人生をはじめる——といった考え方はおかしい。サラリーマンが、課長や部長を目的地にして、そこに至る「道中」を軽視するなら、その人の人生は寂しいものだ。<br><br>（注1）見知らぬ：見たことがない<br>（注2）風物：自然の景色や人々の暮らしの様子<br>（注3）興味をかきたてられる：ここでは、興味がわいてくる<br>（注4）弥次喜多の東海道中も、水戸黄門の漫遊も：旅行を題材にした昔の二つの物語のどちらも<br>（注5）そのもの：それ自体", audioUrl:"", question:"63. 遠足や修学旅行の移動のときの小中学生の様子について、筆者はどのように述べているか。", options:["昔も今も、歌やゲームを楽しんでいる。","昔も今も、窓の外の風景に興味を示す。","昔は歌やゲームを楽しんだが、今は楽しもうとしない。","昔は窓の外の風景に興味を持ったが、今は興味を示さない。"], answer:3,
    translation:"Về thái độ của học sinh tiểu học/trung học khi di chuyển trong các chuyến dã ngoại, tham quan, tác giả nói thế nào? — Xưa các em hứng thú với phong cảnh ngoài cửa sổ, nay thì không tỏ ra hứng thú.",
    explanation:"「昔の小中学生は、車窓の風景を真剣に眺めていた」・「最近の小中学生は、乗り物の窓の外を眺めようとはせず…歌に夢中になっている」⇒ ④. ①②③ trái với nội dung bài. ⇒ ④." },
  { id:"b11-5", passage:"", audioUrl:"", question:"64. 「目的地主義」とはどのようなことか。", options:["旅は早く目的地に着くことが大事だと考える。","目的地に着いてからの時間が旅だと考える。","目的地に着くまでの旅の時間を楽しもうと考える。","目的地を決めることから旅ははじまると考える。"], answer:1,
    translation:"Chủ nghĩa lấy điểm đến làm trọng (目的地主義) là gì? — Coi thời gian sau khi đến điểm đến mới là chuyến đi.",
    explanation:"「最近の人々の考えでは、旅は目的地に着いてからはじまる。目的地に到着するまでの移動の時間は…無駄な時間に感じられている」⇒ đến nơi mới tính là 'đi chơi' ⇒ ②. ①③④ không đúng theo định nghĩa trong bài. ⇒ ②." },
  { id:"b11-6", passage:"", audioUrl:"", question:"65. 筆者が言いたいことは何か。", options:["人生は目標に至る過程を大切にしなければならない。","人生は目標を達成した後に、どうするかが大事だ。","人生は目標を持たずに、今ここで何をするかが大事だ。","人生は目標を明確に決めてしまうと寂しいものになる。"], answer:0,
    translation:"Điều tác giả muốn nói là gì? — Trong cuộc đời, phải biết trân trọng quá trình đi đến mục tiêu.",
    explanation:"Đoạn cuối: 「人生は『道中』が大事だ」「大学に入ってから人生をはじめる——といった考え方はおかしい」「『道中』を軽視するなら、その人の人生は寂しいものだ」⇒ trân trọng quá trình ⇒ ①. ②③④ đều lệch ý. ⇒ ①." },
  { id:"b11-7", passage:"(3) 人工物は人間がある意図のもとにつくり出されたものであるのにも関わらず、その社会に与える影響は設計者の予想を越える場合があり、人工物が人間社会の舵とりを行なう現象が起きている。たとえばコンピュータは「計算機」という日本語が示すように、当初は計算を行う機器として製作されてきたが、現在ではデータベースやコミュニケーションなど、さまざまな用途に用いられ、生活環境を大きく変えてきている。<br><br>このように現代における人工物の大きな影響力を考慮する時、設計者はこれまで以上に人工物のもつ社会的意味を頭に入れ、積極的に設計者の意図を人工物にもたせていくことが必要だと思われる。これからの科学技術、そしてモノ作りにとって何より必要なのは、いったい、これからわたしたち一人一人がどんな生活を送り、どのような社会を作り上げたいのかというビジョン（世界観・価値観）であり、設計者は常にこのビジョンがどのようなものであるか考え、人工物にその価値観をもたせることが必要だと思われる。<br><br>しかし、設計する人々は、一方では、自分の考えとは別に社会の欲する製品を設計することが要求される。マーケットニーズのない製品は売れないからである。こうした場合に設計者が自分の価値観をマーケットニーズとうまく調和させるために、設計者の価値観が購買者の価値観とのなんらかの共通性をもつ必要がある。そのために設計者は社会の情勢をよく理解し、将来の社会についての予測をたて、人々の価値観を調査したうえで、設計者としてのビジョンをもつことが求められるだろう。<br><br>（注1）舵とりを行なう：進む方向を決める<br>（注2）データベース：ある目的に合わせて集めた大量の情報<br>（注3）調和させる：合わせる<br>（注4）購買者：ここでは、消費者<br>（注5）情勢：状況", audioUrl:"", question:"66. コンピュータの例を挙げて、筆者が述べていることは何か。", options:["人工物が設計者の意図に反した使われ方をされている。","人工物が設計者の予想以上に社会に影響を与えている。","人工物が人間を補助することで社会が成り立っている。","人工物の製作に社会は大きな影響を与えている。"], answer:1,
    translation:"Qua ví dụ máy tính, tác giả muốn nói điều gì? — Vật nhân tạo gây ảnh hưởng lên xã hội vượt quá dự đoán của người thiết kế.",
    explanation:"「人工物は…その社会に与える影響は設計者の予想を越える場合があり」⇒ ảnh hưởng vượt dự đoán nhà thiết kế ⇒ ②. ①③④ không đúng nội dung ví dụ máy tính. ⇒ ②." },
  { id:"b11-8", passage:"", audioUrl:"", question:"67. 筆者によると、設計者が人工物を設計する時に必要なことは何か。", options:["将来の生活や社会に望むことを人工物に反映させること","人々の価値観を変えるような人工物を考えること","一つの人工物にさまざまな用途をもたせること","現代の最も進んだ科学技術を取り入れること"], answer:0,
    translation:"Theo tác giả, điều người thiết kế cần làm khi thiết kế vật nhân tạo là gì? — Phản ánh mong muốn về cuộc sống và xã hội tương lai vào vật nhân tạo.",
    explanation:"「これからわたしたち一人一人がどんな生活を送り、どのような社会を作り上げたいのかというビジョン…設計者は…人工物にその価値観をもたせることが必要」⇒ phản ánh mong muốn tương lai vào vật nhân tạo ⇒ ①. ②③④ không khớp. ⇒ ①." },
  { id:"b11-9", passage:"", audioUrl:"", question:"68. 売れる製品を作るために、設計者はどうすればいいか。", options:["自身の価値観を捨てて、消費者に共通する価値観を優先する。","社会の状況を調べて、自身の価値観が正しいことを確認する。","消費者のニーズを調べて、消費者と自身の価値観に共通性をもたせる。","マーケットニーズの変化を考慮しながらも、自身の価値観を優先させる。"], answer:2,
    translation:"Để tạo ra sản phẩm bán chạy, người thiết kế nên làm gì? — Tìm hiểu nhu cầu người tiêu dùng, tạo điểm chung giữa giá trị quan của người tiêu dùng và của bản thân.",
    explanation:"「設計者の価値観が購買者の価値観とのなんらかの共通性をもつ必要がある。そのために設計者は…人々の価値観を調査したうえで」⇒ khảo sát nhu cầu, tạo điểm chung ⇒ ③. ①②④ không đúng. ⇒ ③." },
]},
{ tab:"読解", section:"問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction:"次のAとBの文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b12-1", passage:"A<br>自分は歌がうまくないとか、自信がないから人前で歌を歌いたくないと思っている人は多いと思う。実は、そういう人たちはテレビやCDで聞いてなんとなく覚えた歌を、自分の勝手なイメージで歌ってしまっていることが多い。自信を持って歌を歌うには、まず歌詞を理解して曲を覚えることが必要だ。歌詞は何度もよく読むことで、伝えたいメッセージが理解できる。曲も繰り返し聞けば、細かい部分まで聞き取れるようになり、正確に覚えることができる。このようにして歌詞と曲をしっかり覚えたら、あとは歌手のまねをするような気持ちで、自信を持って歌うことだ。いきなり自分らしく歌おうとするのは、失敗のもとなのでやめたほうがいい。<br><br>B<br>どうしたら人の心に響くような歌が歌えるようになるのだろうか。よく歌手のようにうまく歌いたいと思って歌手のまねをして歌っている人がいるが、私はそのような歌を聞いても感動することは少ない。私にとって上手な歌というのは、何よりも歌う人の気持ちが伝わってくる歌だからだ。<br><br>ではどうすれば人を感動させる歌が歌えるのか。それには歌詞を深く理解することが大切だ。単語の意味はもちろん、描かれている状況や感情を丁寧に読み込んでいけば、どこが大切か、どこを強調して歌えばいいかがわかってくるはずだ。歌詞の理解さえ十分にできていれば、多少音を間違えたとしても、メッセージは必ず聞き手に伝えられると思う。", audioUrl:"", question:"69. 歌を歌う前に歌詞を理解することについて、AとBはどのように考えているか。", options:["AもBも、必要だと述べている。","AもBも、あまり必要ではないと述べている。","Aは必要だと述べ、Bはあまり必要ではないと述べている。","Aはあまり必要ではないと述べ、Bは必要だと述べている。"], answer:0,
    translation:"Về việc hiểu lời bài hát trước khi hát, A và B nghĩ thế nào? — Cả A và B đều nói là cần thiết.",
    explanation:"A: 「自信を持って歌を歌うには、まず歌詞を理解して曲を覚えることが必要だ」. B: 「歌詞を深く理解することが大切だ」⇒ cả hai đều cho rằng cần thiết ⇒ ①. ⇒ ①." },
  { id:"b12-2", passage:"", audioUrl:"", question:"70. AとBは、歌を上手に歌うために、どのようなことが重要だと述べているか。", options:["AもBも、歌手のまねをするような気持ちで歌うことだと述べている。","AもBも、歌の強調したいところを意識して歌うことだと述べている。","Aは歌を正確に覚えてから歌うことだと述べ、Bは気持ちを伝えるように歌うことだと述べている。","Aは自分らしく歌おうとしないことだと述べ、Bは自信を持って歌うことだと述べている。"], answer:2,
    translation:"Để hát hay, A và B nói điều gì là quan trọng? — A nói hát sau khi đã nhớ chính xác bài hát, B nói hát sao cho truyền được cảm xúc.",
    explanation:"A: 「歌詞と曲をしっかり覚えたら、あとは歌手のまねをするような気持ちで…」⇒ nhớ chính xác trước. B: 「歌う人の気持ちが伝わってくる歌」「どこを強調して歌えばいいか」⇒ truyền cảm xúc ⇒ ③. ①②④ không khớp với ý hai người. ⇒ ③." },
]},
{ tab:"読解", section:"問題13 主張理解・長文",
  instruction:"次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b13-1", passage:"以下は、会社における評価について書かれた文章である。<br><br>私たちの会社では、志願してくれたのに、採用できなかった学生から、こんな問い合わせを受けることがよくあります。「なぜ、自分は落ちたのでしょうか」と。<br><br>彼らの多くは、筆記試験の成績も優秀で、面接での受け答えのしっかりした学生。合格しなかったのは、単に当社との相性を他の志願者と比べた結果であって、重大な問題があったわけではありません。しかし、彼らの頭の中には、自分と採用しなかった当社との関係しかない。だから、「落ちたのは自分に問題があるから」と考え込んでしまうのでしょう。<br><br>①こういう人は社会に出ても苦労します。上司が他の社員と比べて評価を下していることまで想像が及びませんから、より結果を出している同僚を棚に上げ、「自分はこんなに頑張って、成果を上げているのに評価されない」と悩んでしまう。<br><br>（中略）<br><br>一定の水準を満たした志願者全員が、入社できるわけではありません。一定以上の業績を上げれば、誰でも高い評価が得られるわけでもない。「自分はこれだけ成果を出したから大丈夫」ということはありません。より大きな成果を出した人がいれば、自分の評価が相対的に下がるのは当たり前。大事なのは他者との比較です。単純な話ですが、皆、意外なほど、②この事実に気づいていない。<br><br>成長するためにはまず、「自分は常に他者と比較されている」ということを意識してください。もし、社内での自分の評価を上げたければ、同僚と自分を積極的に比較しましょう。<br><br>よく「人は人、自分は自分」と言います。評価の高い同僚は、あなたとは強みも活躍する領域も違うかもしれません。それでも、同じような時期に生まれ、自分の得意分野を確立し、頭角を現している人がいるなら、その事実に向き合ってください。そして、上司の視点で自分と比べてみる。「自分に足りないもの」や「評価されるには何をすべきか」といったことが見えてくるはずです。<br><br>（注1）志願する：ここでは、応募する<br>（注2）想像が及ばない：想像できない<br>（注3）～を棚に上げる：ここでは、～のことを考えない<br>（注4）業績：仕事の成果<br>（注5）領域：分野<br>（注6）確立する：ここでは、しっかり持つ<br>（注7）頭角を現している人：能力が高くて、目立つ人", audioUrl:"", question:"71. ①こういう人とはどのような人か。", options:["不採用になった理由を、何度説明しても納得しない人","不採用になった理由を、自分自身で深く考えようとしない人","不採用になったのは、評価の仕方がよくないからだと考える人","不採用になったのは、自分自身に悪い点があるからだと考える人"], answer:3,
    translation:"① 'Người như thế này' là người như thế nào? — Người cho rằng mình bị loại vì bản thân có điểm xấu.",
    explanation:"Ngay trước ①: 「『落ちたのは自分に問題があるから』と考え込んでしまうのでしょう」⇒ cho rằng bị loại là vì lỗi của mình ⇒ ④. ①②③ không khớp. ⇒ ④." },
  { id:"b13-2", passage:"", audioUrl:"", question:"72. ②この事実とあるが、どのようなことか。", options:["一定以上の成果を出さなければ、会社では評価されないこと","会社の評価は厳しいので、高い評価はめったに得られないこと","自分より成果を出した人がいれば、自分の評価は下がること","自分の出した成果に満足していると、すぐに他者に追い抜かれること"], answer:2,
    translation:"② 'Sự thật này' là sự thật gì? — Nếu có người đạt thành quả lớn hơn mình thì đánh giá của mình sẽ giảm.",
    explanation:"Ngay trước ②: 「より大きな成果を出した人がいれば、自分の評価が相対的に下がるのは当たり前」⇒ ③. ①②④ không đúng. ⇒ ③." },
  { id:"b13-3", passage:"", audioUrl:"", question:"73. 筆者によると、会社内で高く評価されるにはどうすればいいか。", options:["評価の高い同僚をよく観察し、その行動をまねる。","評価の高い同僚と比べて、自分がすべきことを考える。","同僚とは比べず、自分の得意分野で高い成果を出す。","同僚と比べて自分に何が足りないのかを上司から教えてもらう。"], answer:1,
    translation:"Theo tác giả, để được đánh giá cao trong công ty thì nên làm gì? — So sánh với đồng nghiệp được đánh giá cao, rồi nghĩ xem mình cần làm gì.",
    explanation:"「同僚と自分を積極的に比較しましょう」「上司の視点で自分と比べてみる。『自分に足りないもの』や『評価されるには何をすべきか』といったことが見えてくるはずです」⇒ so sánh rồi nghĩ việc cần làm ⇒ ②. ①③④ không đúng. ⇒ ②." },
]},
{ tab:"読解", section:"問題14 情報検索",
  instruction:"下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b14-1", passage:"文章作成サポートのご案内<br><br>国際センターでは、留学生のみなさんの日本語文章作成を支援するため、訓練を受けた大学院生が文章作成サポートを行います。<br><br>場所：国際センター（5号館）2階 203教室<br>開室曜日：授業期間中の火・木・金曜日<br>利用時間：①〜⑥の時間から、1日につき1回（①11:40〜12:30 ②14:00〜14:50 ③15:00〜15:50 ④16:00〜16:50 ⑤17:00〜17:50 ⑥18:00〜18:50）<br>利用資格：本学の留学生なら誰でも利用できます。<br>サポートの内容：日本語のアカデミックな文章の作成を支援します。<br>対象になる文章：日本語で書かれたアカデミックな文章（例）授業の課題やレポート、卒業論文、研究計画書<br>対象にならない文章：外国語を翻訳した日本語の文章、履歴書など就職関連の文章<br>利用方法：予約の申し込みは実施日の2週間前から前日の昼12時までメールで受け付けます。氏名・所属・相談内容・携帯電話番号・希望日時（できれば第3希望まで）を書いて、下記のメールアドレスに送信してください。折り返し、確定した日時をメールで返信します。一度にできる予約は1回分です。次回の予約ができるのは、予約した回が終了した後になります。予約した時間に連絡なく15分以上遅れた場合はキャンセルとなります。当日は、支援を受けたい文章を2部印刷して持参してください。予約が入っていない時間帯がある場合に限り、当日利用が可能です。直接来室して確認してください。<br><br>大石大学国際センター文章作成サポート室　bunshou@ooishi.ac.jp / 021-543-0001", audioUrl:"", question:"74. 次の4人は、全員大石大学の留学生であり、文章作成サポートを受けたいと考えている。この中で、このサポートを受けられるのは誰か。<br><br>ミウンさん／就職活動用の履歴書／月曜か火曜<br>ラウラさん／卒業論文／月曜か水曜<br>ジョンさん／授業の課題レポート／木曜<br>グエンさん／ベトナム語の文献を翻訳した文章／火曜か木曜", options:["ミウンさん","ラウラさん","ジョンさん","グエンさん"], answer:2,
    translation:"Bốn người sau đều là du học sinh trường Đại học Oishi và muốn được hỗ trợ viết văn. Ai trong số họ có thể nhận được hỗ trợ? — John.",
    explanation:"Điều kiện: mở cửa 火・木・金; loại trừ văn bản không thuộc đối tượng (履歴書, 外国語を翻訳した文章). ミウン (履歴書 → không thuộc đối tượng) loại; ラウラ (đại học thứ 4 có 卒業論文 ✓ nhưng chỉ đi được 月・水 → phòng đóng cửa thứ Hai và thứ Tư) loại; グエン (văn dịch → không thuộc đối tượng) loại; ジョン (báo cáo bài tập ✓, đi được thứ Năm → mở cửa thứ Năm ✓) hợp lệ ⇒ ③ジョンさん." },
  { id:"b14-2", passage:"", audioUrl:"", question:"75. 文章作成サポートを利用する際に、注意すべき点はどれか。", options:["利用したい日の2週間前までに予約しなければならない。","一度の申し込みで、数回分をまとめて予約することはできない。","予約の際、支援を受けたい文章をメールに添付して送らなければならない。","前日までに予約していなければ、空いている時間があっても利用できない。"], answer:1,
    translation:"Khi sử dụng dịch vụ hỗ trợ viết văn, điểm cần lưu ý là gì? — Không thể đặt trước nhiều buổi trong một lần đăng ký.",
    explanation:"「一度にできる予約は1回分です。次回の予約ができるのは、予約した回が終了した後になります」⇒ một lần chỉ đặt được 1 buổi ⇒ ②. ① sai (nhận từ 2 tuần trước đến 12 giờ trưa ngày hôm trước), ③ sai (bài viết nộp 2 bản giấy khi đến, không gửi kèm email), ④ sai (có thể dùng trong ngày nếu còn khung giờ trống). ⇒ ②." },
]},
/* ================= TAB 5: 聴解 ================= */
{ tab:"聴解", section:"問題1 課題理解",
  instruction:"問題1では、まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File đề có kèm 台本 chính thức ở phần「Đoạn」; audio gốc không có trong file.)",
  questions:[
  { id:"c1-1", passage:"【台本】大学で男の学生と女の学生が話しています。女の学生はこの後何をしますか。<br><br>男：鈴木さん、この間頼まれたレポートのチェックだけど。<br>女：あ、先輩、もう見てくださったんですか。<br>男：うん、再調査して対象者の数も増えてよくなったんじゃない。考察も説得力が増して、読んでて面白かったよ。<br>女：本当ですか、ありがとうございます。再調査、思ったより時間がかかって。でも、やってよかったです。<br>男：よく頑張ったねえ。うん、せっかくだから、結果の示し方をもう少し工夫してたら? 表ばっかりじゃなくて、少しグラフも入れとくとか。もう少しパッと見てわかるように。<br>女：あ、はい。<br>男：それにしても、この分析方法、面白いね。今度僕も使ってみよう。", audioUrl:"", question:"1番：女の学生はこの後何をしますか。", options:["対象者の数を増やす","考察をもっと詳しく書く","結果の見せ方を変える","分析の方法を変える"], answer:2,
    translation:"(Script) Ở trường đại học, nam và nữ sinh viên nói chuyện. Sau đó nữ sinh sẽ làm gì? Nam: Suzuki, về việc kiểm tra báo cáo tôi nhờ cậu lần trước ấy. Nữ: À, tiền bối đã xem giúp em rồi ạ? Nam: Ừ, điều tra lại tăng số đối tượng nên tốt hơn hẳn. Phần phân tích cũng thuyết phục hơn, đọc thú vị lắm. Nữ: Thật ạ, cảm ơn anh. Điều tra lại mất thời gian hơn em tưởng. Nhưng làm thì tốt. Nam: Cố gắng lắm. Nhân tiện, sao không khéo léo thêm chút ở cách trình bày kết quả? Đừng chỉ toàn bảng, thêm chút biểu đồ nữa. Để nhìn phát hiểu ngay. Nữ: À vâng. Nam: Mà cách phân tích này thú vị nhỉ. Lần sau tôi cũng thử dùng.",
    explanation:"Đáp án 3. Nam khuyên 「結果の示し方をもう少し工夫してたら?…少しグラフも入れとくとか」⇒ đổi cách trình bày kết quả ⇒ ③. ① đã làm xong (再調査して対象者の数も増えて), ② đã được khen (考察も説得力が増して), ④ nam nói mình sẽ dùng chứ không bảo nữ đổi. ⇒ ③." },
  { id:"c1-2", passage:"【台本】会社で男の人と女の人が話しています。女の人はこのあと、まず何をしなければなりませんか。<br><br>男：佐藤さん、そろそろ会員向けの案内を出さなきゃいけないんだけど。<br>女：はい。<br>男：印刷屋さんから案内のはがきが出来上がってきたから、あて名のシールを作ってくれるかな。会員の情報をまとめたファイル、わかるよね。あれ使って作成して。あ、郵送物を希望していないお客さんにはメールで送るから、シールはいらないよ。<br>女：はい。会員情報のファイルは更新されてるんですか。<br>男：うん、されてるよ。個人情報だから、気をつけて作業してね。<br>女：はい。メールのほうも私が送りますか。<br>男：まだ文章を準備してないから、今日はいいよ。<br>女：わかりました。", audioUrl:"", question:"2番：女の人はこのあと、まず何をしなければなりませんか。", options:["案内のはがきを印刷する","あて名のシールを作る","会員情報のファイルを更新する","メールの文章を作成する"], answer:1,
    translation:"(Script) Ở công ty, nam và nữ nói chuyện. Sau đó nữ phải làm gì trước tiên? Nam: Chị Sato, sắp tới phải gửi thông báo cho hội viên rồi. Nữ: Vâng. Nam: Bưu thiếp thông báo từ nhà in đã xong, chị làm nhãn dán tên người nhận giúp nhé. File tổng hợp thông tin hội viên, chị biết chứ. Dùng nó để tạo. À, khách không muốn nhận bưu phẩm thì gửi email, không cần nhãn. Nữ: Vâng. File thông tin hội viên đã cập nhật chưa ạ? Nam: Rồi. Vì là thông tin cá nhân nên chị làm cẩn thận nhé. Nữ: Vâng. Phần email em gửi luôn không? Nam: Văn bản chưa chuẩn bị nên hôm nay thôi. Nữ: Vâng, em hiểu rồi.",
    explanation:"Đáp án 2. Nam nhờ 「あて名のシールを作ってくれるかな」⇒ việc đầu tiên là tạo nhãn dán tên người nhận ⇒ ②. ① bưu thiếp đã in xong, ③ file đã được cập nhật, ④ email để hôm khác. ⇒ ②." },
  { id:"c1-3", passage:"【台本】大学で女の学生と男の学生が話しています。女の学生はこのあと何をしますか。<br><br>女：先輩、去年の夏休みに農業体験行かれたんですよね。大学が主催してる。あれ、私も来週から一ヶ月行くんです。何か持ってったほうがいいものとかありますか。<br>男：保険証。去年忘れた人がいて大変だったんだよ。コピーすら持ってきてなくて。僕らみたいな素人が農業をやるときは、思わぬ怪我とかあるから忘れないように気をつけて。<br>女：はい、いつも持ち歩いてます。<br>男：そう。それから、Tシャツは多めに持ってったほうがいいよ。作業着の中に着るんだけど、作業をしてると想像以上に汗を掻くからね。作業着とか長靴は貸してもらえるよ。よく実習生が来るからか、いろんなサイズのがあったよ。<br>女：よかった。長靴買わなきゃって思ってたけど。Tシャツは、作業着があるからいいかなって思って、部屋着ぐらいしか用意してませんでした。<br>男：そうそう。実は去年、僕、健康診断を受けるのを忘れてて、もう少しで参加できなくなりそうだったんだよ。<br>女：へえ、で、どうしたんですか。<br>男：診断書をすぐ出してくれる病院を探して、なんとか間に合ったんだけどね。<br>女：ああ、それで今年は提出が先週までだったんですね。", audioUrl:"", question:"3番：女の学生はこのあと何をしますか。", options:["保険証のコピーを提出する","作業着の中に着るものを用意する","長靴を買う","健康診断書を提出する"], answer:1,
    translation:"(Script) Ở đại học, nữ và nam sinh nói chuyện. Sau đó nữ sinh sẽ làm gì? Nữ: Tiền bối, hè năm ngoái anh có đi trải nghiệm nông nghiệp phải không ạ, do trường tổ chức ấy. Tuần sau em cũng đi một tháng. Có gì nên mang theo không ạ? Nam: Thẻ bảo hiểm. Năm ngoái có người quên, khổ lắm, đến bản photo cũng không mang. Dân tay ngang như bọn mình làm nông dễ bị thương bất ngờ, nhớ đừng quên. Nữ: Vâng, em lúc nào cũng mang theo. Nam: Ừ. Ngoài ra nên mang nhiều áo phông. Mặc trong đồ bảo hộ, mà làm việc thì ra mồ hôi hơn mình tưởng. Đồ bảo hộ với ủng thì được cho mượn, chắc vì hay có thực tập sinh nên đủ cỡ. Nữ: Hay quá. Em còn định mua ủng. Áo phông thì em nghĩ có đồ bảo hộ rồi nên chỉ chuẩn bị đồ mặc ở nhà. Nam: Ừ. Thật ra năm ngoái tôi quên khám sức khỏe, suýt không tham gia được. Nữ: Vậy ạ, rồi anh làm sao? Nam: Tìm bệnh viện cấp giấy chẩn đoán ngay, may kịp. Nữ: À, vậy nên năm nay hạn nộp là tuần trước nhỉ.",
    explanation:"Đáp án 2. Nam khuyên 「Tシャツは多めに持ってったほうがいいよ。作業着の中に着るんだけど」; nữ nói mình chỉ có đồ mặc ở nhà ⇒ nữ cần chuẩn bị đồ mặc bên trong đồ bảo hộ ⇒ ②. ① nữ luôn mang theo thẻ bảo hiểm, ③ ủng được cho mượn nên không cần mua, ④ đã nộp tuần trước. ⇒ ②." },
  { id:"c1-4", passage:"【台本】市役所の国際交流課で、男の人と女の人が話しています。男の人はこれから、まず何をしなければなりませんか。<br><br>男：課長、来月の料理教室のことなんですが。<br>女：あ、料理教室の話ですね。誰でも家で作れるものっていうことで、メニューも決めたんですよね。<br>男：ええ、講師の方と打ち合わせして材料のリストもらったんです。僕が材料を人数分まとめて揃えることになってるんですけど、聞いたことのない材料があって、取り寄せないといけないみたいなんですよ。<br>女：その辺で買えるもので代わりにできないか、講師の先生に相談してください。難しいようなら、メニュー、変更ですね。<br>男：わかりました。<br>女：作り方が簡単でも、材料が近所で手に入るものでないとね。<br>男：そうですね。メニューが変更になったら、参加者にも知らせます。", audioUrl:"", question:"4番：男の人はこれから、まず何をしなければなりませんか。", options:["講師に材料について相談する","材料のリストを作る","代わりになる材料を調べる","参加者にメニューの変更を知らせる"], answer:0,
    translation:"(Script) Ở phòng giao lưu quốc tế của tòa thị chính, nam và nữ nói chuyện. Nam sắp tới phải làm gì trước tiên? Nam: Trưởng phòng, về lớp học nấu ăn tháng sau ạ. Nữ: À, chuyện lớp nấu ăn nhỉ. Vì chọn món ai cũng làm được ở nhà nên đã quyết thực đơn rồi mà. Nam: Vâng, tôi đã bàn với giảng viên và nhận danh sách nguyên liệu. Tôi được giao gom đủ nguyên liệu cho từng người, nhưng có loại nguyên liệu chưa từng nghe, hình như phải đặt mua. Nữ: Hãy hỏi giảng viên xem có thể thay bằng thứ mua quanh đây không. Nếu khó thì đổi thực đơn. Nam: Vâng. Nữ: Cách làm dù đơn giản mà nguyên liệu không mua được gần nhà thì cũng không được. Nam: Đúng ạ. Nếu đổi thực đơn tôi sẽ thông báo cho người tham gia.",
    explanation:"Đáp án 1. Nữ nói 「その辺で買えるもので代わりにできないか、講師の先生に相談してください」⇒ nam phải hỏi giảng viên về nguyên liệu ⇒ ①. ② danh sách đã có, ③④ là việc về sau. ⇒ ①." },
  { id:"c1-5", passage:"【台本】学生の勉強会で、司会の人が話しています。参加者はこのあと、まず何をしますか。<br><br>今日は、大学合同勉強会にご参加いただき、ありがとうございます。これから、世界が今抱えている諸問題についてグループ討論を行い、理解を深めていきます。皆さん、すでにグループに分かれてますね。お配りしてある名札に〇のついている人がグループのリーダーです。リーダーを中心に、話し合いを進めていただきます。予め、皆さんに選んでいただいた課題について議論し、どのような対応ができるか、グループごとに意見をまとめて発表してください。本題に入る前に、自己紹介も兼ねて、皆さんが今取り組んでいる研究テーマについて話してください。リラックスしてから、話し合いに入りましょう。", audioUrl:"", question:"5番：参加者はこのあと、まず何をしますか。", options:["グループのリーダーを決める","話し合う課題を選ぶ","意見をまとめて発表する","自分の研究テーマを紹介する"], answer:3,
    translation:"(Script) Trong buổi học nhóm của sinh viên, người dẫn chương trình đang nói. Sau đó người tham gia sẽ làm gì trước tiên? Hôm nay cảm ơn các bạn đã tham gia buổi học nhóm liên trường. Từ giờ chúng ta sẽ thảo luận nhóm về các vấn đề thế giới đang gặp phải để hiểu sâu hơn. Các bạn đã chia nhóm rồi nhỉ. Người có dấu ○ trên thẻ tên được phát là nhóm trưởng. Hãy thảo luận xoay quanh nhóm trưởng. Các bạn sẽ thảo luận về đề tài đã chọn trước, rồi tổng hợp ý kiến và trình bày theo nhóm xem có thể ứng phó thế nào. Trước khi vào nội dung chính, kết hợp tự giới thiệu, hãy nói về đề tài nghiên cứu hiện tại của mình. Thư giãn rồi hẵng vào thảo luận.",
    explanation:"Đáp án 4. 「本題に入る前に、自己紹介も兼ねて、皆さんが今取り組んでいる研究テーマについて話してください」⇒ việc đầu tiên là giới thiệu đề tài nghiên cứu ⇒ ④. ① nhóm trưởng đã được chỉ định (名札に〇), ② đề tài đã chọn trước, ③ là việc sau khi thảo luận. ⇒ ④." },
]},
{ tab:"聴解", section:"問題2 ポイント理解",
  instruction:"問題2では、まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File đề có kèm 台本 chính thức ở phần「Đoạn」.)",
  questions:[
  { id:"c2-1", passage:"【台本】大学で映画サークルの男の学生と女の学生があるアニメについて話しています。女の学生は、このアニメのどんなところに魅力を感じたと言っていますか。<br><br>男：桜映画祭で金賞を取ったアニメ、見たんだって。どうだった? 300年前の日本が舞台になってるんでしょう。<br>女：うん、歴史的な事実も丁寧に織ってるから。歴史好きの人にはそこが楽しめるんじゃないかな。<br>男：うん。<br>女：私は、自分が音楽やってるせいか、いつもは、BGM音楽に気を取られるんだけど。これ、物語の展開にインパクトがあってね。なんていうか、何度も予想を裏切られて、はらはらどきどきしっぱなし。今までは、映画は音楽次第って思ってたんだけど。<br>男：そうなんだ。<br>女：新聞じゃ、登場人物の心の変化が丁寧に描かれてるって評価だよね。その見方は、私はよくわからなかったけど。", audioUrl:"", question:"1番：女の学生は、このアニメのどんなところに魅力を感じたと言っていますか。", options:["歴史的な事実を反映しているところ","テーマに合った音楽が使われているところ","話の展開に意外性があるところ","人物の気持ちがていねいに表現されているところ"], answer:2,
    translation:"(Script) Ở đại học, nam và nữ sinh của câu lạc bộ điện ảnh nói về một bộ anime. Nữ sinh nói cảm thấy sức hút của bộ anime ở điểm nào? Nam: Nghe nói cậu xem bộ anime đoạt giải vàng ở liên hoan phim Sakura. Lấy bối cảnh Nhật Bản 300 năm trước mà nhỉ. Nữ: Ừ, vì dệt các sự kiện lịch sử cũng tỉ mỉ, người thích lịch sử chắc thấy thú vị ở đó. Nam: Ừ. Nữ: Tớ thì vì bản thân làm âm nhạc nên bình thường hay để ý nhạc nền. Bộ này diễn biến câu chuyện gây ấn tượng mạnh. Nói sao nhỉ, liên tục bị phá vỡ dự đoán, hồi hộp không thôi. Trước giờ tớ nghĩ phim hay là nhờ nhạc. Nam: Vậy à. Nữ: Trên báo đánh giá là miêu tả tỉ mỉ sự biến đổi tâm lý nhân vật. Cách nhìn đó tớ không hiểu lắm.",
    explanation:"Đáp án 3. 「物語の展開にインパクトがあって…何度も予想を裏切られて、はらはらどきどきしっぱなし」⇒ diễn biến có sự bất ngờ ⇒ ③. ① là điều nữ nói 'người thích lịch sử' sẽ thấy hay (không phải bản thân), ② nữ nói mình thường để ý nhạc nhưng lần này lại là điểm khác, ④ là đánh giá trên báo mà nữ nói 'không hiểu lắm'. ⇒ ③." },
  { id:"c2-2", passage:"【台本】空港で男の人と係りの人が話しています。東京行きの飛行機の出発時間が遅れている理由は何ですか。<br><br>男：すみません、さっきの放送、よく聞こえなかったんですが。東京行きの便、出発時間、変更になったんですか。<br>女：はい。大変申し訳ございません。一時間遅れで、12時15分の出発に変更となりました。<br>男：えっ、そんなに?<br>女：申し訳ございません。東京便として使う予定の飛行機がまだこちらの空港に到着していないんです。雪で出発が遅れまして。<br>男：あ、そうなんですか。チェックインカウンターが込んでいたので、それで遅れているのかと思ったんですが。<br>女：本当に申し訳ございません。もう間もなく到着する予定でして、清掃が終わり次第、東京行きのお客様をご案内いたします。<br>男：わかりました。故障ってわけじゃないんですよね。だったらこれ以上遅れるってことはないですよね。<br>女：はい。恐れ入りますが、もう少々お待ちください。", audioUrl:"", question:"2番：東京行きの飛行機の出発時間が遅れている理由は何ですか。", options:["使う予定の飛行機の到着が遅れているから","チェックインカウンターが込んでいるから","飛行機の清掃に時間がかかっているから","飛行機に故障が見つかったから"], answer:0,
    translation:"(Script) Ở sân bay, nam và nhân viên nói chuyện. Vì sao giờ khởi hành chuyến bay đi Tokyo bị hoãn? Nam: Xin lỗi, thông báo lúc nãy tôi nghe không rõ. Chuyến đi Tokyo đổi giờ khởi hành ạ? Nữ: Vâng. Thành thật xin lỗi. Hoãn một tiếng, đổi sang khởi hành lúc 12 giờ 15. Nam: Ơ, lâu vậy ạ? Nữ: Xin lỗi. Máy bay dự định dùng cho chuyến Tokyo vẫn chưa đến sân bay này. Vì tuyết nên khởi hành muộn. Nam: À vậy ạ. Tôi tưởng vì quầy check-in đông nên bị chậm. Nữ: Thành thật xin lỗi. Dự kiến sắp đến, vệ sinh xong sẽ hướng dẫn hành khách đi Tokyo. Nam: Hiểu rồi. Không phải hỏng hóc chứ. Vậy thì không trễ thêm nữa nhỉ. Nữ: Vâng. Xin quý khách đợi thêm chút.",
    explanation:"Đáp án 1. 「東京便として使う予定の飛行機がまだこちらの空港に到着していないんです。雪で出発が遅れまして」⇒ máy bay chưa đến ⇒ ①. ② nam đoán nhưng nhân viên phủ nhận, ③ vệ sinh làm sau khi đến chứ không gây trễ, ④ nhân viên nói không phải hỏng. ⇒ ①." },
  { id:"c2-3", passage:"【台本】日本語の教室で男の人が話しています。男の人はどうして、今、日本語を勉強していますか。<br><br>男：私は来日して三年になります。和菓子がきっかけで日本に興味を持ち、日本語を学ぶようになりました。和菓子職人を目指していた時期もありましたが、昨年、食品会社に就職し、平日は仕事、週末は日本語教室に通う日々です。毎日の暮らしの中で言葉で不自由を感じることはありませんが、職場ではまだまだ力が足りないなあと感じる場面があり、日本語教室で学ぶことはたくさんあると感じています。", audioUrl:"", question:"3番：男の人はどうして、今、日本語を勉強していますか。", options:["和菓子を作る職人になりたいから","日本の会社に就職したいから","仕事をするのに十分ではないから","日常生活で不自由を感じているから"], answer:2,
    translation:"(Script) Trong lớp tiếng Nhật, một người đàn ông nói. Vì sao anh ấy hiện đang học tiếng Nhật? Nam: Tôi đến Nhật được ba năm. Nhờ bánh wagashi mà tôi hứng thú với Nhật Bản và bắt đầu học tiếng Nhật. Có thời kỳ tôi hướng tới làm nghệ nhân wagashi, năm ngoái tôi vào làm công ty thực phẩm, ngày thường đi làm, cuối tuần đi lớp tiếng Nhật. Trong sinh hoạt hằng ngày tôi không thấy bất tiện về ngôn ngữ, nhưng ở nơi làm việc có những lúc tôi thấy mình còn yếu kém, và cảm thấy học ở lớp tiếng Nhật còn nhiều điều.",
    explanation:"Đáp án 3. 「職場ではまだまだ力が足りないなあと感じる場面があり」⇒ tiếng Nhật chưa đủ để làm việc ⇒ ③. ① đã không còn theo đuổi (和菓子職人を目指していた時期もありましたが), ② đã vào công ty rồi, ④ anh nói sinh hoạt hằng ngày không bất tiện. ⇒ ③." },
  { id:"c2-4", passage:"【台本】女の人と男の人が、虫の飼い方について話しています。男の人は、女の人の虫の飼い方の何に問題があると言っていますか。<br><br>女：あのう、田中さん、虫に詳しいって聞いたんだけど、ちょっと聞いてもいい?<br>男：どうしたの?<br>女：うちで子どもとかぶとむしを飼い始めたんだけど、最近元気がなくて、飼い方に問題があるのかなあ。<br>男：飼い方で大事なのは土、温度管理、餌の量、ケースの大きさだけど、何か気になることある?<br>女：ううん、ケースは3匹いるから、餌の取り合いにならないように大きめのにしてるんだ。温度管理は小型の扇風機もつけてるし、特に日中は温度が30度以上にならないように気をつけてて。土は潜りやすいように、できるだけやわらかいのにしてるよ。<br>男：あ、わかった。<br>女：え?<br>男：扇風機回すと土全体が乾燥しちゃうんだ。土の中にいるときに体から水分を吸収してるんだよ。<br>女：そうなの? えさの量が足りないのかなとか考えてたけど。ああ、だから元気がなかったのね、なるほど。", audioUrl:"", question:"4番：男の人は、女の人の虫の飼い方の何に問題があると言っていますか。", options:["土の水分が不足していること","温度の管理ができていないこと","えさの量が適切ではないこと","ケースが小さすぎること"], answer:0,
    translation:"(Script) Nữ và nam nói về cách nuôi côn trùng. Nam nói cách nuôi của nữ có vấn đề ở điểm nào? Nữ: Này anh Tanaka, nghe nói anh rành côn trùng, cho tôi hỏi chút được không? Nam: Sao thế? Nữ: Nhà tôi bắt đầu nuôi bọ hung với con, nhưng dạo này không khỏe, chắc do cách nuôi có vấn đề. Nam: Điều quan trọng là đất, kiểm soát nhiệt độ, lượng thức ăn, độ lớn hộp, có gì băn khoăn không? Nữ: Không, hộp vì có 3 con nên tôi dùng loại to để không tranh thức ăn. Nhiệt độ có gắn quạt nhỏ, nhất là ban ngày để ý không vượt 30 độ. Đất tôi để mềm nhất có thể cho dễ chui. Nam: À, hiểu rồi. Nữ: Hả? Nam: Quạt chạy làm cả đất bị khô. Khi ở trong đất chúng hút nước từ đất. Nữ: Vậy à? Tôi cứ nghĩ do thiếu thức ăn. À, ra là vậy nên mới không khỏe.",
    explanation:"Đáp án 1. Nam nói 「扇風機回すと土全体が乾燥しちゃうんだ。土の中にいるときに体から水分を吸収してる」⇒ đất bị khô, thiếu nước ⇒ ①. ② nữ đã kiểm soát nhiệt độ, ③ đúng là nữ nghi ngờ nhưng không phải nguyên nhân, ④ hộp đã dùng loại to. ⇒ ①." },
  { id:"c2-5", passage:"【台本】市役所で、男の職員と女の職員が話しています。女の職員が、講演会について反省していることは何ですか。<br><br>男：斉藤さん、昨日の食事に関する講演会、どうだった?<br>女：あ、課長、今ご報告に伺おうと思っていたところです。おかげさまで、会場の座席が全部埋まるほどの人で、ポスターを掲示する地域を拡大したのがよかったんでしょうか。<br>男：そうか。<br>女：講演後にアンケートを取ったんですけど、参加者の感想からは、調理法など実践的な内容が喜ばれたことがわかりました。講演中も、熱心にメモをしている方が何人かいたので、材料や作り方を書いたものをお配りしておけばよかったと思います。<br>男：今回資料は用意しなかったもんね。<br>女：はい。それから、今回は新しい会場を使ったんですが、先生の近くで話が聞けてよかったという声も多くいただきました。<br>男：それはよかった。<br>女：はい。会場の大きさって重要ですね。いろいろご意見いただけてよかったので、アンケートは、次回もぜひ実施すべきだと思いました。", audioUrl:"", question:"5番：女の職員が、講演会について反省していることは何ですか。", options:["会場がせますぎたこと","ポスターを貼った場所が少なかったこと","アンケートを実施しなかったこと","参加者に資料を配らなかったこと"], answer:3,
    translation:"(Script) Ở tòa thị chính, nam và nữ nhân viên nói chuyện. Nữ nhân viên thấy hối tiếc (cần rút kinh nghiệm) điều gì về buổi diễn thuyết? Nam: Chị Saito, buổi diễn thuyết về ăn uống hôm qua thế nào? Nữ: À trưởng phòng, em đang định đến báo cáo đây. Nhờ ơn, người đến đông kín cả chỗ ngồi, chắc nhờ mở rộng khu vực dán poster. Nam: Vậy à. Nữ: Sau diễn thuyết em lấy bảng hỏi, cảm nhận người tham gia cho thấy nội dung thực tiễn như cách chế biến được ưa thích. Trong buổi có vài người chăm chú ghi chép, nên em nghĩ giá mà đã phát tài liệu ghi nguyên liệu và cách làm. Nam: Lần này không chuẩn bị tài liệu nhỉ. Nữ: Vâng. Ngoài ra lần này dùng hội trường mới, nhiều người nói được nghe gần thầy nên tốt. Nam: Tốt quá. Nữ: Vâng. Độ lớn hội trường quan trọng thật. Nhận được nhiều ý kiến nên em nghĩ bảng hỏi lần sau cũng nên làm.",
    explanation:"Đáp án 4. 「材料や作り方を書いたものをお配りしておけばよかったと思います」・「今回資料は用意しなかったもんね」⇒ hối tiếc vì không phát tài liệu ⇒ ④. ① hội trường kín chỗ (thành công), ② poster mở rộng khu vực (thành công), ③ có làm bảng hỏi. ⇒ ④." },
]},
{ tab:"聴解", section:"問題3 概要理解",
  instruction:"問題3では、問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。（せんたくし được in trong phần 台本 của đề gốc.)",
  questions:[
  { id:"c3-1", passage:"【台本】テレビでレポーターがある鉄道について話しています。<br><br>女：私は今山川鉄道の山川駅に来ています。屋根のない小さな駅なんですが、可愛らしい列車が一両発車を待っています。普段は静かな駅ですが、今日は朝から大変混雑しています。この山川鉄道、今日の最終列車の運転を最後に一世紀近くの歴史に幕を下ろすことになりました。沿線にも、その姿を一目見ようとカメラを持った大勢の鉄道ファンや観光客が集まっています。", audioUrl:"", question:"1番：レポーターは山川鉄道の何について話していますか。", options:["運転最終日の様子","廃止される理由","利用客の増加","観光客を集める工夫"], answer:0,
    translation:"(Script) Trên truyền hình, phóng viên nói về một tuyến đường sắt. Phóng viên nói về điều gì của tuyến đường sắt Yamakawa? — Khung cảnh ngày chạy cuối cùng. Nữ: Tôi đang ở ga Yamakawa của tuyến đường sắt Yamakawa. Một ga nhỏ không mái che, nhưng có đoàn tàu xinh xắn một toa đang chờ khởi hành. Bình thường ga yên tĩnh, hôm nay từ sáng đã rất đông. Tuyến Yamakawa này, sau chuyến tàu cuối cùng hôm nay sẽ khép lại lịch sử gần một thế kỷ. Dọc tuyến, đông đảo người hâm mộ đường sắt và du khách cầm máy ảnh cũng tụ tập để nhìn thấy hình bóng ấy một lần.",
    explanation:"Đáp án 1. Cả bài nói về ngày cuối cùng: 「今日の最終列車の運転を最後に一世紀近くの歴史に幕を下ろす」「今日は朝から大変混雑」⇒ khung cảnh ngày chạy cuối ⇒ ①. ② không nêu lý do bãi bỏ, ③ không bàn số lượng tăng, ④ không nói mẹo thu hút du khách (chỉ nhắc du khách tụ tập). ⇒ ①." },
  { id:"c3-2", passage:"【台本】テレビでアナウンサーが女の人にインタビューしています。<br><br>男：今日はペットの服を作っている山田さんにお越しいただきました。<br>女：よろしくお願いします。今日は飼い犬のしろと一緒に来ました。しろが着ているこの服、私が初めて作った服なんです。<br>男：とっても素敵ですね。でも、おしゃれが目的だったわけじゃないんですよね?<br>女：ええ、しろは気温差に弱く、皮膚が弱い犬で、体調管理のために服が必要なんです。でも、市販の服だとサイズがぴったりとは合わないので、動きにくいんでしょうね。着るのを嫌がって。それなら自分で作ろうと思いまして。やわらかい生地で動きを邪魔しないようなデザインにしたら、しろも嫌がらずに着てくれたんです。<br>男：そうですか。<br>女：何枚か作ってるうちに、いろんな犬の服を作りたくなってきて、インターネットで販売を始めたら、どんどん注文が入ってきたんです。お客様をお待たせしてしまっているのが現状ですが、一着一着心をこめて製作しています。<br>男：しろも愛情に包まれてあたたかそうですね。お話ありがとうございました。", audioUrl:"", question:"2番：女の人は何について話していますか。", options:["ペットの服を作る難しさ","ペットの体調管理の注意点","ペットの服を作り始めたきっかけ","ペット用品が売れている理由"], answer:2,
    translation:"(Script) Trên TV, người dẫn chương trình phỏng vấn một người phụ nữ. Người phụ nữ nói về điều gì? — Cơ duyên bắt đầu làm quần áo cho thú cưng. Nam: Hôm nay chúng tôi mời chị Yamada, người làm quần áo cho thú cưng. Nữ: Rất hân hạnh. Hôm nay tôi đến cùng chú chó cưng Shiro. Bộ đồ Shiro đang mặc là bộ tôi làm đầu tiên. Nam: Đẹp quá. Nhưng mục đích không phải thời trang nhỉ? Nữ: Vâng, Shiro yếu với chênh lệch nhiệt độ, da yếu, nên cần quần áo để quản lý sức khỏe. Nhưng đồ bán sẵn không vừa kích cỡ nên khó cử động, nó không chịu mặc. Thế nên tôi nghĩ tự làm. May bằng vải mềm, thiết kế không cản trở vận động thì Shiro chịu mặc. Nam: Vậy à. Nữ: Trong khi làm vài bộ, tôi muốn làm quần áo cho nhiều chú chó, bắt đầu bán trên mạng thì đơn đặt hàng vào liên tục. Hiện đang để khách phải chờ, nhưng tôi làm từng bộ một bằng cả tấm lòng. Nam: Shiro trông ấm áp trong tình yêu thương nhỉ. Cảm ơn chị.",
    explanation:"Đáp án 3. Trọng tâm là cơ duyên: 「しろは…体調管理のために服が必要なんです。でも、市販の服だとサイズがぴったりとは合わない…それなら自分で作ろうと思いまして」⇒ bắt đầu làm quần áo cho thú cưng ⇒ ③. ①④ không phải trọng tâm, ② chỉ là lý do dẫn dắt. ⇒ ③." },
  { id:"c3-3", passage:"【台本】ラジオでアナウンサーが話しています。<br><br>今日は天気雨の現象があちこちで観察されました。空に雲一つなく晴れているのに突然雨が降るというこの現象、どのように起きるのか、皆さん案外ご存じないんじゃないでしょうか。天気雨は雨の粒が雨雲から落ちた後に雲が消えたり動いたりしたために発生します。雨の粒が強い風で飛ばされて雲から離れたところに降ることで発生する場合もあります。できれば、突然の雨は避けたいものですが、雨の粒に日の光が当たるのはきれいですよね。同様の現象は冬にも雪で見られるんですよ。", audioUrl:"", question:"3番：アナウンサーは何について話していますか。", options:["天気雨を予測する方法","天気雨が降る仕組み","天気雨を避ける方法","天気雨が多い季節"], answer:1,
    translation:"(Script) Trên radio, phát thanh viên đang nói. Phát thanh viên nói về điều gì? Hôm nay hiện tượng mưa nắng được quan sát ở nhiều nơi. Trời trong xanh không một gợn mây mà bỗng nhiên mưa, hiện tượng này xảy ra thế nào chắc các bạn khá bất ngờ. Mưa nắng xảy ra do hạt mưa rơi từ mây mưa xong thì mây tan đi hoặc di chuyển. Cũng có trường hợp hạt mưa bị gió mạnh thổi bay rơi xuống nơi cách xa mây. Nếu được thì muốn tránh mưa bất chợt, nhưng ánh nắng chiếu vào hạt mưa đẹp nhỉ. Hiện tượng tương tự mùa đông cũng thấy với tuyết.",
    explanation:"Đáp án 2. Bài giải thích cơ chế: 「天気雨は雨の粒が雨雲から落ちた後に雲が消えたり動いたりしたために発生します…」⇒ cơ chế hình thành mưa nắng ⇒ ②. ①③④ không phải nội dung bài. ⇒ ②." },
  { id:"c3-4", passage:"【台本】テレビでアナウンサーが話しています。<br><br>今、若葉町の中央高校に来ています。去年からこちらの高校の校門の前で記念写真を取ろうという外国人の観光客がたくさん訪れるようになりました。それは、この高校で映画『青春スーツ』が撮影されたためです。この映画は10年前に日本で公開され、大変話題になりました。この映画に出演していた俳優の青木たくやさんが去年別の映画で世界的な映画賞を取ったことで、海外でもこの映画が注目されるようになったんだそうです。高校だけでなく、町のあちこちにこの映画が撮影された場所があり、ファンに大変人気があるとのことです。", audioUrl:"", question:"4番：アナウンサーは何について話していますか。", options:["海外からこの町を訪れる人が増えた理由","この映画が日本で話題になった理由","ある俳優が映画賞を取った理由","この町で映画が撮影された理由"], answer:0,
    translation:"(Script) Trên truyền hình, phát thanh viên đang nói. Phát thanh viên nói về điều gì? Hiện tôi đang ở trường trung học trung tâm thị trấn Wakaba. Từ năm ngoái, nhiều du khách nước ngoài bắt đầu đến trước cổng trường này để chụp ảnh kỷ niệm. Đó là vì bộ phim 'Thanh xuân Suits' được quay ở trường này. Phim công chiếu ở Nhật cách đây 10 năm và gây nhiều chú ý. Diễn viên Aoki Takuya tham gia phim này năm ngoái đoạt giải điện ảnh tầm cỡ thế giới ở một phim khác, nhờ đó bộ phim trở nên được chú ý cả ở nước ngoài. Không chỉ ngôi trường, nhiều nơi trong thị trấn có bối cảnh quay phim và rất được fan yêu thích.",
    explanation:"Đáp án 1. Trọng tâm: 「去年から…外国人の観光客がたくさん訪れるようになりました。それは、この高校で映画…が撮影されたためです…海外でもこの映画が注目されるようになった」⇒ lý do du khách nước ngoài tăng là do bộ phim ⇒ ①. ②③④ chỉ là các chi tiết phụ. ⇒ ①." },
  { id:"c3-5", passage:"【台本】町の会議で議員が話しています。<br><br>昨年度の調査によると、わが川中町ではだれも住んでいない空家がこの十年で二倍に増えていることが明らかになりました。空家の増加は地域の防犯上、深刻な問題です。火災の発見が遅れたり、建物が古くなって崩れたりする危険もあります。そして空家は早急に取り壊すべきだという意見が出ていますが、再生させる道を探るほうがいいのではないでしょうか。全国の例を調べてみますと、自治体が空家を管理し、商業施設として再生させているところもあり、人を呼び込むことにつながっている例もあります。", audioUrl:"", question:"5番：議員が言いたいことは何ですか。", options:["空家の数を調べるべきだ","空家を早く取り壊すべきだ","空家を活用すべきだ","空家が増えた理由を調べるべきだ"], answer:2,
    translation:"(Script) Trong cuộc họp của thị trấn, một nghị viên đang nói. Nghị viên muốn nói điều gì? Theo điều tra năm ngoái, ở thị trấn Kawakana chúng ta, nhà bỏ trống không ai ở đã tăng gấp đôi trong mười năm này. Nhà bỏ trống tăng là vấn đề nghiêm trọng về an ninh khu vực. Cũng có nguy cơ phát hiện hỏa hoạn chậm trễ, công trình cũ nát rồi sụp đổ. Có ý kiến cho rằng nên phá dỡ nhà bỏ trống ngay, nhưng phải chăng nên tìm cách tái sinh chúng tốt hơn. Khảo sát ví dụ cả nước thì có nơi chính quyền địa phương quản lý nhà bỏ trống và tái sinh thành cơ sở thương mại, cũng có ví dụ dẫn tới việc thu hút người đến.",
    explanation:"Đáp án 3. 「再生させる道を探るほうがいいではないでしょうか…商業施設として再生させているところもあり、人を呼び込むことにつながっている」⇒ nên tận dụng (tái sinh) nhà bỏ trống ⇒ ③. ① đã điều tra số lượng, ② là ý kiến phá dỡ mà nghị viên phản đối, ④ không phải trọng tâm. ⇒ ③." },
]},
{ tab:"聴解", section:"問題4 即時応答",
  instruction:"問題4では、問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c4-1", passage:"【台本】1番：女：李さん、昨日のプレゼンで李さんを見直しちゃった。<br>1.それじゃ、もう一度見直してみる。<br>2.ええ、頑張ったんだけどな。<br>3.そう? ありがとう。", audioUrl:"", question:"1番", options:["それじゃ、もう一度見直してみる。","ええ、頑張ったんだけどな。","そう? ありがとう。"], answer:2,
    translation:"(Script) 1: Nữ: Anh Lý, trong buổi thuyết trình hôm qua tôi đã nhìn anh bằng ánh mắt khác (đánh giá lại, nể phục anh) đấy. → 3. Vậy à? Cảm ơn nhé.",
    explanation:"Đáp án 3. 「見直しちゃった」= đánh giá lại/theo hướng tốt lên (nể phục). Phản hồi tự nhiên là cảm ơn ⇒ ③. ① hiểu sai thành 'nhìn lại' (xem lại), ② 'đã cố gắng' không khớp lời khen. ⇒ ③." },
  { id:"c4-2", passage:"【台本】2番：うん、この天気じゃ、今日のお花見は中止にするしかないね。<br>1.残念だけど、しょうがないね。<br>2.この天気でもやるの。<br>3.中止にしなくてよかったね。", audioUrl:"", question:"2番", options:["残念だけど、しょうがないね。","この天気でもやるの。","中止にしなくてよかったね。"], answer:0,
    translation:"(Script) 2: Ừ, thời tiết thế này thì hôm nay chỉ còn cách hoãn việc ngắm hoa thôi nhỉ. → 1. Tiếc thật, nhưng đành chịu vậy.",
    explanation:"Đáp án 1. Đồng tình với việc đành phải hoãn ⇒ ①. ② 'vẫn làm à' trái ý, ③ 'may mà không phải hoãn' trái nghĩa. ⇒ ①." },
  { id:"c4-3", passage:"【台本】3番：女：お客様、館内での撮影はご遠慮いただけますか。<br>1.あっ、お願いしていいですか。<br>2.すみません、だめなんですね。<br>3.じゃあ、遠慮なく。", audioUrl:"", question:"3番", options:["あっ、お願いしていいですか。","すみません、だめなんですね。","じゃあ、遠慮なく。"], answer:1,
    translation:"(Script) 3: Nữ: Quý khách, xin quý khách vui lòng không chụp ảnh trong khuôn viên ạ. → 2. Xin lỗi, không được ạ.",
    explanation:"Đáp án 2. 「ご遠慮いただけますか」= yêu cầu không làm ⇒ đáp 'không được à' ⇒ ②. ① 'xin nhờ giúp được không' sai, ③ 'vậy thì không khách sáo nữa' hiểu sai 遠慮. ⇒ ②." },
  { id:"c4-4", passage:"【台本】4番：男：今日はついてないな。<br>1.だから着けてこなかったんだね。<br>2.うまくいったんだ、よかったね。<br>3.えっ、なんかあったの。", audioUrl:"", question:"4番", options:["だから着けてこなかったんだね。","うまくいったんだ、よかったね。","えっ、なんかあったの。"], answer:2,
    translation:"(Script) 4: Nam: Hôm nay xui quá. → 3. Ơ, có chuyện gì à?",
    explanation:"Đáp án 3. 「ついてない」= không may, xui ⇒ hỏi có chuyện gì ⇒ ③. ① hiểu sai thành 着ける (đeo), ② 'suôn sẻ tốt quá' ngược nghĩa. ⇒ ③." },
  { id:"c4-5", passage:"【台本】5番：男：課長、次の企画のリーダー、引き受けた以上はしっかりやります。<br>1.引き受けるかどうか迷ってるの。<br>2.うん、期待してるからね。<br>3.引き受けて欲しかったな。", audioUrl:"", question:"5番", options:["引き受けるかどうか迷ってるの。","うん、期待してるからね。","引き受けて欲しかったな。"], answer:1,
    translation:"(Script) 5: Nam: Trưởng phòng, đã nhận làm trưởng nhóm cho kế hoạch tới thì tôi sẽ làm nghiêm túc. → 2. Ừ, tôi đang kỳ vọng ở cậu đấy.",
    explanation:"Đáp án 2. Người dưới nói sẽ cố gắng, cấp trên nên bày tỏ kỳ vọng ⇒ ②. ① 'đang phân vân có nhận không' lệch vai, ③ 'đáng lẽ muốn cậu nhận' trái (đã nhận rồi). ⇒ ②." },
  { id:"c4-6", passage:"【台本】6番：女：今日の講演会、聞きにきた甲斐がありましたね。<br>1.貴重なお話が聞けましたね。<br>2.講演会聞けたら良かったですよね。<br>3.確かに来る必要なかったですね。", audioUrl:"", question:"6番", options:["貴重なお話が聞けましたね。","講演会聞けたら良かったですよね。","確かに来る必要なかったですね。"], answer:0,
    translation:"(Script) 6: Nữ: Buổi diễn thuyết hôm nay, đến nghe thật đáng công nhỉ. → 1. Đúng là được nghe những câu chuyện quý giá nhỉ.",
    explanation:"Đáp án 1. Đồng tình rằng đáng công ⇒ ①. ② 'giá mà nghe được' lệch (đã nghe rồi), ③ 'đúng là không cần đến' trái nghĩa. ⇒ ①." },
  { id:"c4-7", passage:"【台本】7番：女：部長、出席者の皆さん、もう会場にお揃いです。まだ時間前ですが。<br>1.そうですか。私もすぐ行きます。<br>2.じゃ、全員そろったら教えてください。<br>3.そろそろ皆さんを会場にご案内してください。", audioUrl:"", question:"7番", options:["そうですか。私もすぐ行きます。","じゃ、全員そろったら教えてください。","そろそろ皆さんを会場にご案内してください。"], answer:0,
    translation:"(Script) 7: Nữ: Trưởng phòng, mọi người dự đã có mặt ở hội trường rồi ạ. Dù chưa đến giờ. → 1. Vậy à. Tôi cũng tới ngay đây.",
    explanation:"Đáp án 1. Đã tập trung đông nên trưởng phòng nói sẽ tới ngay ⇒ ①. ② 'đủ người thì báo tôi' thừa, ③ 'hãy hướng dẫn mọi người vào hội trường' sai (đã ở đó rồi). ⇒ ①." },
  { id:"c4-8", passage:"【台本】8番：男：田中さん、皆の前で山田くんに注意すべきじゃなかったんじゃない。<br>1.やっぱり言って良かったってことだね。<br>2.でも、必要だと思ったから。<br>3.注意しろって言うならするよ。", audioUrl:"", question:"8番", options:["やっぱり言って良かったってことだね。","でも、必要だと思ったから。","注意しろって言うならするよ。"], answer:1,
    translation:"(Script) 8: Nam: Chị Tanaka, nhắc nhở Yamada trước mặt mọi người là không nên ấy nhỉ. → 2. Nhưng vì tôi nghĩ điều đó là cần thiết.",
    explanation:"Đáp án 2. Bị phê bình thì nên giải thích lý do ⇒ ②. ① 'hóa ra nói là tốt' trái với ý bị chê, ③ lệch. ⇒ ②." },
  { id:"c4-9", passage:"【台本】9番：女：鈴木さん、午後の打ち合わせ、わたし抜きで始めといてもらえる?<br>1.何時にいらっしゃいますか。<br>2.いらっしゃってから始めるんですね。<br>3.途中で抜けられるということですか。", audioUrl:"", question:"9番", options:["何時にいらっしゃいますか。","いらっしゃってから始めるんですね。","途中で抜けられるということですか。"], answer:0,
    translation:"(Script) 9: Nữ: Anh Suzuki, buổi bàn bạc chiều nay, anh bắt đầu trước không cần tôi có được không? → 1. Mấy giờ chị đến ạ?",
    explanation:"Đáp án 1. Người trên nói 'đừng chờ tôi' nên hỏi giờ đến để sắp xếp ⇒ ①. ② 'đợi chị đến rồi bắt đầu nhỉ' trái ý (là bắt đầu trước), ③ hiểu sai. ⇒ ①." },
  { id:"c4-10", passage:"【台本】10番：男：この旅館、設備はともかく、サービスは満点だね。<br>1.ホント、設備もサービスも最高だね。<br>2.設備もよければ文句ないのにね。<br>3.サービスさえよければいいんだけどね。", audioUrl:"", question:"10番", options:["ホント、設備もサービスも最高だね。","設備もよければ文句ないのにね。","サービスさえよければいいんだけどね。"], answer:0,
    translation:"(Script) 10: Nam: Nhà trọ này, thiết bị thì không bàn tới, chứ dịch vụ thì tuyệt vời nhỉ. → 1. Thật, cả thiết bị lẫn dịch vụ đều tuyệt nhỉ.",
    explanation:"Đáp án 1. 「設備はともかく、サービスは満点だね」= dịch vụ thì tuyệt vời (thiết bị thì gác lại). Đáp đồng tình và khen cả hai: 「設備もサービスも最高だね」⇒ ①. ② 'giá mà thiết bị cũng tốt' mang hàm ý chê thiết bị, ③ 'chỉ cần dịch vụ tốt là được' lệch. ⇒ ①." },
  { id:"c4-11", passage:"【台本】11番：男：青木さん、今回の新製品、青木さんの協力なしには完成しなかったよ。<br>1.完成させられなくて残念です。<br>2.協力できなくて、申し訳ありません。<br>3.お役に立ててうれしいです。", audioUrl:"", question:"11番", options:["完成させられなくて残念です。","協力できなくて、申し訳ありません。","お役に立ててうれしいです。"], answer:2,
    translation:"(Script) 11: Nam: Chị Aoki, sản phẩm mới lần này, không có sự hợp tác của chị thì đã không hoàn thành được. → 3. Tôi rất vui vì đã giúp ích được.",
    explanation:"Đáp án 3. Được khen có công ⇒ đáp khiêm tốn vui vì giúp được ⇒ ③. ① 'tiếc vì không hoàn thành được' trái nghĩa, ② 'xin lỗi vì không hợp tác được' sai. ⇒ ③." },
]},
{ tab:"聴解", section:"問題5 統合理解",
  instruction:"問題5では長めの話を聞きます。この問題には練習はありません。メモをとってもかまいません。1番、2番は問題用紙に何も印刷されていません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。3番はまず話を聞いてください。それから、二つの質問を聞いて、それぞれ問題用紙の1から4の中から、最もよいものを一つ選んでください。（せんたくし được in trong phần 台本 của đề gốc.)",
  questions:[
  { id:"c5-1", passage:"【台本】旅行代理店で女の人と店の人が話しています。<br><br>女：来月の12日、13日に森山市に行くので、泊まるところを予約したいんですが。森山大学で会議があるので、会場に近いところがいいんですが。<br>男：来月の12、13で、森山大学の近くですね。<br>女：はい。一万円ぐらいであるとうれしいです。<br>男：少々お待ちください。ご希望に合うところは四つあります。一つ目は花旅館、大学へは徒歩五分ぐらいですね。1名様1万3000円ですが、温泉があります。<br>女：あっ、森山市って温泉が有名なんですよね。せっかくだから温泉があるところがいいです。<br>男：あ、はい。二つ目は緑ホテルです。こちらは大学まではバスで十分ぐらいですが、ホテルの前にバス停があります。こちらも温泉があって、お一人9000円です。<br>女：大学まではバスですか。<br>男：はい。三つ目は朝日旅館です。こちらも大学へはバスで10分ほどです。温泉付きで、お一人1万円です。<br>女：そうですか。<br>男：最後は温泉はありませんが、ホテル森山。こちらは大学まで徒歩五分でお一人8000円です。<br>女：うん、やっぱり温泉があるほうがいいな。大学までバスで10分ぐらいならいいか。少しでも安いほうがいいから、ここ、予約お願いできますか。", audioUrl:"", question:"1番：女の人はどこを予約することにしましたか。", options:["花旅館","緑ホテル","朝日旅館","ホテル森山"], answer:1,
    translation:"(Script) Ở đại lý du lịch, nữ và nhân viên nói chuyện. Nữ quyết định đặt chỗ ở đâu? Nữ: Ngày 12, 13 tháng sau tôi đi thành phố Moriyama nên muốn đặt chỗ ở. Vì có hội nghị ở Đại học Moriyama nên muốn gần hội trường. Nam: Ngày 12, 13 tháng sau, gần Đại học Moriyama nhỉ. Nữ: Vâng. Khoảng một vạn yên thì tốt. Nam: Xin đợi chút. Có bốn chỗ phù hợp. Thứ nhất là Hanaryokan, đi bộ khoảng 5 phút đến trường, 1 người 13.000 yên, có suối nước nóng. Nữ: À, thành phố Moriyama nổi tiếng suối nước nóng nhỉ. Đã đến thì muốn chỗ có suối nước nóng. Nam: Vâng. Thứ hai là Midori Hotel, đến trường khoảng 10 phút bằng xe buýt, trước khách sạn có trạm xe buýt. Cũng có suối nước nóng, 9.000 yên/người. Nữ: Đến trường bằng xe buýt à. Nam: Vâng. Thứ ba là Asahi Ryokan, đến trường khoảng 10 phút bằng xe buýt, có suối nước nóng, 1 vạn yên/người. Nữ: Vậy à. Nam: Cuối cùng không có suối nước nóng là Hotel Moriyama, đi bộ 5 phút, 8.000 yên/người. Nữ: Ừm, vẫn muốn có suối nước nóng. Mà đến trường bằng xe buýt 10 phút cũng được. Càng rẻ càng tốt, đặt chỗ này giúp tôi nhé.",
    explanation:"Đáp án 2. Cô muốn có 温泉, đến trường bằng xe buýt ~10 phút cũng được, và rẻ nhất có thể. Ứng viên có suối nước nóng đi xe buýt ~10 phút: 緑ホテル (9000) và 朝日旅館 (10000). Rẻ nhất là 緑ホテル ⇒ ②. ① 花旅館 đi bộ nhưng 13000 (đắt), ④ không có suối nước nóng. ⇒ ②." },
  { id:"c5-2", passage:"【台本】地域の合唱サークルのリーダーとメンバーが話しています。<br><br>女1：最近あまり熱心に練習していない人が多いって一部のメンバーから苦情がでてるんですよ。<br>男：長くやってる人が多いから緊張感がなくなってきてるのかもしれませんね。よく知ってる歌を歌うことが多いですし。<br>女2：そうですね。うーん、活動場所をときどき変えてみませんか。ちょっと大きめのホールとか。多少使用料はあがりますが、音の響きもいいそうですよ。<br>女1：そうね。舞台に立ってる感じになるね。今使ってる市民センター、3ヶ月後まで予約してあるから、その後からはときどき変えてみましょうか。<br>女2：ええ。後、他の合唱サークルと合同練習を計画してみるとか、刺激になって練習に身が入るかもしれません。<br>女1：なるほど。うん、一緒にやってくれるサークルを捜すのがたいへんね。<br>男：あのう、何か目標みたいなものを立てるのはどうですか。今までやってなかったけど、コンサートを企画して、私たちのうたを聞いてもらう機会を作るとか。<br>女1：そうね。<br>男：または、今までよりちょっと難しい曲にチャレンジするだけでもいいと思います。頑張ろうって気持ちが起きるんじゃないですか。<br>女2：コンサートはメンバーのやる気は出そうですが、準備がたいへんですよね。曲なら、今度の練習からでも取り入れられそうですが。<br>女1：そうね。コンサートは一度皆に相談してみましょう。練習の場所を変えるにしても少し先のことになりそうだから、すぐ始められることからやってみましょう。", audioUrl:"", question:"2番：このサークルではまず何をすることにしましたか。", options:["練習する場所を変える","他のサークルと合同で練習する","コンサートを企画する","難しい曲にチェンジする"], answer:3,
    translation:"(Script) Trưởng nhóm và thành viên của câu lạc bộ hợp xướng khu vực nói chuyện. Trước tiên câu lạc bộ quyết định làm gì? Nữ1: Gần đây có phàn nàn từ một số thành viên rằng nhiều người không chăm luyện tập. Nam: Chắc vì nhiều người làm lâu nên mất căng thẳng. Vì hay hát bài quen. Nữ2: Ừ nhỉ. Hay là thỉnh thoảng đổi địa điểm hoạt động? Như hội trường to hơn. Phí có tăng chút, nhưng nghe nói âm vang cũng tốt. Nữ1: Nhỉ. Cảm giác như đứng trên sân khấu. Trung tâm công dân đang dùng đã đặt đến 3 tháng sau, nên sau đó thỉnh thoảng đổi thử. Nữ2: Ừ. Ngoài ra, thử lên kế hoạch luyện tập chung với câu lạc bộ hợp xướng khác, có thể tạo kích thích mà chăm hơn. Nữ1: Ra vậy. Tìm câu lạc bộ chịu làm chung khó nhỉ. Nam: Hay là đặt ra mục tiêu gì đó thì sao? Trước giờ chưa làm, tổ chức concert để có dịp mọi người nghe chúng ta hát. Nữ1: Ừ nhỉ. Nam: Hoặc chỉ cần thử thách bài khó hơn chút cũng được. Chắc sẽ nảy sinh tinh thần cố gắng. Nữ2: Concert thì có vẻ khơi dậy ý chí, nhưng chuẩn bị vất vả. Còn bài hát thì có thể áp dụng ngay từ buổi tập tới. Nữ1: Ừ. Concert thì để hỏi ý mọi người. Đổi địa điểm cũng phải chờ chút, nên làm cái bắt đầu được ngay trước đã.",
    explanation:"Đáp án 4. Câu cuối: 「練習の場所を変えるにしても少し先のことになりそうだから、すぐ始められることからやってみましょう」; trước đó nữ2 nói 「曲なら、今度の練習からでも取り入れられそう」⇒ bắt đầu ngay được là đổi sang bài khó hơn ⇒ ④. ① phải chờ (3ヶ月後まで予約済み), ②③ cần bàn/chuẩn bị. ⇒ ④." },
  { id:"c5-3", passage:"【台本】ラジオで男の人が話しています。<br><br>男1：緑公園ではきれいで過ごしやすい公園を目指して、様々な作業をしてくださるボランティアの方を募集します。作業の内容によって四つのグループに分かれています。グループ1は花壇の手入れをします。主に種をまいたり、草取りをしたりします。グループ2は木の手入れをします。木の名前を書く板の作成や取り付けなどしていただきます。経験者の方には枝を切る作業もお願いする予定です。グループ3は公園内のゴミ拾いや落ち葉掃きなどの清掃が主な作業です。グループ4は公園で行う自然体験教室の手伝いで、小学生向けの自然観察会や工作教室にアシスタントとして参加していただきます。各グループの活動日や時間など、詳細はホームページをご覧ください。<br><br>女：あの公園、いつもきれいなのはボランティアの人たちのおかげなんだね。私たちもやってみない?<br>男2：うん、いいね。<br>女：わたし、子供が好きだから、自然体験教室に参加したいけど、工作苦手なんだよね。まさおさんは器用だし工作とかも得意じゃない?<br>男2：自分がするのは好きだけど、子供相手はちょっとね。それより、このあいだテレビで植木職人のドキュメンタリーを見て面白いと思ったんだ。名前とかも覚えられるし、そのグループがいいな。<br>女：私はいつも見てるあのきれいな花壇に何かのかたちで関わりたいな。それにしようっと。<br>男2：いいんじゃない。掃除は苦手だよね。<br>女：ひど〜い。", audioUrl:"", question:"3番：質問1 男の人はどのグループのボランティアをしたいと言っていますか。", options:["グループ1","グループ2","グループ3","グループ4"], answer:1,
    translation:"(Script) Trên radio, một người đàn ông nói. Nữ: Công viên đó lúc nào cũng sạch là nhờ tình nguyện viên nhỉ. Mình cũng thử chứ? Nam2: Ừ, được đấy. Nữ: Tớ thích trẻ con nên muốn tham gia lớp trải nghiệm thiên nhiên, nhưng tớ kém khéo tay. Anh Masao khéo léo, giỏi thủ công nhỉ? Nam2: Tớ thích tự làm, nhưng làm với trẻ con thì hơi. Hơn nữa, dạo này xem phim tài liệu về nghệ nhân cây cảnh trên TV thấy thú vị. Còn nhớ được cả tên nữa, tớ chọn nhóm đó.",
    explanation:"Đáp án 2. Nam nói 「テレビで植木職人のドキュメンタリーを見て…名前とかも覚えられるし、そのグループがいいな」⇒ chăm sóc cây (木の手入れ) = グループ2 ⇒ ②." },
  { id:"c5-4", passage:"【台本】ラジオで男の人が話しています。<br><br>男1：緑公園ではきれいで過ごしやすい公園を目指して、様々な作業をしてくださるボランティアの方を募集します。作業の内容によって四つのグループに分かれています。グループ1は花壇の手入れをします。主に種をまいたり、草取りをしたりします。グループ2は木の手入れをします。木の名前を書く板の作成や取り付けなどしていただきます。経験者の方には枝を切る作業もお願いする予定です。グループ3は公園内のゴミ拾いや落ち葉掃きなどの清掃が主な作業です。グループ4は公園で行う自然体験教室の手伝いで、小学生向けの自然観察会や工作教室にアシスタントとして参加していただきます。各グループの活動日や時間など、詳細はホームページをご覧ください。<br><br>女：あの公園、いつもきれいなのはボランティアの人たちのおかげなんだね。私たちもやってみない?<br>男2：うん、いいね。<br>女：わたし、子供が好きだから、自然体験教室に参加したいけど、工作苦手なんだよね。まさおさんは器用だし工作とかも得意じゃない?<br>男2：自分がするのは好きだけど、子供相手はちょっとね。それより、このあいだテレビで植木職人のドキュメンタリーを見て面白いと思ったんだ。名前とかも覚えられるし、そのグループがいいな。<br>女：私はいつも見てるあのきれいな花壇に何かのかたちで関わりたいな。それにしようっと。<br>男2：いいんじゃない。掃除は苦手だよね。<br>女：ひど〜い。", audioUrl:"", question:"3番：質問2 女の人はどのグループのボランティアをしたいと言っていますか。", options:["グループ1","グループ2","グループ3","グループ4"], answer:0,
    translation:"(Script) (Cùng đoạn hội thoại với 質問1.) Sau đó nữ nói: Tớ muốn góp phần vào luống hoa đẹp mà tớ hay ngắm, theo cách nào đó. Chọn cái đó. Nam2: Được đấy. Cậu kém dọn dẹp nhỉ. Nữ: Quá đáng~.",
    explanation:"Đáp án 1. Nữ nói 「私はいつも見てるあのきれいな花壇に何かのかたちで関わりたいな」⇒ chăm sóc luống hoa (花壇の手入れ) = グループ1 ⇒ ①." },
]},
]});
