/* =========================================================================
   data_2024_07.js — JLPT N2 2024年7月
   Nguồn: pdf_data\15. N2 7.2024.pdf (đề) + pdf_data\script N2 7.2024.pdf (聴解台本)
   Đáp án: ĐÁP ÁN JLPT N2 (update 10.4.2026) — bảng 正解 chính thức.
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2024_07", label:"07/2024", title:"JLPT N2 — 2024年7月 (07/2024)", file:"data_2024_07.js" },
data: [

{ tab: "文字・語彙", section: "問題1 漢字読み",
  instruction: "＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a1-1", passage:"", audioUrl:"", question:"1. 状況を<u>詳細</u>に書いてください。", options:["そうざい","そうさい","しょうざい","しょうさい"], answer:3,
      translation:"Hãy viết chi tiết về tình hình.",
      explanation:"詳細 (しょうさい): chi tiết. そうざい (惣菜) / そうさい (総裁/相殺) / しょうざい sai."},
    { id:"a1-2", passage:"", audioUrl:"", question:"2. <u>分析</u>には少し時間がかかります。", options:["ぶんせき","ぶんかい","ぶんせつ","ぶんかつ"], answer:0,
      translation:"Việc phân tích sẽ mất chút thời gian.",
      explanation:"分析 (ぶんせき): phân tích. ぶんかい (分解) / ぶんせつ (分節) / ぶんかつ (分割) sai."},
    { id:"a1-3", passage:"", audioUrl:"", question:"3. 髪の毛がくしに<u>絡まって</u>しまって。", options:["はさまって","からまって","つまって","たまって"], answer:1,
      translation:"Tóc bị vướng (rối) vào lược mất rồi.",
      explanation:"絡まる (からまる): vướng, rối, quấn. はさまる (挟まる) / つまる (詰まる) / たまる (貯まる) sai."},
    { id:"a1-4", passage:"", audioUrl:"", question:"4. ここでは<u>農薬</u>をまったく使わずに野菜を栽培している。", options:["のんやく","のうやく","のうらく","のんらく"], answer:1,
      translation:"Ở đây người ta trồng rau hoàn toàn không dùng thuốc trừ sâu.",
      explanation:"農薬 (のうやく): thuốc trừ sâu, thuốc bảo vệ thực vật. Các cách đọc còn lại đều sai."},
    { id:"a1-5", passage:"", audioUrl:"", question:"5. とても<u>鮮やか</u>だったことを覚えています。", options:["おだやか","さわやか","あざやか","なごやか"], answer:2,
      translation:"Tôi nhớ nó rất rực rỡ (tươi thắm).",
      explanation:"鮮やか (あざやか): rực rỡ, sắc nét. おだやか (穏やか) / さわやか (爽やか) / なごやか (和やか) sai."},
  ]
},
{ tab: "文字・語彙", section: "問題2 表記",
  instruction: "＿＿＿の言葉を漢字で書くとき、最もよいものを1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a2-1", passage:"", audioUrl:"", question:"6. この会社を<u>しぼう</u>した理由を教えてください。", options:["希望","志望","指望","貴望"], answer:1,
      translation:"Hãy cho tôi biết lý do bạn nguyện vọng (xin vào) công ty này.",
      explanation:"志望 (しぼう): nguyện vọng (vào công ty, trường). 希望 (きぼう) đọc khác; 指望/貴望 không dùng."},
    { id:"a2-2", passage:"", audioUrl:"", question:"7. あの作家の<u>たんぺん</u>小説はとても面白い。", options:["短編","単編","短遍","単遍"], answer:0,
      translation:"Tiểu thuyết truyện ngắn của nhà văn đó rất thú vị.",
      explanation:"短編 (たんぺん): truyện ngắn. Các từ còn lại không đúng chữ Hán."},
    { id:"a2-3", passage:"", audioUrl:"", question:"8. 桜の花が<u>ちって</u>いくのを眺める。", options:["消って","去って","散って","失って"], answer:2,
      translation:"Ngắm hoa anh đào rơi tản dần.",
      explanation:"散る (ちる) → 散って: rơi, tản ra (hoa). 消って/去って/失って đọc khác (きえて/さって/うしなって)."},
    { id:"a2-4", passage:"", audioUrl:"", question:"9. このセーターにはとても<u>やわらかい</u>毛糸が使われている。", options:["伸らかい","軽らかい","暖らかい","柔らかい"], answer:3,
      translation:"Chiếc áo len này dùng sợi len rất mềm.",
      explanation:"柔らかい (やわらかい): mềm mại. Các từ còn lại không tồn tại."},
    { id:"a2-5", passage:"", audioUrl:"", question:"10. 最近あまり体調がよくないのは、<u>ひろう</u>のせいだろう。", options:["疲労","病労","疲老","病老"], answer:0,
      translation:"Dạo này sức khỏe không tốt có lẽ là do mệt mỏi.",
      explanation:"疲労 (ひろう): mệt mỏi (thể lực). Các từ còn lại không đúng."},
  ]
},
{ tab: "文字・語彙", section: "問題3 語形成",
  instruction: "（  ）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a3-1", passage:"", audioUrl:"", question:"11. しょうゆの（  ）原料は大豆です。", options:["主","要","正","本"], answer:0,
      translation:"Nguyên liệu chính của nước tương là đậu nành.",
      explanation:"主要 (しゅよう): chủ yếu. 「主要原料」= nguyên liệu chính. 要/正/本 không ghép được thành 主要 nghĩa này."},
    { id:"a3-2", passage:"", audioUrl:"", question:"12. 子どもたちの読書（  ）が進んでいるらしい。", options:["抜け","逃げ","別れ","離れ"], answer:3,
      translation:"Nghe nói tình trạng trẻ em xa rời việc đọc sách đang tăng.",
      explanation:"読書離れ (どくしょばなれ): việc xa rời đọc sách. 離れ = xa rời, rời bỏ. 抜け/逃げ/別れ sai."},
    { id:"a3-3", passage:"", audioUrl:"", question:"13. 経営の方針については社長が決定（  ）を持っている。", options:["任","手","権","裁"], answer:2,
      translation:"Về phương châm kinh doanh thì giám đốc có quyền quyết định.",
      explanation:"決定権 (けっていけん): quyền quyết định. 権 = quyền. 任/手/裁 không tạo thành 決定権."},
  ]
},
{ tab: "文字・語彙", section: "問題4 文脈規定",
  instruction: "（  ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a4-1", passage:"", audioUrl:"", question:"14. 両親はおいしい料理で客を（  ）のが好きだ。", options:["もてなす","おだてる","ゆるす","すくう"], answer:0,
      translation:"Bố mẹ tôi thích chiêu đãi khách bằng những món ăn ngon.",
      explanation:"もてなす: chiêu đãi, tiếp đãi. おだてる (tâng bốc) / ゆるす (tha thứ) / すくう (cứu, vớt) sai."},
    { id:"a4-2", passage:"", audioUrl:"", question:"15. その駅は各駅停車の電車は止まりますが、急行電車は（  ）します。", options:["経由","直進","通過","横断"], answer:2,
      translation:"Ga đó tàu thường (đỗ mọi ga) thì dừng, nhưng tàu tốc hành thì chạy qua (không dừng).",
      explanation:"通過する: đi qua (không dừng lại). 経由 (đi qua/qua trung gian) / 直進 (đi thẳng) / 横断 (băng qua) sai."},
    { id:"a4-3", passage:"", audioUrl:"", question:"16. 見た人の記憶に残るような（  ）のあるポスターにしたい。", options:["インパクト","プレッシャー","チャージ","ショック"], answer:0,
      translation:"Muốn làm một tấm poster gây ấn tượng để đọng lại trong ký ức người xem.",
      explanation:"インパクト: ấn tượng, sức tác động. プレッシャー (áp lực) / チャージ (nạp) / ショック (cú sốc) sai."},
    { id:"a4-4", passage:"", audioUrl:"", question:"17. 地元の選手がオリンピックでメダルを獲得したことがテレビで（  ）された。", options:["通信","普及","伝言","報道"], answer:3,
      translation:"Việc vận động viên địa phương giành huy chương Olympic đã được đưa tin trên truyền hình.",
      explanation:"報道される: được đưa tin (báo chí, truyền hình). 通信 / 普及 (phổ cập) / 伝言 (lời nhắn) sai."},
    { id:"a4-5", passage:"", audioUrl:"", question:"18. 台風で電車が運休になり通勤や通学で利用する人に（  ）影響を与えた。", options:["大まかな","偉大な","大げさな","多大な"], answer:3,
      translation:"Bão khiến tàu ngừng chạy, gây ảnh hưởng to lớn đến người dùng để đi làm, đi học.",
      explanation:"多大な (ただいな): to lớn, rất nhiều (ảnh hưởng). 大まかな (đại khái) / 偉大な (vĩ đại) / 大げさな (cường điệu) sai."},
    { id:"a4-6", passage:"", audioUrl:"", question:"19. 西川さんは転校してきたばかりだが、友達もできて、もうすっかりクラスに（  ）いる。", options:["当てはまって","溶け込んで","結びついて","触れ合って"], answer:1,
      translation:"Nishikawa vừa mới chuyển trường nhưng đã có bạn bè và hoàn toàn hòa nhập vào lớp.",
      explanation:"溶け込む: hòa nhập, hòa mình vào. 当てはまる (đúng với, khớp) / 結びつく (gắn kết) / 触れ合う (tiếp xúc) sai."},
    { id:"a4-7", passage:"", audioUrl:"", question:"20. 私は（  ）性格なので、時々財布を持たずに買い物に出かけてしまうことがある。", options:["あつかましい","うっとうしい","そそっかしい","さわがしい"], answer:2,
      translation:"Tôi có tính hay lơ đễnh nên đôi khi đi mua sắm mà quên mang ví.",
      explanation:"そそっかしい: lơ đễnh, hấp tấp, thiếu cẩn thận. あつかましい (trơ tráo) / うっとうしい (rườm rà, khó chịu) / さわがしい (ồn ào) sai."},
  ]
},
{ tab: "文字・語彙", section: "問題5 言い換え類義",
  instruction: "＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a5-1", passage:"", audioUrl:"", question:"21. 出張の日程は<u>おおよそ</u>決まりました。", options:["だいたい","すべて","やっと","もう"], answer:0,
      translation:"Lịch trình chuyến công tác đại khái đã được quyết định.",
      explanation:"おおよそ = だいたい: đại khái, khoảng chừng. すべて (tất cả) / やっと (cuối cùng) / もう (đã) sai."},
    { id:"a5-2", passage:"", audioUrl:"", question:"22. 彼女はとても<u>行儀がいい</u>。", options:["アイディア","サービス","マナー","イメージ"], answer:2,
      translation:"Cô ấy rất lễ phép (cư xử đúng mực).",
      explanation:"行儀がいい ≈ マナーがいい: lễ độ, phép tắc, cư xử đúng mực. アイディア/サービス/イメージ sai nghĩa."},
    { id:"a5-3", passage:"", audioUrl:"", question:"23. 中西さんは、いつも<u>いばっている</u>。", options:["眠そうにして","偉そうにして","暇そうにして","嫌そうにして"], answer:1,
      translation:"Anh Nakanishi lúc nào cũng tỏ vẻ ta đây (kênh kiệu).",
      explanation:"いばる = 偉そうにする: tỏ vẻ ta đây, hách dịch. 眠そう/暇そう/嫌そう sai nghĩa."},
    { id:"a5-4", passage:"", audioUrl:"", question:"24. 使わない物は、ここに<u>収納</u>してください。", options:["並べて","捨てて","預けて","しまって"], answer:3,
      translation:"Đồ không dùng thì hãy cất vào đây.",
      explanation:"収納する = しまう: cất đi, cất giữ. 並べる (xếp hàng) / 捨てる (vứt) / 預ける (gửi) sai."},
    { id:"a5-5", passage:"", audioUrl:"", question:"25. 横山さんは<u>不平</u>を言うことが多い。", options:["冗談","文句","うそ","わがまま"], answer:1,
      translation:"Anh Yokoyama hay nói lời phàn nàn.",
      explanation:"不平 = 文句: lời phàn nàn, bất mãn. 冗談 (đùa) / うそ (nói dối) / わがまま (ích kỷ) sai."},
  ]
},
{ tab: "用法", section: "問題6 用法",
  instruction: "次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a6-1", passage:"", audioUrl:"", question:"26. 共有",
      options:["市民ボランティアの共有で、留学生のスピーチコンテストが行われた。","大学と企業が共有で新しい技術の研究を行っている。","これらの事件には、発生場所に共有の特徴があることが分かった。","結婚してから購入した物は、夫婦の共有の財産になる。"], answer:3,
      translation:"Đồ mua sau khi kết hôn trở thành tài sản chung của vợ chồng.",
      explanation:"共有 = cùng sở hữu, dùng chung. Câu 4 đúng (夫婦の共有の財産 = tài sản chung của vợ chồng). Câu 1,2 nên dùng 共同 (cùng nhau), câu 3 nên dùng 共通 (điểm chung)."},
    { id:"a6-2", passage:"", audioUrl:"", question:"27. 鋭い",
      options:["動物たちが自然界で生きていくためには、鋭い感覚が必要だ。","弟は記憶が鋭くて、本に載っているたくさんの国名や国旗をすぐに覚えた。","赤ちゃんの肌は鋭いから、少しの刺激で赤くなってしまう。","運動の能力が鋭い人は、どんなスポーツでもすぐに上達する。"], answer:0,
      translation:"Để sinh tồn trong tự nhiên, các loài động vật cần giác quan nhạy bén.",
      explanation:"鋭い = nhạy bén, sắc bén (giác quan, lời nói). Câu 1 đúng (鋭い感覚). Câu 2 nên dùng 優れた, câu 3 nên dùng 敏感な (nhạy cảm), câu 4 nên dùng 優れた/高い."},
    { id:"a6-3", passage:"", audioUrl:"", question:"28. はきはき",
      options:["よく眠ったので、今日は頭がはきはきとしている。","ビルの屋上から、遠くの山がはきはきと見える。","その学生は、聞かれたことにはきはきと答えた。","ミスの原因をはきはきとさせるために、調査が行われた。"], answer:2,
      translation:"Cậu sinh viên đó trả lời dứt khoát, rõ ràng những gì được hỏi.",
      explanation:"はきはきと: dứt khoát, rõ ràng, hoạt bát (nói năng, thái độ). Câu 3 đúng. Câu 1 nên dùng すっきり, câu 2 nên dùng はっきり, câu 4 sai cách dùng."},
    { id:"a6-4", passage:"", audioUrl:"", question:"29. 鑑賞",
      options:["学校の授業で、工場へ行って自動車を組み立てる様子を鑑賞した。","週末、市のコンサートホールでクラシック音楽を鑑賞した。","資料を読んで、自然を守るための国の活動について鑑賞した。","レストランで、素材の良さを生かした料理を舌でじっくり鑑賞した。"], answer:1,
      translation:"Cuối tuần, tôi thưởng thức nhạc cổ điển ở phòng hòa nhạc của thành phố.",
      explanation:"鑑賞 = thưởng thức (nghệ thuật: nhạc, tranh, phim). Câu 2 đúng. Câu 1 nên dùng 見学, câu 3 nên dùng 理解/学ぶ, câu 4 nên dùng 味わう."},
    { id:"a6-5", passage:"", audioUrl:"", question:"30. 着々",
      options:["ベランダが着々と古くなって危険なので、修理を決めた。","ゲームに夢中になっていたら、時間が着々とたっていた。","来週のパーティーの準備は着々と進んでいるようだ。","夕方になって、外は着々と涼しくなってきている。"], answer:2,
      translation:"Có vẻ như việc chuẩn bị cho bữa tiệc tuần sau đang tiến triển đều đặn.",
      explanation:"着々と: từng bước một, đều đặn, chắc chắn (tiến triển). Câu 3 đúng. Câu 1 nên dùng どんどん, câu 2 nên dùng あっという間に, câu 4 nên dùng だんだん."},
  ]
},
{ tab: "文法", section: "問題7 文の文法1",
  instruction: "次の文の（  ）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a7-1", passage:"", audioUrl:"", question:"31. 卓球クラブの山谷さんは大きな大会で何度も優勝しているのに、「私（  ）まだまだですよ。」といつも言っている。", options:["まで","さえ","なんか","ばかり"], answer:2,
      translation:"Anh Yamaya ở câu lạc bộ bóng bàn dù đã vô địch nhiều lần ở các giải lớn nhưng lúc nào cũng nói \"Những người như tôi còn kém lắm.\"",
      explanation:"～なんか: thứ như..., những kẻ như... (tự hạ thấp mình). 「私なんかまだまだですよ」= Người như tôi còn kém lắm. まで/さえ/ばかり không hợp ngữ cảnh khiêm tốn."},
    { id:"a7-2", passage:"", audioUrl:"", question:"32. 携帯電話を一人一台持つのは当たり前と言われる現代で、私のように携帯電話なしで生活している人は（  ）いるのだろうか。", options:["どうも","どれほど","どうしても","どんなに"], answer:1,
      translation:"Trong thời hiện đại mà ai cũng cho rằng mỗi người có một chiếc điện thoại là đương nhiên, không biết có bao nhiêu người sống không có điện thoại như tôi nhỉ.",
      explanation:"どれほど…いるのだろうか: (không biết) nhiều đến mức nào. どうも (có vẻ) / どうしても (thế nào cũng) / どんなに (dù có...) không hợp câu nghi vấn này."},
    { id:"a7-3", passage:"", audioUrl:"", question:"33. 花山市では、きゅうりやトマト、なす（  ）夏の野菜が多く生産されている。", options:["とする","に関する","といった","に沿った"], answer:2,
      translation:"Ở thành phố Hanaiyama, nhiều loại rau mùa hè như dưa chuột, cà chua, cà tím được sản xuất.",
      explanation:"～といった: như là..., đại loại như (nêu ví dụ). とする / に関する (liên quan đến) / に沿った (dọc theo, phù hợp với) sai."},
    { id:"a7-4", passage:"", audioUrl:"", question:"34. 彼とは数年前に先輩の結婚式で（  ）、ずっと会っていない。", options:["会ったきり","会ったばかりか","会っただけに","会ったところ"], answer:0,
      translation:"Tôi gặp anh ấy lần cuối tại đám cưới của tiền bối vài năm trước, từ đó đến nay không gặp lại.",
      explanation:"～たきり: sau khi làm gì đó thì (không còn)… 「会ったきり…会っていない」. たばかりか / ただけに / たところ không hợp."},
    { id:"a7-5", passage:"", audioUrl:"", question:"35. 近所に子供向けのダンススクールができるらしいので、オープンしたら、娘を体験レッスンに（  ）と思っている。", options:["参加してみようか","参加させてみようか","参加してみてよかった","参加させてみてよかった"], answer:1,
      translation:"Nghe nói gần nhà sắp mở lớp học nhảy cho trẻ em, nên khi khai giảng tôi định cho con gái thử tham gia một buổi học trải nghiệm.",
      explanation:"使役 参加させる: cho (ai) tham gia. 「娘を…参加させてみようか」= hay là cho con gái thử tham gia. 参加して là con tự tham gia (sai vì chủ ngữ là mẹ)."},
    { id:"a7-6", passage:"", audioUrl:"", question:"36. （カメラ屋で）<br>客「カメラを海に落としてしまって、電源が入らないんです。中に水が入ってしまったようなのですが…。」<br>店員「海水が入った（  ）、修理は難しいかもしれませんが、一応見てみますね。」", options:["のであれば","ことであれば","のであって","ことであって"], answer:0,
      translation:"(Ở tiệm máy ảnh) Khách: \"Tôi lỡ làm rơi máy ảnh xuống biển, không bật nguồn được. Hình như nước vào bên trong rồi...\" Nhân viên: \"Nếu nước biển vào thì có thể khó sửa, nhưng cứ để tôi xem thử.\"",
      explanation:"～のであれば: nếu là (chuyện)… (điều kiện giả định). 「海水が入ったのであれば」. ことであれば/のであって/ことであって không hợp."},
    { id:"a7-7", passage:"", audioUrl:"", question:"37. 母「引っ越しまでまだ時間があるけど、直前になって慌てないように、（  ）荷物の整理を進めておいてね。」<br>息子「うん、分かった。」", options:["少しだけでいいのに","少しだけならよくても","少しずつでいいから","少しずつならよく"], answer:2,
      translation:"Mẹ: \"Còn thời gian đến lúc chuyển nhà, nhưng để gần đến lúc không bị luống cuống, con cứ sắp xếp dọn dẹp hành lý từng chút một cũng được nhé.\" Con trai: \"Vâng, con biết rồi.\"",
      explanation:"～でいいから: chỉ cần … là được. 「少しずつでいいから」= chỉ cần từng chút một. 少しだけでいいのに/少しだけならよくても/少しずつならよく không hợp ngữ pháp."},
    { id:"a7-8", passage:"", audioUrl:"", question:"38. 1896年の第1回オリンピックに参加した国と地域の数は14だったが、2004年には200を超える（  ）。", options:["べきだった","つもりだった","ほかなかった","までになった"], answer:3,
      translation:"Số quốc gia và vùng lãnh thổ tham dự Olympic lần thứ nhất năm 1896 là 14, nhưng đến năm 2004 đã lên tới hơn 200.",
      explanation:"～までになった: đã đạt đến mức, đã trở nên (tới mức). 「200を超えるまでになった」. べきだった/つもりだった/ほかなかった sai nghĩa."},
    { id:"a7-9", passage:"", audioUrl:"", question:"39. チームでの仕事をスムーズに進めるには、メンバー同士の十分なコミュニケーション（  ）。", options:["にすぎない","が欠かせない","のおかげだ","とのことだ"], answer:1,
      translation:"Để công việc nhóm tiến triển trôi chảy thì giao tiếp đầy đủ giữa các thành viên là không thể thiếu.",
      explanation:"～が欠かせない: không thể thiếu. 「コミュニケーションが欠かせない」. にすぎない (chỉ là) / のおかげだ (nhờ ơn) / とのことだ (nghe nói) sai."},
    { id:"a7-10", passage:"", audioUrl:"", question:"40. 昨日、新しくできた遊園地に行った。電車より車のほうが早いだろうと思って車で行ったら、ひどい渋滞でかえって時間がかかってしまった。やはり電車で（  ）。", options:["行けばよかった","行くはずだった","行かなくて済んだ","行きたくてしかたがなかった"], answer:0,
      translation:"Hôm qua tôi đi công viên giải trí mới mở. Nghĩ ô tô sẽ nhanh hơn tàu nên đi ô tô, ai ngờ kẹt xe kinh khủng lại càng mất thời gian. Đúng là giá mà đi tàu thì hơn.",
      explanation:"～ばよかった: giá mà đã làm… (hối tiếc). 「やはり電車で行けばよかった」. はずだった/なくて済んだ/たかった sai nghĩa."},
    { id:"a7-11", passage:"", audioUrl:"", question:"41. 往復2時間の通勤を週に5日、40年間続けたとすると、通勤時間は約2万時間で、2年以上の時間を通勤に使う（  ）。", options:["ということにする","ということにしている","ということになる","ということになっている"], answer:2,
      translation:"Nếu đi làm quãng đường khứ hồi 2 tiếng, 5 ngày/tuần, liên tục 40 năm thì thời gian đi lại khoảng 2 vạn giờ, tức là sẽ dùng hơn 2 năm thời gian để đi lại.",
      explanation:"～ということになる: kết quả là..., nghĩa là... (kết luận khách quan). 「通勤に使うということになる」. ということにする/にしている (tự quyết định) sai."},
    { id:"a7-12", passage:"", audioUrl:"", question:"42. （電話で）<br>A「お電話ありがとうございます。クロカワ建設営業課でございます。」<br>B「高橋さんはいらっしゃいますか。」<br>A「失礼ですが、お名前を（  ）。」", options:["伺ったらいかがでしょうか","伺ってもよろしいでしょうか","お伝えしたらいかがでしょうか","お伝えしてもよろしいでしょうか"], answer:1,
      translation:"(Qua điện thoại) A: \"Cảm ơn quý khách đã gọi. Đây là bộ phận kinh doanh công ty xây dựng Kurokawa.\" B: \"Anh Takahashi có ở đó không?\" A: \"Xin lỗi, tôi có thể hỏi tên quý khách được không ạ?\"",
      explanation:"伺ってもよろしいでしょうか: tôi có thể hỏi (khiêm nhường)… được không ạ. 伺う = khiêm nhường ngữ của 聞く. 伺ったら/お伝えしたら…いかがでしょうか và お伝えして… sai ngữ cảnh (nhân viên xin tên khách)."},
  ]
},
{ tab: "文法", section: "問題8 文の文法2 (sắp xếp - ★)",
  instruction: "次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a8-1", passage:"", audioUrl:"", question:"43. 「さわら」という魚は、漢字の「鰆」と書く ＿＿ ★ ＿＿ ＿＿ 魚の一つです。［1 ように / 2 わかる / 3 ことから / 4 春を代表する］", options:["ように","わかる","ことから","春を代表する"], answer:1,
      translation:"Cá \"sawara\" là một trong những loài cá tiêu biểu cho mùa xuân, điều đó có thể hiểu được từ việc nó được viết bằng chữ Hán là 「鰆\".",
      explanation:"Thứ tự đúng: ことから（3）→ わかる（2）→ ように（1）→ 春を代表する（4）: 「漢字の『鰆』と書くことからわかるように、春を代表する魚の一つです」。★ là ô thứ 2 ⇒ đáp án ② わかる. ～ことからわかるように: như có thể hiểu từ việc..."},
    { id:"a8-2", passage:"", audioUrl:"", question:"44. 会議での西山さんのプレゼンは、普段はなかなか ＿＿ ＿＿ ★ ＿＿ 素晴らしかった。［1 ぐらい / 2 課長が / 3 褒める / 4 褒めることがない］", options:["ぐらい","課長が","褒める","褒めることがない"], answer:2,
      translation:"Bài thuyết trình của chị Nishiyama ở cuộc họp hay đến mức ngay cả trưởng phòng — người bình thường hiếm khi khen — cũng phải khen.",
      explanation:"Thứ tự đúng: 褒めることがない（4）→ 課長が（2）→ 褒める（3）→ ぐらい（1）: 「普段はなかなか褒めることがない課長が褒めるぐらい素晴らしかった」。★ là ô thứ 3 ⇒ đáp án ③ 褒める. ～ぐらい: đến mức..."},
    { id:"a8-3", passage:"", audioUrl:"", question:"45. 同じ気温 ＿＿ ＿＿ ★ ＿＿ は大きく変わる。［1 感じ方 / 2 でも / 3 温度や風の強さなど / 4 によって］", options:["感じ方","でも","温度や風の強さなど","によって"], answer:3,
      translation:"Dù cùng một nhiệt độ, cảm giác (nóng lạnh) thay đổi rất nhiều tùy theo nhiệt độ và độ mạnh của gió...",
      explanation:"Thứ tự đúng: でも（2）→ 温度や風の強さなど（3）→ によって（4）→ 感じ方（1）: 「同じ気温でも、温度や風の強さなどによって感じ方は大きく変わる」。★ là ô thứ 3 ⇒ đáp án ④ によって."},
    { id:"a8-4", passage:"", audioUrl:"", question:"46. 「山川大学アニメ研究会」は ＿＿ ＿＿ ★ ＿＿、できた団体だ。［1 学生が / 2 集まって / 3 アニメが / 4 好きでたまらないという］", options:["学生が","集まって","アニメが","好きでたまらないという"], answer:0,
      translation:"\"Hội nghiên cứu anime của Đại học Yamakawa\" là một tổ chức được thành lập bởi những sinh viên vô cùng yêu thích anime tập hợp lại.",
      explanation:"Thứ tự đúng: アニメが（3）→ 好きでたまらないという（4）→ 学生が（1）→ 集まって（2）: 「アニメが好きでたまらないという学生が集まって、できた団体だ」。★ là ô thứ 3 ⇒ đáp án ① 学生が."},
    { id:"a8-5", passage:"", audioUrl:"", question:"47. 会社の今井先輩は、自分はミスが多いといつも言っているが、 ＿＿ ＿＿ ★ ＿＿ ように見える。［1 新人で / 2 何でも完璧にできている / 3 私からすると / 4 わからないことばかりの］", options:["新人で","何でも完璧にできている","私からすると","わからないことばかりの"], answer:2,
      translation:"Tiền bối Imai ở công ty lúc nào cũng nói mình mắc nhiều lỗi, nhưng từ góc nhìn của tôi — một người mới còn đầy điều chưa biết — thì anh ấy có vẻ làm được mọi thứ một cách hoàn hảo.",
      explanation:"Thứ tự đúng: 新人で（1）→ わからないことばかりの（4）→ 私からすると（3）→ 何でも完璧にできている（2）: 「新人でわからないことばかりの私からすると、何でも完璧にできているように見える」。★ là ô thứ 3 ⇒ đáp án ③ 私からすると."},
  ]
},
{ tab: "文法", section: "問題9 文章の文法 (điền vào đoạn văn)",
  instruction: "次の文章を読んで、文章全体の内容を考えて、48から51の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a9-1", passage:"以下は、留学生がスピーチのために書いた文章である。<br><br><b>紅葉の異変</b><br>サリム・ソフィア<br><br>私は日本の秋の景色が好きです。秋になって紅葉が始まり、緑だった葉が黄色やオレンジ、赤に変わると、とてもきれいです。秋の紅葉は、日本の四季の変化を感じさせてくれるものです。<br><br>（４８）ですが、先日テレビで、紅葉がピークを迎える時期が年々遅くなっているというニュースを見ました。中には、１月になってからピークを迎えたところもあるそうで、驚きました。温暖化によって平均気温が上昇していることが大きな原因だそうです。私は、夏が過ぎて気温が下がってくれば、必ず紅葉が始まると思っていました。（４９）、そうではありませんでした。紅葉には、条件となる気温の変化があります。<br><br>葉の変色が始まるのは、1日の最低気温が大体8度以下になってからです。秋になっても、最低気温が一定の気温まで下がらなければ、紅葉は（５０）。その後、さらに寒くなり、5〜6度まで下がると、紅葉は一気に進みます。また、5度以下の日が続くと、最も美しい紅葉が見られると言われています。<br><br>紅葉に起きている異変を知り、このまま温暖化が進むと、日本の秋の景色が変わってしまう可能性もあるのではないかと思いました。もしかしたら、紅葉自体が見られなくなる日も来るかもしれません。紅葉を通して、温暖化が身近な問題であることをより強く（５１）。", audioUrl:"", question:"48. （４８）ですが、先日テレビで、紅葉がピークを迎える時期が年々遅くなっているというニュースを見ました。中には、１月になってからピークを迎えたところもあるそうで、驚きました。", options:["そこの紅葉","そんな紅葉","そちら","紅葉"], answer:1,
      translation:"Đoạn văn là bài viết của một lưu học sinh cho buổi phát biểu. \"Sự bất thường của lá đỏ\" — Salim Sophia: Tôi thích phong cảnh mùa thu Nhật Bản. Nhưng lá đỏ như vậy, dạo trước trên TV tôi thấy tin thời điểm lá đỏ đạt đỉnh mỗi năm một muộn dần. Có nơi đến tận tháng 1 mới đạt đỉnh khiến tôi kinh ngạc. Nguyên nhân lớn là do nhiệt độ trung bình tăng vì nóng lên toàn cầu.",
      explanation:"Đáp án ② そんな紅葉. 「そんな紅葉ですが、…ニュースを見ました」: Nhưng chuyện lá đỏ ấy thì..., (nêu nội dung mới trái ngược nhẹ). ①そこの紅葉 ③そちら ④紅葉 không nối được mạch văn. (Theo bảng 正解: 48 → 2.)"},
    { id:"a9-2", passage:"以下は、留学生がスピーチのために書いた文章である。<br><br><b>紅葉の異変</b><br>サリム・ソフィア<br><br>私は日本の秋の景色が好きです。秋になって紅葉が始まり、緑だった葉が黄色やオレンジ、赤に変わると、とてもきれいです。秋の紅葉は、日本の四季の変化を感じさせてくれるものです。<br><br>（４８）ですが、先日テレビで、紅葉がピークを迎える時期が年々遅くなっているというニュースを見ました。中には、１月になってからピークを迎えたところもあるそうで、驚きました。温暖化によって平均気温が上昇していることが大きな原因だそうです。私は、夏が過ぎて気温が下がってくれば、必ず紅葉が始まると思っていました。（４９）、そうではありませんでした。紅葉には、条件となる気温の変化があります。<br><br>葉の変色が始まるのは、1日の最低気温が大体8度以下になってからです。秋になっても、最低気温が一定の気温まで下がらなければ、紅葉は（５０）。その後、さらに寒くなり、5〜6度まで下がると、紅葉は一気に進みます。また、5度以下の日が続くと、最も美しい紅葉が見られると言われています。<br><br>紅葉に起きている異変を知り、このまま温暖化が進むと、日本の秋の景色が変わってしまう可能性もあるのではないかと思いました。もしかしたら、紅葉自体が見られなくなる日も来るかもしれません。紅葉を通して、温暖化が身近な問題であることをより強く（５１）。", audioUrl:"", question:"49. 私は、夏が過ぎて気温が下がってくれば、必ず紅葉が始まると思っていました。（４９）、そうではありませんでした。", options:["結局","確かに","しかし","つまり"], answer:2,
      translation:"Tôi vẫn nghĩ rằng khi hè qua, nhiệt độ hạ xuống thì lá đỏ nhất định sẽ bắt đầu. Tuy nhiên, không phải vậy.",
      explanation:"Đáp án ③ しかし: tuy nhiên (chuyển ý trái ngược). Trước nêu suy nghĩ \"nhất định...\", sau phủ định \"không phải vậy\" ⇒ dùng しかし. 結局/確かに/つまり không hợp."},
    { id:"a9-3", passage:"以下は、留学生がスピーチのために書いた文章である。<br><br><b>紅葉の異変</b><br>サリム・ソフィア<br><br>私は日本の秋の景色が好きです。秋になって紅葉が始まり、緑だった葉が黄色やオレンジ、赤に変わると、とてもきれいです。秋の紅葉は、日本の四季の変化を感じさせてくれるものです。<br><br>（４８）ですが、先日テレビで、紅葉がピークを迎える時期が年々遅くなっているというニュースを見ました。中には、１月になってからピークを迎えたところもあるそうで、驚きました。温暖化によって平均気温が上昇していることが大きな原因だそうです。私は、夏が過ぎて気温が下がってくれば、必ず紅葉が始まると思っていました。（４９）、そうではありませんでした。紅葉には、条件となる気温の変化があります。<br><br>葉の変色が始まるのは、1日の最低気温が大体8度以下になってからです。秋になっても、最低気温が一定の気温まで下がらなければ、紅葉は（５０）。その後、さらに寒くなり、5〜6度まで下がると、紅葉は一気に進みます。また、5度以下の日が続くと、最も美しい紅葉が見られると言われています。<br><br>紅葉に起きている異変を知り、このまま温暖化が進むと、日本の秋の景色が変わってしまう可能性もあるのではないかと思いました。もしかしたら、紅葉自体が見られなくなる日も来るかもしれません。紅葉を通して、温暖化が身近な問題であることをより強く（５１）。", audioUrl:"", question:"50. 秋になっても、最低気温が一定の気温まで下がらなければ、紅葉は（５０）。", options:["始まらないのです","始まらないためです","始まらないのでしょうか","始まらないためでしょうか"], answer:0,
      translation:"Khi mùa thu đến, nếu nhiệt độ thấp nhất không hạ xuống mức nhiệt độ nhất định thì lá đỏ sẽ không bắt đầu.",
      explanation:"Đáp án ① 始まらないのです: (giải thích) là... không bắt đầu. Kết thúc bằng ～のです/～のです để giải thích lý do mạch văn. 始まらないためです sai vì ため đứng cuối không hợp sắc thái; ～でしょうか (nghi vấn) không hợp vì đây là câu khẳng định."},
    { id:"a9-4", passage:"以下は、留学生がスピーチのために書いた文章である。<br><br><b>紅葉の異変</b><br>サリム・ソフィア<br><br>私は日本の秋の景色が好きです。秋になって紅葉が始まり、緑だった葉が黄色やオレンジ、赤に変わると、とてもきれいです。秋の紅葉は、日本の四季の変化を感じさせてくれるものです。<br><br>（４８）ですが、先日テレビで、紅葉がピークを迎える時期が年々遅くなっているというニュースを見ました。中には、１月になってからピークを迎えたところもあるそうで、驚きました。温暖化によって平均気温が上昇していることが大きな原因だそうです。私は、夏が過ぎて気温が下がってくれば、必ず紅葉が始まると思っていました。（４９）、そうではありませんでした。紅葉には、条件となる気温の変化があります。<br><br>葉の変色が始まるのは、1日の最低気温が大体8度以下になってからです。秋になっても、最低気温が一定の気温まで下がらなければ、紅葉は（５０）。その後、さらに寒くなり、5〜6度まで下がると、紅葉は一気に進みます。また、5度以下の日が続くと、最も美しい紅葉が見られると言われています。<br><br>紅葉に起きている異変を知り、このまま温暖化が進むと、日本の秋の景色が変わってしまう可能性もあるのではないかと思いました。もしかしたら、紅葉自体が見られなくなる日も来るかもしれません。紅葉を通して、温暖化が身近な問題であることをより強く（５１）。", audioUrl:"", question:"51. 紅葉を通して、温暖化が身近な問題であることをより強く（５１）。", options:["感じているからだと思います","感じられるところだと思います","感じさせることができました","感じるようになりました"], answer:3,
      translation:"Thông qua lá đỏ, tôi càng cảm nhận mạnh mẽ hơn rằng sự nóng lên toàn cầu là một vấn đề gần gũi.",
      explanation:"Đáp án ④ 感じるようになりました: đã trở nên cảm nhận được (thay đổi nhận thức). 「より強く感じるようになりました」. 感じているからだと思います/感じられるところだと思います/感じさせることができました không hợp ngữ pháp – ngữ cảnh kết bài phát biểu."},
  ]
},
/* ================= TAB 4: 読解 ================= */
{ tab: "読解", section: "問題10 内容理解・短文",
  instruction: "次の(1)から(5)の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b10-1", passage:"自分の言葉は自分の頭の中にしかなく、相手の言葉は相手の頭の中にしかありません。抽象的な言葉の場合には、まったく同じ意味で使用していることのほうが少ないと言えるでしょう。したがって、議論をする際には、言葉の定義づけが重要になってきます。相手がどういう意味でその言葉を使用しているのか、自分と同じ意味で使用しているのかを確認することは大切なことです。これは、論理的に会話をするうえでの大前提となるものです。<br><br>（注）定義づけ：ここでは、意味を決めること", audioUrl:"", question:"52. 筆者によると、論理的な会話をするのに必要なことは何か。",
      options:["抽象的な言葉をできるだけ使用しないようにする","抽象的な言葉を、正しい意味かどうかを確認してから使用する","同じ言葉を、相手と自分が同じ意味で使用しているかを確認する","相手の知らない言葉は、自分がどういう意味で使用しているかを説明する"], answer:2,
      translation:"Lời của mình chỉ nằm trong đầu mình, lời của đối phương chỉ nằm trong đầu đối phương. Với những từ trừu tượng, việc hai người dùng chúng với cùng một nghĩa là khá hiếm. Vì thế, khi thảo luận, việc định nghĩa từ ngữ trở nên quan trọng. Việc xác nhận đối phương dùng từ đó với nghĩa gì, có dùng cùng nghĩa với mình không là điều quan trọng. Đây là tiền đề lớn để trò chuyện một cách logic.",
      explanation:"Đáp án ③. Câu chốt 「相手がどういう意味でその言葉を使用しているのか、自分と同じ意味で使用しているのかを確認することは大切」⇒ xác nhận đối phương và mình có dùng cùng nghĩa không ⇒ ③. ① bài không nói hạn chế dùng từ trừu tượng; ② không nói \"kiểm tra nghĩa đúng rồi mới dùng\"; ④ chỉ nói về từ đối phương không biết, không phải nội dung chính."},
    { id:"b10-2", passage:"以下は、ある鉄道会社がホームページに掲載したお知らせである。<br><br>トップ>お知らせ>定期システム点検実施のお知らせ<br><b>6月の定期システム点検実施のお知らせ</b><br>いつも北坂鉄道をご利用いただきまして、ありがとうございます。<br>当社では情報管理システムの安全性向上のため、第４土曜日の夜間にシステム点検を実施しております。<br>今月の作業は6月23日（土）午前2時から4時までとなります。この間は、予約システムを休止いたします。インターネットでの特急券予約がご利用いただけなくなりますので、ご注意ください。なお、ホームページ内の時刻表や運賃表は通常どおり閲覧が可能です。<br>ご不便をおかけいたしますが、ご理解くださいますようお願い申し上げます。<br>北坂鉄道株式会社", audioUrl:"", question:"53. このお知らせで伝えたいことは何か。",
      options:["6月23日の午前2時から4時までは、インターネットで特急券が予約できない","6月23日の午前2時から4時までは、ホームページで時刻表や運賃表が見られない","6月23日の午前4時以降、インターネットで特急券が予約できるようになる","6月23日の午前4時以降、ホームページで時刻表や運賃表が見られるようになる"], answer:0,
      translation:"Đây là thông báo của một công ty đường sắt đăng trên trang web. Thông báo về việc kiểm tra hệ thống định kỳ tháng 6: Công ty kiểm tra hệ thống vào đêm thứ Bảy tuần thứ tư hằng tháng. Tháng này tiến hành từ 2 giờ đến 4 giờ sáng ngày 23/6 (thứ Bảy). Trong thời gian này hệ thống đặt chỗ tạm dừng, không thể đặt vé tàu tốc hành qua Internet. Bảng giờ tàu và bảng giá vé trên trang web vẫn xem được bình thường.",
      explanation:"Đáp án ①. 「午前2時から4時まで…インターネットでの特急券予約がご利用いただけなくなります」⇒ ①. ② sai vì 時刻表・運賃表 vẫn xem bình thường; ③④ nói về \"sau 4 giờ\" nhưng thông báo không nêu thời điểm mở lại."},
    { id:"b10-3", passage:"新緑の時期に森を歩くと、地面に小さなロールキャベツ状の物体が落ちているのを見かけます。しばしば一か所に大量に落ちていて、とてもよく目立ちます。これはオトシブミという小さな甲虫の仲間が、自分の幼虫のためにつくったものです。この虫のメスは、数分の間に産んだ卵を木の葉で丁寧に包んでから地面に落とす習性をもちます。中で孵った幼虫は、内側からこの巻いた葉を食べて成長します。幼虫にとっては、この葉巻きは隠れ家であるとともに食料なわけです。<br><br>（注1）ロールキャベツ：キャベツで肉を包んだ料理<br>（注2）甲虫：虫の一種<br>（注3）習性：ここでは、特徴的な性質<br>（注4）孵った：ここでは、卵から生まれた", audioUrl:"", question:"54. オトシブミという虫について、筆者はどのように述べているか。",
      options:["食料を木の葉で包んで落とし、幼虫はそれを見つけて食べる","木の葉と卵を落とし、生まれた幼虫は食料をその葉で巻いて隠す","卵を木の葉で包んで落とし、生まれた幼虫はその中でその葉を食べる","落ちている木の葉に卵を産んで包み、幼虫はその中で生まれて育つ"], answer:2,
      translation:"Khi đi trong rừng vào thời kỳ lá non, ta thấy những vật nhỏ giống như cuộn bắp cải cuộn thịt rơi trên mặt đất; đôi khi rơi rất nhiều ở một chỗ nên rất dễ thấy. Đó là thứ con bọ cánh cứng nhỏ tên オトシブミ làm cho ấu trùng của mình. Con cái có tập tính đẻ trứng rồi khéo léo gói trứng bằng lá cây và thả xuống đất. Ấu trùng nở ra trong đó sẽ ăn chính chiếc lá cuộn này từ bên trong để lớn lên. Với ấu trùng, cuộn lá vừa là nơi ẩn náu vừa là thức ăn.",
      explanation:"Đáp án ③. 「産んだ卵を木の葉で丁寧に包んでから地面に落とす」「中で孵った幼虫は、内側からこの巻いた葉を食べて成長します」⇒ ③. ① sai: vật được gói là trứng chứ không phải thức ăn; ② sai: ấu trùng không cuốn lá; ④ sai: trứng không được đẻ vào lá rụng."},
    { id:"b10-4", passage:"以下は、ある会社に届いたメールである。<br><br>コイノ株式会社<br>営業部 島川英一様<br><br>お世話になっております。JC文具の池西です。<br>昨日、商品「軽量ホチキスcx35」の見本が2個届きました。機能性とシンプルなデザインは社内で評価が高く、取り扱い商品に加える方向で検討を進めております。<br>同封されていた最新のカタログによると、来月から新色として3色が追加で発売され、全部で5色になるとのことですので、新色の見本も送付していただけないでしょうか。代金が必要な場合は、お支払いします。<br>取り扱うことが正式に決定しましたら、まずは5色を20個ずつ注文する予定です。<br>よろしくお願いいたします。<br>JC文具<br>池西秋子", audioUrl:"", question:"55. このメールの用件は何か。",
      options:["見本として5色すべての商品を送ってほしい","見本として新色の3個を追加で送ってほしい","見本の代金としていくら支払えばいいか教えてほしい","商品5色を20個ずつ注文できるかどうか教えてほしい"], answer:1,
      translation:"Đây là mail gửi đến một công ty. Kính gửi anh Shimakawa, phòng kinh doanh, công ty Koinо. Tôi là Ikenishi của JC Bungu. Hôm qua đã nhận được 2 mẫu sản phẩm 「軽量ホチキスcx35」. Tính năng và thiết kế đơn giản được nội bộ đánh giá cao, chúng tôi đang xem xét đưa vào danh mục hàng. Theo catalogue mới nhất gửi kèm, từ tháng sau sẽ bán thêm 3 màu mới, tổng cộng thành 5 màu, vậy có thể gửi thêm mẫu của màu mới không ạ? Nếu cần trả tiền chúng tôi xin thanh toán. Khi chính thức quyết định lấy hàng, dự kiến đặt 5 màu, mỗi màu 20 chiếc.",
      explanation:"Đáp án ②. 「新色の見本も送付していただけないでしょうか」⇒ xin thêm mẫu của 3 màu mới ⇒ ②. ① sai: không xin cả 5 màu (2 mẫu đã nhận là hàng hiện có); ③ chỉ là điều kiện kèm theo (nếu cần tiền thì trả), không phải mục đích; ④ mới là \"dự định\", mail không hỏi trước."},
    { id:"b10-5", passage:"競争や出世にはあまり関係のない、たとえばだれかを支えたり育んだりする仕事に喜びを感じる人もいるでしょう。仕事はそこそこに、趣味に生きることを楽しむ人もいるでしょう。たとえ、受験や就職、あるいは出世などの過酷な競争ゲームのただ中にあったとしても、そしてそれにある時、敗れてしまったとしても、わたしたちの人生の選択肢はそれだけではないし、「それで終わり」というわけでもありません。視点を変えれば、現代社会にはさまざまな生き方の世界が広がっているのです。<br><br>（注1）育む：育てる<br>（注2）そこそこに：適度に<br>（注3）過酷な：非常に厳しい<br>（注4）ただ中：最中", audioUrl:"", question:"56. 筆者の考えに合うのはどれか。",
      options:["他人と競争せずに、自分の生き方を見つければいい","人生の選択肢は多様であり、生き方は一つではない","人生の選択肢が多ければ多いほど、世界が広がっていく","仕事や趣味を通して、さまざまな生き方を知ることができる"], answer:1,
      translation:"Có người thấy niềm vui ở công việc ít liên quan đến cạnh tranh hay thăng tiến, ví dụ công việc nâng đỡ, nuôi dưỡng ai đó. Cũng có người sống cho sở thích, công việc chỉ vừa đủ. Dù đang ở giữa cuộc cạnh tranh khốc liệt như thi cử, xin việc hay thăng tiến, và dù có lúc thất bại, lựa chọn trong đời ta không chỉ có thế, cũng không phải \"thế là hết\". Đổi góc nhìn thì trong xã hội hiện đại có rất nhiều thế giới về cách sống khác nhau đang mở ra.",
      explanation:"Đáp án ②. 「人生の選択肢はそれだけではない」「現代社会にはさまざまな生き方の世界が広がっている」⇒ lựa chọn đời sống đa dạng, cách sống không chỉ một ⇒ ②. ① bài không khuyên \"không cạnh tranh\"; ③ bài không nói càng nhiều lựa chọn thì thế giới càng rộng; ④ chỉ là ví dụ của người khác, không phải ý chính."},
  ]
},
{ tab: "読解", section: "問題11 内容理解・中文",
  instruction: "次の(1)から(4)の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b11-1", passage:"(1) ほとんどの人が、スマホやタブレットを通して、大量のSNSやネットニュースを毎日見ていることでしょう。多くの人がその膨大な情報を読むことあるいは見ることに、かなりの時間を費やしていて、ネット上の情報に追われている印象すら受けます。その結果、じっくり考える時間がどんどん少なくなっているようにも感じられます。<br><br>また、大量の情報がネット上に流されるようになった結果、自分に都合の良い情報にしか接しない人が増えてきています。技術革新のおかげではあるのですが、SNSやネットニュースでは、その人の履歴から判断して、その人が関心を持っていると思われる情報やニュースが目につくところに流れるような工夫がされています。<br><br>このような工夫はとても便利なことで、それによって時間が節約できたりする面は確かにあります。(中略)<br><br>しかし、人々が見たいものだけを見て、信じている情報だけに接すると、発想が固定化してしまい、新しい進化が生まれにくくなってしまいます。また、思想的にも偏りのある考えが生まれやすくなってしまいます。<br><br>そう考えると、この大量情報社会においては、いかにうまく情報を処理していくかがとても大事なことがわかります。また、大量の情報を、一部だけ最初から抜き出して把握するのではなく、偏りがない形で、大量に処理することも必要です。<br><br>（注1）スマホやタブレット：コンピューターの機能を持った小型の電子機器類<br>（注2）SNSやネットニュース：ここでは、インターネット上でやり取りされる情報やニュース<br>（注3）費やす：使う<br>（注4）技術革新：技術の進歩<br>（注5）履歴：ここでは、インターネット上の情報の閲覧の記録<br>（注6）いかに：どのように<br>（注7）把握する：理解する", audioUrl:"", question:"57. このような工夫とはどのようなことか。",
      options:["情報を要約して、短時間で大量に見られるようにすること","多くの人が関心を持っている情報を優先的に流すこと","見る人が自分では探せない情報を選んで、提供すること","見る人の興味の傾向に合わせて、情報を提供すること"], answer:3,
      translation:"(1) Hầu hết mọi người mỗi ngày đều xem một lượng lớn SNS và tin tức mạng qua smartphone, máy tính bảng. Nhiều người dành khá nhiều thời gian đọc hoặc xem lượng thông tin khổng lồ đó, thậm chí có cảm giác đang bị thông tin trên mạng rượt đuổi. Kết quả là thời gian để suy nghĩ kỹ càng ngày càng ít đi. Mặt khác, do lượng thông tin lớn được đẩy lên mạng, số người chỉ tiếp xúc với thông tin có lợi cho mình đang tăng lên. Nhờ tiến bộ kỹ thuật, SNS và tin tức mạng được thiết kế sao cho dựa vào lịch sử truy cập mà đoán thông tin/tin tức mà người đó quan tâm và đưa vào chỗ dễ thấy. Cách làm này rất tiện, đúng là có mặt giúp tiết kiệm thời gian. (Lược) Nhưng nếu chỉ xem thứ mình muốn xem và chỉ tiếp xúc với thông tin mình tin, thì suy nghĩ sẽ bị cố định, khó sinh ra tiến hóa mới, và cũng dễ nảy sinh quan điểm lệch lạc về tư tưởng. Nghĩ như vậy thì trong xã hội nhiều thông tin này, việc xử lý thông tin khéo léo là rất quan trọng. Ngoài ra, không phải chỉ trích ra một phần rồi nắm bắt, mà cần xử lý lượng lớn thông tin một cách không thiên lệch.",
      explanation:"Đáp án ④. \"Cách làm\" nói ở đoạn 2: 「その人の履歴から判断して、その人が関心を持っていると思われる情報やニュースが目につくところに流れる」⇒ phù hợp với xu hướng quan tâm của người xem ⇒ ④. ① không nói tóm tắt; ② \"nhiều người quan tâm\" sai (là theo từng người); ③ không nói \"thông tin người xem không tự tìm được\"."},
    { id:"b11-2", passage:"", audioUrl:"", question:"58. 大量情報会社（＝大量情報社会）について、筆者の考えに合うのはどれか。",
      options:["発想が固定化しないように、大量の情報を工夫して処理しなければならない","思想的に偏りのある考えでも、工夫してうまく処理しなければならない","必要な情報を選ぶために、大量の情報をうまく処理しなければならない","時間がかかっても、偏りなく大量の情報を処理しなければならない"], answer:0,
      translation:"(Bài đọc: xem bản dịch ở câu 57)",
      explanation:"Đáp án ①. 「見たいものだけを見て…発想が固定化してしまい」「この大量情報社会においては、いかにうまく情報を処理していくかがとても大事」⇒ phải xử lý khéo léo lượng lớn thông tin để phát hiện không bị cố định ⇒ ①. ② bài nói tránh quan điểm lệch lạc, không phải \"dù lệch lạc vẫn phải xử lý\"; ③ không nói \"chọn thông tin cần thiết\"; ④ bài không nói \"dù mất thời gian\"."},
    { id:"b11-3", passage:"(2) 勉強にしても、仕事にしても、その能率には必ず波があり、それがないようにみえても、波が小さいだけである。つまり、人間は機械のようにいつも同じ調子ではたらいていないから、1時間に50個の製品がつくれるから、10時間で500個がつくれる、という具合には計算できない。従って、脳が最も快調にはたらいているときを基準にすると、たいていのときは不調ということになってしまう。<br><br>それでも、全く無計画に勉強や仕事をするわけにもゆかないので、一応はスケジュールを立てる。その際に、快調に脳がはたらいているときの能率を基準にしてスケジュールを立てれば、そのスケジュールの通りにことが進行することは絶対にないといってもいい。その度に、自分の才能に失望していれば、失望しつづけることになる。さし迫った難しい状態では、どうしても脳がフル回転しているときを基準にスケジュールを組むので、たいていは不完全な形で終わってしまう。スケジュールをつくるときには、せめて中等度に脳がはたらいているときの能率を基準にする必要がある。スケジュール以上にはかどっても誰もこまる人はいない。<br><br>そして、スケジュールにこだわるよりは、脳の変動の波をできるだけ感じとり、能率が悪くても悲観せずに、必ず上げ潮のときがくることを期待すればいい。そして、上げ潮のときには自分でもおどろくほどに能率が上がるので、そのときに一気に遅れをとり戻せばいいのである。<br><br>（注1）さし迫った：ここでは、時間に余裕がない<br>（注2）フル回転する：ここでは、最もはたらく<br>（注3）はかどる：順調に進む<br>（注4）悲観する：悲しむ<br>（注5）上げ潮のとき：調子が上向きになるとき", audioUrl:"", question:"59. 筆者によると、スケジュールを立てる際の注意点は何か。",
      options:["脳の調子がいいときを基準にしない","いつも脳が同じ調子ではたらけるようにする","能率の変化を考えすぎない","能率が悪くなったときに変更できるようにしておく"], answer:0,
      translation:"(2) Dù là học hay làm việc, hiệu suất luôn có sóng, nếu trông như không có thì chỉ là sóng nhỏ. Nói cách khác, con người không làm việc đều đặn như máy móc, nên không thể tính kiểu \"1 giờ làm được 50 sản phẩm thì 10 giờ được 500\". Vì vậy, nếu lấy lúc não hoạt động sung sức nhất làm chuẩn thì phần lớn thời gian sẽ bị coi là không tốt. Tuy vậy cũng không thể học/làm việc hoàn toàn không kế hoạch, nên vẫn phải lập lịch. Nếu lúc đó lấy hiệu suất khi não sung sức làm chuẩn thì có thể nói chắc chắn công việc sẽ không bao giờ tiến triển đúng như lịch. Mỗi lần như vậy mà thất vọng về tài năng của mình thì sẽ thất vọng mãi. Trong tình trạng gấp gáp khó khăn, người ta buộc phải lấy lúc não hoạt động hết công suất làm chuẩn nên thường kết thúc dang dở. Khi lập lịch, ít nhất phải lấy mức trung bình của não làm chuẩn. Vượt hơn lịch thì không ai phiền cả. Và thay vì bám chặt vào lịch, hãy cố cảm nhận sóng biến động của não, đừng bi quan khi hiệu suất kém, hãy mong đợi rằng lúc thủy triều lên nhất định sẽ đến. Khi thủy triều lên, hiệu suất tăng đến mức bản thân cũng kinh ngạc, lúc đó hãy đuổi kịp một mạch phần chậm trễ.",
      explanation:"Đáp án ①. 「快調に脳がはたらいているときの能率を基準にしてスケジュールを立てれば、そのスケジュールの通りに…絶対にない」「せめて中等度に…基準にする必要がある」⇒ lập lịch phải tránh lấy lúc não sung sức làm chuẩn ⇒ ①. ② trái với \"con người không làm đều như máy\"; ③ bài khuyến khích cảm nhận sóng; ④ bài không nói chuẩn bị sẵn phương án đổi."},
    { id:"b11-4", passage:"", audioUrl:"", question:"60. 筆者の考えに合うのはどれか。",
      options:["能率を上げるためには、脳の状態をコントロールするといい","脳の変動の波に合わせて勉強や仕事を進められる方法を探すといい","計画の通りに行かなくても失望せずに、脳の調子が上がるのを待てばいい","計画の通りに勉強や仕事を進めるために、脳の変動の波を小さくすればいい"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 59)",
      explanation:"Đáp án ③. 「能率が悪くても悲観せずに、必ず上げ潮のときがくることを期待すればいい」⇒ không thất vọng, chờ lúc phong độ lên ⇒ ③. ① bài không nói kiểm soát trạng thái não; ② \"tìm cách làm theo sóng\" không được nêu; ④ bài nói sóng không thể triệt tiêu, không nói làm nhỏ sóng."},
    { id:"b11-5", passage:"(3) お祭りの日は町の雰囲気が一変して、ふだんひっそりとしている町並みがいきいきとしています。そんな町の様子を「祭りがある町」として撮る。神社の境内で行われるような祭りであれば、「神社」の風景として撮る。<br><br>というふうに少し視点を周辺にずらしてみると単なる祭り写真ではない写真に出会えます。祭りの中から自分だけの祭りを探し出すことができるかどうか。写真を見た人から、こういう祭りの見方もあるんだねと言われるような写真が撮れたら「祭りの写真」ではなく写真として内容のあるものになると思います。<br><br>(中略)<br><br>「もう何年もかけて撮ってるんだけど、いい写真が撮れなくてね」とぼやく人がいますが、そういう人は頭の中で思い描いた「上手い写真」の構図から離れることができずにいて、すでにいろいろと見慣れている同じような画像を撮らされるだけだからなのです。<br><br>ねらった被写体を自分のものにするのだと独占する強引さがないと、被写体が刺激的であるほどその場にふりまわされてしまいます。祭りなら激しい動きに、絶景なら色彩にのみこまれて被写体に撮らされているみたいになる。<br><br>被写体に撮らされてしまうような写真は、結局その場の説明でしかない。表現としての写真は自分だけの写真を撮ることになるわけで、それはフィクションでもあるのですから、つねに「私はこう見た」「私はこう撮った」を撮るのです。<br><br>（注1）一変する：すっかり変わる<br>（注2）町並み：ここでは、町の様子<br>（注3）境内：ここでは、敷地内<br>（注4）ぼやく：不満を言う<br>（注5）構図：画面の構成<br>（注6）被写体：写真に撮る対象<br>（注7）絶景：素晴らしい景色", audioUrl:"", question:"61. 写真として内容のあるものとはどのようなものか。",
      options:["祭りの風景から町の人の様子が分かるような写真","祭りに対する撮る人自身の見方が感じられる写真","見る人にとって祭り独特の魅力が感じられる写真","撮る人自身の祭りに対する情熱が伝わってくる写真"], answer:1,
      translation:"(3) Ngày lễ hội, không khí thị trấn đổi khác hoàn toàn, phố phường thường ngày vắng lặng trở nên sống động. Chụp cảnh thị trấn đó như \"thị trấn có lễ hội\". Nếu là lễ hội tổ chức trong khuôn viên đền thì chụp như phong cảnh \"ngôi đền\". Dịch điểm nhìn ra xung quanh một chút như vậy thì sẽ gặp được những bức ảnh không chỉ là ảnh lễ hội đơn thuần. Vấn đề là có tìm ra được lễ hội của riêng mình giữa lễ hội hay không. Nếu chụp được bức ảnh khiến người xem nói \"ồ, cũng có cách nhìn lễ hội như thế này\", thì bức ảnh đó không còn là \"ảnh lễ hội\" mà trở thành bức ảnh có nội dung. (Lược) Có người than \"chụp mấy năm rồi mà không được tấm nào đẹp\", là vì họ không thoát ra khỏi bố cục \"ảnh đẹp\" hình dung trong đầu nên chỉ chụp ra những hình ảnh giống nhau đã quá quen mắt. Nếu không có sự ngang tàng \"chiếm đoạt\" đối tượng mình nhắm tới, thì đối tượng càng kích thích ta càng bị cuốn theo. Đám rước lễ hội thì bị chuyển động dữ dội cuốn, phong cảnh tuyệt đẹp thì bị màu sắc cuốn, cứ như thể bị đối tượng chụp ngược lại mình. Bức ảnh bị đối tượng \"chụp\" như vậy rốt cuộc chỉ là mô tả tại chỗ. Ảnh với tư cách biểu đạt là chụp bức ảnh của riêng mình, và vì nó cũng là fiction, nên luôn chụp \"tôi đã thấy thế này\", \"tôi đã chụp thế này\".",
      explanation:"Đáp án ②. 「写真を見た人から、こういう祭りの見方もあるんだねと言われるような写真」＝ thể hiện cách nhìn của người chụp ⇒ ②. ① bài nói chụp cảnh thị trấn chứ không phải \"thấy được tình hình người dân\"; ③ nói về sức hút của lễ hội, không phải \"nội dung\"; ④ không nói \"truyền đam mê\"."},
    { id:"b11-6", passage:"", audioUrl:"", question:"62. 写真を撮ることについて、筆者が言いたいことは何か。",
      options:["上手い写真を撮ろうと思っても撮れるものではない","上手い写真が撮れるまで、自分の撮り方を続けるべきだ","自分だけの写真を撮るには、刺激的な対象を探し出すべきだ","自分にしか表現できないものを撮るという気持ちで撮るべきだ"], answer:3,
      translation:"(Bài đọc: xem bản dịch ở câu 61)",
      explanation:"Đáp án ④. 「表現としての写真は自分だけの写真を撮ることになる…つねに『私はこう見た』『私はこう撮った』を撮るのです」⇒ luôn chụp với tinh thần \"chỉ mình mình mới thể hiện được\" ⇒ ④. ① bài không nói \"không thể chụp dù muốn\"; ② không khuyên tiếp tục cách chụp cũ (trái lại phải thoát khỏi nó); ③ bài nói đối tượng càng kích thích càng dễ bị cuốn, không khuyên tìm đối tượng kích thích."},
    { id:"b11-7", passage:"(4) 何事もそうですが、「できる人」は応用がききます。接客が完全にマニュアル化されているファーストフード店に行っても、やはりスタッフの差は出ます。たまたま時間のかかるメニューを頼んでしまった際の事前説明、セットメニューに関する質問への対応など、ちょっと注意して観察してみると、頭の回転と表現力の差は随所に表れてきます。<br><br>(中略)<br><br>もっと高度な判断を求められる仕事の現場はどうでしょう。どんな仕事にも、マニュアルもしくはマニュアルに類するような規準があります。その中で「できる人」は、それぞれの仕事にあるマニュアル的なものを咀嚼して状況に対応します。これがまさに「仕事力の差」につながります。<br><br>簡単に言えば、「できる人」は勝手に自分で応用してしまうのです。それは本人にとっては良いことであり、暴走による失敗は別として、お客にとっても会社や店にとってもプラスに作用することが多いと思います。<br><br>しかし今度は人を率いる立場になり、多くの人を育てる番になったとき、今まで意識しなかった壁に突き当たることがあります。<br><br>自分が自然とやってきたことを、なかなかできない人がたくさんいるという事実。これを頭では理解しても、なかなか感覚でキャッチできません。そのため部下への指導が、「マニュアルを越えたものが見えている人の世界」で行われてしまうのです。ところが指導される側は「見えていない世界」の住人ですから、うまく受け取ることができないのは当然です。<br><br>（注1）随所：いろいろなところ　（注2）もしくは：または<br>（注3）咀嚼する：十分に理解する<br>（注4）暴走：ここでは、周囲の状況を考えないでやること<br>（注5）率いる：ここでは、指導する　（注6）キャッチする：受け取る", audioUrl:"", question:"63. 筆者によると、「できる人」とはどのような人か。",
      options:["マニュアルの問題点を見つけて改善できる人","マニュアルをよく理解し、マニュアルどおりに対応できる人","マニュアルをよく理解したうえで、自分が置かれた状況に対応できる人","マニュアルがなくても、自分のやり方で状況に対応できる人"], answer:2,
      translation:"(4) Việc gì cũng vậy, \"người làm được việc\" biết ứng dụng. Dù vào cửa hàng thức ăn nhanh nơi việc tiếp khách đã được mô phạm hóa hoàn toàn, vẫn thấy rõ sự khác biệt giữa các nhân viên. Như khi lỡ gọi món mất thời gian thì giải thích trước thế nào, xử lý câu hỏi về set menu ra sao… chỉ cần chú ý quan sát một chút là thấy khác biệt về độ nhanh nhạy và khả năng diễn đạt ở khắp nơi. (Lược) Còn ở nơi làm việc đòi hỏi phán đoán cao hơn thì sao? Công việc nào cũng có mô phạm hoặc chuẩn mực tương tự mô phạm. Trong đó, \"người làm được việc\" nhai kỹ (hiểu thấu) cái mang tính mô phạm của từng công việc rồi ứng phó với tình huống. Đó chính là khác biệt về \"năng lực công việc\". Nói đơn giản, \"người làm được việc\" tự mình ứng dụng một cách tự nhiên. Điều đó tốt cho bản thân, và ngoài trường hợp thất bại do chạy ẩu, thường có tác động tích cực cho cả khách hàng lẫn công ty/cửa hàng. Nhưng đến khi ở vị trí dẫn dắt người khác, đến lượt phải đào tạo nhiều người, có khi gặp bức tường mà trước đây chưa từng ý thức. Sự thật là có rất nhiều người không thể làm được việc mà mình vẫn làm một cách tự nhiên. Dù hiểu bằng đầu, nhưng rất khó \"bắt\" được bằng cảm giác. Vì thế việc hướng dẫn cấp dưới bị tiến hành trong \"thế giới của người nhìn thấy được những gì vượt trên mô phạm\". Nhưng người được hướng dẫn lại là cư dân của \"thế giới chưa nhìn thấy\", nên đương nhiên không thể tiếp nhận tốt.",
      explanation:"Đáp án ③. 「『できる人』は、それぞれの仕事にあるマニュアル的なものを咀嚼して状況に対応します」⇒ hiểu kỹ mô phạm rồi ứng phó tình huống ⇒ ③. ① không nói tìm điểm xấu để cải tiến; ② thiếu vế \"ứng phó tình huống\" (chỉ làm đúng mô phạm là người thường); ④ sai: bài nói công việc nào cũng có mô phạm."},
    { id:"b11-8", passage:"", audioUrl:"", question:"64. 筆者によると、「できる人」が人を育てるときに問題になることは何か。",
      options:["マニュアルを使わないで、自分の好きなように説明してしまうこと","自分ができることは説明できても、できないことはうまく説明できないこと","自分ができることだけでなく、できないことまで、相手に期待してしまうこと","自分にはできることでも、それをできない人もいることが実感できないこと"], answer:3,
      translation:"(Bài đọc: xem bản dịch ở câu 63)",
      explanation:"Đáp án ④. 「自分が自然とやってきたことを、なかなかできない人がたくさんいるという事実。これを頭では理解しても、なかなか感覚でキャッチできません」⇒ không thực cảm được rằng có người không làm được việc mình làm được ⇒ ④. ① bài không nói \"không dùng mô phạm\"; ② không nói \"không giải thích được việc mình không làm được\"; ③ không nói \"kỳ vọng quá mức\"."},
  ]
},
{ tab: "読解", section: "問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction: "次のAとBの文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b12-1", passage:"<b>A</b> 新しい商品を企画するとき、いいアイディアがなかなか思いつかないことがある。そんなとき、自分には才能がないからだと思い込み、自信をなくしてしまうのはよくない。アイディアは生まれつきの能力に関係なく、努力次第で誰でも生み出すことができる。<br><br>アイディアは、情報の組み合わせによって生まれることがほとんどだ。そのため、日ごろから情報を集めておくことが有効だ。担当する商品に関連する情報だけを集めていると、似たようなアイディアばかりになってしまう。発想の幅を広げるには、関連する分野以外の情報も頭に入れておくほうがいい。ふだんから視野を広げてさまざまな情報を蓄積（ちくせき）しておけば、必ずアイディアの役に立つはずだ。<br><br><b>B</b> 新しい商品を企画するには、これまでとは異なるアイディアが必要だ。現在流行している商品の情報を集めるだけでは、他社に勝つことはできないだろう。私はアイディアを生み出すために、一般的に考えられていることとは逆の発想をするようにしている。現在流行している商品が若者向けの物なら高齢者向けにできないかと考えたり、多機能の物なら機能を一つに絞れないかと考えたりするのである。<br><br>アイディアは一部の才能がある人しか生み出せないものだという印象があるせいか、生み出し方を知ろうとしない人が多いと思う。才能がないからといってあきらめるのではなく、思い切って発想を転換してみれば、いいアイディアにつながっていく。", audioUrl:"", question:"65. アイディアを生み出すことについて、A と B が共通して述べていることは何か。",
      options:["アイディアの生み出し方は、簡単に身につけることができる。","多くの情報を得ることで、アイディアを生み出しやすくなる。","特別な能力がなくても、アイディアを生み出すことができる。","発想のしかたを大きく変えなければ、アイディアは生み出せない。"], answer:2,
      translation:"A: Khi lên kế hoạch cho sản phẩm mới, có khi mãi không nghĩ ra ý tưởng hay. Lúc đó, đừng vội nghĩ rằng mình không có tài năng mà mất tự tin. Ý tưởng không liên quan đến năng lực bẩm sinh, ai cũng có thể tạo ra nếu nỗ lực. Ý tưởng hầu hết sinh ra từ việc kết hợp thông tin. Vì thế thu thập thông tin thường ngày rất hiệu quả. Nếu chỉ thu thập thông tin liên quan đến sản phẩm mình phụ trách thì chỉ toàn ra ý tưởng giống nhau. Để mở rộng phát tưởng, nên đưa cả thông tin ngoài lĩnh vực liên quan vào đầu. Nếu thường ngày mở rộng tầm nhìn, tích lũy nhiều thông tin thì chắc chắn sẽ có ích cho ý tưởng.<br><br>B: Để lên kế hoạch sản phẩm mới cần ý tưởng khác biệt so với trước nay. Chỉ thu thập thông tin về sản phẩm đang thịnh hành thì không thể thắng được công ty khác. Tôi, để sinh ra ý tưởng, cố phát tưởng ngược lại với điều thường được nghĩ. Ví dụ sản phẩm đang thịnh hành hướng tới người trẻ thì nghĩ xem có thể hướng tới người cao tuổi không, đồ nhiều chức năng thì nghĩ xem có thể rút lại còn một chức năng không. Có lẽ vì ấn tượng \"ý tưởng chỉ người có tài mới sinh ra được\" nên nhiều người không tìm cách biết cách sinh ra nó. Đừng từ bỏ vì \"không có tài\", mà hãy mạnh dạn chuyển hướng phát tưởng thì sẽ dẫn tới ý tưởng hay.",
      explanation:"Đáp án ③. A:「アイディアは生まれつきの能力に関係なく、努力次第で誰でも生み出すことができる」. B:「アイディアは一部の才能がある人しか生み出せないものだという印象がある…才能がないからといってあきらめるのではなく」⇒ cả hai đều nói không cần năng lực đặc biệt ⇒ ③. ① không nhắc \"dễ học được\"; ② chỉ A nói \"thu thập nhiều thông tin\", B nói ngược lại (cần ngược với thông tin phổ biến); ④ chỉ B đề cập \"chuyển hướng phát tưởng\"."},
    { id:"b12-2", passage:"", audioUrl:"", question:"66. 新しい商品を企画することについて、A と B はどのようなアドバイスをしているか。",
      options:["A もB も、いろいろな分野の情報をできるだけ多く集めるといいと述べている。","A もB も、流行している商品について詳しく調べるといいと述べている。","A は関連する分野の他社の商品の情報を集めるといいと述べ、B は流行に逆らった考え方をするといいと述べている。","A は関連する分野だけでなく、ほかの分野の情報も得るといいと述べ、B は普通とは反対のことを考えるといいと述べている。"], answer:3,
      translation:"(Bài đọc: xem bản dịch ở câu 65)",
      explanation:"Đáp án ④. A:「関連する分野以外の情報も頭に入れておくほうがいい」. B:「一般的に考えられていることとは逆の発想をするようにしている」⇒ A: lấy cả thông tin ngoài lĩnh vực liên quan, B: nghĩ ngược với điều bình thường ⇒ ④. ① B không nói \"thu thập nhiều thông tin\" (ngược lại); ② B nói chỉ thông tin hàng thịnh hành thì không thắng được, ③ A không nhắc \"thông tin sản phẩm của công ty khác\"."},
  ]
},
{ tab: "読解", section: "問題13 主張理解・長文",
  instruction: "次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b13-1", passage:"読むことは、受動的な（注1）作業だと思っている人は意外に多い。（中略）読んでインプットして、書いてアウトプットする。そうではなくて、両方アウトプットなのだというのが、私の持論（注2）である。<br><br>そこにある言葉を読む。すると心には、文字以上のものが広がる。たとえば、子どものころ読んだ海外作品に、聞いたこともない料理名が出てくるということが、よくあった。クロスグリのパイだとか、ジンジャークッキーだとか。食べたことのないものを、懸命に想像して味わう。それを食べる主人公の舌を、獲得するわけである。<b>①この行為</b>は、受動ではなく能動（注3）である。「創る」作業である。本でしか読んだことのない食べものを、大人になってから実際に食べ、「違う」と思った経験を持つ人は、意外に多いのではないだろうか。もちろん違うのは私たちの想像なのだが、しかし自分の頭のなかで創った料理のほうが、断然（注4）おいしかった、ということは、よくある。<br><br>本を読まない、というのは、だから、私にとって創造の放棄（注5）である。<b>②つまらない本</b>、相性が悪い本というのはもちろんある。しかしそこで、どこがどんなふうにつまらないのか、どう展開したらおもしろかったのか、自分のどの部分と相性が悪いのか、そんなことを考えていると、つまらない本はおもしろくなるし、相性が悪い本はいつか相性がよくなる日を待とうと思うことができる。私は、おもしろかった本よりつまらなかった本のあらすじを人に話すほうが、ずっと好きだ。どこがどんなふうにつまらなく感じたかを話すのは、それだけ創造の余地（注6）があるからだろう。<br><br>料理でも、絵画でも、あるいは家事の手順でも、創ることの喜びを知ってしまうと、なかなかそれから離れることができない。読むことの楽しみは、と訊かれれば（注7）、創ることの自由さだと私は答える。<br><br>（注1）受動的な：ここでは、受け取るだけの<br>（注2）持論：いつも持っている考え<br>（注3）能動：自ら進んで行うこと<br>（注4）断然：ずっと<br>（注5）〜の放棄：〜を捨てること<br>（注6）余地：ここでは、可能性<br>（注7）訊く：「聞く」と同じ", audioUrl:"", question:"67. ①この行為とはどういうことか。",
      options:["実際に、主人公が食べていた食べものを味わってみること。","食べたことのないものを主人公と一緒に食べているところを想像すること。","主人公がどんな食べものが好きかを想像してみること。","主人公になりきって、食べたことのないものを想像して味わうこと。"], answer:3,
      translation:"Nhiều người bất ngờ khi nghĩ rằng đọc là công việc thụ động. (Lược) Đọc để input, viết để output. Không phải vậy, mà cả hai đều là output — đó là chủ trương của tôi. Đọc những từ ngữ ở đó, thì trong lòng ta lan rộng ra những thứ hơn cả chữ nghĩa. Ví dụ, trong các tác phẩm nước ngoài đọc hồi nhỏ, thường có tên món ăn chưa từng nghe. Như bánh pie quả lý chua đen, hay bánh quy gừng. Ta ra sức tưởng tượng và nếm thử những thứ chưa từng ăn. Ta \"có được\" cái lưỡi của nhân vật ăn nó. ①Hành vi này không phải thụ động mà là chủ động. Là công việc \"sáng tạo\". Những thứ chỉ đọc thấy trong sách, khi lớn lên ăn thật rồi thấy \"khác\", hẳn nhiều người có trải nghiệm đó. Tất nhiên cái khác là sự tưởng tượng của ta, nhưng chuyện món ăn do ta tạo ra trong đầu lại ngon hơn hẳn là chuyện thường gặp. Vì thế, không đọc sách, với tôi là sự từ bỏ sáng tạo. ②Sách dở, sách không hợp thì tất nhiên có. Nhưng khi nghĩ xem dở ở đâu, dở thế nào, nếu triển khai ra sao thì sẽ thú vị, phần nào của mình không hợp với nó, thì sách dở trở nên thú vị, và sách không hợp thì ta có thể nghĩ \"hãy chờ ngày nào đó hợp nhau\". Tôi thích kể tóm tắt sách dở cho người khác hơn là sách hay. Kể xem mình thấy dở ở đâu, dở thế nào là bởi vì chừng đó vẫn còn dư địa cho sáng tạo. Nấu ăn, hội họa, hay cả trình tự việc nhà, một khi biết niềm vui sáng tạo thì khó rời xa nó. Nếu được hỏi niềm vui của việc đọc là gì, tôi trả lời: sự tự do của việc sáng tạo.",
      explanation:"Đáp án ④. 「食べたことのないものを、懸命に想像して味わう。それを食べる主人公の舌を、獲得するわけである」⇒ hóa thân thành nhân vật, tưởng tượng và nếm thứ chưa từng ăn ⇒ ④. ① sai vì chỉ đọc trong sách, không ăn thật (đó là đoạn sau dành cho người lớn); ② không nói \"ăn cùng nhân vật\"; ③ không nói \"nhân vật thích món gì\"."},
    { id:"b13-2", passage:"", audioUrl:"", question:"68. ②つまらない本について、筆者はどのように述べているか。",
      options:["つまらなく感じた点についていろいろ考えていると、おもしろくなる。","つまらなく感じた理由を考えていると、自分の好みがよく分かってくる。","つまらないと思っても、いつか必ず相性がよくなる日がくる。","つまらないと思っても、人にあらすじを話すと面白いところが見つけられる。"], answer:0,
      translation:"(Bài đọc: xem bản dịch ở câu 67)",
      explanation:"Đáp án ①. 「どこがどんなふうにつまらないのか、どう展開したらおもしろかったのか…そんなことを考えていると、つまらない本はおもしろくなる」⇒ ①. ② bài nói \"phần nào của mình không hợp\", không nói \"hiểu rõ sở thích của mình\"; ③ bài nói có thể \"chờ ngày hợp nhau\" (chứ không phải chắc chắn sẽ đến); ④ bài nói thích kể tóm tắt sách dở, không nói \"tìm ra chỗ thú vị\"."},
    { id:"b13-3", passage:"", audioUrl:"", question:"69. 本を読むことについて、筆者はどのように考えているか。",
      options:["本を読むことは、料理や絵画より創ることの喜びが大きい。","本を読むことは、自由に想像を膨らませる楽しい創造の作業だ。","本を読んでたくさん知ることができれば、創ることの喜びも増す。","本を読んで想像力を身につければ、生活のなかでも自由に創造が楽しめる。"], answer:1,
      translation:"(Bài đọc: xem bản dịch ở câu 67)",
      explanation:"Đáp án ②. 「読むことは受動ではなく能動である。『創る』作業である」「読むことの楽しみは…創ることの自由さだ」⇒ đọc là công việc sáng tạo, tự do tưởng tượng ⇒ ②. ① bài không so sánh \"niềm vui lớn hơn nấu ăn/hội họa\"; ③ không nói \"biết nhiều thì niềm vui sáng tạo tăng\"; ④ không nói \"nhờ đọc mà vui sáng tạo trong đời sống\"."},
  ]
},
{ tab: "読解", section: "問題14 情報検索",
  instruction: "右のページは、ある動画コンテストの募集案内である。下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b14-1", passage:"<b>春口市「動画コンテスト」<br>動画作品募集のご案内</b><br>春口市の魅力をアピールする動画を募集します。受賞した作品は、春口市のホームページで公開し、市の魅力を伝える活動に使用させていただきます。<br><br><b>１．募集する作品</b><br>以下の①か②のどちらかの部門に応募してください。応募できるのは、一人1作品で、未発表の作品に限ります。<br>　①緑茶部門　春口市の緑茶をアピールする、20秒から30秒の作品<br>　②観光部門　春口市の歴史、文化、自然に関する、2分から5分の作品<br><br><b>２．応募資格</b>　高校生以上の方であれば、どなたでも応募可能です。<br><br><b>３．選考方法と賞品</b><br>選考は、春口市出身の映像作家である花山洋子氏を委員長とする選考委員会が行います。賞品として、最優秀賞受賞者（①②各1名）に商品券3万円分を、優秀賞受賞者（①②各2名）に商品券1万円分を、応募者全員に記念品を差し上げます。<br><br><b>４．応募方法</b><br>4月15日（月）から5月10日（金）までの間に、春口市広報課ホームページの応募用ページから必要な情報を送信してください。その後、動画を以下の（1）か（2）のどちらかの方法で送ってください。<br>（1）DVDに記録して郵送する場合<br>　作品をDVDに記録して、5月17日（金）必着で郵送してください。なお、提出されたDVDは返却いたしません。<br>（2）インターネットで送信する場合<br>　応募の受付後1週間以内に動画送信用ページの情報をお知らせするので、5月24日（金）までに送信してください。<br><br><b>５．応募および問い合わせ先</b><br>春口市役所広報課（市役所3階）<br>〒129-9988 春口市東町1丁目1番　電話・FAX 032-451-6879<br>ホームページ http://haruguchi-jp.com/video-contest<br><br><b>（4人の応募予定者）</b><br><table border='1' cellpadding='4' style='border-collapse:collapse;font-size:0.9em'><tr><th>名前</th><th>職業</th><th>作品の内容</th><th>応募動画の長さ</th><th>応募動画の発表歴</th></tr><tr><td>ヤンさん</td><td>高校生</td><td>春口市の自然の魅力</td><td>25秒</td><td>なし</td></tr><tr><td>村木さん</td><td>塾講師</td><td>春口市の緑茶の魅力</td><td>28秒</td><td>なし</td></tr><tr><td>長島さん</td><td>会社員</td><td>春口市の歴史的な建物</td><td>3分45秒</td><td>あり</td></tr><tr><td>原田さん</td><td>中学生</td><td>春口市の祭りの文化</td><td>2分15秒</td><td>なし</td></tr></table>", audioUrl:"", question:"70. 次の4人は、動画コンテストに応募しようと考えている。現段階で応募条件を満たしているのは誰か。",
      options:["ヤンさん","村木さん","長島さん","原田さん"], answer:1,
      translation:"春口市 \"Cuộc thi video\": Thông báo mời gửi tác phẩm video quảng bá sức hút của thành phố Haruguchi. Tác phẩm đoạt giải sẽ được công khai trên trang web của thành phố và dùng cho hoạt động truyền bá sức hút của thành phố.<br><br>1. Tác phẩm dự thi: chọn một trong hai hạng mục. Mỗi người 1 tác phẩm, chỉ nhận tác phẩm chưa công bố. ①Hạng mục trà xanh: tác phẩm 20–30 giây quảng bá trà xanh của thành phố. ②Hạng mục du lịch: tác phẩm 2–5 phút về lịch sử, văn hóa, thiên nhiên của thành phố.<br>2. Điều kiện: ai từ học sinh trung học phổ thông trở lên đều có thể dự thi.<br>3. Cách tuyển chọn và giải thưởng: hội đồng giám khảo do nhà làm phim Hanayama Yoko gốc thành phố làm chủ tịch tuyển chọn. Giải thưởng: giải xuất sắc nhất (mỗi hạng mục 1 người) phiếu mua hàng 3 vạn yên; giải khuyến khích (mỗi hạng mục 2 người) phiếu 1 vạn yên; tất cả người dự thi đều nhận quà kỷ niệm.<br>4. Cách đăng ký: từ 15/4 (thứ Hai) đến 10/5 (thứ Sáu), gửi thông tin cần thiết từ trang đăng ký trên website phòng tuyên truyền thành phố. Sau đó gửi video theo một trong hai cách: (1) ghi vào DVD và gửi bưu điện, phải đến trước ngày 17/5 (thứ Sáu); DVD không hoàn trả. (2) gửi qua Internet: trong vòng 1 tuần sau khi nhận đăng ký sẽ thông báo thông tin trang gửi video, hãy gửi trước ngày 24/5 (thứ Sáu).<br>5. Liên hệ: phòng tuyên truyền tòa thị chính Haruguchi.<br><br>Bảng 4 người dự kiến dự thi: ヤン – học sinh cấp 3 – vẻ đẹp thiên nhiên Haruguchi – 25 giây – chưa công bố. 村木 – giáo viên luyện thi – vẻ đẹp trà xanh Haruguchi – 28 giây – chưa công bố. 長島 – nhân viên công ty – các công trình lịch sử của Haruguchi – 3 phút 45 giây – đã công bố. 原田 – học sinh cấp 2 – văn hóa lễ hội Haruguchi – 2 phút 15 giây – chưa công bố.",
      explanation:"Đáp án ②. Điều kiện: 高校生以上 = từ THPT trở lên (→ 原田 học sinh cấp 2 loại ⇒ ④ sai), 未発表の作品 (→ 長島 có 発表歴 loại ⇒ ③ sai). ヤンさん: nội dung 自然 → hạng mục ② yêu cầu 2–5 phút nhưng chỉ 25 giây ⇒ loại (① sai). 村木さん: nội dung 緑茶 → hạng mục ① yêu cầu 20–30 giây, 28 giây thỏa mãn; là 塾講師 (≥ THPT), chưa công bố ⇒ đủ điều kiện ⇒ ②."},
    { id:"b14-2", passage:"", audioUrl:"", question:"71. ローズさんは、動画コンテストに応募しようと考えている。動画は、インターネットで送りたい。ローズさんは、どうしなければならないか。",
      options:["5月10日までに応募情報を送信し、17日までに動画を送信する。","5月10日までに応募情報を送信し、24日までに動画を送信する。","5月10日までに応募情報と動画を送信する。","5月24日までに応募情報と動画を送信する。"], answer:1,
      translation:"(Bài đọc: xem bản dịch ở câu 70)",
      explanation:"Đáp án ②. 応募情報 phải gửi trong khoảng 15/4–10/5 ⇒ \"đến 10/5\". Vì ローズ gửi video qua Internet nên theo mục (2): gửi động từ trước 24/5 ⇒ ②. ① 17/5 là hạn của cách gửi DVD. ③ phải gửi thông tin trước rồi mới gửi video (không cùng lúc). ④ gửi thông tin muộn nhất 10/5 chứ không phải 24/5."},
  ]
},
/* ================= TAB 5: 聴解 ================= */
{ tab: "聴解", section: "問題1 課題理解",
  instruction: "まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions: [
    { id:"c1-1", passage:"大学で女の学生と男の学生が話しています。<br>女：中村くん。シンポジウムのポスター、掲示板に貼ってくれたんだね。ありがとう。<br>男：えぇ、他に僕がやっておくことってありますか?<br>女：マイクとか会場の準備は前日にすればいいし、当日のスタッフ用のスケジュール表、これないから欲しいな。今週中にお願いしていい?<br>男：あ、はい。<br>女：それから1番大事な当日配る資料、コピーまだなんじゃない?100部だよね?<br>男：あ、それなんですけど、発表者の方からの資料まだ全部集まってないんですよ。<br>女：そう、みなさんお忙しい方ばかりだから⋯私から発表者に資料を送ってもらうようにすぐに連絡をするから、集まり次第コピーしよう。週明けには出してもらうようにするね。<br>男：はい、わかりました。", audioUrl:"", question:"1番 男の学生はこの後まず、何をしますか。",
      options:["シンポジウムのポスターをはる","スタッフの当日の予定表を作る","当日配るしりょうをコピーする","発表者にれんらくする"], answer:1,
      translation:"Ở trường đại học, một nữ sinh và một nam sinh đang nói chuyện.<br>Nữ: Nakamura, cậu đã dán poster hội thảo lên bảng tin rồi nhỉ. Cảm ơn nhé.<br>Nam: Vâng, còn việc gì nữa tớ nên làm trước không ạ?<br>Nữ: Mic với chuẩn bị hội trường thì làm trước một ngày là được; còn bảng lịch trình cho nhân viên ngày hôm đó, cái này chưa có nên mình muốn có. Trong tuần này làm giúp được không?<br>Nam: À, vâng.<br>Nữ: Rồi tài liệu phát trong ngày — quan trọng nhất ấy, chưa photo đúng không? 100 bản nhỉ?<br>Nam: À, chuyện đó thì tài liệu từ phía người trình bày vẫn chưa tập hợp hết ạ.<br>Nữ: Vậy à, mn đều bận nên tớ sẽ liên lạc ngay để người trình bày gửi tài liệu; tập hợp xong thì photo. Đầu tuần sau tớ sẽ để mọi người nộp.<br>Nam: Vâng, tớ hiểu rồi.",
      explanation:"Đáp án ②. Cô giao bảng lịch trình dùng cho nhân viên ngày diễn ra: 「当日のスタッフ用のスケジュール表…今週中にお願いしていい?」→ nam sinh đồng ý 「あ、はい」⇒ việc làm ngay tiếp theo là làm 予定表 ⇒ ②. ① đã dán xong (được khen). ③ tài liệu chưa tập hợp hết và cô ấy sẽ liên hệ trước → chỉ photo sau khi tập hợp đủ. ④ người liên lạc với người trình bày là cô ấy (「私から…連絡をする」)."},
    { id:"c1-2", passage:"スーパーで男の店長と女の店員が話しています。<br>男：おはようございます、森田さん。今日は一部の商品に割引きシールを付ける作業をやってくれることになってたね。<br>女：あ、はい。準備してます。<br>男：えっと、忙しい時に悪いんだけど、倉庫に行って南コーヒーの豆、何袋あるか数えてきてくれる?数が少なかったら今日中に注文しないといけないんだ。<br>女：あ、わかりました。急ぎですか?<br>男：あー、そのシールを貼る作業が終わってからでいいから。袋の数を数えたらメモを私の机の上に置いといて。<br>女：わかりました。<br>男：お客さんがレジにたくさん並んでるから、私もすぐレジを手伝わなきゃいけなくて。値引シールを付けた商品をレジの横の棚に並べるのは明日の開店前にみんなですればいいから。じゃ、よろしくね。", audioUrl:"", question:"2番 女の店員はこの後まず、何をしますか。",
      options:["商品に値引きシールをはる","そうこで南コーヒーの数を数える","レジの手伝いをする","商品をレジの横のたなにならべる"], answer:0,
      translation:"Ở siêu thị, ông quản lý (nam) và nữ nhân viên đang nói chuyện.<br>Nam: Chào buổi sáng, chị Morita. Hôm nay chị được giao việc dán nhãn giảm giá cho một số sản phẩm nhỉ.<br>Nữ: À vâng. Em đang chuẩn bị.<br>Nam: Ơ, xin lỗi vì làm phiền lúc bận, nhưng chị ra kho đếm xem hạt cà phê Nam có bao nhiêu túi giúp tôi được không? Nếu ít quá thì phải đặt hàng trong hôm nay.<br>Nữ: Vâng, em hiểu rồi. Gấp không ạ?<br>Nam: À, việc đó làm sau khi xong việc dán nhãn cũng được. Đếm xong số túi thì để ghi chú lên bàn tôi.<br>Nữ: Vâng.<br>Nam: Khách xếp hàng đông ở quầy nên tôi cũng phải ra giúp quầy ngay. Việc xếp hàng giảm giá lên kệ cạnh quầy thì sáng mai trước giờ mở cửa cả nhóm làm là được. Vậy nhờ chị nhé.",
      explanation:"Đáp án ①. Việc đếm túi cà phê mà quản lý nhờ phải làm sau: 「そのシールを貼る作業が終わってからでいいから」⇒ việc đầu tiên là tiếp tục dán nhãn giảm giá ⇒ ①. ② là việc làm tiếp sau khi xong dán nhãn; ③ là việc của quản lý (tôi phải giúp quầy); ④ để sáng mai trước giờ mở cửa cả nhóm làm."},
    { id:"c1-3", passage:"出版社で女の人と男の人が話しています。<br>女：すみません、雑誌に載せる蕎麦屋の写真を私の代わりに撮りに行ってくれるそうでありがとうございます。<br>男：あ、はい。緑駅前の蕎麦屋さんですよね?<br>女：はい。えっと、説明しますね。この雑誌では通常はお店で1番の人気料理の写真を撮らせてもらうんですが、今回この写真はお店から提供していただくことになっています。<br>男：はい、わかりました。<br>女：それから店内の様子の撮影についてはお店に許可をいただいています。お客様が写り込まないように撮影をお願いしますね。調理する人の写真は店によっては掲載しますが、こちらは掲載不可とのことです。<br>男：はい。<br>女：外から見た入口の写真は天候に左右されるから先日、天気が良い日に済ませてきましたので結構です。よろしくお願いします。<br>男：わかりました。", audioUrl:"", question:"3番 男の人は何の写真を撮らなければなりませんか。",
      options:["店で一番の人気料理","店の中の様子","店の調理人の様子","店の入り口の様子"], answer:1,
      translation:"Ở nhà xuất bản, một người nữ và một người nam đang nói chuyện.<br>Nữ: Xin lỗi, cảm ơn anh đã nhận đi chụp thay tôi ảnh quán soba để đăng tạp chí.<br>Nam: À vâng. Là quán soba trước ga Midori đúng không ạ?<br>Nữ: Đúng rồi. Để tôi giải thích nhé. Với tạp chí này, thông thường chúng tôi xin chụp ảnh món ăn được yêu thích nhất ở quán, nhưng lần này ảnh đó sẽ do quán cung cấp.<br>Nam: Vâng, tôi hiểu rồi.<br>Nữ: Tiếp theo, việc chụp cảnh bên trong quán đã được quán cho phép. Anh chụp sao cho khách không bị lọt vào ảnh nhé. Ảnh người nấu thì tùy quán sẽ đăng, nhưng quán này không được đăng ạ.<br>Nam: Vâng.<br>Nữ: Ảnh cửa vào nhìn từ bên ngoài phụ thuộc thời tiết nên hôm trước tôi đã làm rồi vào ngày đẹp trời, nên không cần nữa. Nhờ anh nhé.<br>Nam: Tôi hiểu rồi.",
      explanation:"Đáp án ②. 「店内の様子の撮影についてはお店に許可をいただいています…撮影をお願いしますね」⇒ phải chụp cảnh bên trong quán ⇒ ②. ① ảnh món ăn do quán cung cấp; ③ ảnh người nấu không được đăng (掲載不可); ④ ảnh cửa vào đã chụp xong hôm trước."},
    { id:"c1-4", passage:"日本語学校で女の職員と男の課長が話しています。<br>女：課長、明日の卒業パーティについてですけど、あとは何をしましょうか。<br>男：卒業生の皆さんに渡す記念品は袋に入れてくれた?<br>女：まだ届いていないんですよ。<br>男：あ、記念品の納品は3時だったね。あと1時間か⋯⋯それじゃ、会場の入り口の花瓶、あれをステージの上に運んでくれる?<br>女：はい、花瓶ですね。<br>男：それと記念品の到着を待ってる間、出席者の名前を書いた紙を椅子に貼ってくれない?そうだ、忘れないうちに言っとくけど明日の朝一番に卒業生代表のグエンさんと挨拶のリハーサルをお願いね。<br>女：はい、わかりました。<br>男：あ、花瓶の移動なんだけど、落とすといけないから記念品の準備の後で私と一緒にやりましょうか。<br>女：はい。", audioUrl:"", question:"4番 女の職員はこの後まず、何をしますか。",
      options:["記念品をふくろに入れる","かびんをステージの上に運ぶ","いすに出席者の名前の紙をはる","代表者とあいさつの練習をする"], answer:2,
      translation:"Ở trường tiếng Nhật, nữ nhân viên và trưởng phòng (nam) đang nói chuyện.<br>Nữ: Trưởng phòng, về tiệc tốt nghiệp ngày mai ạ, còn phải làm gì nữa ạ?<br>Nam: Quà kỷ niệm tặng học viên tốt nghiệp, em đã cho vào túi chưa?<br>Nữ: Vẫn chưa được giao đến ạ.<br>Nam: À, quà kỷ niệm giao lúc 3 giờ nhỉ. Còn 1 tiếng nữa… Vậy thì, lọ hoa ở cửa vào hội trường, em mang nó lên sân khấu được không?<br>Nữ: Vâng, lọ hoa ạ.<br>Nam: Và trong lúc chờ quà kỷ niệm đến, em dán giấy ghi tên người tham dự lên ghế được không? À này, nói luôn cho khỏi quên: sáng sớm mai em nhờ tập dượt lời chào với bạn Nguyen — đại diện học viên tốt nghiệp nhé.<br>Nữ: Vâng, em hiểu rồi.<br>Nam: À, việc chuyển lọ hoa, sợ làm rơi nên để sau khi chuẩn bị quà kỷ niệm, hai chúng ta cùng làm nhé.<br>Nữ: Vâng.",
      explanation:"Đáp án ③. Việc làm ngay trong lúc chờ quà kỷ niệm (3 giờ mới đến, còn 1 tiếng): 「記念品の到着を待ってる間、出席者の名前を書いた紙を椅子に貼ってくれない?」⇒ ③. ② lọ hoa: trưởng phòng nói để làm cùng nhau sau khi chuẩn bị quà kỷ niệm (「記念品の準備の後で私と一緒に」) ⇒ không phải việc làm ngay. ① quà kỷ niệm chưa giao đến. ④ tập dượt lời chào là việc sáng mai."},
    { id:"c1-5", passage:"大学で女の学生と男の学生が話しています。<br>女：田中くん、聞いて。昨日自転車、駅前に止めてたんだけど、乗って帰ろうとしたら自転車がなくて・・・。置いといた場所の地面に「駐輪禁止区域のため移動しました」って紙が貼られてたんだよ。<br>男：駅前は駐輪場以外には停めちゃいけないんだよ。<br>女：そうなんだ。どうすればいいの?自転車、警察に取りに行くの?<br>男：警察じゃないと思うけど⋯貼られてた紙に預かり場所、書いてなかった?<br>女：よく読まなかった。<br>男：えーっと、そしたら市役所のホームページに書いてあるから確認して。取りに行くならそれからだよ。<br>女：わかった。<br>男：確か身分証明書がいるよ。あ、あとお金もいる。自転車受け取る時払うよ。<br>女：お金払うの?<br>男：うん、自転車の預かり料だよ。", audioUrl:"", question:"5番 女の学生はこの後、何をしますか。",
      options:["駅前で自転車をさがす","市役所へ自転車を取りに行く","自転車の預かり場所を調べる","けいさつでお金を払う"], answer:2,
      translation:"Ở trường đại học, nữ sinh và nam sinh đang nói chuyện.<br>Nữ: Tanaka, nghe này. Hôm qua tớ để xe đạp trước ga, định đạp về thì xe biến mất… Ở chỗ đất nơi để xe có dán giấy \"đã di chuyển vì khu vực cấm đỗ xe\".<br>Nam: Trước ga thì không được đỗ ngoài bãi đỗ xe đạp đâu.<br>Nữ: Vậy à. Phải làm sao? Ra cảnh sát lấy lại xe à?<br>Nam: Tớ nghĩ không phải cảnh sát… Trên tờ giấy dán đó không ghi nơi gửi giữ à?<br>Nữ: Tớ không đọc kỹ.<br>Nam: Ờ… vậy thì nó ghi trên trang web của tòa thị chính, cậu xem thử đi. Muốn đi lấy thì làm sau đó.<br>Nữ: Hiểu rồi.<br>Nam: Chắc là cần giấy tờ tùy thân. À, còn cần tiền nữa. Trả khi nhận xe.<br>Nữ: Phải trả tiền à?<br>Nam: Ừ, tiền gửi giữ xe đạp mà.",
      explanation:"Đáp án ③. Nam nói: 「市役所のホームページに書いてあるから確認して。取りに行くならそれからだよ」⇒ trước tiên phải kiểm tra nơi gửi giữ xe trên web ⇒ ③. ① không đi tìm ở trước ga (xe đã bị di chuyển). ② lấy xe là việc sau khi biết nơi gửi giữ, và không phải \"tòa thị chính\" là nơi để xe. ④ tiền là tiền gửi xe, trả ở nơi nhận xe chứ không phải ở cảnh sát."},
  ]
},
{ tab: "聴解", section: "問題2 ポイント理解",
  instruction: "まず質問を聞いてください。そのあと、問題用紙を見てください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions: [
    { id:"c2-1", passage:"テレビでアナウンサーの女の人がパン屋の店長にインタビューをしています。<br>女：店長の山本さんです。こちらのお店の手作りのパン、大変人気ですが山本さんご自身は以前、会社員をなされていたんですよね?<br>男：はい。この店はもともとパン作りが好きな母がやる予定だったんですが、店を出す準備をしている途中で母が病気になってしまいました。母はずっとパン屋をやりたかったので店を諦めることをとても残念がっていたんですよ。それで「やってくれ」と言われたわけじゃないんですが、僕が何とか形にしたいと思いました。<br>女：それまでパン作りのご経験はあったんですか?<br>男：いえ、全くなくて⋯⋯。パン作りは専門学校で一から勉強しました。卒業する前に母は亡くなりました。<br>女：そうでしたか。<br>男：母のレベルにはまだまだなんですが、おいしいパンを地元の方に食べてもらえるように頑張っています。", audioUrl:"", question:"1番 店長はどうしてパン屋を始めたと言っていますか。",
      options:["母といっしょにパン屋をやりたかったから","母にたのまれたから","母のゆめをかなえたかったから","母のパンの味を残したかったから"], answer:2,
      translation:"Trên TV, nữ phát thanh viên đang phỏng vấn chủ tiệm bánh (nam).<br>Nữ: Đây là anh Yamamoto, chủ tiệm. Bánh thủ công của tiệm rất được ưa chuộng, mà bản thân anh trước đây từng là nhân viên công ty đúng không ạ?<br>Nam: Vâng. Tiệm này vốn dĩ mẹ tôi — người thích làm bánh — định mở, nhưng đang chuẩn bị mở tiệm thì mẹ tôi bị bệnh. Mẹ tôi luôn muốn mở tiệm bánh nên rất tiếc khi phải từ bỏ. Vì vậy, tuy không phải là mẹ bảo \"con làm đi\", nhưng tôi muốn bằng cách nào đó biến nó thành hiện thực.<br>Nữ: Trước đó anh đã có kinh nghiệm làm bánh chưa ạ?<br>Nam: Chưa, hoàn toàn không… Tôi học làm bánh từ đầu ở trường chuyên môn. Mẹ tôi mất trước khi tôi tốt nghiệp.<br>Nữ: Vậy ạ.<br>Nam: So với mẹ tôi thì còn kém xa, nhưng tôi đang cố gắng để người địa phương được ăn bánh ngon.",
      explanation:"Đáp án ③. 「母はずっとパン屋をやりたかったので店を諦めることをとても残念がっていた…僕が何とか形にしたいと思いました」⇒ muốn thay mẹ thực hiện ước mơ ⇒ ③. ② sai vì có nói rõ 「『やってくれ』と言われたわけじゃないんですが」 (không phải mẹ nhờ). ① sai: mẹ định tự làm, không phải hai mẹ con cùng làm. ④ không hề nói muốn giữ hương vị bánh của mẹ."},
    { id:"c2-2", passage:"うちで女の人と男の人が話しています。<br>女：引っ越し会社に引越しの見積もりを出してもらったけど予算よりかなり高かったよ。今の時期はどこの会社も高いんだね。荷物の量と移動距離で料金を計算するから荷物を減らせば安くなるって。<br>男：そう、んー。大きい荷物を減らそうか。えーっと、大きいものって言ったらソファー、冷蔵庫、本棚だね。<br>女：本棚は分解できるよ。ソファーはあまり使ってないし、欲しい人にあげてもいいかもしれないね。<br>男：それもそうだね。あ、冷蔵庫は古いし、この際、売って向こうで新しいのを買う?<br>女：えー?冷蔵庫はまだ使うよ!あ、そうだ。親戚のおじさんがトラックを持ってるからおじさんに手伝ってもらって、自分たちで荷物を運ぶ?<br>男：荷物の積み降ろしって結構大変だよ。やっぱり引っ越し会社に頼んだ方がいいんじゃないかな?<br>女：うーん、そうだね。安い引っ越し会社は見つからないだろうし、費用を抑えられるようにあんまり使ってない大きい家具のもらい手を探そうか。<br>男：うん、そうだね。", audioUrl:"", question:"2番 2人は引っ越しの値段を安くするため、どうすることにしましたか。",
      options:["ソファーをもらってくれる人をさがす","れいぞうこを売る","親戚にひっこしを手伝ってもらう","安いひっこし会社をさがす"], answer:0,
      translation:"Ở nhà, một người nữ và một người nam đang nói chuyện.<br>Nữ: Công ty chuyển nhà đã đưa bảng báo giá nhưng cao hơn nhiều so với dự toán. Mùa này công ty nào cũng đắt nhỉ. Họ tính phí theo khối lượng đồ và quãng đường nên nếu giảm đồ thì sẽ rẻ hơn.<br>Nam: Vậy à, ừm. Giảm đồ cỡ lớn nhỉ. Nào, đồ cỡ lớn thì có sofa, tủ lạnh, giá sách.<br>Nữ: Giá sách thì tháo rời được. Sofa thì ít dùng, có khi cho người cần cũng được.<br>Nam: Cũng đúng. À, tủ lạnh thì cũ rồi, nhân dịp này bán đi rồi sang bên kia mua cái mới?<br>Nữ: Ơ? Tủ lạnh vẫn dùng chứ! À, này. Bác họ tôi có xe tải nên nhờ bác giúp, tự mình chuyển đồ nhé?<br>Nam: Bốc dỡ đồ đạc khá vất vả đấy. Hay là vẫn nên nhờ công ty chuyển nhà?<br>Nữ: Ừm… Cũng đúng. Chắc không tìm được công ty rẻ, vậy để giảm chi phí, mình tìm người nhận đồ nội thất lớn ít dùng nhé.<br>Nam: Ừ, vậy đi.",
      explanation:"Đáp án ①. Kết luận của hai người: 「費用を抑えられるようにあんまり使ってない大きい家具のもらい手を探そうか」「うん、そうだね」⇒ tìm người nhận đồ nội thất lớn ít dùng (ソファー) ⇒ ①. ② tủ lạnh: nữ phản đối 「冷蔵庫はまだ使うよ」. ③ nhờ bác họ giúp: nam phản đối 「積み降ろしって結構大変…引っ越し会社に頼んだ方が」, nữ cũng đồng ý không làm. ④ bài nói không tìm được công ty rẻ 「安い引っ越し会社は見つからないだろうし」."},
    { id:"c2-3", passage:"会社で男の人と女の人がアンケートについて話しています。<br>男：働き方の改善の社内アンケート調査、もう書いた?「改善すべきことがあるか」って聞かれてもすぐ思い浮かばなくて⋯。<br>女：そう、残業代のアップも私たち社員が声を上げたから実現したし、言うべきことは言ったほうがいいんじゃない?私は有給とかの休暇の取得申請、もっと簡単に申請できるように改善してほしいんだよね。<br>男：あー、そう言うことを書けばいいんだね。<br>女：そうそう。私はそうしようと思ってる。あ、そういえば、この間、在宅での勤務を今、週2日可能だけどもっと増やしてほしいって言ってなかった?<br>男：そうだ、それを書こう。あと社内のパソコンを新しくしてほしいんだよね。今の古くって。<br>女：パソコン、今年度中には買い換えるって聞いたよ。<br>男：あ、じゃ、いいね。", audioUrl:"", question:"3番 女の人はアンケートに何を書くと言っていますか。",
      options:["残業代のきんがくをもっと上げてほしい","休暇の申請方法を簡単にしてほしい","在宅でのきんむを増やしてほしい","パソコンを新しくしてほしい"], answer:1,
      translation:"Ở công ty, một người nam và một người nữ nói chuyện về bản khảo sát.<br>Nam: Bản khảo sát nội bộ về cải thiện cách làm việc, anh viết chưa? Bị hỏi \"có gì cần cải thiện không\" mà tôi không nghĩ ra ngay…<br>Nữ: Vậy à, việc tăng tiền làm thêm cũng nhờ nhân viên chúng ta lên tiếng mới thành hiện thực, nên điều gì cần nói thì nên nói chứ? Tôi thì muốn việc xin nghỉ phép (như nghỉ có lương) được cải thiện để xin đơn giản hơn.<br>Nam: À, thì ra viết những điều như vậy.<br>Nữ: Đúng vậy. Tôi định viết thế. À nhân tiện, lần trước anh có nói hiện có thể làm ở nhà 2 ngày/tuần nhưng muốn tăng thêm đúng không?<br>Nam: Đúng, tôi sẽ viết cái đó. Và muốn thay máy tính trong công ty cho mới, vì cái hiện tại cũ quá.<br>Nữ: Nghe nói máy tính trong năm nay sẽ được đổi mới đấy.<br>Nam: À, vậy thì tốt.",
      explanation:"Đáp án ②. Phát ngôn của nữ nhân viên: 「私は有給とかの休暇の取得申請、もっと簡単に申請できるように改善してほしいんだよね」⇒ muốn việc xin nghỉ phép đơn giản hơn ⇒ ②. ① nữ chỉ nhắc việc tăng tiền làm thêm như ví dụ \"tiếng nói đã được thực hiện\", không nói mình sẽ viết. ③④ là nội dung nam nhân viên định viết (在宅勤務・パソコン)."},
    { id:"c2-4", passage:"女の学生と男の学生が毎日着る服について話しています。<br>女：岡田くん、ファッションの勉強をしているから教えてほしいんだけど…私、毎日どんな服を着たらいいのかわからなくて⋯。ファッション雑誌を見ても自分に似合うかどうかわからないし。<br>男：雑誌は参考になると思うけど、そうだね⋯あ、インターネットで毎月、洋服を送ってくれるサービスって知ってる?プロがその人に似合いそうな服を選んで送ってくれるんだよ。気に入ればそのまま買い取れるし、気に入らなければ返せばいいし。<br>女：あぁ、それ友達がやってた。でも私は送り返すのも面倒だなと思って。<br>男：うーん、僕は毎日シンプルな服を着てるよ。制服化って言うの?白いシャツに黒いズボンっていうスタイル。<br>女：そういえば岡田くんって大体いつもそうだね。でも学校の制服みたいに単調にならないのは小物を上手く取り入れてるからなんだね。<br>男：そうかな。あ、佐藤さん、リサイクルショップに行ったことある?種類がたくさんあってデザインもいろいろ選べるし、気に入るものがあるかもしれないよ。<br>女：中古か⋯ちょっと抵抗あるなぁ。<br>男：そう。じゃ、佐藤さんにはやっぱり僕と同じ方法がお勧めだね。", audioUrl:"", question:"4番 男の学生は女の学生にどうしたら1番いいと言っていますか。",
      options:["ファッション雑誌を参考にする","ファッションのプロに服を選んでもらう","毎日シンプルな服を着る","リサイクルショップで服を買う"], answer:2,
      translation:"Nữ sinh và nam sinh nói chuyện về quần áo mặc hằng ngày.<br>Nữ: Okada, cậu đang học về thời trang nên chỉ cho tớ với… Tớ không biết mỗi ngày nên mặc gì… Xem tạp chí thời trang cũng không biết có hợp với mình không.<br>Nam: Tạp chí thì tớ nghĩ là có ích, nhưng mà… À, cậu biết dịch vụ mỗi tháng gửi quần áo qua Internet không? Chuyên gia sẽ chọn và gửi những bộ đồ có vẻ hợp với người đó. Nếu thích thì mua luôn, không thích thì gửi trả.<br>Nữ: À, bạn tớ có dùng. Nhưng tớ thấy gửi trả cũng phiền.<br>Nam: Ừm… Tớ thì mặc đồ đơn giản mỗi ngày. Gọi là \"đồng phục hóa\" ấy? Kiểu áo trắng với quần đen.<br>Nữ: Nói mới nhớ, Okada lúc nào cũng vậy nhỉ. Nhưng không bị đơn điệu như đồng phục trường là nhờ cậu khéo phối phụ kiện.<br>Nam: Vậy à. À, Satô, cậu đã đến cửa hàng đồ cũ (recycle shop) chưa? Ở đó nhiều loại, thiết kế cũng đa dạng, có khi có cái cậu thích.<br>Nữ: Đồ cũ à… tớ hơi ngại.<br>Nam: Vậy à. Thế thì với Satô vẫn là nên dùng cách giống tớ.",
      explanation:"Đáp án ③. 「じゃ、佐藤さんにはやっぱり僕と同じ方法がお勧めだね」và cách của nam là 「僕は毎日シンプルな服を着てるよ。制服化」⇒ khuyên mặc quần áo đơn giản mỗi ngày ⇒ ③. ② dịch vụ chuyên gia: nữ nói gửi trả phiền ⇒ không được chọn. ④ cửa hàng đồ cũ: nữ nói 「ちょっと抵抗ある」⇒ không được chọn. ① tạp chí: nữ nói xem cũng không biết có hợp không."},
    { id:"c2-5", passage:"テレビでアナウンサーの男の人が女の人にインタビューしています。<br>男：今日は転職を経験されている会社員の内田さんにお話を伺います。<br>女：あ、はい。私は2回転職経験があります。転職というと経験を積んでそれを活かし、より給料の良いところに移っていく人もいますけど、どちらかというと現状に不満や不足を感じて居心地のいい場所を求める人が多いように感じます。私の最初の転職がそうでした。<br>男：そうですか。<br>女：現在は友人が新しく作った会社に入れてもらったんです。前に勤めてた会社に何か不満があったわけじゃなく、新たな世界を見てみたいと思っていた時だったので。分野は全然違うんですけど、やり甲斐があります。<br>男：そういう理由もあるんですね。", audioUrl:"", question:"5番 女の人が今の会社に転職した理由は何ですか。",
      options:["これまでの経験を生かせそうだったから","給料などよいじょうけんがそろっていたから","前のしょくばに不満があったから","新しい分野の仕事をしてみたかったから"], answer:3,
      translation:"Trên TV, nam phát thanh viên phỏng vấn một người nữ.<br>Nam: Hôm nay chúng tôi xin nghe câu chuyện của chị Uchida, nhân viên công ty đã từng chuyển việc.<br>Nữ: À vâng. Tôi đã chuyển việc 2 lần. Nói đến chuyển việc, có người tích lũy kinh nghiệm, tận dụng nó rồi chuyển đến nơi lương cao hơn, nhưng tôi cảm thấy đa phần là những người cảm thấy bất mãn hay thiếu thốn với hiện tại, đi tìm nơi thoải mái hơn. Lần chuyển việc đầu của tôi là vậy.<br>Nam: Vậy ạ.<br>Nữ: Hiện tại tôi được nhận vào công ty mà bạn tôi mới thành lập. Không phải vì có bất mãn gì với công ty cũ, mà đúng lúc tôi muốn nhìn thấy một thế giới mới. Lĩnh vực hoàn toàn khác, nhưng rất đáng làm.<br>Nam: Cũng có lý do như vậy nhỉ.",
      explanation:"Đáp án ④. Cô nói về công ty hiện tại: 「前に勤めてた会社に何か不満があったわけじゃなく、新たな世界を見てみたいと思っていた時だったので。分野は全然違うんですけど」⇒ muốn thử công việc ở lĩnh vực mới ⇒ ④. ③ sai rõ (không có bất mãn với nơi làm cũ). ① không nói tận dụng kinh nghiệm (nói lĩnh vực hoàn toàn khác, 全然違う). ② không nói điều kiện lương tốt — đó là kiểu chuyển việc của \"người khác\" mà cô chỉ nhắc đến."},
    { id:"c2-6", passage:"子供のサッカークラブのコーチがクラブの紹介をしています。<br>男：サッカーで勝つためには、ボールを正確に蹴る高い技術力や足の速さなどの高い身体能力はもちろん、精神力の強さも求められます。また、いつ、どのようにプレーするかを正しく選択する判断力も不可欠です。個人個人に高い技術力や身体能力、精神力があっても適切な判断ができないとチームの勝ちには繋がりません。ですから、このクラブでは特に、この力が身に付くよう選手を育てることに力を入れています。", audioUrl:"", question:"6番 コーチはこのサッカークラブでは特にどのような力を持った選手に育てたいと言っていますか。",
      options:["高いぎじゅつ力","高い身体能力","強いせいしん力","すぐれたはんだん力"], answer:3,
      translation:"Huấn luyện viên của câu lạc bộ bóng đá thiếu nhi đang giới thiệu về câu lạc bộ.<br>Nam: Để thắng trong bóng đá, tất nhiên cần kỹ thuật cao như đá bóng chính xác, thể lực cao như tốc độ chạy, và cả tinh thần mạnh mẽ. Ngoài ra, khả năng phán đoán để chọn đúng khi nào và chơi như thế nào cũng không thể thiếu. Dù mỗi cá nhân có kỹ thuật, thể lực, tinh thần cao, nếu không phán đoán đúng thì không dẫn đến chiến thắng của đội. Vì thế, ở câu lạc bộ này chúng tôi đặc biệt chú trọng đào tạo cầu thủ sao cho có được năng lực này.",
      explanation:"Đáp án ④. Câu trước 「この力」 là 「いつ、どのようにプレーするかを正しく選択する判断力も不可欠です」⇒ năng lực phán đoán ⇒ ④. ①②③ tuy cũng được nêu là cần thiết nhưng không phải thứ được nhấn \"đặc biệt\" ở câu kết luận (「このクラブでは特に」)."},
  ]
},
{ tab: "聴解", section: "問題3 概要理解",
  instruction: "問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。",
  questions: [
    { id:"c3-1", passage:"ラジオで歯医者が話しています。<br>女：歯は毎日の生活と関わっています。歯が健康でものが良く噛めれば、消化を助け、全身に栄養を届けることができます。また、歯があるおかげで発音ができ、会話ができます。この他、体の姿勢やバランスを保ったり、豊かな表情を作ったりなど食べること以外の面でも歯の存在は不可欠ですね。", audioUrl:"", question:"1番 歯医者は何について話していますか。",
      options:["歯の構造","歯の役割","歯の正しいケアの仕方","歯の病気の原因"], answer:1,
      translation:"Trên radio, một nha sĩ đang nói.<br>Nữ: Răng gắn với cuộc sống hằng ngày. Răng khỏe, nhai tốt thì giúp tiêu hóa và đưa dinh dưỡng đến toàn cơ thể. Ngoài ra, nhờ có răng mà ta phát âm được, nói chuyện được. Bên cạnh đó, răng còn không thể thiếu trong việc giữ tư thế, thăng bằng cơ thể hay tạo biểu cảm phong phú, tức cả những mặt ngoài việc ăn.",
      explanation:"Đáp án ②. Cả bài nói về những việc răng làm được cho cơ thể: «giúp tiêu hóa», «đưa dinh dưỡng», «phát âm», «giữ tư thế», «tạo biểu cảm» ⇒ vai trò của răng ⇒ ②. ① không nói cấu tạo; ③ không nói cách chăm sóc; ④ không nói nguyên nhân bệnh."},
    { id:"c3-2", passage:"講演会で鉄道の写真家が話しています。<br>男：私は鉄道の写真を撮るためにいろいろなところへ行きます。行く先々で鉄道ファンの方に会うと「どうやったらうまく撮れますか?」と聞かれるんですが、私は反対に「写真で何を伝えたいですか?」と尋ねるんです。シャッターを押すタイミングとか列車と風景をどんなバランスで撮るかとか、上手に撮影するテクニックはいろいろあります。けど、少しぐらい下手でも構わないんです。1枚の写真の中に季節感や感動的な風景など何を表現したいかを意識して撮ることで全く違った写真になると思うんです。", audioUrl:"", question:"2番 鉄道の写真家が伝えたいことは何ですか。",
      options:["鉄道の写真を撮る時に大切なこと","鉄道の写真を撮るのに良い場所","鉄道の美しさを表現する楽しさ","鉄道の写真を上手に撮るテクニック"], answer:0,
      translation:"Trong buổi diễn thuyết, một nhiếp ảnh gia đường sắt đang nói.<br>Nam: Tôi đi nhiều nơi để chụp ảnh đường sắt. Đến đâu gặp người hâm mộ đường sắt hỏi \"làm sao chụp đẹp được?\", tôi lại hỏi ngược lại \"anh muốn truyền đạt gì qua bức ảnh?\". Có nhiều kỹ thuật chụp đẹp như thời điểm bấm máy, cân đối giữa tàu và phong cảnh. Nhưng hơi kém một chút cũng không sao. Tôi nghĩ chỉ cần chụp với ý thức rõ muốn thể hiện gì trong một bức ảnh — cảm giác mùa, phong cảnh gây xúc động — thì bức ảnh sẽ hoàn toàn khác.",
      explanation:"Đáp án ①. Nội dung: nhấn mạnh điều quan trọng là ý thức \"muốn thể hiện gì\" chứ không phải kỹ thuật (「少しぐらい下手でも構わない」) ⇒ điều quan trọng khi chụp ảnh đường sắt ⇒ ①. ④ chính là thứ được nói là \"không quan trọng lắm\"; ② không nói địa điểm; ③ không nói \"niềm vui thể hiện vẻ đẹp\"."},
    { id:"c3-3", passage:"テレビで工業デザイナーが話しています。<br>女：中学1年の時、視力が悪くなり、メガネが必要になりました。メガネ屋さんに行ったのですが、気に入るメガネが見つかりませんでした。仕方なく1つ買ったんですが、自分の気に入らないメガネをかけるのは耐えられませんでした。同じ頃、友達の家で出されたジュースのコップがすごくきれいな形で感激しました。有名なデザイナーがデザインしたコップだったのですが、ちょっと形を変えるだけでこんなにおしゃれになるんだと驚きました。今思えば、デザインということに初めて興味を持ったのがこの頃でした。", audioUrl:"", question:"3番 工業デザイナーは何について話していますか。",
      options:["メガネを買う人へのアドバイス","人気があるメガネのデザイン","おしゃれなデザインのポイント","デザインを意識し始めたきっかけ"], answer:3,
      translation:"Trên TV, một nhà thiết kế công nghiệp đang nói.<br>Nữ: Năm lớp 7, thị lực tôi kém đi và cần đeo kính. Tôi đến tiệm kính nhưng không tìm được cái nào ưng ý. Đành mua một cái, nhưng đeo kính mình không thích thì không chịu nổi. Cùng thời gian đó, cái cốc nước trái cây được dọn ra ở nhà bạn có hình dáng rất đẹp khiến tôi cảm động. Đó là cái cốc do một nhà thiết kế nổi tiếng thiết kế, và tôi kinh ngạc vì chỉ cần đổi hình dáng một chút mà lại sành điệu đến vậy. Nghĩ lại thì đây là lúc tôi lần đầu quan tâm đến \"thiết kế\".",
      explanation:"Đáp án ④. Câu chốt: 「今思えば、デザインということに初めて興味を持ったのがこの頃でした」⇒ cơ duyên bắt đầu ý thức về thiết kế ⇒ ④. ① không phải lời khuyên cho người mua kính; ② không nói thiết kế kính được ưa chuộng; ③ không nói \"điểm cốt lõi của thiết kế sành điệu\"."},
    { id:"c3-4", passage:"ラジオでタレントが話しています。<br>男：タレントの仕事を始めて30年が経ちました。ありがたいことにいろんな仕事をいただき、充実した日々を送っています。ただ、仕事が多すぎて、時間管理の必要性を感じます。限られた時間の中でやりたい仕事を全部はできないのだから何をするかの優先順位をつけて、できることを確実に進め、できないことは諦めるということを意識して生活しています。", audioUrl:"", question:"4番 タレントは何について話していますか。",
      options:["時間を上手に使う工夫","仕事の楽しみ方","自分の仕事の内容","自分の計画性のなさ"], answer:0,
      translation:"Trên radio, một nghệ sĩ đang nói.<br>Nam: Đã 30 năm kể từ khi tôi bắt đầu làm nghệ sĩ. May mắn là tôi nhận được nhiều công việc, ngày tháng rất trọn vẹn. Chỉ là công việc quá nhiều nên tôi thấy cần phải quản lý thời gian. Vì trong thời gian có hạn không thể làm hết mọi việc muốn làm, nên tôi sống với ý thức: sắp xếp thứ tự ưu tiên cho việc gì, chắc chắn làm xong việc có thể làm, và từ bỏ việc không thể làm.",
      explanation:"Đáp án ①. Nội dung: 「時間管理の必要性を感じます…優先順位をつけて、できることを確実に進め、できないことは諦める」⇒ cách sử dụng thời gian khéo léo ⇒ ①. ② không nói cách tận hưởng công việc; ③ không kể nội dung công việc; ④ bài không nói \"mình thiếu kế hoạch\" (ngược lại, đang chủ động ưu tiên hóa)."},
    { id:"c3-5", passage:"ラジオで俳優が話しています。<br>男：みなさんは旅が好きですか。旅といえば、遠いところに行くことだと思う人もいるかもしれませんが、僕は例えば、電車で一駅手前で降りて、いつもと違う道を歩いて帰るのも旅だと思うんです。距離ではなく、移動そのものが重要なんです。目的地に到達するまでのいつもと違った過程を楽しむ。そういうのも旅だと言えるのではないでしょうか。", audioUrl:"", question:"5番 俳優は何について話していますか。",
      options:["旅の思い出","1人で行く旅の計画","旅をすることの重要性","自分が考える旅というもの"], answer:3,
      translation:"Trên radio, một diễn viên đang nói.<br>Nam: Các bạn có thích du lịch không? Nói đến du lịch, có người nghĩ là đi đến nơi xa, nhưng tôi nghĩ ví dụ như xuống tàu sớm một ga rồi đi bộ về theo con đường khác với mọi ngày cũng là du lịch. Không phải khoảng cách, mà chính việc di chuyển là quan trọng. Tận hưởng quá trình khác với mọi ngày cho đến khi đến điểm đích. Tôi nghĩ như vậy cũng có thể gọi là du lịch.",
      explanation:"Đáp án ④. Bài nói chỉ ra quan niệm của bản thân về du lịch: 「僕は…も旅だと思うんです」「そういうのも旅だと言えるのではないでしょうか」⇒ cách nghĩ của bản thân về du lịch ⇒ ④. ① không có kỷ niệm cụ thể; ② không nói kế hoạch đi một mình; ③ không nói \"tầm quan trọng của việc đi du lịch\" nói chung (mà là \"cái gì được coi là du lịch\")."},
  ]
},
{ tab: "聴解", section: "問題4 即時応答",
  instruction: "問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。",
  questions: [
    { id:"c4-1", passage:"今日中に漢字20個覚えるなんて、無理に決まってるよ。", audioUrl:"", question:"1番",
      options:["頑張ればできるんじゃない?","楽にできるって思ってるんだね。","簡単に覚えられてすごいね。"], answer:0,
      translation:"\"Trong hôm nay mà học thuộc 20 chữ kanji thì chắc chắn là không thể rồi.\"<br>① Nếu cố gắng thì cũng làm được mà? / ② Cậu nghĩ là làm được một cách dễ dàng nhỉ. / ③ Học được dễ dàng thật là giỏi.",
      explanation:"Đáp án ①. Câu nói là sự khẳng định \"không thể\"; phản hồi tự nhiên là động viên, nêu khả năng có thể ⇒ 「頑張ればできるんじゃない?」. ② sai vì người nói đang nói \"không thể\", không phải \"dễ\". ③ nói \"nhớ dễ thật giỏi\" — trái với nội dung câu nói."},
    { id:"c4-2", passage:"課長、明日の会議の資料ですが、ご覧いただけないでしょうか?", audioUrl:"", question:"2番",
      options:["資料、見てくれるんですね。","資料は私が作っておきますね。","資料、見ておきます。"], answer:2,
      translation:"\"Trưởng phòng, về tài liệu cuộc họp ngày mai ạ, ngài xem qua giúp em được không ạ?\"<br>① Vậy là anh xem tài liệu giúp nhỉ. / ② Tài liệu thì tôi sẽ làm sẵn nhé. / ③ Tài liệu, tôi sẽ xem trước.",
      explanation:"Đáp án ③. Đây là lời nhờ cấp trên xem tài liệu (ご覧いただけないでしょうか) ⇒ trả lời phù hợp là nhận lời xem ⇒ 「資料、見ておきます」. ① sai vì chuyển thành người kia xem (hướng ngược). ② nói \"tôi làm tài liệu\" — không phải nội dung được nhờ (là xem tài liệu đã có)."},
    { id:"c4-3", passage:"この会社、経験者に限らず応募できるって。", audioUrl:"", question:"3番",
      options:["募集は経験が無い人だけなんだ。","経験がなくてもいいんだね。","やっぱり経験が無いといけないのか。"], answer:1,
      translation:"\"Nghe nói công ty này có thể ứng tuyển không chỉ giới hạn ở người có kinh nghiệm.\"<br>① Hóa ra tuyển chỉ dành cho người không có kinh nghiệm. / ② Vậy là không có kinh nghiệm cũng được nhỉ. / ③ Đúng là không có kinh nghiệm thì không được nhỉ.",
      explanation:"Đáp án ②. 「経験者に限らず」＝ không chỉ người có kinh nghiệm, tức người chưa có kinh nghiệm cũng được ⇒ 「経験がなくてもいいんだね」. ① sai (nói ngược lại: chỉ người không có kinh nghiệm). ③ sai (nói là phải có kinh nghiệm)."},
    { id:"c4-4", passage:"僕が出張の間、庭の花の水やり、毎日欠かさないでね。", audioUrl:"", question:"4番",
      options:["じゃ、やらないでおくね。","忘れないようにするね。","水、毎日やっちゃだめなんだね。"], answer:1,
      translation:"\"Trong lúc tôi đi công tác, việc tưới nước cho hoa ngoài vườn, đừng bỏ ngày nào nhé.\"<br>① Vậy thì tớ sẽ không làm nhé. / ② Tớ sẽ cố để không quên nhé. / ③ Hóa ra là không được tưới nước mỗi ngày nhỉ.",
      explanation:"Đáp án ②. 「毎日欠かさないで」＝ mỗi ngày đều phải làm, không được bỏ ⇒ nhận lời 「忘れないようにするね」. ① sai (nói sẽ không làm). ③ sai (hiểu ngược thành \"không được tưới mỗi ngày\")."},
    { id:"c4-5", passage:"履歴書の提出、もう少しで締め切りに遅れるところだったよ。", audioUrl:"", question:"5番",
      options:["間に合ってよかったね。","遅れちゃったんだ。","あと少しだったのにね。"], answer:0,
      translation:"\"Việc nộp sơ yếu lý lịch, suýt chút nữa là trễ hạn rồi đấy.\"<br>① May mà kịp nhỉ. / ② Hóa ra là bị trễ rồi à. / ③ Chỉ còn một chút nữa thôi nhỉ.",
      explanation:"Đáp án ①. 「もう少しで…ところだった」＝ suýt nữa thì (nhưng thực tế đã kịp) ⇒ phản hồi phù hợp là mừng vì đã kịp 「間に合ってよかったね」. ② sai (thực tế không trễ). ③ hiểu sai thành \"đã trễ, chỉ thiếu chút nữa\"."},
    { id:"c4-6", passage:"前田さん、お客さまへの商品説明はこのパンフレットに沿って話してください。", audioUrl:"", question:"6番",
      options:["自由に話していいんですね。","ここに書いてあるように話すんですね。","パンフレットに関係なく話すんですね。"], answer:1,
      translation:"\"Chị Maeda, phần giải thích sản phẩm cho khách hãy nói theo cuốn pamphlet này nhé.\"<br>① Vậy là được nói tự do nhỉ. / ② Vậy là nói theo như những gì ghi ở đây nhỉ. / ③ Vậy là nói không liên quan đến pamphlet nhỉ.",
      explanation:"Đáp án ②. 「〜に沿って」＝ theo, dựa theo ⇒ nói theo nội dung ghi trong pamphlet ⇒ ②. ①③ đều hiểu ngược (tự do / không liên quan)."},
    { id:"c4-7", passage:"今日の午後、商品発表会で話すんだけど緊張のあまり食欲もないよ。", audioUrl:"", question:"7番",
      options:["随分落ち着いてるんだね。","そんなに緊張しなくても大丈夫だよ。","少しは緊張感持たないとだめだよ。"], answer:1,
      translation:"\"Chiều nay tôi phải nói ở buổi ra mắt sản phẩm, mà căng thẳng quá nên chẳng có cảm giác thèm ăn gì cả.\"<br>① Cậu bình tĩnh ghê nhỉ. / ② Không cần căng thẳng đến thế đâu. / ③ Phải có chút căng thẳng mới được chứ.",
      explanation:"Đáp án ②. Người nói than rằng rất căng thẳng ⇒ phản hồi phù hợp là trấn an 「そんなに緊張しなくても大丈夫だよ」. ① sai (đang căng thẳng, không \"bình tĩnh\"). ③ trách ngược lại, không phù hợp ngữ cảnh than thở."},
    { id:"c4-8", passage:"今日の会議でのプレゼン、先輩が休みだから私がやらざるを得なくなって…。", audioUrl:"", question:"8番",
      options:["プレゼン、やらなくてよくなったの?","プレゼンできてうれしいんだね。","そういうことなら、仕方ないね。"], answer:2,
      translation:"\"Phần thuyết trình ở cuộc họp hôm nay, vì đàn anh nghỉ nên tôi buộc phải làm…\"<br>① Vậy là không phải làm thuyết trình nữa à? / ② Được thuyết trình nên vui nhỉ. / ③ Nếu vậy thì cũng đành chịu nhỉ.",
      explanation:"Đáp án ③. 「やらざるを得ない」＝ buộc phải làm (hàm ý bất đắc dĩ) ⇒ phản hồi thông cảm 「そういうことなら、仕方ないね」. ① sai (vẫn phải làm). ② sai (người nói không vui mà là bị buộc)."},
    { id:"c4-9", passage:"今日のお昼の定食、食べ応えあったね。", audioUrl:"", question:"9番",
      options:["本当、お腹いっぱいになったね。","そうそう、あれじゃ足りない人多いよね。","確かに、量が少なめでちょうどよかったね。"], answer:0,
      translation:"\"Suất cơm trưa hôm nay, ăn đã thật đấy nhỉ.\"<br>① Đúng vậy, no căng bụng luôn nhỉ. / ② Phải đấy, nhiều người thấy thế là không đủ nhỉ. / ③ Đúng là, lượng hơi ít mà vừa đủ nhỉ.",
      explanation:"Đáp án ①. 「食べ応えがあった」＝ ăn đủ đầy, thấy no ⇒ phản hồi cùng ý 「お腹いっぱいになったね」. ②③ đều nói \"không đủ/ít\" — trái nghĩa với 食べ応え."},
    { id:"c4-10", passage:"店長。山田さん、配達の仕事、頼まれたらやらないこともないって言ってました。", audioUrl:"", question:"10番",
      options:["他の人を探さないとだめだね。","山田さんに断られたか。","じゃ、お願いしてみようかな。"], answer:2,
      translation:"\"Quản lý. Anh Yamada nói rằng nếu được nhờ việc giao hàng thì cũng không phải là không làm.\"<br>① Phải tìm người khác nhỉ. / ② Hóa ra bị anh Yamada từ chối à. / ③ Vậy thì thử nhờ xem sao nhỉ.",
      explanation:"Đáp án ③. 「やらないこともない」＝ không phải là không làm (ý là có thể nhận nếu được nhờ) ⇒ phản hồi phù hợp là quyết định thử nhờ ⇒ ③. ① sai (không cần tìm người khác). ② sai (không bị từ chối)."},
    { id:"c4-11", passage:"来年からの入学先、迷った挙句、初めに思ってたとこにしたよ。", audioUrl:"", question:"11番",
      options:["いろいろ悩んだんだね。","すぐに決められたんだね。","少しは迷ったんだね。"], answer:0,
      translation:"\"Trường sẽ vào học từ năm sau, sau khi phân vân đủ đường thì tôi đã chọn nơi mình nghĩ đến đầu tiên.\"<br>① Hóa ra đã băn khoăn đủ thứ nhỉ. / ② Hóa ra đã quyết được ngay nhỉ. / ③ Hóa ra đã phân vân một chút nhỉ.",
      explanation:"Đáp án ①. 「迷った挙句」＝ sau khi phân vân rất nhiều ⇒ 「いろいろ悩んだんだね」. ② sai (không phải quyết ngay). ③ sai vì 挙句 nhấn mạnh \"phân vân rất nhiều\", không phải \"một chút\"."},
  ]
},
{ tab: "聴解", section: "問題5 統合理解",
  instruction: "長めの話を聞きます。この問題には練習はありません。問題用紙にメモをとってもかまいません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。",
  questions: [
    { id:"c5-1", passage:"地域のボランティアグループのリーダーとメンバー2人が話しています。<br>男1：僕たちが市と協力して定期的にゴミ拾いをしている東公園、ゴミを置いていっちゃう人が多いよね。何か対策を考えて市役所に提案しようと思うんだ。<br>女：お菓子の袋とかペットボトルとか、置いていっちゃう人がいるんですよね。<br>男1：市の方針でゴミ箱は置かないことになってるからね。<br>男2：特にゴミが多いところから対策を考えた方がいいんじゃないですか?ゴミが目立つところに花壇を作るとか。他の公園で花壇を作ったら、その周りはゴミが減ったそうですよ。<br>男1：ゴミが多いのはベンチの周りだよね?あそこに花壇を作るのは難しいんじゃないかな。<br>男2：じゃ、代わりにベンチをもっと明るい色にして花の絵も描いたらどうですか?きれいでちゃんと手入れされている印象があるとゴミを置いていきにくいと思います。<br>男1：なるほど。<br>女：私は公園全体を考えた方がいいと思うんですが⋯。「ゴミを持ち帰りましょう」って書いた看板を増やすのはどうですか?<br>男1：うーん、既にいくつか立ててあるから今以上に増やす必要ないんじゃないかな?<br>女：あと私たちボランティアが見回って、ゴミを持って帰ってもらうように直接声をかけるのも効果があると思いますけど。<br>男1：ボランティアの負担が大きくなるのはちょっとね。うーん、まず、ゴミが多いところからなんとかしよう。花壇を作る代わりにっていうアイディアが良さそうだね。市役所の担当者に早速提案してみよう。", audioUrl:"", question:"1番 公園のゴミを減らすため、何を市役所に提案することにしましたか。",
      options:["ベンチの近くに花壇を作ること","ベンチを塗り直してきれいにすること","看板を立てること","公園を見回ること"], answer:1,
      translation:"Trưởng nhóm tình nguyện khu vực và 2 thành viên đang nói chuyện.<br>Nam1: Công viên Higashi mà chúng ta phối hợp với thành phố nhặt rác định kỳ ấy, nhiều người bỏ rác lại quá nhỉ. Tôi định nghĩ cách đối sách rồi đề xuất với tòa thị chính.<br>Nữ: Cũng có người bỏ lại túi bánh kẹo, chai nhựa… nhỉ.<br>Nam1: Vì chủ trương của thành phố là không đặt thùng rác mà.<br>Nam2: Hay là nên nghĩ đối sách từ nơi nhiều rác nhất? Ví dụ làm vườn hoa ở nơi rác nổi bật. Nghe nói ở công viên khác làm vườn hoa thì quanh đó rác giảm hẳn.<br>Nam1: Nơi nhiều rác là quanh ghế băng nhỉ? Làm vườn hoa chỗ đó chắc khó.<br>Nam2: Vậy thì thay vào đó, sơn ghế băng sang màu sáng hơn rồi vẽ cả hình hoa thì sao ạ? Tôi nghĩ nếu có ấn tượng đẹp, được chăm sóc cẩn thận thì người ta khó bỏ rác lại.<br>Nam1: Ra vậy.<br>Nữ: Tôi thì nghĩ nên xét cả công viên. Thêm biển ghi \"Hãy mang rác về\" thì sao?<br>Nam1: Ừm, đã dựng vài cái rồi nên chắc không cần tăng thêm nữa nhỉ?<br>Nữ: Ngoài ra, tình nguyện viên chúng ta đi tuần, trực tiếp nhắc để người ta mang rác về cũng có hiệu quả, tôi nghĩ vậy.<br>Nam1: Việc gánh nặng cho tình nguyện viên tăng lên thì hơi… Ừm, trước tiên cứ giải quyết từ nơi nhiều rác đi. Ý tưởng \"thay cho việc làm vườn hoa\" có vẻ hay. Thử đề xuất ngay với người phụ trách tòa thị chính vậy.",
      explanation:"Đáp án ②. Câu chốt của trưởng nhóm: 「まず、ゴミが多いところからなんとかしよう。花壇を作る代わりにっていうアイディアが良さそうだね」— \"thay cho việc làm vườn hoa\" chính là ý của Nam2: 「ベンチをもっと明るい色にして花の絵も描いたら」⇒ sơn lại/tô màu ghế băng cho sạch đẹp ⇒ ②. ① bị loại: 「あそこに花壇を作るのは難しい」. ③ bị loại: 「今以上に増やす必要ない」. ④ bị loại: 「ボランティアの負担が大きくなるのはちょっとね」."},
    { id:"c5-2", passage:"港で行われているイベントでアナウンスを聞いた後、女の人と男の人が話しています。<br>女1：本日は桜港祭りにお越しいただき、ありがとうございます。会場は4つに分かれています。各会場についてご案内いたします。中央会場では、今朝捕れた魚や貝をその場で焼いてお召し上がりいただけます。こちらは、なくなり次第終了いたします。南会場では、初心者向けの釣り教室を開催しています。道具の貸し出しはもちろん、餌の付け方などもお教えいたします。東会場では、海の生き物が観察できます。地元の海の生き物を間近で見ることができ、お子様も大人の方もお楽しみいただけます。西会場では、新鮮な魚介類を販売しております。是非、お買い求めください。<br>女2：新鮮な魚、おいしそう。なくなる前に早く行かない?<br>男：え?早速買い物?先に買っちゃうと持って歩くの大変じゃない?<br>女2：あ、そっちじゃなくて自分たちで焼いて食べられるって方。買い物は最後にしようよ。<br>男：あぁ、じゃ、まずはそこに行こう。それから近くで生き物を観察できるっていうのに行かない?<br>女2：いいよ。釣りはいいの?好きでしょ?今日もやりたいんじゃない?<br>男：うーん、初心者向けって言ってたから今日はしなくていいかな。", audioUrl:"", question:"2番 質問1 2人は最初にどの会場に行きますか。",
      options:["中央会場","南会場","東会場","西会場"], answer:0,
      translation:"Sau khi nghe thông báo ở sự kiện diễn ra tại cảng, một người nữ và một người nam nói chuyện.<br>Nữ1: Hôm nay quý khách đã đến với Lễ hội cảng Sakura, xin chân thành cảm ơn. Hội trường chia thành 4 khu. Chúng tôi xin giới thiệu từng khu. Ở khu giữa (中央), quý khách có thể nướng ngay tại chỗ cá và sò hến đánh bắt sáng nay để thưởng thức. Khu này kết thúc khi hết hàng. Ở khu nam (南), đang diễn ra lớp học câu cá cho người mới. Không chỉ cho mượn dụng cụ mà còn hướng dẫn cách mắc mồi. Ở khu đông (東), có thể quan sát sinh vật biển. Có thể nhìn cận cảnh sinh vật biển địa phương, cả trẻ em và người lớn đều vui. Ở khu tây (西), bán hải sản tươi. Xin mời quý khách mua.<br>Nữ2: Cá tươi trông ngon quá. Đi sớm trước khi hết không?<br>Nam: Ớ? Mua đồ ngay à? Mua trước rồi cầm đi lại khổ lắm?<br>Nữ2: À, không phải chỗ đó, mà là chỗ tự mình nướng ăn ấy. Mua sắm để cuối cùng đi.<br>Nam: À, vậy thì đi chỗ đó trước. Sau đó đi chỗ gần gần quan sát được sinh vật nhé?<br>Nữ2: Được thôi. Câu cá thì sao? Cậu thích mà? Hôm nay cũng muốn làm chứ?<br>Nam: Ừm, người ta nói là cho người mới nên hôm nay không làm cũng được.",
      explanation:"Đáp án ①. Kết luận: 「買い物は最後にしようよ」「じゃ、まずはそこに行こう」— \"chỗ đó\" là nơi tự nướng cá ăn = 「自分たちで焼いて食べられる」= 中央会場 (khu giữa) ⇒ ①. (Mua sắm = 西会場 để cuối cùng; câu cá = 南会場 không làm; quan sát sinh vật = 東会場 là điểm thứ hai.)"},
    { id:"c5-3", passage:"港で行われているイベントでアナウンスを聞いた後、女の人と男の人が話しています。<br>女1：本日は桜港祭りにお越しいただき、ありがとうございます。会場は4つに分かれています。各会場についてご案内いたします。中央会場では、今朝捕れた魚や貝をその場で焼いてお召し上がりいただけます。こちらは、なくなり次第終了いたします。南会場では、初心者向けの釣り教室を開催しています。道具の貸し出しはもちろん、餌の付け方などもお教えいたします。東会場では、海の生き物が観察できます。地元の海の生き物を間近で見ることができ、お子様も大人の方もお楽しみいただけます。西会場では、新鮮な魚介類を販売しております。是非、お買い求めください。<br>女2：新鮮な魚、おいしそう。なくなる前に早く行かない?<br>男：え?早速買い物?先に買っちゃうと持って歩くの大変じゃない?<br>女2：あ、そっちじゃなくて自分たちで焼いて食べられるって方。買い物は最後にしようよ。<br>男：あぁ、じゃ、まずはそこに行こう。それから近くで生き物を観察できるっていうのに行かない?<br>女2：いいよ。釣りはいいの?好きでしょ?今日もやりたいんじゃない?<br>男：うーん、初心者向けって言ってたから今日はしなくていいかな。", audioUrl:"", question:"2番 質問2 2人は2番目にどの会場に行きますか。",
      options:["中央会場","南会場","東会場","西会場"], answer:2,
      translation:"(Cùng một đoạn hội thoại như câu c5-2.)<br>Sau khi nghe thông báo ở Lễ hội cảng Sakura, hai người quyết định: trước tiên đi khu giữa (tự nướng cá ăn), sau đó: «それから近くで生き物を観察できるっていうのに行かない?」「いいよ」.",
      explanation:"Đáp án ③. 「それから近くで生き物を観察できるっていうのに行かない?」— quan sát sinh vật biển = 東会場 ⇒ ③. ② câu cá (南会場): 「今日はしなくていいかな」⇒ không đi. ④ mua sắm (西会場) để cuối cùng. ① đã đi đầu tiên."},
  ]
},

]
});
