/* =========================================================================
   data_2019_7.js — JLPT N2 2019年7月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   Nguồn: pdf_data/2019_7.pdf — bản scan 30 trang (16 trang đề + trang
   bảng 正解表 (第17页) cùng các trang 解説 tiếng Trung và 台本 phần 聴解).
   Toàn bộ đáp án dưới đây đã được đối chiếu với bảng 正解表 của chính file đề.
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2019_07", label:"07/2019", title:"JLPT N2 — 2019年7月 (07/2019)", file:"data_2019_7.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{ tab:"文字・語彙", section:"問題1 漢字読み",
  instruction:"＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a1-1", passage:"", audioUrl:"", question:"1. 誰も<u>憎んで</u>なんていませんから、心配しないでください。", options:["なやんで","くやんで","うらんで","にくんで"], answer:3,
    translation:"Không ai oán ghét gì bạn đâu, đừng lo lắng.",
    explanation:"憎む = にくむ ⇒ 憎んで = にくんで: oán ghét, căm ghét. なやんで (悩んで: buồn phiền)・くやんで (悔やんで: hối hận)・うらんで (恨んで: oán hận) sai âm đọc." },
  { id:"a1-2", passage:"", audioUrl:"", question:"2. <u>偶然</u>、駅で友達に会った。", options:["とつぜん","ぐうぜん","ぐぜん","とぜん"], answer:1,
    translation:"Tình cờ tôi gặp bạn ở nhà ga.",
    explanation:"偶然 = ぐうぜん: tình cờ, ngẫu nhiên. とつぜん (突然: đột ngột)・ぐぜん・とぜん (徒然: buồn chán) sai âm đọc." },
  { id:"a1-3", passage:"", audioUrl:"", question:"3. 大学のゼミではいろいろな<u>刺激</u>を受けた。", options:["さてき","さげき","しげき","してき"], answer:2,
    translation:"Ở buổi seminar đại học tôi đã nhận được nhiều kích thích (cảm hứng).",
    explanation:"刺激 = しげき: kích thích, kích động. さてき・さげき là âm đọc sai; してき (指摘: chỉ ra) sai nghĩa." },
  { id:"a1-4", passage:"", audioUrl:"", question:"4. 失敗して<u>恥</u>をかいたが、先輩の優しい一言に慰められた。", options:["はし","はじ","はず","はす"], answer:1,
    translation:"Tôi thất bại và bị xấu hổ, nhưng đã được một lời dịu dàng của tiền bối an ủi.",
    explanation:"恥 = はじ: sự xấu hổ, nỗi nhục. 「恥をかく」= bị xấu hổ. はし (端/橋/箸)・はず (筈: lẽ ra)・はす (蓮: hoa sen) sai âm đọc." },
  { id:"a1-5", passage:"", audioUrl:"", question:"5. 彼の強さは<u>圧倒的</u>だ。", options:["あっとうてき","おっとうてき","あつどうてき","おつどうてき"], answer:0,
    translation:"Sức mạnh của anh ấy là áp đảo.",
    explanation:"圧倒的 = あっとうてき: mang tính áp đảo, tuyệt đối. Các phương án còn lại đều là âm đọc sai." },
]},
{ tab:"文字・語彙", section:"問題2 表記",
  instruction:"＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a2-1", passage:"", audioUrl:"", question:"6. 私の<u>しゅみ</u>はピアノをひくことだ。", options:["趣味","興味","好味","習味"], answer:0,
    translation:"Sở thích của tôi là chơi piano.",
    explanation:"しゅみ = 趣味: sở thích, thú vui. 興味 (きょうみ: hứng thú) đọc khác; 好味・習味 là tổ hợp chữ không tồn tại." },
  { id:"a2-2", passage:"", audioUrl:"", question:"7. もう少し<u>こい</u>鉛筆がほしい。", options:["軟い","薄い","硬い","濃い"], answer:3,
    translation:"Tôi muốn một cây bút chì đậm (màu) hơn một chút.",
    explanation:"こい = 濃い: (màu) đậm, nồng. 軟い (やわらかい: mềm)・薄い (うすい: nhạt/mỏng)・硬い (かたい: cứng) sai nghĩa." },
  { id:"a2-3", passage:"", audioUrl:"", question:"8. この皿は、真っ白ではなく、少し青が<u>まじった</u>ような色をしている。", options:["組じった","含じった","混じった","加じった"], answer:2,
    translation:"Cái đĩa này không phải trắng tinh mà có màu như pha lẫn một chút xanh.",
    explanation:"まじる = 混じる: lẫn, trộn, xen vào. 組む (くむ: kết hợp)・含める (ふくめる: bao gồm)・加える (くわえる: thêm) đọc khác, sai." },
  { id:"a2-4", passage:"", audioUrl:"", question:"9. 彼はいつも<u>そん</u>になることばかりしている。", options:["罪","害","損","毒"], answer:2,
    translation:"Anh ấy lúc nào cũng chỉ làm những việc bị thiệt.",
    explanation:"そん = 損: thiệt, lỗ. 罪 (つみ: tội)・害 (がい: hại)・毒 (どく: độc) sai nghĩa." },
  { id:"a2-5", passage:"", audioUrl:"", question:"10. 素晴らしい<u>えんぎ</u>に感動した。", options:["演劇","演技","園技","園劇"], answer:1,
    translation:"Tôi đã cảm động trước diễn xuất tuyệt vời.",
    explanation:"えんぎ = 演技: diễn xuất, kỹ năng biểu diễn. 演劇 (えんげき: kịch, sân khấu) sai âm; 園技・園劇 là tổ hợp chữ sai." },
]},
{ tab:"文字・語彙", section:"問題3 語形成",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a3-1", passage:"", audioUrl:"", question:"11. ゲームのしすぎは目に（　）影響を与える。", options:["悪","重","高","大"], answer:0,
    translation:"Chơi game quá nhiều gây ảnh hưởng xấu đến mắt.",
    explanation:"悪影響 (あくえいきょう) = ảnh hưởng xấu. 重 (五重の塔: năm tầng)・高 (高収入: thu nhập cao)・大 (大規模: quy mô lớn) không tạo được từ đúng nghĩa ở đây." },
  { id:"a3-2", passage:"", audioUrl:"", question:"12. 彼はアメリカ（　）のビジネスで成功した。", options:["形","質","性","流"], answer:3,
    translation:"Anh ấy thành công trong việc kinh doanh theo kiểu Mỹ.",
    explanation:"アメリカ流 = kiểu Mỹ, phong cách Mỹ. 形 (三角形: hình tam giác)・質 (品質: chất lượng)・性 (可能性: khả năng) không ghép đúng nghĩa." },
  { id:"a3-3", passage:"", audioUrl:"", question:"13. 別れ（　）に、彼女は私に何か言ったが、聞こえなかった。", options:["刻","際","間","期"], answer:1,
    translation:"Lúc chia tay, cô ấy nói gì đó với tôi nhưng tôi không nghe được.",
    explanation:"別れ際 (わかれぎわ) = lúc chia tay, ngay khi chia tay. 刻 (彫刻: điêu khắc)・間 (時間: thời gian)・期 (時期: thời kỳ) sai nghĩa." },
]},
{ tab:"文字・語彙", section:"問題4 文脈規定",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a4-1", passage:"", audioUrl:"", question:"14. 予算もスタッフも希望通りにしたんだから、成果を期待しているよと、上司に（　）をかけられた。", options:["ショック","プレッシャー","ダメージ","コンプレックス"], answer:1,
    translation:"Vị sếp gây áp lực: “Ngân sách và nhân sự đều theo như cậu mong muốn rồi, tôi đang trông đợi thành quả đấy”.",
    explanation:"プレッシャーをかける = gây áp lực. ショック (sốc)・ダメージ (tổn thương)・コンプレックス (mặc cảm) không đi với 「～をかける」 theo nghĩa này." },
  { id:"a4-2", passage:"", audioUrl:"", question:"15. アルバイトの仕事は勤務が多い月と少ない月があって、毎月の収入が（　）だ。", options:["不安定","不自由","不都合","不公平"], answer:0,
    translation:"Việc làm thêm có tháng nhiều ca tháng ít ca nên thu nhập hằng tháng không ổn định.",
    explanation:"不安定 = không ổn định. 不自由 (không tự do/bất tiện)・不都合 (không thỏa đáng/bất tiện)・不公平 (bất công) sai nghĩa." },
  { id:"a4-3", passage:"", audioUrl:"", question:"16. 彼は（　）返事をしていたから、パーティーに来るかどうかわからない。", options:["地味な","かすかな","あいまいな","鈍感な"], answer:2,
    translation:"Anh ấy trả lời mập mờ nên không biết có đến bữa tiệc hay không.",
    explanation:"あいまいな = mơ hồ, mập mờ. 地味な (giản dị)・かすかな (mờ nhạt, yếu ớt)・鈍感な (kém nhạy cảm) sai nghĩa." },
  { id:"a4-4", passage:"", audioUrl:"", question:"17. 新しいことがなかなか覚えられないのは記憶力が（　）からだろうか。", options:["傷んだ","散った","かれた","おとろえた"], answer:3,
    translation:"Không nhớ nổi những điều mới, có lẽ là do trí nhớ đã suy giảm chăng.",
    explanation:"おとろえる = 衰える: suy yếu, suy giảm (記憶力が衰える). 傷んだ (bị hư)・散った (rụng/tản)・かれた (khô/tàn) sai nghĩa." },
  { id:"a4-5", passage:"", audioUrl:"", question:"18. 相手が弱いと思って（　）したら、負けてしまった。", options:["納得","油断","失望","覚悟"], answer:1,
    translation:"Tưởng đối phương yếu nên chủ quan, kết quả là thua.",
    explanation:"油断する = chủ quan, lơ là mất cảnh giác. 納得 (thấu hiểu, đồng tình)・失望 (thất vọng)・覚悟 (giác ngộ, quyết tâm) sai nghĩa." },
  { id:"a4-6", passage:"", audioUrl:"", question:"19. 二人とも働いているので、家事や育児は夫婦で（　）している。", options:["分別","区別","区分","分担"], answer:3,
    translation:"Vì cả hai đều đi làm nên việc nhà và chăm con được hai vợ chồng chia nhau gánh vác.",
    explanation:"分担する = phân chia, chia nhau làm. 分別 (phân biệt/phân loại)・区別 (phân biệt)・区分 (phân loại) sai nghĩa." },
  { id:"a4-7", passage:"", audioUrl:"", question:"20. 次の社長に最も（　）人は、経験豊富な鈴木さんでしょう。", options:["ふさわしい","等しい","ありがちな","当たり前な"], answer:0,
    translation:"Người phù hợp nhất để làm giám đốc kế nhiệm có lẽ là anh Suzuki giàu kinh nghiệm.",
    explanation:"ふさわしい = phù hợp, thích hợp, xứng đáng. 等しい (bằng nhau)・ありがちな (thường hay có)・当たり前な (đương nhiên) sai nghĩa." },
]},
{ tab:"文字・語彙", section:"問題5 言い換え類義",
  instruction:"＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a5-1", passage:"", audioUrl:"", question:"21. この辺りも<u>物騒</u>になってきた気がする。", options:["きれいじゃなくなってきた","うるさくなってきた","安全じゃなくなってきた","さびしくなってきた"], answer:2,
    translation:"Tôi có cảm giác vùng này cũng trở nên bất an (nguy hiểm) hơn rồi.",
    explanation:"物騒 = ぶっそう: nguy hiểm, bất an vì hay xảy ra chuyện xấu ⇔ 安全じゃなくなってきた. きれいじゃなくなってきた (không còn sạch)・うるさくなってきた (ồn hơn)・さびしくなってきた (vắng vẻ hơn) sai nghĩa." },
  { id:"a5-2", passage:"", audioUrl:"", question:"22. その話を聞いて<u>落ち込んだ</u>。", options:["緊張した","びっくりした","がっかりした","心配した"], answer:2,
    translation:"Nghe chuyện đó tôi thấy chán nản, hụt hẫng.",
    explanation:"落ち込む = おちこむ: chán nản, hụt hẫng, tinh thần đi xuống ⇔ がっかりした (thất vọng). 緊張した (căng thẳng)・びっくりした (giật mình)・心配した (lo lắng) sai nghĩa." },
  { id:"a5-3", passage:"", audioUrl:"", question:"23. <u>精いっぱい</u>やったのに、あまり評価されなかった。", options:["せっかく","一生懸命","いろいろ","何回も"], answer:1,
    translation:"Đã cố hết sức rồi mà không được đánh giá cao lắm.",
    explanation:"精いっぱい = せいいっぱい: hết sức, cố hết mức ⇔ 一生懸命 (いっしょうけんめい: chăm chỉ, hết lòng). せっかく (đã cất công)・いろいろ (đủ thứ)・何回も (nhiều lần) sai nghĩa." },
  { id:"a5-4", passage:"", audioUrl:"", question:"24. その話を聞いて、みんな<u>同情</u>した。", options:["しかたないと思った","うらやましいと思った","なつかしいと思った","かわいそうだと思った"], answer:3,
    translation:"Nghe chuyện đó ai cũng thấy thương hại (đồng cảm).",
    explanation:"同情する = どうじょうする: đồng cảm, thương hại ⇔ かわいそうだと思った (thấy tội nghiệp). しかたないと思った (thấy đành vậy)・うらやましい (ghen tị)・なつかしい (hoài niệm) sai nghĩa." },
  { id:"a5-5", passage:"", audioUrl:"", question:"25. 条件を<u>定める</u>必要がある。", options:["決める","伝える","調べる","合わせる"], answer:0,
    translation:"Cần phải định ra (quy định) các điều kiện.",
    explanation:"定める = さだめる: quy định, định ra ⇔ 決める (quyết định). 伝える (truyền đạt)・調べる (tìm hiểu/điều tra)・合わせる (khớp, hợp) sai nghĩa." },
]},

/* ================= TAB 2: 用法 ================= */
{ tab:"用法", section:"問題6 用法",
  instruction:"次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a6-1", passage:"", audioUrl:"", question:"26. 廃止", options:["予想以上のコストがかかることがわかり、新製品の開発を廃止した。","石川さんは毎日ジョギングすることを廃止したらしい。","ほかの人に話すことで、不安を廃止できることもある。","あの銀行はATM手数料無料のサービスを廃止するそうだ。"], answer:3,
    translation:"廃止 = bãi bỏ, xóa bỏ (một chế độ, dịch vụ, cơ quan…).",
    explanation:"Đáp án 4. 廃止 dùng cho việc bãi bỏ một chế độ/dịch vụ mang tính hệ thống ⇒ 「ATM手数料無料のサービスを廃止する」 đúng. 1 nên dùng 中止 (đình chỉ giữa chừng), 2 nên dùng やめる (thôi, bỏ), 3 nên dùng 解消 (giải tỏa)." },
  { id:"a6-2", passage:"", audioUrl:"", question:"27. 初歩", options:["3年前に英語を初歩から始め、今では自由に話せるようになった。","バスケットボールの試合で、初歩から大量の点を取られた。","今日の暑さはまだほんの初歩で、これからますます暑くなっていくだろう。","兄とのけんかの初歩は、くだらないことだった。"], answer:0,
    translation:"初歩 = sơ bộ, bước đầu, vỡ lòng (phần cơ bản nhất khi bắt đầu học).",
    explanation:"Đáp án 1. 初歩 = 初歩から始める ⇒ bắt đầu từ những điều sơ đẳng nhất ⇒ 「英語を初歩から始め」 đúng. 2 nên dùng 最初 (đầu tiên), 3 nên dùng 序の口 (mới chỉ là khởi đầu), 4 nên dùng きっかけ (duyên cớ)." },
  { id:"a6-3", passage:"", audioUrl:"", question:"28. だらしない", options:["昨日作ったスープは塩がたりなかったのか、とてもだらしない味だった。","この公園は管理する人がいないので、あちこちに草がだらしなく生えている。","知識がだらしなかったせいで、間違ったことを人に教えてしまった。","先月までは、仕事もしないで遊んでばかりのだらしない生活をしていた。"], answer:3,
    translation:"だらしない = luộm thuộm, lôi thôi, sống buông thả, không nghiêm chỉnh.",
    explanation:"Đáp án 4. だらしない (lối sống buông thả) ⇒ 「仕事もしないで遊んでばかりのだらしない生活」 đúng. 1 nên dùng 薄い (nhạt), 2 nên dùng ぼうぼう (mọc um tùm), 3 nên dùng 足りなかった (thiếu)." },
  { id:"a6-4", passage:"", audioUrl:"", question:"29. 即座に", options:["私が駅に着くと即座に友人たちも来た。","さっきまで晴れていたのに、即座に雲が出てきた。","先生は学生からの質問に即座に答えた。","1月になってから即座に仕事が忙しくなった。"], answer:2,
    translation:"即座に = そくざに: ngay lập tức (phản ứng lại điều gì vừa xảy ra).",
    explanation:"Đáp án 3. 即座に (đáp lại ngay) ⇒ 「質問に即座に答えた」 đúng. 1 nên dùng ちょうど (đúng lúc), 2 & 4 nên dùng 急に/突然 (đột ngột)." },
  { id:"a6-5", passage:"", audioUrl:"", question:"30. 尽きる", options:["あしたで定期券の期限が尽きるので、新しいのを買いに行った。","森さんと会うのは久しぶりだったので、いくら話しても話が尽きなかった。","木村選手は、けがのせいで連続出場の記録が尽きてしまった。","この作家の絵は好きなので、展示会が尽きないうちにもう一度見に来たい。"], answer:1,
    translation:"尽きる = つきる: hết, cạn (話が尽きない = nói hoài không hết).",
    explanation:"Đáp án 2. 尽きる (hết, cạn kiệt) ⇒ 「話が尽きなかった」 (câu chuyện không hết) đúng. 1 nên dùng 切れる (hết hạn), 3 nên dùng 途絶える (bị gián đoạn), 4 nên dùng 終わる (kết thúc)." },
]},

/* ================= TAB 3: 文法 ================= */
{ tab:"文法", section:"問題7 文の文法1",
  instruction:"次の文の（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a7-1", passage:"", audioUrl:"", question:"31. テレビの後ろ側は、すぐほこり（　）になってしまう。", options:["きり","じゅう","ぐらい","だらけ"], answer:3,
    translation:"Mặt sau ti vi chẳng mấy chốc mà đầy bụi.",
    explanation:"名詞＋だらけ: đầy, đầy rẫy (thường hàm ý tiêu cực) ⇒ 「ほこりだらけになる」✓. きり (chỉ, chỉ có)・じゅう (suốt, khắp — thời gian/phạm vi)・ぐらい (khoảng chừng) sai." },
  { id:"a7-2", passage:"", audioUrl:"", question:"32. A「ねえ、明日、用事があるって言ってたけど、パーティーには来られそう?」<br>B「用事が何時に終わるかわからないんだよ。行ける（　）、多分、途中からになると思う。」", options:["からって","ものなら","どころか","としても"], answer:3,
    translation:"A: “Này, cậu nói mai có việc bận, thế có đến được bữa tiệc không?” B: “Không biết mấy giờ mới xong việc. Kể cả có đi được thì chắc cũng phải đến giữa chừng.”",
    explanation:"～としても: dù cho…, kể cả có… (nhượng bộ) ⇒ 「行けるとしても、途中からになる」✓. からって (vì rằng — truyền đạt lí do), ものなら (nếu mà… thì), どころか (chứ đâu phải) sai nghĩa." },
  { id:"a7-3", passage:"", audioUrl:"", question:"33. X社は、新しい事業を始める（　）、現在、社員を募集している。", options:["とすると","にあたって","からには","のだったら"], answer:1,
    translation:"Công ty X, nhân dịp bắt đầu một công việc kinh doanh mới, hiện đang tuyển nhân viên.",
    explanation:"～にあたって: nhân dịp, khi (làm việc gì trang trọng) ⇒ 「新しい事業を始めるにあたって」✓. とすると (nếu giả sử)・からには (một khi đã… thì phải)・のだったら (nếu là… thì) không hợp mạch 'đang tuyển dụng'." },
  { id:"a7-4", passage:"", audioUrl:"", question:"34. 私はピアノを弾くことが、好き（　）好き（　）たまらない。", options:["が/が","に/に","で/で","は/は"], answer:2,
    translation:"Tôi thích chơi piano đến mức không chịu nổi.",
    explanation:"～てたまらない (không thể chịu nổi) với tính từ đuôi な/名詞 chuyển thành ～で ⇒ 「好きで好きでたまらない」✓ (lặp lại để nhấn mạnh mức độ). が・に・は không đi với ～たまらない trong mẫu này." },
  { id:"a7-5", passage:"", audioUrl:"", question:"35. (電話で)田中「ねえ、明日のイベントの準備、終わった?」<br>小川「まだ終わってないけど、まあ、大丈夫だよ。」<br>田中「（　）小川さんの楽観的な性格がうらやましいよ。」", options:["そんなに","あんなに","そういう","ああいう"], answer:2,
    translation:"(Qua điện thoại) Tanaka: “Này, việc chuẩn bị cho sự kiện mai xong chưa?” Ogawa: “Chưa xong nhưng mà, chắc không sao đâu.” Tanaka: “Tôi ghen tị với tính cách lạc quan ấy của cậu ghê.”",
    explanation:"そういう (loại… như thế) bổ nghĩa cho danh từ 「性格」⇒ 「そういう小川さんの楽観的な性格」✓. そんなに/あんなに (đến mức đó — bổ nghĩa cho động từ/tính từ)・ああいう (loại kia — chỉ thứ cả hai đều biết) sai ở đây." },
  { id:"a7-6", passage:"", audioUrl:"", question:"36. 日曜日に行われたマラソン大会に弟が参加して、10キロのコースを45分で（　）。", options:["走りきった","走り始めた","走ってばかりだ","走るようにする"], answer:0,
    translation:"Em trai tôi đã tham gia cuộc thi marathon diễn ra Chủ nhật và chạy hết quãng đường 10 km trong 45 phút.",
    explanation:"～きる (làm cho trọn vẹn, làm đến cùng) ⇒ 「45分で走りきった」✓. 走り始めた (bắt đầu chạy)・走ってばかりだ (toàn chạy)・走るようにする (cố chạy) sai nghĩa." },
  { id:"a7-7", passage:"", audioUrl:"", question:"37. 子供のころ、海水浴に行く前の日はいつも「どうか明日は雨が（　）」と祈りながら寝ていた。", options:["降ることはありません","降りませんように","降らなくてもいいです","降らないでしょうか"], answer:1,
    translation:"Hồi nhỏ, đêm trước ngày đi tắm biển tôi luôn vừa cầu nguyện “mong sao mai trời đừng mưa” vừa ngủ thiếp đi.",
    explanation:"～ませんように: mong sao… (câu ước, cầu nguyện) ⇒ 「雨が降りませんように」✓. ことはありません (không có chuyện…)・なくてもいいです (không… cũng được)・ないでしょうか (không biết có… không) sai nghĩa." },
  { id:"a7-8", passage:"", audioUrl:"", question:"38. 鈴木選手は、アマチュア時代に何度かこの大会に出場しているが、プロの選手（　）今回が初めての出場だ。", options:["としては","としても","にとっては","にとっても"], answer:0,
    translation:"Vận động viên Suzuki tuy hồi còn nghiệp dư đã vài lần tham dự giải này, nhưng với tư cách vận động viên chuyên nghiệp thì đây là lần đầu tiên.",
    explanation:"～としては: với tư cách là… (nhấn mạnh は so sánh) ⇒ 「プロの選手としては今回が初めて」✓. としても (dù là với tư cách)・にとっては/にとっても (đối với… thì/đối với… cũng) sai nghĩa." },
  { id:"a7-9", passage:"", audioUrl:"", question:"39. 泣くのを我慢（　）、逆に涙はあふれ出した。", options:["しようとすることから","しそうになることから","しようとすればするほど","しそうになればなるほど"], answer:2,
    translation:"Càng cố nén khóc thì ngược lại nước mắt càng trào ra.",
    explanation:"～ようとすればするほど: càng cố… thì càng… ⇒ 「我慢しようとすればするほど」✓ (～ば～ほど). ことから (vì, do — nêu nguyên cớ)・しそうになる (suýt thì…) không hợp mẫu 'càng… càng…'." },
  { id:"a7-10", passage:"", audioUrl:"", question:"40. 押し入れを片付けていたら、子供のころに大切にしていたぬいぐるみが出てきた。（　）と思ったが、どうしても捨てられなかった。", options:["捨ててくるだろう","捨てているのだ","捨ててあるのか","捨ててしまおうか"], answer:3,
    translation:"Khi dọn tủ âm tường, tôi tìm thấy con gấu bông mà hồi nhỏ tôi rất quý. Tôi đã nghĩ “hay là bỏ quách đi nhỉ” nhưng rốt cuộc không nỡ vứt.",
    explanation:"～てしまおうか: hay là… quách đi nhỉ (ý định, quyết định) ⇒ 「捨ててしまおうかと思った」✓. 捨ててくるだろう (chắc sẽ đi vứt rồi về)・捨てているのだ (đang vứt)・捨ててあるのか (đã được vứt rồi à) sai nghĩa." },
  { id:"a7-11", passage:"", audioUrl:"", question:"41. 田中「昨日、息子がひろしくんに（　）ありがとうございます。」<br>ひろしの母「いえいえ。」", options:["遊んでもらえそうで","遊んでくれそうで","遊んでもらったそうで","遊んでくれたそうで"], answer:2,
    translation:"Tanaka: “Chuyện hôm qua con trai tôi được cháu Hiroshi chơi cùng, cảm ơn chị.” Mẹ của Hiroshi: “Không có gì đâu.”",
    explanation:"Chủ ngữ là con trai mình (phe người nói) ⇒ dùng ～てもらう (nhận ơn): 「息子が…遊んでもらったそうで」✓; sự việc đã xảy ra (hôm qua) nên là ～たそうで. 遊んでくれたそうで (chủ ngữ là người khác)・～そうで (dạng chưa xảy ra) sai." },
  { id:"a7-12", passage:"", audioUrl:"", question:"42. この映画を見て、私は今までこれほど何かに夢中に（　）と考えさせられた。", options:["なることがあるだろうか","なったことがあっただろうか","することがあるだろうか","したことがあっただろうか"], answer:1,
    translation:"Xem bộ phim này, tôi bỗng tự hỏi: “Liệu đến nay đã từng có lúc nào mình say mê điều gì đến mức này chưa nhỉ?”",
    explanation:"夢中に＋なる ⇒ loại する (C, D). Vế trước là 「今まで」 (đến nay) nên dùng thì quá khứ ～なったことがあっただろうか ✓. なることがあるだろうか (dạng hiện tại) sai thì." },
]},
{ tab:"文法", section:"問題8 文の文法2 (sắp xếp - ★)",
  instruction:"次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a8-1", passage:"", audioUrl:"", question:"43. 料理のおもしろいところは、安い材料でも ＿＿ ＿＿★ ＿＿ ＿＿ ができるところです。［1 ごちそう / 2 工夫 / 3 豪華な / 4 次第で］", options:["ごちそう","工夫","豪華な","次第で"], answer:2,
    translation:"Điều thú vị của việc nấu ăn là, dù nguyên liệu rẻ, tùy theo cách khéo léo mà có thể làm ra món ăn xa hoa.",
    explanation:"Thứ tự đúng: 工夫（2）→ 次第で（4）→ 豪華な（3）→ ごちそう（1）: 「安い材料でも工夫次第で豪華なごちそうができる」。★ là ô thứ 3 ⇒ đáp án ③ 豪華な. ～次第で: tùy theo…" },
  { id:"a8-2", passage:"", audioUrl:"", question:"44. 田中「昨日は、息子の高校の入学式だったんですよ。」<br>山田「田中さんの ＿＿ ＿＿★ ＿＿ ＿＿ ですか。早いですね」［1 もう / 2 息子さん / 3 高校生 / 4 も］", options:["もう","息子さん","高校生","も"], answer:0,
    translation:"Tanaka: “Hôm qua là lễ nhập học cấp ba của con trai tôi đấy.” Yamada: “Con trai anh cũng đã là học sinh cấp ba rồi à. Nhanh thật.”",
    explanation:"Thứ tự đúng: 息子さん（2）→ も（4）→ もう（1）→ 高校生（3）: 「田中さんの息子さんももう高校生ですか」。★ là ô thứ 3 ⇒ đáp án ① もう." },
  { id:"a8-3", passage:"", audioUrl:"", question:"45. 世界各国の国会議員選挙における投票率を世代ごとに見ると、若い世代の ＿＿ ＿＿★ ＿＿ ＿＿ ことがわかる。［1 わが国に限らず / 2 傾向がある / 3 投票率は / 4 相対的に低い］", options:["わが国に限らず","傾向がある","投票率は","相対的に低い"], answer:3,
    translation:"Nhìn tỉ lệ đi bỏ phiếu trong bầu cử quốc hội các nước theo từng thế hệ, có thể thấy tỉ lệ đi bỏ phiếu của thế hệ trẻ tương đối thấp, không chỉ riêng ở nước ta.",
    explanation:"Thứ tự đúng: 投票率は（3）→ わが国に限らず（1）→ 相対的に低い（4）→ 傾向がある（2）: 「…若い世代の投票率は、わが国に限らず相対的に低い傾向がある」。★ là ô thứ 3 ⇒ đáp án ④ 相対的に低い. ～に限らず: không chỉ…" },
  { id:"a8-4", passage:"", audioUrl:"", question:"46. 5歳の娘は、私と同じ警察官になりたいと言っている。本当に将来 ＿＿ ＿＿★ ＿＿ ＿＿ 感激した。［1 別として / 2 そんなことを / 3 言ってくれたことに / 4 なるかどうかは］", options:["別として","そんなことを","言ってくれたことに","なるかどうかは"], answer:1,
    translation:"Cô con gái 5 tuổi nói muốn trở thành cảnh sát giống tôi. Khoan nói chuyện sau này có thành hay không, chỉ riêng việc con nói những điều như thế tôi đã cảm động rồi.",
    explanation:"Thứ tự đúng: なるかどうかは（4）→ 別として（1）→ そんなことを（2）→ 言ってくれたことに（3）: 「…なるかどうかは別として、そんなことを言ってくれたことに感激した」。★ là ô thứ 3 ⇒ đáp án ② そんなことを. ～は別として: khoan kể đến…" },
  { id:"a8-5", passage:"", audioUrl:"", question:"47. 試合に負けて本当は ＿＿★ ＿＿ ＿＿ ＿＿ 表情だったのは、「つらいときこそ明るく」というのが監督の方針だからだそうだ。［1 悔しいはずの / 2 明るい / 3 なぜか / 4 選手たちが］", options:["悔しいはずの","明るい","なぜか","選手たちが"], answer:0,
    translation:"Nghe nói việc các vận động viên, những người lẽ ra phải tiếc nuối sau khi thua trận, lại không hiểu sao có vẻ mặt tươi cười là do phương châm của huấn luyện viên: “càng lúc khổ sở càng phải tươi vui”.",
    explanation:"Thứ tự đúng: 悔しいはずの（1）→ 選手たちが（4）→ なぜか（3）→ 明るい（2）: 「…本当は悔しいはずの選手たちがなぜか明るい表情だったのは…」。★ là ô đầu ⇒ đáp án ① 悔しいはずの." },
]},
{ tab:"文法", section:"問題9 文章の文法 (điền vào đoạn văn)",
  instruction:"次の文章を読んで、文章全体の内容を考えて、48から52の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a9-1", passage:"以下は、留学生の作文である。<br><br>打ち水<br>ロバーツアレン<br><br>夏休みに、友達に誘われて打ち水のイベントに参加しました。私はそのとき初めて打ち水というものを知りました。打ち水は、暑さ対策として道路や庭、玄関先などに水をまくという、日本に昔から伝わる生活の知恵です。もともとは各家庭で行うものでしたが、節電や地球温暖化対策として打ち水のイベントを企画する自治体なども（48）。<br><br>打ち水をすると、確かに涼しく感じました。（49）、気分の問題ではないかとも思いました。打ち水によって実際に気温は下がるのでしょうか。<br><br>調べていたら、打ち水の効果を調べた実験結果を紹介している記事がありました。その記事によると、水をまいたところの気温が2度下がったということでした。これは水の性質によるものです。水は気体になるときに、周囲の熱を吸収します。水をまいたところの地面の熱は気体とともに逃げていき、気温が（50）。しかも、地面の温度は、水が蒸発しきった後も1時間は下がったままだったとも書かれていました。<br><br>打ち水の効果を十分に得るには、朝か夕方に日陰にまくこともポイントのようです。そうすることで水がすぐに蒸発せず、温度の下がった状態が持続します。私が参加したイベントも夕方からだったので、なぜだろうと思っていましたが、（51）あったのだと知って、なるほどと思いました。<br><br>打ち水の効果は、科学的に説明できるものでした。だから昔から今まで打ち水の文化が続いているのだと（52）。", audioUrl:"", question:"48. 節電や地球温暖化対策として打ち水のイベントを企画する自治体なども（48）。", options:["増えたとします","増えているのです","増えてしまいます","増えているそうです"], answer:3,
    translation:"Đoạn văn trên là bài văn của một du học sinh. Vào kỳ nghỉ hè, được bạn rủ, tôi đã tham gia một sự kiện 打ち水 (té nước làm mát). Lúc đó tôi mới biết đến 打ち水. …Ban đầu việc này do từng gia đình tự làm, nhưng nghe nói hiện nay cả các chính quyền địa phương tổ chức sự kiện 打ち水 như biện pháp tiết kiệm điện và chống nóng lên toàn cầu cũng đang tăng lên.",
    explanation:"【48】= 増えているそうです: nghe nói đang tăng lên (truyền đạt thông tin) ⇒ 「自治体なども増えているそうです」✓. 増えたとします (coi như đã tăng)・増えているのです (là đang tăng — nêu giải thích)・増えてしまいます (lỡ tăng mất — tiêu cực) sai mạch văn." },
  { id:"a9-2", passage:"", audioUrl:"", question:"49. 打ち水をすると、確かに涼しく感じました。（49）、気分の問題ではないかとも思いました。", options:["ただ","それに","つまり","それどころか"], answer:0,
    translation:"Làm 打ち水 thì đúng là thấy mát hơn. Tuy nhiên, tôi cũng nghĩ có khi đó chỉ là vấn đề cảm giác.",
    explanation:"【49】= ただ: tuy nhiên, nhưng (nêu ý tương phản) ⇒ hợp với câu sau phủ định lại cảm giác ✓. それに (hơn nữa — bổ sung)・つまり (nói cách khác — tổng kết)・それどころか (chứ đâu chỉ thế) sai." },
  { id:"a9-3", passage:"", audioUrl:"", question:"50. 水をまいたところの地面の熱は気体とともに逃げていき、気温が（50）。", options:["下がるところです","下がる一方でした","下がるというわけです","下がることがありました"], answer:2,
    translation:"Nhiệt của mặt đất nơi được té nước thoát đi cùng với hơi nước, tức là nhiệt độ sẽ giảm xuống.",
    explanation:"【50】= 下がるというわけです: tức là… giảm xuống (tổng kết, giải thích nguyên nhân — khép lại đoạn giải thích khoa học) ✓. 下がるところです (sắp giảm)・下がる一方でした (đã cứ giảm mãi)・下がることがありました (đã từng giảm) sai nghĩa." },
  { id:"a9-4", passage:"", audioUrl:"", question:"51. 私が参加したイベントも夕方からだったので、なぜだろうと思っていましたが、（51）あったのだと知って、なるほどと思いました。", options:["ある理由が","そのような理由が","どの理由も","あんな理由も"], answer:1,
    translation:"Sự kiện tôi tham gia cũng bắt đầu từ chiều tối nên tôi từng thắc mắc không hiểu vì sao, nhưng khi biết rằng có lí do như vậy thì tôi thấy “à, ra thế”.",
    explanation:"【51】= そのような理由が: có lí do “như thế/đó” — chỉ lí do vừa được nêu ở đoạn trên ✓. ある理由が (một lí do nào đó — không chỉ định)・どの理由も (lí do nào cũng)・あんな理由も (đến cả lí do như kia — dùng cho thứ xa/coi nhẹ) sai." },
  { id:"a9-5", passage:"", audioUrl:"", question:"52. だから昔から今まで打ち水の文化が続いているのだと（52）。", options:["納得させられました","納得したのでしょう","納得させてほしかったです","納得してもらえました"], answer:0,
    translation:"Vì vậy, tôi đã tự cảm nhận và thấy hiểu ra rằng văn hóa 打ち水 vẫn được duy trì từ xưa đến nay là như thế.",
    explanation:"【52】= 納得させられました: (tự nhiên) thấy được thuyết phục, hiểu ra (dạng tự phát) — chủ ngữ là người viết ✓. 納得したのでしょう (chắc là đã hiểu)・納得させてほしかった (muốn được làm cho hiểu)・納得してもらえました (mình làm cho người khác hiểu) sai." },
]},

/* ================= TAB 4: 読解 ================= */
{ tab:"読解", section:"問題10 内容理解・短文",
  instruction:"次の（1）から（5）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b10-1", passage:"（1）一般的に、表とグラフでは、グラフのほうがすぐに特徴をみつけやすいといえます。だからといって、そうしてみつけた特徴が本当に意味がある特徴かどうか、単なる錯覚（注1）ではないのか、グラフをみたことで先入観（注2）をもってしまったあとでは、検証（注3）がむずかしいでしょう。<br><br>だからこそ、まずは、特徴をみつけにくい表をながめてデータ分析をすることが、データ読解力を高めるうえでは大切です。そうして表のデータを読む力を磨くことで、やがてグラフでの錯覚を避ける能力も高まります。<br><br>（注1）錯覚：ここでは、勘違い<br>（注2）先入観：思い込み<br>（注3）検証：調べて、証明すること", audioUrl:"", question:"53. 筆者によると、データ分析の力をつけるにはどうすればいいか。", options:["特徴がみつけやすいので、先に表をみるようにしたほうがいい。","思い込みが避けられるので、先に表をみるようにしたほうがいい。","思い込みに気づきやすいので、先にグラフをみるようにしたほうがいい。","意味のある特徴がみつけられるので、先にグラフをみるようにしたほうがいい。"], answer:1,
    translation:"Nói chung, giữa bảng biểu và đồ thị thì có thể nói đồ thị dễ phát hiện đặc điểm ngay. Nhưng chính vì thế, liệu đặc điểm tìm thấy như vậy có thực sự có ý nghĩa hay chỉ là ảo giác? Sau khi đã nhìn đồ thị mà mang định kiến thì việc kiểm chứng sẽ khó. Vì vậy, trước hết hãy nhìn bảng biểu (khó phát hiện đặc điểm) để phân tích dữ liệu — điều đó quan trọng để nâng cao năng lực đọc dữ liệu.",
    explanation:"Đoạn 2 nói phải bắt đầu bằng việc nhìn 表 (bảng) để tránh định kiến/ảo giác ⇒ đáp án 2 “để tránh thành kiến thì nên xem bảng trước” ✓. 1 sai vì bảng không dễ thấy đặc điểm; 3, 4 nói xem グラフ trước là ngược với ý tác giả." },
  { id:"b10-2", passage:"（2）以下は、ある市のホームページに掲載されたお知らせである。<br><br>今村市＞文化芸術施設＞お知らせ<br>2019年5月29日<br><br>文化施設共通利用券および「特別展セット」販売のお知らせ<br><br>文化施設共通利用券を販売いたします。この券は、市内五つの博物館や美術館などの文化施設にそれぞれ1回ご入場できるチケットです。<br>また、文化施設共通利用券に特別展割引チケットを付け「特別展セット」も販売いたします。特別展のご入場には通常1回1,000円かかりますが、「特別展セット」では各施設の特別展の中から一つに限り割引価格で1回ご入場できます。<br><br>販売場所：各施設のチケット売り場<br>販売価格：文化施設共通利用券2,000円、「特別展セット」2,800円<br>販売期間：2019年7月1日～2019年10月31日<br>有効期間：2019年7月1日～2019年12月27日<br><br>どちらも大変お得になっています。この機会にぜひご利用ください。", audioUrl:"", question:"54. 「特別展セット」を買うと何ができるか。", options:["各施設に1回ずつ入場でき、さらに割引価格で特別展に1回ずつ入場できる。","各施設に1回ずつ入場でき、さらに割引価格で特別展のうち一つに1回入場できる。","各施設に何回でも入場でき、さらに割引価格で特別展に1回ずつ入場できる。","各施設に何回でも入場でき、さらに割引価格で特別展のうち一つに1回入場できる。"], answer:1,
    translation:"Mua “特別展セット” thì được gì? — Mỗi cơ sở văn hóa vào được 1 lần, và thêm nữa, với giá ưu đãi được vào 1 lần đối với một trong các triển lãm đặc biệt.",
    explanation:"「共通利用券」cho vào mỗi cơ sở 1 lần ⇒ loại 3, 4 (何回でも sai). 「特別展セット」= 各施設の特別展の中から一つに限り割引価格で1回入場 ⇒ đáp án 2 ✓. 1 sai vì 'mỗi triển lãm 1 lần' (1回ずつ) không đúng — chỉ được một triển lãm." },
  { id:"b10-3", passage:"（3）論文というものは言葉で書くものである。あたりまえのことだが、これは肝心な（注1）ことである。ということは、よい論文を書くためには言葉に敏感でなければならないということである。しかし、それはかならずしも、なにか特別なもっともらしい（注2）言葉をうまく操らなければいけないということではない。むしろ、自分の身についた、ふだんはなにげなく（注3）使っているにすぎないような言葉を、いちいち、しっかりととらえなおし、その意味を自分にとってたしかな手応えのある（注4）ものにしてゆくということである。<br><br>（注1）肝心な：とても大切な<br>（注2）もっともらしい：いかにも本物らしい<br>（注3）なにげなく：意識しないで<br>（注4）たしかな手応えのある：ここでは、確信の持てる", audioUrl:"", question:"55. 筆者は、論文を書くのに大切なことは何だと考えているか。", options:["多くの言葉を正確に使えるようにすること","特別な言葉を日常的に使えるようにすること","新しい言葉の意味をしっかりととらえること","日常使っている言葉の意味をたしかめながら使うこと"], answer:3,
    translation:"Luận văn là thứ viết bằng ngôn từ. Điều quan trọng là phải nhạy cảm với ngôn từ. Nhưng không hẳn là phải dùng những từ ngữ đặc biệt, có vẻ 'đúng' nào đó, mà ngược lại: nắm lại thật chắc từng từ ngữ mình đã quen, vẫn dùng hằng ngày một cách vô thức, và biến ý nghĩa của chúng thành điều mình thực sự nắm chắc.",
    explanation:"Sau 「むしろ」 (ngược lại, chính là) tác giả nói: nắm lại chắc chắn ý nghĩa của những từ mình dùng hằng ngày rồi mới dùng ⇒ đáp án 4 ✓. 1, 2, 3 nói dùng nhiều từ / từ đặc biệt / từ mới — không phải ý tác giả." },
  { id:"b10-4", passage:"（4）以下は、ある会社が製品を注文してきた相手に出したメールである。<br><br>あて先：seiji_omura@matsufuku-shokai.co.jp<br>件名：スピーカー「8QPS1」のご注文につきまして<br>日時：2019年6月5日10:30<br><br>マツフク商会<br>営業部大村成次様<br><br>お世話になっております。<br>このたびは、スピーカー「8QPS1」20台をご注文いただきありがとうございました。同機は4月の発売以来、予想以上の売れ行きが続き、製造が追いついておりません。現在、海外の工場でも対応しておりますが、ご指定の期日（6月28日）での納品は難しい状況です。納品可能時期は今月中旬に改めてお知らせいたします。たいへん申し訳ございませんが、ご理解くださいますようお願いいたします。<br><br>オーシーサウンド<br>販売部川勝直広", audioUrl:"", question:"56. このメールで最も伝えたいことは何か。", options:["「8QPS1」の納品日が今月中旬になること","「8QPS1」の納品が可能かどうかを今月中旬に知らせること","「8QPS1」を指定の納品日に納品できないこと","「8QPS1」が予想以上に売れていて、注文を受けられないこと"], answer:2,
    translation:"Đây là email công ty gửi cho bên đã đặt hàng. Nội dung chính: xin lỗi vì không thể giao hàng đúng ngày chỉ định (28/6); thời điểm có thể giao sẽ thông báo lại vào giữa tháng này.",
    explanation:"Câu 3 và 4 của mail nói: 'khó giao đúng ngày 6月28日' và 'giữa tháng này sẽ thông báo lại thời điểm giao được' ⇒ ý chính là không giao được đúng ngày ⇒ đáp án 3 ✓. 1, 2 nói về ngày giao/thông báo — chỉ là thông tin phụ; 4 sai (vẫn nhận đơn, chỉ chậm giao)." },
  { id:"b10-5", passage:"（5）試合に出してもらえない、監督やコーチと相性が悪い、他の選手のほうが贔屓（注1）されている…。自分がうまくできない、試合で活躍できないのは、環境が悪いからだ、監督のせいだ、他の選手とプレーがかみ合わない、（注2）……。自分がある程度頑張っているつもりの選手は、つい、こう考えてしまうものです。<br><br>うまくなるために自分自身と向き合っているとすれば、そこに周りは一切（注3）関係ありません。人のせい、物のせいにするのはラク（注4）ですが、私から言わせれば、人のせい、物のせいにするのは、逃げていることと同じです。<br><br>（注1）贔屓される：ここでは、気に入って特別に扱われる<br>（注2）かみ合う：うまく合う<br>（注3）一切：全く<br>（注4）ラク：「楽」とも書く", audioUrl:"", question:"57. 筆者の考えに合うのはどれか。", options:["うまくなるためには、周りのせいにしてはいけない。","うまくなりたいなら、周りに合わせてはいけない。","周りから悪い評価を受けたら、認めなければならない。","頑張っていても、周りから認められないことがある。"], answer:0,
    translation:"Không được cho ra sân, không hợp với huấn luyện viên, đồng đội được ưu ái hơn… Nếu thực sự đối diện với bản thân để giỏi lên thì mọi thứ xung quanh chẳng liên quan gì. Đổ lỗi cho người khác, cho hoàn cảnh thì nhàn thân, nhưng theo tôi, đó cũng giống như đang bỏ chạy.",
    explanation:"「うまくなるために自分自身と向き合っているとすれば、そこに周りは一切関係ありません」⇒ đáp án 1 'để giỏi lên thì không được đổ lỗi cho xung quanh' ✓. 2 (không được hòa hợp với xung quanh)・3 (phải thừa nhận đánh giá xấu)・4 (cố gắng mà không được công nhận) không phải ý tác giả." },
]},
{ tab:"読解", section:"問題11 内容理解・中文",
  instruction:"次の（1）から（3）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b11-1", passage:"（1）本を読むことは、かつて生きた優れた人の言葉を聞くということ。読むとは、基本的に人の話を聞くことです。学ぶことの基本行為も「聞くこと」です。<br>しかも、本を読むことが生きている人間から話を聞くことと同じととらえられれば、その読みは一層リアル（注1）になるはずです。たとえば、本居宣長を読むのでもゲーテを読むのでも、彼らが生きているかのようにして読める人のほうが、生の声として聞こえてくるからより一層リアルです。<br>ですから、「聞く構え」（注2）ができている人は、より良く学べることにもなります。<br>逆に、聞く構えがないと、相手からは成長がない人と見られてしまいます。言い換えれば、「聞く気がない」と受け取られてしまうと、会社でも学校でも「この人は見込み（注3）がない」と思われてしまうのです。<br>こんなふうに、学ぶ姿勢は現実の生活において、私たちの根本的な評価にかかわってきます。<br>学ぶことは、優れた人の話を聞いて自分を修正していくこと。あるいは、その人に憧れを持ち、その人によって自分の新たな目標が見え、歩むべき方向性が決まることです。そして、本や人の話の中から具体的なアドバイスを得て、自分の生活の中にある種の学びの習慣をつくっていく。だからこそ、読書を学びの基本にするとよいのです。<br>本を読まないということは、いわば膨大な数の賢者（注4）たちから、あらかじめ見放されて（注5）しまっているということです。<br><br>（注1）リアル：現実的<br>（注2）構え：姿勢<br>（注3）見込み：可能性<br>（注4）賢者：優れた人<br>（注5）見放される：ここでは、無視される", audioUrl:"", question:"58. 筆者によると、本はどのように読むといいか。", options:["書かれていることを、現実の話として読む。","書かれていることを、作者と同じ気持ちになって読む。","書かれていることを、前に聞いた話と比べながら読む。","書かれていることを、話を聞いているような気持ちで読む。"], answer:3,
    translation:"Đọc sách chính là nghe lời của những người tài giỏi đã từng sống. Đọc, về cơ bản, là nghe người ta nói. Nếu coi việc đọc sách giống như nghe người đang sống nói chuyện thì việc đọc sẽ trở nên chân thực hơn. Vì thế, người có “tư thế lắng nghe” sẽ học tốt hơn. Ngược lại, không có tư thế lắng nghe thì bị coi là người không tiến bộ. Học là nghe lời người giỏi để sửa mình… Vì thế, hãy lấy đọc sách làm nền tảng của việc học. Không đọc sách nghĩa là đã bị vô số bậc hiền triết bỏ rơi từ trước.",
    explanation:"Ý tác giả: coi việc đọc như đang nghe người thật nói ⇒ đáp án 4 'đọc với cảm giác như đang nghe ai đó nói' ✓. 1 (đọc như chuyện hiện thực)・2 (đọc với tâm trạng giống tác giả)・3 (so sánh với chuyện từng nghe) sai." },
  { id:"b11-2", passage:"", audioUrl:"", question:"59. 「聞く構え」ができていない人について、筆者はどのように述べているか。", options:["人の話を聞いてもすぐに忘れてしまう人だと思われる。","人の話を聞いて学ぼうという気がない人だと思われる。","会社や学校での評価を気にしない人だと思われる。","聞いたことを間違って理解する人だと思われる。"], answer:1,
    translation:"Về người không có “tư thế lắng nghe”, tác giả nói gì? — Bị coi là người không có ý muốn nghe để học hỏi.",
    explanation:"「言い換えれば、『聞く気がない』と受け取られてしまうと…『見込みがない』と思われてしまう」⇒ đáp án 2 ✓. 1 (quên ngay)・3 (không quan tâm đánh giá)・4 (hiểu sai điều đã nghe) sai nghĩa." },
  { id:"b11-3", passage:"", audioUrl:"", question:"60. 読書について、筆者の考えに合うのはどれか。", options:["読書によって、学びの習慣を身につけていくことが大切だ。","優れた人の本を読むことで、その人に近づくことができる。","新たな目標が見つかったら、その目標に合った本を読むのがいい。","歩むべき方向性を決めるには、具体的なアドバイスの本を読むのがいい。"], answer:0,
    translation:"Về đọc sách, ý nào hợp với suy nghĩ của tác giả? — Thông qua đọc sách, việc hình thành thói quen học tập là quan trọng.",
    explanation:"Câu tổng kết: 「本や人の話の中から具体的なアドバイスを得て、自分の生活の中にある種の学びの習慣をつくっていく。だからこそ、読書を学びの基本にするとよい」⇒ đáp án 1 ✓. 2, 3, 4 nói về việc tiến gần người giỏi / đọc sách hợp mục tiêu / đọc sách lời khuyên — không phải ý chính." },
  { id:"b11-4", passage:"（2）紙は私たちの身の回りにあふれているが、日本には一般的に使われている「洋紙」のほかに、古くから使われている「和紙」がある。<br>洋紙は、安い価格で多量に手に入る針葉樹や広葉樹の、皮を取り除いた幹（注1）の部分を原料とする。一方和紙は、主に楮、三椏、雁皮という木の、皮の部分を使用する。また、洋紙は表面に凹凸が少なく印刷に適しているが、和紙は表面が滑らかでなく印刷には向かないという違いがある。しかし、和紙には丈夫で強く、さらに劣化（注2）しにくいので長期間保存ができるという利点もある。<br>日本では六世紀ごろから和紙が使用されていたが、明治時代になり洋紙が輸入され始めると洋紙が一気に広まった。手作業で製造されていた和紙に対し、洋紙は早くから製造過程が機械化され、大量生産による安価で安定した供給が可能であったためである。その結果、和紙は洋紙に対抗できなくなり、和紙産業は衰えた。しかし、これをきっかけに和紙の製造過程も機械化が進められた。<br>現在日本国内で広く用いられているのは洋紙だが、和紙は和紙でなければならない分野で活用されている。書道や絵画だけでなく、その美しさが評価されて壁紙や便箋、封筒などにも利用されており、海外でもその価値が認められている。また、丈夫で傷みにくいという利点を生かして美術作品などの修理・保存にも使われている。今後も残していきたい伝統文化である。<br><br>（注1）幹：木の、根から上のほうに伸びて、枝・葉を出す部分<br>（注2）劣化する：品質が低下する", audioUrl:"", question:"61. 和紙の特徴として、筆者が述べているのはどれか。", options:["木の皮を取り除いた幹の部分を原料とし、丈夫で破れにくい。","木の皮を取り除いた幹の部分を原料とし、価格が高い。","木の皮の部分を原料とし、印刷に適している。","木の皮の部分を原料とし、長く保存できる。"], answer:3,
    translation:"Giấy (washi) Nhật Bản: nguyên liệu là phần vỏ của các loại cây kozo, mitsumata, ganpi; tuy không thích hợp in ấn nhưng bền chắc, khó hư hỏng nên bảo quản được lâu dài.",
    explanation:"Đoạn 2: 和紙 dùng 皮の部分 làm nguyên liệu; 丈夫で強く、劣化しにくいので長期間保存できる ⇒ đáp án 4 ✓. 1, 2 sai nguyên liệu (幹); 3 sai vì 和紙 không hợp in ấn." },
  { id:"b11-5", passage:"", audioUrl:"", question:"62. 「和紙は洋紙に対抗できなくなり」とあるが、なぜか。", options:["和紙は大量に生産することができなかったから","和紙は日本国内であまり利用されていなかったから","和紙より洋紙のほうが品質がよかったから","和紙より洋紙のほうが珍しくて人気があったから"], answer:0,
    translation:"Vì sao “washi không thể cạnh tranh được với giấy phương Tây”? — Vì washi không thể sản xuất với số lượng lớn.",
    explanation:"洋紙は機械化により大量生産され安価で安定供給が可能だったのに対し、和紙は手作業で製造 ⇒ vì 和紙 không sản xuất hàng loạt được ⇒ đáp án 1 ✓. 2, 3, 4 không được nêu là nguyên nhân." },
  { id:"b11-6", passage:"", audioUrl:"", question:"63. 和紙について、筆者はどのように考えているか。", options:["和紙の特徴を生かせるような、新しい利用方法を考えていきたい。","海外でも、和紙の価値が認められるようにしていきたい。","洋紙のよさを取り入れて、和紙をよりよいものにしたい。","洋紙にはない和紙のよさがあるから、守っていきたい。"], answer:3,
    translation:"Về washi, tác giả nghĩ gì? — Vì washi có ưu điểm mà giấy phương Tây không có, nên muốn gìn giữ nó.",
    explanation:"Câu cuối: 「今後も残していきたい伝統文化である」 (là văn hóa truyền thống muốn gìn giữ) ⇒ đáp án 4 ✓. 1 (tìm cách dùng mới)・2 (làm cho giá trị được công nhận ở nước ngoài)・3 (tiếp thu ưu điểm giấy phương Tây) không đúng." },
  { id:"b11-7", passage:"（3）現代の若者は、「温かさ」まで人から与えてもらえるものだと期待している。なにもかも、自分に向かって訪れるものだと信じている。だから、そういうものが自分にやってこないと、相手が悪い、周囲が悪い、社会が悪い、国が悪い、経済が悪い、運が悪い、時代が悪いということになってしまう。①そのような分析もけっこうだが、たとえそれらしい原因を見つけても、解決の方法を見出す（注1）ことはできないだろう。自分のことならなんとかなるが、相手や周囲や社会や国や経済や運や時代は、自分の努力では変えられないからだ。<br>それなのに、解決策がどこかにないだろうか、と②「検索」する。検索で解決するようなものだったら、「問題」とはいえないことにも気づいていない。<br>情報化社会において人は、自分の思うとおりにならないのは、なんらかの情報を自分が「知らない」せいだ、と解釈してしまう。必死になってネット（注2）を検索するのも、また、友達の話や、たまたま耳にしたことを簡単に信じてしまうのも、「知る」ことで問題が解決できると信じているせいだ。<br>検索できるものは、過去に存在した情報だけだ。知ることができるのも、既に存在している知見（注3）だけである。しかし、自分の問題を解決する方法は、自分で考え、模索し（注4）、新たに編み出さ（注5）なければならないものなのである。<br>自分の生き方に関する問題は、どこかに解決策が書かれているはずがない。検索しても見つかるはずがない。どんなに同じような道に見えても、先輩の言葉が全面的に通用するわけでもない。自分で生きながら、見つけるしかないのである。<br><br>（注1）見出す：見つける<br>（注2）ネット：インターネット<br>（注3）知見：ここでは、見方や考え方<br>（注4）模索する：探し求める<br>（注5）編み出す：生み出す", audioUrl:"", question:"64. ①そのような分析とはどのような分析か。", options:["自分の期待どおりにならないのは自分以外が原因だと考える。","自分の努力では周囲を変えることはできないと考える。","自分が持っていないものは人から与えてもらえると考える。","周囲や社会で悪いことが起こっても自分とは関係ないと考える。"], answer:0,
    translation:"Giới trẻ hiện nay kỳ vọng rằng ngay cả “sự ấm áp” cũng được người khác trao cho, tin rằng mọi thứ sẽ tự đến với mình; khi không đến thì đổ cho đối phương, xung quanh, xã hội, đất nước, kinh tế, vận may, thời đại là xấu. ①“Sự phân tích như vậy” tức là cách phân tích quy nguyên nhân việc không như ý cho thứ khác ngoài bản thân.",
    explanation:"①“そのような分析” chỉ việc quy kết nguyên nhân khi mọi việc không như mong đợi cho người khác/xung quanh/xã hội… (tức là bản thân không có lỗi) ⇒ đáp án 1 ✓. 2 (không thể thay đổi xung quanh)・3 (được người khác trao cho)・4 (không liên quan đến mình) không khớp nội dung ① chỉ tới." },
  { id:"b11-8", passage:"", audioUrl:"", question:"65. ②「検索」するのはなぜか。", options:["自分で考えた解決策が正しいか確認できると思っているから","さまざまな情報を使って解決策を生み出せると考えているから","情報を知れば、問題が解決できると思っているから","友達の話より信頼できる情報が得られるから"], answer:2,
    translation:"Vì sao lại ②“tìm kiếm”? — Vì tin rằng chỉ cần biết thông tin là có thể giải quyết được vấn đề.",
    explanation:"Đoạn 3: mọi người tin rằng “知る” (biết) là giải quyết được vấn đề nên ra sức tra cứu trên mạng ⇒ đáp án 3 ✓. 1, 2, 4 không được nêu làm lí do." },
  { id:"b11-9", passage:"", audioUrl:"", question:"66. 筆者が言いたいことは何か。", options:["検索した情報に頼らずに人とは違う生き方を見つけるべきだ。","周りの人の言葉や情報を生かして自分の問題を解決すべきだ。","自分の問題を解決する方法は自分で考え出すべきだ。","自分に必要な情報を探して問題を解決すべきだ。"], answer:2,
    translation:"Ý tác giả muốn nói: cách giải quyết vấn đề của bản thân (nhất là vấn đề về cách sống) phải do chính mình nghĩ ra, không thể tra cứu mà có.",
    explanation:"Đoạn 4: 「自分の問題を解決する方法は、自分で考え、模索し、新たに編み出さなければならない」 và đoạn cuối nhấn mạnh phải tự mình tìm ⇒ đáp án 3 ✓. 1 (không dựa vào thông tin tra cứu để tìm cách sống khác người)・2・4 đều đề cao việc dựa vào thông tin/người khác — trái ý tác giả." },
]},
{ tab:"読解", section:"問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction:"次のAとBは、旅行について書かれた文章である。AとBの両方を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b12-1", passage:"A<br>旅は準備をする時から始まります。目的地の気候、歴史、文化などについて調べ、どんなことをするか計画を立て、必要な物を準備します。さらに、旅行中に多くのことができるように、無駄のない予定を組み、電車やバスや宿泊場所を予約しておきます。そうすれば、余計なことに時間をとられないで旅を楽しむことができます。<br>旅の楽しみは、その土地の名所を訪ねたり名産品を食べたりして、普段の生活とは違う経験をすることだと思います。旅先では予想外の出来事にあうこともありますが、しっかり準備をしておけば、時間やお金を無駄にせずに、楽しい旅ができるでしょう。<br><br>B<br>私は行きたいと思ったらすぐ旅に出るのが好きです。駅に行き最初に乗れる電車に乗り、降りたい駅で降りて、その土地の人が勧めてくれる旅館やホテルに泊まります。何を食べるか、次の日に何をするか、どこへ行くかも、土地の人に話を聞くのが一番です。そこには、出発前には知らなかった新しい発見があります。また、新しく知り合った人と気が合えば一緒に行動するのも面白いものです。では何が起こるか分かりませんから、状況に合わせて好きなように予定を決めればいいのです。日常では味わえない自由な時間が過ごせ、楽しい旅になります。", audioUrl:"", question:"67. 旅について、AとBはどのように述べているか。", options:["AもBも、しっかり準備をすることが大切だと述べている。","AもBも、準備をしたうえで、状況に合わせて予定を変えるのがいいと述べている。","Aは十分に準備をしたほうがいいと述べ、Bは準備をしなくてもいいと述べている。","Aは準備した計画は変えないほうがいいと述べ、Bは準備をする必要はないと述べている。"], answer:2,
    translation:"A: Chuyến đi bắt đầu từ lúc chuẩn bị — tra cứu khí hậu, lịch sử, văn hóa; lập kế hoạch; đặt tàu xe, chỗ ở để không mất thời gian vô ích. B: Tôi thích xách ba lô lên và đi ngay khi muốn; lên chuyến tàu đầu tiên, xuống ga mình thích, hỏi người địa phương về nơi ăn ở, tùy tình hình mà quyết định lịch trình.",
    explanation:"A: cần chuẩn bị kỹ. B: không cần chuẩn bị, cứ đi rồi tùy cơ ứng biến ⇒ đáp án 3 ✓. 1, 2 sai vì B không nói cần chuẩn bị; 4 sai vì A không nói 'không đổi kế hoạch' và B không phủ nhận việc chuẩn bị theo cách đó." },
  { id:"b12-2", passage:"", audioUrl:"", question:"68. 旅の楽しみについて、AとBはどのように述べているか。", options:["AもBも、その土地の人から話を聞くことだと述べている。","AもBも、日々の生活ではできない経験をすることだと述べている。","Aは無駄のない時間を過ごすことだと述べ、Bは気分転換をすることだと述べている。","Aはその土地でしかできない経験をすることだと述べ、Bは新しい友人を作ることだと述べている。"], answer:1,
    translation:"Về niềm vui của chuyến đi: A nói là trải nghiệm khác với cuộc sống thường ngày (thăm thắng cảnh, ăn đặc sản); B nói có thể trải qua thời gian tự do mà đời thường không có.",
    explanation:"A: 「普段の生活とは違う経験をすること」; B: 「日常では味わえない自由な時間が過ごせ」⇒ cả hai đều nói 'trải nghiệm không thể có trong đời thường' ⇒ đáp án 2 ✓. 1 chỉ đúng với B; 3, 4 không đúng ý cả hai." },
]},
{ tab:"読解", section:"問題13 主張理解・長文",
  instruction:"次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b13-1", passage:"正しい仕事の任せ方というのは、一体どのようなものだろうか。<br><br>理想的なのは、部下の実力よりも少し上のレベルの仕事、部下が何とか自分の力で判断・実行することができ、ときには（注1）小さな失敗を招くであろうレベルの仕事を任せることだ。<br><br>そういう仕事を、段階的にレベルを上げながら与えていくことで、部下は着実に仕事力を磨いていくのだ。<br><br>ところが、そのような仕事を部下に与えたとしても、日本の会社では、「ホウ・レン・ソウ」（報告・連絡・相談）などといって、上司がいちいち部下の仕事に干渉（注2）しがちだ。そして結局は、部下に自分の力でハードル（注3）を乗り越えさせないことが多い。<br><br>たとえば、あるプレゼン資料を部下につくらせるとする。日本の会社の多くの上司は全体像を示さず、ただ「こういうものをつくれ」と部下に曖昧に命じ、持ってこさせる。<br><br>そして「ここをこう直せ」と要求し、部下はその意図がわからないまま上司の指示通りに修正をする。そんなことを何度も繰り返す。その結果、部下に身につくのは、エクセル（注4）やパワーポイントの操作法だけ、ということになる。これでは、レベルの高いプレゼン資料を自分で考え、つくり上げる力はつかないだろう。<br><br>そうではなく、「この資料は、こういう目的で、こういう相手に対して、このように説得するために使用するものだ」という全体像を事前に明確に説明すべきだ。<br><br>その上で、見本を見せて、あとは部下の創意工夫（注5）に任せ、部下が最善だと思う資料ができるまで口出しはしない（注6）ことだ。<br><br>結果的に出来上がるものが、上司の想定するものと違うこともあるだろう。しかし、その資料をつくる意図、全体像がつかめていれば、なぜいけないのか、どこが悪いのか、どう修正すればよくなるのかがわかるし、上司からの修正指示に納得もできるし、学ぶこともできる。<br><br>部下は、「いや、そういう目的なら、自分だったらこうするけどな…」と思うかもしれない。それならそれでいいのだ。そういうことを積み重ねながら、最終的には、部下は自分なりの仕事のやり方を確立（注7）していくはずだ。上司では考えられなかったようなレベルの高い資料をつくることも、いずれはあるかもしれない。<br><br>繰り返すが、「部下を教育するのが上司の役目」というのは間違っている。部下を育てるのは「仕事」そのものであり、その仕事をするための「場を与える」のが上司の役目なのである。<br><br>（注1）ときには：場合によっては<br>（注2）干渉する：ここでは、必要以上に関わる<br>（注3）ハードル：障害<br>（注4）エクセルやらパワーポイント：コンピュータのソフト<br>（注5）創意工夫：新しいアイデアや工夫<br>（注6）口出しはしない：ここでは、何も言わない<br>（注7）確立する：ここでは、しっかり身につける", audioUrl:"", question:"69. 「そういう仕事」とはどのような仕事か。", options:["上司の助けがあれば、大きな失敗をしないような仕事","部下が自身の力で問題なくできるような仕事","失敗する可能性があっても、部下自身がしたいと思うような仕事","実力を超えているが、部下自身で最後までできるような仕事"], answer:3,
    translation:"Bài luận bàn về cách giao việc đúng đắn. Lý tưởng là giao cho cấp dưới công việc khó hơn thực lực một chút, họ có thể tự phán đoán/thực hiện, đôi khi có thể mắc sai sót nhỏ. Nhưng ở công ty Nhật, cấp trên hay can thiệp nên cấp dưới không tự vượt qua được thử thách. Đúng ra phải nêu rõ bức tranh toàn cảnh, cho xem mẫu rồi để cấp dưới tự sáng tạo, không xen vào cho đến khi họ làm ra sản phẩm tốt nhất của mình. Nuôi dưỡng cấp dưới là chính “công việc”, và vai trò của cấp trên là “tạo sân chơi” cho công việc đó.",
    explanation:"「そういう仕事」 chỉ đoạn ngay trước: 部下の実力より少し上で、自分で判断・実行でき、時に小さな失敗を招くレベル ⇒ đáp án 4 'vượt thực lực nhưng cấp dưới tự làm được đến cùng' ✓. 1 (có cấp trên giúp)・2 (làm được không vấn đề)・3 (cấp dưới muốn làm) sai." },
  { id:"b13-2", passage:"", audioUrl:"", question:"70. 筆者によると、上司が部下にプレゼン資料を作成させるときに大切なことは何か。", options:["事前に見本を見せて、部下のわからない部分を教えること","事前に全体像を示したら、あとは部下に任せること","部下のアイデアを取り入れた上で、最善の方法を指示すること","最初から完成まで何も言わず、自分のやり方でさせること"], answer:1,
    translation:"Theo tác giả, khi cho cấp dưới làm tài liệu thuyết trình, điều quan trọng là gì? — Nêu rõ bức tranh toàn cảnh trước, sau đó giao phó cho cấp dưới.",
    explanation:"Đoạn giữa: 事前に全体像を明確に説明 + 見本を見せてあとは部下の創意工夫に任せ、最善の資料ができるまで口出ししない ⇒ đáp án 2 ✓. 1 (dạy phần chưa hiểu)・3 (chỉ đạo cách tốt nhất)・4 (không nói gì từ đầu đến cuối) sai." },
  { id:"b13-3", passage:"", audioUrl:"", question:"71. 筆者によると、上司としてするべきことは何か。", options:["部下が仕事を通して成長できるような状況をつくること","部下が最終的に自身の力で仕事ができるように教育すること","部下が上司を追い越せるようなレベルになるまで育てること","部下が上司の仕事のやり方を学べるような環境を整えること"], answer:0,
    translation:"Theo tác giả, cấp trên nên làm gì? — Tạo ra tình huống để cấp dưới có thể trưởng thành thông qua công việc.",
    explanation:"Câu cuối: 「部下を育てるのは『仕事』そのものであり、その仕事をするための『場を与える』のが上司の役目」⇒ đáp án 1 'tạo tình huống để cấp dưới trưởng thành qua công việc' ✓. 2 (giáo dục để tự làm được)・3 (nuôi đến mức vượt cấp trên)・4 (sắp xếp môi trường học cách làm của cấp trên) không đúng trọng tâm." },
]},
{ tab:"読解", section:"問題14 情報検索",
  instruction:"右のページは、ある市の駐輪場の利用案内である。下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b14-1", passage:"2020年度竹本駅周辺駐輪場（自転車）の定期利用のご案内<br><br>2020年4月から2021年3月までの竹本駅周辺駐輪場の定期利用の申請を受け付けます。<br><br>年間定期利用料金<br>駐輪場：市民の方（一般／高校生以下）／市民以外の方（一般／高校生以下）／設備<br>A 竹本駅東駐輪場：6,000円／4,000円／8,000円／5,000円／屋根あり・管理人なし<br>B 竹本駅西駐輪場：5,500円／3,500円／7,500円／4,500円／屋根あり・管理人なし<br>C 谷山通り駐輪場：7,000円／5,000円／9,000円／6,000円／屋根あり・管理人あり<br>D 東町駐輪場：7,000円／5,000円／9,000円／6,000円／屋根あり・管理人あり<br>E 池中駐輪場：5,500円／3,500円／7,500円／4,500円／屋根なし・管理人あり<br><br>市民は以下の①～③のいずれかに当てはまる方です。<br>①竹本市にお住まいの方　②竹本市に通勤されている方　③竹本市に通学されている方<br><br>【申し込み期間】継続して利用される方：2020年1月6日から1月31日まで<br>初めて利用される方：2020年2月3日から2月28日まで<br>【申し込み窓口】A、B：駐輪場センター［竹本駅前］（受付：午前8時～午後6時）<br>C～E：各駐輪場の管理人室（受付：午前7時～午後9時）<br>【申し込み方法】<br>指定の申込み窓口で申請書をご提出ください。ご提出の際には、身分証明証（高校生以下の方は学生証）をご提示ください。<br>現在、定期利用中で来年度も継続して申請をされる方は、登録証を更新しますので現在利用中の登録証もお持ちください。<br>【支払い】<br>3月13日までに指定の金融機関で利用料金をお支払いください。<br>竹本市役所交通課電話：041-551-8754", audioUrl:"", question:"72. 竹本市にある会社に勤めているヨランダさんは、駐輪場の定期利用を申請したいと思っている。屋根があって、管理人がいる駐輪場がいい。ヨランダさんの希望に合う駐輪場はどれで、払うことになる料金はいくらか。", options:["Bの5,500円か、CかDの7,000円","CかDの7,000円","CかDの9,000円","CかDの9,000円か、Eの7,500円"], answer:1,
    translation:"Chị Yolanda làm việc ở một công ty trong thành phố Takemoto, muốn xin dùng gửi xe định kỳ. Chị muốn nơi có mái che và có người quản lý. Bãi xe nào hợp nguyện vọng và giá phải trả là bao nhiêu? — C hoặc D, 7,000 yên.",
    explanation:"屋根あり・管理人あり là C và D (loại B, E). Chị làm việc ở 竹本市 nên tính là 市民 ⇒ giá 市民一般 = 7,000円 ⇒ đáp án 2 ✓. 1 (B/E không hợp điều kiện)・3 (9,000円 là giá người ngoài thành phố)・4 (E không có mái che) sai." },
  { id:"b14-2", passage:"", audioUrl:"", question:"73. タンさんは、現在、「竹本駅東駐輪場」を定期利用している。2020年4月からも継続して利用したい場合、どのように申し込まなければならないか。", options:["1月6日から1月31日の間に竹本駅東駐輪場の管理人室に行き、申請書を提出し、身分証明証を提示する。","1月6日から1月31日の間に竹本駅東駐輪場の管理人室に行き、申請書、登録証を提出し、身分証明証を提示する。","1月6日から1月31日の間に駐輪場センターに行き、申請書、登録証を提出し、身分証明証を提示する。","2月3日から2月28日の間に駐輪場センターに行き、申請書、登録証を提出し、身分証明証を提示する。"], answer:2,
    translation:"Anh Tan hiện đang dùng gửi xe định kỳ ở “Bãi xe phía Đông ga Takemoto”. Muốn tiếp tục dùng từ tháng 4/2020 thì phải xin như thế nào? — Trong khoảng 6/1 đến 31/1, đến Trung tâm bãi đỗ xe, nộp đơn, giấy đăng ký và xuất trình giấy tờ tùy thân.",
    explanation:"竹本駅東駐輪場 là A ⇒ 窓口 là 駐輪場センター (loại 1, 2 vì nói 管理人室). 継続 ⇒ 1月6日～1月31日 (loại 4). 継続申請 cần 申請書＋登録証＋身分証明証 ⇒ đáp án 3 ✓." },
]},

/* ================= TAB 5: 聴解 ================= */
{ tab:"聴解", section:"問題1 課題理解",
  instruction:"問題1では、まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c1-1", passage:"【台本】男の人と女の人が話しています。男の人はこの後何をしますか。<br><br>男：佐藤さん、僕、来週引っ越すんだけど、今使っている冷蔵庫がいらなくなったんだ。それで、もらってくれる人を探しているんだけど、誰か知らない?<br>女：うん…ちょっと心当たりないなあ。<br>男：そっか。冷蔵庫って、確か粗大ごみとしては出せないんだよね。<br>女：うん、法律で、いらなくなった冷蔵庫を出す時は、手続きをすることになってるよね。<br>男：そっか。手続きって、どこでするの。<br>女：市役所に連絡してもいいけど、引っ越し会社によっては、事前に言っておけば、手続きをしてくれて、引っ越し当日、冷蔵庫の回収もしてくれるって聞いたことあるよ。<br>男：えっ。そうなんだ。<br>女：そのほうが簡単だから、聞いてみたら?来週まで、時間もないでしょう。<br>男：わかった。ありがとう。", audioUrl:"", question:"1番：男の人はこの後何をしますか。", options:["冷蔵庫を友達にあげる","冷蔵庫を粗大ごみとして出す","市役所で手続きをする","引っ越し会社に問い合わせる"], answer:3,
    translation:"Người đàn ông sắp chuyển nhà, muốn cho đi chiếc tủ lạnh. Người phụ nữ gợi ý nên hỏi công ty chuyển nhà — họ có thể lo thủ tục và thu hồi tủ lạnh trong ngày chuyển nhà.",
    explanation:"Đáp án 4. 「引っ越し会社によっては…手続きをしてくれて…回収もしてくれるって聞いたことある」「聞いてみたら?」⇒ anh ấy sẽ liên hệ công ty chuyển nhà ⇒ ④. ① không tìm được người nhận, ② không vứt được như rác cỡ lớn, ③ người phụ nữ chỉ nói 'cũng được' nhưng đề xuất công ty chuyển nhà." },
  { id:"c1-2", passage:"【台本】日本語学校で、先生が話しています。学生はこの後、スピーチの原稿をどう直しますか。<br><br>女：先週提出してもらったスピーチの原稿を返します。はじめのところに自己紹介を入れてもらいましたが、皆さんよく書けていました。スピーチの内容もそれぞれとても面白かったです。授業で勉強したように、難しい言葉には説明をつけて、分かりやすくしていたのも良かったんですが、皆さん、文と文をつなぐ表現がほとんど使われていませんでした。不自然に感じるので、今から見直して入れてみましょう。そのほかの点については、それぞれコメントを入れました。全体的な長さは今は考えなくてもいいですよ。", audioUrl:"", question:"2番：学生はこの後、スピーチの原稿をどう直しますか。", options:["自己紹介を入れる","難しい言葉に説明を加える","文をつなぐ言葉を追加する","全体的に短くする"], answer:2,
    translation:"Giáo viên trả lại bản thảo bài phát biểu; tự giới thiệu và giải thích từ khó đã tốt, nhưng hầu như chưa dùng từ nối giữa câu nên cần xem lại và thêm vào. Độ dài tổng thể chưa cần bận tâm.",
    explanation:"Đáp án 3. 「文と文をつなぐ表現がほとんど使われていませんでした…今から見直して入れてみましょう」⇒ thêm từ nối ⇒ ③. ①② đã làm tốt, ④ 先生 nói 'chưa cần nghĩ đến độ dài'." },
  { id:"c1-3", passage:"【台本】デパートの洋服売り場で、店の人と男の人が話しています。店の人はズボンの裾をどのように仕上げますか。<br><br>店の人：お客様、そちらのズボン、はいてみていかがですか。<br>男：ああ、ちょうどいいです。ただ裾が少し長いので、短くしてもらえますか。<br>店の人：かしこまりました。では、長さを確認いたします。<br>男：あのう、今これは裾が内側に折ってあるんですけど、外側に折るようにしてもらえますか。売り場に飾ってあったのみたいに。<br>店の人：あ、はい。<br>男：できますか。よかった。で、売り場にあったのは、折ったところをボタンで留めるようになってましたが、糸で留めてもらいたいんです。<br>店の人：ボタンですと、留めたりはずしたりしやすいので、汚れなどのお手入れがしやすいですよ。<br>男：うん、僕には必要ないかな。<br>店の人：承知しました。では、そのように。", audioUrl:"", question:"3番：店の人はズボンの裾をどのように仕上げますか。", options:["内側に折り、ボタンで留める","内側に折り、糸で留める","外側に折り、ボタンで留める","外側に折り、糸で留める"], answer:3,
    translation:"Khách muốn lên gấu quần: gấp ra ngoài (thay vì gấp vào trong như hiện tại) và cố định bằng chỉ (chứ không phải bằng cúc).",
    explanation:"Đáp án 4. 「外側に折るようにしてもらえますか」+「糸で留めてもらいたいんです」⇒ gấp ngoài, dùng chỉ ⇒ ④. ①② gấp trong (sai), ③ dùng cúc (khách đã từ chối)." },
  { id:"c1-4", passage:"【台本】会社で、女の人と男の人が話しています。男の人はこの後まず何をしなければなりませんか。<br><br>女：田中さん、新製品の発売に合わせて行うイベント、あれ、やることが確定したから、準備始めてくれる。<br>男：はい、わかりました。<br>女：今回は、社長に挨拶をお願いしてあるから、社長が来られる日でないといけないの。秘書課に予定を聞いてくれ。候補の日を絞らないといけないから。<br>男：はい、日にちが決まったら、会場を予約しますね。参加者は何人ぐらいになるでしょうか。<br>女：100人ぐらいかな。営業部が今、招待客の名簿を作ってるところなんだけど。<br>男：じゃ、会場を予約するのは名簿ができてからですね。<br>女：うん。", audioUrl:"", question:"4番：男の人はこの後まず何をしなければなりませんか。", options:["社長の予定を確認する","イベントの候補日を出す","会場を予約する","招待する人の名簿を作る"], answer:0,
    translation:"Người nữ giao anh chuẩn bị sự kiện; vì phải nhờ giám đốc phát biểu nên phải chọn ngày giám đốc có thể đến — bảo anh hỏi phòng thư ký về lịch của giám đốc để thu hẹp ngày ứng viên.",
    explanation:"Đáp án 1. 「秘書課に予定を聞いてくれ。候補の日を絞らないといけないから」⇒ việc đầu tiên là xác nhận lịch của giám đốc ⇒ ①. ② làm sau khi hỏi lịch; ③ chỉ đặt sau khi có danh sách; ④ do phòng kinh doanh làm." },
  { id:"c1-5", passage:"【台本】アパートの入り口で、男の管理人と女の学生が話しています。女の学生は明日の朝まず何をしなければなりませんか。<br><br>男：あ、李さん、おはようございます。掲示板にお知らせをしておいたんですけど、明日の土曜日、大丈夫ですか。<br>女：えっ、明日、何かあるんですか。すみません、掲示板ちゃんと読んでなくて。<br>男：自転車置き場のペンキを塗りなおすんですよ。ついでに、自転車置き場の掃除もするんです。<br>女：ああ、そうなんですか。すみません、明日はちょっと時間がなくて。<br>男：ああ、いえ。自転車をアパートの前の駐車場に移動してほしいんです。今日はまだ駐車場が使えないから、明日の朝七時から十時の間にお願いします。<br>女：ああ、一緒にペンキを塗るのかと思っちゃいました。<br>男：はは、それはプロに頼んでありますよ。明日の朝、大丈夫そうですか。無理なら、私がやっておきますが。<br>女：はい。出かける前にできます。<br>男：お願いします。動かしたら、すみませんが、鍵は私に預けてください。自転車はこちらで戻しておきますから。<br>女：わかりました。", audioUrl:"", question:"5番：女の学生は明日の朝まず何をしなければなりませんか。", options:["ペンキぬりを手伝う","自転車置き場のそうじをする","自分の自転車を駐車場に運ぶ","自転車の鍵を預ける"], answer:2,
    translation:"Người quản lý dặn nữ sinh sáng mai (7–10 giờ) chuyển xe đạp của mình ra bãi đỗ trước khu nhà (vì sơn lại bãi để xe); sau khi chuyển thì gửi chìa khóa cho ông.",
    explanation:"Đáp án 3. 「自転車をアパートの前の駐車場に移動してほしい…明日の朝七時から十時の間にお願いします」⇒ việc đầu tiên là dời xe đạp ⇒ ③. ① sơn xe là việc của thợ chuyên, ② dọn bãi do người khác, ④ gửi chìa khóa là việc sau khi đã dời xe." },
]},
{ tab:"聴解", section:"問題2 ポイント理解",
  instruction:"問題2では、まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c2-1", passage:"【台本】男の人と女の人がプリンターについて話しています。女の人は今使っているプリンターを選んだ理由は何だと言っていますか。<br><br>男：中山さん、この間プリンター買ったって言ってたよね、うちのプリンター、急に壊れちゃって、新しいの買わないといけないんだけど、参考までにどうやって決めたのか教えてもらえない?<br>女：そうだね。最近のプリンターは写真をすごくきれいに印刷できるし、インクの容量も大きいし、すごいなって思った。コピーやファックスの機能も付いてたりして、便利になってるし。<br>男：うん。<br>女：私が買ったのは印刷スピードが速いっていうのが一番の特徴だったんだけど。私は文字を取り込む機能があるのがいいなあって思ったんだ。<br>男：文字を取り込む?<br>女：うん。紙の書類を電子データとして、パソコンに保存したい時ってあるでしょう。そんな時に便利なんだ。いちいち手で打ち直さなくていいし。<br>男：えっ、そうなの。すごいね。", audioUrl:"", question:"1番：女の人は今使っているプリンターを選んだ理由は何だと言っていますか。", options:["写真がきれいに印刷できるから","インクの容量が大きいから","印刷のスピードが速いから","紙の書類を電子データにできるから"], answer:3,
    translation:"Người đàn ông hỏi vì sao chị中山 chọn chiếc máy in đó. Chị nói điều chị thấy hay nhất là chức năng quét chữ (文字を取り込む) — tiện khi muốn lưu tài liệu giấy thành dữ liệu điện tử vào máy tính, không phải gõ lại.",
    explanation:"Đáp án 4. 「私は文字を取り込む機能があるのがいいなあって思ったんだ…紙の書類を電子データとして、パソコンに保存したい時に便利」⇒ lý do là có thể chuyển tài liệu giấy thành dữ liệu điện tử ⇒ ④. ①②③ là đặc điểm chung chị ca ngợi nhưng không phải lý do chị chọn." },
  { id:"c2-2", passage:"【台本】会社で、女の人と男の人が話しています。男の人は何が一番うれしいと言っていますか。<br><br>女：田中さん、田中さんの企画した新商品、先月の売り上げ1位でしたね。おめでとうございます。<br>男：たまたまだよ。<br>女：部長も喜んでいらっしゃいましたよ。<br>男：そう。企画の時から、自由にやらせてもらったからね。実は、この間、大学時代の友人と話していたら、この商品のことをすごくいいねって言ってくれたんだよ。作ってる側からすると、知ってる人からこう言ってもらえるのはどんな言葉よりうれしいよね。これからも頑張らなきゃって思うよ。<br>女：よかったですね。次の企画も私たちみんな、期待しています。<br>男：うわ。プレッシャー大きいなあ。", audioUrl:"", question:"2番：男の人は何が一番うれしいと言っていますか。", options:["企画した商品の売り上げが1位になったこと","自由に仕事をさせてくれたこと","企画した商品を知人がほめてくれたこと","次の企画への期待が高いこと"], answer:2,
    translation:"Anh田中 nói điều khiến anh vui nhất là khi trò chuyện với người bạn đại học, bạn khen sản phẩm do anh lên ý tưởng — 'được người quen khen là hơn cả mọi lời nói'.",
    explanation:"Đáp án 3. 「知ってる人からこう言ってもらえるのはどんな言葉よりうれしいよね」⇒ được người quen khen sản phẩm mình làm ⇒ ③. ① anh chỉ nói 'たまたまだ'; ② chỉ là điều kiện làm việc; ④ là áp lực chứ không phải niềm vui." },
  { id:"c2-3", passage:"【台本】放課後の子どものための教室で、男の学生と係りの人が話しています。係りの人はどんな人にボランティアに来てほしいと言っていますか。<br><br>男：すみません、こちらの教室で夏休みの間のボランティアスタッフを募集しているって聞いたんですが。この教室って、どんなことするんですか。<br>係りの人：ああ、小学生の子どもたちが放課後、一緒に遊んだり、宿題をしたりするんです。夏休みは、普段より子どもが増えるので、募集してるんですが。ボランティアご希望ですか。<br>男：興味あるんですが。こういうボランティアやったことないんです。大丈夫でしょうか。<br>係りの人：経験はないよりあったほうがいいですけど、まあ、子どもって、放っておいても、自分で遊ぶものですからね。遊びを教えたりする必要もないですし。<br>男：そうですか。<br>係りの人：それより、子どもの話に耳を傾けてくれる人がいいんです。子どもって自分の話を聞いてもらえたら、それだけでうれしいんですよ。<br>男：へえ。<br>係りの人：算数とか国語とか、勉強を教えられる人はほかにもたくさんいますから。よかったら、一度ぜひ教室に来てみてください。<br>男：はい。ありがとうございます。", audioUrl:"", question:"3番：係りの人はどんな人にボランティアに来てほしいと言っていますか。", options:["この教室でボランティアをしたことがある人","遊びを教えるのが上手な人","子どもの話を聞いてあげられる人","勉強を教えるのが上手な人"], answer:2,
    translation:"Người phụ trách nói mong có người biết lắng nghe trẻ con: 'trẻ con chỉ cần được người khác nghe mình nói là đã vui rồi'.",
    explanation:"Đáp án 3. 「子どもの話に耳を傾けてくれる人がいいんです」⇒ người biết nghe trẻ nói ⇒ ③. ① kinh nghiệm không bắt buộc, ② 'không cần dạy cách chơi', ④ 'người dạy học thì đã có nhiều'." },
  { id:"c2-4", passage:"【台本】日本語のクラスで、留学生が日本での体験についてスピーチをしています。留学生はある店で買い物をしたとき、店員のどんな対応がいやだったと言っていますか。<br><br>女：先日、スニーカーを買いに行きました。店に入るとすぐ、店員さんが声をかけてくれました。それはうれしかったんですが、その後ずっと離れないんです。商品を見ようとすると、丁寧な言葉で説明してくれましたが、近くにいられると気になって、ゆっくり見られませんでした。私の国では、店員は挨拶はしますが、客が質問した時しか近くには来ないんです。ただ、私の国の場合、高い商品をすすめられることが多いんですが、この店では、そんなことはありませんでした。", audioUrl:"", question:"4番：留学生はある店で買い物をしたとき、店員のどんな対応がいやだったと言っていますか。", options:["店に入るとすぐ話しかけてきたこと","買い物の間ずっとそばにいたこと","言葉が難しかったこと","高い商品をすすめできたこと"], answer:1,
    translation:"Du học sinh nói điều khiến cô khó chịu là nhân viên cứ ở mãi bên cạnh suốt lúc mua hàng, khiến cô không thể xem thoải mái. Việc chào hỏi thì cô thấy vui; việc bị giới thiệu hàng đắt thì 'ở cửa hàng này không có'.",
    explanation:"Đáp án 2. 「その後ずっと離れないんです…近くにいられると気になって、ゆっくり見られませんでした」⇒ nhân viên cứ đứng ngay cạnh suốt ⇒ ②. ① cô thấy vui chứ không khó chịu, ③ không được nêu, ④ ngược lại (không bị giới thiệu hàng đắt)." },
  { id:"c2-5", passage:"【台本】図書館で、女の人と男の人が話しています。男の人は図書館へ来る人を増やすために、まずどんなことをしたらいいと言っていますか。<br><br>女：ここ数年、うちの図書館を利用する人が減ってきてるんですが。<br>男：そうだね。少し前に、子供向けに絵本の読み聞かせの会とか図書館ツアーとかやってみたら、効果があったよね。これから対象を子供以外にも広げていったらどうかな。<br>女：大人向けのイベントなら、今までもやってましたよね。<br>男：うん。ただ、これまでは昼間しかやってなかったでしょう。今度は夜の時間にもやってみるとか。これなら、すぐにできるし。<br>女：そうですね。<br>男：うん。とにかくやってみよう。後、将来的には、学習スペースの設備を充実させたり。<br>女：設備?<br>男：うん。机や椅子をいいものに変えて、快適にしたり、パソコンを使う人も多くなってるから、コンセントを増やしたり。<br>女：なるほど。もしそうなったら、積極的に宣伝したいですね。<br>男：そうだね。", audioUrl:"", question:"5番：男の人は図書館へ来る人を増やすために、まずどんなことをしたらいいと言っていますか。", options:["子どものための企画を増やす","大人向けのイベントを夜も行う","学習スペースの設備をよくする","図書館の宣伝のしかたを工夫する"], answer:1,
    translation:"Người đàn ông đề xuất trước tiên tổ chức cả sự kiện cho người lớn vào buổi tối ('việc này làm được ngay'); thiết bị của không gian học tập là chuyện tương lai.",
    explanation:"Đáp án 2. 「大人向けのイベント…これまでは昼間しかやってなかったでしょう。今度は夜の時間にもやってみるとか。これなら、すぐにできるし」⇒ tổ chức sự kiện cho người lớn vào ban đêm ⇒ ②. ① đã làm cho trẻ rồi (mở rộng hơn nữa mới là ý sau), ③ là 'tương lai', ④ không được nêu." },
]},
{ tab:"聴解", section:"問題3 概要理解",
  instruction:"問題3では、問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。（せんたくし được in trong phần 台本 của đề gốc, không in trên tờ đề thi.)",
  questions:[
  { id:"c3-1", passage:"【台本】就職セミナーで、ある航空会社の社員が話しています。<br><br>女：私は飛行機の乗務員をしています。機内でお客様が快適で安全に過ごせるように様々な仕事をします。この仕事は飛行機でいろいろな場所に行けて、魅力的だと思われているようで、就職を希望する学生さんが多いのも事実です。ただ、いい面ばかりではありません。お客様の荷物の上げ下ろしのお手伝いや飲み物、食事のサービスなど休む間もないほどです。また、何かトラブルが起きれば、お客様への対応が求められます。外からはそういうことはなかなか見えにくいと思いますが。", audioUrl:"", question:"1番：社員は何について話していますか。", options:["この仕事の魅力","この仕事の大変さ","この仕事についた理由","この仕事に必要な体力"], answer:1,
    translation:"Trong buổi hội thảo việc làm, một nhân viên hàng không (tiếp viên) nói về công việc. Cô nói công việc này được cho là hấp dẫn, nhưng không chỉ toàn mặt tốt — phải giúp khách nâng hạ hành lý, phục vụ đồ uống/bữa ăn không có lúc nghỉ, và khi có sự cố thì phải ứng phó với hành khách; từ bên ngoài khó thấy được điều đó.",
    explanation:"Đáp án 2. 「ただ、いい面ばかりではありません…休む間もないほどです…お客様への対応が求められます」⇒ chủ yếu nói về sự vất vả của nghề ⇒ ② 大変さ. ① chỉ là phần dẫn, ③④ không được nêu." },
  { id:"c3-2", passage:"【台本】女の人と男の人が男の人が買った車について話しています。<br><br>女：最近、新しい車を買ったんだってね?<br>男：うん、ずっと憧れてた車なんだ。有名なデザイナーがデザインした車で、外見も中も洗練されてて、僕にとっては一流ホテルにいるのと同じような感じなんだ。<br>女：へえ。<br>男：ただ、買うかどうか最後まで悩む値段だったんだけどね。買ってから驚いたんだけど、乗ってて疲れにくいんだ。視界のよさとか、操作のしやすさとか、運転手の負担を最小限に抑える工夫が効いてて、安全運転にもつながるしね。その意味では安い買い物だったと思ってるよ。", audioUrl:"", question:"2番：男の人は買った車についてどう言っていますか。", options:["値段も安かったし、いい車で満足だ。","値段は高かったが、いい車で満足だ。","安い車なので、性能に不満がある。","高級な車だが、性能に不満がある。"], answer:1,
    translation:"Người đàn ông nói về chiếc xe mới: giá thì đắt đến mức phải đắn đo, nhưng đi không mệt, tầm nhìn tốt, dễ thao tác, nên 'xét theo nghĩa đó là món hời' — tức giá cao nhưng hài lòng.",
    explanation:"Đáp án 2. 「買うかどうか最後まで悩む値段だった」(giá đắt) + 「その意味では安い買い物だった」(đáng tiền) ⇒ giá cao nhưng xe tốt, hài lòng ⇒ ②. ① sai (giá không rẻ), ③④ đều nói '不満' — trái hoàn toàn." },
  { id:"c3-3", passage:"【台本】ラジオで、料理研究家が話しています。<br><br>女：料理を作ったら、食べた人に美味しいと言ってほしいと誰でも思いますよね。ところが、好みは人それぞれで、その好みを形成するものの一つは子供の頃から毎日食べていた家庭料理の味です。家庭だけでなく、学生時代によく通っていた食堂などの慣れ親しんだ味を美味しいと感じることが多いと言われています。ほかにも暑い地域では、汗をかいて体温を下げる効果のある辛い料理が好まれるといった気候によるものなどもあります。", audioUrl:"", question:"3番：料理研究家は何について話していますか。", options:["おいしい料理を作る工夫","子供時代の食事の思い出","家庭料理の味の特徴","味の好みを決める要素"], answer:3,
    translation:"Trên radio, nhà nghiên cứu ẩm thực nói rằng sở thích ăn uống mỗi người khác nhau; một yếu tố hình thành nó là vị của món ăn gia đình thuở nhỏ, hương vị quen thuộc thời đi học, và cả yếu tố khí hậu (xứ nóng thích món cay).",
    explanation:"Đáp án 4. Cả đoạn liệt kê các yếu tố hình thành sở thích (món ăn gia đình, quán quen, khí hậu) ⇒ chủ đề là 'yếu tố quyết định khẩu vị' ⇒ ④. ①②③ chỉ là chi tiết/ví dụ, không phải chủ đề chung." },
  { id:"c3-4", passage:"【台本】テレビで、アナウンサーが作家にインタビューをしています。<br><br>女：今日は今話題の作家山田はじめさんにお話を伺います。どうぞ、よろしくお願いいたします。山田さん、最近若い人の読書離れが進んでいると言われていますが。<br>男：読書っていうのは人生を豊かにしてくれるので、若い人には本を読んでもらいたいですね。ただ個人的には一年に何冊本を読んだとか、そういうことはそれほど大切ではないと思います。<br>女：と言いますと。<br>男：私は若い頃、好きな本をよく汚れてぼろぼろになるまで読んでいましたが、同じ本でも読むたびに違うことを感じて、考えが深まっていったのを覚えています。最近は仕事や人間関係に役立つからといって、実用的な本ばかり宣伝される傾向がありますが、そういう本は何回も読んだりしないですからね。<br>女：ええ。<br>男：若い人にも自分が出会った一冊とじっくり向き合ってほしいですね。", audioUrl:"", question:"4番：作家が言いたいことは何ですか。", options:["好きな本を繰り返し読んでほしい。","なるべく多くの本を読んでほしい。","すぐに役に立つ本を読んでほしい。","宣伝を参考にして本を選んでほしい。"], answer:0,
    translation:"Nhà văn nói: đọc sách làm giàu cuộc sống; cá nhân ông không coi trọng số lượng sách đọc mỗi năm; hồi trẻ ông đọc đi đọc lại cuốn mình thích đến rách nát và mỗi lần đọc lại cảm nhận khác, suy nghĩ sâu hơn; sách thực dụng thì người ta không đọc nhiều lần.",
    explanation:"Đáp án 1. 「同じ本でも読むたびに違うことを感じて…自分が出会った一冊とじっくり向き合ってほしい」⇒ đọc đi đọc lại cuốn mình thích ⇒ ①. ② sai (ông nói số lượng không quan trọng), ③④ trái ý (ông chê sách thực dụng và không khuyên theo quảng cáo)." },
  { id:"c3-5", passage:"【台本】学校で校長先生が話しています。<br><br>男：受験勉強やスポーツの練習など大きな目標に向かっているとき、目標しか見えなくなっていることがあります。そこに向かう道はつらくても仕方がないといやいや取り組んでいたりしませんか。目標を持つことはもちろん大事ですが、ちょっと視点を変えてみましょう。学ぶことや運動すること自体にも喜びがあり、自分の成長につながるはずです。最終的な目標は同じでも、そこにどう辿り着くか、どう取り組むかによって、得られるものも変わってくるかもしれません。", audioUrl:"", question:"5番：校長先生が伝えたいことはどのようなことですか。", options:["目標は自分に合ったものがよい。","目標を持ち続けることが必要だ。","目標に向かうプロセスにも意味がある。","時々目標を見直すことが大事だ。"], answer:2,
    translation:"Hiệu trưởng nói: khi hướng tới mục tiêu lớn, đôi khi chỉ nhìn thấy mục tiêu mà quên rằng bản thân việc học/việc tập luyện cũng có niềm vui và giúp mình trưởng thành; dù mục tiêu cuối cùng giống nhau, cách đi tới và cách nỗ lực khác nhau sẽ đem lại những gì khác nhau.",
    explanation:"Đáp án 3. 'Việc học/tập luyện tự thân cũng có ý nghĩa; cách tiến tới mục tiêu thay đổi những gì ta nhận được' ⇒ nhấn mạnh quá trình hướng tới mục tiêu cũng có ý nghĩa ⇒ ③. ① (mục tiêu phù hợp bản thân)・② (kiên trì mục tiêu)・④ (thỉnh thoảng xem lại mục tiêu) không được nêu." },
]},
{ tab:"聴解", section:"問題4 即時応答",
  instruction:"問題4では、問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c4-1", passage:"【台本】男：うん?会議の資料、この机の上に置いたはずなのに。", audioUrl:"", question:"1番", options:["えっ、ないんですか。","助かります。ありがとうございます。","あっ、机の上に置いてはいけなかったんですね。"], answer:0,
    translation:"“Ơ? Tài liệu cuộc họp đáng lẽ tôi để trên bàn này mà.” ⇒ “Hả, không có à?”",
    explanation:"Đáp án 1. Người nói băn khoăn tài liệu không thấy đâu ⇒ phản hồi phù hợp là ngạc nhiên/xác nhận 「えっ、ないんですか」✓. ② 助かります dùng khi được giúp đỡ, ③ ngụ ý 'đặt trên bàn là sai' — không hợp ngữ cảnh." },
  { id:"c4-2", passage:"【台本】男：田村さん、勧めてくれたから、買いましたよ。小型ながらなかなか高性能ですね。", audioUrl:"", question:"2番", options:["もっと小さいのがよかったんですね。","小さいのに、すごいでしょう。","小さいほうが性能がいいんですか。"], answer:1,
    translation:"“Chị Tamura, vì chị giới thiệu nên tôi đã mua rồi. Tuy nhỏ nhưng hiệu năng khá đấy.” ⇒ “Nhỏ mà giỏi nhỉ.”",
    explanation:"Đáp án 2. Người nói khen 'nhỏ mà hiệu năng cao' ⇒ đồng tình 「小さいのに、すごいでしょう」✓. ① hiểu sai thành 'muốn cái nhỏ hơn', ③ hỏi lại 'cái nhỏ thì tốt hơn à' — không hợp." },
  { id:"c4-3", passage:"【台本】女：今日の自習のレポート、明日出さなきゃいけないなんて。", audioUrl:"", question:"3番", options:["明日までじゃなくてよかったね。","本当、もっと時間ほしいよね。","えっ、レポート出さなくてもよくなったの。"], answer:1,
    translation:"“Báo cáo tự học hôm nay, vậy mà mai phải nộp rồi.” ⇒ “Thật, ước gì có thêm thời gian nhỉ.”",
    explanation:"Đáp án 2. Người nói than phải nộp báo cáo gấp ⇒ đồng cảm 「もっと時間ほしいよね」✓. ① hiểu ngược, ③ hiểu sai (thành 'không phải nộp nữa à')." },
  { id:"c4-4", passage:"【台本】女：あのう、佐藤さん、この椅子、運んでくださると、助かるんですが。", audioUrl:"", question:"4番", options:["運んでいただけるんですか。","えっ、私、運んでませんよ。","あっ、はい、どこへ運びましょうか。"], answer:2,
    translation:"“À, anh Satou, nếu anh khiêng giúp tôi cái ghế này thì tốt quá.” ⇒ “À, vâng, khiêng đi đâu ạ?”",
    explanation:"Đáp án 3. Người nói nhờ khiêng ghế ⇒ nhận lời 「どこへ運びましょうか」✓. ① dùng lại câu nhờ (sai vai), ② phản bác 'tôi không khiêng' — sai ngữ cảnh." },
  { id:"c4-5", passage:"【台本】女：鈴木さん、パーティーの準備は順調?", audioUrl:"", question:"5番", options:["では、さっそく準備を始めます。","中止になるなんて残念です。","今のところうまく行ってます。"], answer:2,
    translation:"“Anh Suzuki, việc chuẩn bị tiệc ổn chứ?” ⇒ “Hiện tại thì đang tiến triển tốt.”",
    explanation:"Đáp án 3. Câu hỏi thăm tình hình ⇒ trả lời tình hình 「今のところうまく行ってます」✓. ①② trả lời lệch câu hỏi (người hỏi không hề nhờ chuẩn bị/không nói đến hủy tiệc)." },
  { id:"c4-6", passage:"【台本】女：昨日愚痴を言っちゃったけど、なかったことにしてくれない?", audioUrl:"", question:"6番", options:["ああ、わかった。忘れるよ。","えっ、ちゃんと聞いてたよ。","もちろん、いつでも聞くよ。"], answer:0,
    translation:"“Hôm qua tôi đã lỡ than vãn, cậu coi như không có được không?” ⇒ “À, hiểu rồi. Tớ sẽ quên đi.”",
    explanation:"Đáp án 1. Người nói xin 'coi như chưa từng nói' ⇒ 「わかった。忘れるよ」✓. ②③ hiểu sai thành chuyện 'có nghe hay không'." },
  { id:"c4-7", passage:"【台本】男：今朝、もう少しでいつもの電車に乗り遅れるところだったよ。", audioUrl:"", question:"7番", options:["そうか。でも間に合ったならよかったね。","ああ、いつものに乗れなかったんだ。","えっ、電車が遅れたんだ。"], answer:0,
    translation:"“Sáng nay suýt chút nữa thì lỡ chuyến tàu quen thuộc rồi.” ⇒ “Vậy à. Nhưng kịp được thì tốt rồi.”",
    explanation:"Đáp án 1. 「もう少しで…乗り遅れるところだった」= suýt thì lỡ (nhưng đã kịp) ⇒ 「間に合ったならよかったね」✓. ② hiểu ngược (tưởng đã không lên được), ③ hiểu sai (thành 'tàu bị trễ')." },
  { id:"c4-8", passage:"【台本】男：伊藤さん、午後の会議の準備、一緒にやることになってるけど、ぼく一人でできないこともないよ。", audioUrl:"", question:"8番", options:["それなら、一緒にやろうか。","えっ、一人でやったの。","じゃあ、お願いしてもいい?"], answer:2,
    translation:"“Chị Itou, việc chuẩn bị cho cuộc họp chiều nay có phân công hai người cùng làm, nhưng một mình tớ cũng không phải là không làm được đâu.” ⇒ “Vậy thì, nhờ cậu được không?”",
    explanation:"Đáp án 3. Người nói gợi ý 'một mình cũng làm được' (ý nhường) ⇒ nên nhờ anh ấy làm một mình 「お願いしてもいい?」✓. ① bỏ qua thiện ý, ② hiểu sai thời (đã làm rồi à)." },
  { id:"c4-9", passage:"【台本】女：藤田さん、スピーチの練習、付き合ってくださってありがとうございました。当日もうまく行くといいんですけど。", audioUrl:"", question:"9番", options:["うまく行ったんだ。頑張った甲斐があったね。","仕方ないよ。そんなにがっかりしないで。","きっと練習の成果を出せると思うよ。"], answer:2,
    translation:"“Anh Fujita, cảm ơn anh đã luyện tập bài phát biểu cùng tôi. Mong rằng hôm đó sẽ suôn sẻ.” ⇒ “Chắc chắn sẽ phát huy được kết quả luyện tập thôi.”",
    explanation:"Đáp án 3. Người nói mong buổi chính sẽ suôn sẻ ⇒ động viên 「きっと練習の成果を出せると思うよ」✓. ① hiểu sai (thành đã thành công rồi), ② an ủi khi thất bại — sai ngữ cảnh." },
  { id:"c4-10", passage:"【台本】男：パーティーの打ち合わせ、5番教室でやるって聞いたけど、教室は予約してからでないと使えないよ。", audioUrl:"", question:"10番", options:["予約は必要ないんですね。","先週、予約しました。","せっかく予約したのに使えないんですか。"], answer:1,
    translation:"“Nghe nói buổi họp bàn tiệc sẽ làm ở phòng số 5, nhưng phòng phải đặt trước mới dùng được.” ⇒ “Tuần trước tôi đã đặt rồi.”",
    explanation:"Đáp án 2. Người nói nhắc 'phải đặt trước' ⇒ phản hồi phù hợp là 'đã đặt rồi' ✓. ① hiểu ngược (bảo không cần đặt), ③ hiểu sai (thành 'đã đặt mà không dùng được')." },
  { id:"c4-11", passage:"【台本】男：吉田さん、吉田さんの企画書だけど、データなしじゃ検討しようがないよ。", audioUrl:"", question:"11番", options:["すみません。すぐ用意します。","あっ、検討していただけるんですね。","ええ、ご理解ありがとうございます。"], answer:0,
    translation:"“Chị Yoshida, bản kế hoạch của chị, không có dữ liệu thì không thể xem xét được.” ⇒ “Xin lỗi. Tôi sẽ chuẩn bị ngay.”",
    explanation:"Đáp án 1. Người nói chỉ ra thiếu dữ liệu ⇒ cần xin lỗi và khắc phục 「すみません。すぐ用意します」✓. ② bám vào '検討していただける' mà bỏ qua lời phê, ③ 「ご理解ありがとう」 sai ngữ cảnh." },
]},
{ tab:"聴解", section:"問題5 統合理解",
  instruction:"問題5では長めの話を聞きます。この問題には練習はありません。メモをとってもかまいません。",
  questions:[
  { id:"c5-1", passage:"【台本】市の体育館の受付で女の人と男の職員が話しています。<br><br>女：すみません。何か軽い体操でもはじめたいと思ってるんですが。こちらでそういう教室はやってますか。<br>男：はい。いろいろありますよ。時間や内容のご希望はございますか。<br>女：ええと、平日の午前中で、運動が苦手な私でも続けられそうな教室がいいんですけど。通ってらっしゃる他の方とも親しくなれるような雰囲気の。<br>男：そうですね。軽い体操というと。火曜九時半からのボール体操。これは直径50センチぐらいのボールに座って体操をします。<br>女：ああ。<br>男：それから水曜10時からの柔軟体操。体をゆっくり動かして、手足を伸ばします。こちらのクラスは時々参加者の皆さんで交流会をやっているみたいです。<br>女：へえ、いいですね。<br>男：それから、木曜10時からのリズム運動。音楽を流して、それに合わせて運動をします。仲のいいクラスで、去年の秋には皆さんで近くにハイキングに出かけてましたよ。<br>女：その教室、この間テレビで紹介してましたよね。音楽に合わせて体操するの、楽しそうでしたけど。皆さん、汗びっしょりでした。<br>男：あっ、ご覧になったんですね。かなり体を動かすので、いい運動になりますよ。あとは、土曜の午前なんですが、筋肉トレーニングもあります。講師からいろんなトレーニング器具の使い方を教わりながら、筋肉を鍛えるクラスです。<br>女：迷いますね。でも、やっぱり週末はあけておきたいんですよね。あんまり激しい運動だと、できるかどうか自信がないし、教室以外にも仲良くなる機会があるほうがいいなあ。ええと、こちらの教室、見学できますか。", audioUrl:"", question:"1番：女の人はどの教室を見学したいと言っていますか。", options:["ボール体操","柔軟体操","リズム運動","筋肉トレーニング"], answer:1,
    translation:"Người phụ nữ muốn tìm lớp thể dục nhẹ: buổi sáng ngày thường, dễ duy trì, có không khí để làm thân với người khác; muốn để cuối tuần trống, không thích vận động quá mạnh, mong có cơ hội giao lưu ngoài giờ học.",
    explanation:"Đáp án 2. Cô loại 筋肉トレーニング (thứ Bảy) vì muốn để cuối tuần trống; loại リズム運動 vì 'かなり体を動かす' (quá mạnh); ボール体操 không có cơ hội giao lưu. 柔軟体操 có 交流会 ⇒ ② 柔軟体操 ✓." },
  { id:"c5-2", passage:"【台本】大学で、大学祭の係の学生三人が話しています。<br><br>女1：大学祭まであと一か月だね。去年の参加者のアンケートで、ごみ箱の場所がわかりにくかったっていう声が多かったけど。今年どうしたらいいかまだ決めてなかったね。<br>男：あちこちにゴミが捨てられてね。来場者に配る会場案内のチラシにごみ箱の場所も書いておいたんだけど。チラシの数が足りなかったかなあ。<br>女2：チラシは余ってたよ。<br>男：じゃあ、チラシが見にくかったかなあ。もう少し字を大きくして見やすくしたらどうかなあ。<br>女2：でも、お客さんは食べ物や荷物を持って移動するわけだよね。チラシまで見ながら歩くのは難しいんじゃない?<br>女1：そうだね。うん、去年は、会場内に「ごみ箱はここです」っていう看板も立てたよね。設置場所も問題なさそうだったけど。<br>女1：うん。看板の文字も大きくてかなり目立ってたはずなんだけど。<br>男：込んでからね。行列もあちこちにできてたし。<br>女2：それで見えにくかったのかもしれないね。それなら、今年はもう少し高さがあるものにしてみようか。目につきやすいように。<br>女1：うん。なるほど。それがいいね。<br>男：で、チラシは今年はどうする。見てもらえないなら配るのをやめる?<br>女1：見る人は見るから、あったほうがいいと思う。去年ので十分見やすくできてたと思うから、あれを使おう。", audioUrl:"", question:"2番：問題解決のために、何をすることにしましたか。", options:["チラシの文字を大きくする。","配るチラシの数を増やす。","看板の文字を大きくする。","看板の高さを高くする。"], answer:3,
    translation:"Ba sinh viên bàn về việc khó tìm chỗ đặt thùng rác ở lễ hội trường. Cuối cùng quyết định làm biển (看板) cao hơn để dễ thấy; còn tờ rơi thì giữ nguyên và dùng lại tờ năm ngoái.",
    explanation:"Đáp án 4. 「今年はもう少し高さがあるものにしてみようか。目につきやすいように」⇒ làm biển cao hơn ⇒ ④. ①② tờ rơi đã loại (số lượng đủ, chữ vẫn ổn), ③ chữ trên biển đã to sẵn nên không phải vấn đề." },
  { id:"c5-3", passage:"【台本】テレビでアナウンサーが使われなくなった学校の校舎の再活用について話しています。<br><br>（アナウンサー）生徒数が減り、廃止になった学校、その校舎の一部を有効活用する取り組みが各地で行われています。今日はその中から四つご紹介します。まず、山の中の小さな学校、東小学校は、今宿泊施設として活用されています。豊かな自然の中で山歩きや川遊びを楽しめます。二つ目の西田市にある西中学校は、地域のイベントやコンサート、展覧会などに広く使われています。2階は映画館になっていて、昭和時代の雰囲気が残っています。それから海に面した南小学校には、手作りのパンやアクセサリー作品の店が並んでいます。自分で作ったものを販売したいという若い人が集まってきています。ええ、四つ目の農村地域にある北中学校は食堂になっています。地元でとれた新鮮な野菜をたくさん使ったメニューが人気です。<br><br>男：今映ってた学校で、友達が今度作品を発表するんだ。<br>女：へえ、友達、何か作って売ってるの。<br>男：え、あ、その学校じゃなくて、その友達自分で映画を撮っててね。見に行くことになってるんだ。<br>女：そうなんだ。私は一度でいいから、学校に泊まってみたかったんだよね。今度の夏休みに山登りのついでにみんなで行ってみない?<br>男：えっ、夜の学校なんて真っ暗で怖そうじゃない?おいしいごはんを食べるんだったらいつでも喜んで行くけど。<br>女：今は学校じゃないんだから大丈夫だよ。", audioUrl:"", question:"3番・質問1：男の人はどの学校に行くつもりだと言っていますか。", options:["東小学校","西中学校","南小学校","北中学校"], answer:1,
    translation:"Chương trình giới thiệu 4 ngôi trường cũ được tái sử dụng: 東小学校→nhà nghỉ; 西中学校→sự kiện/hội trường, tầng 2 là rạp chiếu phim; 南小学校→cửa hàng đồ thủ công; 北中学校→quán ăn. Người nam nói đi xem phim của bạn (bạn tự quay phim) ⇒ đến trường có rạp chiếu phim = 西中学校.",
    explanation:"Đáp án 2. Người nam nói bạn anh ấy tự quay phim và anh ấy sẽ đi xem; chỉ 西中学校 có 映画館 (rạp phim) ⇒ ② 西中学校 ✓. ① là nhà nghỉ, ③ là cửa hàng, ④ là quán ăn." },
  { id:"c5-4", passage:"", audioUrl:"", question:"3番・質問2：女の人はどの学校に行きたいと言っていますか。", options:["東小学校","西中学校","南小学校","北中学校"], answer:0,
    translation:"Câu hỏi 2: Người nữ nói muốn đến trường nào? — Cô nói 'muốn được ở lại qua đêm tại trường một lần' ⇒ trường dùng làm nhà nghỉ = 東小学校.",
    explanation:"Đáp án 1. 「私は一度でいいから、学校に泊まってみたかったんだよね」⇒ muốn ngủ lại ở trường ⇒ chỉ 東小学校 là 宿泊施設 (nhà nghỉ) ⇒ ① 東小学校 ✓." },
]},
	]
	}
);



