/* =========================================================================
   data_2021_12.js — JLPT N2 2021年12月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   Nguồn: pdf_data/2021_12.pdf (bản scan 30 trang, có kèm bảng đáp án + giải thích).
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2021_12", label:"12/2021", title:"JLPT N2 — 2021年12月 (12/2021)", file:"data_2021_12.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{ tab:"文字・語彙", section:"問題1 漢字読み",
  instruction:"＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a1-1", passage:"", audioUrl:"", question:"1. 美しい<u>情景</u>が目に浮かんだ。", options:["じょうけい","じょけい","じょうえい","じよえい"], answer:0,
    translation:"Khung cảnh đẹp hiện lên trong mắt tôi.",
    explanation:"情景 = じょうけい: phong cảnh, khung cảnh, tình cảnh. じょけい (女系: mẫu hệ)・じょうえい (上映: chiếu phim)・じよえい là các âm đọc sai." },
  { id:"a1-2", passage:"", audioUrl:"", question:"2. この世代の人たちはコンピューターの知識が<u>乏しい</u>ように思う。", options:["くわしい","とぼしい","まずしい","あやしい"], answer:1,
    translation:"Tôi nghĩ rằng thế hệ này có vẻ thiếu kiến thức về máy tính.",
    explanation:"乏しい = とぼしい: khan hiếm, thiếu thốn. くわしい (詳しい: chi tiết, am hiểu)・まずしい (貧しい: nghèo)・あやしい (怪しい: đáng ngờ) đều sai." },
  { id:"a1-3", passage:"", audioUrl:"", question:"3. ボランティアでお年寄りの<u>介護</u>をしている。", options:["かいごう","かんごう","かいご","かんご"], answer:2,
    translation:"Tôi đang chăm sóc người già với tư cách tình nguyện viên.",
    explanation:"介護 = かいご: việc chăm sóc (người già, người tàn tật). かいごう (会合: cuộc họp)・かんごう (勘合: đối chiếu)・かんご (看護: điều dưỡng) sai." },
  { id:"a1-4", passage:"", audioUrl:"", question:"4. 今ごろになって<u>焦って</u>もしかたない。", options:["あせっても","しかっても","まよっても","いのっても"], answer:0,
    translation:"Đến giờ này mới sốt ruột thì cũng vô ích.",
    explanation:"焦る = あせる: sốt ruột, nóng lòng ⇒ あせっても. しかっても (叱っても: dù có mắng)・まよっても (迷っても: dù có lưỡng lự)・いのっても (祈っても: dù có cầu nguyện) sai nghĩa." },
  { id:"a1-5", passage:"", audioUrl:"", question:"5. 高速道路の建設については、<u>賛否</u>が分かれた。", options:["さんふ","さんぶ","さんひ","さんぴ"], answer:3,
    translation:"Về việc xây dựng đường cao tốc, ý kiến tán thành và phản đối đã chia rẽ.",
    explanation:"賛否 = さんぴ: tán thành hay không, đồng ý và phản đối. さんふ・さんぶ (散布: rải rác)・さんひ đều sai. ⚠️ Đề gốc in nhầm tiêu đề 問題2 (giống 問題1) — đúng ra phải là「漢字で書くとき」." },
]},
{ tab:"文字・語彙", section:"問題2 表記",
  instruction:"＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a2-1", passage:"", audioUrl:"", question:"6. この仕事は、山本さんに<u>まかせて</u>おけば安心です。", options:["仕せて","担せて","任せて","但せて"], answer:2,
    translation:"Công việc này cứ giao cho anh Yamamoto thì yên tâm.",
    explanation:"まかせる = 任せる: giao phó, ủy thác. 仕える (つかえる: hầu hạ)・担う (になう: gánh vác)・但せて (không có từ này) sai." },
  { id:"a2-2", passage:"", audioUrl:"", question:"7. 新入生をテニスサークルに<u>かんゆう</u>した。", options:["勧誘","勧遊","観誘","観遊"], answer:0,
    translation:"Tôi đã rủ rê/thuyết phục sinh viên mới vào câu lạc bộ quần vợt.",
    explanation:"かんゆう = 勧誘: rủ rê, mời gọi, thuyết phục tham gia. 勧遊・観誘・観遊 đều là chữ tự tạo, không tồn tại." },
  { id:"a2-3", passage:"", audioUrl:"", question:"8. この計画は<u>じゅんちょう</u>に進んでいる。", options:["準長","準調","順長","順調"], answer:3,
    translation:"Kế hoạch này đang tiến triển thuận lợi.",
    explanation:"じゅんちょう = 順調: thuận lợi, trôi chảy (tiến triển tốt). 準長・準調・順長 đều không phải từ đúng." },
  { id:"a2-4", passage:"", audioUrl:"", question:"9. 落ち葉が<u>つもった</u>道を歩いた。", options:["詰もった","満もった","占もった","積もった"], answer:3,
    translation:"Tôi bước đi trên con đường đầy lá rụng chất đống.",
    explanation:"つもる = 積もる: chất đống, tích tụ (tuyết, lá rụng, bụi…). 詰もった・満もった・占もった đều là chữ ghép sai." },
  { id:"a2-5", passage:"", audioUrl:"", question:"10. この状態が<u>えいきゅう</u>に続くわけではない。", options:["延久","永久","延及","永及"], answer:1,
    translation:"Tình trạng này không phải sẽ kéo dài mãi mãi.",
    explanation:"えいきゅう = 永久: vĩnh viễn, mãi mãi. 延久・延及・永及 đều là chữ tự tạo." },
]},
{ tab:"文字・語彙", section:"問題3 語形成",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a3-1", passage:"", audioUrl:"", question:"11. 私も山口さんと（　）意見です。", options:["等","同","共","似"], answer:1,
    translation:"Tôi cũng có ý kiến giống như anh Yamaguchi.",
    explanation:"同じ意見 (おなじ いけん): ý kiến giống nhau. 同 = giống, cùng. 等 (đẳng cấp), 共 (cùng nhau), 似 (giống về hình thức) không ghép đúng ở đây." },
  { id:"a3-2", passage:"", audioUrl:"", question:"12. このバナナは甘い香りがするので、そろそろ食べ（　）ですよ。", options:["頃","期","刻","節"], answer:0,
    translation:"Chuối này có mùi thơm ngọt nên sắp đến lúc ăn được rồi đấy.",
    explanation:"食べ頃 (たべごろ): vừa đúng lúc để ăn, chín tới. ～頃 = khoảng thời gian, lúc thích hợp. 期 (thời kỳ), 刻 (đơn vị thời gian âm lịch), 節 (tiết trời) không đúng." },
  { id:"a3-3", passage:"", audioUrl:"", question:"13. 本登録の前に、まずは（　）登録を行ってください。", options:["先","予","仮","近"], answer:2,
    translation:"Trước khi đăng ký chính thức, hãy đăng ký tạm thời trước.",
    explanation:"仮登録 (かりとうろく): đăng ký tạm thời. 仮 = tạm. 先登録・予登録・近登録 đều không phải từ ghép đúng." },
]},
{ tab:"文字・語彙", section:"問題4 文脈規定",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a4-1", passage:"", audioUrl:"", question:"14. 学生のころ、宿題は（　）になってからやることが多かった。", options:["びりびり","ばりばり","ぎりぎり","じりじり"], answer:2,
    translation:"Hồi còn sinh viên, tôi thường để sát nút (nước đến chân) mới làm bài tập.",
    explanation:"ぎりぎり: sát nút, vừa đúng hạn, không còn dư thời gian. びりびり (tê buốt, rách toạc)・ばりばり (hăng hái, xột xoạt)・じりじり (từ từ, sốt ruột) sai nghĩa." },
  { id:"a4-2", passage:"", audioUrl:"", question:"15. 生命保険を（　）したいので、手続きを教えてください。", options:["廃止","解約","中止","解消"], answer:1,
    translation:"Tôi muốn hủy hợp đồng bảo hiểm nhân thọ nên xin hãy hướng dẫn thủ tục.",
    explanation:"解約 (かいやく): hủy hợp đồng (bảo hiểm, tài khoản…). 廃止 (bãi bỏ chế độ, quy định), 中止 (đình chỉ giữa chừng), 解消 (xóa bỏ trạng thái) đều không đúng." },
  { id:"a4-3", passage:"", audioUrl:"", question:"16. 私たちは、お客様の（　）に対応したサービスを提供しています。", options:["ニーズ","ストライキ","セールス","エコノミー"], answer:0,
    translation:"Chúng tôi cung cấp dịch vụ đáp ứng nhu cầu của khách hàng.",
    explanation:"ニーズ (needs): nhu cầu. お客様のニーズに対応した = đáp ứng nhu cầu của khách. ストライキ (đình công), セールス (bán hàng), エコノミー (kinh tế) sai." },
  { id:"a4-4", passage:"", audioUrl:"", question:"17. 来年ここに新しい支店を（　）することが決まった。", options:["創造","形成","工作","開設"], answer:3,
    translation:"Người ta đã quyết định mở một chi nhánh mới ở đây vào năm sau.",
    explanation:"開設 (かいせつ): thành lập, mở (chi nhánh, tài khoản, trang web). 創造 (sáng tạo), 形成 (hình thành), 工作 (gia công) sai." },
  { id:"a4-5", passage:"", audioUrl:"", question:"18. 卒業パーティーには、ちゃんとした（　）で行ったほうがいいのかな。", options:["様子","容姿","外見","格好"], answer:3,
    translation:"Đi dự tiệc tốt nghiệp thì có nên ăn mặc chỉnh tề một chút không nhỉ.",
    explanation:"格好 (かっこう): dáng vẻ, cách ăn mặc. ちゃんとした格好で = ăn mặc tử tế/chỉnh tề. 様子 (tình hình), 容姿 (dung mạo), 外見 (vẻ bề ngoài) không hợp ngữ cảnh." },
  { id:"a4-6", passage:"", audioUrl:"", question:"19. 店が忙しいときは臨時にアルバイトを（　）いる。", options:["つかんで","ふくんで","やとって","かせいで"], answer:2,
    translation:"Khi cửa hàng bận rộn thì chúng tôi thuê thêm nhân viên làm thêm theo thời vụ.",
    explanation:"雇う (やとう): thuê, tuyển dụng (người). アルバイトを雇う = thuê nhân viên làm thêm. つかむ (nắm), ふくむ (bao gồm), かせぐ (kiếm tiền) sai." },
  { id:"a4-7", passage:"", audioUrl:"", question:"20. 誰にも言えずにずっと悩んでいたが、昨日親友に（　）相談してみた。", options:["思いきって","うっかり","せっかく","知らず知らず"], answer:0,
    translation:"Tôi đã đau đầu suốt mà không dám nói với ai, nhưng hôm qua đã liều mình thử tham khảo ý kiến bạn thân.",
    explanation:"思いきって (おもいきって): liều mình, dứt khoát làm việc đã do dự. うっかり (lỡ, vô ý)・せっかく (khó khăn lắm mới)・知らず知らず (vô thức) sai." },
]},
{ tab:"文字・語彙", section:"問題5 言い換え類義",
  instruction:"＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a5-1", passage:"", audioUrl:"", question:"21. 私の会社は<u>最寄り</u>の駅から歩いて15分です。", options:["一番大きい","一番近い","終点の","始発の"], answer:1,
    translation:"Công ty tôi cách ga gần nhất 15 phút đi bộ.",
    explanation:"最寄り (もより) = 一番近い: gần nhất. 「最寄りの駅」= ga gần nhất. 終点 (ga cuối)・始発 (ga khởi hành)・一番大きい sai." },
  { id:"a5-2", passage:"", audioUrl:"", question:"22. 演奏会で着るドレスは、いつも近所の店で<u>レンタル</u>しています。", options:["作って","買って","直して","借りて"], answer:3,
    translation:"Chiếc váy mặc đi buổi hòa nhạc thì tôi luôn thuê ở cửa hàng gần nhà.",
    explanation:"レンタルする = 借りる: thuê, mượn (trả phí). 作る (làm), 買う (mua), 直す (sửa) sai." },
  { id:"a5-3", passage:"", audioUrl:"", question:"23. 村上さんはほかの人に<u>指図される</u>のが嫌いだそうだ。", options:["命令","反対","注意","自慢"], answer:0,
    translation:"Nghe nói anh Murakami ghét bị người khác ra lệnh.",
    explanation:"指図する (さしず) = 命令する: ra lệnh, sai khiến, chỉ đạo. 反対 (phản đối), 注意 (nhắc nhở), 自慢 (khoe khoang) sai." },
  { id:"a5-4", passage:"", audioUrl:"", question:"24. この時期に旅行するなら、かさは<u>欠かせない</u>。", options:["ないといい","あるとじゃまだ","ないと困る","あると便利だ"], answer:2,
    translation:"Nếu đi du lịch vào thời điểm này thì ô là thứ không thể thiếu.",
    explanation:"欠かせない (かかせない): không thể thiếu ⇒ ないと困る (không có thì khó xử). あるとじゃまだ (có thì vướng)・あると便利だ (có thì tiện) sai." },
  { id:"a5-5", passage:"", audioUrl:"", question:"25. 雨は<u>依然</u>強かった。", options:["確かに","まだ","意外に","とても"], answer:1,
    translation:"Mưa vẫn còn mạnh như trước.",
    explanation:"依然 (いぜん) = まだ: vẫn còn, vẫn như cũ. 確かに (đúng là), 意外に (bất ngờ), とても (rất) sai." },
]},
{ tab:"用法", section:"問題6 用法",
  instruction:"次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a6-1", passage:"", audioUrl:"", question:"26. 栽培", options:["両親は牧場で牛を栽培して、チーズを作っています。","私は今、生まれて半年の赤ちゃんを栽培しています。","庭で見つけた虫の卵を栽培して、観察日記を書いた。","この畑では、農薬を使わずに野菜を栽培しています。"], answer:3,
    translation:"Ở thửa ruộng này, người ta trồng rau mà không dùng thuốc trừ sâu.",
    explanation:"栽培 (さいばい): trồng trọt (cây cối, nông sản). 「野菜を栽培する」✓. Các câu khác phải dùng: 牛 → 牧畜/飼育, 赤ちゃん → 養育, 虫の卵 → 培養." },
  { id:"a6-2", passage:"", audioUrl:"", question:"27. 急激", options:["イベントの開催日が近くなり、準備が急激に進められている。","新しい駅ができて、市の人口が急激に増加している。","このパンは非常に人気があり、朝8時に開店すると急激に売れていく。","松田選手が現れると、ファンの人たちが急激に取り囲んだ。"], answer:1,
    translation:"Nhà ga mới được xây nên dân số thành phố đang tăng lên một cách nhanh chóng.",
    explanation:"急激 (きゅうげき): đột ngột, nhanh và mạnh (thường đi với 変化・増加・減少). 「人口が急激に増加している」✓. Câu 1 nên dùng 急速に, câu 3 nên dùng すぐ, câu 4 nên dùng 急に." },
  { id:"a6-3", passage:"", audioUrl:"", question:"28. 漏れる", options:["ジュースを注ぎすぎて、コップから漏れてしまった。","転んでしまって、ひざから血が漏れてきた。","水道管に穴があいているのか、水が漏れてきている。","悲しい映画を見たせいで、涙が漏れてきた。"], answer:2,
    translation:"Có lẽ đường ống nước bị thủng nên nước đang rò rỉ ra.",
    explanation:"漏れる (もれる): rò, rỉ, lọt ra (chất lỏng, khí, thông tin). 「水が漏れてきている」✓. Câu 1 → 溢れて, 2 → 出て, 4 → 流れて mới đúng." },
  { id:"a6-4", passage:"", audioUrl:"", question:"29. 傾向", options:["ファッション誌によると、今年は黄色が傾向するそうだ。","最近では、家族がばらばらに食事をする傾向がある。","姉は日本文学の研究に傾向している。","この坂は傾向がきつくて、自転車だとつらい。"], answer:1,
    translation:"Gần đây, có xu hướng các thành viên trong gia đình ăn cơm riêng mỗi người một lúc.",
    explanation:"傾向 (けいこう): xu hướng, khuynh hướng. 「〜する傾向がある」= có xu hướng ~ ✓. Câu 1 → 流行する, 3 → 傾注して, 4 → 傾斜/斜度 mới đúng." },
  { id:"a6-5", passage:"", audioUrl:"", question:"30. さっさと", options:["いつまでもテレビを見てないで、さっさと宿題をしなさい。","雷が鳴り出したと思ったら、さっさと雨が降り出した。","さっさと着くので、もう少しそこで待っていてください。","買ってまだ一週間なのに、さっさと壊れた。"], answer:0,
    translation:"Đừng có xem tivi mãi thế, làm bài tập nhanh lên.",
    explanation:"さっさと: nhanh chóng, mau lẹ (làm việc mình cần làm). 「さっさと宿題をしなさい」✓. Câu 2 → たちまち, 3 → すぐ, 4 → もう mới đúng nghĩa." },
]},
{ tab:"文法", section:"問題7 文の文法1",
  instruction:"次の文の（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a7-1", passage:"", audioUrl:"", question:"31. A「田中さんに話があるんだけど、今、会議中？」　B「うん。」　A「じゃあ、会議が終わるのを待つ（　）ないね。」", options:["しか","だけ","まで","さえ"], answer:0,
    translation:"A: \"Tôi có chuyện muốn nói với anh Tanaka, giờ anh ấy đang họp à?\" B: \"Ừ.\" A: \"Vậy thì chỉ còn cách đợi cuộc họp kết thúc thôi nhỉ.\"",
    explanation:"～しかない: chỉ còn cách…, ngoài ra không còn cách nào khác (đi với phủ định ない). 「待つしかない」✓. だけ (chỉ, nhưng không đi với ない theo mẫu này)・まで・さえ sai." },
  { id:"a7-2", passage:"", audioUrl:"", question:"32. この道路拡張計画を（　）にあたっては、市民の皆様のご理解が必要です。", options:["進めた","進める","進めたい","進めよう"], answer:1,
    translation:"Khi tiến hành kế hoạch mở rộng đường này, cần có sự thông hiểu của quý vị người dân.",
    explanation:"～にあたって: nhân dịp, khi (làm việc gì quan trọng) — nối với động từ ở dạng từ điển (thể nguyên). 「進めるにあたって」✓. 進めた/進めたい/進めよう sai cách nối." },
  { id:"a7-3", passage:"", audioUrl:"", question:"33. 今日の試合は大雪で延期になった。（　）この時期に大雪になるとは思わなかった。", options:["一体","二度と","まさか","かえって"], answer:2,
    translation:"Trận đấu hôm nay đã hoãn vì tuyết lớn. Không ngờ vào thời điểm này lại có tuyết lớn đến vậy.",
    explanation:"まさか～とは思わなかった: không ngờ rằng… (diễn tả sự bất ngờ). 一体 (rốt cuộc — dùng cho câu hỏi), 二度と (một lần nữa — đi với phủ định), かえって (ngược lại) sai." },
  { id:"a7-4", passage:"", audioUrl:"", question:"34. 水泳クラブの山田コーチは、私たちにとってコーチ（　）兄のような存在です。", options:["に限らず","なしには","のおかげで","というより"], answer:3,
    translation:"Huấn luyện viên Yamada của câu lạc bộ bơi đối với chúng tôi không hẳn là huấn luyện viên mà giống như một người anh.",
    explanation:"～というより: nói là… thì đúng hơn là, không hẳn là… mà là… 「コーチというより兄のような存在」✓. に限らず (không chỉ giới hạn), なしには (nếu không có… thì không), のおかげで (nhờ ơn) sai nghĩa." },
  { id:"a7-5", passage:"", audioUrl:"", question:"35. X社の健康食品はテレビ番組で紹介（　）以来、とても売れている状態が続いている。", options:["されて","される","されている","された"], answer:0,
    translation:"Thực phẩm chức năng của công ty X kể từ khi được giới thiệu trên chương trình truyền hình đến nay vẫn tiếp tục bán rất chạy.",
    explanation:"～て以来: kể từ khi… đến nay (luôn ở trạng thái đó). Động từ phải ở dạng ～て (thể て) ⇒ 「紹介されて以来」✓. される/されている/された sai cách nối." },
  { id:"a7-6", passage:"", audioUrl:"", question:"36.（店で）　A「このシャツ、かわいい。でも、会社に着ていくには派手かな。」　B「うん。デートで着る（　）、仕事には派手すぎるよ。」", options:["にしては","としたら","ならともかく","からとはいえ"], answer:2,
    translation:"(Ở cửa hàng) A: \"Chiếc áo này xinh nhỉ. Nhưng mặc đến công ty thì hơi lòe loẹt nhỉ.\" B: \"Ừ. Nếu mặc đi hẹn hò thì còn được, chứ đi làm thì quá lòe loẹt.\"",
    explanation:"～ならともかく: nếu là… thì còn tạm được (nhưng với trường hợp khác thì không). 「デートで着るならともかく、仕事には派手すぎる」✓. にしては (xét theo), としたら (nếu giả sử), からとはいえ (dù vì…) sai." },
  { id:"a7-7", passage:"", audioUrl:"", question:"37. 娘は、社会人（　）朝一人で起きられない。私が起こさないといつまでも寝ている。", options:["にもなって","にもなれば","にでもなって","にでもなれば"], answer:0,
    translation:"Con gái tôi đã đi làm rồi mà buổi sáng không thể tự dậy. Tôi không gọi thì nó ngủ mãi.",
    explanation:"～にもなって: đã trở thành… rồi mà (còn làm điều không nên, hàm ý trách móc). 「社会人にもなって朝一人で起きられない」✓. にもなれば (nếu đã trở thành), にでもなって/にでもなれば (thành… chăng, không tự nhiên) sai. ⚠️ Bảng đáp án in kèm file ghi ③, nhưng theo ngữ pháp đáp án đúng là ① にもなって." },
  { id:"a7-8", passage:"", audioUrl:"", question:"38. 友達は、お茶でうがいを（　）、風邪をひかなくなったらしい。私も始めてみようと思う。", options:["しようとすれば","しようとしたことで","するようにすれば","するようにしたことで"], answer:3,
    translation:"Nghe nói bạn tôi nhờ kiên trì súc miệng bằng trà nên không còn bị cảm nữa. Tôi cũng định bắt đầu thử.",
    explanation:"～するようにしたことで: nhờ đã kiên trì/đặt ra và duy trì việc… mà… 「うがいをするようにしたことで、風邪をひかなくなった」✓. しようとすれば (nếu định…), しようとしたことで, するようにすれば sai về ý nghĩa nguyên nhân." },
  { id:"a7-9", passage:"", audioUrl:"", question:"39. 彼女があのとき何を考えていたのか知りたいけれど、今はもう会うこともないので、（　）。", options:["確かめかねない","確かめるほかない","確かめようがない","確かめるわけではない"], answer:2,
    translation:"Tôi muốn biết lúc đó cô ấy đã nghĩ gì, nhưng giờ không còn gặp nhau nữa nên không cách nào xác nhận được.",
    explanation:"～ようがない: không có cách nào (làm) được, không thể. 「確かめようがない」✓. 確かめかねない (có thể sẽ xác nhận - tiêu cực), 確かめるほかない (chỉ còn cách xác nhận), 確かめるわけではない (không hẳn là xác nhận) sai nghĩa." },
  { id:"a7-10", passage:"", audioUrl:"", question:"40.（不動産屋で）店員「お客様、本日いくつかのお部屋を（　）が、ご希望に合うお部屋はございましたか。」客「最初の部屋がいいなと思ったんですが、ちょっと検討させてください。」", options:["参りました","拝見しました","お越しいただきました","ご覧いただきました"], answer:3,
    translation:"(Ở công ty bất động sản) Nhân viên: \"Thưa quý khách, hôm nay tôi đã đưa quý khách xem vài căn phòng, có căn nào phù hợp với mong muốn của quý khách không ạ?\" Khách: \"Căn đầu tiên thì tôi thấy được, nhưng cho tôi suy nghĩ thêm một chút.\"",
    explanation:"ご覧いただく: khiêm nhường ngữ = \"được quý khách xem (giúp tôi)\" → dùng đúng cho nhân viên nói về việc khách đã xem phòng ✓. 参りました (tôi đã đến), 拝見しました (tôi đã xem - khiêm nhường ngữ của mình), お越しいただきました (được quý khách đến) sai ngữ cảnh." },
  { id:"a7-11", passage:"", audioUrl:"", question:"41. カレーを大量に作りすぎて、一人では食べ（　）と思ったので、友人をよんで食べた。", options:["切れるかもしれない","切れそうにない","かねないだろう","かねないようだ"], answer:1,
    translation:"Tôi làm quá nhiều cà ri, nghĩ rằng một mình thì có vẻ ăn không hết nên đã gọi bạn đến ăn cùng.",
    explanation:"～切れる: ăn/làm hết được ⇒ phủ định 「切れそうにない」= có vẻ không thể ăn hết ✓. 切れるかもしれない (có thể ăn hết), かねないだろう/かねないようだ (có nguy cơ…) sai nghĩa." },
  { id:"a7-12", passage:"", audioUrl:"", question:"42. 最近は毎月決まった金額でかけ放題の国際電話サービスがある。私が留学していたときにもそんなサービスがあったら（　）。", options:["どれだけよかった","どれだけよかったか","どうしてもよかった","どうしてもよかったか"], answer:1,
    translation:"Gần đây có dịch vụ gọi điện quốc tế thỏa thích với mức phí cố định hàng tháng. Giá mà hồi tôi du học cũng có dịch vụ như vậy thì tốt biết bao.",
    explanation:"～たらどれだけよかったか: giá mà… thì tốt biết bao (mẫu câu tiếc nuối). Cần か ở cuối vì là câu cảm thán ⇒ どれだけよかったか ✓. Các phương án khác thiếu か hoặc dùng どうしても sai." },
]},
{ tab:"文法", section:"問題8 文の文法2 (sắp xếp - ★)",
  instruction:"次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a8-1", passage:"", audioUrl:"", question:"43. もう酒は飲まないと ＿＿ ＿＿ ★ ＿＿ 絶対に守りたい。［1 決めた / 2 どんなに / 3 以上は / 4 誘われても］", options:["決めた","どんなに","以上は","誘われても"], answer:1,
    translation:"Vì đã quyết là không uống rượu nữa, nên dù có bị rủ rê thế nào tôi cũng nhất định giữ lời.",
    explanation:"Thứ tự đúng: 決めた（1）→以上は（3）→どんなに（2）→誘われても（4）: 「もう酒は飲まないと決めた以上は、どんなに誘われても絶対に守りたい」。★ là ô thứ 3 ⇒ đáp án ② どんなに. ～以上は: một khi đã… thì (phải)… 「～と決める」= quyết định rằng…" },
  { id:"a8-2", passage:"", audioUrl:"", question:"44. 必要のない物でも、欲しくなると ＿＿ ＿＿ ★ ＿＿ しまう。［1 買わずには / 2 すぐ買って / 3 いられなく / 4 なって］", options:["買わずには","すぐ買って","いられなく","なって"], answer:3,
    translation:"Dù là thứ không cần thiết, một khi đã muốn thì tôi không thể nhịn không mua mà mua ngay.",
    explanation:"Thứ tự đúng: 買わずには（1）→いられなく（3）→なって（4）→すぐ買って（2）: 「欲しくなると買わずにはいられなくなって、すぐ買ってしまう」。★ ô thứ 3 ⇒ đáp án ④ なって. ～ずにはいられない: không thể không…, không nhịn được." },
  { id:"a8-3", passage:"", audioUrl:"", question:"45. パソコンの電源を入れたのだが、画面に「お待ちください」という ＿＿ ＿＿ ★ ＿＿ 電源を入れ直した。［1 待っても / 2 何分 / 3 メッセージが出たまま / 4 先に進まないので］", options:["待っても","何分","メッセージが出たまま","先に進まないので"], answer:0,
    translation:"Tôi bật nguồn máy tính, nhưng màn hình cứ hiện thông báo \"Xin chờ\" mãi, đợi mấy phút cũng không tiến triển gì nên tôi đã bật lại nguồn.",
    explanation:"Thứ tự đúng: メッセージが出たまま（3）→何分（2）→待っても（1）→先に進まないので（4）: 「…というメッセージが出たまま何分待っても先に進まないので、電源を入れ直した」。★ ô thứ 3 ⇒ đáp án ① 待っても. ～たまま: giữ nguyên trạng thái…" },
  { id:"a8-4", passage:"", audioUrl:"", question:"46.（電話で）　A「すみません、来週の2時からの会議ですが、その時間、別の用件が入ってしまいまして、もしそちらのご都合が ＿＿ ＿＿ ★ ＿＿ 、いかがでしょうか。」　B「こちらは大丈夫ですよ。」［1 ありがたいんですが / 2 変更していただけると / 3 4時以降に / 4 よろしければ］", options:["ありがたいんですが","変更していただけると","4時以降に","よろしければ"], answer:1,
    translation:"(Qua điện thoại) A: \"Xin lỗi, về cuộc họp lúc 2 giờ tuần sau, giờ đó tôi lại có việc khác mất rồi, nếu phía anh thuận tiện thì nếu được đổi sang sau 4 giờ thì tôi rất cảm ơn, anh thấy thế nào ạ?\" B: \"Phía tôi không vấn đề gì.\"",
    explanation:"Thứ tự đúng: よろしければ（4）→4時以降に（3）→変更していただけると（2）→ありがたいんですが（1）: 「ご都合がよろしければ、4時以降に変更していただけるとありがたいんですが」。★ ô thứ 3 ⇒ đáp án ② 変更していただけると." },
  { id:"a8-5", passage:"", audioUrl:"", question:"47. 20年前に初めてこの歌手の歌を聴いたとき、＿＿ ＿＿ ★ ＿＿ 。［1 と思った / 2 よく覚えている / 3 のを / 4 なんと美しい声なんだろう］", options:["と思った","よく覚えている","のを","なんと美しい声なんだろう"], answer:2,
    translation:"Tôi vẫn nhớ rất rõ là 20 năm trước, khi lần đầu nghe giọng hát của ca sĩ này, tôi đã nghĩ \"giọng hát đẹp biết bao\".",
    explanation:"Thứ tự đúng: なんと美しい声なんだろう（4）→と思った（1）→のを（3）→よく覚えている（2）: 「…なんと美しい声なんだろうと思ったのをよく覚えている」。★ ô thứ 3 ⇒ đáp án ③ のを. ～の: danh từ hóa mệnh đề trước; ～をよく覚えている = nhớ rõ việc…" },
]},
{ tab:"文法", section:"問題9 文章の文法 (điền vào đoạn văn)",
  instruction:"次の文章を読んで、文章全体の内容を考えて、48から51の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a9-1", passage:"「落語」体験　バラージ・ペーテル<br><br>今回、留学生センターで行われた文化体験のテーマは「落語」だった。落語は日本の伝統的な芸能の一つだ。着物を着た落語家が舞台に正座したまま、一人で何役も演じ、語って聞かせる。たいていは、面白く、おかしい話だ。私の国には演劇はあるが、落語のようなものはない。<br><br>私は、文化体験が落語だと知って、実はがっかりした。以前、ある落語を授業で読んだが、あまり面白いと（48）話をただ聞いているのは退屈だろうと思ったし、聞き取れるかどうかも不安だった。<br><br>（49）落語を聞いている間、私はよく笑った。落語家の動作や声の出し方は本当に面白くて、場面の様子もよくわかった。しぐさや話し方を変えて、親と子など二役以上を一人で演じ、会話を進める。座ったまま体を揺らして歩いている様子を見せ、家から店に移動したことを表す。食事の動作は、本当に何かを食べているようだった。<br><br>文化体験が終わったとき、落語の印象がすっかり変わっていた。落語とは、落語家の動作と語りを同時に（50）。私は、話の細部は理解できていなかったかもしれない。しかし、落語家の動作と語りを通して、登場人物の性格や暮らしが感じられた。それに、映像や音楽や踊りがなくても、生き生きと話を伝え、人を笑わせられる落語家の表現力にも感動した。<br><br>落語には、怖い話や感動的な話もあるそうだ。落語家は（51）をするのだろうか。ぜひいろいろな落語を聞いてみたい。",
    audioUrl:"", question:"48. 以前、ある落語を授業で読んだが、あまり面白いと（48）話をただ聞いているのは退屈だろうと思った。", options:["思えなかったまでだ","思えなかったほどだ","思えなかっただけだ","思えなかったからだ"], answer:3,
    translation:"Trải nghiệm \"Rakugo\". Chủ đề của buổi trải nghiệm văn hóa lần này ở trung tâm du học sinh là \"Rakugo\". Rakugo là một trong những bộ môn nghệ thuật truyền thống của Nhật Bản. Nghệ sĩ rakugo mặc kimono, ngồi quỳ trên sân khấu và một mình diễn nhiều vai, kể cho khán giả nghe. Phần lớn là những câu chuyện thú vị, buồn cười. Đất nước tôi có kịch nhưng không có thứ giống rakugo. Khi biết buổi trải nghiệm văn hóa là rakugo, thật ra tôi đã thất vọng. Trước đây tôi từng đọc một câu chuyện rakugo trong giờ học, nhưng tôi nghĩ rằng chỉ ngồi nghe thì sẽ nhàm chán, và cũng lo không biết mình có nghe hiểu được không. (49) Trong khi nghe rakugo, tôi đã cười rất nhiều. Động tác và cách phát ra giọng của nghệ sĩ thật sự thú vị, và tình huống của câu chuyện cũng rất dễ hiểu…",
    explanation:"【48】= 思えなかったからだ: vì (tôi) đã không thể nghĩ rằng… 「あまり面白いと思えなかったからだ」= vì không thể thấy nó thú vị ⇒ nêu lý do cho việc đã thất vọng. ～までだ (chỉ là…), ～ほどだ (đến mức…), ～だけだ (chỉ là…) đều không diễn tả nguyên nhân." },
  { id:"a9-2", passage:"", audioUrl:"", question:"49. （49）落語を聞いている間、私はよく笑った。", options:["しかも","すなわち","ところが","したがって"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 48) / Tuy nhiên, trong khi nghe rakugo thì tôi lại cười rất nhiều.",
    explanation:"【49】= ところが: thế nhưng, tuy nhiên (biểu thị sự tương phản với dự đoán trước đó là \"sẽ nhàm chán\"). しかも (hơn nữa), すなわち (tức là), したがって (do đó) đều sai quan hệ logic." },
  { id:"a9-3", passage:"", audioUrl:"", question:"50. 落語とは、落語家の動作と語りを同時に（50）。", options:["楽しむものなのだ","楽しむはずなのだ","楽しむようにするのだ","楽しむことになったのだ"], answer:0,
    translation:"(Đoạn văn: xem bản dịch ở câu 48) / Rakugo là thứ mà ta cùng thưởng thức đồng thời cả động tác và lời kể của nghệ sĩ.",
    explanation:"【50】= 楽しむものなのだ: là thứ (để) thưởng thức — 「～とは…ものなのだ」là mẫu định nghĩa/giải thích bản chất sự vật. 楽しむはずなのだ (đáng ra phải thưởng thức — suy đoán), 楽しむようにするのだ (quyết định làm cho thưởng thức), 楽しむことになったのだ (hóa ra là được thưởng thức) đều sai." },
  { id:"a9-4", passage:"", audioUrl:"", question:"51. 落語には、怖い話や感動的な話もあるそうだ。落語家は（51）をするのだろうか。", options:["どんな表現","その表現","表現","こういう表現"], answer:0,
    translation:"(Đoạn văn: xem bản dịch ở câu 48) / Nghe nói rakugo cũng có những câu chuyện đáng sợ hay cảm động. Không biết nghệ sĩ rakugo sẽ thể hiện (những câu chuyện đó) bằng cách nào nhỉ.",
    explanation:"【51】= どんな表現: (những) cách thể hiện như thế nào — đi với nghi vấn ～だろうか ở cuối câu tạo sự hài hòa ✓. その表現 (cách thể hiện đó)・表現・こういう表現 (cách thể hiện như thế này) không kết hợp với nghi vấn か." },
]},
/* ================= TAB 4: 読解 ================= */
{ tab:"読解", section:"問題10 内容理解・短文",
  instruction:"次の（1）から（5）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b10-1", passage:"森はいつも独特な香りに包まれ、さわやかに感じられるが、それはある物質の効果によるものだ。その物質は、木々が動けない体を守るために自ら作り出すもので、木につく虫や（注）細菌の増加を防いだり、落ち葉や枯れ木が腐ったときなどに生じる嫌なにおいを消したりする働きを持っている。さらにその物質には、人間の神経を安定させる効果もあるという。私たちが森林に入るとリラックスした気分になるのは、このためだ。<br><br>（注）細菌：非常に小さくて目に見えない生物",
    audioUrl:"", question:"52. ある物質の働きについて、この文章からわかることは何か。",
    options:["人間の持つ嫌なにおいを防ぐ。","人々の気持ちを落ち着かせる。","落ち葉や枯れ木を腐りにくくする。","木々がもともと持っているにおいを消す。"], answer:1,
    translation:"Rừng luôn được bao phủ bởi một mùi hương đặc trưng, mang lại cảm giác sảng khoái, và đó là nhờ tác dụng của một chất nào đó. Chất ấy do cây cối tự tạo ra để bảo vệ thân thể không thể di chuyển của mình, có tác dụng ngăn sự gia tăng của côn trùng và vi khuẩn (chú thích) bám trên cây, đồng thời khử mùi khó chịu sinh ra khi lá rụng hay cây khô mục. Hơn nữa, chất đó còn được cho là có tác dụng ổn định thần kinh của con người. Đó chính là lý do khi vào rừng chúng ta cảm thấy thư giãn.",
    explanation:"Đáp án 2. Bài nêu「さらにその物質には、人間の神経を安定させる効果もあるという」⇒ chất đó giúp làm dịu/làm ổn định tinh thần con người. 1 sai (không phải \"mùi của con người\"), 3 sai (bài chỉ nói khử mùi khi lá/cây mục, không nói làm chậm mục), 4 sai." },
  { id:"b10-2", passage:"以下は、池林市の市民文化センターに届いたメールである。<br><br>池林市民文化センター<br>ご担当者様<br><br>3月に文化センターで行われる市民文化祭用のポスターについてお願いがあります。<br><br>ホームページには、サークルの代表者が直接センターの受付に持参するようにと書いてありますが、仕事の都合で、受付が開いている平日の開館時間には伺うことができません。そのため郵送での提出を認めていただくことはできませんでしょうか。<br><br>ポスターは、ホームページの指示にしたがって問題なく作成できていると思います。お忙しいところすみませんが、ご回答いただけますようよろしくお願いいたします。<br><br>市民絵画サークルぽぷら代表　山下達次",
    audioUrl:"", question:"53. このメールの用件は何か。",
    options:["ポスターの作り方に間違いがないか確認してほしい。","ポスターの提出が遅れることを許可してほしい。","ポスターを休日に提出させてほしい。","ポスターを郵送で提出させてほしい。"], answer:3,
    translation:"Dưới đây là email gửi đến trung tâm văn hóa công dân thành phố Ikebayashi. Kính gửi người phụ trách trung tâm văn hóa công dân Ikebayashi. Tôi có một đề nghị liên quan đến poster cho lễ hội văn hóa công dân tổ chức ở trung tâm vào tháng 3. Trên trang web có ghi là đại diện của các câu lạc bộ phải trực tiếp mang đến quầy tiếp nhận của trung tâm, nhưng vì lý do công việc nên tôi không thể đến vào giờ mở cửa các ngày thường khi quầy tiếp nhận làm việc. Vì vậy, liệu quý trung tâm có thể cho phép tôi nộp qua đường bưu điện được không ạ? Tôi nghĩ poster đã được làm đúng theo hướng dẫn trên trang web, không có vấn đề gì. Xin lỗi vì làm phiền khi quý vị đang bận, mong nhận được hồi âm. Đại diện câu lạc bộ hội họa công dân Popura, Yamashita Tatsuji.",
    explanation:"Đáp án 4. Câu then chốt:「そのため郵送での提出を認めていただくことはできませんでしょうか」⇒ xin được cho phép nộp qua bưu điện. ⚠️ Bảng đáp án in kèm file ghi ③ nhưng nội dung lựa chọn ③ là \"nộp vào ngày nghỉ\", trái với phần giải thích của chính tài liệu đó — đáp án đúng theo nội dung là ④." },
  { id:"b10-3", passage:"以下は、新聞のコラムである。<br><br>最近は、環境のためによい商品が市場に多く出ているが、それらを求める際にとても便利なインターネットのサイトが、ある環境団体によって運営されている。そのサイトには、環境のことを考えた家電製品からホテルまで10分類、1万点もの商品・サービスの情報がある。<br><br>例えば、パソコンの場合、メーカー名や「ノート」か「デスクトップ」かなどを指定して検索すると、約74点の商品のリサイクルの状況、修理のしやすさ、長寿命商品であるかなどを比較することができる。メーカー側が年4回、情報を書き換える仕組みとなっており、最新のモデルを検討する際にも便利だ。",
    audioUrl:"", question:"54. このインターネットのサイトの便利な点について述べているのはどれか。",
    options:["買いたいと思う商品についてこのサイトを通してメーカーから直接買うことができる。","買いたいと思っている商品が環境に良いか悪いかを、このサイトで調べることができる。","このサイトには高齢者が使いやすいさまざまな家電製品やホテルの情報が載っている。","環境団体が各商品の情報を常に書き換えているので、最新のモデルを選ぶことができる。"], answer:1,
    translation:"Dưới đây là một bài bình luận trên báo. Gần đây, nhiều sản phẩm tốt cho môi trường xuất hiện trên thị trường, và để tìm những sản phẩm đó thì có một trang web Internet rất tiện lợi do một tổ chức môi trường điều hành. Trên trang web đó có thông tin về 10 loại, 1 vạn sản phẩm/dịch vụ, từ đồ gia dụng thân thiện môi trường cho đến khách sạn. Ví dụ với máy tính, nếu chỉ định tên hãng hay \"laptop\" hay \"để bàn\" để tìm kiếm thì có thể so sánh tình trạng tái chế, mức độ dễ sửa chữa, có phải sản phẩm tuổi thọ cao hay không… của khoảng 74 sản phẩm. Cơ chế là phía nhà sản xuất cập nhật thông tin 4 lần một năm, nên cũng tiện khi cân nhắc mẫu mới nhất.",
    explanation:"Đáp án 2. Bài nói trang web giúp so sánh tình trạng tái chế, độ dễ sửa, tuổi thọ sản phẩm… ⇒ có thể tra cứu xem sản phẩm mình định mua có thân thiện với môi trường hay không. 1 sai (không bán hàng trực tiếp), 3 sai (không hề nói về người cao tuổi), 4 sai (bài nói nhà sản xuất cập nhật 4 lần/năm, không phải \"thường xuyên\" và chủ thể là nhà sản xuất, không phải tổ chức môi trường)." },
  { id:"b10-4", passage:"以下は、ある会社の社内文書である。<br><br>6月24日<br><br>担当者各位<br>総務課長<br><br>事務用品の注文について<br><br>これまで、事務用品は、総務課で事務用品配達サービス会社に一括して注文管理し、各課に支給してきました。しかし、事務作業を簡略化するため、8月より各課で直接注文していただくことになりました。管理も各課でお願いいたします。<br><br>なお、注文方法の詳細については、改めて説明会を行う予定です。<br><br>よろしくお願いいたします。<br><br>以上",
    audioUrl:"", question:"55. この文書を書いた一番の目的は何か。",
    options:["事務用品の注文先の会社の変更を伝える。","事務用品の注文方法の説明会の日時を知らせる。","事務用品の注文、管理方法の問題点を伝える。","事務用品の注文、管理方法の変更を知らせる。"], answer:3,
    translation:"Dưới đây là văn bản nội bộ của một công ty. Ngày 24 tháng 6. Kính gửi các cán bộ phụ trách. Trưởng phòng tổng vụ. Về việc đặt hàng văn phòng phẩm. Từ trước đến nay, văn phòng phẩm được phòng tổng vụ đặt hàng và quản lý tập trung qua công ty dịch vụ giao hàng văn phòng phẩm, rồi cấp phát cho từng phòng. Tuy nhiên, để đơn giản hóa công việc hành chính, từ tháng 8, các phòng sẽ trực tiếp đặt hàng. Việc quản lý cũng xin giao cho từng phòng. Ngoài ra, về chi tiết cách đặt hàng, chúng tôi dự định sẽ tổ chức buổi giải thích riêng. Mong mọi người hợp tác. Hết.",
    explanation:"Đáp án 4. Câu then chốt:「8月より各課で直接注文していただくことになりました。管理も各課でお願いいたします」⇒ thông báo thay đổi cách đặt hàng và quản lý văn phòng phẩm. 1 sai (không đổi công ty), 2 sai (chưa ấn định ngày giờ buổi giải thích), 3 sai (không nêu \"vấn đề tồn tại\")." },
  { id:"b10-5", passage:"人材の評価や選抜の方式は、社会の根本的な活力を規定する最も重要な（注1）ファクターである。しかもその人材の育成には時間がかかる。競争のない社会、公正な評価が通らない組織は、長い目で見れば必ず（注2）衰退する。だからこそ、いつの時代でも、どの組織でも、優秀な人材の獲得に（注3）躍起になり、人材の育成に多大な努力を注ぐとともに、いかに公正な評価のシステムを組み込むのかという点に強い関心を払ってきたのである。<br><br>（注1）ファクター：要素　（注2）衰退する：衰える、弱くなる　（注3）躍起になる：必死になる",
    audioUrl:"", question:"56. 筆者は、人材が公正に評価されないと組織はどうなると述べているか。",
    options:["短期間で人材を育てられなくなる。","優秀な人材を獲得できなくなる。","組織の活力を維持できなくなる。","組織への関心が薄くなる。"], answer:2,
    translation:"Cách đánh giá và tuyển chọn nhân tài là nhân tố (chú thích 1) quan trọng nhất quy định sức sống cơ bản của xã hội. Hơn nữa, việc đào tạo nhân tài cần thời gian. Một xã hội không có cạnh tranh, một tổ chức không có đánh giá công bằng, nhìn lâu dài nhất định sẽ suy thoái (chú thích 2). Chính vì vậy, ở mọi thời đại, mọi tổ chức đều sốt sắng (chú thích 3) giành lấy nhân tài giỏi, dồn nhiều nỗ lực vào đào tạo nhân tài, đồng thời rất quan tâm đến việc làm sao đưa được một hệ thống đánh giá công bằng vào tổ chức.",
    explanation:"Đáp án 3. Câu then chốt:「競争のない社会、公正な評価が通らない組織は、長い目で見れば必ず衰退する」⇒ nếu không được đánh giá công bằng thì tổ chức sẽ suy thoái, tức không duy trì được sức sống (活力) của tổ chức. 1, 2, 4 không được nêu." },
]},
{ tab:"読解", section:"問題11 内容理解・中文",
  instruction:"次の（1）から（3）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b11-1", passage:"次の文章は、ある小学校の先生が自分のクラスについて書いたものである。<br><br>5年生を受け持った時の5月、T男が（注1）つぶやいた。「僕はやりたくないなあ。だって、どうせ僕にはいいところなんてないもん」。クラスの友達の「いいところ探し」をしようと提案した時のことだ。<br><br>クラス替えをしたばかりで、まだ子ども同士の関係が深まっていない時期である。友達のことを知ってほしい、長所を見つける目を持ってほしい、という意図で提案した。T男のつぶやきを聞き、自信をつけさせるチャンスになるかもしれない、と考えた。<br><br>「その人のいいところや、良さを見つけた場面などを書きましょう」と全員の名前を書いたプリントを配布した。プリントを前に、ニコニコしながら書く子、友達の顔をちらちらと見て書く子、難しい顔で考え込む子など様々だ。それでも表情を見ているだけで、子どもたちが一生懸命友達の良さを見つけようとしている様子が伝わってきた。<br><br>T男を見ると、全く書けていない。小声で伝えた。「T男くんの良いところを書いてくれている人がたくさんいるよ」「うそだー」「うそじゃないよ。習字がうまいとか、係の仕事をちゃんとやっているとか」。聞いて（注2）まんざらでもないといった表情である。続きを翌週までに仕上げておくことにした。T男も全員分の長所の記入ができた。<br><br>提出されたものをまとめ、冊子にして配布した。自分の長所について書かれたものを読んでいる子どもたちは、T男を含め誰もが、照れくさいけれどうれしい、といった表情だった。<br><br>（注1）つぶやく：小さな声でひとりごとを言う　（注2）まんざらでもない：必ずしも嫌ではない",
    audioUrl:"", question:"57. 「僕はやりたくないなあ。」とあるが、T男はなぜ「いいところ探し」をやりたくないと言ったのか。",
    options:["自分自身の長所が見つけられないから","自分の良さを書くのがはずかしいから","友達の長所を見つけるのは難しいから","友達のことがまだよくわからないから"], answer:0,
    translation:"Dưới đây là bài viết của một giáo viên tiểu học về lớp mình phụ trách. Vào tháng 5 khi tôi phụ trách lớp 5, em T lẩm bẩm: \"Em không muốn làm đâu. Vì dù sao em cũng chẳng có điểm tốt nào cả\". Đó là lúc tôi đề nghị cả lớp làm \"tìm điểm tốt\" của bạn. Lúc này lớp vừa mới đổi nên quan hệ giữa các em chưa sâu. Tôi đề nghị với ý định muốn các em hiểu về bạn, có con mắt tìm ra điểm mạnh của bạn. Nghe lời lẩm bẩm của em T, tôi nghĩ biết đâu đây sẽ là cơ hội để em tự tin hơn. Tôi phát phiếu có ghi tên cả lớp và đề nghị: \"Hãy viết ra điểm tốt, hay khoảnh khắc em thấy bạn mình tốt\". Trước phiếu, có em vừa cười vừa viết, có em liếc nhìn mặt bạn rồi viết, có em nhíu mặt suy nghĩ… Chỉ nhìn gương mặt thôi cũng thấy các em đang cố gắng tìm ra điểm tốt của bạn. Nhìn em T thì thấy em hoàn toàn không viết được. Tôi nói nhỏ: \"Có rất nhiều bạn viết điểm tốt của em T đấy\". \"Xạo mà\". \"Không phải xạo đâu. Nào là chữ viết đẹp, nào là làm việc lớp nghiêm túc\". Nghe xong, em tỏ vẻ không hẳn là khó chịu. Tôi quyết định cho các em hoàn thành phần còn lại trước tuần sau. Em T cũng ghi được điểm mạnh của tất cả các bạn. Tôi tổng hợp lại, làm thành tập nhỏ và phát cho cả lớp. Các em đọc phần viết về điểm mạnh của mình, ai cũng gồm cả em T đều có vẻ mặt ngại ngùng mà vui sướng.",
    explanation:"Đáp án 1. Ngay sau câu hỏi, lời em T:「だって、どうせ僕にはいいところなんてないもん」= làm gì có điểm tốt nào ở mình ⇒ vì không thấy được ưu điểm của chính mình. 2, 3, 4 không được nêu." },
  { id:"b11-2", passage:"", audioUrl:"", question:"58. 「いいところ探し」は、どのようにするのか。",
    options:["先生からもらった紙に、いいところのある友達の名前を書いて提出する。","先生からもらった紙に、クラス全員の名前といいところを書いて提出する。","クラス全員の名前のある紙に、一人ひとりの長所を書いて、先生に提出する。","クラス全員の名前のある紙に、長所がある友達について書いて、先生に提出する。"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 57) / Cách làm \"tìm điểm tốt\": viết ưu điểm của từng người lên phiếu có tên cả lớp rồi nộp cho giáo viên.",
    explanation:"Đáp án 3. Bài viết:「全員の名前を書いたプリントを配布した」「その人のいいところや、良さを見つけた場面などを書きましょう」「T男も全員分の長所の記入ができた」⇒ trên phiếu có tên cả lớp, viết ưu điểm của từng người rồi nộp. 2 sai (phiếu đã có tên cả lớp, không phải tự viết tên), 1, 4 sai (phải viết cho mọi người, không chỉ một số bạn)." },
  { id:"b11-3", passage:"", audioUrl:"", question:"59. 「いいところ探し」の目的は何か。",
    options:["T男のいいところをみんなに知ってもらい、T男が新しいクラスに馴染むようにすること","クラスのみんなが互いにほかの友達のことを知り、いいところを認め合うようにすること","誰も気づいていなかった友達の長所を見つけて書き、クラスの前で話せるようにすること","友達のいいところを探して書くことで、自分に足りなかったことに気づくようにすること"], answer:1,
    translation:"(Đoạn văn: xem bản dịch ở câu 57) / Mục đích của \"tìm điểm tốt\": để mọi người trong lớp hiểu nhau hơn và cùng công nhận điểm tốt của nhau.",
    explanation:"Đáp án 2. Câu then chốt:「友達のことを知ってほしい、長所を見つける目を持ってほしい、という意図で提案した」⇒ muốn các em hiểu về bạn và biết nhìn ra ưu điểm của bạn. 1 sai (chỉ là suy nghĩ riêng của giáo viên về em T), 3, 4 không được nêu." },
  { id:"b11-4", passage:"作り声は「本当の自分の姿を出したくない」という思いの表れでもあります。<br><br>（中略）<br><br>日本には、話す人が違ってもまるで同じ人であるかのような「職業声」があります。その仕事に就く人は「自分はこんな声にならないといけない」と思い込んでいるかのようです。<br><br>特に（注1）接客業や営業職に多く見られる職業声は、まるで声をマニュアルや制服と同じように扱っているように感じます。自分の本来の声を職業声で覆ってしまうことで、「仕事を言われたとおりにやっていますよ」「自分はこの仕事をする人になりきっていますよ」と暗に示しているのです。自分の個性を消して（注2）うわべの職業声で話すことは、厳しい見方をすれば、人間対人間の場面で、個人を放棄しているとも言えますね。個人の（注3）放棄は責任の放棄ともたやすく繋がります。<br><br>制服を着てしまうと組織の一員となって個人は消える。職業声も同じです。仕事に個性などいらないということでしょうか。しかし一日の三分の一は仕事をしているわけですから、その時間を制服のような借り物の声で話すことは、気楽ではあるかもしれないけれど、心身には大きな負担であろうと思います。<br><br>（注1）接客業：飲食店やホテルなどで客に接する職業　（注2）うわべの：表面的な　（注3）放棄する：捨てる",
    audioUrl:"", question:"60. 筆者は、人々がなぜ「職業声」を使うと思っているか。",
    options:["自分が仕事をするうえで求められていると思っているから","自分が仕事に慣れていると思われたいから","自分がその仕事に合わないと思われたくないから","自分の中で仕事のイメージを明確にできると思っているから"], answer:0,
    translation:"Giọng điệu nhân tạo cũng là biểu hiện của suy nghĩ \"không muốn để lộ con người thật của mình\". (Lược trung gian) Ở Nhật có \"giọng nghề nghiệp\" — dù người nói khác nhau nhưng nghe như cùng một người. Người làm nghề đó dường như tin chắc rằng \"mình phải dùng giọng này\". Giọng nghề nghiệp thường thấy nhiều ở nghề tiếp khách (chú thích 1) hay nghề kinh doanh, cảm giác như người ta đối xử với giọng nói y như sách hướng dẫn hay đồng phục. Bằng cách phủ giọng nghề nghiệp lên giọng thật của mình, họ ngầm cho thấy \"tôi đang làm việc đúng như được dặn\", \"tôi đang nhập vai thành người làm nghề này\". Việc xóa bỏ cá tính của mình và nói bằng giọng nghề nghiệp hời hợt (chú thích 2), nếu nhìn nghiêm khắc thì có thể nói là đang từ bỏ cá nhân trong quan hệ người với người. Việc từ bỏ (chú thích 3) cá nhân cũng dễ dàng gắn với việc từ bỏ trách nhiệm. Mặc đồng phục vào thì trở thành một thành viên của tổ chức và cá nhân biến mất. Giọng nghề nghiệp cũng vậy. Phải chăng nghĩa là công việc không cần cá tính? Nhưng vì một phần ba một ngày là làm việc, nên việc nói suốt thời gian đó bằng thứ giọng mượn như đồng phục thì dù có thể thoải mái, nhưng tôi nghĩ sẽ là gánh nặng lớn cho cả tinh thần lẫn thể xác.",
    explanation:"Đáp án 1. Câu then chốt:「その仕事に就く人は『自分はこんな声にならないといけない』と思い込んでいるかのようです」+「仕事を言われたとおりにやっていますよ」⇒ vì cho rằng khi làm nghề đó thì bị đòi hỏi phải dùng giọng như vậy. 2, 3, 4 không được nêu." },
  { id:"b11-5", passage:"", audioUrl:"", question:"61. 「職業声」で話すことについて、筆者はどのように考えているか。",
    options:["人との繋がりがなくなってしまう。","人に信用されなくなってしまう。","仕事に対する自信を失ってしまう。","個人としての自分を消してしまう。"], answer:3,
    translation:"(Đoạn văn: xem bản dịch ở câu 60) / Về việc nói bằng \"giọng nghề nghiệp\", tác giả cho rằng: làm mất đi chính bản thân mình với tư cách một cá nhân.",
    explanation:"Đáp án 4. Bài viết:「自分の個性を消してうわべの職業声で話すことは…個人を放棄しているとも言えます」⇒ xóa bỏ cá tính, từ bỏ chính mình với tư cách cá nhân. 1, 2, 3 không được nêu." },
  { id:"b11-6", passage:"（3）数年前、家を引っ越した。50年住み慣れた小さな家だったが、いざ引っ越しとなると、使っていない道具がごろごろ出てきて、あらためてものの多さにびっくりした。道具にしろ、本にしろずいぶん多量に所有していて、これを（注1）使いこなし、（注2）読みつくすには多量の時間がかかる。あと何年生きられるだろうと人生を逆算してみて、①この物量はムダだなあと引っ越しのトラックの助手席で考えた。<br><br>私は世間の人よりはものの所有欲が強いとは思っていない。むしろものをもたないほうだと思っているが、それでもものが多過ぎるのである。<br><br>昔、「預かりものの思想」と言った人がいる。人はぽつんと生まれて、ぷつんと消えていく。家や土地、道具にしても、いくら自分の所有だと力んでみても、死んでしまえばもっていけない。いずれは世の中に返していかなければならない。このわずかな人生の時間の中で、②それを楽しむしかないのだ。空気や水と同じように、土地も家も道具も、あらゆる諸物は世の中から預かって、生きている間だけ借りているのだ、という考えだった。たしかに、私たちはものへの所有欲が強い。車をもつ、家をもつ、高級ブランド品をもつ、携帯電話をもつ、コンピューターをもつ、所有することで満足感を得ている。しかし、所有欲をふくらませるには、どこかで限界があるだろう。「預かりものの思想」は、そういう（注3）物欲にかられる私たちに冷水をかける思想だった。<br><br>（注1）使いこなす：ここでは、すべて使う　（注2）読みつくす：すべて読む　（注3）物欲にかられる：物欲を抑えられなくなる",
    audioUrl:"", question:"62. ①この物量はムダだなあとあるが、筆者はなぜそう考えたのか。",
    options:["残された時間ですべてを利用することができないから","使っていない道具も一緒に運ばなければならないから","整理のために人生の貴重な時間がなわれるから","使わなくなったものがたくさんあるから"], answer:0,
    translation:"Vài năm trước, tôi chuyển nhà. Đó là căn nhà nhỏ đã sống quen suốt 50 năm, nhưng khi bắt tay vào chuyển thì những đồ vật không dùng cứ lần lượt xuất hiện, khiến tôi lại giật mình vì số lượng đồ đạc quá nhiều. Dù là dụng cụ hay sách, tôi sở hữu số lượng rất lớn, mà để dùng hết và đọc hết chúng thì cần rất nhiều thời gian. Tôi thử tính ngược lại xem còn sống được bao nhiêu năm nữa, và ngồi ở ghế phụ của xe tải chuyển nhà, tôi nghĩ: ①khối lượng đồ đạc này thật lãng phí. Tôi không nghĩ mình có lòng tham sở hữu đồ vật mạnh hơn người đời. Tôi cho rằng mình thuộc kiểu không giữ nhiều đồ, vậy mà vẫn quá nhiều. Xưa có người nói về \"tư tưởng của những thứ được gửi giữ\". Con người sinh ra lẻ loi, rồi cũng lặng lẽ biến mất. Dù là nhà, đất hay dụng cụ, có gắng gượng cho rằng đó là sở hữu của mình đi nữa, chết rồi thì cũng không mang theo được. Rồi cũng phải trả lại cho thế gian. Trong khoảng thời gian sống ngắn ngủi này, ②chỉ còn cách tận hưởng nó mà thôi. Đó là suy nghĩ rằng: cũng giống như không khí và nước, đất, nhà, dụng cụ, mọi vật đều là thứ ta nhận giữ từ thế gian, chỉ mượn trong lúc còn sống. Đúng là chúng ta có lòng ham muốn sở hữu mạnh mẽ…",
    explanation:"Đáp án 1. Trước chỗ gạch chân, tác giả viết:「これを使いこなし、読みつくすには多量の時間がかかる。あと何年生きられるだろうと人生を逆算してみて」⇒ vì thời gian còn lại không đủ để dùng hết/đọc hết chỗ đồ đó. 2, 3, 4 không đúng trọng tâm." },
  { id:"b11-7", passage:"", audioUrl:"", question:"63. ②それとは何を指すか。",
    options:["世の中","ものの貸し借り","所有しているもの","わずかな人生の時間"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 62) / \"Nó\" ở ② chỉ: những thứ mình đang sở hữu.",
    explanation:"Đáp án 3. Trước 「②それを楽しむしかない」 là đoạn nói về nhà, đất, dụng cụ — dù là sở hữu của mình cũng phải trả lại thế gian ⇒ 「それ」 chỉ những vật ngoài thân mà mình đang có. 世の中/ものの貸し借り không phải đối tượng để \"tận hưởng\", わずかな人生の時間 sai." },
  { id:"b11-8", passage:"", audioUrl:"", question:"64. 「預かりものの思想」では、ものをどのように考えているか。",
    options:["生きている間にすべて返さなければならない。","生きている間だけ世の中から借りている。","所有していてもいつかは消えてしまう。","所有するより借りたほうがいい。"], answer:1,
    translation:"(Đoạn văn: xem bản dịch ở câu 62) / Theo \"tư tưởng của những thứ được gửi giữ\", đồ vật được coi là: chỉ mượn từ thế gian trong lúc còn sống.",
    explanation:"Đáp án 2. Câu then chốt:「あらゆる諸物は世の中から預かって、生きている間だけ借りているのだ、という考えだった」⇒ mọi vật là thứ nhận giữ từ thế gian, chỉ mượn trong lúc sống. 1 sai (không nói phải trả hết ngay khi còn sống), 3, 4 không đúng nội dung." },
]},
{ tab:"読解", section:"問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction:"次は、森中市立図書館に張られている掲示（A）と、その図書館を利用している高校生が森中市に寄せた意見（B）である。AとBの両方を読んで、後の問いに対する答えとして、最もよいものを1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b12-1", passage:"【A】森中市立図書館の掲示<br><br>おねがい<br>図書館を使用される方へ<br><br>閲覧室に自分の教科書や参考書を持ってきて机の上に広げ、学校の宿題や試験勉強をする中学生や高校生の方がいます。そのような行為は図書館の本を利用される方にとって迷惑になりますので、ご遠慮くださるようお願いします。<br><br>図書館の机は図書館の資料を利用される方々のためのものです。<br><br>森中市立図書館<br><br>【B】高校生の意見<br><br>私は来年大学を受験する高校3年生です。受験に備えて勉強を始めていますが、夏休みに入り、しっかり勉強したいと思って家の近くの森中市立図書館に通うことにしました。家にいるとついテレビを見たり友達と電話をしたりして遊んでしまうからです。<br><br>ところが、その図書館には勉強禁止の張り紙がされているのです。図書館はたくさんの人が本を利用するための場所であり、勉強する場所ではありません。だから、本を使う人を優先するために、図書館の本を利用しない勉強を禁止するというのも分かります。<br><br>しかし、多くの人が私のように勉強をする場所として利用しているのです。図書館はもともと地域の住民へのサービス機関だと思います。それなら勉強する場所として、受験生も利用できていいと思うのです。<br><br>図書館の人は利用者が何を望んでいるのか、どうすればより利用しやすい図書館になるのかを常に考え、改善していくべきだと思います。",
    audioUrl:"", question:"65. Aの「森中市立図書館の掲示」は何を禁止しているのか。",
    options:["図書館の本の上に教科書を広げて勉強すること","図書館の本を使わないで試験勉強などをすること","中学生や高校生が図書館の閲覧室を利用すること","高校生が図書館の本を使って学校の宿題をすること"], answer:1,
    translation:"【A】Thông báo của thư viện thành phố Morinaka. Đề nghị. Gửi quý vị sử dụng thư viện. Có những học sinh trung học cơ sở và trung học phổ thông mang sách giáo khoa, sách tham khảo của mình đến phòng đọc, mở ra trên bàn để làm bài tập về nhà hoặc ôn thi. Những hành vi như vậy gây phiền toái cho những người sử dụng sách của thư viện, nên mong quý vị hãy tránh. Bàn của thư viện là dành cho những người sử dụng tài liệu của thư viện. Thư viện thành phố Morinaka. 【B】Ý kiến của học sinh trung học phổ thông. Tôi là học sinh lớp 12 sẽ dự kỳ thi đại học vào năm sau. Tôi bắt đầu học để chuẩn bị cho kỳ thi, và khi vào kỳ nghỉ hè, tôi muốn học cho tử tế nên quyết định đến thư viện thành phố Morinaka gần nhà. Vì ở nhà thì tôi lại xem tivi hay gọi điện cho bạn bè mà chơi mất. Thế nhưng, ở thư viện đó lại dán tờ giấy cấm học. Thư viện là nơi để nhiều người sử dụng sách, không phải nơi để học. Vì vậy, tôi hiểu việc cấm những hành vi học mà không dùng sách của thư viện, nhằm ưu tiên cho người sử dụng sách. Nhưng nhiều người, như tôi, đang sử dụng thư viện như một nơi để học. Tôi nghĩ thư viện vốn là cơ quan phục vụ cư dân địa phương. Nếu vậy thì với tư cách là nơi học, học sinh ôn thi cũng nên được sử dụng chứ. Tôi nghĩ nhân viên thư viện nên luôn suy nghĩ xem người sử dụng mong muốn điều gì, làm thế nào để thư viện dễ sử dụng hơn và cải tiến.",
    explanation:"Đáp án 2. A viết:「閲覧室に自分の教科書や参考書を持ってきて机の上に広げ、学校の宿題や試験勉強をする」行為は迷惑 ⇒ cấm việc học/ôn thi mà không dùng sách của thư viện. 1 sai (không phải cấm \"mở sách giáo khoa trên sách thư viện\"), 3 sai (không cấm học sinh vào phòng đọc), 4 sai (không cấm dùng sách thư viện)." },
  { id:"b12-2", passage:"", audioUrl:"", question:"66. Aの「森中市立図書館の掲示」とBの「高校生の意見」の内容について、正しいのはどれか。",
    options:["AはBのような考えを持った利用者が今後増えることを望んでいる。","BはAの「おねがい」を理解してはいるが、十分に納得はしていない。","Aでは中学生や高校生が図書館で勉強中に話すことが問題になっている。","Bは図書館に住民へのサービスとして受験用の本も置くよう希望している。"], answer:1,
    translation:"(Văn bản A/B: xem bản dịch ở câu 65) / Về nội dung của A và B: B hiểu \"đề nghị\" của A nhưng chưa hoàn toàn thỏa đáng/chấp nhận.",
    explanation:"Đáp án 2. B viết:「だから、本を使う人を優先するために…禁止するというのも分かります」⇒ hiểu cho A; nhưng sau「しかし」B phản đối và nêu mong muốn. 1 sai (A không hề mong điều đó), 3 sai (A không nói đến việc nói chuyện), 4 sai (B không yêu cầu đặt sách ôn thi)." },
]},
{ tab:"読解", section:"問題13 主張理解・長文",
  instruction:"次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b13-1", passage:"（注1）ネットワークにつながったコンピュータには「オフライン状態」と「オンライン状態」があります。オフライン状態のコンピュータは、外部と（注2）交信せずに、すでにインプットされている情報やソフトウェアを用いて作業しています。一方、オンライン状態のコンピュータは、インターネットなどで外部と交信しながら新しい情報やソフトウェアを取り入れながら作業します。人間にもまた、オフライン状態とオンライン状態があるようです。オフライン状態はいわば日常生活で、あまり新しいことを取り入れることはありませんが、オンライン状態では新しい情報を取り入れて、自分の行動や思考を変えていきます。<br><br>ぼくの場合、旅行に出ると自然にオンライン状態になります。いま住んでいる日本にいても当然、オンライン状態になることがありますが、旅に出れば、どちらを向いても新しい情報がたくさんあるので自然にオンラインになるのです。<br><br>動物は皆、（注3）本能にもとづいて習慣的に行動します。人間もまた動物で、強い習慣性があります。そして、習慣的なことに対しては、毎日の生活で疑問に感じることなどありません。しかし旅に出ると、非日常的な環境に放り出されます。そうすると、自分がいままであたりまえにやっていたことに疑問を抱くきっかけが生まれます。日々、あたりまえのようにやっていたことにも別なやり方があることに気づくのです。それがオフラインからオンラインになることにつながります。<br><br>旅先でなら、自分とは違うことをしている人を見て、単に「こいつらは変だ」とか「おかしい」と思うのではなく、「この国の人は皆こういうようにやっているようだから、（注4）一理あるんじゃないか」と考えることができ、（注5）ひいては「自分でもやってみようじゃないか」となります。そして、こういった経験を通して自分のそれまでのやり方、人生を考え直すことになるのです。<br><br>（中略）<br><br>「灯台下暗し」という諺があります。『広辞苑』によると「灯台（燭台）の直下はあかりが暗いように、（注6）手近の事情はかえってわかりにくいものである」とあります。ふだんの環境にあって自分の人生を考え直したり、（注7）おさらいしたりしようと思っても、それは難しいのです。だから、ちょっと離れて自分のことを考えるために旅に出るのです。<br><br>（注1）ネットワーク：ここでは、インターネットなど　（注2）交信する：通信し合う　（注3）本能：生まれつき持っている性質　（注4）一理ある：もっともな理由がある　（注5）ひいては：さらに　（注6）手近の：身近な　（注7）おさらいする：ここでは、振り返る",
    audioUrl:"", question:"67. 筆者によると、人間の「オフライン状態」とはどういう状態か。",
    options:["他人と交流したいと思わない。","コンピュータをあまり使わない。","新しいことをすることは少ない。","日常生活の中でしか新しいことを探さない。"], answer:2,
    translation:"Máy tính kết nối mạng (chú thích 1) có \"trạng thái offline\" và \"trạng thái online\". Máy tính ở trạng thái offline làm việc bằng thông tin và phần mềm đã được nhập sẵn, không giao tiếp (chú thích 2) với bên ngoài. Ngược lại, máy tính ở trạng thái online làm việc vừa giao tiếp với bên ngoài qua Internet… vừa tiếp nhận thông tin và phần mềm mới. Con người cũng dường như có trạng thái offline và online. Trạng thái offline nói cách khác là đời sống thường nhật, không tiếp thu nhiều điều mới, còn ở trạng thái online thì tiếp nhận thông tin mới và thay đổi hành động, suy nghĩ của mình. Với tôi, khi đi du lịch thì tôi tự nhiên ở trạng thái online… Động vật đều hành động theo thói quen dựa trên bản năng (chú thích 3). Con người cũng là động vật và có tính thói quen mạnh mẽ. Và với những việc mang tính thói quen thì trong sinh hoạt hàng ngày ta không hề thấy nghi ngờ gì. Nhưng khi đi du lịch, ta bị ném vào môi trường phi thường nhật. Khi đó, nảy sinh cơ hội để đặt nghi vấn về những việc mình vẫn làm một cách đương nhiên. Ta nhận ra rằng những việc vẫn làm như đương nhiên hàng ngày cũng có cách làm khác. Đó chính là điều dẫn từ offline sang online… Có câu ngạn ngữ \"tối dưới chân đèn\". Theo Từ điển Kōjien thì \"cũng như ngay dưới chân đèn (chân nến) thì ánh sáng lại tối, những việc gần gũi (chú thích 6) trái lại khó hiểu rõ\". Dù muốn suy nghĩ lại về cuộc đời mình hay nhìn lại (chú thích 7) nó trong môi trường quen thuộc thì cũng khó. Vì vậy, người ta đi du lịch để tách ra một chút mà nghĩ về bản thân.",
    explanation:"Đáp án 3. Câu then chốt:「オフライン状態はいわば日常生活で、あまり新しいことを取り入れることはありません」⇒ trạng thái offline = ít làm/tiếp thu điều mới. 1, 2, 4 không được nêu." },
  { id:"b13-2", passage:"", audioUrl:"", question:"68. 筆者によると、人間は旅に出るとどうなるか。",
    options:["自分とは違うやり方があることに気づく。","自分とは違うことをしている人を批判する。","自分のやり方が自分に合っているとわかる。","毎日の生活で感じた疑問を解決できる。"], answer:0,
    translation:"(Đoạn văn: xem bản dịch ở câu 67) / Theo tác giả, khi đi du lịch thì con người: nhận ra rằng có cách làm khác với cách của mình.",
    explanation:"Đáp án 1. Câu then chốt:「日々、あたりまえのようにやっていたことにも別なやり方があることに気づくのです」⇒ nhận ra có cách làm khác. 2 sai (bài nói KHÔNG nên chỉ nghĩ \"lạ thật\"/\"kỳ quặc\"), 3, 4 không được nêu." },
  { id:"b13-3", passage:"", audioUrl:"", question:"69. 旅について、筆者の考えに合うのはどれか。",
    options:["自分の知識を広げるために、旅をするといい。","忙しい日常生活を忘れるために、旅は必要だ。","旅によって、自分の人生を見つめ直すことができる。","旅をたくさんすれば、自分の人生を変えることができる。"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 67) / Về du lịch, quan điểm của tác giả: nhờ du lịch mà có thể nhìn lại cuộc đời mình.",
    explanation:"Đáp án 3. Câu then chốt:「こういった経験を通して自分のそれまでのやり方、人生を考え直すことになるのです」⇒ nhờ du lịch mà nhìn lại cuộc đời mình. 1, 2 không được nêu; 4 sai (bài chỉ nói \"nhìn lại\", không nói \"thay đổi\")." },
]},
{ tab:"読解", section:"問題14 情報検索",
  instruction:"右のページは、あるスーパーマーケットの宅配サービスの案内である。下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b14-1", passage:"スーパー森下の宅配サービス<br><br>スーパー森下の会員（一般会員、シニア会員）のお客様が、スーパー森下でお買い求めになった常温の商品を、ご自宅まで配達いたします。ご利用を希望されるお客様は、1階サービスカウンターまでお越しください。<br><br>＊冷蔵・冷凍の商品は宅配サービスの対象外です。<br>＊専用の箱（縦35cm×横50cm×高さ30cm）で配達いたします。<br><br>【会員の種類と利用条件】<br>・一般会員：お買い物の合計金額3,000円以上で、ご利用になれます。<br>・シニア会員：お買い物の合計金額1,000円ごとに、1箱ご利用になれます。<br>・一般会員、シニア会員ともに、送ることができるのは3箱までです。<br>・お買い物の合計金額（宅配サービス対象外の物も含む）が、上の金額未満の場合、宅配サービスはご利用になれません。<br><br>【配達対象地域】<br>・中区：岩長町全域、緑町全域、花森町1丁目〜5丁目<br>・北区：朝春町全域、千京町3丁目〜6丁目<br>・南区：平川町1丁目〜3丁目<br><br>【配達受付と配達時間】<br>・受付：開店（午前10時）から正午まで → 配達：[A]当日午後1時〜5時／[B]当日午後5時〜9時<br>・受付：正午から午後4時まで → 配達：[A]当日午後5時〜9時／[B]翌日の午前9時〜正午<br>・受付：午後4時から閉店（午後10時）まで → 配達：[A]翌日の午前9時〜正午／[B]翌日の午後1時〜9時<br>・配達時間は、[A][B]どちらかの時間が選べます。<br><br>【ご利用方法】<br>1. レジでご精算のあと、配達をご希望の商品を1階サービスカウンターにお持ちください。<br>2. 専用の箱に配達をご希望の商品を入れ、会員カードとレシートを見せ、配達受付をしてください。",
    audioUrl:"", question:"70. 次の4人は、スーパー森下で買い物を終えたところで、買った商品を自宅まで届けてほしいと考えている。この中で、店の宅配サービスを利用できるのは誰か。<br><br>① リーさん／南区半川町2丁目／非会員／5,232円／3箱分<br>② 川口さん／中区緑町4丁目／一般会員／2,546円／2箱分<br>③ ハリスさん／北区千京町1丁目／シニア会員／2,179円／1箱分<br>④ 高橋さん／北区朝春町5丁目／シニア会員／1,630円／1箱分",
    options:["リーさん","川口さん","ハリスさん","高橋さん"], answer:3,
    translation:"Dịch vụ giao hàng của siêu thị Morishita. Siêu thị Morishita sẽ giao đến tận nhà cho khách là hội viên (hội viên thường, hội viên cao tuổi) những sản phẩm ở nhiệt độ thường mà khách đã mua tại siêu thị. Khách muốn sử dụng xin đến quầy dịch vụ ở tầng 1. ＊Hàng lạnh, hàng đông lạnh không thuộc đối tượng của dịch vụ. ＊Giao bằng thùng chuyên dụng (dọc 35cm × ngang 50cm × cao 30cm). 【Điều kiện sử dụng】Hội viên thường: tổng số tiền mua từ 3.000 yên trở lên. Hội viên cao tuổi: cứ mỗi 1.000 yên trong tổng số tiền mua thì được 1 thùng. Cả hai loại đều tối đa 3 thùng. Nếu tổng tiền mua (kể cả các mặt hàng không thuộc dịch vụ) thấp hơn mức trên thì không dùng được dịch vụ. 【Khu vực giao hàng】Quận Trung: toàn bộ Iwanaga, toàn bộ Midori, Hanamori 1–5. Quận Bắc: toàn bộ Asaharu, Senkyō 3–6. Quận Nam: Hirakawa 1–3. 【Tiếp nhận và thời gian giao】Tiếp nhận từ mở cửa (10 giờ sáng) đến 12 giờ trưa → [A] 13h–17h cùng ngày / [B] 17h–21h cùng ngày. Tiếp nhận từ 12h trưa đến 16h → [A] 17h–21h cùng ngày / [B] 9h–12h hôm sau. Tiếp nhận từ 16h đến khi đóng cửa (22h) → [A] 9h–12h hôm sau / [B] 13h–21h hôm sau. Chọn được [A] hoặc [B]. 【Cách sử dụng】Sau khi thanh toán ở quầy thu ngân, mang hàng muốn gửi đến quầy dịch vụ tầng 1; cho hàng vào thùng chuyên dụng, xuất trình thẻ hội viên và hóa đơn để làm thủ tục.",
    explanation:"Đáp án 4 (anh Takahashi). ① Loại vì không phải hội viên. ② Loại vì là hội viên thường nhưng tổng tiền 2.546 yên < 3.000 yên. ③ Loại vì địa chỉ 千京町**1丁目** không nằm trong khu vực giao hàng (chỉ 3–6丁目). ④ Hội viên cao tuổi, 1.630 yên ⇒ đủ 1.000 yên để được 1 thùng, địa chỉ 朝春町 thuộc khu vực giao hàng, 1 thùng ≤ 3 thùng ⇒ hợp lệ ✓" },
  { id:"b14-2", passage:"", audioUrl:"", question:"71. 加山さんは一般会員で、この宅配サービスが利用可能である。今日、水などの常温の商品と冷凍食品を買うつもりである。明日の午前中に商品を届けてもらいたい。送れるのは何で、受付は何時から何時までに済ませなければならないか。",
    options:["常温の商品で、午前10時から午後4時までに済ませる。","常温の商品で、正午から午後10時までに済ませる。","常温の商品と冷凍の商品で、午前10時から午後4時までに済ませる。","常温の商品と冷凍の商品で、正午から午後10時までに済ませる。"], answer:1,
    translation:"(Tài liệu: xem bản dịch ở câu 70) / Anh Kayama là hội viên thường và có thể dùng dịch vụ giao hàng này. Hôm nay anh định mua nước… là hàng nhiệt độ thường và cả thực phẩm đông lạnh. Anh muốn hàng được giao vào buổi sáng ngày mai. Có thể gửi loại hàng nào và phải hoàn tất tiếp nhận từ mấy giờ đến mấy giờ.",
    explanation:"Đáp án 2. (1) Loại hàng: dịch vụ chỉ áp dụng cho 常温の商品, hàng 冷蔵・冷凍 không thuộc đối tượng ⇒ loại 3 và 4. (2) Thời gian tiếp nhận: muốn nhận buổi sáng ngày mai thì khung [B] 翌日の午前9時〜正午 ứng với tiếp nhận「正午から午後4時まで」hoặc「午後4時から閉店（午後10時）まで」⇒ khoảng「正午から午後10時まで」⇒ đáp án 2." },
]},
/* ================= TAB 5: 聴解 ================= */
{ tab:"聴解", section:"問題1 課題理解",
  instruction:"問題1では、まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File kèm theo đề này có đầy đủ 台本/script chính thức — nội dung hội thoại được đưa vào phần「Đoạn」; audio gốc không có trong file.)",
  questions:[
  { id:"c1-1", passage:"【台本】音楽教室の事務室で女の社員と男の社員が話しています。<br><br>女：あの、ちょっと頼みたいことがあるんだけど。<br>男：何でしょうか。<br>女：初級ギターのグループレッスンを受講している山田さんから電話があって、次のレッスンから曜日を日曜から土曜日のクラスに変更したいって。土曜日も初級クラスは同じ木村先生が担当なんだけどね。<br>男：じゃ、まず希望するクラスが空いているか確認しましょうか。<br>女：あ、それは大丈夫だった。ただ、テキストと先生が同じでも、クラスによって進む速さが違う場合もあるでしょう。山田さんに次に何をやるのかって聞かれて。<br>男：はい。<br>女：それで、先生に電話して確かめてもらえないかな。で、それを山田さんに伝えてくれる？今日、私早退するので。<br>男：わかりました。<br>女：山田さんへの連絡が済んだら、受講生の名簿の修正もしといてもらえると助かるんだけど。<br>男：はい。",
    audioUrl:"", question:"1番：男の社員はこの後、まず何をしますか。", options:["土曜クラスに空きがあるか調べる","山田さんにれんらくする","木村先生に電話する","じゅこう者リストを直す"], answer:2,
    translation:"(Script) Ở phòng hành chính của lớp học nhạc, nữ và nam nhân viên nói chuyện. Nữ: Tôi muốn nhờ anh một việc. Nam: Việc gì vậy? Nữ: Anh Yamada đang học lớp guitar sơ cấp gọi đến, muốn đổi ngày học từ Chủ nhật sang lớp thứ Bảy. Lớp sơ cấp thứ Bảy cũng do thầy Kimura phụ trách. Nam: Vậy trước tiên để tôi kiểm tra xem lớp mong muốn còn chỗ không nhé. Nữ: À, cái đó ổn rồi. Nhưng dù cùng giáo trình và cùng thầy, tốc độ học giữa các lớp có thể khác nhau. Anh Yamada hỏi tiếp theo sẽ học gì. … Thế nên, anh gọi điện cho thầy xác nhận giúp tôi được không. Rồi truyền đạt lại cho anh Yamada nhé? Hôm nay tôi về sớm. Nam: Vâng. Nữ: Sau khi liên lạc với anh Yamada xong thì sửa lại danh sách học viên giúp tôi thì tốt quá.",
    explanation:"Đáp án 3. Nữ nói:「それで、先生に電話して確かめてもらえないかな」⇒ việc đầu tiên là gọi điện cho thầy Kimura để xác nhận. 1 đã xong (「あ、それは大丈夫だった」), 2 là việc sau đó, 4 là việc cuối cùng." },
  { id:"c1-2", passage:"【台本】公園で職員が花壇を作るボランティアの人に話しています。<br><br>男：午後のボランティアの皆さん、よろしくお願いします。午前の方には雑草を抜いて、花壇の整備をしていただきました。午後は花の苗を植えていただきます。苗と苗は間隔をあけて植えていくので、今からこちらの職員が植える場所の目印を付けていきます。その間に、皆さんには私と一緒にそちらの倉庫から花の苗を運んでいただきます。とりあえず、花壇の前に置いていってください。その後、職員が付けた目印に合わせて苗を並べていきます。",
    audioUrl:"", question:"2番：ボランティアの人はまず何をしますか。", options:["雑草をぬく","なえをうえる位置の目印を付ける","そうこからなえを運ぶ","目印に合わせてなえを並べる"], answer:2,
    translation:"(Script) Ở công viên, nhân viên nói với các tình nguyện viên làm bồn hoa. Nam: Chào các tình nguyện viên buổi chiều. Buổi sáng mọi người đã nhổ cỏ và chỉnh trang bồn hoa. Buổi chiều chúng ta trồng cây hoa. Vì trồng cách quãng nên nhân viên bên tôi sẽ đánh dấu vị trí trồng từ bây giờ. Trong lúc đó, mọi người cùng tôi vận chuyển cây hoa từ kho kia ra. Trước mắt cứ để trước bồn hoa. Sau đó sẽ xếp cây theo các dấu mà nhân viên đã đánh.",
    explanation:"Đáp án 3. Nhân viên nói:「その間に、皆さんには私と一緒にそちらの倉庫から花の苗を運んでいただきます」⇒ việc đầu tiên của tình nguyện viên là vận chuyển cây từ kho. 1 là việc buổi sáng, 2 do nhân viên làm, 4 là việc sau đó." },
  { id:"c1-3", passage:"【台本】女の留学生と男の留学生が話しています。<br><br>女：いよいよ卒業だね。国に帰るんで、家具とか電気製品いらなくなるんだけど、どうしたらいいかな。<br>男：僕の場合は、アルバイト先の友達に譲るんだ。<br>女：それはいいね。私のもまだ十分使えるから、捨てるのもったいなくて。<br>男：この間、大学の掲示板で見たんだけど、先輩の家具を引き取って新入生にあげる活動をしているボランティア団体があるんだって。連絡すれば、取りに来てくれるから、そこに寄付すれば。<br>女：へー、いいね。<br>男：それか、リサイクルショップに売るっていうのもいいよね。あー、だけど、電気製品の古いのは買い取ってくれないかも。<br>女：そうなんだ。あっ、インターネットでの販売はどう？写真載せて、買いたい人と直接やり取りするやつ。<br>男：あ、それは避けたほうがいいと思うよ。受け渡しとか、お金のこととか、トラブルもあるって聞くし。<br>女：そうか。<br>男：やっぱり、新入生に喜んでもらうのがいいんじゃない。<br>女：うん、じゃ、そうしよう。",
    audioUrl:"", question:"3番：女の留学生はいらなくなったものをどうしますか。", options:["アルバイト先の友達にゆずる","ボランティア団体にきふする","リサイクルショップに売る","インターネットで売る"], answer:1,
    translation:"(Script) Nữ du học sinh và nam du học sinh nói chuyện. Nữ: Sắp tốt nghiệp rồi nhỉ. Mình về nước nên đồ đạc, đồ điện không cần nữa, biết làm sao đây. Nam: Mình thì cho bạn ở chỗ làm thêm. Nữ: Hay nhỉ. Đồ của mình vẫn dùng được nên vứt đi thì tiếc. Nam: Hôm trước mình thấy trên bảng tin của trường có một tổ chức tình nguyện nhận đồ của khóa trên rồi tặng cho sinh viên mới. Liên lạc là họ đến lấy, cứ quyên góp cho họ. Nữ: Ồ hay đấy. Nam: Hoặc bán cho cửa hàng đồ tái chế cũng được. À nhưng đồ điện cũ có thể họ không mua. Nữ: Vậy à. À, bán qua Internet thì sao? Đăng ảnh rồi trao đổi trực tiếp với người muốn mua. Nam: Cái đó nên tránh. Nghe nói giao nhận, tiền nong cũng có rắc rối. Nữ: Thế à. Nam: Dù sao làm sinh viên mới vui thì tốt hơn chứ. Nữ: Ừ, vậy làm thế đi.",
    explanation:"Đáp án 2. Cuối cùng nữ nói:「じゃ、そうしよう」sau khi nam gợi ý「新入生に喜んでもらうのがいいんじゃない」⇒ quyên góp cho tổ chức tình nguyện. 1 là cách của nam, 3 bị loại (đồ điện cũ có thể không được mua lại), 4 bị loại." },
  { id:"c1-4", passage:"【台本】大学で、学生と先生がスピーチの原稿について話しています。<br><br>女：先生、昨日スピーチの原稿を送らせていただいたんですが。<br>男：あー、はい、見ましたよ。<br>女：いかがでしょうか。全体の構成があまりよくないんじゃないかと思うんですが。<br>男：うん、構成は悪くないと思いますよ。わかりやすく書けていますし。ただ、導入の部分、詳しく書いてあっていいんですが、全体の長さを考えると、もう少し簡潔にしたほうがいいですね。<br>女：あ、長いですか。真ん中の私の経験を書いた部分ももう少し短くしたほうがいいでしょうか。<br>男：うん、具体的な経験が書いてある部分は大事なところなので、このままでいいと思いますよ。<br>女：そうですか。最後のまとめの部分はどうでしょうか。<br>男：自分の意見をまとめてあって、よく書けてますよ。ここはもう少し長くてもいいような気がしますが、全体がこれ以上長くなると良くないので、とりあえず、このままにしましょう。<br>女：はい、わかりました。じゃ、すぐ直します。ありがとうございました。",
    audioUrl:"", question:"4番：学生はまず原稿のどこを直しますか。", options:["全体のこうせい","どうにゅうの部分","経験を書いた部分","まとめの部分"], answer:1,
    translation:"(Script) Ở trường đại học, sinh viên và giáo viên nói về bản thảo bài phát biểu. Nữ: Thưa thầy, hôm qua em đã gửi bản thảo bài phát biểu. Nam: À vâng, thầy xem rồi. Nữ: Thế nào ạ? Em nghĩ bố cục tổng thể chưa tốt lắm. Nam: Ừ, bố cục không tệ đâu. Viết dễ hiểu mà. Nhưng phần mở đầu, viết chi tiết thì tốt, mà xét độ dài tổng thể thì nên ngắn gọn hơn. Nữ: À, dài quá ạ? Phần giữa viết về trải nghiệm của em cũng nên ngắn lại chứ ạ? Nam: Ừ, phần trải nghiệm cụ thể là phần quan trọng nên cứ để nguyên. Nữ: Vậy ạ. Phần tổng kết cuối thì sao ạ? Nam: Em tổng hợp ý kiến của mình, viết tốt. Phần này dài hơn chút cũng được, nhưng cả bài dài thêm nữa thì không tốt, nên tạm thời cứ để nguyên. Nữ: Vâng, em hiểu rồi. Vậy em sửa ngay ạ.",
    explanation:"Đáp án 2. Thầy nói:「導入の部分…もう少し簡潔にしたほうがいいですね」⇒ phần cần sửa đầu tiên là phần mở đầu (導入). Các phần khác thầy nói giữ nguyên." },
  { id:"c1-5", passage:"【台本】男の人と女の人がコンピューターを見ながら飛行機の席を選んでいます。（Đề gốc in kèm sơ đồ ghế máy bay với 4 vị trí đánh số 1〜4; không thể tái hiện hình sơ đồ trong file dữ liệu này.)<br><br>女：この白いのが空いている席ってことですよね。<br>男：あー、そうだね。窓側がゆっくりできるからいいんだけど、並んで座れるところあるかな。できれば打ち合わせもしたいし。<br>女：そうですね。一つが窓側で、しかも並べるところですと、一番後ろになりますね。<br>男：でも、一番後ろって、座席が倒せないから、苦しいんだよね。<br>女：あー、そうなんですか。じゃ、あと、並んで座れるのはこの通路側のところですね。<br>男：うん、仕方ないか。<br>女：窓側だと、ここに一つ空いてますね。<br>男：うん。<br>女：私はその斜め前の席にしますよ。もしかしたら、私の隣の人が課長の席と変わってくれるかもしれないですから。<br>男：そうだね。そうしたら並べるか。じゃ、そうしよう。",
    audioUrl:"", question:"5番：男の人はどの席を選ぶことにしますか。", options:["座席①","座席②","座席③","座席④"], answer:3,
    translation:"(Script) Nam và nữ vừa nhìn máy tính vừa chọn ghế máy bay. Nữ: Cái màu trắng là ghế trống nhỉ. Nam: À đúng rồi. Ghế cạnh cửa sổ thì thư giãn, nhưng có chỗ nào ngồi cạnh nhau không nhỉ. Nếu được thì muốn bàn công việc luôn. Nữ: Vừa cạnh cửa sổ lại vừa ngồi cạnh nhau thì chỉ có hàng cuối cùng. Nam: Nhưng hàng cuối thì ghế không ngả được, mệt lắm. Nữ: Vậy còn chỗ ngồi cạnh nhau là chỗ phía lối đi này. Nam: Ừ, biết làm sao được. Nữ: Còn cạnh cửa sổ thì ở đây còn một chỗ trống. Nam: Ừ. Nữ: Em sẽ ngồi ghế chéo phía trước đó. Biết đâu người ngồi cạnh em sẽ đổi với ghế của trưởng phòng. Nam: Nhỉ. Vậy thì ngồi cạnh nhau được. Vậy làm thế đi.",
    explanation:"Đáp án 4. Nam chọn ghế cạnh cửa sổ (窓側) — vì nữ sẽ ngồi chéo phía trước để có thể đổi chỗ với người bên cạnh, nhờ đó hai người ngồi cạnh nhau được. Trong sơ đồ của đề, đó là vị trí ④. ①② là ghế phía lối đi, ③ là hàng cuối (ghế không ngả được)." },
]},
{ tab:"聴解", section:"問題2 ポイント理解",
  instruction:"問題2では、まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c2-1", passage:"【台本】女の人と男の人が話しています。<br><br>女：これ、な〜に？<br>男：トマトだよ。最近作り始めたんだ。<br>女：ええ〜、おいしそうねえ。でも、どうして？農薬とか心配だから？<br>男：そうだね。外で買う野菜はたくさん農薬がかかってるから、うちで作ったほうが安心だって言う人も多いよね。でも、まあ、ぼくはあまり気にしてないんだけど。<br>女：へえ〜、じゃあ、家計の節約？<br>男：はははは、これぐらいじゃ、節約にならないよ。これは、息子がなにか野菜を作りたいって言って、やってるんだ。<br>女：へえ〜、たしか小学生だよね。すごいね。",
    audioUrl:"", question:"1番：男の人がうちでトマトを育てているのはどうしてですか。", options:["おいしい野菜を食べたいから","家で作る方が安心だから","せつやくしたいから","こどもが育てたいと言ったから"], answer:3,
    translation:"(Script) Nữ: Cái này là gì thế? Nam: Cà chua đấy. Gần đây mình bắt đầu trồng. Nữ: Ồ, trông ngon nhỉ. Nhưng sao lại trồng? Vì lo thuốc trừ sâu à? Nam: Nhiều người nói rau mua ngoài bị phun nhiều thuốc nên trồng ở nhà yên tâm hơn. Nhưng mình thì không để ý lắm. Nữ: Vậy là để tiết kiệm chi tiêu gia đình? Nam: Haha, chừng này thì chẳng tiết kiệm được gì. Cái này là vì con trai mình nói muốn trồng rau gì đó nên mình làm. Nữ: Ồ, chắc còn học tiểu học nhỉ. Giỏi thật.",
    explanation:"Đáp án 4. Nam nói:「これは、息子がなにか野菜を作りたいって言って、やってるんだ」⇒ vì con trai nói muốn trồng. 1, 2, 3 là những lý do bị phủ định trong hội thoại." },
  { id:"c2-2", passage:"【台本】大学で、女の学生と男の学生が話しています。<br><br>女：高橋くん、今晩一緒にご飯食べに行かない。<br>男：悪い。夜はレストランでウェイターのバイトなんだ。<br>女：あれ？高橋くん、塾の講師やってるって言ってなかった？<br>男：うん、これから就職の準備で忙しくなるから、今月からバイト換えたんだ。塾は時給もいいし、楽しかったんだけどね。<br>女：塾のシフト、減らしてもらえばよかったんじゃない？<br>男：塾で一緒に働いていた友達にもそう言われたんだけど、塾って、決まった曜日と時間、あけておかなきゃいけないでしょ。面接が入ったり、先輩と会ったりするから、スケジュールが流動的でも、対応できる方がいいと思って、今のバイト先は、一週間ごとに予定を提出すればいいんだ。<br>女：そっか。新しい仕事だと、覚えることも多くて大変そうだね。<br>男：まあ、これもいい経験だよ。",
    audioUrl:"", question:"2番：男の学生はどうしてアルバイト先をレストランに換えたと言っていますか。", options:["夜間の時給が高いから","友人といっしょに働けて楽しいから","自分の都合に合わせて働きやすいから","経験があってなれている仕事だから"], answer:2,
    translation:"(Script) Nữ: Takahashi, tối nay đi ăn cơm không? Nam: Xin lỗi, tối mình làm bồi bàn ở nhà hàng. Nữ: Ơ? Chẳng phải cậu nói đang làm gia sư ở lò luyện thi à? Nam: Ừ, sắp tới chuẩn bị tìm việc sẽ bận nên từ tháng này mình đổi việc làm thêm. Ở lò luyện thi lương giờ cũng tốt và vui, nhưng… Nữ: Vậy giảm ca ở đó đi chẳng phải hơn à? Nam: Bạn làm cùng ở đó cũng nói vậy, nhưng lò luyện thi thì phải để trống ngày giờ cố định. Vì mình có phỏng vấn, gặp tiền bối, nên lịch có thể thay đổi mà vẫn xoay được thì tốt hơn. Chỗ làm hiện tại chỉ cần nộp lịch mỗi tuần. Nữ: Ra vậy. Việc mới chắc phải nhớ nhiều thứ nên vất vả nhỉ. Nam: Ừ, nhưng đây cũng là trải nghiệm tốt.",
    explanation:"Đáp án 3. Nam nói:「スケジュールが流動的でも、対応できる方がいいと思って、今のバイト先は、一週間ごとに予定を提出すればいいんだ」⇒ vì dễ sắp xếp theo lịch phát sinh của bản thân. 1, 2 bị phủ định (塾 mới là nơi lương giờ tốt và vui), 4 không được nêu." },
  { id:"c2-3", passage:"【台本】大学の日本語のクラスで先生が留学生に話しています。<br><br>この間書いてもらったレポートを返します。環境問題について自分の考察を書きましたね。引用した資料は、みなさん信頼できるものを使って書けていました。ただ、考察が自分の考えなのか、資料にある文を引用したのかが曖昧なレポートが多く見られたので、次からはこの点に気をつけましょう。授業で注意した文体の統一については、話し言葉がまざることはなく、書けていました。前回は決められた文字数を超える人がいましたが、今回はみなさん決められた文字数の中でうまくまとめられていました。",
    audioUrl:"", question:"3番：先生はレポートで何ができていない人が多かったと言っていますか。", options:["しんらいできるデータを使って書くこと","引用と自分の考えを区別して書くこと","文体をとういつして書くこと","決められた文字数で書くこと"], answer:1,
    translation:"(Script) Giáo viên: Thầy trả lại bài báo cáo các em viết hôm trước. Các em đã viết suy nghĩ của mình về vấn đề môi trường. Tài liệu trích dẫn thì các em đều dùng loại đáng tin cậy. Tuy nhiên, có nhiều bài mà không rõ phần nhận xét là suy nghĩ của mình hay là trích câu trong tài liệu, nên từ lần sau các em chú ý điểm này. Về việc thống nhất văn phong mà thầy đã lưu ý, các em viết không bị lẫn văn nói. Lần trước có người vượt số chữ quy định, lần này các em đều tóm gọn trong số chữ quy định.",
    explanation:"Đáp án 2. Thầy nói:「考察が自分の考えなのか、資料にある文を引用したのかが曖昧なレポートが多く見られた」⇒ nhiều bài không phân biệt được trích dẫn và ý kiến của bản thân. 1, 3, 4 đều là những điểm thầy nói đã làm được." },
  { id:"c2-4", passage:"【台本】フリーマーケットの会場で、女の学生と男の学生が話しています。<br><br>女：フリーマーケット一日目、お疲れ様。服、予想以上に売れたね。<br>男：うん。シャツとかズボンとか、服の種類サイズ別に分けて見やすく並べたのが、よかったんじゃない。<br>女：そうだね。あしたはどうしようか。今日、隣の店が色ごとに分けてたのを見て、見た目きれいだから、あんな並べ方するのもいいかなって思ったんだ。<br>男：うーん、色の種類がそんなにあるわけじゃないし、そこまでしなくていいよ。それより、値段もうすこし高い設定でもよかったかも。<br>女：でも、お客さん喜んでくれてたよ。値札は変えなくていいんじゃない。<br>男：じゃあ、そのままでいいか。そういえば、値段が高いのから安いのまでごちゃごちゃにおいてたのはよくなかったかもしれないね。<br>女：そうだね。サイズ別に分けて、それをさらに値段の順番で並べてみる？お客さんにしたら、そのほうがいいかな。<br>男：じゃ、明日の朝、早めに来て取り掛かろう。",
    audioUrl:"", question:"4番：二人はあした新たに何をすることにしましたか。", options:["商品をサイズ別にならべる","商品を色別にならべる","値札のきんがくを高く書き変える","商品を値段の順にならべる"], answer:3,
    translation:"(Script) Ở hội chợ đồ cũ. Nữ: Ngày đầu chợ trời, vất vả rồi. Quần áo bán được hơn dự đoán nhỉ. Nam: Ừ. Việc chia theo loại và kích cỡ, xếp dễ nhìn có lẽ hiệu quả. Nữ: Nhỉ. Mai làm gì đây? Hôm nay thấy cửa hàng bên cạnh chia theo màu, trông đẹp nên mình nghĩ xếp kiểu đó cũng được. Nam: Ừm, số màu không nhiều lắm nên không cần đến thế. Hơn nữa, giá đặt cao hơn chút có lẽ tốt hơn. Nữ: Nhưng khách vui mà. Không cần đổi giá đâu. Nam: Vậy cứ để nguyên. Nghĩ lại thì việc để lẫn lộn từ đắt đến rẻ chưa chắc đã tốt. Nữ: Nhỉ. Hay là chia theo kích cỡ rồi xếp thêm theo thứ tự giá? Với khách thì như vậy có lẽ tốt hơn. Nam: Vậy sáng mai đến sớm làm nhé.",
    explanation:"Đáp án 4. Nữ đề xuất:「サイズ別に分けて、それをさらに値段の順番で並べてみる？」và nam đồng ý⇒ việc mới là xếp theo thứ tự giá. 1 đã làm hôm nay, 2 bị nam phủ định, 3 bị nữ phủ định." },
  { id:"c2-5", passage:"【台本】ラジオでアナウンサーが店の紹介をしています。<br><br>ええ、今朝は最近話題になっているお店に来ています。お店に入りますと、まるでカフェのような落ち着いた雰囲気です。店内には、プレゼント用の箱が並んでいます。お菓子が入っていそうな箱や、宝石箱のようなものもあります。私もまさかこの箱に花が入っているとは思いませんでした。カフェのような店ですし、箱にはコーヒーが入っていると思われる方も多いそうです。",
    audioUrl:"", question:"5番：この店で売っている箱には何が入っていますか。", options:["コーヒー","花","おかし","ほうせき"], answer:1,
    translation:"(Script) Trên radio, phát thanh viên giới thiệu một cửa hàng. Sáng nay tôi đang ở một cửa hàng đang được bàn tán gần đây. Bước vào thì không khí tĩnh lặng như quán cà phê. Trong tiệm bày những chiếc hộp để làm quà tặng. Có hộp trông như đựng bánh kẹo, có hộp như hộp trang sức. Tôi cũng không ngờ chiếc hộp này lại đựng hoa. Vì là cửa hàng như quán cà phê nên nhiều người nghĩ hộp đựng cà phê.",
    explanation:"Đáp án 2. Người dẫn nói:「私もまさかこの箱に花が入っているとは思いませんでした」⇒ hộp đựng hoa. 1 là điều nhiều người lầm tưởng, 3, 4 chỉ là so sánh hình thức (trông như đựng bánh/trang sức)." },
  { id:"c2-6", passage:"【台本】ラジオで女のアナウンサーと社長が話しています。<br><br>女：田中社長、経営者という立場は、ストレスが多いと伺いますが、どうやってストレスを解消していらっしゃるんですか。<br>男：そうですね。若い頃は、仲間と一緒にサッカーをして一杯やって、翌朝にはスッキリ、ストレス解消していましたが。<br>女：ああ、サッカーですか。<br>男：最近は、友人がランニングを始めて、体にもいいし、汗も流して、ストレス解消にもなるからって、勧められたんですけど、なかなか…で、毎日一時間ほど歩くことにしてみたんです。<br>女：そうですか。<br>男：家内も一緒に始めたんですよ。体を動かしながら、いろいろ話をするようになって、それがけっこう楽しくてね。たいていの嫌なことは忘れられるんです。今では家族と旅行に行ったときも、旅行先で楽しんでいます。",
    audioUrl:"", question:"6番：社長は今どうやってストレスを解消していますか。", options:["仲間とサッカーをする","ランニングをして汗を流す","妻とウォーキングをする","家族と旅行に行く"], answer:2,
    translation:"(Script) Trên radio, nữ phát thanh viên nói chuyện với giám đốc. Nữ: Thưa giám đốc Tanaka, nghe nói ở cương vị người quản lý thì nhiều căng thẳng, ngài giải tỏa căng thẳng thế nào ạ? Nam: Hồi trẻ thì tôi cùng bạn bè đá bóng rồi uống một chút, sáng hôm sau sảng khoái, giải tỏa hết. Nam: Gần đây bạn tôi khuyên chạy bộ vì tốt cho sức khỏe, ra mồ hôi, giải tỏa căng thẳng… nhưng khó quá, nên tôi thử đi bộ khoảng một tiếng mỗi ngày. Vợ tôi cũng bắt đầu đi cùng. Vừa vận động vừa nói chuyện nhiều thứ, khá vui. Hầu hết những điều khó chịu đều quên được. Giờ đi du lịch với gia đình thì cũng tận hưởng ở nơi đến.",
    explanation:"Đáp án 3. Ông nói:「毎日一時間ほど歩くことにしてみたんです」「家内も一緒に始めたんですよ」⇒ hiện tại là đi bộ (walking) cùng vợ. 1 là cách thời trẻ, 2 bị từ chối (「なかなか…」), 4 chỉ là việc đi du lịch chứ không phải cách giải tỏa." },
]},
{ tab:"聴解", section:"問題3 概要理解",
  instruction:"問題3では、問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c3-1", passage:"【台本】学校の事務室で事務の人と学生が話しています。<br><br>男：あの、ジョンです。事務に来るようにという掲示を見てきました。<br>女：あ、はい、ジョンさんですね。<br>男：あのう、なんでしょうか？授業料は先日支払いましたけど。それとも奨学金のことですか？<br>女：奨学金はまだなんですけど。<br>女：あの、ジョンさん、金曜日の佐藤先生の授業を取っていますよね。<br>男：はい。<br>女：その、先生が明後日の金曜日、急にご都合が悪くなり、日程を変更したいというご連絡があったんですが。<br>女：あの、来週の金曜日に三時間続けて授業をなさりたいそうなんですが、大丈夫ですか？<br>男：あ、はい、金曜日は、先生の授業だけですから。<br>女：そうですか、他の学生も問題ないそうですから、じゃあそういうことでお願いします。",
    audioUrl:"", question:"1番：事務の人の話の内容は何でしたか。", options:["担当教師の変更について","奨学金の結果について","授業料の支払いについて","授業の日程の変更について"], answer:3,
    translation:"(Script) Ở phòng hành chính của trường. Nam: Tôi là John, tôi thấy thông báo bảo đến phòng hành chính. Nữ: Vâng, anh John nhỉ. Nam: Có việc gì vậy ạ? Học phí tôi đã nộp hôm trước rồi, hay là về học bổng? Nữ: Học bổng thì chưa. Anh John có học lớp thứ Sáu của thầy Satō đúng không. Thầy báo thứ Sáu mốt đột nhiên bận nên muốn đổi lịch. Thầy muốn dạy liền 3 tiếng vào thứ Sáu tuần sau, anh có ổn không? Nam: Vâng, thứ Sáu tôi chỉ có lớp của thầy. Nữ: Vậy ạ, sinh viên khác cũng không vấn đề, vậy xin thống nhất như thế.",
    explanation:"Đáp án 4. Nữ nói:「先生が…日程を変更したいというご連絡があった」⇒ nội dung là việc thay đổi lịch học. 1, 2, 3 đều bị loại trong hội thoại (không đổi giáo viên, học bổng chưa có kết quả, học phí đã nộp)." },
  { id:"c3-2", passage:"【台本】女の人と男の人が、映画を見た後で感想を話しています。<br><br>女：いい映画だったね。<br>男：うん、そうね。<br>女：よくなかったの？<br>男：いや、そういうわけじゃないんだけど。<br>男：なんかいい映画見ると気持ちが暗くなることってない？<br>女：えー、そんなことないよ！<br>男：あ、そう？僕は自分の人生ってなんなんだろうとか考えちゃうんだよね。で、こう気分がね。<br>女：うーん。そうなんだ。じゃあ良くない映画だったらどう？<br>男：それは、無駄な時間使ったなって、暗くなっちゃうよ。<br>女：なんだ。じゃあ、よくも悪くもない映画見るしかないね。<br>男：いや、それはやっぱりいい映画見たいよ。",
    audioUrl:"", question:"2番：男の人はこの映画を見て、どう感じましたか。", options:["映画が良かったので、気分が沈んだ。","映画は良くなかったけれど、楽しかった。","映画が良くなかったので、暗い気持ちになった。","映画が良くも悪くもなかったので楽しくない。"], answer:0,
    translation:"(Script) Nữ: Phim hay nhỉ. Nam: Ừ, nhỉ. Nữ: Không hay à? Nam: Không phải vậy. Nam: Khi xem phim hay thì cậu có thấy tâm trạng trùng xuống không? Nữ: Ơ, không có! Nam: Vậy à? Mình thì lại nghĩ về việc cuộc đời mình là gì… rồi tâm trạng như thế. Nữ: Ra vậy. Vậy nếu là phim không hay thì sao? Nam: Thì lại thấy \"mất thời gian vô ích\" mà buồn. Nữ: Vậy chẳng phải chỉ còn cách xem phim không hay cũng không dở thôi sao. Nam: Không, mình vẫn muốn xem phim hay.",
    explanation:"Đáp án 1. Nam nói:「いい映画見ると気持ちが暗くなることってない？」「僕は自分の人生ってなんなんだろうとか考えちゃうんだよね」⇒ vì phim hay nên tâm trạng trùng xuống. 3 sai (đây là phim hay), 2, 4 không đúng." },
  { id:"c3-3", passage:"【台本】テレビ番組でスポーツジムの指導員が話しています。<br><br>女：スポーツジムなどで体を鍛えて筋肉をつけようという方から、トレーニングをしても思うように筋肉がつかないという声を聞くことがあります。おそらくやり方が適切でないのでしょう。運動量が多ければいいというものではありません。どのトレーニングも基本的なやり方としては、一セット十回、間に二分程度の休憩を挟みつつ、二、三セットやるのが効果的です。やり過ぎは体に疲労が蓄積され逆効果です。また一度トレーニングをしたら四十八時間ほど時間を置いて筋肉を休ませることも大切です。",
    audioUrl:"", question:"3番：スポーツジムの指導員は何について話していますか。", options:["トレーニングを続けることのメリット","トレーニングの効果的な方法","一日のうちでトレーニングに適した時間","トレーニングを行う重要性"], answer:1,
    translation:"(Script) Nữ: Từ những người tập luyện ở phòng gym để tăng cơ, tôi nghe nhiều ý kiến rằng dù tập nhưng cơ không lên như mong muốn. Có lẽ cách làm chưa hợp lý. Không phải tập nhiều là tốt. Cách cơ bản hiệu quả là: mỗi hiệp 10 lần, nghỉ khoảng 2 phút giữa các hiệp, tập 2-3 hiệp. Tập quá nhiều khiến mệt mỏi tích tụ, phản tác dụng. Ngoài ra, sau một buổi tập nên để khoảng 48 giờ cho cơ nghỉ ngơi.",
    explanation:"Đáp án 2. Nội dung nói về cách tập đúng: số hiệp, số lần, thời gian nghỉ, thời gian hồi phục ⇒ phương pháp tập luyện hiệu quả. 1, 3, 4 không được nêu." },
  { id:"c3-4", passage:"【台本】ラジオでアナウンサーが作文コンクールについて話しています。<br><br>桜新聞が毎年行っている小学生作文コンクールが今年も行われました。今年のテーマは家族です。多数の応募があり、その中から大好きなおじいさんとの交流を書いた小学五年生の小林健太さんの作文が最優秀賞に輝きました。おじいさんと交わした会話や、一緒に遊んだ時の様子が、目に浮かぶように鮮やかに描かれ、おじいさんがどんな人なのかがよくわかると評価されました。作品は桜新聞のホームページに掲載されていますので、是非ご覧ください。",
    audioUrl:"", question:"4番：アナウンサーはこの作文コンクールの何について話していますか。", options:["開催している目的","受賞者のコメント","最優秀賞に選ばれた作品","次回の応募方法"], answer:2,
    translation:"(Script) Cuộc thi viết văn của học sinh tiểu học do báo Sakura tổ chức hàng năm năm nay cũng đã diễn ra. Chủ đề năm nay là gia đình. Có rất nhiều bài dự thi, và trong đó bài của em Kobayashi Kenta, học sinh lớp 5, viết về sự giao lưu với người ông yêu quý đã giành giải xuất sắc nhất. Bài viết được đánh giá là miêu tả sinh động đến mức hình dung được cuộc trò chuyện với ông và cảnh chơi cùng ông, giúp hiểu rõ ông là người thế nào. Tác phẩm được đăng trên trang web của báo Sakura, mời mọi người xem.",
    explanation:"Đáp án 3. Người dẫn giới thiệu chi tiết về bài đạt 最優秀賞 (giải xuất sắc nhất) của em Kobayashi ⇒ nói về tác phẩm đoạt giải. 1, 2, 4 không được nêu." },
  { id:"c3-5", passage:"【台本】テレビで、女のアナウンサーと動物学者がある鳥について話しています。<br><br>女：本日は、鳥の研究がご専門の伊藤先生にお越しいただきました。<br>男：よろしくお願いします。<br>女：先生、ペットとして飼われている鳥の中には「こんにちは」と言うと、「こんにちは」と返してくるような鳥がいますよね。<br>男：ええ。それは話しているように聞こえるんですが、話しているわけではないんですよ。<br>女：そうなんですか。<br>男：それらの鳥のメスは、自分と似た声のオスとカップルになろうとするため、オスはメスの声を真似して相手にアピールするんです。<br>女：ああ。<br>男：そしてカップルになった後もお世話関係を深めるために、さらに似た声で鳴くようになります。ペットの鳥の行動についても、これと同じように考えられます。飼い主に愛情を示しているのだと思います。",
    audioUrl:"", question:"5番：動物学者はこの鳥の何について話していますか。", options:["人の言葉を、理解する能力","記憶力の良さ","飼い主との共通点","人の言葉を真似する理由"], answer:3,
    translation:"(Script) Nữ: Hôm nay chúng tôi có thầy Itō, chuyên gia nghiên cứu về chim. Nam: Rất hân hạnh. Nữ: Thưa thầy, trong số chim được nuôi làm cảnh có loài khi ta nói \"xin chào\" thì nó cũng đáp lại \"xin chào\" nhỉ. Nam: Vâng. Nghe như đang nói chuyện nhưng thực ra không phải là nói. Nữ: Vậy ạ. Nam: Con cái của loài chim đó muốn kết đôi với con đực có giọng giống mình, nên con đực bắt chước giọng con cái để hấp dẫn bạn tình. Sau khi thành đôi, để thắt chặt quan hệ chăm sóc, chúng còn kêu giống nhau hơn. Với hành vi của chim cảnh cũng có thể nghĩ tương tự. Tôi cho rằng đó là cách thể hiện tình cảm với chủ.",
    explanation:"Đáp án 4. Chuyên gia giải thích vì sao chim bắt chước giọng người (giống như con đực bắt chước giọng con cái để kết đôi và thể hiện tình cảm) ⇒ lý do bắt chước lời nói của con người. 1, 2, 3 không được nêu." },
]},
{ tab:"聴解", section:"問題4 即時応答",
  instruction:"問題4では、問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。（File có kèm đầy đủ lời thoại và 3 phương án trả lời.)",
  questions:[
  { id:"c4-1", passage:"【台本】女：金曜日締切りのレポート、間に合いそう？", audioUrl:"", question:"1番", options:["やっぱり書くことになったよ。","日本文学についてまとめたら。","徹夜で頑張るしかないよ。"], answer:2,
    translation:"Cô gái hỏi: \"Bài báo cáo hạn thứ Sáu, kịp không?\" ⇒ \"Đành phải thức trắng mà cố thôi.\"",
    explanation:"Đáp án 3. Câu hỏi về việc có kịp hạn hay không ⇒ trả lời「徹夜で頑張るしかないよ」(đành thức đêm cố) là hợp lý nhất. 1, 2 không trả lời đúng câu hỏi." },
  { id:"c4-2", passage:"【台本】女：ゼミの発表、うまく行かなかったからって、そんなに落ち込むことないよ。", audioUrl:"", question:"2番", options:["落ち着いてるように見える？","ありがとう、気持ちを切り替えなきゃね。","不満を言われても困るよ。"], answer:1,
    translation:"Cô gái: \"Dù phần thuyết trình ở seminar không suôn sẻ thì cũng đừng buồn quá như vậy.\" ⇒ \"Cảm ơn nhé, mình phải đổi tâm trạng thôi.\"",
    explanation:"Đáp án 2. Lời an ủi ⇒ đáp lại bằng lời cảm ơn và ý định đổi tâm trạng là tự nhiên nhất. 1, 3 không hợp ngữ cảnh." },
  { id:"c4-3", passage:"【台本】漢字のテスト、明日なのに、まだ全然覚えてないよ。テスト、来週になったらいいのに。", audioUrl:"", question:"3番", options:["テストの日、来週に変わるの？","来週にはならないでしょう。","来週になってよかったよね。"], answer:1,
    translation:"\"Bài kiểm tra kanji mai thi rồi mà mình chưa nhớ gì cả. Giá mà bài kiểm tra lùi sang tuần sau.\" ⇒ \"Chắc không lùi sang tuần sau được đâu.\"",
    explanation:"Đáp án 2. Câu nói thể hiện mong muốn không thực tế ⇒ đáp lại「来週にはならないでしょう」(chắc không thành tuần sau đâu) là phù hợp. 1 hiểu sai ý, 3 trái nghĩa." },
  { id:"c4-4", passage:"【台本】先週メールでお送りした出張の報告書、課長、ご覧いただけましたか。", audioUrl:"", question:"4番", options:["見てもらえたんだ、よかったね。","急いでるから、早めに出して。","ごめん、まだ見てないんだ。"], answer:2,
    translation:"\"Báo cáo chuyến công tác tôi gửi qua email tuần trước, thưa trưởng phòng, ngài đã xem chưa ạ?\" ⇒ \"Xin lỗi, tôi vẫn chưa xem.\"",
    explanation:"Đáp án 3. Người được hỏi chính là trưởng phòng ⇒ trả lời trực tiếp là「ごめん、まだ見てないんだ」. 1, 2 không đúng vai." },
  { id:"c4-5", passage:"【台本】あ、佐藤さん、こんにちは、こんなところでお会いするとは。", audioUrl:"", question:"5番", options:["本当、偶然ですね。","わざわざ会いに来てくれたんですか。","あ、じゃ、ここじゃないところにしましょう。"], answer:0,
    translation:"\"A, chị Satō, xin chào. Không ngờ lại gặp chị ở chỗ này.\" ⇒ \"Đúng là trùng hợp nhỉ.\"",
    explanation:"Đáp án 1. 「こんなところでお会いするとは」= bày tỏ sự bất ngờ vì gặp nhau ⇒「本当、偶然ですね」là đáp lại tự nhiên. 2, 3 không hợp." },
  { id:"c4-6", passage:"【台本】文化祭での僕たちのイベント、森先輩のアドバイスなしには成功しなかったよね。", audioUrl:"", question:"6番", options:["森先輩はアドバイスしてくれたよ。","本当、森先輩に感謝しなくちゃね。","だから成功しなかったんだね。"], answer:1,
    translation:"\"Sự kiện của chúng ta ở lễ hội văn hóa, nếu không có lời khuyên của anh Mori thì đã không thành công nhỉ.\" ⇒ \"Đúng vậy, phải cảm ơn anh Mori mới được.\"",
    explanation:"Đáp án 2. 「～なしには…ない」= nếu không có… thì không… ⇒ cần đáp lại đồng tình và biết ơn. 3 hiểu ngược nghĩa, 1 chỉ nhắc lại." },
  { id:"c4-7", passage:"【台本】村田さん、部長が、この前の村田さんのプレゼン見て、大したもんだって言ってたよ。", audioUrl:"", question:"7番", options:["ああ、部長、厳しいですね。","え、部長が褒めてくれたんですか。","曖昧だったのはどこですか"], answer:1,
    translation:"\"Chị Murata, trưởng phòng xem bài thuyết trình của chị hôm trước và nói là rất giỏi đấy.\" ⇒ \"Ơ, trưởng phòng khen tôi ạ?\"",
    explanation:"Đáp án 2. 「大したもんだ」= lời khen ⇒ đáp lại bằng sự ngạc nhiên/vui mừng khi được khen là hợp. 1, 3 không hợp." },
  { id:"c4-8", passage:"【台本】急なんだけど、明後日の出張、小野さんの代わりに行ってくれる？", audioUrl:"", question:"8番", options:["小野さん、どうかされたんですか。","小野さんと一緒に行けばいいんですね。","小野さん、どなたと代わるんですか"], answer:0,
    translation:"\"Gấp quá, chuyến công tác ngày mốt, cậu đi thay anh Ono được không?\" ⇒ \"Anh Ono có chuyện gì vậy ạ?\"",
    explanation:"Đáp án 1. Được nhờ đi thay ⇒ hỏi lý do「小野さん、どうかされたんですか」là phản ứng tự nhiên. 2 hiểu sai (không phải đi cùng), 3 dùng sai vai/nghĩa." },
  { id:"c4-9", passage:"【台本】先生、希望の会社に就職できるかどうか不安でしたが、なんとかなりました。", audioUrl:"", question:"9番", options:["それは心配ですね","そうですか。よかったですね。","まだ諦めちゃだめですよ。"], answer:1,
    translation:"\"Thưa thầy, em lo không biết có vào được công ty mong muốn không, nhưng cuối cùng cũng xoay xở được.\" ⇒ \"Vậy à. Tốt quá nhỉ.\"",
    explanation:"Đáp án 2. Kết quả tốt ⇒ chúc mừng「よかったですね」. 1 chỉ phù hợp khi nghe tin xấu, 3 nói khi chưa có kết quả." },
  { id:"c4-10", passage:"【台本】君の企画書、興味深く読ませてもらったよ。", audioUrl:"", question:"10番", options:["何か、ご意見いただければ嬉しいです。","すぐに書き直してお持ちします。","ぜひご覧になってみてください。"], answer:0,
    translation:"\"Bản kế hoạch của cậu, tôi đã đọc rất hứng thú.\" ⇒ \"Nếu được ngài cho ý kiến thì em rất vui ạ.\"",
    explanation:"Đáp án 1. Cấp trên đã đọc và quan tâm ⇒ xin ý kiến phản hồi là hợp lý. 2, 3 không phù hợp (chưa có yêu cầu viết lại, và 3 lại mời người vốn đã đọc xem)." },
  { id:"c4-11", passage:"【台本】あのう、すいません。サンドイッチ頼んでから、だいぶ経ってるんですけど。", audioUrl:"", question:"11番", options:["すみません、ただいま聞いてまいります。","すみません、すぐご注文をお伺いいたします。","すみません、もう結構です。"], answer:0,
    translation:"\"Xin lỗi, tôi gọi bánh sandwich từ khá lâu rồi mà chưa thấy.\" ⇒ \"Xin lỗi, tôi sẽ đi hỏi ngay ạ.\"",
    explanation:"Đáp án 1. Khách phàn nàn vì chờ lâu ⇒ nhân viên xin lỗi và đi kiểm tra「ただいま聞いてまいります」. 2 (xin nhận order) sai vì đã gọi rồi, 3 sai hoàn toàn ngữ cảnh." },
]},
{ tab:"聴解", section:"問題5 統合理解",
  instruction:"問題5では長めの話を聞きます。この問題には練習はありません。メモをとってもかまいません。（File có kèm đầy đủ 台本 chính thức.)",
  questions:[
  { id:"c5-1", passage:"【台本】市の図書館で、館長と職員二人が図書館のサービスについて話しています。<br><br>女1：最近、図書館の利用者数が伸び悩んでいるので、市民にもっと利用してもらえるよう、何かできることはないか考えてみたいと思います。<br>女2：今ポイントカードを発行して、貸し出し数に応じてポイントを付けてますよね？ポイントが貯まったら文房具をあげてるんですけど、あまり喜ばれていないように思うんです。品物を変えてみてはどうでしょうか。<br>女1：そうですね、他に何か案はありますか？<br>女2：後はもっと楽しく本を借りてもらえるように、二、三冊袋に入れて貸し出すのはどうですか？本のタイトルを秘密にして。<br>女1：え？どういうことですか？<br>女2：恋愛とか冒険とかテーマに沿って本を集めて、数冊袋に入れておくんです。どんな本が入っているか袋を開けるまで分からないようにして。<br>女1：なるほど。<br>男：でも、それだと読んだことがある本が入ってるってこともありますよね。<br>女2：その時は交換できるようにしたらいいですよ。<br>男：あの、まずは今やっている館内の見学会をホームページとかでもっと宣伝するのはどうですか？<br>女1：うん、これまでもホームページやチラシで十分宣伝してきてますからね。<br>男：それなら親子で参加できるイベントを増やしたらどうですか？今定期的にやってる工作や折り紙の教室、いつも人気で店員いっぱいですよね。<br>女1：うんー、そうすると、イベント当日は職員の数を増やす必要が出てくるし、準備の負担も増えますね。ポイントカードの制度は経費がかかるからこの際やめてもいいかなって思ってるんです。今回は手間も経費も少なくて済みそうな、さっきのユニークな案、試してみましょう。",
    audioUrl:"", question:"1番：図書館の利用者を増やすために何をすることにしましたか。", options:["ポイントと交換する品物を買える。","テーマごとに本を袋に入れて貸し出す。","見学会の宣伝に力を入れる。","親子で参加できるイベントを増やす。"], answer:1,
    translation:"(Script) Ở thư viện thành phố, giám đốc và hai nhân viên bàn về dịch vụ. Nữ1: Gần đây số người dùng thư viện không tăng, tôi muốn nghĩ xem có thể làm gì để người dân dùng nhiều hơn. Nữ2: Hiện đang phát hành thẻ điểm, cứ theo số lần mượn thì cộng điểm; khi đủ điểm thì tặng văn phòng phẩm, nhưng tôi thấy người ta không vui lắm. Hay là đổi phần thưởng? Nữ1: Nhỉ. Còn ý tưởng nào khác không? Nữ2: Hay là để việc mượn sách vui hơn, mình cho 2-3 cuốn vào một túi rồi cho mượn, giữ bí mật tên sách? Nữ1: Ơ, ý là sao? Nữ2: Gom sách theo chủ đề như tình yêu, phiêu lưu… rồi để vài cuốn vào túi, đến khi mở túi mới biết có sách gì. Nữ1: Ra vậy. Nam: Nhưng như thế có thể có cuốn mình đã đọc rồi. Nữ2: Lúc đó cho đổi là được. Nam: Hay là trước tiên quảng bá buổi tham quan thư viện hiện có trên trang web nhiều hơn? Nữ1: Ừ, nhưng trước giờ đã quảng bá đủ trên web và tờ rơi rồi. Nam: Vậy tăng các sự kiện cha mẹ và con cùng tham gia thì sao? Các lớp làm đồ thủ công, gấp giấy hiện tổ chức định kỳ luôn đông người. Nữ1: Ừm, nhưng làm vậy thì ngày sự kiện phải tăng số nhân viên và tăng gánh nặng chuẩn bị. Chế độ thẻ điểm tốn chi phí nên tôi định bỏ luôn. Lần này thử phương án độc đáo vừa nãy, vì ít tốn công và chi phí. (⇒ chọn phương án cho mượn túi sách bí mật)",
    explanation:"Đáp án 2. Cuối cùng giám đốc chốt:「今回は手間も経費も少なくて済みそうな、さっきのユニークな案、試してみましょう」— 「さっきのユニークな案」chính là ý tưởng cho mượn túi sách theo chủ đề (2-3 cuốn/túi). 1 (đổi quà tặng) và 3 (quảng bá) bị loại, 4 (tăng sự kiện) bị loại vì tốn nhân lực/chi phí." },
  { id:"c5-2", passage:"【台本】市民運動公園で係の人がイベントの説明をしています。<br><br>男：本日の防災フェアは、四つの会場に分かれています。第一会場の体育館では、災害時、怪我をした際の応急手当を実際に体験できます。第二会場の運動場では、ヘリコプターの離陸訓練をご覧いただけます。先着10名の方は、実際にヘリコプターに乗ることもできます。ただし、18歳以上の方に限ります。えー、それから、第三会場の駐車場では、消防車を展示しており、運転席に座ってみることができます。第四会場のプールでは、午後1時より服を着たまま泳ぐ訓練をご覧いただけます。各会場での体験や見学を通して、防災について学んでいただきたいと思います。<br><br>男：へー、色々あるんだね。ヘリコプターなんてなかなか乗れないから、乗ってみたいなぁ。行ってみない？<br>女：私は高いところが苦手だから、下で見てるね。<br>男：え、じゃ消防車にしようか。<br>女：せっかくだから、乗りたいのに乗ったら？先着順だから、急いで行こう。<br>男：分かった。他にどこか行きたいところある？<br>女：服を着たまま泳ぐっていうのに興味あるけど、あと3時間もあるから、応急手当はどう？役立ちそうだし。<br>男：そうだね、じゃあ、次はそれに行こう。",
    audioUrl:"", question:"2番 質問1：二人はまずどこへ行きますか。", options:["第1会場","第2会場","第3会場","第4会場"], answer:1,
    translation:"(Script) Ở công viên thể thao thành phố, nhân viên phụ trách giải thích về sự kiện. Nam: Hội chợ phòng chống thiên tai hôm nay chia làm 4 hội trường. Hội trường 1 (nhà thi đấu): trải nghiệm sơ cứu khi bị thương. Hội trường 2 (sân vận động): xem huấn luyện cất cánh trực thăng; 10 người đến trước được ngồi thử trực thăng (từ 18 tuổi trở lên). Hội trường 3 (bãi đỗ xe): trưng bày xe cứu hỏa, được ngồi vào ghế lái. Hội trường 4 (hồ bơi): từ 13 giờ có xem huấn luyện bơi mặc nguyên quần áo. … Nam: Ồ, nhiều thứ nhỉ. Trực thăng khó được đi nên mình muốn thử. Đi không? Nữ: Mình sợ độ cao nên ở dưới xem. Nam: Vậy thì xe cứu hỏa nhé. Nữ: Khó có dịp, cứ đi cái mình muốn đi. Vì ai đến trước được trước nên đi gấp thôi. Nam: Hiểu rồi. Còn chỗ nào muốn đi không? Nữ: Mình thích cái bơi mặc quần áo, nhưng còn 3 tiếng nữa nên hay là sơ cứu? Có vẻ hữu ích. Nam: Nhỉ, vậy tiếp theo đi cái đó.",
    explanation:"Đáp án 2. Nam muốn đi trực thăng (第2会場) và nữ khuyên「乗りたいのに乗ったら？先着順だから、急いで行こう」⇒ hai người đi 第2会場 trước ⇒ đáp án 2." },
  { id:"c5-3", passage:"(Xem 台本 ở câu 1番/質問1 của 問題5)", audioUrl:"", question:"2番 質問2：二人は次にどこへ行きますか。", options:["第1会場","第2会場","第3会場","第4会場"], answer:0,
    translation:"(Script: xem bản dịch ở 質問1) / Hai người tiếp theo sẽ đi: 第1会場 (hội trường 1).",
    explanation:"Đáp án 1. Nữ nói:「応急手当はどう？役立ちそうだし」và nam đồng ý「じゃあ、次はそれに行こう」⇒ 応急手当 = 第1会場 ⇒ đáp án 1." },
]},
]});

