/* =========================================================================
   data_2022_07.js — JLPT N2 2022年7月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2022_07", label:"07/2022", title:"JLPT N2 — 2022年7月 (07/2022)", file:"data_2022_07.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{ tab:"文字・語彙", section:"問題1 漢字読み",
  instruction:"＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a1-1", passage:"", audioUrl:"", question:"1. その当時の<u>記憶</u>はあまりない。", options:["きりょく","きよく","きろく","きおく"], answer:3,
    translation:"Ký ức về khoảng thời gian đó thì tôi không còn nhớ nhiều.",
    explanation:"記憶 = きおく: ký ức, trí nhớ. きりょく・きよく・きろく đều không phải âm đọc của 記憶." },
  { id:"a1-2", passage:"", audioUrl:"", question:"2. 前田さんがそんなに<u>偉い</u>人だとは知りませんでした。", options:["かしこい","えらい","すごい","するどい"], answer:1,
    translation:"Tôi không biết anh Maeda lại là người giỏi giang/vĩ đại đến thế.",
    explanation:"偉い = えらい: giỏi giang, vĩ đại, (địa vị) cao. かしこい (thông minh), すごい (tuyệt vời), するどい (sắc bén) sai." },
  { id:"a1-3", passage:"", audioUrl:"", question:"3. 私が仕事の話を始めたら、<u>途端に</u>西川さんの機嫌が悪くなった。", options:["とたんに","よたんに","とだんに","とだんに"], answer:0,
    translation:"Vừa lúc tôi bắt đầu nói chuyện công việc thì tâm trạng anh Nishikawa bỗng xấu đi ngay lập tức.",
    explanation:"途端に = とたんに: ngay khi vừa… thì. ⚠️ File gốc in trùng lựa chọn 3 và 4 (cùng là とだんに) — đáp án đúng là 1: とたんに." },
  { id:"a1-4", passage:"", audioUrl:"", question:"4. スピーチ大会の司会を<u>務める</u>。", options:["まとめる","やめる","やめる","つとめる"], answer:3,
    translation:"Tôi sẽ đảm nhận vai trò người dẫn chương trình cho cuộc thi hùng biện.",
    explanation:"務める = つとめる: đảm nhận (vai trò, chức vụ). まとめる (tổng hợp lại), やめる (nghỉ, bỏ) sai. ⚠️ File gốc in trùng lựa chọn 2 và 3." },
  { id:"a1-5", passage:"", audioUrl:"", question:"5. これは特別な<u>素材</u>で作られているそうだ。", options:["そうざい","すさい","そざい","すうざい"], answer:2,
    translation:"Nghe nói cái này được làm từ chất liệu đặc biệt.",
    explanation:"素材 = そざい: chất liệu, nguyên liệu. そうざい (惣菜/総菜: món ăn chế biến sẵn)・すさい・すうざい đều sai." },
]},
{ tab:"文字・語彙", section:"問題2 表記",
  instruction:"＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a2-1", passage:"", audioUrl:"", question:"6. いつのまにか太陽が<u>のぼって</u>いた。", options:["おって","至って","昇って","照って"], answer:2,
    translation:"Không biết từ lúc nào mặt trời đã mọc lên rồi.",
    explanation:"のぼる = 昇る: mọc lên, đi lên (dùng cho mặt trời, khói…). 及って/至って (đạt tới, đến mức), 照って (chiếu sáng) không hợp." },
  { id:"a2-2", passage:"", audioUrl:"", question:"7. <u>すいちょく</u>に線を引く。", options:["乗頂","乗直","垂頂","垂直"], answer:3,
    translation:"Kẻ một đường thẳng đứng.",
    explanation:"すいちょく = 垂直: thẳng đứng, vuông góc. 乗頂・乗直・垂頂 là chữ viết sai hoặc không tồn tại." },
  { id:"a2-3", passage:"", audioUrl:"", question:"8. 研修生を受け入れるためには、<u>じゅうきょ</u>を確保する必要がある。", options:["住宅","住居","住家","住屋"], answer:1,
    translation:"Để tiếp nhận thực tập sinh, cần phải đảm bảo chỗ ở.",
    explanation:"じゅうきょ = 住居: chỗ ở, nơi cư trú (cách nói trang trọng). 住宅 (nhà ở - chỉ loại nhà), 住家・住屋 không đúng." },
  { id:"a2-4", passage:"", audioUrl:"", question:"9. 災害に<u>そなえる</u>ことはとても大切だ。", options:["備える","準える","策える","防える"], answer:0,
    translation:"Việc chuẩn bị đối phó với thiên tai là vô cùng quan trọng.",
    explanation:"そなえる = 備える: chuẩn bị, phòng bị (災害に備える). 準える (mô phỏng, làm theo), 策える・防える không dùng cho nghĩa này." },
  { id:"a2-5", passage:"", audioUrl:"", question:"10. <u>てんけいてき</u>な例を挙げて説明した。", options:["点形的","典形的","点型的","典型的"], answer:3,
    translation:"Tôi đã nêu một ví dụ điển hình để giải thích.",
    explanation:"てんけいてき = 典型的: điển hình, tiêu biểu. Các cách viết 点形的・典形的・点型的 đều sai." },
]},
{ tab:"文字・語彙", section:"問題3 語形成",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a3-1", passage:"", audioUrl:"", question:"11. （　）分野の人と話すのはいい刺激になる。", options:["逆","異","副","裏"], answer:1,
    translation:"Nói chuyện với người ở lĩnh vực khác là một động lực/kích thích tốt.",
    explanation:"異分野 (いぶんや): lĩnh vực khác. 異 = khác biệt. 逆分野・副分野・裏分野 đều không phải từ ghép đúng." },
  { id:"a3-2", passage:"", audioUrl:"", question:"12. その店は、よい品物を（　）価格で売っている。", options:["半","安","小","低"], answer:3,
    translation:"Cửa hàng đó bán hàng tốt với giá thấp.",
    explanation:"低価格 (ていかかく): giá thấp. 半価格・安価格・小価格 đều không phải cách ghép chuẩn." },
  { id:"a3-3", passage:"", audioUrl:"", question:"13. 運転免許証など、顔写真（　）の身分証明書を見せてください。", options:["足し","載せ","付き","含み"], answer:2,
    translation:"Hãy xuất trình giấy tờ tùy thân có kèm ảnh chân dung như bằng lái xe.",
    explanation:"顔写真付き (かおじゃしんつき): có kèm ảnh chân dung. ～付き = có kèm, gắn kèm. 足し・載せ・含み không tạo từ đúng nghĩa." },
]},
{ tab:"文字・語彙", section:"問題4 文脈規定",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a4-1", passage:"", audioUrl:"", question:"14. 職場環境の問題については、会社との（　）の結果、改善してもらえることになった。", options:["交渉","授受","通話","出願"], answer:0,
    translation:"Về vấn đề môi trường làm việc, sau khi thương lượng với công ty, kết quả là họ sẽ cải thiện cho tôi.",
    explanation:"交渉 (こうしょう): thương lượng, đàm phán. 会社との交渉 = thương lượng với công ty. 授受 (trao đổi), 通話 (gọi điện), 出願 (nộp đơn) không hợp." },
  { id:"a4-2", passage:"", audioUrl:"", question:"15. この企画を成功させるには、いくつもの課題を（　）しなければならない。", options:["キャンセル","クリア","カット","プッシュ"], answer:1,
    translation:"Để làm cho kế hoạch này thành công, phải vượt qua nhiều vấn đề/thử thách.",
    explanation:"クリアする: vượt qua, giải quyết xong (課題をクリアする). キャンセル (hủy), カット (cắt), プッシュ (đẩy) không hợp." },
  { id:"a4-3", passage:"", audioUrl:"", question:"16. このカメラは小型だが、通常のモデルに比べて性能が（　）いるわけではない。", options:["縮んで","荒れて","沈んで","劣って"], answer:3,
    translation:"Chiếc máy ảnh này tuy nhỏ gọn nhưng không phải vì thế mà hiệu năng kém hơn mẫu thông thường.",
    explanation:"劣る (おとる): kém hơn, thua kém. 性能が劣っている = hiệu năng kém hơn. 縮む (co lại), 荒れる (dữ dội), 沈む (chìm) không hợp." },
  { id:"a4-4", passage:"", audioUrl:"", question:"17. 父は手術後、医者も驚くほど（　）回復した。", options:["劇的に","格別に","真剣に","強大に"], answer:0,
    translation:"Sau ca phẫu thuật, bố tôi hồi phục một cách nhanh chóng/ấn tượng đến mức bác sĩ cũng kinh ngạc.",
    explanation:"劇的に (げきてきに): một cách kịch tính, rất nhanh và rõ rệt. 格別に (đặc biệt), 真剣に (nghiêm túc), 強大に (không tồn tại) sai." },
  { id:"a4-5", passage:"", audioUrl:"", question:"18. このシステムを利用するには、インターネットに（　）しているパソコンが必要です。", options:["到達","付属","接続","密着"], answer:2,
    translation:"Để sử dụng hệ thống này, cần một máy tính đang kết nối với Internet.",
    explanation:"接続する (せつぞく): kết nối. インターネットに接続している = đang kết nối Internet. 到達 (đạt tới), 付属 (thuộc kèm), 密着 (bám sát) không hợp." },
  { id:"a4-6", passage:"", audioUrl:"", question:"19. アルバイトの募集は3月末で（　）ので、もう応募はできません。", options:["取り払った","打ち消した","締め切った","引き離した"], answer:2,
    translation:"Việc tuyển nhân viên part-time đã kết thúc (đóng đơn) vào cuối tháng 3 nên không thể ứng tuyển nữa.",
    explanation:"締め切る (しめきる): kết thúc, đóng (hạn nộp, đơn đăng ký). 募集を締め切る = chốt/đóng tuyển. 取り払う (dỡ bỏ), 打ち消す (phủ nhận), 引き離す (tách ra) không hợp." },
  { id:"a4-7", passage:"", audioUrl:"", question:"20. ガイドの後ろをツアー客たちが、（　）ついて歩いている。", options:["ごくごく","ぞろぞろ","ぎしぎし","じめじめ"], answer:1,
    translation:"Các du khách nối đuôi nhau lũ lượt bước theo sau người hướng dẫn.",
    explanation:"ぞろぞろ: (từ tượng thanh) lũ lượt, nối đuôi nhau đông người. ごくごく (ực ực - uống), ぎしぎし (két két), じめじめ (ẩm ướt) sai." },
]},
{ tab:"文字・語彙", section:"問題5 言い換え類義",
  instruction:"＿＿＿の言葉に意味が最も近いものを1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a5-1", passage:"", audioUrl:"", question:"21. ほかの車と<u>衝突しそう</u>になってしまった。", options:["ぶつかりそう","落ちそう","壊しそう","破りそう"], answer:0,
    translation:"Suýt chút nữa thì đâm vào xe khác.",
    explanation:"衝突する = ぶつかる: đâm vào, va chạm. ぶつかりそう = suýt đâm vào. 落ちる (rơi), 壊す (làm hỏng), 破る (xé) sai." },
  { id:"a5-2", passage:"", audioUrl:"", question:"22. 彼には<u>再三</u>お願いしているんです。", options:["たまに","何度か","何度も","いつも"], answer:2,
    translation:"Tôi đã nhờ vả anh ấy nhiều lần rồi.",
    explanation:"再三 (さいさん): nhiều lần, lặp đi lặp lại ⇒ 何度も. たまに (thỉnh thoảng), 何度か (vài lần - ít hơn), いつも (luôn luôn) không sát nghĩa." },
  { id:"a5-3", passage:"", audioUrl:"", question:"23. 彼が言っていることは<u>でたらめ</u>だ。", options:["悪口","わがまま","うそ","自慢"], answer:2,
    translation:"Những gì anh ta nói là bịa đặt/nói sai sự thật.",
    explanation:"でたらめ: chuyện bịa, vô căn cứ ⇒ うそ (lời nói dối). 悪口 (nói xấu), わがまま (ích kỷ), 自慢 (khoe khoang) sai." },
  { id:"a5-4", passage:"", audioUrl:"", question:"24. すみません、お<u>勘定</u>をお願いします。", options:["注文","会計","予約","配達"], answer:1,
    translation:"Xin lỗi, cho tôi thanh toán (tính tiền).",
    explanation:"お勘定 = かんじょう: việc tính tiền, thanh toán ⇒ 会計 (かいけい). 注文 (gọi món), 予約 (đặt trước), 配達 (giao hàng) sai." },
  { id:"a5-5", passage:"", audioUrl:"", question:"25. 今日は、犬がいつもより<u>さわがしい</u>。", options:["悲しそうだ","静かだ","楽しそうだ","うるさい"], answer:3,
    translation:"Hôm nay con chó có vẻ ồn ào hơn mọi ngày.",
    explanation:"さわがしい = 騒がしい: ồn ào, huyên náo ⇒ うるさい. 悲しそうだ (có vẻ buồn), 静かだ (yên tĩnh - trái nghĩa), 楽しそうだ (có vẻ vui) sai." },
]},
{ tab:"用法", section:"問題6 用法",
  instruction:"次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a6-1", passage:"", audioUrl:"", question:"26. 温厚", options:["温厚な伯父は、みんなから愛されている。","旅行中は、どこに行っても温厚な歓迎を受けてうれしかった。","今日は気温が下がるようなので、温厚なコートが必要だ。","雪の日には温厚なスープが飲みたくなる。"], answer:0,
    translation:"Người bác hiền lành, ôn hòa của tôi được mọi người yêu quý.",
    explanation:"温厚 (おんこう): ôn hòa, hiền lành (tính cách người). 「温厚な伯父」✓. 「温厚な歓迎」「温厚なコート」「温厚なスープ」đều sai vì 温厚 chỉ dùng cho tính cách con người." },
  { id:"a6-2", passage:"", audioUrl:"", question:"27. 濁る", options:["外と室内の温度の差で窓が濁っている。","今日は空が雲で暗く濁っている。","しばらく洗っていないので、車が濁っている。","大雨で川の水が茶色く濁っている。"], answer:3,
    translation:"Vì mưa lớn nên nước sông đục ngầu màu nâu.",
    explanation:"濁る (にごる): bị đục, vẩn đục (chất lỏng). 「川の水が濁る」✓. 窓が濁る (kính mờ - phải dùng 曇る), 空が濁る, 車が濁る đều sai." },
  { id:"a6-3", passage:"", audioUrl:"", question:"28. 世代", options:["野口さんはまだ20代なので、世代を取っているとはいえない。","先日のパーティーでは私と同じ世代の人がたくさんいて、話が盛り上がった。","青山さんは今は日本語の先生をしているが、実は英語の先生の世代が長い。","仕事を頑張るだけでなく、趣味も楽しんで、充実した世代を送りたい。"], answer:1,
    translation:"Ở bữa tiệc hôm trước có rất nhiều người cùng thế hệ với tôi nên câu chuyện rất sôi nổi.",
    explanation:"世代 (せだい): thế hệ. 「同じ世代の人」= người cùng thế hệ ✓. Các câu khác dùng sai: 世代を取る→年を取る, 世代が長い→経験が長い, 世代を送る→人生を送る." },
  { id:"a6-4", passage:"", audioUrl:"", question:"29. 普及", options:["よくないうわさが普及しているので、気をつけてください。","全員に飲み物が普及したようなので、森さんから乾杯のあいさつをお願いします。","最近は携帯電話が普及しているので、家に電話を置かない家庭もある。","先週からインフルエンザが普及していて、小学校が休みになっている。"], answer:2,
    translation:"Gần đây điện thoại di động trở nên phổ biến nên cũng có gia đình không đặt điện thoại cố định ở nhà.",
    explanation:"普及 (ふきゅう)する: phổ biến, lan rộng (đồ vật/dịch vụ/công nghệ). 「携帯電話が普及している」✓. うわさ (nên dùng 広がる), 飲み物 (nên dùng 行き渡る), インフルエンザ (nên dùng 流行する) đều sai." },
  { id:"a6-5", passage:"", audioUrl:"", question:"30. 生じる", options:["メールシステムに問題が生じて、メールが送れなくなった。","バターやチーズは牛乳から生じる。","昨日、姉に2番目の子どもが生じた。","いくら考えても、いいアイデアが生じない。"], answer:0,
    translation:"Hệ thống email phát sinh vấn đề nên không gửi được mail nữa.",
    explanation:"生じる (しょうじる): nảy sinh, phát sinh (vấn đề, sự việc trừu tượng). 「問題が生じる」✓. 牛乳から生じる (nên dùng できる), 子どもが生じた (nên dùng 生まれる), アイデアが生じない (thường dùng 浮かばない) đều không tự nhiên." },
]},
{ tab:"文法", section:"問題7 文の文法1",
  instruction:"次の文の（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a7-1", passage:"", audioUrl:"", question:"31. このカレーは15分（　）あればできるので、よく作る。", options:["に","も","まで","より"], answer:1,
    translation:"Món cà ri này chỉ cần có 15 phút là làm được nên tôi hay nấu.",
    explanation:"～もあれば: chỉ cần có đến… (nhấn mạnh lượng/thời gian như vậy là đủ). 「15分もあればできる」✓." },
  { id:"a7-2", passage:"", audioUrl:"", question:"32. A「新しい携帯電話、ちょっと使いづらいんだよね。」　B「使っていれば（　）慣れるよ。」", options:["いまにも","ようやく","そのうち","いつのまにか"], answer:2,
    translation:"A: \"Điện thoại mới hơi khó dùng nhỉ.\" B: \"Cứ dùng thì dần dần sẽ quen thôi.\"",
    explanation:"そのうち: một lúc nào đó, dần dần (trong tương lai gần). いまにも (sắp sửa ngay), ようやく (cuối cùng thì), いつのまにか (lúc nào không biết) không hợp ngữ cảnh." },
  { id:"a7-3", passage:"", audioUrl:"", question:"33. 今朝は寝坊してしまい、食事をする時間（　）顔を洗う時間もなかった。", options:["すら","しか","とはいえ","どころか"], answer:3,
    translation:"Sáng nay tôi ngủ quên, đừng nói là thời gian ăn, đến thời gian rửa mặt cũng không có.",
    explanation:"～どころか…もない: đừng nói là ~, đến … cũng không. 「食事をする時間どころか、顔を洗う時間もなかった」✓. しか phải đi với phủ định 「しか～ない」 và không hợp cách dùng ở đây." },
  { id:"a7-4", passage:"", audioUrl:"", question:"34. A「ねえ、経済学のレポート書けた？」　B「うん、難しかったけど、（　）書いたよ。」", options:["書けば","書いてでも","書くだけは","書いたわりに"], answer:2,
    translation:"A: \"Này, viết xong báo cáo kinh tế học chưa?\" B: \"Ừ, khó thật nhưng ít nhất thì đã viết xong.\"",
    explanation:"～だけは: ít ra thì, tối thiểu thì (nhấn mạnh đã hoàn thành một việc). 「書くだけは書いた」= ít nhất thì đã viết xong ✓." },
  { id:"a7-5", passage:"", audioUrl:"", question:"35. 情報技術の発展（　）、コミュニケーションの手段は多様化している。", options:["において","にこたえて","にあたって","にともなって"], answer:3,
    translation:"Cùng với sự phát triển của công nghệ thông tin, các phương tiện giao tiếp ngày càng trở nên đa dạng.",
    explanation:"～にともなって: cùng với, kéo theo (thay đổi đi kèm). 「情報技術の発展にともなって」✓. において (tại, ở), にこたえて (đáp lại), にあたって (nhân dịp, khi) sai." },
  { id:"a7-6", passage:"", audioUrl:"", question:"36.（歯医者のホームページで）虫歯が小さい（　）、簡単な治療で済みます。虫歯かもしれないと思ったら、早めに受診するようにしましょう。", options:["うちなら","うちでも","だけなら","だけでも"], answer:0,
    translation:"(Trên trang web của nha sĩ) Nếu sâu răng còn nhỏ thì chỉ cần điều trị đơn giản là xong.",
    explanation:"～うちなら: nếu còn trong lúc (chưa quá mức)… 「小さいうちなら」= nếu còn nhỏ (sớm) thì ✓. だけなら, うちでも, だけでも không hợp nghĩa điều kiện." },
  { id:"a7-7", passage:"", audioUrl:"", question:"37. 水族館では、2か月前にイルカの赤ちゃんが生まれてから来場者が増え、非常に混雑する（　）、開館時間を早めることを検討している。", options:["ようにしたとしても","ようにしたことから","ようになったとしても","ようになったことから"], answer:3,
    translation:"Ở thủy cung, từ khi cá heo con chào đời 2 tháng trước, lượng khách tăng và trở nên rất đông, nên họ đang cân nhắc việc mở cửa sớm hơn.",
    explanation:"～ようになったことから: vì (lý do) đã trở nên như vậy. 「混雑するようになったことから、開館時間を早める」✓. としても (dù có… thì) sai nghĩa; ようにしたことから không tự nhiên ở đây." },
  { id:"a7-8", passage:"", audioUrl:"", question:"38.（ホテルで）客「これから西森町に行くんですが、どこかおいしい和食のお店はありますか。」　フロント「西森町に（　）『さくら』はいかがでしょうか。大変人気のあるお店です。」", options:["伺うんでしたら","伺いますと","いらっしゃるんでしたら","いらっしゃいますと"], answer:2,
    translation:"Khách: \"Tôi sắp đi thị trấn Nishimori, có nhà hàng Nhật nào ngon không?\" Lễ tân: \"Nếu quý khách đến thị trấn Nishimori thì nhà hàng 'Sakura' thế nào ạ? Đó là quán rất nổi tiếng.\"",
    explanation:"いらっしゃる là kính ngữ của 行く/来る/いる → dùng cho khách. 「いらっしゃるんでしたら」= nếu quý khách đến… ✓. 伺う là khiêm nhường ngữ (dùng cho bản thân), nên sai khi nói về khách." },
  { id:"a7-9", passage:"", audioUrl:"", question:"39. 田中さんは仕事が忙しいらしく、最近テニスクラブの練習を（　）。", options:["休みかねない","休みがちだ","休むとのことだ","休むに違いない"], answer:1,
    translation:"Anh Tanaka có vẻ bận công việc nên gần đây hay nghỉ tập ở câu lạc bộ quần vợt.",
    explanation:"～がちだ: thường xuyên, hay (làm việc gì đó không mong muốn). 「休みがちだ」= hay nghỉ ✓. ～かねない (có thể sẽ - tiêu cực), ～とのことだ (nghe nói), ～に違いない (chắc chắn là) sai nghĩa." },
  { id:"a7-10", passage:"", audioUrl:"", question:"40. 飼っている犬が最近よくしゃっくりをする。心配になって病院で聞いてみたら、1時間以上続く場合は検査したほうがいいが、すぐに止まるなら（　）と言われた。", options:["心配しなければならない","心配しないでもない","心配するわけではない","心配することはない"], answer:3,
    translation:"Con chó tôi nuôi gần đây hay bị nấc. Lo quá nên hỏi ở bệnh viện thì được trả lời: nếu kéo dài hơn 1 tiếng thì nên kiểm tra, nhưng nếu dừng ngay thì không cần lo.",
    explanation:"～ことはない: không cần phải… 「心配することはない」= không cần lo ✓. 心配しなければならない (phải lo), 心配しないでもない (không phải là không lo), 心配するわけではない (không hẳn là lo) đều sai nghĩa." },
  { id:"a7-11", passage:"", audioUrl:"", question:"41. 私が教えている経営学の講義では、去年から、毎回学生に講義の感想や質問を書いて（　）。そこから気づかされることも多いからだ。", options:["出してもらうことにしている","出してもらうことがある","出してあげることにしている","出してあげることがある"], answer:0,
    translation:"Ở bài giảng kinh doanh học tôi dạy, từ năm ngoái, mỗi buổi tôi đều yêu cầu sinh viên viết ra cảm nhận và câu hỏi về bài giảng. Vì từ đó tôi cũng nhận ra được nhiều điều.",
    explanation:"～ことにしている: đã đặt ra quy tắc là sẽ làm (thói quen tự quy định). 「出してもらう」= được (sinh viên) nộp cho mình ✓. ～ことがある (thỉnh thoảng có khi) không hợp vì ngữ cảnh là \"mỗi lần\"." },
  { id:"a7-12", passage:"", audioUrl:"", question:"42. A「ねえ、大変。これから行くお寺、見学するには（　）よ。ガイドブックのここに書いてある。」　B「本当だ。今から予約できるか電話して聞いてみようか。」", options:["予約しないといけないみたいだ","予約しないといけないはずだ","予約したくなるみたいだ","予約したくなるはずだ"], answer:0,
    translation:"A: \"Này, phiền rồi. Ngôi chùa sắp đi, hình như muốn tham quan thì phải đặt trước đấy. Sách hướng dẫn ghi ở đây này.\" B: \"Thật nhỉ. Gọi điện hỏi xem bây giờ còn đặt được không nhỉ.\"",
    explanation:"～みたいだ: có vẻ như, hình như (suy đoán dựa trên thông tin vừa đọc được). 「予約しないといけないみたいだ」✓. ～はずだ (đáng lẽ phải) dùng cho phán đoán có căn cứ logic, không hợp khi vừa phát hiện thông tin." },
]},
{ tab:"文法", section:"問題8 文の文法2 (sắp xếp - ★)",
  instruction:"次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a8-1", passage:"", audioUrl:"", question:"43. この歌を聞く ＿＿ ＿＿ ★ ＿＿ ことだ。彼はカラオケに行くと必ずこの歌を歌っていた。［1 ことを / 2 思い出す / 3 たびに / 4 高校時代の友人の］", options:["ことを","思い出す","たびに","高校時代の友人の"], answer:0,
    translation:"Mỗi khi nghe bài hát này, tôi lại nhớ đến người bạn thời trung học. Anh ấy cứ vào quán karaoke là nhất định hát bài này.",
    explanation:"Thứ tự đúng: たびに（3）→高校時代の友人の（4）→ことを（1）→思い出す（2）: 「この歌を聞くたびに、高校時代の友人のことを思い出すことだ」。★ là ô thứ 3 ⇒ đáp án ① ことを. ～たびに: mỗi khi… ⚠️ File PDF gốc in nhầm lựa chọn 1 thành「には」." },
  { id:"a8-2", passage:"", audioUrl:"", question:"44. 昨日、アルバイトに遅刻しそうだったので ＿＿ ＿＿ ★ ＿＿ 結局遅刻してしまった。［1 タクシーに乗ったら / 2 かえって時間がかかり / 3 急ごうと思って / 4 道が渋滞していたせいで］", options:["タクシーに乗ったら","かえって時間がかかり","急ごうと思って","道が渋滞していたせいで"], answer:3,
    translation:"Hôm qua suýt muộn giờ làm thêm, định đi gấp nên bắt taxi, nhưng vì đường tắc nên lại càng mất thời gian, cuối cùng vẫn đến muộn.",
    explanation:"Thứ tự đúng: 急ごうと思って（3）→タクシーに乗ったら（1）→道が渋滞していたせいで（4）→かえって時間がかかり（2）: 「急ごうと思ってタクシーに乗ったら、道が渋滞していたせいでかえって時間がかかり、結局遅刻してしまった」。★ ô thứ 3 ⇒ đáp án ④. ～せいで: vì (nguyên nhân xấu)." },
  { id:"a8-3", passage:"", audioUrl:"", question:"45. 来月結婚する友人に結婚式のスピーチを頼まれた。大勢の前で話すのは ＿＿ ＿＿ ★ ＿＿ 飛び出していった。［1 悩んだのだが / 2 と言われて / 3 どうしても / 4 苦手なので］", options:["悩んだのだが","と言われて","どうしても","苦手なので"], answer:2,
    translation:"Tôi được người bạn kết hôn tháng sau nhờ phát biểu ở lễ cưới. Vì vốn không giỏi nói trước đông người nên tôi đã rất băn khoăn, nhưng vì bị \"nhất định phải làm\" nên (đành nhận lời).",
    explanation:"Thứ tự đúng: 苦手なので（4）→悩んだのだが（1）→どうしても（3）→と言われて（2）: 「大勢の前で話すのは苦手なので悩んだのだが、どうしてもと言われて…」。★ ô thứ 3 ⇒ đáp án ③ どうしても. 「どうしてもと言われて」= bị/được nói là \"nhất định phải\"." },
  { id:"a8-4", passage:"", audioUrl:"", question:"46. 先日の政治家A氏の発言はあまりに無責任だ。＿＿ ＿＿ ★ ＿＿ と思う。［1 政治家としての / 2 うえで / 3 発言しなければならなかった / 4 自分の立場をよく考えた］", options:["政治家としての","うえで","発言しなければならなかった","自分の立場をよく考えた"], answer:1,
    translation:"Phát ngôn của chính trị gia A hôm trước quá vô trách nhiệm. Tôi nghĩ lẽ ra ông ta phải suy nghĩ kỹ về vị trí của mình với tư cách một chính trị gia rồi mới phát ngôn.",
    explanation:"Thứ tự đúng: 政治家としての（1）→自分の立場をよく考えた（4）→うえで（2）→発言しなければならなかった（3）: 「政治家としての自分の立場をよく考えたうえで発言しなければならなかった」。★ ô thứ 3 ⇒ đáp án ② うえで. ～うえで: sau khi… (làm cơ sở) rồi mới…" },
  { id:"a8-5", passage:"", audioUrl:"", question:"47. 食事や睡眠などの生活習慣は一度乱れてしまうと、＿＿ ＿＿ ★ ＿＿ 、大切だ。［1 規則正しい生活を / 2 戻そうとしても / 3 普段から意識することが / 4 なかなか戻せないので］", options:["規則正しい生活を","戻そうとしても","普段から意識することが","なかなか戻せないので"], answer:3,
    translation:"Những thói quen sinh hoạt như ăn uống, ngủ nghỉ một khi đã bị xáo trộn thì dù muốn quay lại nếp sống điều độ cũng khó trở lại, nên việc luôn ý thức ngay từ bình thường là rất quan trọng.",
    explanation:"Thứ tự đúng: 規則正しい生活を（1）→戻そうとしても（2）→なかなか戻せないので（4）→普段から意識することが（3）: 「…規則正しい生活を戻そうとしても、なかなか戻せないので、普段から意識することが大切だ」。★ ô thứ 3 ⇒ đáp án ④." },
]},
{ tab:"文法", section:"問題9 文章の文法 (điền vào đoạn văn)",
  instruction:"次の文章を読んで、文章全体の内容を考えて、48から51の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a9-1", passage:"地下駐輪場<br><br>誰もが安全に、そして快適に暮らせる街をつくるため、各自治体はさまざまな取り組みを行っている。特に都市部において、駅周辺の整備は重要な課題となる。<br><br>今回取り上げるのは、自転車の【48】。多くの駅には駐輪場が設置されているが、スペースには限りがある。駐輪場を利用できない人が多くなると、道路や歩道など許可されていない場所に置かれる自転車が増え、車両や歩行者の通行の妨げになってしまう。<br><br>そこで有効になるのが地下空間の利用だ。地下に駐輪場があること自体はそれほど珍しくない。だが最近では、新しいタイプの地下駐輪場も見られる。それは、地下に【49】。全自動式の地下駐輪場なのだ。自転車だけを運ぶエレベーターが設置されており、地上で自転車をエレベーターに乗せてボタンを押すと、機械によって地下の駐輪スペースへと運ばれる。そして機械が判断して空いている場所へ収納してくれる。取り出すときも、暗証番号を入力すれば、機械が地上へ運んできてくれる。<br><br>【50】にはさまざまなメリットがある。たとえば、出し入れの手軽さだ。荷物が多い人や子供連れにとっては、駐輪場の中を移動せずに自転車を取り出せるというのは非常に便利だ。また、人が出入りしないので、盗難の心配もない。<br><br>駐輪場不足を解決し、より快適で安全な街に【51】、全自動式の地下駐輪場の設置は有効な手段の一つだといえる。今後も増えていきそうだ。",
    audioUrl:"", question:"48. 今回取り上げるのは、自転車の【48】。", options:["問題だろう","問題である","問題とのことだ","問題ではないか"], answer:1,
    translation:"Bãi đỗ xe đạp ngầm. Để tạo nên một thành phố nơi ai cũng có thể sống an toàn và thoải mái, mỗi chính quyền địa phương đang thực hiện nhiều biện pháp khác nhau. Đặc biệt ở khu vực đô thị, việc chỉnh trang quanh nhà ga là một vấn đề quan trọng. Lần này chúng tôi đề cập đến vấn đề bãi đỗ xe đạp. Nhiều nhà ga có bãi đỗ xe đạp nhưng diện tích có hạn. Khi số người không dùng được bãi đỗ tăng lên, xe đạp bị đặt ở những nơi không được phép như lòng đường, vỉa hè cũng tăng, gây cản trở cho xe cộ và người đi bộ.",
    explanation:"【48】= 問題である: khẳng định「自転車の問題である」. 問題だろう (chắc là vấn đề), 問題とのことだ (nghe nói là vấn đề), 問題ではないか (chẳng phải là vấn đề sao) không hợp văn phong báo cáo." },
  { id:"a9-2", passage:"", audioUrl:"", question:"49. それは、地下に【49】。全自動式の地下駐輪場なのだ。", options:["つくられているにすぎない","つくられているに違いない","つくられているといってもよい","つくられているというだけではない"], answer:3,
    translation:"(Đoạn văn: xem bản dịch ở câu 48) / Vậy nên việc sử dụng không gian ngầm trở nên hữu hiệu. Bãi đỗ xe đạp ngầm vốn không hiếm. Nhưng gần đây xuất hiện loại bãi đỗ ngầm kiểu mới: không chỉ đơn thuần được xây ở dưới lòng đất. Đó là bãi đỗ hoàn toàn tự động.",
    explanation:"【49】= つくられているというだけではない: không chỉ đơn thuần là được xây dựng (mà còn hơn thế). にすぎない (chỉ là), に違いない (chắc chắn là), といってもよい (có thể nói là) không hợp mạch văn nhấn mạnh điểm mới." },
  { id:"a9-3", passage:"", audioUrl:"", question:"50. 【50】にはさまざまなメリットがある。たとえば、出し入れの手軽さだ。", options:["駐輪場","ある駐輪場","このような駐輪場","そこの駐輪場"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 48) / Loại bãi đỗ xe này có nhiều ưu điểm. Ví dụ là sự tiện lợi khi lấy ra/cất vào.",
    explanation:"【50】= このような駐輪場: \"loại bãi đỗ xe như thế này\" — chỉ loại vừa được giới thiệu ở đoạn trên. 駐輪場 (thiếu chỉ định), ある駐輪場 (một bãi nào đó), そこの駐輪場 (bãi ở đó) không phù hợp." },
  { id:"a9-4", passage:"", audioUrl:"", question:"51. 駐輪場不足を解決し、より快適で安全な街に【51】、全自動式の地下駐輪場の設置は有効な手段の一つだといえる。", options:["しても","するために","なったように","なってはじめて"], answer:1,
    translation:"(Đoạn văn: xem bản dịch ở câu 48) / Để giải quyết tình trạng thiếu bãi đỗ và hướng tới một thành phố thoải mái, an toàn hơn, việc lắp đặt bãi đỗ xe đạp ngầm hoàn toàn tự động có thể nói là một biện pháp hữu hiệu. Có vẻ nó sẽ còn tăng lên trong tương lai.",
    explanation:"【51】= するために: \"để\" (mục đích) — 「より快適で安全な街にするために」. しても (dù có làm), なったように (như thể đã trở thành), なってはじめて (chỉ sau khi trở thành) đều sai nghĩa." },
]},
/* ================= TAB 4: 読解 ================= */
{ tab:"読解", section:"問題10 内容理解・短文",
  instruction:"次の（1）から（5）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b10-1", passage:"恐ろしい、恥ずかしい、淋しい、腹が立つ（注1）などなどは、不快な感情ではありますが、単に取り除かれればよいもの、存在しなければよいものではありません。それらが一切（注2）存在しない理想の人生があると考えるのは間違いで、それらには存在する理由があるのです。<br><br>どんなに恵まれた人生でも、恐いことはありますし、恥ずかしいこと、淋しいこと、腹が立つことはあります。むしろそういう感情があることが豊かな人生だとさえ言えます。<br><br>（注1）腹が立つ：怒りを感じる　（注2）一切：全く",
    audioUrl:"", question:"52. 筆者の考えに合うのはどれか。",
    options:["不快な感情を持てば持つほど、人生はより豊かになる","不快な感情を取り除ければ、理想の人生が送れる","不快な感情が存在する理由を考えることで、人生は豊かになる","不快な感情があるからこそ、人生は豊かになる"], answer:3,
    translation:"Sợ hãi, xấu hổ, cô đơn, tức giận… đều là những cảm xúc khó chịu, nhưng không phải là thứ chỉ cần loại bỏ đi, không phải là thứ không tồn tại thì tốt. Nghĩ rằng có một cuộc đời lý tưởng không tồn tại chút nào những cảm xúc ấy là sai lầm, vì chúng có lý do để tồn tại. Dù cuộc đời có may mắn đến đâu vẫn có điều đáng sợ, đáng xấu hổ, cô đơn, tức giận. Trái lại, có thể nói chính vì có những cảm xúc ấy mà cuộc đời trở nên phong phú.",
    explanation:"Đáp án 4. Tác giả nói những cảm xúc khó chịu không nên bị loại bỏ, chúng có lý do tồn tại và「そういう感情があることが豊かな人生だ」⇒ chính vì có cảm xúc khó chịu mà cuộc đời phong phú. 1 sai (không phải càng nhiều càng tốt), 2 trái ý tác giả, 3 sai (không phải \"suy nghĩ về lý do\" mà là \"có cảm xúc\")." },
  { id:"b10-2", passage:"以下は、ある店でもらったちらしである。<br><br>オリジナル帽子店「マリー」<br>期間限定・特別ショップのお知らせ<br><br>この度、4月1日から15日までの期間限定で、南野デパートに特別ショップを開店いたします。<br><br>特別ショップでは、通常の商品に加え、春の新商品を販売いたします。<br><br>春の新商品のうち、「花」シリーズは、特別ショップのみでの販売となりますので、ぜひこの機会にご来店ください。<br><br>なお、そのほかの春の新商品は、4月16日から「マリー」各店でも販売を開始いたします。",
    audioUrl:"", question:"53. 「花」シリーズを買いたい場合、どうすればいいか。",
    options:["4月1日から15日までの間に特別ショップに行く","1月1日から15日までの間に特別ショップか「マリー」各店に行く","4月1日から15日までの間は特別ショップに行き、16日以降は「マリー」各店に行く","4月16日以降に特別ショップか「マリー」各店に行く"], answer:0,
    translation:"Dưới đây là tờ rơi nhận được ở một cửa hàng. Cửa hàng mũ độc quyền \"Marie\" — Thông báo cửa hàng đặc biệt có thời hạn. Lần này, trong thời gian giới hạn từ 1/4 đến 15/4, chúng tôi mở cửa hàng đặc biệt ở tầng thương mại Minamino. Tại cửa hàng đặc biệt, ngoài hàng thông thường, chúng tôi bán các sản phẩm mới mùa xuân. Trong số đó, dòng \"Hoa\" chỉ được bán tại cửa hàng đặc biệt, mong quý khách ghé thăm nhân dịp này. Còn các sản phẩm mới mùa xuân khác sẽ bắt đầu bán ở các cửa hàng \"Marie\" từ 16/4.",
    explanation:"Đáp án 1. Dòng「花」chỉ bán ở 特別ショップ, mà 特別ショップ chỉ mở từ 1/4 đến 15/4 ⇒ phải đến trong khoảng đó. 2 sai tháng (1月 là lỗi in của file gốc), 3 sai vì「花」không bán ở các cửa hàng Marie, 4 sai vì sau 16/4 không còn cửa hàng đặc biệt." },
  { id:"b10-3", passage:"「適度に暖かく、発芽（注1）に使える水があり、呼吸もできるという条件がそろえば、多くの植物のタネは発芽する」と思われがちです。しかし、実際には、そうではありません。多くの植物のタネは、発芽の三条件がそろったからといって、うかつに（注2）発芽しないのです。<br><br>なぜなら、発芽の三条件の中には、「光が当たること」という条件が入っていないからです。もし、光の当たらない場所でタネが発芽すれば、発芽した芽生え（注3）がどんな運命をたどるか（注4）は、容易に想像がつきます。<br><br>（注1）発芽：芽を出すこと　（注2）うかつに：ここでは、簡単に　（注3）芽生え：ここでは、芽　（注4）どんな運命をたどるか：ここでは、どうなっていくか",
    audioUrl:"", question:"54. 本文の内容に合うのはどれか。",
    options:["発芽の三条件がそろった状態で光が当たっても、育たないことがある","発芽の三条件がそろって発芽しても、光が当たらなければ成長しにくい","発芽の三条件は、光が当たることよりも重要だ","発芽の三条件は、光の当たらない場所ではそろいにくい"], answer:1,
    translation:"Người ta thường nghĩ rằng \"nếu hội đủ ba điều kiện: ấm độ vừa phải, có nước dùng được cho nảy mầm và có thể hô hấp thì hạt của nhiều loài cây sẽ nảy mầm\". Nhưng thực tế không phải vậy. Hạt của nhiều loài cây dù đã hội đủ ba điều kiện nảy mầm cũng không nảy mầm một cách dễ dàng. Bởi vì trong ba điều kiện nảy mầm ấy không có điều kiện \"được ánh sáng chiếu vào\". Nếu hạt nảy mầm ở nơi không có ánh sáng thì dễ dàng tưởng tượng được mầm cây sẽ đi đến kết cục gì.",
    explanation:"Đáp án 2. Bài nói ba điều kiện không bao gồm \"ánh sáng\", nên hạt nảy mầm ở nơi tối sẽ khó phát triển (dẫn đến kết cục xấu). 1 sai (bài không nói \"có ánh sáng mà vẫn không mọc\"), 3 trái ý (bài nhấn mạnh ánh sáng cũng quan trọng, không nói ba điều kiện quan trọng hơn), 4 sai." },
  { id:"b10-4", passage:"以下は、ある会社の社員が、別の課の社員に送ったメールである。<br><br>宛て先：shinji_yasumura@tameikyo.co.jp<br>件名：「何でもハサミ」のミラ商会への納品について<br>日時：4月30日 11:55<br><br>商品管理課　安村様<br><br>お疲れ様です。<br><br>6月15日発売の「何でもハサミ」の件ですが、ミラ商会の担当者から連絡がありました。価格についての問題は解決しましたが、納品数については、最初の予定の50本ではなく、80本に変更してほしいとのことです。<br><br>今週中に返答しなければならないのですが、今から30本増やすことは可能でしょうか。<br><br>納品日は5月20日で、変更ありません。<br><br>ご検討よろしくお願いします。<br><br>営業課　大森",
    audioUrl:"", question:"55. このメールで問い合わせていることは何か。",
    options:["ミラ商会に、最初の予定より早く納品できるか","ミラ商会の希望する価格で、納品できるか","5月20日に、ミラ商会に80本を納品できるか","今週中に、ミラ商会に30本を納品できるか"], answer:2,
    translation:"Dưới đây là email một nhân viên công ty gửi cho nhân viên phòng khác. Kính gửi anh Yasumura, phòng quản lý sản phẩm. Xin chào. Về sản phẩm \"Kéo gì cũng cắt\" phát hành ngày 15/6, phía phụ trách của Mira Shōkai đã liên hệ. Vấn đề về giá đã giải quyết, nhưng về số lượng giao hàng, họ muốn thay đổi từ 50 chiếc theo dự định ban đầu thành 80 chiếc. Chúng tôi phải trả lời trong tuần này, liệu từ giờ có thể tăng thêm 30 chiếc được không? Ngày giao hàng là 20/5, không thay đổi. Mong anh xem xét. Phòng kinh doanh, Ōmori.",
    explanation:"Đáp án 3. Email hỏi: có thể tăng thêm 30 chiếc để giao đủ 80 chiếc vào 20/5 hay không ⇒ \"có giao được 80 chiếc cho Mira Shōkai vào 20/5 không\". 1 sai (ngày giao không đổi), 2 sai (giá đã giải quyết xong), 4 sai (không giao 30 chiếc, mà là tăng thêm 30 để thành 80)." },
  { id:"b10-5", passage:"仕事でも、人生でも、ようは（注1）降りかかる（注2）問題をいかに（注3）解決していくか、という作業の繰り返しだ。ある人は問題から逃げる。これも、この人にとっての解決である。しかし、そういう人は逃げ続けなければならない。一度きちんと解決をした人は、同じ問題に遭遇したときに対処できる。このようにして、スキル（注4）が上がっていき、その後得をするだろう。<br><br>（注1）ようは：大切なことは　（注2）降りかかる：ここでは、自分に起きる　（注3）いかに：どうやって　（注4）スキル：能力や技術",
    audioUrl:"", question:"56. 筆者の考えに合うのはどれか。",
    options:["問題に取り組む経験を積むほど、問題に対処できるようになる","問題から逃げることも、問題の解決には必要である","人生で得をするために、難しい問題に積極的に取り組むべきだ","解決できたかどうかより、問題解決に取り組む態度が大切だ"], answer:0,
    translation:"Dù là công việc hay cuộc sống, suy cho cùng đều là sự lặp đi lặp lại của việc giải quyết những vấn đề ập đến với mình. Có người trốn tránh vấn đề. Với người đó, đấy cũng là một cách giải quyết. Nhưng người như thế phải tiếp tục trốn mãi. Người đã từng giải quyết dứt khoát một lần thì khi gặp lại vấn đề tương tự sẽ biết cách xử lý. Như vậy, kỹ năng sẽ tăng lên và sau đó sẽ có lợi.",
    explanation:"Đáp án 1. Bài nói người giải quyết vấn đề một cách dứt khoát thì khi gặp lại vấn đề tương tự sẽ xử lý được ⇒ càng tích lũy kinh nghiệm giải quyết vấn đề, càng biết đối phó. 2 sai (tác giả không coi trốn tránh là giải pháp tốt), 3 sai (không nhấn mạnh \"để có lợi\"), 4 sai." },
]},
{ tab:"読解", section:"問題11 内容理解・中文",
  instruction:"次の（1）から（3）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b11-1", passage:"もの心つくかつかないかというころの子供（注1）は、まだ言葉では表現できない自分の感情や欲求を、何らかの方法で吐き出そうとする。身近に鉛筆やクレヨンなどがあれば、そこらに何かを描きなぐる（注2）のもその一つだ。注意深く見ていると、その段階ですでに、絵の好きな子は、絵らしきもの（注3）を描き始めている。そこですぐ、「あ、この子は絵が好きだ。画家にしよう」と考えるのは早すぎるが、大事なことは、「部屋がきたなくなる。そこらを汚す」といって、子供の遊びをやみくもに禁じて（注4）しまわないことだ。<br><br>（中略）<br><br>絵を学ぼうとして大学にまで来た人たちは、子供のときに両親から、絵を描くことを禁じられなかった人たちであることは確かである。画家になりたい、自分の芸術を発見したい、というところまでこぎつけた（注5）、この人々にとって、あとは自分自身の問題だ。教える方としても、いやな勉強を無理に続けたり押し付けたりしても、いい結果は得られないと思う。人は、いやなことをさせられれば、早くそこを通りすぎようとばかりするが、自分から喜んで、遊び心をもってやることはよく身につき、蓄積されていくものだ。<br><br>楽しく、遊び心でというのは、楽をするというのとは違う。それ自体は非常に苦しいことでも、自分を一段高いところへ進ませてくれるものだと、どこかで信じていれば、楽しくもある。<br><br>（注1）もの心つくかつかないかというころの子供：ここでは、幼い子供　（注2）描きなぐる：乱暴に描く　（注3）絵らしきもの：絵のようなもの　（注4）やみくもに禁じて：よく考えないでやめさせる　（注5）こぎつける：到達する",
    audioUrl:"", question:"57. 筆者によると、親は何かを描こうとしている子供にどう接したらいいか。",
    options:["さらに描きたい気持ちにさせる","描きたがっているのを止めない","描いているものを批判しない","描く楽しみを教える"], answer:1,
    translation:"Đứa trẻ ở độ tuổi vừa mới nhận thức được mọi thứ này nọ sẽ cố gắng thổ lộ bằng cách nào đó những cảm xúc, mong muốn mà mình chưa thể diễn đạt bằng lời. Nếu quanh mình có bút chì hay bút sáp thì việc vẽ nguệch ngoạc cái gì đó cũng là một cách. Nếu quan sát kỹ, ngay ở giai đoạn đó, đứa trẻ yêu thích vẽ đã bắt đầu vẽ những thứ trông như tranh. Vì thế, việc nghĩ ngay rằng \"à, đứa này thích vẽ, cho làm họa sĩ nhé\" là quá sớm, nhưng điều quan trọng là đừng vì \"phòng bẩn hết, bôi bẩn khắp nơi\" mà cấm đoán trò chơi của trẻ một cách vô căn cứ. (Lược trung gian) Những người đến tận đại học để học vẽ chắc chắn là những người hồi nhỏ không bị cha mẹ cấm vẽ. Với những người đã đạt đến mức muốn trở thành họa sĩ, muốn khám phá nghệ thuật của chính mình, phần còn lại là vấn đề của bản thân họ. Bản thân tôi nghĩ rằng dù có ép buộc tiếp tục hay áp đặt việc học buồn chán thì cũng không thu được kết quả tốt. Nếu bị bắt làm điều mình ghét, người ta chỉ lo đi qua thật nhanh, nhưng điều mình tự nguyện vui vẻ làm với tinh thần vui chơi thì lại thấm vào người và tích lũy lại. Vui vẻ, với tinh thần vui chơi không giống với việc làm biếng. Dù bản thân việc đó rất gian khổ, nếu tin ở đâu đó rằng nó sẽ đưa mình lên một tầng cao hơn thì cũng trở nên vui.",
    explanation:"Đáp án 2. Bài nói điều quan trọng là「子供の遊びをやみくもに禁じてしまわないこと」⇒ không ngăn cấm việc trẻ đang muốn vẽ. 1 sai (bài không nói khuyến khích thêm), 3 sai (không nói đến phê bình tranh vẽ), 4 sai (không nói dạy niềm vui vẽ)." },
  { id:"b11-2", passage:"", audioUrl:"", question:"58. 絵を学ぶ人に対して、筆者が言いたいことは何か。",
    options:["楽をしようと考えなければ、自分を向上させられる","画家になりたいという気持ちをもち続けるべきだ","不調のときにこそ、自分の芸術が発見できる","自ら楽しんで取り組むことが大切だ"], answer:3,
    translation:"(Đoạn văn: xem bản dịch ở câu 57) / Với người học vẽ, tác giả muốn nói: điều quan trọng là tự mình vui vẻ dấn thân.",
    explanation:"Đáp án 4. Bài nói「自分から喜んで、遊び心をもってやることはよく身につき、蓄積されていく」và「楽しく、遊び心でというのは、楽をするというのとは違う」⇒ tự mình vui vẻ làm là quan trọng. 1 sai (vui vẻ ≠ làm biếng), 2,3 không phải ý chính." },
  { id:"b11-3", passage:"読書は、本の書き手や登場人物のワールド（注1）が自分の中に根づくことで、人生を豊かにしていくことができるものです。読書でワールドを増やしていけるのです。<br><br>一方で、他者が自分の中に入り込む怖さもあります。自分よりはるかに思考力がある人の考えを読み、その人が深く入り込んできたら…。自分がなくなってしまうくらい影響を受けるかもしれません。読み方を間違えれば①危険でもあるのです。<br><br>（中略）<br><br>言葉を使っているというのもポイントで、著者の思考をなぞる（注2）ことができてしまう。それだけ深いレベルで影響を受けやすいのです。<br><br>そう考えると、場合によっては「批判的に読む」ことも必要でしょう。<br><br>ただ注意したいのは、何でも批判的に、ナナメに（注3）読めば思考力が深まるわけではないということです。著者の思考、世界観をいったんはそのまま受け入れるほうが得るものは大きいはずです。<br><br>「どっぷり読書」も、それはそれで②いいものです。その世界にどっぷりはまる（注4）ことで、思考が深まる面もあります。その上で批判的に読む。ちょっと離れたところから見るような感じです。この視点は、さまざまな本を読んでいるうちに自然と身につくものでもあります。<br><br>一人の作家に入れ込んで（注5）、その作家のものばかり読んでいると、どうしても視点が偏りがちになります。その作家しか受け付けない（注6）、というのではやはり思考も深まりません。違うタイプの作家のものを読んだり、違うジャンルの本を読んでいると、同時にいくつかの視点を持てるようになります。<br><br>（注1）ワールド：世界　（注2）なぞる：ここでは、追う　（注3）ナナメに：悪い点を探そうとして　（注4）どっぷりはまる：深く入り込む　（注5）入り込む：夢中になる　（注6）受けつける：受け入れる",
    audioUrl:"", question:"59. ①危険とあるが、どのような点が危険か。",
    options:["著者の考えに疑問を持つこと","著者の考えに支配されてしまうこと","著者の考えを読み間違えてしまうこと","著者の考えを理解することで満足してしまうこと"], answer:1,
    translation:"Đọc sách là việc thế giới của người viết hay nhân vật bén rễ trong bản thân mình, nhờ đó có thể làm cho cuộc đời phong phú hơn. Nhờ đọc sách mà ta có thể gia tăng thế giới của mình. Mặt khác, cũng có nỗi sợ rằng người khác xâm nhập vào trong ta. Đọc suy nghĩ của người có năng lực tư duy hơn mình rất nhiều, và nếu người đó đi sâu vào trong ta… thì có thể mình bị ảnh hưởng đến mức đánh mất chính mình. Nếu đọc sai cách thì đó cũng là ①nguy hiểm. (Lược trung gian) Việc dùng ngôn từ cũng là một điểm: ta có thể lần theo suy nghĩ của tác giả. Chính vì thế mà ta dễ bị ảnh hưởng ở mức độ sâu. Nghĩ như vậy thì trong một số trường hợp, việc \"đọc phê phán\" cũng là cần thiết. Nhưng điều cần lưu ý là không phải cứ đọc phê phán, đọc theo kiểu soi mói thì sẽ làm sâu sắc năng lực tư duy. Việc tạm thời tiếp nhận nguyên vẹn suy nghĩ, thế giới quan của tác giả chắc chắn sẽ thu được nhiều hơn. \"Đọc sách đắm chìm\" cũng là một điều ②tốt theo cách riêng. Nhờ đắm chìm sâu vào thế giới đó mà mặt tư duy cũng trở nên sâu sắc. Trên cơ sở đó rồi đọc phê phán — cảm giác như nhìn từ một chỗ hơi tách ra. Góc nhìn này cũng là thứ tự nhiên hình thành khi đọc nhiều sách. Nếu chỉ say mê một tác giả và chỉ đọc tác giả đó thì góc nhìn nhất định sẽ dễ bị lệch. Nếu chỉ chấp nhận một tác giả thì tư duy cũng không sâu sắc. Đọc tác giả khác kiểu hoặc đọc sách khác thể loại thì ta sẽ có thể đồng thời nắm được vài góc nhìn.",
    explanation:"Đáp án 2. Ngay trước ① tác giả viết「自分がなくなってしまうくらい影響を受けるかもしれません」⇒ nguy hiểm là bị suy nghĩ của tác giả chi phối/đánh mất chính mình. 1,3,4 không đúng với mạch văn." },
  { id:"b11-4", passage:"", audioUrl:"", question:"60. ②いいものですとあるが、なぜか。",
    options:["著者の視点がすぐに身につくから","著者の問題点に気づくようになるから","自分の考えも深まることがあるから","自分の考えを著者に近づけることもできるから"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 59) / \"Đọc sách đắm chìm\" cũng là một điều tốt: vì nhờ đắm chìm vào thế giới đó mà suy nghĩ của bản thân cũng có khi trở nên sâu sắc hơn.",
    explanation:"Đáp án 3. Ngay sau ② tác giả viết「その世界にどっぷりはまることで、思考が深まる面もあります」⇒ vì suy nghĩ của mình cũng có thể trở nên sâu sắc hơn. 1,2,4 không đúng mạch văn." },
  { id:"b11-5", passage:"", audioUrl:"", question:"61. 読書について、著者の考えに合うのはどれか。",
    options:["視点が偏らないように、さまざまな種類の本を読むことが大切だ。","思考を深めるには、偏りのない視点で書かれた本を読むことが必要だ。","一人の作家を理解するには、その作家の違う種類の本を読んだほうがいい。","作者から影響を受けすぎないように、常に批判的に読まなければいけない。"], answer:0,
    translation:"(Đoạn văn: xem bản dịch ở câu 59) / Về việc đọc sách: điều quan trọng là đọc nhiều loại sách khác nhau để góc nhìn không bị lệch.",
    explanation:"Đáp án 1. Đoạn cuối:「違うタイプの作家のものを読んだり、違うジャンルの本を読んでいると、同時にいくつかの視点を持てるようになります」⇒ đọc nhiều loại sách để không lệch góc nhìn. 2 sai (không nói \"sách có góc nhìn không lệch\"), 3 sai (không phải \"đọc các loại sách khác của cùng tác giả\"), 4 sai (bài nói không phải lúc nào cũng phải đọc phê phán)." },
  { id:"b11-6", passage:"以下は、企業の経営者に向けて書かれた文章である。<br><br>①長く同じ活動を行ってきた組織には、安定的な動きができるという長所があります。ところがこういう組織には同時に、ある一つの方向からの固定的な見方しかできないという欠点もあります。この欠点はなかなかやっかいなものです。こうした見方が組織内に一度根づいて（注1）しまうと、なかなか変えることができない難しさがあるからです。よそから見れば危険極まりない（注2）状態なのに、組織の中では誰もそれにまったく気づかないということが起こるのはそのためです。<br><br>これは②組織を支配する「気」が原因です。言葉を変えると、周りにいる本人は気づいていない、空気や雰囲気、あるいは文化といったものといえます。企業のように独特な文化を持つ組織の中では、これが原因で気に囲まれた人々が等しくおかしな見方をしてしまうことがよく起こります。組織の中でふだんから慣れ親しんでいる価値観が、いつの間にかその人たちの価値観になってしまうのです。<br><br>この状況を変えることができるのは、じつはトップだけです。トップがやらなければならないのは、組織全体を包んでいる「気」に惑わされない（注3）ことです。そしてできれば見たくないものを逆にしっかりと見るようにして、事業の全体像を正確に把握する（注4）ことです。その上でしっかりと価値付けを行い、組織の人たちが正しい方向に動けるように戦略を示すことができたら、いつの時代も最高の力を発揮できる組織をつくることができます。<br><br>（注1）根づく：定着する　（注2）危険極まりない：非常に危険　（注3）惑わされる：迷わされる　（注4）把握する：しっかりと理解する",
    audioUrl:"", question:"62. ①長く同じ活動を行ってきた組織について、筆者が挙げている問題点は何か。",
    options:["組織の中に間違った見方をしている人が多いことに誰も気づかないこと","組織が非常に危険な状態なのに、そのことを誰も言いだせないこと","組織全体が同じ見方をしていて、危ない状況であることに誰も気づかないこと","長く同じ活動を行っていることに、誰も疑問を持とうとしないこと"], answer:2,
    translation:"Dưới đây là bài viết dành cho các nhà quản lý doanh nghiệp. Tổ chức đã thực hiện cùng một hoạt động trong thời gian dài có ưu điểm là có thể vận hành ổn định. Nhưng đồng thời, tổ chức như vậy cũng có nhược điểm là chỉ có thể nhìn theo một cách cố định từ một hướng nhất định. Nhược điểm này khá là rắc rối, bởi vì một khi cách nhìn như thế đã bén rễ trong tổ chức thì rất khó thay đổi. Chính vì thế mà có chuyện: nhìn từ bên ngoài thì tình trạng vô cùng nguy hiểm, nhưng trong nội bộ tổ chức không ai nhận ra điều đó. Nguyên nhân là do thứ \"khí\" chi phối tổ chức. Nói cách khác, đó là bầu không khí, không khí tổng thể hay văn hóa mà bản thân những người xung quanh không nhận ra. Trong tổ chức có văn hóa đặc thù như doanh nghiệp, vì nguyên nhân này mà những người bị thứ \"khí\" bao quanh thường có cùng một cách nhìn kỳ lạ. Những giá trị mà người ta vốn quen thuộc trong tổ chức, đến một lúc nào đó lại trở thành giá trị của chính họ. Thứ có thể thay đổi tình trạng này thực ra chỉ có người lãnh đạo cao nhất. Điều người lãnh đạo phải làm là không để bị thứ \"khí\" bao trùm cả tổ chức làm cho mê muội. Và nếu có thể thì hãy nhìn ngược lại, nhìn thật kỹ những gì mình không muốn thấy, để nắm bắt chính xác toàn cảnh công việc. Trên cơ sở đó định giá trị một cách vững vàng và nếu có thể đưa ra chiến lược để người trong tổ chức đi theo đúng hướng thì có thể tạo ra tổ chức phát huy được sức mạnh cao nhất ở mọi thời đại.",
    explanation:"Đáp án 3. Bài viết:「ある一つの方向からの固定的な見方しかできない」+「よそから見れば危険極まりない状態なのに、組織の中では誰もそれにまったく気づかない」⇒ cả tổ chức cùng một cách nhìn, không ai nhận ra tình trạng nguy hiểm. 1 sai (không phải \"nhiều người nhìn sai\"), 2 sai (không phải \"không dám nói\"), 4 sai." },
  { id:"b11-7", passage:"", audioUrl:"", question:"63. ②組織を支配する「気」とはどのようなものか。",
    options:["組織内で無意識に共有されている価値観","組織内で押し付けられている価値観","組織内で人が変えたいと思っている価値観","組織内の人が常に意識している価値観"], answer:0,
    translation:"(Đoạn văn: xem bản dịch ở câu 62) / \"Khí\" chi phối tổ chức là: những giá trị được chia sẻ một cách vô thức trong tổ chức.",
    explanation:"Đáp án 1. Bài viết:「本人は気づいていない、空気や雰囲気、あるいは文化」「いつの間にかその人たちの価値観になってしまう」⇒ giá trị được chia sẻ vô thức. 2 sai (không phải bị áp đặt), 3 sai (không phải \"muốn thay đổi\"), 4 sai (không phải \"luôn ý thức\")." },
  { id:"b11-8", passage:"", audioUrl:"", question:"64. 筆者によると、トップに求められていることは何か。",
    options:["これまでの価値観を見直し、その良い点を伸ばした組織にすること","部下たちの価値観を認め、力を引き出せるような戦略を示すこと","組織の文化を理解した上で、時代に合った組織をつくること","組織の文化に流されずに、組織の適切な方向に導くこと"], answer:3,
    translation:"(Đoạn văn: xem bản dịch ở câu 62) / Theo tác giả, điều người lãnh đạo được yêu cầu là: không bị cuốn theo văn hóa tổ chức mà dẫn dắt tổ chức đi theo hướng thích hợp.",
    explanation:"Đáp án 4. Bài viết:「トップがやらなければならないのは、組織全体を包んでいる『気』に惑わされないこと」「組織の人たちが正しい方向に動けるように戦略を示す」⇒ không bị văn hóa tổ chức chi phối, dẫn dắt đúng hướng. 1,2,3 không đúng trọng tâm." },
]},
{ tab:"読解", section:"問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction:"次のAとBは、それぞれの立場から書かれた文章である。後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b12-1", passage:"【A】感謝の手紙を書くとき、どうしたら相手に自分の思いをうまく伝えられるだろうか。手紙というと、始まりや終わりの決まり文句など、形式的な表現や文を使わなければならないと思われがちだ。そのような表現や文を使うことは、確かに表面上は相手のことを大切に考えているような印象を与えるが、実は失礼にならないように自分を飾っているだけなのではないか。<br><br>思いを伝えるには、手紙を読んだ相手の気持ちを想像することが大事になる。その上で、形式的な表現や文を使わずに自分の言葉で書けば、思いが相手にまっすぐ届く。<br><br>【B】感謝の思いは、手紙で伝えるのがいいと思う。ふだんとは違う丁寧に書かれた文章から、真剣な気持ちが伝わるからだ。手紙で思いを伝えるには、始まりや終わりの文句など、形式的な表現や文を、正しく理解して使ったほうがいい。相手と自分との関係に合わせて適切に使い、相手が読んでどう感じるかもよく考えながら書くことが重要だ。<br><br>手紙は個人的なものだから、どのように書いても自由だと思うかもしれない。しかし、形式的な表現や文を正しく使い、礼儀正しい印象を持ってもらうことで、自分が伝えたいこともしっかり伝わるものだ。",
    audioUrl:"", question:"65. 感謝の手紙を書く際に形式的な表現や文を使うことについて、AとBはどのように述べているか。",
    options:["AもBも、礼儀正しすぎる印象を与えるのであまり使わないほうがいいと述べている。","AもBも、自分の思いをきちんと伝えるためにできるだけ使ったほうがいいと述べている。","Aは人は自分をよく見せようとしているだけなので使わないほうがいいと述べ、Bは真剣な気持ちが伝わるので使ったほうがいいと述べている。","Aは人は正しく使うのは難しいので使わないほうがいいと述べ、Bは真剣な気持ちが伝わるので使ったほうがいいと述べている。"], answer:2,
    translation:"【A】Khi viết thư cảm ơn, làm thế nào để truyền đạt tình cảm của mình tới đối phương một cách hiệu quả? Nói đến thư từ, người ta thường nghĩ phải dùng những cách diễn đạt, câu mở đầu và kết thúc theo khuôn mẫu. Dùng những cách diễn đạt ấy đúng là bề ngoài tạo ấn tượng rằng mình coi trọng đối phương, nhưng thực ra chẳng phải chỉ là tô điểm bản thân để không thất lễ sao? Để truyền đạt tình cảm, điều quan trọng là tưởng tượng cảm xúc của người đọc thư. Trên cơ sở đó, nếu viết bằng lời của chính mình mà không dùng cách diễn đạt khuôn mẫu thì tình cảm sẽ đến thẳng với đối phương. 【B】Tôi nghĩ tình cảm biết ơn nên được truyền đạt bằng thư tay. Vì từ một văn bản được viết cẩn thận khác với ngày thường, sẽ truyền được tâm ý nghiêm túc. Để truyền đạt tình cảm bằng thư, nên hiểu đúng và dùng những cách diễn đạt, câu khuôn mẫu ở đầu và cuối thư. Điều quan trọng là dùng phù hợp với quan hệ giữa mình và đối phương, đồng thời suy nghĩ kỹ xem đối phương đọc sẽ cảm thấy thế nào. Có thể bạn nghĩ thư là thứ riêng tư nên viết thế nào cũng được. Nhưng nếu dùng đúng những cách diễn đạt khuôn mẫu và tạo được ấn tượng lịch sự thì điều mình muốn truyền đạt cũng được truyền đạt trọn vẹn.",
    explanation:"Đáp án 3. A phủ nhận cách diễn đạt khuôn mẫu (chỉ là \"自分を飾っているだけ\" ⇒ không nên dùng), còn B khẳng định nên dùng (truyền được \"真剣な気持ち\" và ấn tượng lịch sự). 4 sai vì A không nói \"khó dùng đúng\" mà nói \"chỉ để tô điểm bản thân\"." },
  { id:"b12-2", passage:"", audioUrl:"", question:"66. 感謝の手紙を書くうえで、AとBが共通して大切だと述べていることは何か。",
    options:["自分の思いを自由に表現すること","自分らしい文章にすること","相手との関係に合わせて書き方を変えること","相手の気持ちを考えて書くこと"], answer:3,
    translation:"(Đoạn văn: xem bản dịch ở câu 65) / Điều cả A và B đều cho là quan trọng khi viết thư cảm ơn: viết có suy nghĩ đến cảm xúc của đối phương.",
    explanation:"Đáp án 4. A:「手紙を読んだ相手の気持ちを想像することが大事になる」. B:「相手が読んでどう感じるかもよく考えながら書くことが重要だ」⇒ cả hai đều nhấn mạnh việc nghĩ đến cảm xúc của người đọc. 1,2,3 không được nêu chung ở cả hai." },
]},
{ tab:"読解", section:"問題13 主張理解・長文",
  instruction:"次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b13-1", passage:"決断力がないと、いつも誰かの指示や命令に黙って従って生きていくしかない。そんな人生は誰も望まないだろう。若いうちは人の上に立つ機会は少ないが、決断力のある人をよく観察して、「なるほど、ああいうふうにすればいいのか」などと参考にしたほうがいい。とにかく早くから決断するクセをつけておくことだ。<br><br>どうやって決断力を磨くか。これは難しい問題のようだが、実は簡単で、決断力とは「決断すればいい」だけのこと。要は（注1）決断の勇気があるかどうかなのである。たとえば、「行く」「行かない」「断る」など、すべてその場で決める勇気なのだ。<br><br>このことを理解するためには、逆に①なかなか決断できない人を考えてみればいい。決断しなければならない場面で決断できない人は、何を考えているのだろうか。たとえば「行く」か「行かない」かという決断をするときに、その見通しをつけたいと思っているのだ。行けばどうなるか、行かないとどうか。つまり「正しい決断をしたい」と思っているのだ。<br><br>だが、この気持ちこそが決断を遅らせる最大の原因である。<br><br>（中略）<br><br>わからないことをわかろうと無理する必要はない。エイヤッと（注2）決めてしまえばそれで済む。哲学者のアミエルという人が「決心する前に、完全な見通しをつけようとする者は、決心することができない」といっている。そのとおりなのだ。決断で大切なことは、さっさと自分で「決断する」ことのみである。自分が決断しなければ、人の決断に従うことになる。人の決断に従って、結果が悪ければ、自分ですればよかったと後悔する。あるいは人のせいにする。絶対にそんな人生を送ってはいけない。自分の人生ではないか。<br><br>A社かB社かで悩んだ②就活生（注3）がB社を選んだとする。だが、三年で退職する羽目になった（注4）。すると「A社にしておけばよかった」と思うかもしれない。だが、A社を選んで同じ結果が出れば、「B社にすればよかった」と思うに決まっている。<br><br>これは、おかしくないか。どっちを選んでも後悔しているからだ。うまくいかなかった原因は決断にあったのではなく、その後の処し方（注5）が悪かったからだ。もし、うまくいっていれば、決断が正しかったと思うだろうが、そうではなく、処し方がよかったのだ。<br><br>こう考えてくると、決断の正体（注6）がだんだん見えてくるだろう。決断ですべてが決まるわけではない。決断した後の考え方や行動が大切。だが、決断しないことには何事も（注7）はじまらない。物事を前進させるためには決断が不可欠である。何がいけないといって、決断すべきときに決断しないのがいちばんいけない。<br><br>（注1）要は：大事なことは　（注2）エイヤッと：ここでは思い切って　（注3）就活生：就活のために活動をする学生　（注4）～羽目になる：～という困った状況になる　（注5）処し方：ここでは、対応　（注6）正体：本当の姿　（注7）何事も：どんなことも",
    audioUrl:"", question:"67. ①なかなか決断できない人とあるが、なぜ決断できないのか。",
    options:["自分が正しい決断ができるとは思えないから","一度決断したら変えられないと思って迷うから","その場で決断すべきことかどうかわからないから","間違った決断をしたくないと思って考えすぎるから"], answer:3,
    translation:"Nếu không có năng lực quyết đoán, ta chỉ còn cách im lặng tuân theo mệnh lệnh, chỉ dẫn của người khác. Chắc không ai mong muốn cuộc đời như vậy. Hồi trẻ, cơ hội đứng trên người khác ít, nhưng nên quan sát kỹ người có năng lực quyết đoán và tham khảo kiểu \"à, hóa ra làm như thế là được\". Dù sao cũng nên tập thói quen quyết định từ sớm. Làm thế nào để mài giũa năng lực quyết đoán? Nghe như vấn đề khó, nhưng thực ra đơn giản: năng lực quyết đoán chỉ là \"quyết định là được\". Cốt lõi là có dũng khí quyết định hay không. Ví dụ \"đi\", \"không đi\", \"từ chối\"… tất cả đều là dũng khí quyết ngay tại chỗ. Để hiểu điều này, hãy thử nghĩ ngược lại về người ①không thể quyết định. Người không thể quyết định khi phải quyết định đang nghĩ gì? Ví dụ khi quyết \"đi\" hay \"không đi\", họ muốn thấy trước kết quả. Đi thì thế nào, không đi thì ra sao. Tức là họ nghĩ \"muốn quyết định cho đúng\". Nhưng chính tâm lý này là nguyên nhân lớn nhất khiến việc quyết định bị trì hoãn. (Lược trung gian) Không cần cố gắng hiểu điều không hiểu. Cứ liều quyết một cái là xong. Triết gia tên Amiel đã nói: \"Người muốn có cái nhìn thấu đáo hoàn hảo trước khi quyết tâm thì không thể quyết tâm được\". Đúng là như vậy. Điều quan trọng trong quyết định chỉ là tự mình \"quyết định\" cho nhanh. Nếu mình không quyết định thì sẽ phải theo quyết định của người khác. Theo quyết định của người khác mà kết quả xấu thì lại hối hận lẽ ra mình nên làm, hoặc đổ lỗi cho người khác. Tuyệt đối không được sống cuộc đời như thế. Đó chẳng phải là cuộc đời của mình sao? Một ②sinh viên tìm việc (注3) phân vân giữa công ty A và B, giả sử chọn B. Nhưng rồi rơi vào tình cảnh phải nghỉ việc sau ba năm (注4). Thế là có thể nghĩ \"giá mà chọn A\". Nhưng nếu chọn A mà kết quả cũng vậy thì nhất định sẽ nghĩ \"giá mà chọn B\". Như thế có kỳ không? Vì chọn bên nào cũng hối hận. Nguyên nhân thất bại không nằm ở quyết định mà ở cách xử lý sau đó. Nếu suôn sẻ, ta nghĩ quyết định đúng, nhưng không phải vậy, mà là do cách xử lý tốt. Nghĩ như thế thì dần thấy được bản chất của quyết định. Quyết định không quyết định tất cả. Cách nghĩ và hành động sau khi quyết định mới quan trọng. Nhưng nếu không quyết định thì mọi việc không bắt đầu. Để đưa sự việc tiến lên, quyết định là không thể thiếu. Nói điều gì là tệ nhất thì việc không quyết định đúng lúc cần quyết định là tệ nhất.",
    explanation:"Đáp án 4. Bài viết:「『正しい決断をしたい』と思っている。だが、この気持ちこそが決断を遅らせる最大の原因である」⇒ vì muốn quyết định cho đúng nên suy nghĩ quá nhiều. 1,2,3 không được nêu trong bài." },
  { id:"b13-2", passage:"", audioUrl:"", question:"68. ②就活生の例を挙げて、筆者が問題だと述べていることは何か。",
    options:["人の意見を聞いて決断すればよかったと思うこと","悪い結果になったとき、それを認めようとしないこと","決断を間違えたせいで悪い結果になったと思うこと","決断は正しかったにもかかわらず、後悔をしていること"], answer:2,
    translation:"(Đoạn văn: xem bản dịch ở câu 67) / Qua ví dụ sinh viên tìm việc, tác giả cho là vấn đề: việc nghĩ rằng kết quả xấu là do đã quyết định sai.",
    explanation:"Đáp án 3. Bài viết:「うまくいかなかった原因は決断にあったのではなく、その後の処し方が悪かったからだ」⇒ vấn đề là nghĩ \"do quyết định sai\". 4 sai vì bài nói chọn bên nào cũng hối hận, trọng tâm là quy \"tại quyết định\" là sai." },
  { id:"b13-3", passage:"", audioUrl:"", question:"69. この文章で筆者が言いたいことは何か。",
    options:["必要なときに決断したうえで、どのように対応するかが重要だ。","決断する前に、うまくいかなかった場合の対応を考えておくべきだ。","正しい決断ができるようになるには、決断するという経験を積むべきだ。","どんな結果になっても後悔しないように、よく考えて決断することが重要だ。"], answer:0,
    translation:"(Đoạn văn: xem bản dịch ở câu 67) / Điều tác giả muốn nói trong bài: quyết định đúng lúc cần thiết, và sau đó cách ứng xử thế nào mới là quan trọng.",
    explanation:"Đáp án 1. Bài viết:「決断ですべてが決まるわけではない。決断した後の考え方や行動が大切」「物事を前進させるためには決断が不可欠」「決断すべきときに決断しないのがいちばんいけない」⇒ phải quyết định khi cần, rồi cách xử lý sau đó mới quan trọng. 2,4 trái ý (bài nói không cần thấy trước hoàn hảo, không cần suy nghĩ quá nhiều), 3 sai trọng tâm." },
]},
{ tab:"読解", section:"問題14 情報検索",
  instruction:"次の資料を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b14-1", passage:"料金案内<br><br>グループをご利用になる場合は、入場券とプール利用料がセットになった、一日パスまたはショートパスをご購入ください。<br><br>【チケット】　一日パス＝入場券＋プール利用料（9時から20時まで利用可能）／ショートパス＝入場券＋プール利用料（14時以降のみ利用可能）<br>■一日パス<br>　・通常：大人（13歳以上）3,000円／子供（5歳〜12歳）2,400円／幼児（0〜4歳）1,300円<br>　・特別期間*1：大人 3,500円／子供 2,900円／幼児 1,800円<br>■ショートパス<br>　・通常：大人 2,300円／子供 1,700円／幼児 500円<br>　・特別期間*1：大人 2,800円／子供 2,200円／幼児 1,000円<br>■入場券のみ*2<br>　・通常：大人 1,600円／子供 1,000円／幼児 200円<br>　・特別期間*1：大人 2,100円／子供 1,500円／幼児 700円<br><br>*1 特別期間：7月1日〜8月31日<br>*2 入場券だけでは、グループは利用になれません。<br><br>【団体割引について】<br>・20名以上の団体の場合、団体割引が適用されます。ご利用料金から、一般団体は1割引、学校団体は3割引になります。<br>　学校団体とは保育園、幼稚園、小・中学校、高校の児童・生徒による団体を指し、学校が発行する、学校にかかわる活動としての説明書がある場合に限り、割引を適用します。<br>・特別期間中（7月1日〜8月31日）の土日、祝日は、団体割引の対象外となります。<br>・一般団体、学校団体にかかわらず、お電話で事前のご予約をお願いいたします。<br>　団体予約センター：02-1236-4569（10時〜18時）<br><br>【平日限定 割引サービス（特別期間を含む）】<br>一日パス・ショートパスの料金が300円引きとなります！",
    audioUrl:"", question:"70. スマンさんは3歳の娘と一緒に8月の平日にプールに行き、10時から12時まで遊ぶつもりである。スマンさんたちの料金はいくらになるか。",
    options:["スマンさん2,800円、娘1,000円から、それぞれ300円を引いた金額","スマンさん3,000円、娘1,300円から、それぞれ300円を引いた金額","スマンさん3,500円、娘1,800円から、それぞれ300円を引いた金額","スマンさん3,500円、娘1,800円"], answer:2,
    translation:"Bảng giá. Khi sử dụng theo nhóm, hãy mua 一日パス (vé ngày) hoặc ショートパス — là vé vào cổng kèm phí sử dụng hồ bơi. 【Vé】一日パス = vé vào cổng + phí hồ bơi (dùng từ 9h đến 20h) / ショートパス = vé vào cổng + phí hồ bơi (chỉ dùng từ 14h trở đi). ■一日パス: Thông thường — người lớn (13+) 3.000 yên / trẻ em (5–12) 2.400 yên / trẻ nhỏ (0–4) 1.300 yên; Thời gian đặc biệt*1 — 3.500 / 2.900 / 1.800 yên. ■ショートパス: Thông thường 2.300 / 1.700 / 500 yên; Thời gian đặc biệt 2.800 / 2.200 / 1.000 yên. ■Chỉ vé vào cổng*2: 1.600 / 1.000 / 200 yên; đặc biệt 2.100 / 1.500 / 700 yên. *1 Thời gian đặc biệt: 1/7–31/8. *2 Chỉ có vé vào cổng thì nhóm không sử dụng được. 【Về giảm giá theo nhóm】- Nhóm từ 20 người trở lên được giảm giá: nhóm thường giảm 10%, nhóm trường học giảm 30%. Nhóm trường học là nhóm trẻ em/học sinh của nhà trẻ, mẫu giáo, tiểu học, trung học, và chỉ được giảm khi có giấy giải thích do nhà trường phát hành. - Vào thứ Bảy, Chủ nhật, ngày lễ trong thời gian đặc biệt (1/7–31/8) thì không được giảm giá theo nhóm. - Dù là nhóm thường hay nhóm trường học đều cần đặt trước qua điện thoại. 【Giảm giá riêng ngày thường (bao gồm cả thời gian đặc biệt)】Giá vé ngày và vé ngắn sẽ được giảm 300 yên!",
    explanation:"Đáp án 3. 8月 thuộc 特別期間 (1/7–31/8) ⇒ giá áp dụng là giá 特別期間. 10–12h nằm trong khung 9–20h ⇒ dùng 一日パス. Ông Smarn (người lớn) = 3,500 yên; con gái 3 tuổi = 幼児 (0–4) = 1,800 yên. Vì đi vào 平日 ⇒ được giảm thêm 300 yên/người ⇒ 3,500 − 300 và 1,800 − 300. Đó chính là phương án 3." },
  { id:"b14-2", passage:"", audioUrl:"", question:"71. 次の四つの団体は、一日パスを購入しようと思っている。この中で、学校団体として割引が適用されるのはどの団体か。",
    options:["① 高下北小学校／説明書なし／23名／7月の平日","② 高下南小学校／説明書あり／30名／8月の平日","③ 高下第二小学校／説明書あり／18名／9月の日曜日","④ 高下高校／説明書あり／45名／8月の土曜日"], answer:1,
    translation:"(Tài liệu: xem bản dịch ở câu 70) / Bốn nhóm dưới đây định mua vé ngày. Nhóm nào được áp dụng giảm giá với tư cách nhóm trường học?",
    explanation:"Đáp án 2 (nhóm ②). Điều kiện nhóm trường học: (a) từ 20 người trở lên, (b) có giấy giải thích do nhà trường phát hành, (c) không rơi vào thứ Bảy/Chủ nhật/ngày lễ trong thời gian đặc biệt. ① 23 người nhưng không có giấy → loại. ② 30 người, có giấy, là ngày thường tháng 8 → đủ điều kiện ✓. ③ chỉ 18 người (<20) → loại. ④ ngày thứ Bảy trong thời gian đặc biệt → không được giảm." },
]},
/* ================= TAB 5: 聴解 ================= */
{ tab:"聴解", section:"問題1 課題理解",
  instruction:"問題1では、まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（ファイルには音声がありません。問題用紙に印刷されたせんたくしと、公式の解答のみ掲載しています。）",
  questions:[
  { id:"c1-1", passage:"🎧 File đề không có audio. Đáp án theo bảng đáp án chính thức: ④", audioUrl:"", question:"1番", options:["テーマを決める","商店街の人に話を聞く","クラスで話し合う","町について調べる"], answer:3,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ④「町について調べる」. ⚠️ File PDF không chứa file âm thanh nên không thể cung cấp nội dung hội thoại; đáp án lấy theo bảng đáp án của đề." },
  { id:"c1-2", passage:"", audioUrl:"", question:"2番", options:["前回のアンケートをまとめる","次回の申し込みの対応をする","次回の資料を発送する","前回の参加者にお礼のメールを送る"], answer:0,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ①「前回のアンケートをまとめる」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c1-3", passage:"", audioUrl:"", question:"3番", options:["商品名の文字の色を変える","商品の厚さの数字を大きく書く","以前の商品と比べた図を入れる","性能の変更点を加える"], answer:2,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ③「以前の商品と比べた図を入れる」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c1-4", passage:"", audioUrl:"", question:"4番", options:["環境問題のアートを制作する","活動をまとめた文献を読む","環境問題のイベントに参加する","別の人に相談する"], answer:1,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ②「活動をまとめた文献を読む」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c1-5", passage:"", audioUrl:"", question:"5番", options:["食品を袋に詰める","机の下に段ボール箱を置く","食品を机の上に並べる","学生が取った食品の数を確認する"], answer:2,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ③「食品を机の上に並べる」. ⚠️ Thiếu dữ liệu audio trong file." },
]},
{ tab:"聴解", section:"問題2 ポイント理解",
  instruction:"問題2では、まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（ファイルには音声がありません。）",
  questions:[
  { id:"c2-1", passage:"🎧 File đề không có audio. Đáp án theo bảng đáp án chính thức: ①", audioUrl:"", question:"1番", options:["面接中は明るい顔をするようにする","面接の前にメモを作る","面接の最初にあいさつする","日本人の友達と練習する"], answer:0,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ①「面接中は明るい顔をするようにする」. ⚠️ File PDF không có audio nên không thể cung cấp nội dung." },
  { id:"c2-2", passage:"", audioUrl:"", question:"2番", options:["音楽の専門学校の先生に推薦された","駅前で音楽関係の人に声をかけられた","音楽の事務所に歌の録音を送った","音楽のコンテストで優勝した"], answer:3,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ④「音楽のコンテストで優勝した」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c2-3", passage:"", audioUrl:"", question:"3番", options:["注文が遅れたこと","数を間違って工場に依頼したこと","問題が起こった時に課長に報告しなかったこと","京都支店の小林部長に相談したこと"], answer:2,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ③「問題が起こった時に課長に報告しなかったこと」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c2-4", passage:"", audioUrl:"", question:"4番", options:["おなかがすいた時に食べる","決まった時間に3食食べる","手軽で冷たい物を食べる","のどごしがよい物を食べる"], answer:1,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ②「決まった時間に3食食べる」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c2-5", passage:"", audioUrl:"", question:"5番", options:["さくら駅に取りに行く","森川駅に電話をかける","警察署に問い合わせる","西山駅で宅配便の手続きをする"], answer:0,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ①「さくら駅に取りに行く」. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c2-6", passage:"", audioUrl:"", question:"6番", options:["防災グッズに関心を持つこと","防災グッズを買いそろえること","防災グッズを使ってみること","防災グッズを定期的に見直すこと"], answer:2,
    translation:"(Không có audio trong file — nội dung hội thoại không có.)",
    explanation:"Đáp án ③「防災グッズを使ってみること」. ⚠️ Thiếu dữ liệu audio trong file." },
]},
{ tab:"聴解", section:"問題3 概要理解",
  instruction:"問題3では、問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。（⚠️ File đề không có audio cũng không có nội dung in trên giấy.)",
  questions:[
  { id:"c3-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — audio không có. Đáp án chính thức: ④", audioUrl:"", question:"1番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ④." },
  { id:"c3-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ①", audioUrl:"", question:"2番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ①." },
  { id:"c3-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ②", audioUrl:"", question:"3番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c3-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ④", audioUrl:"", question:"4番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ④." },
  { id:"c3-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ①", audioUrl:"", question:"5番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ①." },
]},
{ tab:"聴解", section:"問題4 即時応答",
  instruction:"問題4では、問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。（⚠️ File đề không có audio.)",
  questions:[
  { id:"c4-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ③", audioUrl:"", question:"1番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ③." },
  { id:"c4-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ②", audioUrl:"", question:"2番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c4-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ②", audioUrl:"", question:"3番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c4-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ③", audioUrl:"", question:"4番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ③." },
  { id:"c4-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ①", audioUrl:"", question:"5番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ①." },
  { id:"c4-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ③", audioUrl:"", question:"6番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ③." },
  { id:"c4-7", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ②", audioUrl:"", question:"7番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c4-8", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ②", audioUrl:"", question:"8番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c4-9", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ②", audioUrl:"", question:"9番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c4-10", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ①", audioUrl:"", question:"10番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ①." },
  { id:"c4-11", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE — audio không có. Đáp án chính thức: ③", audioUrl:"", question:"11番（nội dung trong audio）", options:["① audio","② audio","③ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ③." },
]},
{ tab:"聴解", section:"問題5 統合理解",
  instruction:"問題5では長めの話を聞きます。この問題には練習はありません。メモをとってもかまいません。（⚠️ File đề không có audio.)",
  questions:[
  { id:"c5-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — 1番はまず話を聞いて、質問とせんたくしを聞いて答えます。audio không có. Đáp án chính thức: ②", audioUrl:"", question:"1番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
    translation:"Không thể dịch do thiếu nội dung audio.", explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE. Đáp án theo bảng đáp án của đề: ②." },
  { id:"c5-2", passage:"⚠️ Thiếu audio: phần in trên giấy chỉ có 4 lựa chọn về コース; không có nội dung hội thoại. Đáp án chính thức: ②", audioUrl:"", question:"2番（質問1）", options:["1番のコース","2番のコース","3番のコース","4番のコース"], answer:1,
    translation:"(Không có audio trong file — không thể dịch nội dung.)", explanation:"Đáp án ②「2番のコース」theo bảng đáp án của đề. ⚠️ Thiếu dữ liệu audio trong file." },
  { id:"c5-3", passage:"⚠️ Thiếu audio: phần in trên giấy chỉ có 4 lựa chọn về コース; không có nội dung hội thoại. Đáp án chính thức: ④", audioUrl:"", question:"2番（質問2）", options:["1番のコース","2番のコース","3番のコース","4番のコース"], answer:3,
    translation:"(Không có audio trong file — không thể dịch nội dung.)", explanation:"Đáp án ④「4番のコース」theo bảng đáp án của đề. ⚠️ Thiếu dữ liệu audio trong file." },
]},
]});

