/* =========================================================================
   data_2019_12.js — JLPT N2 2019年12月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   Nguồn: pdf_data/2019_12.pdf — bản scan 31 trang (16 trang đề + trang
   bảng 正解表 (第16页) cùng các trang 解説 tiếng Trung và 台本 phần 聴解).
   Toàn bộ đáp án dưới đây đã được đối chiếu với bảng 正解表 của chính file đề.
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2019_12", label:"12/2019", title:"JLPT N2 — 2019年12月 (12/2019)", file:"data_2019_12.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{ tab:"文字・語彙", section:"問題1 漢字読み",
  instruction:"＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a1-1", passage:"", audioUrl:"", question:"1. 木村さんは誰に対しても<u>等しく</u>接する人だ。", options:["やさしく","ひとしく","したしく","きびしく"], answer:1,
    translation:"Anh Kimura là người đối xử với ai cũng bình đẳng như nhau.",
    explanation:"等しい = ひとしい: bình đẳng, ngang nhau ⇒ 等しく = ひとしく. やさしく (優しい: dịu dàng)・したしく (親しい: thân thiết)・きびしく (厳しい: nghiêm khắc) sai nghĩa." },
  { id:"a1-2", passage:"", audioUrl:"", question:"2. 石川さんのけがは、<u>軽傷</u>だったらしい。", options:["けいしょう","けいそう","けしょう","けそう"], answer:0,
    translation:"Vết thương của anh Ishikawa có vẻ chỉ là vết thương nhẹ.",
    explanation:"軽傷 = けいしょう: vết thương nhẹ. けいそう (軽装: trang phục gọn nhẹ)・けしょう (化粧: trang điểm)・けそう (懸想: tương tư) sai âm đọc." },
  { id:"a1-3", passage:"", audioUrl:"", question:"3. 費用はみんなで<u>負担</u>した。", options:["ぶんてん","ふてん","ぶんたん","ふたん"], answer:3,
    translation:"Chi phí được mọi người cùng chia nhau gánh vác.",
    explanation:"負担 = ふたん: gánh vác, chịu (chi phí). ぶんてん (分店: chi nhánh)・ぶんたん (分担: phân công chia nhau làm) sai nghĩa; ふてん là âm đọc sai." },
  { id:"a1-4", passage:"", audioUrl:"", question:"4. 湖に<u>映った</u>夕日がきれいだ。", options:["あたった","ひかった","てった","うつった"], answer:3,
    translation:"Ánh hoàng hôn phản chiếu trên mặt hồ thật đẹp.",
    explanation:"映る = うつる: phản chiếu, phản ánh ⇒ 映った = うつった. あたった (当たった: trúng, đập vào)・ひかった (光った: phát sáng)・てった sai âm đọc." },
  { id:"a1-5", passage:"", audioUrl:"", question:"5. 9月の<u>下旬</u>に旅行に行く予定です。", options:["げしゆん","かじゅん","げじゅん","かしゅん"], answer:2,
    translation:"Tôi dự định đi du lịch vào cuối tháng 9.",
    explanation:"下旬 = げじゅん: cuối tháng (từ ngày 21 đến hết tháng). げしゆん・かじゅん・かしゅん sai âm đọc." },
]},
{ tab:"文字・語彙", section:"問題2 表記",
  instruction:"＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a2-1", passage:"", audioUrl:"", question:"6. その行為は交通ルールに<u>いはん</u>します。", options:["偉判","偉反","違判","違反"], answer:3,
    translation:"Hành vi đó vi phạm luật giao thông.",
    explanation:"いはん = 違反: vi phạm, trái (quy định). 偉判・偉反・違判 là tổ hợp chữ sai (偉 = vĩ đại; 判 = phán xét) — không tạo thành từ 違反." },
  { id:"a2-2", passage:"", audioUrl:"", question:"7. <u>いさましい</u>声が聞こえてきた。", options:["戦ましい","勇ましい","騒ましい","勢ましい"], answer:1,
    translation:"Tôi nghe thấy một giọng nói đầy khí thế, dũng mãnh.",
    explanation:"いさましい = 勇ましい: dũng mãnh, hùng tráng, đầy khí thế. 騒ましい sai vì âm đúng của 騒がしい là さわがしい; 戦ましい・勢ましい không tồn tại (勢いは いきおい)." },
  { id:"a2-3", passage:"", audioUrl:"", question:"8. その店には<u>ようき</u>な音楽が流れていた。", options:["揚起","揚気","陽気","陽起"], answer:2,
    translation:"Trong cửa hàng đó đang vang lên bản nhạc sôi động, vui tươi.",
    explanation:"ようき = 陽気: vui tươi, sôi nổi, hoạt bát. 揚起・揚気・陽起 sai (揚 = giương lên; 起 = dậy) — không tạo thành 陽気." },
  { id:"a2-4", passage:"", audioUrl:"", question:"9. 楽しみにしていたドラマを<u>みのがして</u>しまった。", options:["見逃して","見延して","見欠して","見去して"], answer:0,
    translation:"Tôi đã bỏ lỡ bộ phim mà mình hằng mong đợi.",
    explanation:"みのがす = 見逃す: bỏ lỡ, bỏ sót, để lọt ⇒ 見逃して. 見延して・見欠して・見去して không đúng chữ." },
  { id:"a2-5", passage:"", audioUrl:"", question:"10. 来月から、道路を<u>かくちょう</u>するための工事が始まる。", options:["拡張","広張","拡長","広長"], answer:0,
    translation:"Từ tháng sau, công trình nhằm mở rộng con đường sẽ bắt đầu.",
    explanation:"かくちょう = 拡張: mở rộng, khuếch trương. 広張・拡長・広長 sai chữ (広 = rộng nhưng đọc こう/ひろ; 長 = dài)." },
]},
{ tab:"文字・語彙", section:"問題3 語形成",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a3-1", passage:"", audioUrl:"", question:"11. この建物は（　）町長の時代に建てられたものだ。", options:["先","古","前","昔"], answer:2,
    translation:"Tòa nhà này được xây vào thời kỳ của vị trưởng thị trấn tiền nhiệm.",
    explanation:"前(ぜん) là tiền tố nghĩa 'đời trước, tiền nhiệm' (前会長, 前社長) ⇒ 前町長. 先(せん) chỉ 'trước đó, vừa qua' (先代, 先人); 古(ふる) = cũ; 昔(むかし) không dùng làm tiền tố." },
  { id:"a3-2", passage:"", audioUrl:"", question:"12. 池田さんには何度も助けてもらっているので、今回は頼み（　）。", options:["づらい","わるい","きつい","よわい"], answer:0,
    translation:"Vì đã được anh Ikeda giúp nhiều lần nên lần này tôi khó mà nhờ anh ấy được.",
    explanation:"〜づらい: khó (làm gì) về mặt tâm lý, ngại ⇒ 頼みづらい (khó nhờ). わるい (気味が悪い…), きつい (nặng, chật, gắt), よわい (yếu — 心弱い) không hợp nghĩa." },
  { id:"a3-3", passage:"", audioUrl:"", question:"13. この歌の歌詞は政治（　）が強いように感じられる。", options:["香","風","味","色"], answer:3,
    translation:"Lời của bài hát này có cảm giác mang đậm màu sắc chính trị.",
    explanation:"色(しょく): sắc thái, màu sắc ⇒ 政治色 = màu sắc chính trị (giống 地方色, 国際色). 香 (mùi hương)・風 (phong cách)・味 (vị) không tạo được từ 政治〜 với nghĩa này." },
]},
{ tab:"文字・語彙", section:"問題4 文脈規定",
  instruction:"（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a4-1", passage:"", audioUrl:"", question:"14. 今日は残業で疲れていて夕食を作るのが（　）だから、外で食べて帰ろうと思う。", options:["余計","面倒","過剰","無力"], answer:1,
    translation:"Hôm nay tăng ca mệt nên nấu bữa tối thấy phiền phức, thôi định ăn ngoài rồi về.",
    explanation:"面倒(めんどう): phiền phức, phiền hà ⇒ 作るのが面倒だ (nấu ăn thấy phiền). 余計 (dư thừa, không cần)・過剰 (quá mức, thừa)・無力 (bất lực) sai nghĩa." },
  { id:"a4-2", passage:"", audioUrl:"", question:"15. この犬のロボットは動きが自然で、まるで（　）の犬のようだ。", options:["本物","現状","事実","正式"], answer:0,
    translation:"Chú chó robot này chuyển động tự nhiên, cứ như chó thật vậy.",
    explanation:"本物(ほんもの): đồ thật, hàng thật ⇒ まるで本物の犬のようだ. 現状 (hiện trạng)・事実 (sự thật)・正式 (chính thức) sai nghĩa." },
  { id:"a4-3", passage:"", audioUrl:"", question:"16. 山下先輩は私の（　）で、いつか山下先輩のようになりたいと思っている。", options:["あこがれ","望み","願い","夢"], answer:0,
    translation:"Tiền bối Yamashita là người tôi hằng ngưỡng mộ, tôi mong một ngày nào đó được như anh ấy.",
    explanation:"あこがれ: sự ngưỡng mộ, khát khao hướng tới ⇒ 私のあこがれ (người tôi ngưỡng mộ). 望み・願い (nguyện vọng, mong muốn)・夢 (giấc mơ) không diễn tả 'đối tượng được hâm mộ'." },
  { id:"a4-4", passage:"", audioUrl:"", question:"17. 今日会社で京都支社から東京本社への（　）を命じられ、今月末に東京へ引っ越すことになった。", options:["移行","転職","転勤","移住"], answer:2,
    translation:"Hôm nay ở công ty tôi được lệnh điều chuyển từ chi nhánh Kyoto về trụ sở Tokyo, cuối tháng này sẽ chuyển nhà đến Tokyo.",
    explanation:"転勤(てんきん): điều chuyển nơi làm việc trong cùng công ty ⇒ đúng với 'từ chi nhánh về trụ sở'. 移行 (chuyển tiếp)・転職 (đổi nghề, nhảy việc)・移住 (di cư, chuyển nơi ở) sai nghĩa." },
  { id:"a4-5", passage:"", audioUrl:"", question:"18. この辺りの農家は、無農薬で野菜を（　）しています。", options:["制作","栽培","養成","製造"], answer:1,
    translation:"Nông dân vùng này trồng rau không dùng thuốc trừ sâu.",
    explanation:"栽培(さいばい): trồng trọt, canh tác ⇒ 野菜を栽培する. 制作 (chế tác tác phẩm)・養成 (đào tạo, nuôi dưỡng người)・製造 (chế tạo, sản xuất công nghiệp) sai đối tượng." },
  { id:"a4-6", passage:"", audioUrl:"", question:"19. 彼は私の意見に対して何も言わなかったが、（　）ことで同意を示してくれた。", options:["ふりむく","にらむ","かがむ","うなずく"], answer:3,
    translation:"Anh ấy không nói gì với ý kiến của tôi, nhưng đã gật đầu để thể hiện sự đồng ý.",
    explanation:"うなずく(頷く): gật đầu, tán thành ⇒ うなずくことで同意を示す. ふりむく (quay đầu lại/để tâm)・にらむ (trừng mắt)・かがむ (cúi xuống) sai nghĩa." },
  { id:"a4-7", passage:"", audioUrl:"", question:"20. 机の上がいろいろな物で（　）しているから、早くきれいに片付けよう。", options:["きちんと","ぼんやり","ごちゃごちゃ","きょろきょろ"], answer:2,
    translation:"Trên bàn đầy ắp thứ bừa bộn, nên mau dọn dẹp cho gọn gàng đi.",
    explanation:"ごちゃごちゃ: lộn xộn, bừa bãi ⇒ 物でごちゃごちゃしている. きちんと (ngăn nắp, đúng mực — trái nghĩa)・ぼんやり (mơ hồ, thẫn thờ)・きょろきょろ (ngó nghiêng lia lịa) sai nghĩa." },
]},
{ tab:"文字・語彙", section:"問題5 言い換え類義",
  instruction:"＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a5-1", passage:"", audioUrl:"", question:"21. この仕事はとても<u>ハード</u>だ。", options:["楽しい","簡単だ","大変だ","新しい"], answer:2,
    translation:"Công việc này rất vất vả.",
    explanation:"ハード (hard): vất vả, khó nhọc, nặng nề ⇒ gần nghĩa nhất với 大変だ (gian nan, cực nhọc). 楽しい (vui)・簡単だ (đơn giản)・新しい (mới) trái/khác nghĩa." },
  { id:"a5-2", passage:"", audioUrl:"", question:"22. その話を聞いて<u>動揺した</u>。", options:["うれしくなった","不安になった","不満に思った","面白いと思った"], answer:1,
    translation:"Nghe câu chuyện đó, tôi cảm thấy bất an, dao động.",
    explanation:"動揺する: dao động, hoang mang, bất an ⇒ gần nhất với 不安になった (trở nên bất an). うれしくなった (vui lên)・不満に思った (thấy bất mãn)・面白いと思った (thấy thú vị) sai nghĩa." },
  { id:"a5-3", passage:"", audioUrl:"", question:"23. 早く<u>引き返した</u>ほうがいい。", options:["払った","直した","戻った","答えた"], answer:2,
    translation:"Tốt hơn là nhanh chóng quay lại (quay về).",
    explanation:"引き返す: quay lại, quay về (đường cũ) ⇒ gần nhất với 戻った (trở về). 払った (đã trả)・直した (sửa)・答えた (trả lời) sai nghĩa." },
  { id:"a5-4", passage:"", audioUrl:"", question:"24. 機能を<u>一層</u>強化したい。", options:["すぐに","少し","できるだけ","もっと"], answer:3,
    translation:"Muốn tăng cường chức năng hơn nữa.",
    explanation:"一層: hơn nữa, càng thêm ⇒ gần nhất với もっと (hơn). すぐに (ngay)・少し (một chút)・できるだけ (càng nhiều càng tốt) sai nghĩa." },
  { id:"a5-5", passage:"", audioUrl:"", question:"25. 急にひどい頭痛がしてきたので、<u>かかりつけの</u>病院に行った。", options:["いつも行く","休日も開いている","近くの","専門の"], answer:0,
    translation:"Đột nhiên bị đau đầu dữ dội nên tôi đến bệnh viện mà mình vẫn khám thường xuyên.",
    explanation:"かかりつけ (の病院): (bệnh viện) mình thường đi khám ⇒ gần nhất với いつも行く (vẫn thường đến). 休日も開いている (mở cả ngày lễ)・近くの (gần đó)・専門の (chuyên khoa) sai nghĩa." },
]},
{ tab:"用法", section:"問題6 用法",
  instruction:"次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a6-1", passage:"", audioUrl:"", question:"26. 特殊", options:["その日は夏なのに特殊な寒さだった。","自分で育てた野菜を食べるのは特殊な喜びがある。","母は誕生日など、特殊な日にはとても豪華な料理を作ってくれる。","バスを運転するためには特殊な免許が必要だ。"], answer:3,
    translation:"特殊: đặc thù, đặc biệt (khác thường). Dùng đúng: 'Để lái xe buýt cần một loại bằng lái đặc thù.'",
    explanation:"特殊: đặc thù, khác thường so với thông thường ⇒ 特殊な免許 (bằng lái đặc thù) hợp. ① 夏なのに特殊な寒さ → nên là 異常な (bất thường) / 珍しい; ② 特殊な喜び → nên là 特別な (đặc biệt) / 格別な; ③ 特殊な日 → nên là 特別な日." },
  { id:"a6-2", passage:"", audioUrl:"", question:"27. 素材", options:["プラスチックは石油を素材に作られている。","このお店は素材の味を生かした料理で有名です。","いろいろな情報を集めて、判断の素材にする。","故障の素材になったものを探さなくてはいけない。"], answer:1,
    translation:"素材: nguyên liệu, vật liệu (làm nên cái gì). Dùng đúng: 'Quán này nổi tiếng với các món ăn tận dụng vị nguyên bản của nguyên liệu.'",
    explanation:"素材: nguyên liệu ⇒ 素材の味 (vị của nguyên liệu) hợp. ① 石油を素材に → nên là 原料 (nguyên liệu thô); ③ 判断の素材 → nên là 材料 (tư liệu, căn cứ); ④ 故障の素材 → nên là 原因 (nguyên nhân)." },
  { id:"a6-3", passage:"", audioUrl:"", question:"28. しみる", options:["飛んできたボールが頭にしみて、けがをした。","煙が目にしみて、涙が止まらなくなった。","食べすぎで、ベルトがおなかにしみて苦しい。","料理をしているときに包丁の先が指にしみて、少し血が出た。"], answer:1,
    translation:"しみる: thấm vào, ngấm vào; (khói, nước…) làm nhức/xót. Dùng đúng: 'Khói xộc vào mắt khiến nước mắt không ngừng chảy.'",
    explanation:"しみる: thấm/ngấm vào, gây xót, nhức (煙が目にしみる) ⇒ ②  hợp. ① 頭にしみて → nên là ぶつかって (đập vào); ③ ベルトが…しみて → nên là 食い込んで (siết vào); ④ 包丁の先が指にしみて → nên là 刺さって (đâm vào)." },
  { id:"a6-4", passage:"", audioUrl:"", question:"29. 充満", options:["この図書館は、あらゆる分野の本が充満していて、とても便利だ。","このコンサートは人気があって、常に観客が充満している。","部屋に食べ物の強いにおいが充満していたので、窓を開けた。","夢が充満している子どもたちが大好きで、小学校の教師になった。"], answer:2,
    translation:"充満: tràn ngập, đầy ắp (khí, mùi, âm thanh…). Dùng đúng: 'Vì trong phòng tràn ngập mùi thức ăn nồng nặc nên tôi đã mở cửa sổ.'",
    explanation:"充満: (khí/mùi…) tràn ngập không gian ⇒ ③ 部屋ににおいが充満する hợp. ① 本が充満 → nên là 充実 (phong phú, đầy đủ); ② 観客が充満 → nên là 押し寄せて (ùn ùn kéo tới); ④ 夢が充満 → nên là あふれて (tràn đầy)." },
  { id:"a6-5", passage:"", audioUrl:"", question:"30. めくる", options:["この小説は面白くて、次のページをめくるのが楽しみだった。","汗をかいたので、タオルを水でぬらし、きつくめくって体をふいた。","封筒に書類を入れ、開かないように丁寧にのりでめくっておいた。","そのドアは押すのではなくて手前にめくらないと開きませんよ。"], answer:0,
    translation:"めくる: lật (trang sách, tờ giấy). Dùng đúng: 'Tiểu thuyết này hay đến nỗi tôi háo hức lật sang trang tiếp theo.'",
    explanation:"めくる: lật, giở (trang) ⇒ ① 次のページをめくる hợp. ② タオルを…めくって → nên là 絞って (vắt); ③ のりでめくって → nên là 貼って (dán); ④ ドアを…めくる → nên là 引かないと (không kéo ra)." },
]},
/* ================= TAB 3: 文法 ================= */
{ tab:"文法", section:"問題7 文の文法1",
  instruction:"次の文の（　）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a7-1", passage:"", audioUrl:"", question:"31. X市とY市を結ぶ橋が、約10年の工事（　）、昨年ようやく完成した。", options:["の際","の末","のたび","のもと"], answer:1,
    translation:"Cây cầu nối thành phố X và thành phố Y, sau quá trình thi công kéo dài khoảng 10 năm, năm ngoái cuối cùng đã hoàn thành.",
    explanation:"〜の末(に): sau một quá trình dài, vất vả ⇒ cuối cùng mới có kết quả ⇒ 工事の末. の際 (khi, nhân dịp)・のたび (mỗi lần)・のもと (dưới sự…) sai nghĩa." },
  { id:"a7-2", passage:"", audioUrl:"", question:"32. 「田中さんがこの会社をやめるって話、まだ秘密みたいだから、悪いけど、聞かなかった（　）にしてくれない?」", options:["こと","だけ","もの","の"], answer:0,
    translation:"“Chuyện anh Tanaka nghỉ việc ở công ty này hình như vẫn còn là bí mật, nên xin lỗi nhé, cậu có thể coi như chưa từng nghe thấy không?”",
    explanation:"Vた + ことにする: coi như là…, giả sử là… ⇒ 聞かなかったことにして (coi như chưa nghe). だけ・もの・の không tạo thành cấu trúc này." },
  { id:"a7-3", passage:"", audioUrl:"", question:"33. 最近、よくお腹が痛くなるので、病院で診てもらったら、（　）ストレスが原因だろうと言われた。", options:["どうか","まさか","おそらく","いったい"], answer:2,
    translation:"Dạo này hay bị đau bụng nên tôi đi khám, bác sĩ nói có lẽ nguyên nhân là do căng thẳng.",
    explanation:"おそらく: có lẽ, e rằng (biểu thị phỏng đoán), thường đi với だろう ⇒ おそらく…だろう. どうか (xin hãy…)・まさか (không ngờ)・いったい (rốt cuộc — nghi vấn mạnh) sai nghĩa." },
  { id:"a7-4", passage:"", audioUrl:"", question:"34. 私は、急な雨（　）、いつも折り畳み傘を持ち歩いている。", options:["に反して","に加えて","に備えて","に応じて"], answer:2,
    translation:"Tôi luôn mang theo ô gấp để phòng khi trời mưa bất chợt.",
    explanation:"〜に備えて: để chuẩn bị, phòng khi ⇒ 急な雨に備えて. に反して (trái với)・に加えて (thêm vào)・に応じて (tùy theo) sai nghĩa." },
  { id:"a7-5", passage:"", audioUrl:"", question:"35. （自転車屋で）客「すみません、自転車のブレーキ、壊れちゃったんですけど、すぐ直りますか。」　店員「そうですね、これだったら30分（　）直りますよ。」", options:["もあるのに","もあれば","はないのに","はなければ"], answer:1,
    translation:"(Ở tiệm xe đạp) Khách: “Xin lỗi, phanh xe đạp của tôi bị hỏng, sửa ngay được không ạ?” Nhân viên: “Để xem nào, cái này thì nhiều lắm 30 phút là sửa xong.”",
    explanation:"数詞 + も + あれば: nếu (nhiều lắm)…thì (nêu giới hạn tối đa) ⇒ 30分もあれば直る (nhiều lắm 30 phút là xong). もあるのに・はないのに・はなければ sai ngữ pháp/nghĩa." },
  { id:"a7-6", passage:"", audioUrl:"", question:"36. （講演会で）司会「ご来場の皆様、本日は第3回さくら市教育講演会に（　）、ありがとうございます。」", options:["まいり","ご覧になり","お目にかかり","おいでくださり"], answer:3,
    translation:"(Tại buổi thuyết trình) Người dẫn chương trình: “Kính thưa quý vị có mặt, cảm ơn quý vị đã đến với buổi thuyết trình giáo dục lần thứ 3 của thành phố Sakura hôm nay.”",
    explanation:"おいでくださり: dạng kính ngữ (tôn kính) của 来る ⇒ cảm ơn khách đã đến ⇒ đúng. まいり (khiêm nhường ngữ của 来る)・お目にかかり (khiêm nhường ngữ của 会う) dùng cho hành vi của mình; ご覧になり (kính ngữ của 見る) sai động từ." },
  { id:"a7-7", passage:"", audioUrl:"", question:"37. 夫は動物が好きじゃないから、もし私がペットを飼いたいと言っても、（　）。", options:["反対しかねる","反対しようがない","反対するならいい","反対するに決まっている"], answer:3,
    translation:"Chồng tôi không thích động vật, nên dù tôi có nói muốn nuôi thú cưng thì chắc chắn anh ấy sẽ phản đối.",
    explanation:"〜に決まっている: chắc chắn là…, nhất định là… ⇒ 反対するに決まっている. 反対しかねる (khó mà phản đối)・反対しようがない (không có cách phản đối)・反対するならいい sai nghĩa." },
  { id:"a7-8", passage:"", audioUrl:"", question:"38. 今はスポーツも演劇もテレビで見られる時代だが、直接見ることに（　）得られない感動というものがある。", options:["とってしか","よってしか","ついてのみ","対してのみ"], answer:1,
    translation:"Giờ đây là thời đại mà cả thể thao lẫn kịch đều xem được qua tivi, nhưng có những rung cảm chỉ có thể có được khi được xem trực tiếp.",
    explanation:"〜によってしか〜ない: chỉ có thể nhờ vào… (mới có) ⇒ 直接見ることによってしか得られない. にとって (đối với)・について (về)・に対して (đối với) không hợp nghĩa/cấu trúc しか." },
  { id:"a7-9", passage:"", audioUrl:"", question:"39. 子供のおもちゃは、種類ごとに透明なケースにしまって中身がわかる（　）、子供がおもちゃを探しやすくなるので、おすすめです。", options:["ようになるには","ようにしておくと","ようになっても","ようにしておいて"], answer:1,
    translation:"Đồ chơi trẻ em nên cất theo loại vào hộp nhựa trong suốt, làm sao để nhìn thấy bên trong thì trẻ sẽ dễ tìm đồ chơi hơn, nên rất đáng khuyên dùng.",
    explanation:"〜ようにしておく + と (giả định/điều kiện): nếu chuẩn bị sẵn sao cho… thì… ⇒ わかるようにしておくと. ようになるには (để trở nên)・ようになっても (dù trở nên)・ようにしておいて (chuẩn bị sẵn — không hợp と điều kiện) sai." },
  { id:"a7-10", passage:"", audioUrl:"", question:"40. 昨日購入した中古の大型バイクは、かなり古いものなのだが、とてもきれいな状態だった。前の持ち主によほど大切に（　）。", options:["されてもおかしくない","し続けてもおかしくない","されていたに違いない","し続けていたに違いない"], answer:2,
    translation:"Chiếc xe máy phân khối lớn đã qua sử dụng mua hôm qua đã khá cũ nhưng trạng thái rất tốt. Hẳn là chủ trước đã rất trân trọng, giữ gìn nó.",
    explanation:"「前の持ち主に」dùng trợ từ に ⇒ phải là thể bị động 大切にされる, và に違いない (hẳn là…) ⇒ 大切にされていたに違いない. Các phương án dùng し続けて (tự làm) hoặc てもおかしくない sai." },
  { id:"a7-11", passage:"", audioUrl:"", question:"41. （電話で）上田「課長、すみません、今日はお休みをいただけないでしょうか。娘と夫が風邪で熱を出してしまったんです。」　課長「それは大変だね。わかりました。看病でお疲れで、上田さんが（　）。」", options:["倒れなくなるよ","倒れてしまいたくないのに","倒れないことになるの","倒れてしまわないようにね"], answer:3,
    translation:"(Qua điện thoại) Ueda: “Trưởng phòng, xin lỗi, hôm nay tôi xin nghỉ được không ạ? Con gái và chồng tôi bị cảm, sốt mất rồi.” Trưởng phòng: “Thế thì vất vả quá. Tôi hiểu rồi. Chăm người bệnh mệt mỏi, Ueda đừng để mình ngã bệnh nhé.”",
    explanation:"〜ようにね: biểu thị mong mỏi, cầu chúc ⇒ 倒れてしまわないようにね (mong đừng để bị ngã/đổ bệnh). 倒れなくなるよ (sẽ không ngã)・倒れてしまいたくないのに (dù không muốn ngã)・倒れないことになるの (sẽ không ngã — ことになる chỉ quyết định/kết quả) sai nghĩa." },
  { id:"a7-12", passage:"", audioUrl:"", question:"42. 山田「林さんの手作りクッキー、本当においしかったです。どうもありがとうございました。」　林「どういたしまして。山田さんにおいしいって（　）です。」", options:["言ってもらえてよかった","言ってもらってもよかった","言ってあげられてよかった","言ってあげてもよかった"], answer:0,
    translation:"Yamada: “Bánh quy làm tay của chị Hayashi ngon thật đấy. Cảm ơn chị nhiều.” Hayashi: “Không có gì. Tôi rất vui vì được anh Yamada khen ngon.”",
    explanation:"言ってもらえて (được người khác nói cho mình) + よかった (thật tốt/vui) ⇒ うれしい気持ち ⇒ đúng. 言ってあげられて (mình nói cho người khác) ngược hướng; 〜てもよかった/〜てあげてもよかった sai nghĩa." },
]},
{ tab:"文法", section:"問題8 文の文法2 (sắp xếp - ★)",
  instruction:"次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a8-1", passage:"", audioUrl:"", question:"43. 他社からの質問や問い合わせには、一度社内で ＿＿ ＿＿★ ＿＿ ＿＿ できないことになっています。［1 検討 / 2 回答 / 3 でないと / 4 してから］", options:["検討","回答","でないと","してから"], answer:2,
    translation:"Quy định rằng, với câu hỏi hay thắc mắc từ công ty khác, nếu chưa bàn bạc trong nội bộ thì không thể trả lời.",
    explanation:"Thứ tự đúng: 検討(1)→してから(4)→でないと(3)→回答(2): 「一度社内で検討してからでないと回答できない」. ★ là ô thứ 3 ⇒ đáp án ③ でないと. 〜してからでないと: chưa làm… thì không thể… (đi với phủ định)." },
  { id:"a8-2", passage:"", audioUrl:"", question:"44. 昨日の夜は、11時までには ＿＿ ＿＿★ ＿＿ ＿＿ 、結局寝たのは1時だった。［1 つい / 2 寝ようと / 3 思いつつ / 4 テレビを見続けてしまい］", options:["つい","寝ようと","思いつつ","テレビを見続けてしまい"], answer:0,
    translation:"Đêm qua, định bụng là ngủ trước 11 giờ nhưng rồi cứ xem tivi mãi, kết cục 1 giờ mới ngủ.",
    explanation:"Thứ tự đúng: 寝ようと(2)→思いつつ(3)→つい(1)→テレビを見続けてしまい(4): 「…寝ようと思いつつ、ついテレビを見続けてしまい…」. ★ là ô thứ 3 ⇒ đáp án ① つい. 〜つつ: tuy… nhưng…; つい: vô tình, lỡ." },
  { id:"a8-3", passage:"", audioUrl:"", question:"45. 私は、新しいことにチャレンジするときも悩まない。 ＿＿ ＿＿★ ＿＿ ＿＿ と思っているからだ。［1 まずやってみて / 2 もう一度考えればいい / 3 うまくいかなかったら / 4 そのときにどうしたらいいか］", options:["まずやってみて","もう一度考えればいい","うまくいかなかったら","そのときにどうしたらいいか"], answer:3,
    translation:"Khi thử sức với việc mới tôi cũng không đắn đo, vì tôi nghĩ rằng cứ thử làm trước đã, nếu không thuận lợi thì lúc đó nghĩ xem nên làm thế nào là được.",
    explanation:"Thứ tự đúng: まずやってみて(1)→うまくいかなかったら(3)→そのときにどうしたらいいか(4)→もう一度考えればいい(2). ★ là ô thứ 3 ⇒ đáp án ④ そのときにどうしたらいいか. 〜たら: nếu…" },
  { id:"a8-4", passage:"", audioUrl:"", question:"46. 家の近くの本屋では ＿＿ ＿＿★ ＿＿ ＿＿ 少し遠いけど行ってみようと思う。［1 買えなかった漫画の最新号が / 2 まだ買えるらしいので / 3 もう売り切れていて / 4 隣町のABC書店に行けば］", options:["買えなかった漫画の最新号が","まだ買えるらしいので","もう売り切れていて","隣町のABC書店に行けば"], answer:3,
    translation:"Ở hiệu sách gần nhà, số mới nhất của bộ truyện mình chưa mua được đã hết hàng mất rồi, nghe nói nếu đến hiệu sách ABC ở thị trấn bên thì vẫn còn mua được, nên tuy hơi xa nhưng tôi định thử ghé xem.",
    explanation:"Thứ tự đúng: もう売り切れていて(3)→買えなかった漫画の最新号が(1)→隣町のABC書店に行けば(4)→まだ買えるらしいので(2). ★ là ô thứ 3 ⇒ đáp án ④ 隣町のABC書店に行けば. 〜らしい: nghe nói, hình như." },
  { id:"a8-5", passage:"", audioUrl:"", question:"47. 話題のカレー屋さんを初訪問。野菜の ＿＿ ＿＿★ ＿＿ ＿＿ 「夏限定ベジタブルカレー」。評判どおりのおいしさだった。［1 中で / 2 私が選んだのは / 3 夏の野菜がたっぷり入った / 4 カレーがいくつかある］", options:["中で","私が選んだのは","夏の野菜がたっぷり入った","カレーがいくつかある"], answer:1,
    translation:"Lần đầu ghé thăm quán cà ri đang hot. Trong vài loại cà ri rau củ, món tôi chọn là “Cà ri rau củ mùa hè giới hạn” đầy ắp rau mùa hè. Ngon đúng như lời đồn.",
    explanation:"Thứ tự đúng: カレーがいくつかある(4)→中で(1)→私が選んだのは(2)→夏の野菜がたっぷり入った(3). ★ là ô thứ 3 ⇒ đáp án ② 私が選んだのは. いくつかある中で: trong số mấy cái…" },
]},
{ tab:"文法", section:"問題9 文章の文法 (điền vào đoạn văn)",
  instruction:"次の文章を読んで、文章全体の内容を考えて、48から52の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"a9-1", passage:"以下は、伊能忠敬という人物について書かれた文章である。<br><br>初めて正確な日本地図を作成した人物として知られる伊能忠敬は、1745年、上総国（今の千葉県）に生まれた。優れた経営者だった忠敬だが、50歳を前に仕事をやめ、興味があった星や暦について高橋至時のもとで（48）。19歳も年下の至時を忠敬は敬い、熱心に勉強した。<br><br>当時の学者たちの関心は、地球の直径を知ることにあった。江戸（今の東京）から蝦夷地（今の北海道）までの距離は当時はまだわからなかったが、それが（49）正確に直径が計算できると知った忠敬は、蝦夷地へ行くことを願う。<br><br>しかし、蝦夷地に行くには国の許可が必要だった。至時は、蝦夷地の地図作成を理由に国の許可をとり、忠敬を担当にする。（50）、忠敬55歳のとき、地図作りの旅が始まった。<br><br>昼間は測って歩き、夜は星を観察して昼間測った数値を修正する日々が続いた。完成した蝦夷地の地図は国から高く評価され、忠敬は東日本の地図作成も（51）。地図作成の旅は順調に終わったが、完成前に、忠敬を支え続けた至時が病気で亡くなってしまう。一番の理解者である至時を失い、忠敬はひどく落ち込んだ。だが、悲しみに耐え、さらに命じられた西日本の地図作成にも取り組む。旅を終え、完成に向けて作業の最終段階に入っていた1818年、忠敬は73歳で人生の幕を閉じた。作業は弟子らが続け、1821年、日本全国の地図が完成した。<br><br>忠敬は自分に大きな仕事ができたのはすべて至時先生のおかげだと書き残している。歴史に残る（52）は、二人の信頼関係によって、誕生したのである。", audioUrl:"", question:"48. 優れた経営者だった忠敬だが、50歳を前に仕事をやめ、興味があった星や暦について高橋至時のもとで（48）。", options:["学んだばかりだ","学ぼうと思っている","学び始めた","学ぶところだった"], answer:2,
    translation:"Đoạn văn kể về nhân vật Inō Tadataka. Ông nổi tiếng là người đầu tiên lập bản đồ Nhật Bản chính xác. Vốn là một nhà kinh doanh tài giỏi nhưng trước tuổi 50 ông nghỉ việc, và bắt đầu học về tinh tú, lịch pháp mà mình vốn hứng thú dưới sự dẫn dắt của Takahashi Yoshitoki (48).",
    explanation:"【48】= 学び始めた: bắt đầu học. Đoạn trước nói ông nghỉ việc khi gần 50, sau là 「熱心に勉強した」, cả bài là hồi ký quá khứ ⇒ 学び始めた ✓. 学んだばかりだ (vừa mới học)・学ぼうと思っている (định học)・学ぶところだった (đang định học thì…) sai thời/thể." },
  { id:"a9-2", passage:"", audioUrl:"", question:"49. 江戸から蝦夷地までの距離は当時はまだわからなかったが、それが（49）正確に直径が計算できると知った忠敬は、蝦夷地へ行くことを願う。", options:["わかって","わかれば","わかるため","わかったことで"], answer:1,
    translation:"Khoảng cách từ Edo đến vùng Ezo lúc đó chưa ai biết, nhưng khi biết rằng nếu hiểu được điều đó thì có thể tính chính xác đường kính trái đất, Tadataka đã mong muốn được đi Ezo.",
    explanation:"【49】= わかれば: nếu biết được (điều kiện) ⇒ 「それがわかれば正確に…計算できる」✓. わかって/わかるため/わかったことで đều mang nghĩa nguyên nhân ('vì biết'), không hợp cấu trúc 'nếu… thì có thể'." },
  { id:"a9-3", passage:"", audioUrl:"", question:"50. 至時は、蝦夷地の地図作成を理由に国の許可をとり、忠敬を担当にする。（50）、忠敬55歳のとき、地図作りの旅が始まった。", options:["また","しかも","ところが","こうして"], answer:3,
    translation:"Yoshitoki lấy lý do lập bản đồ vùng Ezo để xin phép triều đình, và để Tadataka phụ trách. Như thế, vào năm 55 tuổi, chuyến đi vẽ bản đồ của Tadataka bắt đầu.",
    explanation:"【50】= こうして: như thế, do đó (từ nối tổng kết diễn biến) ⇒ 「こうして、…旅が始まった」✓. また (lại)・しかも (hơn nữa)・ところが (thế nhưng) sai mạch văn." },
  { id:"a9-4", passage:"", audioUrl:"", question:"51. 完成した蝦夷地の地図は国から高く評価され、忠敬は東日本の地図作成も（51）。", options:["命じられることとなる","命じられたことになる","命じられることもある","命じられたことである"], answer:0,
    translation:"Bản đồ vùng Ezo hoàn thành được triều đình đánh giá cao, và Tadataka rốt cuộc cũng được giao cả việc lập bản đồ miền Đông Nhật Bản.",
    explanation:"【51】= 命じられることとなる: (thể từ điển) + こととなる: kết cục là, cuối cùng được… ⇒ 「東日本の地図作成も命じられることとなる」✓. 命じられたことになる sai cách dùng; 命じられることもある (đôi khi cũng được giao — không phù hợp); 命じられたことである sai." },
  { id:"a9-5", passage:"", audioUrl:"", question:"52. 忠敬は自分に大きな仕事ができたのはすべて至時先生のおかげだと書き残している。歴史に残る（52）は、二人の信頼関係によって、誕生したのである。", options:["これ","あるもの","日本地図","そういう地図"], answer:2,
    translation:"Tadataka viết lại rằng ông làm được công việc lớn lao là nhờ tất cả công ơn thầy Yoshitoki. Bản đồ Nhật Bản còn lưu danh sử sách (52) đã ra đời nhờ mối quan hệ tin cậy của hai người.",
    explanation:"【52】= 日本地図: cả bài nói về việc làm nên bản đồ Nhật Bản ⇒ từ khái quát phù hợp nhất ✓. これ (cái này — dễ bị hiểu là 'điều được viết lại')・あるもの (một thứ nào đó)・そういう地図 (bản đồ như thế — trung chỉ, chỉ nhiều thứ) sai." },
]},
/* ================= TAB 4: 読解 ================= */
{ tab:"読解", section:"問題10 内容理解・短文",
  instruction:"次の（1）から（5）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b10-1", passage:"（1）人に何か言われて、それがどんな意味なんだろう、どうしてそんなことを言ったんだろうと、一人で考えれば考えるほど、あなたは成長します。<br>逆に言えば、自分一人で考える時間がなければ、あなたはどんなに立派な話を聞いても、どんなに役立つ本を読んでも、その考えやアイデアは、あなたのものになりません。取ってつけた（注1）ようで、人は、それがあなたの本当の知識じゃないことを見抜きます（注2）。<br><br>（注1）取ってつけた：無理に付け加えた<br>（注2）～を見抜く：ここでは、～に簡単に気づく", audioUrl:"", question:"53. 筆者の考えに合うのはどれか。", options:["自分自身を知るには、一人で考える時間が必要だ。","人として成長するには、自分一人で考える時間が必要だ。","自分一人で考える時間が長ければ、よいアイデアが浮かぶ。","本当の知識を得るには、役立つ本や立派な話に接するべきだ。"], answer:1,
    translation:"Khi bị ai đó nói điều gì, càng tự mình suy nghĩ xem nó có nghĩa gì, vì sao người ta nói thế thì bạn càng trưởng thành. Ngược lại, nếu không có thời gian tự suy nghĩ một mình thì dù nghe chuyện hay, đọc sách bổ ích đến đâu, ý tưởng đó cũng không thành của bạn — người ta sẽ nhận ra đó không phải kiến thức thật của bạn.",
    explanation:"Câu đầu nêu 「一人で考えれば考えるほど、あなたは成長します」; nếu không có thời gian suy nghĩ một mình thì kiến thức không thành của mình ⇒ để trưởng thành cần thời gian suy nghĩ một mình ⇒ đáp án 2 ✓. 1 (hiểu bản thân)・3 (suy nghĩ lâu thì có ý tưởng hay — văn không nói)・4 (phải đọc sách hay, nghe chuyện hay) sai." },
  { id:"b10-2", passage:"（2）以下は、ある市の国際交流協会から届いたメールである。<br><br>水森市国際交流協会<br>会員の皆様<br><br>今年も水森市国際交流協会の活動に参加してくださりありがとうございました。<br>会員の方にはこれまで毎年12月に会費4,000円（翌年1月から12月の1年分）を納めていただきましたが、来年より4月に会費（4月から翌年3月の1年分）を納めていただくことになりました。<br>今回の変更に伴い、来年1月から3月までの分の1,000円は、1月の交流会で集めます。<br>なお、1月の交流会に参加できない場合は、1月中に事務局にお持ちください。<br>今後ともよろしくお願いいたします。<br><br>水森市国際交流協会事務局<br>会計担当　赤木春香", audioUrl:"", question:"54. 会員は、来年1月から再来年3月までの会費をどのように払えばいいか。", options:["今年12月に4,000円払い、来年1月に1,000円払う。","来年1月に1,000円と4,000円を払う。","来年1月に1,000円払い、4月に4,000円払う。","来年4月に1,000円と4,000円を払う。"], answer:2,
    translation:"Email từ Hiệp hội Giao lưu Quốc tế thành phố Mizumori. Trước đây hội viên nộp phí 4.000 yên mỗi năm vào tháng 12; từ năm sau sẽ nộp vào tháng 4 (cho 1 năm từ tháng 4 đến tháng 3 năm sau). Phần 1.000 yên cho tháng 1–3 năm sau sẽ thu tại buổi giao lưu tháng 1 (nếu không dự được thì mang đến văn phòng trong tháng 1).",
    explanation:"Từ năm sau đổi thành nộp phí vào tháng 4 (1 năm từ 4月→翌年3月); phần 来年1月～3月 tương ứng 1,000円 thì thu vào tháng 1 ⇒ 来年1月に1,000円 + 4月に4,000円 ⇒ đáp án 3 ✓." },
  { id:"b10-3", passage:"（3）ヒトと機械は違っているからこそ、補完し（注1）合えるのだという考え方がある。同じであっては意味が無いとさえ言い切る人もいる。同じものが二つあっても量的な能力が倍増する（注2）だけであって、質的な変化は起こりえない。初期のコンピュータが結構役に立ったのは人間と全く違った単純作業ができたからである。人間だと繰り返しの作業の中でどうしても思い込みが起こる。コンピュータが得意なのは常に一定の判断である。それであるがゆえに（注3）人間の単純なミスを指摘できるのである。<br><br>（注1）補完する：不十分な部分を補う<br>（注2）倍増する：二倍に増える<br>（注3）それであるがゆえに：だから", audioUrl:"", question:"55. 筆者によると、コンピュータがヒトと違う点は何か。", options:["ヒトの単純なミスを予測できること","ヒトの二倍の量の仕事ができること","常に質の高い仕事ができること","常に同じ作業ができること"], answer:3,
    translation:"Có quan điểm cho rằng chính vì người và máy khác nhau nên mới bù đắp được cho nhau. Máy tính thời kỳ đầu hữu ích vì làm được công việc đơn giản hoàn toàn khác con người; con người dễ sinh định kiến trong công việc lặp lại, còn máy tính sở trường là luôn phán đoán nhất định, nhờ đó chỉ ra được sai sót đơn giản của con người.",
    explanation:"「コンピュータが得意なのは常に一定の判断である」⇒ điểm khác là luôn làm được công việc/ phán đoán ổn định, không đổi ⇒ đáp án 4 ✓. 1 (dự đoán sai sót — văn là '指摘できる' chỉ ra, không phải dự đoán)・2 (gấp đôi lượng việc)・3 (luôn chất lượng cao) sai." },
  { id:"b10-4", passage:"（4）以下は、あるカメラメーカーがホームページに掲載したお知らせである。<br><br>ビーエスカメラ＞製品情報<br>2019年10月8日<br><br>デジタルカメラ「BS-ZG1」に関するお知らせ<br><br>弊社のデジタルカメラ「BS-ZG1」は、電源ボタンの不具合が見付かったため、9月30日より販売を一時中止しておりました。その後の調査の結果、この不具合は製造番号ZH29200～ZH29800の製品にのみ起きることが分かりました。対象の製品をお持ちのお客様は、現在不具合が起きていなくても無料で修理させていただきますので、お手数ですがお近くの販売店までお持ちくださいますようお願い申し上げます。<br>なお、製造番号の確認方法は、下記のホームページをご覧ください。<br>http://bs-camera.jp/info/20191008<br><br>ビーエスカメラ　お客様サポート窓口", audioUrl:"", question:"56. このお知らせで最も伝えたいことは何か。", options:["「BS-ZG1」の電源ボタンに不具合が起きていないかどうか、確認してほしい。","すべての「BS-ZG1」を無料で修理するので、販売店に持ってきてほしい。","対象の製造番号の「BS-ZG1」を無料で修理するので、販売店に持ってきてほしい。","不具合が起きた「BS-ZG1」の製造番号をホームページに載せたので、確認してほしい。"], answer:2,
    translation:"Thông báo của hãng máy ảnh BS Camera về máy ảnh kỹ thuật số “BS-ZG1”: do phát hiện lỗi nút nguồn nên tạm ngừng bán từ 30/9; điều tra cho thấy lỗi chỉ xảy ra với sản phẩm có số sê-ri ZH29200～ZH29800. Khách có sản phẩm thuộc diện này, dù hiện chưa bị lỗi, cũng được sửa miễn phí nên hãy mang đến cửa hàng gần nhất.",
    explanation:"Lỗi chỉ xảy ra ở số máy ZH29200～ZH29800; khách có sản phẩm thuộc diện được sửa miễn phí và mang đến cửa hàng ⇒ đáp án 3 ✓. 1 (kiểm tra xem có lỗi không)・2 (sửa TẤT CẢ — sai)・4 (đăng số máy lên web để kiểm tra — chỉ là thông tin phụ, không phải ý chính)." },
  { id:"b10-5", passage:"（5）作者というものは、たいていの場合、自分の詩のいい読者ではありえません。作意（注）や創作過程が心につよく残っていて、作品を客観的に見ることを妨げるからです。だれだって、自分のことは自分がもっともよく知っていると思うでしょう。ですが、その反面、他人にはすぐわかるのに、本人にはいっこうにわからないような一面が人間にはあります。作者と詩の場合もこれと同じです。だから、作者がこの詩についてはこう言っているのだから、これが正しいというような考え方には、僕はあまり賛成できません。<br><br>（注）作意：作成した意図", audioUrl:"", question:"57. あまり賛成できませんとあるが、なぜか。", options:["詩は、読者自身が意味を考えることに意義があるから","詩の解釈は、正しいかどうかを考えても意味がないから","作者が自身の詩を他人よりわかっているとは限らないから","作者の意図や創作過程を知ることは、あまり重要ではないから"], answer:2,
    translation:"Tác giả (nhà thơ) phần lớn không thể là người đọc tốt thơ của chính mình, vì dụng ý và quá trình sáng tác còn đọng lại quá mạnh, cản trở việc nhìn tác phẩm một cách khách quan. Con người có mặt mà người khác thấy ngay nhưng bản thân lại không hề nhận ra — thơ cũng vậy. Nên tôi không tán thành cách nghĩ rằng 'vì tác giả nói thơ này thế nên điều đó đúng'.",
    explanation:"「その反面、他人にはすぐわかるのに、本人にはいっこうにわからないような一面が人間にはあります。作者と詩の場合もこれと同じです」⇒ tác giả không nhất thiết hiểu thơ mình hơn người khác ⇒ đáp án 3 ✓. 1 (ý nghĩa ở chỗ độc giả tự nghĩ)・2 (giải thích đúng sai vô nghĩa)・4 (biết ý đồ/ quá trình sáng tác không quan trọng) không khớp lý do trong văn." },
]},
{ tab:"読解", section:"問題11 内容理解・中文",
  instruction:"次の（1）から（3）の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b11-1", passage:"（1）豊かな時代に育った若い人たちは、子供時代から学生を卒業するまで、「情の世界」の物差し（注1）を使って世の中を見る時代が続く。情の世界の物差しとは「好き」「嫌い」「感じる」「感じない」という物差しで、「イヤだったらやめる」ということが許される時代でもある。<br>しかし社会に出ると、これはまったく許されない。社会や会社は「論理の世界」だからだ。「八時に始まる」というのであれば、一分遅れて来てもそれは許されない。なぜなら「論理の世界」では、その規則や約束をきちんと守っていかなければ、仕事が先に進まない。たとえば一台のクルマをつくるのに必要な部品は、数千あるいは数万個あるだろう。しかしたとえその一つでも納品の時間が守られなければ、クルマは完成しないのである。<br>論理が先、情が後。<br>その順番を間違えない人が、会社や組織においてスムーズに仕事を進めることのできる優れた人材といえるだろう。だから「情の世界」で過ごしてきた若い人たちは、自分たちがその世界を卒業して「論理の世界」に入ったのだということを自覚して（注2）ほしい。<br>さらには、ぜひ次のことも知っておいてほしい。「好き」「嫌い」「感じる」「感じない」という感性の物差しだけで生きてしまうとすれば、決して人間的な向上を図る（注3）ことはできない。一方で理性を働かせ（注4）、「正しい」か「正しくない」か、さらには「正しいことをしよう」「いいことをしよう」という努力をしていく過程の中で、自己向上が図られていくのである。<br><br>（注1）物差し：ここでは、評価の基準<br>（注2）自覚する：意識する<br>（注3）図る：ここでは、目指す<br>（注4）理性を働かせる：ここでは、感情に左右されることなく思考する", audioUrl:"", question:"58. まだ社会に出ていない若い人たちについて、筆者はどのように述べているか。", options:["物事を感性で判断する。","世の中のことを見ようとしない。","感情的に行動することは少ない。","「好き」「嫌い」の基準が明確だ。"], answer:0,
    translation:"Về những người trẻ chưa bước vào xã hội, tác giả nói gì? — Họ phán đoán mọi việc bằng cảm tính.",
    explanation:"Đoạn 1: từ thời thơ ấu đến khi tốt nghiệp, giới trẻ liên tục nhìn thế gian qua thước đo 「情の世界」 = 「好き」「嫌い」「感じる」「感じない」⇒ họ phán đoán sự việc bằng cảm tính ⇒ đáp án 1 ✓. 2 (không nhìn vào thế gian)・3 (ít hành động theo cảm xúc)・4 (tiêu chí 好き/嫌い rõ ràng) đều không được văn nêu." },
  { id:"b11-2", passage:"", audioUrl:"", question:"59. 筆者によると、人は社会に出たらどうしなければならないか。", options:["自分以外の人の感情を尊重する。","規則や約束を守ることを優先する。","優先するべきことを自分で考える。","感情を捨てて会社や組織のために働く。"], answer:1,
    translation:"Theo tác giả, khi bước vào xã hội con người phải làm gì? — Ưu tiên tuân thủ quy tắc và lời hứa.",
    explanation:"Đoạn 2: 「社会や会社は『論理の世界』」「その規則や約束をきちんと守っていかなければ、仕事が先に進まない」và 「論理が先、情が後」⇒ ưu tiên quy tắc, ước hẹn ⇒ đáp án 2 ✓. 1・3・4 không được văn nêu." },
  { id:"b11-3", passage:"", audioUrl:"", question:"60. 筆者の考えに合うのはどれか。", options:["人間的な向上を目指すには、正しいことだけをしていけばいい。","自身の感情を抑えられるようになれば、人間的に向上したといえる。","正しさを基準に行動しようとしていくことが、人間的な向上につながる。","「好き」「嫌い」「感じる」「感じない」という感性は、人間的な向上を妨げる。"], answer:2,
    translation:"Ý nào hợp với suy nghĩ của tác giả? — Việc cố gắng hành động dựa trên tiêu chuẩn 'đúng đắn' dẫn tới sự trưởng thành về nhân cách.",
    explanation:"Câu cuối: dùng lý trí, xét 「正しい」か「正しくない」か, rồi nỗ lực 「正しいことをしよう」「いいことをしよう」— chính trong quá trình đó self-trưởng thành được vun đắp ⇒ đáp án 3 ✓. 1 (chỉ làm việc đúng là đủ)・2 (chỉ cần kìm nén cảm xúc)・4 (cảm tính cản trở trưởng thành — cách nói tuyệt đối hóa) đều không đúng ý tác giả." },
  { id:"b11-4", passage:"（2）以下は、幼児の心の発達について述べた文章である。<br><br>2、3歳ごろになると、「自分でやりたい」という思いが強くなり、何に対しても「イヤ!」「〇〇ちゃんがやるの!（注1）」というように、養育者（注2）に対する反抗が顕著（注3）になる（第一反抗期）。それまでは養育者の意図に従って行動していたのに対して、自我が芽生えて（注4）自分のやりたいことが生じ、養育者の意図とは異なる自分の意思を養育者に表明する（注5）ことで起こる。この時期には、だめなことはだめと伝えたり、ひととかかわる時にはルールがあることを根気強く教えていく必要がある。そのことにより、幼児は自分の気持ちをコントロールする力を身につける。<br>このころの幼児は、他者の立場に立ってものごとを考えることが難しく、自分の考えと相手の考えが同じであるととらえている。このとらえ方を自己中心的思考とよぶ。例えば、自分が楽しいときには、相手も同じように楽しいと感じているととらえていたり、自分の見た夢のことを相手も知っていると思っている状態である。（中略）<br>目の前にない物やできごとを思い浮かべることを象徴的思考と言う。乳児（注6）期には、「目の前にないものは存在しない」という考え方をする。そのため、母親が乳児の目の前からいなくなると母親が存在しなくなったと思い、不安になって泣く。しかし、幼児期になり、象徴的思考ができるようになると、目の前に母親がいなくても、母親がこの世（注7）からいなくなったわけではないと考えられるようになるため不安を訴えて泣くことはなくなる。<br><br>（注1）〇〇ちゃん：ここでは、自分<br>（注2）養育者：ここでは、親など子供を育てる人<br>（注3）顕著になる：ここでは、多く見られるようになる<br>（注4）自我が芽生える：ここでは、自分の考えが生まれる<br>（注5）表明する：はっきり表す<br>（注6）乳児：1歳ごろまでの子供<br>（注7）この世：現実の世界", audioUrl:"", question:"61. 筆者によると、2、3歳の幼児が親などに反抗するようになるのはなぜか。", options:["相手とは異なる自分の意思を持ち、それを伝えようとするから","相手の意図はすべて受け入れたくないと思うから","自分のやりたいことがあるのに、それを伝えられないから","自分とは異なる相手の意図が理解できないから"], answer:0,
    translation:"Theo tác giả, vì sao trẻ 2–3 tuổi trở nên chống đối cha mẹ? — Vì trẻ có ý chí riêng khác với người lớn và muốn truyền đạt điều đó.",
    explanation:"Đoạn 1: 「自我が芽生えて自分のやりたいことが生じ、養育者の意図とは異なる自分の意思を養育者に表明することで起こる」⇒ trẻ nảy sinh cái tôi, có ý muốn riêng khác với ý định của người nuôi dưỡng và bộc lộ ý chí đó ⇒ đáp án 1 ✓. 3 sai vì văn nói trẻ '表明する' (bộc lộ được); 2・4 không được nêu." },
  { id:"b11-5", passage:"", audioUrl:"", question:"62. 自己中心的思考とはどのようなものか。", options:["相手が自分の気持ちに合わせるべきだと思う。","相手も自分と同じ考えだと思う。","自分といれば相手はいつも楽しいと感じると思う。","自分はあらゆるものごとを知っていると思う。"], answer:1,
    translation:"Tư duy lấy mình làm trung tâm là gì? — Nghĩ rằng đối phương cũng có suy nghĩ giống mình.",
    explanation:"「自分の考えと相手の考えが同じであるととらえている。このとらえ方を自己中心的思考とよぶ」⇒ trẻ cho rằng suy nghĩ của người khác giống hệt mình ⇒ đáp án 2 ✓. 1 (bắt người khác chiều theo mình)・3・4 không được nêu." },
  { id:"b11-6", passage:"", audioUrl:"", question:"63. 筆者によると、幼児が象徴的思考を身につけるとどうなるか。", options:["目の前に存在していなくても、存在していると分かる。","目の前にないものは、存在しないと考えるようになる。","母親以外の存在も理解できるようになる。","ものごとに不安を感じることがなくなる。"], answer:0,
    translation:"Theo tác giả, khi trẻ có được tư duy tượng trưng thì sẽ thế nào? — Biết rằng dù không ở trước mắt thì sự vật vẫn tồn tại.",
    explanation:"Đoạn cuối: khi có 象徴的思考, dù mẹ không ở trước mắt trẻ cũng hiểu 「母親がこの世からいなくなったわけではない」⇒ không còn khóc vì bất an ⇒ đáp án 1 ✓. 2 là cách nghĩ của thời 乳児期 (trước khi có tư duy tượng trưng); 3・4 không được nêu." },
  { id:"b11-7", passage:"（3）未熟な（注1）人たちを育てることは、強い組織を創りあげる鉄則（注2）である。短期的な成果ばかりに目が行く上司は、能力の高い特定の人間だけを重用し（注3）、能力が低い人間には目が行かない。出来る人間は仕事が速く確かだし、任せていれば安心で自分がラクなのである。<br>一方、能力の低い部下は、細かく指示を出さなければならず、仕事は遅いし失敗することも多い。何かあったときに責任を問われるのは、上司である自分だ。できればそうした「落ちこぼれ」は、早く別の部署に異動させて（注4）代わって優秀な社員を獲得したいだろう。<br>しかし、それでは強い組織は出来上がらない。なぜなら、よくできる社員はすでによくがんばっているので、いま以上の伸びしろ（注5）はそれほど大きくないからだ。<br>上司が重点的に気をかけなければいけないのは、少し遅れ気味の部下、外れ者の部下、苦労している部下である。そういう部下は、手間はかかるかもしれないが、少し手を差し伸べれば、2〜3割は容易に伸びる。そうすることで組織を構成するメンバー全体の力を伸ばし、組織の底上げ（注6）ができる。結果として、与えられた業務目標を、組織として達成することができるのである。これぞ上司の本懐（注7）である。<br>組織の中で大きく伸びていく人材の多くは、新入社員時代にどんな部署の誰が上司であったかということが大きく影響するといわれる。まだ仕事というものがよくわかっていないとき「会社というのは……」「仕事とはこうするのだ」と的確に教えてもらえたかどうかが、その人の仕事人生を大きく左右するということだ。<br><br>（注1）未熟な：能力や経験が不十分な<br>（注2）鉄則：ここでは、絶対に必要なこと<br>（注3）〜を重用する：〜に重要な役割を与える<br>（注4）別の部署に異動させる：別の部に移す<br>（注5）伸びしろ：伸びる可能性<br>（注6）底上げ：全体のレベルを高めること<br>（注7）本懐：一番の願い", audioUrl:"", question:"64. 「それ」とはどういうことか。", options:["能力の低い部下にも責任のある仕事を任せること","能力の低い部下には能力に合った仕事を与えること","能力の高い部下にも細かく指示を出すこと","能力が高い部下だけを使って成果を上げようとすること"], answer:3,
    translation:"“Điều đó” (それ) nghĩa là gì? — Chỉ dùng những cấp dưới giỏi để đạt thành tích.",
    explanation:"「それ」 chỉ nội dung phía trước: người trên chỉ chú trọng thành tích ngắn hạn thì chỉ trọng dụng số ít người giỏi, còn với người kém thì muốn sớm chuyển sang bộ phận khác để có được nhân viên ưu tú thay thế ⇒ đáp án 4 ✓. 1・2・3 không khớp với điều 「それ」 thay thế." },
  { id:"b11-8", passage:"", audioUrl:"", question:"65. 組織を強くしていくために、上司はどうしなければならないか。", options:["目標を高く設定し、メンバー全体で協力させる。","能力の低い部下を適切に指導し、組織全体の力を伸ばす。","部下がまだ仕事がよくわからないときでも、まずは仕事をやらせてみる。","仕事ができる部下にもそうでない部下にも、能力を伸ばすように指導する。"], answer:1,
    translation:"Để tổ chức trở nên mạnh, người trên phải làm gì? — Hướng dẫn thích hợp những cấp dưới kém năng lực, nâng cao sức mạnh của cả tổ chức.",
    explanation:"Đoạn 4: phải chú trọng những người hơi chậm, người lạc lõng, người đang vất vả; chỉ cần đưa tay ra giúp thì họ dễ tiến bộ 2〜3割, từ đó 「組織を構成するメンバー全体の力を伸ばし、組織の底上げができる」⇒ đáp án 2 ✓. 1・3・4 không được văn nêu là điều người trên phải làm." },
]},
{ tab:"読解", section:"問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction:"次のAとBは文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b12-1", passage:"A<br>会話が上手な人とはどんな人だろうか。話題や知識が豊富な人だろうか。確かにそういう人と話していると、知らなかった話や興味深い話が聞けて、話がうまいと思うことも多い。しかしそれは話すのが上手だということで、会話が上手だということではない。ただ一方的に自分の得意な分野やしたい話をしているだけという場合も多いのだ。<br>私が会話が上手だと思う人は、誰と話していても話を広げていくのが上手な人だ。相手の関心のありそうな話題について、まず自分が話を始めてきっかけを作る。そして相手が話し出したら、それを広げていくような質問をする。このように相手が話しやすいように、うまく会話の流れを作り出していける人が、会話が上手な人だと思う。<br><br>B<br>会話で大切なのは、まず相手の話をよく聞くことだ。まだ相手が話しているのに自分の話を始める人がいるが、これではうまく会話が続かない。<br>しかし、それ以上に私が気になるのは、聞いているだけで何も話さない人だ。質問をしても「そうですね」と言うだけで次が続かない。こういう相手では、楽しく会話しようとしても難しい。<br>会話はお互いに話すことで成立するものだから、自分から話をしようとする態度が必要ではないか。たとえ、この話題については自分の話はしたくないと思っても、世の中や他の人のことなど、関連のある話で話をふくらませていくことはできる。自ら参加し、ともに会話を進めていこうとする姿勢が大切だ。", audioUrl:"", question:"66. 会話をする際の問題点として、AとBが指摘している点は何か。", options:["Aは相手が興味を持っているかどうかを気にしないことだと述べ、Bは自分の聞きたい話しか聞かないことだと述べている。","Aは相手の話を聞こうとしないことだと述べ、Bは相手に質問されても返事をしないことだと述べている。","Aは自分の知識を自慢することだと述べ、Bは相手が話している途中で話を始めることだと述べている。","Aは自分の話ばかりすることだと述べ、Bは相手の話を聞いてばかりいることだと述べている。"], answer:3,
    translation:"Vấn đề khi trò chuyện mà A và B chỉ ra là gì? — A: chỉ nói về mình; B: chỉ nghe mà không nói.",
    explanation:"A: 「ただ一方的に自分の得意な分野やしたい話をしているだけという場合も多い」⇒ chỉ độc thoại điều mình muốn. B: 「それ以上に私が気になるのは、聞いているだけで何も話さない人だ」⇒ chỉ nghe, không chịu nói ⇒ đáp án 4 ✓. 1・2・3 không đúng nội dung mà A/B chỉ ra." },
  { id:"b12-2", passage:"", audioUrl:"", question:"67. 会話をうまく進めていくために、AとBが共通して必要だと述べていることは何か。", options:["相手に的確な質問をすること","相手の話を正確に理解しようとすること","相手と一緒に話を展開していこうとすること","相手と自分が共通して話せる話題を提供すること"], answer:2,
    translation:"Để cuộc trò chuyện diễn ra suôn sẻ, điều mà cả A và B đều cho là cần thiết là gì? — Cùng với đối phương triển khai câu chuyện.",
    explanation:"A: người giỏi trò chuyện 「相手が話し出したら、それを広げていくような質問をする」「うまく会話の流れを作り出していける人」. B: 「自ら参加し、ともに会話を進めていこうとする姿勢が大切」⇒ cả hai đều nhấn mạnh việc cùng nhau mở rộng/tiến triển cuộc trò chuyện ⇒ đáp án 3 ✓. 1・2・4 không phải điểm chung mà cả hai nêu." },
]},
{ tab:"読解", section:"問題13 主張理解・長文",
  instruction:"次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b13-1", passage:"人の能力は多様です。研究の仕事に適性（注1）をもっている人もいれば、動物の世話をしているときが何より充実しているという人もいる。そういう自分の関心や能力に見合った領域（注2）の仕事をすることは、たしかに人の幸福の大きな部分を占めています。<br>しかし、最初から自分に合った仕事に就けるとは限らないし、それがすぐに見つかるとも限らない。自分に合った仕事や好きな仕事を見つけるのは時間がかかることであり、だから、そうした仕事を欲している人はそれに出会うまでは多少の回り道を覚悟すべきだと思います。<br>（中略）<br>仕事や生き方というのはあせって決めても仕方がないし、決めようと思って決められるものでもありません。いま、それが見つからないのなら、多少遠回りしてもいいから、じっくり腰を据えて（注3）探してみるのがいいのではないでしょうか。<br>夢や個性についても同じです。<br>最近では、中学校や小学校のころから、将来の夢をもちなさい、個性的であれ（注4）といわれるそうです。人生のずいぶん早い時期から、将来の設計図を描け、たしかな自分をもてと迫られるわけです。<br>しかし、夢や個性というのは荷物じゃないのだから、「もて」といわれて、もてるものでもありません。夢や目標などは時期がくれば自然に抱くようになるものなのです。<br>個性も主張するから身につくものではありません。個性などということはちっとも考えず、自分の好きなこと、やりたいことをなりふりかまわず（注5）、必死で追いかけるうちに、おのずとにじみ出てくる（注6）のが個性なのです。<br>私が自分の娘から唯一、感謝されているのは、いつか彼女に対していった「夢なんかあえてもつ必要はない」という言葉です。娘は学校の先生から「夢をもちなさい」といわれて、「夢をもたなきゃ」と強迫観念（注7）を抱いていたが、父親のその言葉で気が楽になったといいます。<br>ゆっくり育てた果実は大きいといいますから、夢も仕事も、じっくり探して育てていけばいいのです。回り道や道草が栄養になるのは、自分自身の経験からもいえます。<br><br>（注1）適性：ある物事をするのに適した性質や能力<br>（注2）領域：分野<br>（注3）腰を据えて：ここでは、落ち着いて<br>（注4）個性的であれ：個性的になりなさい<br>（注5）なりふりかまわず：ここでは、他のことを気にせずに<br>（注6）おのずとにじみ出てくる：自然に表れ出る<br>（注7）強迫観念：ここでは、強い不安", audioUrl:"", question:"68. 仕事について、筆者はどのように述べているか。", options:["自分に合った仕事や好きな仕事は、すぐに見つからない場合がある。","自分に合った仕事や好きな仕事が見つかるかどうかは、能力次第だ。","自分に合った仕事や好きな仕事に就けなくても、幸福になれる。","自分に合った仕事や好きな仕事が、いい仕事だとは限らない。"], answer:0,
    translation:"Về công việc, tác giả nói gì? — Công việc phù hợp với mình hay công việc yêu thích có trường hợp không tìm thấy ngay.",
    explanation:"「最初から自分に合った仕事に就けるとは限らないし、それがすぐに見つかるとも限らない」⇒ không nhất thiết tìm được ngay ⇒ đáp án 1 ✓. 2 (tùy năng lực)・3 (không làm được việc phù hợp vẫn hạnh phúc)・4 (phù hợp chưa chắc là tốt) đều không được văn nêu." },
  { id:"b13-2", passage:"", audioUrl:"", question:"69. 筆者はなぜ「夢なんかあえてもつ必要はない」と言ったのか。", options:["夢を実現できるかどうか分からないと考えているから","夢は大人になると自然に変わるものだと考えているから","夢は大人になってからもつべきだと考えているから","夢は自然にもつようになるものだと考えているから"], answer:3,
    translation:"Vì sao tác giả nói “không cần cố mà có ước mơ”? — Vì tác giả cho rằng ước mơ là thứ tự nhiên mà có được.",
    explanation:"「夢や目標などは時期がくれば自然に抱くようになるものなのです」⇒ đến lúc thì ước mơ tự nhiên nảy sinh ⇒ đáp án 4 ✓. 1 (không biết có thực hiện được không)・2 (khi lớn tự nhiên thay đổi)・3 (nên có khi đã lớn) đều không được nêu làm lý do." },
  { id:"b13-3", passage:"", audioUrl:"", question:"70. この文章で筆者が最も言いたいことは何か。", options:["将来の可能性を広げるには、あまり大きな夢をもたないほうがいい。","自分に合ったやりたいことを探すには、遠回りをしてもいい。","若いうちは、自分の個性に合ったことをしたほうがいい。","多くの経験を積むことによって、将来夢が実現できる。"], answer:1,
    translation:"Điều tác giả muốn nói nhất trong bài là gì? — Để tìm việc mình muốn làm, phù hợp với mình thì đi vòng cũng không sao.",
    explanation:"「多少の回り道を覚悟すべき」「多少遠回りしてもいいから、じっくり腰を据えて探してみるのがいい」「回り道や道草が栄養になる」⇒ để tìm được điều phù hợp thì đường vòng là chấp nhận được ⇒ đáp án 2 ✓. 1・3・4 không phải ý chính tác giả muốn nói." },
]},
{ tab:"読解", section:"問題14 情報検索",
  instruction:"右のページは、ある文化祭の参加者募集の案内である。下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions:[
  { id:"b14-1", passage:"朝田市文化祭 参加者募集<br><br>11月2日（土）から11月4日（月）まで朝田市民文化会館で行われる「朝田市文化祭」に参加しませんか。<br><br>1．募集内容について<br>【作品展示】11月2日（土）～11月4日（月）10時～17時<br>・絵画：72cm×65cmまで<br>・書道：150cm×95cmまで<br>・写真：41cm×60cmまで<br>★作品は1人1点のみです。未発表作品に限ります。<br>【ダンス】11月2日（土）13時～17時<br>・5人以上の団体でのみ出演可　・発表時間は4分以内<br>【音楽】11月3日（日）13時～17時<br>・1人でも団体でも出演可　・発表時間は10分以内<br>応募資格：市内在住の方、市内に勤務先のある方、市内で文化活動を行っている方<br><br>2．申し込みについて<br>申込受付期間：2019年9月2日（月）～9月13日（金）<br>・指定の申込書にご記入の上、事務所にご持参くださるか、ファックスまたは郵送でお願いします。（申込書は下記のウェブページからダウンロードが可能です。）<br>・ダンス、音楽に団体でお申し込みの場合、申込書に出演者全員の氏名を記入し、ご提出ください。申込書は1団体につき1枚です。なお、舞台リハーサルをご希望の場合は、3.の②の表をご覧ください。<br><br>3．文化祭までの流れ<br>①説明会（参加者ご本人、または団体の代表の方は必ずご出席ください。）<br>・月日：作品展示10月4日（金）、ダンス10月5日（土）、音楽10月6日（日）<br>・時間：いずれも19時から<br>・場所：朝田市民文化会館3階研修室<br>②準備・片付け、リハーサル<br>【作品展示】作品は11月2日（土）7時～9時に運び入れ、11月4日（月）17時15分～19時に片付けてください。<br>【ダンス】舞台リハーサルは、11月1日（金）9時～17時に15分以内でお願いします。<br>【音楽】舞台リハーサルは、11月2日（土）9時～17時に15分以内でお願いします。<br><br>朝田市文化祭実行委員会事務所（朝田市民文化会館内）<br>〒320-2745　朝田市広山30-1　電話08-6400-5000　ファックス08-6400-5001<br>http://www.asada.lg.jp/bunkasai", audioUrl:"", question:"71. ポリーさんは、朝田市のダンス教室の仲間と文化祭でダンスの発表をしたいと考えている。申し込みにあたって、注意しなければならないこととして合っているのはどれか。", options:["10分以内の発表時間で申し込まなければならない。","事務所に直接行って申込書を提出しなければならない。","1枚の申込書に出演者全員の名前を書かなければならない。","事前の舞台リハーサルに出なければならない。"], answer:2,
    translation:"Chị Polly muốn cùng nhóm của lớp khiêu vũ thành phố Asada biểu diễn nhảy tại lễ hội văn hóa. Điều cần lưu ý khi đăng ký là gì? — Phải ghi tên tất cả người biểu diễn vào một tờ đơn đăng ký.",
    explanation:"Mục 2「ダンス、音楽に団体でお申し込みの場合、申込書に出演者全員の氏名を記入し、ご提出ください。申込書は1団体につき1枚です」⇒ đáp án 3 ✓. 1 sai vì ダンス là 「発表時間は4分以内」 (10分以内 là 音楽); 2 sai vì có thể nộp ファックス hoặc 郵送 (không bắt buộc trực tiếp); 4 sai vì 舞台リハーサル là 「ご希望の場合は」— không bắt buộc." },
  { id:"b14-2", passage:"", audioUrl:"", question:"72. ザーリンさんは文化祭に申し込みをし、写真作品を展示することになった。この後、文化祭が始まるまでに、何をしなければならないか。", options:["10月4日の説明会に行き、文化祭初日の前日の9時から17時の間に作品を運び入れる。","10月4日の説明会に行き、文化祭初日の7時から9時の間に作品を運び入れる。","10月4日から6日のどれかの説明会に行き、文化祭初日の前日の9時から17時の間に作品を運び入れる。","10月4日から6日のどれかの説明会に行き、文化祭初日の7時から9時の間に作品を運び入れる。"], answer:1,
    translation:"Anh Zaarin đã đăng ký và sẽ trưng bày tác phẩm ảnh. Sau đó, trước khi lễ hội bắt đầu phải làm gì? — Đến buổi giải thích ngày 4/10, và mang tác phẩm vào trong khoảng 7–9 giờ ngày đầu lễ hội.",
    explanation:"Về 作品展示: 説明会 là 10月4日（金）(không phải 4～6日 — đó là gồm cả ダンス/音楽) và 「作品は11月2日（土）7時～9時に運び入れ」— 11月2日 là ngày đầu (初日) ⇒ đáp án 2 ✓. 1・3 (khung 9時～17時 là giờ リハーサル, không phải 運び入れ)・4 sai." },
]},
/* ================= TAB 5: 聴解 ================= */
{ tab:"聴解", section:"問題1 課題理解",
  instruction:"問題1では、まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c1-1", passage:"【台本】アパートで女の人と管理人が話しています。女の人は壊れたパソコンをどうしますか。<br><br>女：すみません。管理人さん、壊れたパソコンは、粗大ごみの申し込みをして、アパートの指定の場所に出せば、収集してくれるんでしたっけ。薄いノートパソコンなんですけど。<br>男：パソコンはメーカーに回収してもらうか、パソコンを買ったお店に持っていくかしないと、粗大ごみとして出せないんですよ。<br>女：そうなんですか。何十年も前のものなので、どこで買ったか…。<br>男：でしたら、メーカーに連絡すれば、専用の伝票を送ってくれますから、それを梱包したパソコンに貼って、郵送すればいいんですよ。<br>女：意外と簡単な手続きなんですね。<br>男：大きい自治体だと、市役所とか公共施設に回収箱が設置されていて、そこに入れればパソコンも回収してくれるんですけど。この地域はないですよね。<br>女：そうですか。", audioUrl:"", question:"1番：女の人は壊れたパソコンをどうしますか。", options:["アパートの指定場所に出す","メーカーに送る","買った店に持っていく","市のかいしゅう箱に入れる"], answer:1,
    translation:"Người phụ nữ hỏi người quản lý chung cư về cách xử lý chiếc máy tính hỏng. Vì đã lâu không nhớ mua ở đâu, người quản lý khuyên liên hệ hãng để được gửi phiếu chuyên dụng, dán lên máy đã đóng gói rồi gửi bưu phẩm.",
    explanation:"Đáp án 2. 「メーカーに連絡すれば、専用の伝票を送ってくれますから、それを梱包したパソコンに貼って、郵送すればいい」⇒ gửi cho hãng ⇒ ②. ① máy tính không vứt được như rác cỡ lớn; ③ không nhớ mua ở đâu; ④ khu vực này không có thùng thu hồi." },
  { id:"c1-2", passage:"【台本】会社で部長と事務の女の人が話しています。女の人はこの後、何をしなければなりませんか。<br><br>男：ちょっといいかな、北山食品からのプラスチック容器の注文のことなんだけど、この請求書を作成したのって。<br>女：ああ、部長、作ったのは私です。何か間違いがありましたか。<br>男：いや、これ、中村君に頼まれて作成したんだよね。営業担当は中村君だから。<br>女：はい。<br>男：注文の数がこれまでよりずいぶん減ってるから、その理由が知りたいんだけど、中村君外出中みたいで、何か聞いてない?<br>女：いいえ。何も。<br>男：そうか。悪いけど、わたし今から会議だから、中村君戻ったらこの件について、わたしのところに説明にくるよう伝えといてもらえるかな。5時には会議終わって戻るから。特に報告受けてなかったものだから、気になっちゃってね。<br>女：わかりました。", audioUrl:"", question:"2番：女の人はこの後、何をしなければなりませんか。", options:["中村さんに伝言をする","せいきゅう書の間違いを直す","会議に出席する","注文数について部長に報告する"], answer:0,
    translation:"Trưởng phòng hỏi về hóa đơn đặt hàng; vì số lượng đặt giảm nhiều mà Nakamura đang ra ngoài, ông nhờ cô chuyển lời để Nakamura về thì lên giải thích cho ông (5 giờ ông họp xong sẽ về).",
    explanation:"Đáp án 1. 「中村君戻ったらこの件について、わたしのところに説明にくるよう伝えといてもらえるかな」⇒ truyền lời cho Nakamura ⇒ ①. ② hóa đơn không sai; ③ người đi họp là trưởng phòng; ④ người phải báo cáo là Nakamura." },
  { id:"c1-3", passage:"【台本】日本語のクラスで先生が留学生に話しています。留学生は主に商店街の何についてインタビューのプランを立てますか。<br><br>女：来週の授業では、さくら商店街に行って、グループごとに二軒ずつ古くから続く商店を回って、お店の人にインタビューをします。ええ、さくら商店街は最近では魚のコロッケなどの人気商品で知られ、新しいことに次々とチャレンジしていますが、県内で最も長く続く商店街なんです。そこで商店街全体がこれまでどのように困難を乗り越え、変化、発展してきたのか、話を伺います。今日はこのテーマに基づいてグループごとにインタビューのプランを立てましょう。今から、各グループに店のリストを配ります。", audioUrl:"", question:"3番：留学生は主に商店街の何についてインタビューのプランを立てますか。", options:["最近人気のある商品","これからのチャレンジ","店が困っていること","はってんのれきし"], answer:3,
    translation:"Giáo viên cho biết tuần sau cả lớp sẽ phỏng vấn các cửa hàng lâu đời ở phố mua sắm Sakura và yêu cầu lập kế hoạch phỏng vấn về việc cả phố đã vượt qua khó khăn, thay đổi, phát triển như thế nào.",
    explanation:"Đáp án 4. 「商店街全体がこれまでどのように困難を乗り越え、変化、発展してきたのか、話を伺います。今日はこのテーマに基づいてインタビューのプランを立てましょう」⇒ lịch sử phát triển ⇒ ④ はってんのれきし. ①②③ chỉ là thông tin phụ/không phải chủ đề." },
  { id:"c1-4", passage:"【台本】大学の事務所で学生と事務所の人が話しています。学生はこの後、まず何をしますか。<br><br>男：すみません。先週インフルエンザで経済学の学期末試験を休んでしまったんですが、病気の場合は、もう一度試験が受けられると聞きまして。<br>女：経済学は西山先生ですね。まずは先生に試験が受けられるか確認して、受けられるということなら、こちらの申請書を書いて、医師の診断書と一緒に出してください。申請、今日までだから、急いで西山先生に確認してくださいね。<br>男：あっ、先生には許可をいただきました。あのう、診断書が必要って知らなくて、病院でもらって来なかったんですけど。<br>女：病気の場合は診断書がないと。<br>男：今日は病院が休みで。明日書いてもらって必ず持ってきますので。<br>女：うーん、仕方ないですね。じゃあ、今日は申請書だけで、試験の詳細は来週掲示板に出ますから、自分で確認するようにしてくださいね。<br>男：はい、ありがとうございます。", audioUrl:"", question:"4番：学生はこの後、まず何をしますか。", options:["西山先生に相談する","しんせい書をていしゅつする","病院にしんだん書をもらいに行く","けいじ板をかくにんする"], answer:1,
    translation:"Sinh viên đã được giáo sư Nishiyama cho phép thi lại nhưng chưa có giấy chẩn đoán. Nhân viên nói hôm nay chỉ cần nộp đơn đăng ký, còn chi tiết kỳ thi sẽ được dán trên bảng tin vào tuần sau và sinh viên tự kiểm tra.",
    explanation:"Đáp án 2. 「先生には許可をいただきました」「じゃあ、今日は申請書だけで」⇒ việc đầu tiên phải làm là nộp đơn (申請書) ⇒ ②. ① đã xin phép xong; ③ để ngày mai (hôm nay bệnh viện nghỉ); ④ là việc tuần sau, tự xem bảng tin." },
  { id:"c1-5", passage:"【台本】男の人と女の人が話しています。女の人は、パーティーの日に何をしますか。<br>（ア＝受付をして会費を受け取る　イ＝会場の飾り付け　ウ＝会場の音楽（曲を選んで当日かける）　エ＝ビデオ撮影（動画の編集もする））<br><br>男：山下さん、来月、松田君の結婚パーティーをレストランでやることになったんだけど、手伝ってくれない。<br>女：もちろん。なんでも言って。<br>男：ありがとう。じゃあ、受付をお願いできないかな。会費制でやるから、会費の受け取りをしてほしいんだけど。<br>女：わかった。<br>男：ねえ、もう一つ、会場の音楽担当か、ビデオ撮影の担当も頼めない?音楽係は事前に松田君と相談して曲を選んで、当日かけてほしいんだ。ダンスの曲とか。撮影係は動画の編集までやってもらいたいんだけど。<br>女：わたし、動画作るの、得意。<br>男：本当。じゃあ、決まりだね。だけど、受付お願いするとなると、時間ギリギリに来場する人がいたら、撮影開始が遅れちゃうか。カメラを最初だけほかの人に任せるとしても、なんか慌ただしいしな。やっぱり、山下さんには受付やめて、会場の飾り付けのグループに入ってもらおうかな。当日2時間前に来られる?<br>女：うん、大丈夫。<br>男：じゃあ、係をふたつお願いすることになるけど、よろしくね。", audioUrl:"", question:"5番：女の人は、パーティーの日に何をしますか。", options:["アとウ","アとエ","イとウ","イとエ"], answer:3,
    translation:"Anh nhờ chị Yamashita giúp tiệc cưới: chị nhận vai quay phim (giỏi làm video), nhưng vì nếu làm lễ tân sẽ khó quay ngay từ đầu nên anh đổi để chị vào nhóm trang trí hội trường, và nhờ chị đảm nhiệm hai vai.",
    explanation:"Đáp án 4. 「山下さんには受付やめて、会場の飾り付けのグループに入ってもらおうかな」+ 「動画作るの、得意」⇒ vai của chị là 会場の飾り付け(イ) và ビデオ撮影(エ) ⇒ イとエ = ④. ア (受付) đã bỏ, ウ (音楽) không chọn." },
]},
{ tab:"聴解", section:"問題2 ポイント理解",
  instruction:"問題2では、まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c2-1", passage:"【台本】大学で、女の学生と男の学生が卒業論文について話しています。男の学生は女の学生にどんな方法を勧めましたか。<br><br>女：卒業論文もう始めなきゃ間に合わないのに、なかなか取り掛かる気になれなくて。<br>男：僕は先月から始めたけど、やっぱり始めるまでに時間かかったよ。とりあえず資料を集めるとか、簡単なことからやってみれば?そうするうちに、だんだん集中してくと思うよ。<br>女：そっか。まずはやるべきことがイメージできるよう、長期的な計画を立ててみようかなと思ってたけど。私の場合、それで満足して終わっちゃいそうだから、そのほうがいいかも。<br>男：去年卒業した先輩からは、いい論文が書けたっていう成功をイメージするといいよってアドバイスを受けたけど、完成まであまりに遠いから、イメージしづらくてね。<br>女：確かにね。なんか相談したらやる気出てきた。少し進んだら報告するから。また相談に乗ってね。", audioUrl:"", question:"1番：男の学生は女の学生にどんな方法を勧めましたか。", options:["簡単な作業から始める","長期的な計画を立てる","せいこうをイメージする","進み具合を友人と報告し合う"], answer:0,
    translation:"Nam sinh khuyên nữ sinh nên bắt đầu từ việc đơn giản như thu thập tài liệu, rồi dần dần sẽ tập trung hơn — thay vì lập kế hoạch dài hạn hay hình dung thành công (những cách anh thấy khó).",
    explanation:"Đáp án 1. 「とりあえず資料を集めるとか、簡単なことからやってみれば?そうするうちに、だんだん集中してくと思う」⇒ bắt đầu từ việc đơn giản ⇒ ①. ② nữ tự nghĩ rồi bỏ; ③ là lời khuyên của senpai, anh nói khó hình dung; ④ không được nêu." },
  { id:"c2-2", passage:"【台本】女の人と男の人が就職試験の結果について話しています。男の人はどうして合格した会社に入らないと言っていますか。<br><br>女：先週、就職試験の最終面接だったでしょう。結果、どうだった?<br>男：採用通知もらったよ。でも、辞退することにしたんだ。<br>女：せっかく合格したのに?<br>男：うん、自分の専門が生かせそうな会社だったんだけど、入社後三年以内に少なくとも五年は東京じゃなくて、地方の支店に転勤してもらうことになるだろうって、面接で言われて、家庭の事情もあって、東京勤務以外は考えられないんだ。<br>女：そっか。<br>男：オフィスを見学したとき、活気があって、雰囲気も自分に合いそうだったから、すごく悩んだんだけど。提示された給料も自分の予想を超えてたしね。結局悩んだ末、辞退することにしたんだ。専門が生かせる仕事はほかにもあると思うから、頑張って探してみるよ。", audioUrl:"", question:"2番：男の人はどうして合格した会社に入らないと言っていますか。", options:["専門を生かした仕事ができないから","地方に勤める可能性があるから","会社のふんいきが合わなそうだから","給料が自分の予想より低かったから"], answer:1,
    translation:"Người đàn ông đỗ nhưng từ chối vì công ty yêu cầu trong 3 năm đầu phải luân chuyển ít nhất 5 năm ở chi nhánh địa phương, mà hoàn cảnh gia đình chỉ có thể làm việc ở Tokyo.",
    explanation:"Đáp án 2. 「地方の支店に転勤してもらうことになるだろうって…東京勤務以外は考えられない」⇒ có khả năng phải làm ở địa phương ⇒ ②. ① ngược lại (công ty phát huy được chuyên môn); ③ không khí hợp; ④ lương cao hơn dự tính." },
  { id:"c2-3", passage:"【台本】会社で男の人と女の人が防災について話しています。女の人は自分のうちでは今後何をする必要があると言っていますか。<br><br>男：この間、家族で防災センターに見学に行ったんですけど、もしもの時、うちは何も準備ができてないなって思って。災害への備え、何かしてますか。<br>女：うちは本棚とか、冷蔵庫とか家具が倒れないように固定したり、それから、家族で近くの避難所まで安全な行き方を確認しながら行ってみたり。<br>男：防災意識高いですね。<br>女：まあ、そうですね。非常時にどうやって連絡取り合うかも家族で話して決めてありますし。携帯電話がつながりにくくなることがあるって聞いて。<br>男：うちなんて、食料と飲料を常備してるぐらいですよ。<br>女：それも大事ですよ。うちもやってはいるんですけど、家族で三日分ぐらいしかなくて。一週間分は置いとかなきゃって思ってるとこです。<br>男：そうですか。うちももう少し家族で意識高めないとなあ。", audioUrl:"", question:"3番：女の人は自分のうちでは今後何をする必要があると言っていますか。", options:["家具がたおれないように固定する","ひなん所までの行き方をかくにんする","非常時のれんらく方法を決める","食べ物と飲み物を十分にたくわえる"], answer:3,
    translation:"Người phụ nữ nói nhà cô đã cố định đồ đạc, xác nhận đường đến nơi tránh nạn, bàn cách liên lạc khi khẩn cấp; việc cần làm tiếp theo là dự trữ thức ăn và nước uống cho cả tuần (hiện chỉ đủ ba ngày).",
    explanation:"Đáp án 4. 「一週間分は置いとかなきゃって思ってるとこです」⇒ cần chuẩn bị thức ăn và đồ uống đủ dùng ⇒ ④. ①②③ đều đã làm rồi." },
  { id:"c2-4", passage:"【台本】女の学生と男の学生が話しています。女の学生は交渉について、授業でどんなことを習ったと言っていますか。<br><br>女：今日、経済学の授業で、交渉について習ったんだ。<br>男：交渉って、自分の希望通りにいくように、相手と話をするあの交渉?買い物で値引きしてもらう時なんかの?<br>女：そう。特に値引き交渉なんかはどうやったらこっちの思い通りになるかって、相手を負かそうとするでしょう。でもね、ちゃんとお互いの利益になるよう歩み寄って、交渉を通して、より高い価値を生み出すっていうのが賢い交渉なんだって。<br>男：へえ。<br>女：お互いが得をするようなやり方が望ましいってこと。もちろん互いに譲れない交渉となると、厳しいやり取りが求められると思うけどね。", audioUrl:"", question:"4番：女の学生は交渉について、授業でどんなことを習ったと言っていますか。", options:["どうこうしょうすれば、物が安く買えるか","こうしょうを通して、何が学べるか","理想的なこうしょうとは、どういうものか","どうやって、相手にこうしょうをもとめるか"], answer:2,
    translation:"Nữ sinh kể bài học về đàm phán: thay vì cố đánh bại đối phương, đàm phán thông minh là nhượng bộ để hai bên cùng có lợi và tạo ra giá trị cao hơn — tức thế nào là đàm phán lý tưởng.",
    explanation:"Đáp án 3. 「お互いの利益になるよう歩み寄って、交渉を通して、より高い価値を生み出すっていうのが賢い交渉なんだって」⇒ nói về kiểu đàm phán lý tưởng ⇒ ③. ① (đàm phán để mua rẻ) là cách hiểu thông thường, bị phủ định; ②④ không được nêu." },
  { id:"c2-5", passage:"【台本】セミナーで専門家が話しています。専門家はサービスについて、どのようにしていく必要があると言っていますか。<br><br>女：これまで製造業においては、物を作り出す技術、あるいは生産性を高めるための様々な研究が進められてきました。一方、サービスについてはどうでしょう。今だ経験や勘に頼るところが大きく、例えば、サービスの質と価格の関係をデータから分析したり、効果を測定し評価するなど、科学的なアプローチによる研究が十分に行われてきたとは言えません。サービス業は国内で労働者の6割が従事し、大きな利益を生んでいる重要な産業なのですから、その必要性を強く感じるわけです。", audioUrl:"", question:"5番：専門家はサービスについて、どのようにしていく必要があると言っていますか。", options:["より経験をじゅうしする","科学的に研究する","りえきを追いもとめる","国内の主要産業にする"], answer:1,
    translation:"Chuyên gia nói ngành dịch vụ hiện còn dựa nhiều vào kinh nghiệm và trực giác, cần được nghiên cứu bằng cách tiếp cận khoa học (phân tích dữ liệu, đo lường, đánh giá hiệu quả).",
    explanation:"Đáp án 2. 「科学的なアプローチによる研究が十分に行われてきたとは言えません…その必要性を強く感じる」⇒ cần nghiên cứu một cách khoa học ⇒ ②. ① ngược lại (đang dựa vào kinh nghiệm); ③④ không được nêu." },
]},
{ tab:"聴解", section:"問題3 概要理解",
  instruction:"問題3では、問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。（せんたくし được in trong phần 台本 của đề gốc, không in trên tờ đề thi.）",
  questions:[
  { id:"c3-1", passage:"【台本】テレビでレポーターが男の人にインタビューしています。<br><br>女：私は今アニメのイベント会場に来ています。こちらのイベントを毎年開催している山本さんにお話を伺います。<br>男：このイベントでは新作アニメの紹介やアニメグッズの販売、ゲーム、コンサートなどを行っています。年に一度のこの機会にぜひ、新たなお気に入りのアニメを見つけたり、ファン同士の交流を深めたりして、皆さんに楽しんでもらいたいと思います。日本のアニメは海外でも人気で、アニメファンはもちろんですが、友達にこのイベントに連れて来られて興味を持つようになったという外国の方も多いんです。<br>女：そうですか。<br>男：アニメを通して、日本のことをもっと知って、好きになってもらいたいので、このイベントがそういうきっかけになるようにと思ってます。", audioUrl:"", question:"1番：男の人は何について話していますか。", options:["このイベントを開催する目的","このイベントで一番人気のコーナー","このイベントを外国で行う計画","このイベントを始めたきっかけ"], answer:0,
    translation:"Người đàn ông tổ chức sự kiện anime hằng năm nói về mong muốn để mọi người tìm thấy anime yêu thích, tăng giao lưu giữa các fan và qua anime hiểu thêm, yêu thêm Nhật Bản — tức mục đích tổ chức sự kiện.",
    explanation:"Đáp án 1. 「皆さんに楽しんでもらいたい」「アニメを通して、日本のことをもっと知って、好きになってもらいたいので、このイベントがそういうきっかけになるようにと思ってます」⇒ mục đích tổ chức ⇒ ①. ② nội dung hoạt động chỉ được liệt kê; ③④ không được nêu." },
  { id:"c3-2", passage:"【台本】ラジオで女の人が話しています。<br><br>ある高齢者介護施設では、わざと施設内に階段や段差を設置しているそうです。えっと思われるかもしれませんが、あえて不便にすることで、体力や体の機能の低下を防ごうとするものなんです。パソコンの普及で漢字が書けなくなったなんてよく聞きますが、昔は何でも手書きで手間はかかるけど、おかげで漢字を忘れずに済んだわけですよね。そういえば、先日うちの掃除機が壊れて、家中箒で掃いたんですけど、日ごろの運動不足が解消された気が…これも同じことかなあ。", audioUrl:"", question:"2番：女の人が言いたいことは何ですか。", options:["介護には苦労が多い","不便さにも利点がある","生活はもっと便利になる","お年寄りの知恵は素晴らしい"], answer:1,
    translation:"Người phụ nữ nói về việc cơ sở chăm sóc người cao tuổi cố tình tạo cầu thang, bậc để ngăn suy giảm thể lực; cũng như việc viết tay giúp không quên chữ Hán, hay quét nhà bằng chổi giúp vận động — tức sự bất tiện cũng có mặt tốt.",
    explanation:"Đáp án 2. 「あえて不便にすることで、体力や体の機能の低下を防ごうとする」「これも同じことかなあ」⇒ sự bất tiện cũng có lợi ích ⇒ ②. ①③④ không phải điều người nói muốn truyền đạt." },
  { id:"c3-3", passage:"【台本】テレビで動物園の職員が話しています。<br><br>動物園というと、一般的には、遠足やデートなどで訪れるレクリエーションの場というイメージをお持ちかもしれませんが、動物の生態や自然環境について学ぶ機会を提供する場でもあるんです。また、近年、自然環境の悪化などにより、野生動物の生活範囲が狭くなってきていて、住む場所を失ったり、数が著しく減少してしまったりしている動物たちがいます。動物園には、そうした動物を保護し、守るという一面もあるんです。", audioUrl:"", question:"3番：職員は何について話していますか。", options:["動物園の抱える問題点","動物園の設備の改善","動物園が減っている現状","動物園が果たす役割"], answer:3,
    translation:"Nhân viên sở thú nói rằng sở thú không chỉ là nơi giải trí mà còn là nơi cung cấp cơ hội học về sinh thái động vật, môi trường tự nhiên, và còn bảo vệ, che chở động vật hoang dã — tức vai trò của sở thú.",
    explanation:"Đáp án 4. 「動物の生態や自然環境について学ぶ機会を提供する場でもある」「そうした動物を保護し、守るという一面もある」⇒ các vai trò của sở thú ⇒ ④. ①②③ không phải nội dung chính được nói." },
  { id:"c3-4", passage:"【台本】会社で上司と女の人が残業時間を制限することについて話しています。<br><br>男：中野さん、今社内で残業を週10時間以内に制限するっていう話が出てるんだけど、中野さんはチームリーダーとしてどう思う?<br>女：そうですね。確かに会社全体で無駄な残業をなくすのは必要なことですが、なんでも時間で区切ってしまうというのは。うちは商品開発部という性質上、アイディアを膨らませたり、企画を練ったり、退社時間を気にせず、集中したいっていう時がありますから。<br>男：現場としては、そうなんだね。", audioUrl:"", question:"4番：女の人が言いたいことは何ですか。", options:["会社が残業時間に制限をかけるべきだ","残業が多いのは能率が悪いからだ","残業しても結局疲れて集中できない","仕事内容によっては残業が必要とされる"], answer:3,
    translation:"Nữ trưởng nhóm nói việc cắt giảm giờ làm thêm vô ích là cần thiết, nhưng không thể áp đặt giới hạn thời gian cho mọi việc, vì ở bộ phận phát triển sản phẩm có lúc cần tập trung làm việc không để ý đến giờ về.",
    explanation:"Đáp án 4. 「なんでも時間で区切ってしまうというのは…退社時間を気にせず、集中したいっていう時がありますから」⇒ tùy nội dung công việc mà cần làm thêm ⇒ ④. ① cô phản đối việc áp giới hạn cứng; ② ③ không được nêu." },
  { id:"c3-5", passage:"【台本】セミナーで林業の専門家が話しています。<br><br>日本は昔から、木の文化と言われていますが、近年では、木造住宅の建築に、外国の木材が多く使われています。価格が安く、種類も豊富な輸入木材に、国産が押されているわけです。しかし、雨が多い日本で育った木は、梅雨の時期や高温で湿度の高い夏でも腐らず、冬の乾燥でも変形しないなど、日本の気候に非常によく合っていて、長く使うことができるんです。百年前の木造の家だって、手入れすればまだ住めるほどです。もう一度、見直してもらいたいですね。", audioUrl:"", question:"5番：専門家は何について話していますか。", options:["日本人が木を好む理由","木造の家の現象","国産の木材の強み","日本の森林の変化"], answer:2,
    translation:"Chuyên gia lâm nghiệp nói dù gỗ ngoại nhập giá rẻ, đa dạng đang lấn át gỗ trong nước, nhưng gỗ trồng ở Nhật rất hợp khí hậu Nhật (không mục, không biến dạng) và dùng được lâu — tức ưu điểm của gỗ nội địa.",
    explanation:"Đáp án 3. 「雨が多い日本で育った木は…日本の気候に非常によく合っていて、長く使うことができる」⇒ ưu thế của gỗ trong nước ⇒ ③. ①②④ không phải nội dung chính." },
]},
{ tab:"聴解", section:"問題4 即時応答",
  instruction:"問題4では、問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。",
  questions:[
  { id:"c4-1", passage:"【台本】1番：男：さっき、先輩に何言われたか知らないけど、気にすることないよ。", audioUrl:"", question:"1番：返事として最もよいものを選びなさい。", options:["それは教えられない。","心配してくれて、ありがとう。","言われたこと、気にしてないの?"], answer:1,
    translation:"“Chuyện vừa rồi bị senpai nói gì tôi không biết, nhưng đừng bận tâm.” → “Cảm ơn vì đã lo cho tôi.”",
    explanation:"Đáp án 2. Người kia an ủi 「気にすることないよ」⇒ đáp lại bằng lời cảm ơn vì đã quan tâm ⇒ ②. ①『không thể dạy được』・③ hỏi ngược lại không phù hợp." },
  { id:"c4-2", passage:"【台本】2番：女：このラーメン、結構辛いね。見た目に反して。", audioUrl:"", question:"2番：返事として最もよいものを選びなさい。", options:["そうは見えないのにね。","ほんとう辛そうだもんね。","見た目からしてすごいよね。"], answer:0,
    translation:"“Món ramen này khá cay nhỉ, trái với vẻ ngoài.” → “Trông không giống thế nhỉ.”",
    explanation:"Đáp án 1. 「見た目に反して」⇒ đồng tình rằng nhìn bề ngoài không thấy cay ⇒ ①. ② nói 'trông có vẻ cay' mâu thuẫn; ③ nói 'nhìn vẻ ngoài đã thấy ghê' cũng ngược." },
  { id:"c4-3", passage:"【台本】3番：女：社長がお呼びですので、至急お越しいただけますか。", audioUrl:"", question:"3番：返事として最もよいものを選びなさい。", options:["じゃ、すぐ社長を呼んできます。","えっ?なんだろう。すぐ行きます。","すぐに電話するようにします。"], answer:1,
    translation:"“Giám đốc gọi, anh đến ngay được không?” → “Ơ? Chuyện gì nhỉ. Tôi đến ngay đây.”",
    explanation:"Đáp án 2. Được yêu cầu đến ngay ⇒ đáp lại tự nhiên là thắc mắc nhẹ rồi nói sẽ đến ngay ⇒ ②. ① gọi giám đốc đến (hiểu sai quan hệ trên-dưới); ③ gọi điện (không phù hợp vì phải đến)." },
  { id:"c4-4", passage:"【台本】4番：女：あっ、お久しぶりです。こんなところでお会いするとは。", audioUrl:"", question:"4番：返事として最もよいものを選びなさい。", options:["ほんとう偶然ですね。","会いに来てくれたんですね。","それなら、ほかのところにしましょう。"], answer:0,
    translation:"“Ồ, lâu quá không gặp. Không ngờ lại gặp anh ở đây.” → “Đúng là trùng hợp thật nhỉ.”",
    explanation:"Đáp án 1. 「こんなところでお会いするとは」⇒ bày tỏ sự trùng hợp ⇒ ①. ② hiểu sai (không phải đến để gặp); ③ không liên quan." },
  { id:"c4-5", passage:"【台本】5番：男：道、渋滞してますね。新幹線の時間、間に合えばいいですけど。", audioUrl:"", question:"5番：返事として最もよいものを選びなさい。", options:["間に合ったんだから、いいですよ。","新幹線、行っちゃったんですか。","ぎりぎりかもしれませんね。"], answer:2,
    translation:"“Đường tắc nhỉ. Ước gì kịp giờ tàu Shinkansen.” → “Có thể chỉ vừa kịp thôi nhỉ.”",
    explanation:"Đáp án 3. Lo lắng về việc kịp hay không ⇒ đáp lại 'có thể chỉ sát giờ' là tự nhiên ⇒ ③. ① nói đã kịp (mâu thuẫn); ② hỏi tàu chạy mất rồi à (chưa chắc)." },
  { id:"c4-6", passage:"【台本】6番：男：ねえ、田中君が、大学やめるなんて、ほんとううそみたいだよね。", audioUrl:"", question:"6番：返事として最もよいものを選びなさい。", options:["わたしも驚いた。","よかった。やめないんだね。","田中君がうそついたの。"], answer:0,
    translation:"“Này, chuyện Tanaka bỏ đại học khó tin thật đấy nhỉ.” → “Tôi cũng bất ngờ.”",
    explanation:"Đáp án 1. 「うそみたいだよね」⇒ đồng cảm bất ngờ ⇒ ①. ② hiểu sai thành 'không nghỉ nữa'; ③ hiểu sai 'nói dối'." },
  { id:"c4-7", passage:"【台本】7番：男：ゼミの松田君、留学に備えて、毎日語学学校通ってるんだってよ。", audioUrl:"", question:"7番：返事として最もよいものを選びなさい。", options:["留学のあともずっと?すごいね。","ちゃんと留学の準備してて、えらいね。","留学中、毎日勉強してるんだね。"], answer:1,
    translation:"“Nghe nói Matsuda lớp seminar ngày nào cũng đi trường ngoại ngữ để chuẩn bị du học.” → “Chuẩn bị du học chu đáo nhỉ, giỏi thật.”",
    explanation:"Đáp án 2. 「留学に備えて」= để chuẩn bị du học ⇒ ② khen chuẩn bị chu đáo. ① hiểu sai thành 'sau khi du học'; ③ hiểu sai thành 'trong lúc du học'." },
  { id:"c4-8", passage:"【台本】8番：女：プレゼンの内容、これでいいか。このあと、課長にも見てもらわないとね。", audioUrl:"", question:"8番：返事として最もよいものを選びなさい。", options:["じゃ、わたしが課長に確認しておきます。","どうして課長に見てもらえないですか。","よかった。課長もこれでいいんですね。"], answer:0,
    translation:"“Nội dung thuyết trình thế này ổn chưa nhỉ. Sau đó phải để trưởng phòng xem nữa.” → “Vậy tôi sẽ xác nhận với trưởng phòng trước.”",
    explanation:"Đáp án 1. Trước yêu cầu cần cho trưởng phòng xem ⇒ nhận làm việc đó ⇒ ①. ② hỏi 'vì sao không cho trưởng phòng xem' không phù hợp; ③ hiểu sai là trưởng phòng đã đồng ý." },
  { id:"c4-9", passage:"【台本】9番：男：昨日、転職した元同僚に会ったんだけど、なんか生き生きしてたよ。", audioUrl:"", question:"9番：返事として最もよいものを選びなさい。", options:["ああ、また会社に戻ってくるってこと?","何で迷ってたの?","充実してるってことじゃない。"], answer:2,
    translation:"“Hôm qua gặp đồng nghiệp cũ đã chuyển việc, trông anh ấy có vẻ rất sung sức.” → “Chắc là đang thấy thoả mãn đấy mà.”",
    explanation:"Đáp án 3. 「生き生きしてた」= tràn đầy sức sống ⇒ suy ra 'đang thấy cuộc sống/th công việc thỏa mãn' ⇒ ③. ① hiểu sai thành quay lại công ty; ② không hợp ngữ cảnh." },
  { id:"c4-10", passage:"【台本】10番：男：最近、社長が何でも新しいことやりたがるから、困るよね。", audioUrl:"", question:"10番：返事として最もよいものを選びなさい。", options:["えっ、だから、社長困ってるの?","次から次へじゃ、大変だよね。","もっとチャレンジしてほしいのにね。"], answer:1,
    translation:"“Dạo này giám đốc thích làm việc mới gì cũng muốn, mệt thật nhỉ.” → “Hết cái này đến cái khác thì vất vả thật nhỉ.”",
    explanation:"Đáp án 2. Đồng cảm với nỗi vất vả vì liên tục có việc mới ⇒ ②. ① hiểu sai thành giám đốc đang gặp khó; ③ nói muốn giám đốc thử thách nhiều hơn (ngược ý)." },
  { id:"c4-11", passage:"【台本】11番：女：味もボリュームも、ステーキはこの店に限るね。", audioUrl:"", question:"11番：返事として最もよいものを選びなさい。", options:["それじゃ、ほかの店にしようか。","ああ、ステーキは限定メニューなんだね。","やっぱりここのステーキじゃないとね。"], answer:2,
    translation:"“Về vị lẫn độ đầy đặn thì bít tết chỉ có quán này là nhất nhỉ.” → “Đúng vậy, không phải bít tết ở đây thì không được nhỉ.”",
    explanation:"Đáp án 3. 「〜に限る」= chỉ có… là nhất ⇒ đồng tình bằng 「やっぱりここのステーキじゃないとね」⇒ ③. ① ngược ý; ② hiểu sai 「限る」thành 'menu giới hạn'." },
]},
{ tab:"聴解", section:"問題5 統合理解",
  instruction:"問題5では、長めの話を聞きます。この問題には練習はありません。メモをとってもかまいません。",
  questions:[
  { id:"c5-1", passage:"【台本】1番：男の留学生と女の学生が話しています。<br><br>男：ねえ、松本さん、松本さんって、観光ガイドのアルバイトをしてるよね。<br>女：うん。<br>男：来週、家族が日本に来るんだけど、何か、日本らしい体験ができるところない?両親の希望は、記念のものが手元に残って、日中は観光したいから、夕方4時以降がいいって。8歳の弟も一緒だから、子どもが飽きないのがいいんだけど。<br>女：それなら、陶芸教室は?茶碗とか、お皿とか作るの。陶器は焼くのに2、3週間かかるけど、後で国に送ってくれるよ。それから、布を染める教室もお勧め。スカーフを染めるんだけど、日本の伝統的な色を使うから、日本らしいお土産になるし、その日に持ち帰れるよ。<br>男：弟は工作が得意だから、茶碗とか作るの、好きそうだけど、布はどうかな。前に国でそういうのをやったとき、退屈してた記憶が…<br>女：そっか。どっちも4時半開始だけど、陶器を作る教室は、郊外の桜町だから、行くまでに時間かかるんだよね。<br>男：桜町に4時半か。間に合わないだろうな。<br>女：それと、観光センターに行けば、日本料理と、それから茶道の教室も体験できるよ。<br>男：弟、日本料理、大好きだよ。<br>女：だけど、料理は今昼間しかやってないんだ。お寿司とか作れて楽しいし、箸に名前を入れてプレゼントしてくれるから、すごく人気なんだけど。茶道のほうは、夜7時まで、1時間ごとに好きな時間で予約できるよ。お土産に和菓子もらえるけど、食べたら残らないね。四つの教室のどれかにするなら、私が予約するよ。<br>男：ありがとう。昼は無理だし、手元に何か残るっていう希望は聞いてあげなきゃ。弟が好みそうなほうだと、時間が心配だけど、まあ、その日だけ少し早く観光を切り上げてもらおう。", audioUrl:"", question:"1番：男の留学生はどの体験を選びましたか。", options:["陶器を作る","布を染める","日本料理を作る","茶道をする"], answer:0,
    translation:"Du học sinh nam muốn tìm trải nghiệm kiểu Nhật cho gia đình: kỷ niệm để lại được, sau 4 giờ chiều, em trai 8 tuổi không chán. Cuối cùng chọn làm gốm (em trai thích đồ thủ công), dù phải lo thời gian.",
    explanation:"Đáp án 1. Điều kiện: quà lưu niệm giữ lại được + sau 4 giờ + em trai không chán. 布染め: 弟 sẽ chán (nhớ lại lần trước đã buồn chán). 日本料理: chỉ làm ban ngày. 茶道: お土産の和菓子 ăn là hết, không giữ lại được. 陶芸: quà giữ lại được + 弟 thích làm đồ thủ công ⇒ chọn 陶器を作る ⇒ ①." },
  { id:"c5-2", passage:"【台本】2番：食品会社で、部下2人と課長が話しています。<br><br>男：課長、リンさん、すみません。ちょっといいでしょうか。今日3時から1時間ほど、課長とリンさんと私とで、北海道食品店の打ち合わせをすることになっていますが。<br>課長：ええ、中山さん、どうかしました?<br>男：あの、あした予定していた青木商事への納品が、急遽先方の都合で、今日になってしまいまして。それで、午後一番で青木商事に行かなければならないので、ちょっと3時までに戻るのは厳しいかと。遅くとも、3時半には戻れると思うんですが。<br>課長：そう、じゃ、打ち合わせ、4時からにしましょうか。<br>女：あっ、すみません。4時半からちょっと別件がありまして、15分前には出ないといけないんです。打ち合わせ、明日以降では、遅いでしょうか。<br>課長：それが、わたしが明日から急な出張で、一週間ほど留守にするんですよ。<br>女：それじゃ、今日中にしないと、1週間近く企画が止まってしまいますね。中山さん、納品の時間って、早められないんですか。<br>男：日程が1日繰り上がったので、これ以上早めると、準備が間に合いません。それに、先方から納品が遅くならないように言われてますので、後ろにずらすことも…<br>課長：じゃ、元の3時にして、中山さんは社に戻り次第、加わるってことでどう?<br>女：はい。中山さんがいない間、私の方から、現時点での作業状況とか、中山さんの担当の分もまとめて、課長に報告しておきます。<br>男：助かります。<br>課長：じゃ、そういうことでよろしく。", audioUrl:"", question:"2番：三人での打ち合わせの日時はどうなりましたか。", options:["予定通りの日時で行われる","今日時間を変えて行われる","明日の同じ時間に延期される","一週間後の同じ時間に延期される"], answer:0,
    translation:"Cuộc họp ba người vốn định 3 giờ hôm nay; không thể đổi sang 4 giờ (chị có việc khác từ 4 rưỡi) hay để mai (trưởng phòng đi công tác một tuần), nên cuối cùng giữ nguyên 3 giờ như dự định, Nakayama về công ty xong sẽ vào họp.",
    explanation:"Đáp án 1. 「じゃ、元の3時にして、中山さんは社に戻り次第、加わるってことでどう?」⇒ giữ nguyên giờ cũ (3 giờ) ⇒ ①. ② bị bác vì chị bận từ 4 rưỡi; ③ trưởng phòng đi công tác; ④ không được nêu." },
  { id:"c5-3", passage:"【台本】3番：ラジオを聞いたあと、男の学生と女の留学生が話しています。<br><br>ラジオ：毎年各地で開催されるちょっと変わったマラソン大会を四つご紹介します。お米の産地、北町の大会では、給水ポイントで、水だけでなく、おいしいおにぎりが味わえるそうです。ゴールしたときには、お腹いっぱいでしょうね。東町の大会はカレーです。こちらは食べながら走るのではなく、玉ねぎ、人参など、それぞれの畑を回って材料を収穫しながら、ゴールを目指すというものです。材料は持ち帰れるそうですよ。南町では、カメラをもって、海岸沿いの美しいコースを撮影しながら走ります。後で撮った写真のコンテストもあるそうです。最後は西町です。山道を走り、ゴールは山頂のお寺、500もの階段を登りきったところにあります。これは苦しそうですね。いずれの大会も、ただいま出場者募集中とのことです。<br>男：ねえ、リンダさん、国に帰る前にどれか出てみたら?いい思い出になると思うよ。<br>女：うん、楽しそう。<br>男：リンダさんは、カメラが趣味だから、海岸沿いを走るのがいいんじゃない?走るほうはわからないけど、コンテスト優勝できるかもよ。<br>女：カメラ持って走るなんて、落としたらいやだあ。わたし、足腰に自信があるから、階段を駆け上がるのにする。<br>男：おっ、すごいね。じゃ、ぼくは、野菜を収穫するやつに出てみよう。大会のあとでごちそうするよ。腕に自信があるんだ。<br>女：じゃ、その時はわたし、お米炊いて待ってるね。", audioUrl:"", question:"3番 質問1：女の留学生はどこの大会に参加したいと言っていますか。", options:["北町","東町","南町","西町"], answer:3,
    translation:"Nghe giới thiệu bốn giải marathon lạ: Bắc (cơm nắm), Đông (thu hoạch nguyên liệu cà ri), Nam (chạy ven biển chụp ảnh), Tây (leo 500 bậc lên chùa trên đỉnh núi). Nữ du học sinh nói tự tin về chân, chọn leo bậc thang.",
    explanation:"Đáp án 4. 「わたし、足腰に自信があるから、階段を駆け上がるのにする」⇒ 階段の大会 = 西町 (山頂のお寺に500の階段) ⇒ ④ 西町." },
  { id:"c5-4", passage:"", audioUrl:"", question:"3番 質問2：男の学生はどこの大会に参加したいと言っていますか。", options:["北町","東町","南町","西町"], answer:1,
    translation:"Nam sinh nói muốn tham gia giải thu hoạch rau củ.",
    explanation:"Đáp án 2. 「じゃ、ぼくは、野菜を収穫するやつに出てみよう」⇒ giải thu hoạch nguyên liệu (玉ねぎ、人参など) = 東町 ⇒ ② 東町." },
]},
]});
