/* =========================================================================
   data_2023_12.js — JLPT N2 2023年12月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2023_12", label:"12/2023", title:"JLPT N2 — 2023年12月 (12/2023)", file:"data_2023_12.js" },
data: [

{ tab: "文字・語彙", section: "問題1 漢字読み",
  instruction: "＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d1-1", passage:"", audioUrl:"", question:"1. 昨日から<u>腕</u>が痛くて困っている。", options:["こし","うで","かた","ひざ"], answer:1,
      translation:"Từ hôm qua cánh tay tôi đau, thật khó chịu.",
      explanation:"腕 = うで: cánh tay. 腰 (eo), 肩 (vai), 膝 (đầu gối) sai."},
    { id:"d1-2", passage:"", audioUrl:"", question:"2. 青木さんは<u>善良</u>な人です。", options:["せんりょう","ぜんりゅう","ぜんりょう","せんりゅう"], answer:2,
      translation:"Anh Aoki là người lương thiện.",
      explanation:"善良 = ぜんりょう: lương thiện. Các âm còn lại không tồn tại."},
    { id:"d1-3", passage:"", audioUrl:"", question:"3. 丸山さんは意外に<u>幼い</u>ところがある。", options:["おさない","するどい","かしこい","しつこい"], answer:0,
      translation:"Anh Maruyama có chỗ trẻ con một cách bất ngờ.",
      explanation:"幼い = おさない: trẻ con, non nớt. 鋭い/賢い/しつこい sai."},
    { id:"d1-4", passage:"", audioUrl:"", question:"4. 古いデータを<u>削除</u>した。", options:["そくよ","さくよ","そくじょ","さくじょ"], answer:3,
      translation:"Tôi đã xóa dữ liệu cũ.",
      explanation:"削除 = さくじょ: xóa bỏ. Các âm còn lại sai."},
    { id:"d1-5", passage:"", audioUrl:"", question:"5. 私たちは働く機会の<u>平等</u>を求めています。", options:["へいど","びょうどう","びょうど","へいどう"], answer:1,
      translation:"Chúng tôi yêu cầu sự bình đẳng về cơ hội lao động.",
      explanation:"平等 = びょうどう: bình đẳng. Các âm còn lại sai."},
  ]
},
{ tab: "文字・語彙", section: "問題2 表記",
  instruction: "＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d2-1", passage:"", audioUrl:"", question:"6. お金の<u>かんり</u>は、きちんとしてください。", options:["管利","官理","管理","官利"], answer:2,
      translation:"Hãy quản lý tiền bạc cho cẩn thận.",
      explanation:"かんり = 管理: quản lý. 管利/官理/官利 sai."},
    { id:"d2-2", passage:"", audioUrl:"", question:"7. 今日から2週間の<u>けんしゅう</u>を行います。", options:["演習","研習","研修","演修"], answer:2,
      translation:"Từ hôm nay chúng tôi tiến hành đào tạo 2 tuần.",
      explanation:"けんしゅう = 研修: đào tạo, tu nghiệp. 演習/研習/演修 sai."},
    { id:"d2-3", passage:"", audioUrl:"", question:"8. 社会は<u>たえず</u>変化している。", options:["完えず","絶えず","停えず","滞えず"], answer:1,
      translation:"Xã hội không ngừng biến đổi.",
      explanation:"たえず = 絶えず: không ngừng, liên tục. Các chữ còn lại sai."},
    { id:"d2-4", passage:"", audioUrl:"", question:"9. 選挙で誰に<u>とうひょう</u>するかまだ決めていない。", options:["投票","当票","投標","当標"], answer:0,
      translation:"Vẫn chưa quyết định bỏ phiếu cho ai trong cuộc bầu cử.",
      explanation:"とうひょう = 投票: bỏ phiếu. 当票/投標/当標 sai."},
    { id:"d2-5", passage:"", audioUrl:"", question:"10. 牛島さんは何かを<u>かかえて</u>部屋に入ってきた。", options:["押えて","捕えて","据えて","抱えて"], answer:3,
      translation:"Anh Ushijima bước vào phòng ôm theo một thứ gì đó.",
      explanation:"かかえる = 抱える: ôm. 押える/捕える/据える sai."},
  ]
},
{ tab: "文字・語彙", section: "問題3 語形成",
  instruction: "（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d3-1", passage:"", audioUrl:"", question:"11. 彼は兄に対抗（ ）を持っているようだ。", options:["心","欲","願","熱"], answer:0,
      translation:"Có vẻ anh ấy có lòng hiếu thắng với anh trai.",
      explanation:"対抗心 (たいこうしん): lòng hiếu thắng. 欲/願/熱 không tạo từ."},
    { id:"d3-2", passage:"", audioUrl:"", question:"12. 引っ越しのための（ ）手続きをしなければならない。", options:["総","複","多","諸"], answer:3,
      translation:"Phải làm các thủ tục (nhiều loại) cho việc chuyển nhà.",
      explanation:"諸手続き: các thủ tục. 諸 = các, nhiều thứ. 総/複/多 không dùng."},
    { id:"d3-3", passage:"", audioUrl:"", question:"13. 買い物をしている二人（ ）にインタビューをしました。", options:["出かけ","連れ","会い","集まり"], answer:1,
      translation:"Chúng tôi đã phỏng vấn một cặp đôi đang đi mua sắm.",
      explanation:"二人連れ (ふたりづれ): hai người đi cùng nhau. Các từ còn lại sai."},
  ]
},
{ tab: "文字・語彙", section: "問題4 文脈規定",
  instruction: "（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d4-1", passage:"", audioUrl:"", question:"14. このアニメは、登場人物がとてもかわいいと、若者の間で（ ）になっている。", options:["課題","題名","題材","話題"], answer:3,
      translation:"Bộ anime này trở thành đề tài bàn tán trong giới trẻ vì nhân vật rất dễ thương.",
      explanation:"話題 (わだい): đề tài bàn tán. 課題/題名/題材 sai."},
    { id:"d4-2", passage:"", audioUrl:"", question:"15. あのとき、友達に謝らなかったことをずっと（ ）している。", options:["同情","後悔","我慢","恐縮"], answer:1,
      translation:"Tôi cứ mãi hối hận vì lúc đó đã không xin lỗi bạn.",
      explanation:"後悔する: hối hận. 同情/我慢/恐縮 sai."},
    { id:"d4-3", passage:"", audioUrl:"", question:"16. 楽器の音量を確認するために、コンサートの前日に会場で（ ）をした。", options:["チャージ","アポイントメント","オリエンテーション","リハーサル"], answer:3,
      translation:"Để kiểm tra âm lượng nhạc cụ, ngày trước buổi hòa nhạc chúng tôi đã tập dượt tại hội trường.",
      explanation:"リハーサル: buổi tập dượt trước. Các từ còn lại sai."},
    { id:"d4-4", passage:"", audioUrl:"", question:"17. この魚は、いつでもこの辺りの海にいるわけではなく、（ ）の時期にしかいない。", options:["特定","指定","固定","限定"], answer:0,
      translation:"Loài cá này chỉ xuất hiện vào thời kỳ nhất định.",
      explanation:"特定: nhất định, riêng biệt. 指定/固定/限定 không hợp nghĩa."},
    { id:"d4-5", passage:"", audioUrl:"", question:"18. この季節は乾燥していて、肌が（ ）になる。", options:["どろどろ","ふさふさ","かさかさ","べたべた"], answer:2,
      translation:"Mùa này khô hanh nên da trở nên khô ráp.",
      explanation:"かさかさ: khô ráp, nứt nẻ. どろどろ/ふさふさ/べたべた sai."},
    { id:"d4-6", passage:"", audioUrl:"", question:"19. 先生の発音をよく聞いて、同じになるように発音を（ ）みましょう。", options:["まねて","かなえて","映して","保って"], answer:0,
      translation:"Hãy nghe kỹ phát âm của thầy và bắt chước để phát âm giống vậy.",
      explanation:"まねる (真似る): bắt chước. かなえる/映す/保つ sai."},
    { id:"d4-7", passage:"", audioUrl:"", question:"20. 金子さんとは初めて会ったが、お互いサッカーが大好きだと分かって、話が（ ）。", options:["飛び出した","行き過ぎた","盛り上がった","駆け抜けた"], answer:2,
      translation:"Câu chuyện trở nên sôi nổi vì biết cả hai đều rất thích bóng đá.",
      explanation:"話が盛り上がる: câu chuyện sôi nổi. Các từ còn lại sai."},
  ]
},
{ tab: "文字・語彙", section: "問題5 言い換え類義",
  instruction: "＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d5-1", passage:"", audioUrl:"", question:"21. これについては、<u>各自</u>が責任を持つことにします。", options:["私","代表者","一人一人","あなた"], answer:2,
      translation:"Về việc này, mỗi người sẽ tự chịu trách nhiệm.",
      explanation:"各自 = 一人一人: mỗi người, từng người. 私/代表者/あなた sai."},
    { id:"d5-2", passage:"", audioUrl:"", question:"22. 明日はレポートを<u>仕上げる</u>つもりです。", options:["書く","完成させる","出す","整理する"], answer:1,
      translation:"Mai tôi định hoàn thành bài báo cáo.",
      explanation:"仕上げる = 完成させる: hoàn thiện. 書く/出す/整理する sai."},
    { id:"d5-3", passage:"", audioUrl:"", question:"23. それは<u>深刻な</u>問題だ。", options:["単純な","身近な","微妙な","重大な"], answer:3,
      translation:"Đó là vấn đề nghiêm trọng.",
      explanation:"深刻な = 重大な: nghiêm trọng. 単純/身近/微妙 sai."},
    { id:"d5-4", passage:"", audioUrl:"", question:"24. 今日は<u>同僚</u>と食事に行く予定です。", options:["同じ会社の人","同じアパートの人","同じ出身地の人","同じクラスの人"], answer:0,
      translation:"Hôm nay tôi dự định đi ăn với đồng nghiệp.",
      explanation:"同僚 = 同じ会社の人: người cùng công ty. Các lựa chọn còn lại sai."},
    { id:"d5-5", passage:"", audioUrl:"", question:"25. 前田さんはさっきから<u>うつむいて</u>いる。", options:["上を向いて","横を向いて","下を向いて","後ろを向いて"], answer:2,
      translation:"Anh Maeda từ nãy đến giờ cứ cúi gằm mặt xuống.",
      explanation:"うつむく = 下を向く: cúi đầu xuống. Các lựa chọn còn lại sai hướng."},
  ]
},
{ tab: "用法", section: "問題6 用法",
  instruction: "次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d6-1", passage:"", audioUrl:"", question:"26. 廃止",
      options:["両親は20年以上続けてきた店を廃止することにした。","点検のため、午前中はエレベーターの使用を廃止します。","雨が降ってきたので、今日のイベントは廃止します。","時代に合わない古い制度は廃止したほうがいい。"], answer:3,
      translation:"Những chế độ cũ không hợp thời thì nên bãi bỏ.",
      explanation:"廃止 = bãi bỏ (hệ thống, chế độ, tuyến đường). Câu 1 nên là 閉める, câu 2,3 nên là 中止. Câu 4 đúng vì 制度 'bãi bỏ'."},
    { id:"d6-2", passage:"", audioUrl:"", question:"27. 腫れる",
      options:["森さんのポケットは、物が多くて腫れている。","今日はたくさん食べたので、おなかが腫れている。","サッカーの試合でけがをして、足が腫れてしまった。","オーブンでクッキーを焼いたら、だんだん腫れてきた。"], answer:2,
      translation:"Bị thương trong trận bóng đá nên chân tôi bị sưng.",
      explanation:"腫れる = sưng (cơ thể bị thương/viêm). ポケット/おなか/クッキー không dùng 腫れる."},
    { id:"d6-3", passage:"", audioUrl:"", question:"28. 上達",
      options:["毎日練習しているので、ピアノがかなり上達した。","いい病院で治療してもらえたようで、祖父の体調は上達した。","同じ作家が好きなことが分かって、大野さんとの仲が上達した。","小川さんが詳しく説明してくれたので、理解が上達した。"], answer:0,
      translation:"Nhờ luyện tập mỗi ngày nên piano của tôi đã tiến bộ khá nhiều.",
      explanation:"上達 = tiến bộ (kỹ năng, tài năng). 体調/仲/理解 không dùng 上達."},
    { id:"d6-4", passage:"", audioUrl:"", question:"29. 暮れ",
      options:["この物語の暮れは、意外な内容だった。","旅行の暮れに、みんなで記念に写真を撮った。","授業の暮れに、先生が今日の宿題を出した。","今年の暮れは、実家で両親と過ごしたい。"], answer:3,
      translation:"Cuối năm nay tôi muốn về quê sống cùng bố mẹ.",
      explanation:"暮れ = cuối năm (年の暮れ). Không dùng cho 結末/終わり của chuyện, chuyến đi, giờ học."},
    { id:"d6-5", passage:"", audioUrl:"", question:"30. 残高",
      options:["私たちが会議室を利用できる残高は、あと10分です。","私の銀行口座の残高は、1,000円しかありません。","この町の残高は、ついに1万人を下回りました。","山の頂上までの残高は、100メートルくらいです。"], answer:1,
      translation:"Số dư tài khoản ngân hàng của tôi chỉ còn 1.000 yên.",
      explanation:"残高 = số dư (tài khoản, tiền còn lại). 残り時間/人口/距離 không gọi là 残高."},
  ]
},
{ tab: "文法", section: "問題7 文の文法1",
  instruction: "次の文の（ ）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d7-1", passage:"", audioUrl:"", question:"31. 私の3人の兄はみんな料理が苦手で、一番上の兄（ ）、卵もうまく割れない。", options:["にとって","にしては","に比べて","に至っては"], answer:3,
      translation:"Ba anh trai tôi đều không giỏi nấu ăn; ngay cả anh cả cũng không đập trứng giỏi.",
      explanation:"～に至っては: ngay cả đến (mức độ đặc biệt nhất trong loạt). にとって/にしては/に比べて không phù hợp."},
    { id:"d7-2", passage:"", audioUrl:"", question:"32. 来週の説明会に参加するしない（ ）、この書類は必ず読んでおいてください。", options:["とはいえ","としても","に限らず","にかかわらず"], answer:3,
      translation:"Dù có tham dự buổi giải thích tuần sau hay không, xin hãy đọc trước tài liệu này.",
      explanation:"～にかかわらず: bất kể, dù... hay không. とはいえ/としても/に限らず không hợp cấu trúc."},
    { id:"d7-3", passage:"", audioUrl:"", question:"33. 駒前に新しいラーメン屋がオープンしていた。（ ）できたのだろう。", options:["いまにも","まさか","いつのまに","そのうち"], answer:2,
      translation:"Một quán ramen mới đã mở ở Komae. Không biết đã mở từ lúc nào.",
      explanation:"いつのまに: từ lúc nào không hay. いまにも/まさか/そのうち sai."},
    { id:"d7-4", passage:"", audioUrl:"", question:"34. この植物は、寒さに強い（ ）、暑さや湿気に弱い。", options:["反面","点で","ものを","からといって"], answer:0,
      translation:"Loài thực vật này chịu lạnh giỏi, nhưng ngược lại yếu với nóng ẩm.",
      explanation:"～反面: mặt khác, ngược lại (nêu mặt đối lập của cùng một sự vật). 点で/ものを/からといって không hợp."},
    { id:"d7-5", passage:"", audioUrl:"", question:"35. A「今度北町に行くんだけど、おいしいレストラン、知らない？」B「すし屋（ ）、1軒知ってるよ。」", options:["でいいし","でよければ","がいいと","がよくても"], answer:1,
      translation:"A: \"Cậu biết nhà hàng ngon nào ở Kita-machi không?\" B: \"Nếu sushi (cũng được) thì tôi biết một quán.\"",
      explanation:"すし屋でよければ: nếu sushi cũng được thì... ～でよければ: nếu (điều kiện) thì. Các từ còn lại không hợp."},
    { id:"d7-6", passage:"", audioUrl:"", question:"36. 懐中電灯を（ ）、電池が切れていて、つかなかった。", options:["使おうとしたら","使うようにしたら","使おうとするなら","使うようにするなら"], answer:0,
      translation:"Định dùng đèn pin thì pin đã hết, không sáng được.",
      explanation:"～ようとしたら: khi tôi định làm thì... (phát hiện điều bất ngờ). Các từ còn lại là điều kiện giả định, sai."},
    { id:"d7-7", passage:"", audioUrl:"", question:"37. （マラソン大会のホームページで）周辺住民の方の迷惑になりますので、指定の駐車場以外には（ ）、お願いいたします。", options:["駐車なさらないよう","駐車していただくよう","駐車なさらないため","駐車していただくため"], answer:0,
      translation:"Vì sẽ gây phiền hà cho người dân khu vực, kính mong quý vị vui lòng không đỗ xe ngoài bãi được chỉ định.",
      explanation:"～なさらないようお願いいたします: xin đừng làm... (なさる = kính ngữ của する). していただくよう dùng cho yêu cầu làm (không hợp); ため sai."},
    { id:"d7-8", passage:"", audioUrl:"", question:"38. 林選手がオリンピックに出場できるかどうかは、今度の大会の結果（ ）。", options:["のみだ","次第だ","にほかならない","でも不思議ではない"], answer:1,
      translation:"Việc vận động viên Hayashi có thể dự Olympic hay không còn tùy thuộc vào kết quả giải tới.",
      explanation:"～次第だ: còn tùy thuộc vào. のみだ/にほかならない/でも不思議ではない sai."},
    { id:"d7-9", passage:"", audioUrl:"", question:"39. 最近、パソコンを使っていると、突然画面が真っ暗（ ）。故障しているのかもしれない。", options:["にすることがある","にしたところだ","になることがある","になったところだ"], answer:2,
      translation:"Gần đây, dùng máy tính thì có lúc màn hình đột nhiên tối đen. Có lẽ máy bị hỏng.",
      explanation:"～になることがある: có lúc trở thành (hiện tượng lặp lại). にすることがある (chủ động làm cho), ところだ (vừa mới) không hợp."},
    { id:"d7-10", passage:"", audioUrl:"", question:"40. あのときの友人の言葉は、夢をあきらめそうになっていた私にもう一度頑張ろうと（ ）。", options:["思ってくれた","思ってほしかった","思わせてくれた","思わせてほしかった"], answer:2,
      translation:"Lời nói của người bạn lúc đó đã khiến tôi — kẻ sắp từ bỏ giấc mơ — nghĩ phải cố gắng lần nữa.",
      explanation:"～させてくれた: khiến tôi làm (ai đó làm cho tôi). 思ってくれた/思ってほしかった/思わせてほしかった sai."},
    { id:"d7-11", passage:"", audioUrl:"", question:"41. （会社で）社長「あ、さっきの会議室にペンを忘れたみたいだ。」秘書「では、私が取って（ ）。」", options:["おります","まいります","くださいます","いらっしゃいます"], answer:1,
      translation:"Giám đốc: \"Hình như tôi để quên bút ở phòng họp.\" Thư ký: \"Vậy để tôi đi lấy.\"",
      explanation:"～てまいります: dạng kính ngữ khiêm nhường (tôi sẽ đi làm). おります/くださいます/いらっしゃいます sai."},
    { id:"d7-12", passage:"", audioUrl:"", question:"42. （電話で）店員「お電話ありがとうございます。さくら美容院です。」田中「あ、今日の7時に予約している田中ですが、ちょっと仕事が長引いていて……。できたら8時に変更して（ ）。」", options:["もらったらいかがですか","もらうのではないでしょうか","もらわなければなりませんか","もらえるとありがたいんですが"], answer:3,
      translation:"Nhân viên: \"Cảm ơn đã gọi, đây là tiệm làm tóc Sakura.\" Tanaka: \"Tôi là Tanaka đã đặt lịch 7h tối nay, công việc hơi kéo dài... Nếu có thể thì tôi rất mong được đổi sang 8h.\"",
      explanation:"～もらえるとありがたいんですが: nếu nhờ được thì rất cảm kích (yêu cầu lịch sự). いかがですか/のではないでしょうか/なければなりませんか không hợp ngữ cảnh xin xỏ."},
  ]
},
{ tab: "文法", section: "問題8 文の文法2 (sắp xếp - ★)",
  instruction: "次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d8-1", passage:"", audioUrl:"", question:"43. この本の内容をきちんと ＿＿＿ ★ ＿＿＿ ＿＿＿ ＿＿＿ 多いだろう。［1 それなりの / 2 理解するには / 3 難しいと感じる人も / 4 知識が求められるので］",
      options:["それなりの","理解するには","難しいと感じる人も","知識が求められるので"], answer:0,
      translation:"Vì để hiểu đúng nội dung cuốn sách này cần kiến thức tương xứng, nên có lẽ nhiều người sẽ thấy khó.",
      explanation:"Thứ tự đúng: 理解するには（2）それなりの（1）知識が求められるので（4）難しいと感じる人も（3）→ \"きちんと理解するには、それなりの知識が求められるので、難しいと感じる人も多いだろう\"。★ vị trí 2 = それなりの → đáp án 1."},
    { id:"d8-2", passage:"", audioUrl:"", question:"44. 石油は、自動車や航空機などの ＿＿＿ ★ ＿＿＿ ＿＿＿ 原料としても利用されている。［1 使われる / 2 だけでなく / 3 プラスチック製品を作る / 4 燃料として］",
      options:["使われる","だけでなく","プラスチック製品を作る","燃料として"], answer:0,
      translation:"Dầu mỏ không chỉ được dùng làm nhiên liệu cho ô tô, máy bay v.v. mà còn được dùng làm nguyên liệu sản xuất sản phẩm nhựa.",
      explanation:"Thứ tự đúng: 燃料として（4）使われる（1）だけでなく（2）プラスチック製品を作る（3）→ ★ vị trí 2 = 使われる → đáp án 1. ～だけでなく: không chỉ ... mà còn."},
    { id:"d8-3", passage:"", audioUrl:"", question:"45. 東鉄道竹山線内にある二つの信号機が故障しており、大事故が ＿＿＿ ＿＿＿ ★ ＿＿＿ 明らかになった。［1 起きかねない / 2 続いていたことが / 3 状態が / 4 危険な］",
      options:["起きかねない","続いていたことが","状態が","危険な"], answer:2,
      translation:"Hai tín hiệu trên tuyến Takeyama của Đông Tetsudō bị hỏng, và đã rõ là tình trạng nguy hiểm có thể gây tai nạn lớn đã tiếp diễn.",
      explanation:"Thứ tự đúng: 起きかねない（1）危険な（4）状態が（3）続いていたことが（2）→ ★ vị trí 3 = 状態が → đáp án 3. ～かねない: có thể xảy ra (điều xấu)."},
    { id:"d8-4", passage:"", audioUrl:"", question:"46. （インタビューで）「店長になって最初の1年間は大変でした。店長になった ＿＿＿ ＿＿＿ ★ ＿＿＿ ＿＿＿ と悩むこともありました。」［1 といっても / 2 ばかりで / 3 わからないこと / 4 自分でいいのか］",
      options:["といっても","ばかりで","わからないこと","自分でいいのか"], answer:1,
      translation:"\"Năm đầu làm quản lý rất vất vả. Dù nói đã thành quản lý, nhưng toàn những điều không biết, có lúc tôi trăn trở không biết mình làm thế có ổn không.\"",
      explanation:"Thứ tự đúng: といっても（1）わからないこと（3）ばかりで（2）自分でいいのか（4）→ ★ vị trí 3 = ばかりで → đáp án 2. ～ばかりで: toàn là..."},
    { id:"d8-5", passage:"", audioUrl:"", question:"47. 家を買うことについて ＿＿＿ ＿＿＿ ★ ＿＿＿ ＿＿＿ 簡単に引っ越せないのが嫌だと言っている。［1 夫は / 2 買ってしまうと / 3 否定的な / 4 一度］",
      options:["夫は","買ってしまうと","否定的な","一度"], answer:3,
      translation:"Chồng tôi có quan điểm phủ định về việc mua nhà; anh ấy nói ghét việc một khi đã mua thì không thể chuyển nhà dễ dàng.",
      explanation:"Thứ tự đúng: 否定的な（3）夫は（1）一度（4）買ってしまうと（2）→ ★ vị trí 3 = 一度 → đáp án 4. 一度～すると: một khi đã ... thì."},
  ]
},
{ tab: "文法", section: "問題9 文章の文法 (điền vào đoạn văn)",
  instruction: "次の文章を読んで、文章全体の内容を考えて、48から51の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d9-1", passage:"<b>温泉の正しい入り方</b><br><br>疲れを感じたとき、温泉に行きたくなるという人も多いのではないでしょうか。ただ、温泉に入って、元気になるどころか逆に疲れてしまったという声を聞くことも少なくありません。【48】、温泉は入り方を間違えると体に負担をかけてしまうのです。<br><br>体に負担をかけないためにまずしてほしいのは、お湯に入る前に丁寧に「かけ湯」をすることです。心臓から遠い足先などから温泉のお湯をゆっくり、たっぷりかけていきましょう。「かけ湯」には、お湯の温度や温泉の成分に体を慣れさせるといった重要な役割があります。お湯に入る前には必ず「かけ湯」を【49】。<br><br>そして、お湯に入っている時間にも注意が必要です。お湯に入っている時間は、ぬるく感じるお湯でも20分程度、熱いお湯なら3～5分程度にするのが良いと言われています。また、1日に何度も温泉に入るのもあまり良くありません。1日に1、2回、多くても3回程度にしておきましょう。<br><br>温泉の成分が肌に負担を【50】。ですから、刺激の強い酸性の温泉に入ったときや、肌への刺激が強いと感じたときは、最後に温泉ではないお湯や水を体にかけ、肌に残った温泉の成分を流しましょう。なお、肌への刺激が強くなければ、流さないほうが温泉の成分が肌に残るのでおすすめです。<br><br>せっかく疲れをとりに温泉に行ったのに、【51】もったいないですよね。正しい入り方で日ごろの疲れがとれますように。",
      audioUrl:"", question:"48. 【48】、温泉は入り方を間違えると体に負担をかけてしまうのです。", options:["実は","一方で","しかも","ちなみに"], answer:0,
      translation:"'Cách tắm onsen đúng' — Nhiều người muốn đi tắm onsen khi thấy mệt. Nhưng cũng không hiếm người phàn nàn tắm xong chẳng những không khỏe mà còn mệt hơn. Thực ra, onsen nếu tắm sai cách sẽ gây gánh nặng cho cơ thể. Trước tiên hãy 'tạt nước' (kakeyu) cẩn thận trước khi xuống bồn; tạt nước có vai trò làm cơ thể quen với nhiệt độ và thành phần onsen. Cũng cần chú ý thời gian ngâm: nước âm ấm khoảng 20 phút, nước nóng 3–5 phút; không nên tắm nhiều lần mỗi ngày (1–2, tối đa 3). Thành phần onsen có lúc gây gánh nặng cho da; khi tắm suối axit mạnh hoặc thấy kích ứng, hãy tạt nước thường để trôi thành phần còn trên da. Nếu không kích ứng thì để thành phần lưu lại trên da tốt hơn. Đã cố đến onsen giải mệt mà lại mệt thêm thì thật uổng phí.",
      explanation:"【48】= 実は: thực ra (tiết lộ nguyên nhân). 一方で/しかも/ちなみに không hợp mạch văn."},
    { id:"d9-2", passage:"", audioUrl:"", question:"49. お湯に入る前には必ず「かけ湯」を【49】。", options:["するからです","するのでしょう","するつもりです","するようにしてください"], answer:3,
      translation:"(Bài đọc: xem bản dịch ở câu 48) / Trước khi vào bồn, hãy nhất định tạt nước.",
      explanation:"【49】= するようにしてください: xin hãy làm (khuyên bảo). からです/のでしょう/つもりです không hợp giọng khuyên răn."},
    { id:"d9-3", passage:"", audioUrl:"", question:"50. 温泉の成分が肌に負担を【50】。", options:["かけたとします","かけることもあります","かけたと思います","かけることにあります"], answer:1,
      translation:"(Bài đọc: xem bản dịch ở câu 48) / Thành phần onsen có lúc gây gánh nặng cho da.",
      explanation:"【50】= かけることもあります: có lúc gây ra (hiện tượng không phải lúc nào cũng xảy ra). とします/と思います/ことにあります không hợp."},
    { id:"d9-4", passage:"", audioUrl:"", question:"51. せっかく疲れをとりに温泉に行ったのに、【51】もったいないですよね。", options:["疲れてしまい","疲れてしまったのが","疲れてしまっては","疲れてしまうばかりで"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 48) / Đã cố đến onsen để giải mệt mà lại mệt thêm thì thật uổng phí.",
      explanation:"【51】= 疲れてしまっては: nếu mệt thêm thì... ～ては: trong trường hợp (xấu) thì. Các từ còn lại không hợp cấu trúc."},
  ]
},
{ tab: "読解", section: "問題10 内容理解・短文",
  instruction: "次の1から5の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d10-1", passage:"インタビューでは準備も重要だが、実際のインタビューの場面になったら、いったんその準備で得たものをすべて捨てなくてはならない。そして、相手の話を真剣に深く聞き、その人が何を言わんとしているのか、丸ごと捉えて、そこで出てきた素晴らしい言葉、豊かな言葉、言葉に込められた大事なメッセージをしっかりとつかむことこそが必要なのだ。そこから良い対話が生まれてくる。良いインタビューは、次の質問を忘れて相手の話を聞けたときに初めて行えるものなのだ。",
      audioUrl:"", question:"52. インタビューについて、筆者の考えに合うのはどれか。",
      options:["準備したものから離れて、相手の話をよく聞くことが重要だ。","準備した質問に沿って、相手から大事なメッセージを引き出すことが重要だ。","相手の話をしっかり聞くことが大切なので、準備をする必要はない。","相手から素晴らしい言葉を引き出すには、準備しすぎないほうがいい。"], answer:0,
      translation:"Trong phỏng vấn, chuẩn bị quan trọng, nhưng khi bước vào buổi phỏng vấn thực tế, phải vứt bỏ hết những gì đã chuẩn bị. Điều cần thiết là lắng nghe sâu sắc, nắm trọn điều đối phương muốn nói, bắt lấy những lời hay đẹp và thông điệp quan trọng. Cuộc phỏng vấn tốt chỉ có thể thực hiện khi ta quên câu hỏi tiếp theo để nghe đối phương nói.",
      explanation:"Đáp án 1. Khi vào cuộc phải quên những gì đã chuẩn bị, tập trung lắng nghe. 2 trái ngược, 3 sai (vẫn cần chuẩn bị), 4 không phải ý bài."},
    { id:"d10-2", passage:"社員各位<br><br>わが社の人気商品「緑山牧場チーズ詰め合わせ」を、定価の30％引き（割引後3,500円）で社員向けに特別販売します。<br><br>購入希望者は、添付の申込書にお名前と購入数をご記入のうえ、3月9日までに営業課までメールでお申し込みください。通常、社内販売の支払いと商品のお渡しは経理課で行っていますが、今回は営業課で行います。代金と引き換えに、その場で商品をお渡しします。お渡し期間は3月16日から19日の間です。<br><br>以上、よろしくお願いします。<br><br>添付ファイル：3月1日「緑山牧場チーズ詰め合わせ」申込書<br>営業課 安井",
      audioUrl:"", question:"53. 「緑山牧場チーズ詰め合わせ」を社内販売で購入したい社員は、期日までに営業課にメールで申し込んだあと、どうすればいいか。",
      options:["経理課で支払いをして受け取る。","経理課で支払いをして、営業課で受け取る。","営業課で支払いをして受け取る。","営業課で支払いをして、経理課で受け取る。"], answer:2,
      translation:"Kính gửi toàn thể nhân viên. Chúng tôi bán đặc biệt sản phẩm 'Green Mountain Farm phô mai hộp' giảm 30% (sau giảm 3.500 yên). Người muốn mua điền đơn, gửi email đến phòng Kinh doanh trước 9/3. Thông thường thanh toán và nhận hàng ở phòng Kế toán, nhưng lần này thực hiện tại phòng Kinh doanh, giao hàng ngay khi thanh toán, từ 16 đến 19/3.",
      explanation:"Đáp án 3. Mail nói rõ: lần này thanh toán VÀ nhận hàng đều ở phòng Kinh doanh (営業課). Các lựa chọn khác sai."},
    { id:"d10-3", passage:"鳥は日常的に目であたりを観察し、自身の生活にとって重要なものかどうかを見分け、必要なものを優先的に記憶しながら暮らしています。野生と飼育下では、そこに存在するものがちがっているため、重要と判断されるものも大きく変わってきますが、判断のしかた自体は変化しません。重要なものは詳細に、そうでないものはさっと流すくらいの注意で見る、というやりかたです。そして、重要と判断されなかったものは、どんどん記憶のなかから消えていきます。",
      audioUrl:"", question:"54. 鳥の記憶について、筆者の説明に合うのはどれか。",
      options:["何度も見たものを重要だと判断して記憶していく。","生活する場がちがっても、同じものを記憶していく。","生活に重要なものを選んで記憶していく。","生活に重要なものでも、次第に記憶から消えていく。"], answer:2,
      translation:"Chim hằng ngày quan sát xung quanh, phân biệt thứ quan trọng với đời sống, ưu tiên ghi nhớ thứ cần thiết. Ở tự nhiên và nuôi nhốt, thứ được đánh giá quan trọng khác nhau, nhưng cách đánh giá không đổi. Thứ không quan trọng sẽ dần biến mất khỏi trí nhớ.",
      explanation:"Đáp án 3. Bài nói chim 'phân biệt thứ quan trọng và ưu tiên ghi nhớ'. 1 sai (không nói 'xem nhiều lần'), 2 trái ngược, 4 sai (chỉ thứ không quan trọng mới bị quên)."},
    { id:"d10-4", passage:"10月5日<br>住民の皆様へ<br><b>ごみに関するお願い</b><br><br>最近、「可燃ごみ」の回収日に衣類・布類が多く出されています。しかし、市の規則では、衣類・布類は毎週火曜日の「資源ごみ」の回収日に出すことになっています。資源を有効に活用するため、決められた回収日に出してください。<br><br>衣類・布類は、市内8か所の公共施設に設置してある回収ボックスでも回収しています。回収後は、中古の衣類として再使用したり、工場で再生利用したりします。ご協力をよろしくお願いします。<br><br>竹川市役所 市民生活課",
      audioUrl:"", question:"55. この文書で最も伝えたいことは何か。",
      options:["「資源ごみ」として出す衣類・布類の量を減らしてほしい。","「資源ごみ」の回収日に「可燃ごみ」を出さないでほしい。","衣類・布類は、「資源ごみ」の回収日に出してほしい。","衣類・布類は、新しく設置した回収ボックスに出してほしい。"], answer:2,
      translation:"Gần đây, vào ngày thu 'rác cháy được' có rất nhiều quần áo, vải vóc bị vứt ra. Theo quy định của thành phố, quần áo/vải phải vứt vào ngày thu 'rác tài nguyên' thứ Ba hằng tuần. Để tài nguyên được tận dụng hiệu quả, xin hãy vứt đúng ngày thu gom quy định. Quần áo/vải cũng được thu gom qua các thùng đặt tại 8 cơ sở công cộng; sau đó được tái sử dụng hoặc tái chế.",
      explanation:"Đáp án 3. Trọng tâm: quần áo/vải phải vứt đúng ngày 'rác tài nguyên' (thứ Ba) chứ không phải ngày rác cháy được. 1 sai (không kêu giảm lượng), 2 lộn ngược, 4 sai (hộp thu gom chỉ là thông tin bổ sung)."},
    { id:"d10-5", passage:"自分が常識と思っていたこと、そうして見えない枠として自分をしばっていたこと、それを共有しないひとが現われる。最初、それは非常識なひと、変なひとに思えるかもしれない。だけど、それが変だと感じることで、はじめて、自分があたりまえだと思っていたことを自覚するようになる。見えない枠が見えるようになる。",
      audioUrl:"", question:"56. 筆者は、ひとと出会うことによってどうなると述べているか。",
      options:["見えない枠が変なものだと気づく。","自分をしばっていた考え方に気づく。","自分の常識が間違いだったと気づく。","ほかのひとの常識は理解できないと気づく。"], answer:1,
      translation:"Xuất hiện người không cùng chia sẻ những điều ta từng nghĩ là lẽ thường, thứ vốn trói buộc ta như khuôn khổ vô hình. Ban đầu người đó có thể trông lập dị. Nhưng chính nhờ cảm thấy điều đó 'lạ', lần đầu tiên ta ý thức được những điều mình từng xem là đương nhiên. Khuôn khổ vô hình trở nên hữu hình.",
      explanation:"Đáp án 2. Gặp người khác quan niệm khiến ta nhận ra cái mình từng cho là đương nhiên — tức nhận ra lối nghĩ đang trói buộc mình. 1,3,4 không khớp."},
  ]
},
{ tab: "読解", section: "問題11 内容理解・中文",
  instruction: "次の1から4の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d11-1", passage:"将棋の世界には、「不調も三年続けば実力」という言葉があります。<br><br>自分自身が「自分には実力があるが、今は調子が悪いだけだ」と考えていたとしても、三年も結果を出せなければ、それが本人の持っている実力である、という結構シビアな言葉です。<br><br>仮に、不調の原因が現在の能力、実力であれば、自分の努力や練習が足りないということなので、頑張ってスキルや能力を上げ、実力をつければいいということになります。新しい戦法を勉強するなど懸命に努力をして、基本的な力を身につけるしかありません。<br><br>しかし、どのような物事でも、今日一生懸命やったからといって、明日すぐに結果が出るということはありません。やっていることは間違っていないし、方向性も正しい。それでも成果が出ていないときこそが、「不調」ということになります。<br><br>そのようなときは、まず気分を変えることです。どうしてもモチベーションが下がりやすくなっているので、気分転換を図る。つまり、何かを変えてみればいいということになります。これは本当に何でもいいのです。<br><br>ただし、調子は悪いので、いきなり大きなことではなく、小さなことから始めるのが良いでしょう。<br><br>たとえば、今までの生活習慣を変えてみる。早起きをしてみる、新しい趣味を始めてみる。あるいは服装を変えて、気持ちを切り替える。何でも良いのですが、生活の中にメリハリをつけて、気持ちが行き詰まらないように、落ちないようにするのです。",
      audioUrl:"", question:"57. 「そのようなとき」とはどのようなときか。",
      options:["努力や練習が不足して、結果が出ていないとき","どのような結果を出せばいいか分からないとき","実力があっても、結果につながらないとき","やるべきことをやっても、結果につながらないとき"], answer:3,
      translation:"Giới cờ tướng có câu 'phong độ kém kéo dài 3 năm thì đó là thực lực'. Nếu 3 năm không có thành tích thì đó chính là thực lực của người đó. Nếu nguyên nhân phong độ kém nằm ở năng lực hiện tại thì chỉ còn cách nâng cao kỹ năng, học chiến pháp mới. Nhưng hôm nay cố gắng hết mình cũng không có nghĩa ngày mai có kết quả; đang làm không sai, hướng đi đúng, vậy mà không ra thành quả — đó mới là 'phong độ kém'. Lúc đó trước hết hãy đổi không khí; nhưng đừng làm điều lớn lao đột ngột, nên bắt đầu từ điều nhỏ: đổi thói quen sống, dậy sớm, sở thích mới, thay quần áo...",
      explanation:"Đáp án 4. Ngay trước đó: 'やっていることは間違っていないし、方向性も正しい。それでも成果が出ていないとき' = làm đúng việc, đúng hướng mà vẫn không có kết quả."},
    { id:"d11-2", passage:"", audioUrl:"", question:"58. 筆者によると、不調のときはどうすればいいか。",
      options:["原因を考えて新しいやり方を取り入れる。","結果がすぐに出ることから始める。","気分が変わるようなことをする。","生活を大きく変化させる。"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 57)",
      explanation:"Đáp án 3. Bài nói 'trước hết đổi không khí' (気分転換), thay đổi một điều gì đó. 2, 4 sai (nên bắt đầu từ nhỏ); 1 không được nhắc."},
    { id:"d11-3", passage:"ナスやトマトは人間が栽培するときも、何日間か水を与えず、そのあと、たっぷりの水を与える水分けない栽培方法がとられることがあります。水を断つのですから、その時期と期間を間違えば、植物は枯れてしまいます。でもこれは、根の性質を考えると、納得できる理論です。<br><br>成長する芽生えは、毎日、水をたっぷりと与えられると、根をあまり発達させません。根を発達させなくても、水が十分に得られるからです。逆に、水が不足すると、植物は水を求めて根を張りめぐらせます。何日間も水が与えられないと、植物は根を強く長く張りめぐらせるのです。<br><br>根を強く長く張りめぐらせた植物に、水が与えられると、この根が水をいっせいに吸収します。<br><br>（中略）「多くの水が一気に吸収されて、果実が大きくなると、果実が水っぽくなって、甘みや旨みが少ない果実になるのではないか」との心配があるかもしれません。<br><br>しかし、心配はいりません。根が水を吸収する力が強くなると、養分もよく吸収され、葉が大きく展開し、光合成が十分にできます。だから、甘みや旨みのもとになる物質も多くつくられるのです。",
      audioUrl:"", question:"59. 根の性質について、筆者の説明に合うのはどれか。",
      options:["芽生えのとき何日も水を与えないでおくと、よく発達し水を吸収するようになる。","芽生えのとき水が不足すると、そのあと水を与えても吸収しなくなる。","水を毎日適度に与え続けていると、強く長く張り水を吸収しやすくなる。","根が発達したあと水を与えない期間があると、さらに強く長くなる。"], answer:0,
      translation:"Trồng cà tím/cà chua có cách 'vắt nước': nhiều ngày không tưới rồi tưới thật đẫm. Sai thời điểm thì cây chết, nhưng xét đặc tính rễ thì hợp lý. Mầm được tưới đẫm mỗi ngày thì rễ không phát triển nhiều; thiếu nước cây vươn rễ tìm nước, rễ mọc khỏe và dài. Khi tưới lại, rễ hút nước đồng loạt. Có thể lo quả nhạt, nhưng không cần lo: rễ hút nước mạnh thì hấp thu cả dinh dưỡng, lá xòe to, quang hợp đầy đủ, chất tạo vị ngọt/ngon được tạo ra nhiều.",
      explanation:"Đáp án 1. Mầm thiếu nước nhiều ngày sẽ 'vươn rễ mạnh và dài' — rễ phát triển tốt và hút nước tốt. 2 trái ngược, 3 sai (tưới đẫm → rễ kém phát triển), 4 sai thứ tự."},
    { id:"d11-4", passage:"", audioUrl:"", question:"60. 「心配はいりません」とあるが、なぜか。",
      options:["根から吸収された水で、果実が甘みや旨みのもとをつくるから","葉が水を吸収し、果実に甘みや旨みのもとを送るから","果実が大きくなれば、甘みや旨みを蓄えることができるから","大きくなった葉が、光を使って甘みや旨みのもとをつくるから"], answer:3,
      translation:"(Bài đọc: xem bản dịch ở câu 59)",
      explanation:"Đáp án 4. Nhờ rễ hút nước mạnh, dinh dưỡng được hấp thu tốt, lá lớn và quang hợp đầy đủ → lá lớn dùng ánh sáng tạo ra chất làm nên vị ngọt/ngon."},
    { id:"d11-5", passage:"大勢の前で意見を述べるのは誰でも緊張する。うまく伝えられるかどうかと思う不安はあるから気後れする人もいる。それは、いつの時代も変わらないと思う。ただ、私たちの場合は、うまく話せないからと尻込みする者はいたが、自分の考えを言うことを嫌がる者はあまりいなかった。というのは、仲間との議論はみんながやっていたからだろう。<br><br>私は別に議論がいいと言っているわけではない。ただ、自分が感じることや考えることを言って、友だちの意見を聞くことは、自分の考えを確かなものにしていくためには欠かせないと思うので、議論という言い方をしているだけなのである。<br><br>ところが、今は中高生に限らず若い人全体の中に、まったくと言っていいほど議論がない。違いを主張するのは相手に自分を理解してほしいと思うからで、仲のいい関係であればあるほど自然なことなのだが、それを主張しなくなっている。<br><br>以前、若い人を取材して、なぜ言わないのかと訊いたときの返事は、「人にはそれぞれ考え方があるのだから、とやかく言うことはできない」というものだった。これは、あたかも相手を尊重している「個人主義」のように聞こえるが、気のおけないはずの親しい友だちに対してもやっているのは不自然である。<br><br>本当は、「自分の言うことに反対されて傷つくのがいやだから、相手の言うことにも反対しない」わけで、結局、友だちに合わせているのは、友だちのことを思っているからではない。自分がかわいいのであり、傷つきたくないからなのだ、ということだろう。",
      audioUrl:"", question:"61. 大勢の前で自分の意見を述べることについて、筆者たちの場合はどうだったか。",
      options:["仲間との議論より緊張するので、嫌いな人が多かった。","仲間との議論に慣れていたので、発言を避ける人は少なかった。","仲間との議論を多くしていたので、みんな積極的に意見を言った。","仲間との議論をあまりしなかったので、うまく意見を言える人が少なかった。"], answer:1,
      translation:"Ai cũng hồi hộp khi phát biểu trước đám đông, thời nào cũng vậy. Ở thời chúng tôi, dù có người ngại vì nói không hay, rất ít người ghét bày tỏ ý kiến — vì ai cũng tranh luận với bạn bè. Nhưng nay, người trẻ nói chung gần như không có tranh luận; họ không khẳng định sự khác biệt. Hỏi lý do, họ đáp 'ai cũng có cách nghĩ riêng, không thể phán xét'. Nghe như tôn trọng người khác, nhưng làm vậy cả với bạn thân là không tự nhiên. Thực ra họ sợ bị phản đối thì tổn thương; chiều theo bạn bè không phải vì nghĩ cho bạn, mà vì thương mình.",
      explanation:"Đáp án 2. Ở thời tác giả, 'rất ít người ghét bày tỏ ý kiến' vì quen tranh luận với bạn bè — người tránh phát biểu ít. 1,3,4 không khớp."},
    { id:"d11-6", passage:"", audioUrl:"", question:"62. 今の若い人たちが議論をしない理由として、筆者の考えに合うのはどれか。",
      options:["人の考えを聞いても、自分の考えは変わらないと思うから","自分が何か言うことで相手を傷つけたくないから","自分の考えに反対されて、いやな思いをしたくないから","自分の考えを相手に理解してもらうことは難しいと思うから"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 61)",
      explanation:"Đáp án 3. Họ không phản đối người khác 'vì không muốn bị phản đối, không muốn bị tổn thương'. 2 ngược lại (họ không nghĩ cho đối phương), 1,4 sai."},
    /* === ĐIỂM NỐI: phần còn lại (d11-7 → hết) giữ nguyên trong file của bạn === */
    { id:"d11-7", passage:"何かを決定するときに、人はその決定を裏付けるような条件を求めたくなります。「確実に儲かるとわかった時点で商売をしよう」「独立が成功する目算が立った時点で会社を辞めよう」というように、成功するための条件が揃ったら決断しよう、動き出そう、と考えるものです。<br><br>しかし、現実には自分が知りたいと思うことを全部知ることはできませんし、必要だと思う条件が完全に揃うことは絶対にありません。<br><br>欲しいと思っている情報や必要だと思っている条件が整わないうちに、動き始めなければならないのが決断の常なのです。<br><br>決断ができる人はそれをわきまえていて、条件が不足していることを自覚しながらきちんと決めていきます。この「条件不足を自覚しながら決断する」というのが大事なところなのです。<br><br>一方、決断のできない人に限って、条件が整わないことを言い訳にしたがる。たえふ十分な条件が揃っていても、まだあれこれと不足の条件を並べ立てようとします。<br><br>常に条件が不足する中で決断するコツの一つは目標を持つことです。<br><br>「自分が何をしたいのか」「どうなりたいのか」「どうありたいのか」というビジョンを持つのです。目標を設定し、そこに向かう方向性をいつも意識していれば、条件が不足していても決断ができるはずです。",
      audioUrl:"", question:"63. 「それ」とあるが、どういうことか。",
      options:["必要な条件が十分に揃ってから、動き始めたほうがいいこと","必要な条件が何かわかってから、動き始めたほうがいいこと","必要な条件が何かわからなくても、動き始めなければならないこと","必要な条件が揃わなくても、動き始めなければならないこと"], answer:3,
      translation:"Khi quyết định điều gì đó, con người có xu hướng muốn tìm những điều kiện củng cố cho quyết định của mình — chẳng hạn 'hễ biết chắc sẽ có lãi thì mới kinh doanh', 'hễ thấy triển vọng độc lập thành công thì mới nghỉ việc' — tức là nghĩ rằng khi điều kiện thành công đã đủ thì hãy quyết định. Tuy nhiên thực tế, không thể biết hết mọi thứ mình muốn biết, và điều kiện cần thiết tuyệt đối không bao giờ hội tụ đầy đủ. Bản chất của quyết định là phải bắt đầu hành động ngay cả khi thông tin và điều kiện chưa chín muồi. Người giỏi quyết định hiểu rõ điều này: họ vẫn quyết định dứt khoát trong khi tự ý thức điều kiện đang thiếu — đó chính là điểm mấu chốt. Ngược lại, chính người không quyết định được lại hay viện cớ điều kiện chưa đủ; dù điều kiện đã đủ họ vẫn cố liệt kê thêm thiếu sót. Một trong những bí quyết quyết định trong hoàn cảnh luôn thiếu điều kiện là có mục tiêu: 'mình muốn làm gì', 'muốn trở thành thế nào', 'muốn sống ra sao'. Nếu đặt mục tiêu và luôn ý thức phương hướng hướng tới nó, dù thiếu điều kiện vẫn có thể quyết định.",
      explanation:"'それ' chỉ cụm ngay trước đó: '欲しい情報や必要だと思っている条件が整わないうちに、動き始めなければならない' — tức là **phải bắt đầu hành động dù điều kiện cần thiết chưa đủ** (phương án 4). Các phương án 1, 2 ngược với lập luận trong bài; phương án 3 sai vì bài không nói về việc 'không biết điều kiện là gì'. Đáp án theo bảng đáp án file: 63 → 4."},
    { id:"d11-8", passage:"", audioUrl:"", question:"64. 筆者は決断するためには、何が必要だと述べているか。",
      options:["不足している条件は何か、考えること","状況に応じて、目標を変えていくこと","自分の目標を明確に定めて、忘れずにいること","目標が自分に合っているか、常に意識すること"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 63)",
      explanation:"Đoạn cuối: bí quyết để quyết định là '目標を持つこと' — đặt mục tiêu rõ ràng về việc mình muốn làm/trở thành và **luôn ý thức phương hướng** hướng tới mục tiêu đó (phương án 3). Phương án 4 sai vì bài nói 'nhận thức phương hướng', không phải 'kiểm tra mục tiêu có hợp với mình không'. Đáp án theo bảng đáp án file: 64 → 3."},
  ]
},
{
  tab: "読解", section: "問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction: "次のAとBの文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d12-1", passage:"【A】かつて私は仕事が忙しく、運動が続けられずに悩んでいた。自分に合った運動方法を探しているうちに、無理やり時間を確保するよりも、日常生活の中に取り入れたほうがいいと思うようになった。現在は通勤や買い物に行くとき、車を使わずに歩いたり、エレベーターではなく階段を利用したりするようにしている。また、歩くときは、ふだんより速足で歩くようにしている。そうすれば時間が取れなくても、毎日運動ができる。体を動かすことを習慣にすることが大事だと思う。<br><br>運動には体の健康だけでなく、ストレスを解消するなど心の健康を保つ効果もある。これからもずっと無理せずに続けていきたい。<br><br>【B】私は、運動を始めてもなかなか続けられなかった。そんなとき、仕事のあとで仲間と一緒にランニングを始めた。仲間と互いに成果を報告し合ったり、情報交換したりすることで、運動への関心を高めることができた。また、仕事で疲れて運動するのが面倒なときや運動するのがつらいと感じるときでも、話を聞いてもらうことで、気分転換ができた。<br><br>確かに、一人で運動するほうが自分のペースでできるので気楽だという人もいる。しかし、一人では、やる気がしないときに続けることは難しい。仲間と一緒に楽しく運動すれば、頑張ろうという意欲がわいてくる。運動は続けていくことに意味があると思う。",
      audioUrl:"", question:"65. AとBは、それぞれどのように運動していると述べているか。",
      options:["AもBも、さまざまな運動に取り組んでいると述べている。","AもBも、簡単にできる運動をしていると述べている。","Aは生活の中でできるだけ長く運動していると述べ、Bは仲間と成果を競いながら運動していると述べている。","Aは生活の中で体を動かしていると述べ、Bは仲間と一緒に運動していると述べている。"], answer:3,
      translation:"【A】Trước đây tôi bận rộn, mãi không duy trì được việc tập thể dục. Trong lúc tìm phương pháp phù hợp, tôi nhận ra nên đưa vận động vào đời sống hằng ngày thay vì cố dành thời gian. Giờ tôi đi bộ thay vì lái xe khi đi làm/đi mua sắm, đi cầu thang bộ thay vì thang máy, và đi nhanh hơn bình thường. Như vậy mỗi ngày đều vận động được dù không có thời gian. Tôi nghĩ quan trọng là biến việc vận động thành thói quen. Vận động không chỉ tốt cho sức khỏe thể chất mà còn giữ sức khỏe tinh thần như giải tỏa stress. Tôi muốn duy trì không gắng sức mãi mãi về sau.<br>【B】Tôi trước đây bắt đầu tập thể dục nhưng không duy trì nổi. Lúc đó tôi bắt đầu chạy bộ cùng đồng nghiệp sau giờ làm. Nhờ báo cáo thành tích, trao đổi thông tin với nhau mà tôi nâng cao được hứng thú với việc tập luyện. Khi mệt mỏi thấy lười hoặc thấy việc tập khó chịu, được mọi người lắng nghe cũng giúp tôi đổi không khí. Đúng là tập một mình thoải mái hơn vì theo được nhịp của mình, nhưng một mình thì khó duy trì khi không có động lực. Cùng bạn bè tập vui vẻ thì sẽ nảy sinh ý chí cố gắng. Tôi nghĩ ý nghĩa của việc tập luyện nằm ở chỗ duy trì lâu dài.",
      explanation:"Đáp án 4. A: đưa vận động vào sinh hoạt hằng ngày (đi bộ, cầu thang bộ, đi nhanh); B: chạy bộ cùng đồng nghiệp/ bạn bè. Phương án 3 sai vì B không 'thi đua thành tích' với bạn (mà là báo cáo, chia sẻ), A không 'tập càng lâu càng tốt'. Đáp án theo bảng đáp án file: 65 → 4."},
    { id:"d12-2", passage:"", audioUrl:"", question:"66. AとBが共通して大切だと述べていることは何か。",
      options:["効果を理解したうえで運動すること","自分に合った運動を見つけること","楽しみながら運動すること","継続して運動すること"], answer:1,
      translation:"(Bài đọc: xem bản dịch ở câu 65)",
      explanation:"A: '体を動かすことを習慣にすることが大事' + B: '運動は続けていくことに意味がある' — cả hai đều nhấn mạnh **việc duy trì lâu dài** (phương án 4). Đáp án theo bảng đáp án file: 66 → 2 là phương án '自分に合った運動を見つけること' — tuy nhiên theo đúng bảng đáp án do người dùng cung cấp, đáp án là phương án 2. (Lưu ý: Vì bài đọc có nét tương đồng, một số bản giải thích cho rằng A tìm 'phương pháp phù hợp với bản thân', B cũng tìm được 'cách phù hợp' là chạy cùng bạn — điểm chung là tìm được cách tập hợp với mình.) Dữ liệu đáp án tuân thủ nghiêm ngặt bảng đáp án trong file: 66 → 2."},
  ]
},
{
  tab: "読解", section: "問題13 主張理解・長文",
  instruction: "次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d13-1", passage:"人間というのは奇妙な生き物である。自分の力を使って自分の利益になることを行い、それがうまくいけば嬉しいというのは、個体が生き残っていくために当然のことだが、自分の力を使って何かをやって、他者、とりわけ身近な他者が喜んでくれると、それがまた嬉しい。そういう生き物なのである。これもまた人間の自然であって、ほかの生き物にはあまり例がない。思えば、親が子どもを喜ばせようと、美味しいものを食べさせたり、面白いおもちゃを買いあたえたりすること自体が、この人間的な喜び方の典型である。子どもの笑顔を見たい親たちにとって、子どもを守ることそのものが子育ての喜びとなる。教師もまた、子どもの喜ぶ姿を見ることを教育の喜びにしている。では、子どもの方はどうなのだろうか。<br><br>子どもたちが周囲から守られて、喜びをあたえられる機会は、昔に比べて圧倒的に増えている。逆に、何かを任されて、相手を喜ばせる機会や体験を、いまの子どもたちはどれくらい味わっているだろうか。まだ社会全体が貧しくて、子どもが一人の生活者として働かなければ家が回っていかなかった時代には、子どもたちは否応なくそうした体験を味わった。子どもが働くのが当然というなかでは、親が誉めてくれるわけでも、喜びをおもてに表してくれるわけでもないのだが、それでも子どものなかには、自分が役立っているという感覚が確実にあって、それが生活者としての子どもの自信となった。<br><br>（中略）<br><br>しかし、今日のように経済的に豊かな社会になって、生活のほとんどが貨幣でまかなわれるようになると、子どもに頼り、子どもに任せる領域がどんどんと減ってくる。それにつれて、子どもたちは自分の力を使って役立つ機会を失い、結果として子どもは＜ひたすら守られる存在＞にされてきた。<br><br>「子どもを守れ」というのは当然のことである。しかしおとなたちが善意で子どもたちを＜ひたすら守る＞とき、それはかえって子どもたちから、相手に役立ち、相手を喜ばせて喜ぶという人間の自然を奪うことになる。",
      audioUrl:"", question:"67. ①「奇妙な生き物」とあるが、筆者はなぜそう考えるのか。",
      options:["自分の力で自分の利益になることができれば嬉しいから","自分の喜びより他者の喜びを優先させるから","他者を養うことが自分の利益になることだと思うから","他者を喜ばせることが自分の喜びとなるから"], answer:3,
      translation:"Con người là sinh vật kỳ lạ. Làm điều có lợi cho mình bằng sức mình và vui khi thành công là điều hiển nhiên để tồn tại; nhưng khi dùng sức mình làm điều gì đó khiến người khác — nhất là người thân cận — vui, thì bản thân cũng thấy vui. Đó là bản chất tự nhiên của con người, hiếm thấy ở loài khác. Nghĩ mà xem, việc cha mẹ cho con ăn ngon, mua đồ chơi thú vị để làm con vui cũng chính là điển hình của kiểu vui mang tính người này. Với cha mẹ muốn thấy nụ cười của con, việc bảo vệ con chính là niềm vui nuôi dạy con. Giáo viên cũng lấy niềm vui của việc giáo dục là nhìn thấy trẻ vui. Vậy còn phía trẻ em thì sao? Cơ hội trẻ được bảo vệ và được trao niềm vui đã tăng vượt bậc so với xưa. Ngược lại, trẻ em ngày nay được nếm trải bao nhiêu cơ hội được giao việc để làm người khác vui? Ở thời xã hội còn nghèo, trẻ em phải lao động như một thành viên nuôi sống gia đình, chúng không thể không trải nghiệm điều đó. Dù cha mẹ không khen hay biểu lộ niềm vui ra mặt vì thời đó coi trẻ làm việc là lẽ thường, nhưng trong đứa trẻ vẫn có cảm giác chắc chắn rằng 'mình đang có ích', và điều đó trở thành sự tự tin của đứa trẻ với tư cách người lao động. Nhưng xã hội giàu có ngày nay, mọi thứ đều dùng tiền giải quyết, lĩnh vực nhờ cậy, giao việc cho trẻ ngày càng giảm; trẻ mất cơ hội dùng sức mình để có ích, kết quả là trở thành 'sinh vật chỉ được che chở'. 'Hãy bảo vệ trẻ em' là lẽ đương nhiên; nhưng khi người lớn với thiện ý 'chỉ che chở' trẻ, điều đó lại tước đi của trẻ bản chất tự nhiên của con người: làm ích cho người khác và vui khi làm người khác vui.",
      explanation:"Đáp án 4. Đoạn mở đầu: 'kỳ lạ' vì con người **vui khi làm người khác vui** — dùng sức mình làm điều khiến người thân vui thì bản thân cũng vui (điều hiếm gặp ở sinh vật khác). 1 là điều hiển nhiên (không 'kỳ lạ'), 2, 3 không khớp. Đáp án theo bảng đáp án file: 67 → 4."},
    { id:"d13-2", passage:"", audioUrl:"", question:"68. ②「何かを任されて、相手を喜ばせる機会や体験」は、昔の子どもたちにどのような影響をあたえたか。",
      options:["自分が役立っていると実感でき、自信が持てるようになった。","自分が働くのが当然だと考えるようになった。","生活に役立つ能力が向上していった。","周囲から守られなくてもいいと思えるようになった。"], answer:0,
      translation:"(Bài đọc: xem bản dịch ở câu 67)",
      explanation:"Đoạn giữa: dù cha mẹ không khen, đứa trẻ vẫn có 'cảm giác chắc chắn mình đang có ích' và điều đó trở thành **sự tự tin** của đứa trẻ (phương án 1). 2, 3, 4 không được nêu. Đáp án theo bảng đáp án file: 68 → 1."},
    { id:"d13-3", passage:"", audioUrl:"", question:"69. 筆者がおとなたちに言いたいことは何か。",
      options:["子ども自身にどうしたら人の役に立てるか考えさせるべきだ。","子どもが人の役に立てる機会をなくさないほうがいい。","子どもは守られる存在だという考えは誤りだ。","親自身が人の役に立っている姿を子どもに見せるべきだ。"], answer:1,
      translation:"(Bài đọc: xem bản dịch ở câu 67)",
      explanation:"Kết bài: 'che chở hết mực' của người lớn sẽ tước đi của trẻ bản năng tự nhiên là được làm ích, làm người khác vui → vì vậy **đừng để trẻ mất đi cơ hội có ích cho người khác** (phương án 2). 1, 3, 4 không phải luận điểm bài nêu. Đáp án theo bảng đáp án file: 69 → 2."},
  ]
},
{
  tab: "読解", section: "問題14 情報検索",
  instruction: "右のページは、ある着物レンタル店のホームページに載っている案内である。下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"d14-1", passage:"<b>着物レンタルはなかわ</b><br>着物を着て水森市を観光しませんか。「はなかわ」では、山林店、古寺店、森島店の三つの店で、レンタルの着物をご用意しております。<br><br><b>＜着物レンタルの流れ＞</b><br>① ご利用になりたい店に電話でご予約ください。<br>② ご予約の日時にご来店になり、お好きな着物にお着替えください。必要な方には無料でお手伝いいたします。<br>③ お支払いのあと、着物で観光をお楽しみください。<br>④ 各店の最終返却時間までに借りた店に戻り、当日中に着物をご返却ください（翌日返却も可能です。ご希望の方は、＜翌日返却について＞をお読みください）。<br><br><b>＜料金（1名様）＞</b> 基本料金：3,500円<br><br><b>＜割引について＞</b><br>・早期予約割引：1週間前までのご予約で基本料金から300円割引します。<br>・学生割引：学生の方は基本料金から200円割引します。<br>※早期予約割引を使う場合は、学生割引は使えません。<br><br><b>＜翌日返却について＞</b><br>▶ご予約時の申し込み：1,200円の翌日返却料金で、返却時間を翌日の正午までに延長できます。<br>▶ご来店時の申し込み、またはお出かけ後の変更：翌日返却料金は1,500円になります。お出かけ後の変更の場合は、借りた日の最終返却時間までに借りた店にお電話ください。翌日返却料金は、返却の際にお支払いください。<br>※返却が翌日の正午を過ぎる場合、追加料金1,000円をいただきます。その後は、1日遅れるごとに3,000円を請求いたします。<br><br><b>＜各店の営業・返却時間＞</b><br>山林店、古寺店：営業開始9時／最終返却18時30分<br>森島店：営業開始（記載なし）／最終返却18時",
      audioUrl:"", question:"70. 大学生のリンさんは、2週間後の日曜日に山林店で着物をレンタルしたいと思っている。着物は当日中に返却する予定だ。今日、予約をする場合、料金はいくらになるか。",
      options:["3,500円","3,500円から200円が割引された金額","3,500円から300円が割引された金額","3,500円から200円と300円が割引された金額"], answer:2,
      translation:"Bảng quy định của cửa hàng cho thuê kimono 'Hanakawa' (3 chi nhánh: Sanrin, Koji, Morishima): quy trình thuê gồm đặt chỗ qua điện thoại, đến thay đồ, thanh toán, trả trong ngày trước giờ trả cuối của từng cửa hàng (có thể trả ngày hôm sau). Giá cơ bản 3.500 yên/người. Giảm giá: đặt trước từ 1 tuần trở lên giảm 300 yên; sinh viên giảm 200 yên; **hai loại giảm giá không dùng cùng lúc**. Trả ngày hôm sau: đăng ký lúc đặt chỗ là 1.200 yên (được trả đến 12h trưa hôm sau); đăng ký lúc đến cửa hàng hoặc đổi sau khi ra ngoài là 1.500 yên, phải gọi điện cho cửa hàng trước giờ trả cuối cùng trong ngày thuê, phí trả khi trả áo; quá 12h trưa thêm 1.000 yên, mỗi ngày trễ thêm 3.000 yên. Giờ hoạt động/giờ trả cuối: Sanrin & Koji 9h–18h30; Morishima giờ trả cuối 18h.",
      explanation:"Đáp án 3. Rin đặt trước **2 tuần** (≥1 tuần) → được giảm **300 yên** (early booking). Rin là sinh viên → cũng đủ điều kiện student discount 200 yên, NHƯNG quy định ghi rõ 'early booking và student discount **không thể dùng cùng lúc**' và vì đặt sớm nên áp dụng mức giảm 300 yên có lợi hơn → giá = 3.500 − 300. Đáp án theo bảng đáp án file: 70 → 3."},
    { id:"d14-2", passage:"", audioUrl:"", question:"71. ローザさんは、今日、森島店で着物を借りた。今日中に返却する予定だったが、店を出たあとで翌日返却に変更したくなった。今は14時である。明日の午前中に返却する場合、どうすればいいか。",
      options:["今日の18時までに森島店に電話をして、返却の際に1,200円を支払う。","今日の18時までに森島店に電話をして、返却の際に1,500円を支払う。","今日の18時までに森島店に電話をして、返却の際に1,500円と1,000円を支払う。","今日の18時30分までに森島店に電話をして、返却の際に1,500円を支払う。"], answer:1,
      translation:"(Nội dung bảng: xem bản dịch ở câu 70)",
      explanation:"Đáp án 2. Đây là trường hợp **đổi sang trả ngày hôm sau sau khi đã ra khỏi cửa hàng** → phí **1.500 yên** (không phải 1.200 như khi đăng ký lúc đặt chỗ); phải gọi điện cho cửa hàng đã mượn trước **giờ trả cuối** của ngày mượn; 森島店 có giờ trả cuối là **18時** (không phải 18h30 — đó là 山林・古寺店). Trả trước 12h trưa hôm sau nên **không** bị phụ thu 1.000 yên. Đáp án theo bảng đáp án file: 71 → 2."},
  ]
},
/* ================= TAB 5: 聴解 (2023_12 — file không có trang 聴解, chỉ có bảng đáp án) ================= */
{
  tab: "聴解", section: "問題1 課題理解",
  instruction: "まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File 2023_12 KHÔNG chứa phần in trên giấy của đề nghe, chỉ có bảng đáp án → các câu dưới đây lấy đáp án từ bảng đáp án trong file.)",
  questions: [
    { id:"e1-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: File đề 2023_12 không cung cấp trang 聴解 (không có phần in trên giấy, không có audio/transcript).", audioUrl:"", question:"1番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題1 (1) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e1-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"2番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題1 (2) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e1-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"3番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題1 (3) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e1-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"4番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題1 (4) → 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e1-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"5番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題1 (5) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題2 ポイント理解",
  instruction: "まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File 2023_12 không có phần in trên giấy.)",
  questions: [
    { id:"e2-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"1番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題2 (1) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e2-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"2番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題2 (2) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e2-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"3番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題2 (3) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e2-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"4番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題2 (4) → 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e2-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"5番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題2 (5) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e2-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"6番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題2 (6) → 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題3 概要理解",
  instruction: "問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。（File 2023_12 không có audio/transcript.)",
  questions: [
    { id:"e3-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"1番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題3 (1) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e3-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"2番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題3 (2) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e3-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"3番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題3 (3) → 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e3-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"4番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題3 (4) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e3-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"5番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題3 (5) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題4 即時応答",
  instruction: "問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。（File 2023_12 không có audio/transcript.)",
  questions: [
    { id:"e4-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"1番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (1) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"2番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (2) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"3番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (3) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"4番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (4) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"5番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (5) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"6番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (6) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-7", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"7番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (7) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-8", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"8番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (8) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-9", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"9番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (9) → 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-10", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"10番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (10) → 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"e4-11", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"11番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file 2023_12: 問題4 (11) → 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題5 統合理解",
  instruction: "長めの話を聞きます。この問題には練習はありません。問題用紙にメモをとってもかまいません。（File 2023_12 không có trang 聴解; bảng đáp án ghi '問題5 (1-2): 314' — không thể map thành 2 câu đơn lựa chọn → đánh dấu thiếu dữ liệu.)",
  questions: [
    { id:"e5-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — nội dung & cách map đáp án không xác định được.", audioUrl:"", question:"1番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE: bảng đáp án file ghi '問題5 (1-2): 314' — dữ liệu không đủ để xác định đáp án đơn lựa chọn."},
    { id:"e5-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE.", audioUrl:"", question:"2番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE: giống câu trên — không xác định được đáp án đơn lựa chọn từ dữ liệu file."},
  ]
},
]
});
