/* =========================================================================
   data_2023_07.js — JLPT N2 2023年7月
   Đặt cùng thư mục index.html (hoặc dán vào ô "Nạp dữ liệu" của app).
   ========================================================================= */
JLPT_REGISTER({
metadata: { id:"n2_2023_07", label:"07/2023", title:"JLPT N2 — 2023年7月 (07/2023)", file:"data_2023_07.js" },
data: [

/* ================= TAB 1: 文字・語彙 ================= */
{
  tab: "文字・語彙", section: "問題1 漢字読み",
  instruction: "＿＿＿の言葉の読み方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a1-1", passage:"", audioUrl:"", question:"1. バスの<u>運賃</u>を払う。", options:["うんしん","うんちん","うんにん","うんりん"], answer:1,
      translation:"Trả tiền vé xe buýt.",
      explanation:"運賃 = うんちん: tiền vé (phương tiện công cộng). うんしん・うんにん・うんりん đều không phải âm đọc đúng của 運賃."},
    { id:"a1-2", passage:"", audioUrl:"", question:"2. 風が強くて、髪が<u>乱れて</u>しまった。", options:["くずれて","あれて","あばれて","みだれて"], answer:3,
      translation:"Gió mạnh khiến tóc bị rối tung.",
      explanation:"乱れる = みだれる: rối loạn, mất trật tự. 崩れる (sụp đổ), 荒れる (dữ dội/hoang dại), 暴れる (nổi loạn) không hợp nghĩa tóc rối."},
    { id:"a1-3", passage:"", audioUrl:"", question:"3. 前田さんは子供たちに正しい泳ぎ方の<u>模範</u>を示した。", options:["もうばん","もうはん","もばん","もはん"], answer:3,
      translation:"Anh Maeda đã cho bọn trẻ thấy tấm gương (mẫu mực) về cách bơi đúng.",
      explanation:"模範 = もはん: mẫu mực, hình mẫu. Các âm もうばん・もうはん・もばん không tồn tại cho từ này."},
    { id:"a1-4", passage:"", audioUrl:"", question:"4. 思った以上に<u>険しかった</u>。", options:["けわしかった","まぶしかった","おそろしかった","はげしかった"], answer:0,
      translation:"(Nó) hiểm trở hơn tôi tưởng.",
      explanation:"険しい = けわしい: hiểm trở (địa hình), gay go. 眩しい (chói mắt), 恐ろしい (đáng sợ), 激しい (dữ dội) không đúng."},
    { id:"a1-5", passage:"", audioUrl:"", question:"5. さっき<u>握手</u>していた人は誰ですか。", options:["おくしゅ","はくしゅ","あくしゅ","ほくしゅ"], answer:2,
      translation:"Người vừa nãy đang bắt tay là ai vậy?",
      explanation:"握手 = あくしゅ: bắt tay. おくしゅ・はくしゅ・ほくしゅ không phải âm đọc đúng."},
  ]
},
{
  tab: "文字・語彙", section: "問題2 表記",
  instruction: "＿＿＿の言葉を漢字で書くとき、最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a2-1", passage:"", audioUrl:"", question:"6. その<u>ぬの</u>を広げてください。", options:["布","袋","衣","帯"], answer:0,
      translation:"Hãy trải tấm vải đó ra.",
      explanation:"ぬの = 布: vải. 袋 (túi), 衣 (áo), 帯 (đai, thắt lưng) không đọc là ぬの."},
    { id:"a2-2", passage:"", audioUrl:"", question:"7. 今後は<u>ふくし</u>の仕事に就く予定です。", options:["福支","副祉","福祉","副支"], answer:2,
      translation:"Từ nay tôi dự định làm công việc phúc lợi (an sinh).",
      explanation:"ふくし = 福祉: phúc lợi, phúc chỉ. 福支・副祉・副支 không phải chữ viết đúng."},
    { id:"a2-3", passage:"", audioUrl:"", question:"8. 毎日たくさんのごみが<u>すてられて</u>いる。", options:["拾てられて","投てられて","採てられて","捨てられて"], answer:3,
      translation:"Hằng ngày rất nhiều rác bị vứt bỏ.",
      explanation:"すてる = 捨てる: vứt, bỏ đi. (Chú ý: file gốc có lỗi OCR lặp từ 拾てられて; chữ đúng là 捨ててられて → phương án 4). 拾う (nhặt), 投げる (ném), 採る (hái/lấy) không đúng."},
    { id:"a2-4", passage:"", audioUrl:"", question:"9. 小山さんの<u>きげん</u>がよいときに頼んでみよう。", options:["機兼","機嫌","気嫌","気兼"], answer:1,
      translation:"Hãy thử nhờ vả lúc anh Koyama đang vui vẻ (tâm trạng tốt).",
      explanation:"きげん = 機嫌: tâm trạng, sắc mặt. 機嫌がよい = vui vẻ. Các phương án khác không phải chữ viết đúng."},
    { id:"a2-5", passage:"", audioUrl:"", question:"10. これは、会社にとって大きな<u>そんしつ</u>だ。", options:["削失","限失","消失","損失"], answer:3,
      translation:"Đây là một tổn thất lớn đối với công ty.",
      explanation:"そんしつ = 損失: tổn thất, thiệt hại. 消失 (tiêu biến), 削失・限失 không phải từ đúng."},
  ]
},
{
  tab: "文字・語彙", section: "問題3 語形成",
  instruction: "（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a3-1", passage:"", audioUrl:"", question:"11. アンケートでは、質問に（ ）回答の人もいた。", options:["無","空","欠","失"], answer:0,
      translation:"Trong phiếu khảo sát, cũng có người trả lời (để) trống câu hỏi.",
      explanation:"無回答 (むかいとう): không trả lời. 無 + 回答 tạo nghĩa 'không có câu trả lời'. 空回答・欠回答・失回答 không phải từ thông dụng."},
    { id:"a3-2", passage:"", audioUrl:"", question:"12. この本には海外にある日本（ ）の家がたくさん載っている。", options:["気","類","風","状"], answer:2,
      translation:"Cuốn sách này có rất nhiều ảnh ngôi nhà kiểu Nhật (phong cách Nhật) ở nước ngoài.",
      explanation:"日本風 (にほんふう): phong cách Nhật. ～風 = theo phong cách, kiểu. 気・類・状 không tạo từ 日本気/日本類/日本状."},
    { id:"a3-3", passage:"", audioUrl:"", question:"13. 壁（ ）のソファーに座る。", options:["所","際","辺","域"], answer:1,
      translation:"Ngồi xuống chiếc sofa sát tường.",
      explanation:"壁際 (かべぎわ): sát tường. ～際 = chỗ giáp ranh, sát. 壁所・壁辺・壁域 không phải từ thông dụng."},
  ]
},
{
  tab: "文字・語彙", section: "問題4 文脈規定",
  instruction: "（ ）に入るのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a4-1", passage:"", audioUrl:"", question:"14. 彼は本当は優しい人なのに、無口なせいで、冷たい人だとよく（ ）される。", options:["観測","誤解","決意","承認"], answer:1,
      translation:"Anh ấy thật ra là người tốt bụng, nhưng vì ít nói nên hay bị hiểu lầm là người lạnh lùng.",
      explanation:"誤解される: bị hiểu lầm. 観測 (quan trắc), 決意 (quyết tâm), 承認 (công nhận) không hợp ngữ cảnh."},
    { id:"a4-2", passage:"", audioUrl:"", question:"15. 新製品の売れ行きが（ ）なので、生産量を増やすことにした。", options:["温厚","円満","好調","適切"], answer:2,
      translation:"Vì sản phẩm mới bán chạy (tình hình tốt) nên chúng tôi quyết định tăng sản lượng.",
      explanation:"好調 (こうちょう): thuận lợi, suôn sẻ (về tình hình). 温厚 (ôn hòa), 円満 (viên mãn), 適切 (thích hợp) không dùng cho 売れ行き."},
    { id:"a4-3", passage:"", audioUrl:"", question:"16. 彼は、どんな仕事でもミス一つなく期日までに仕上げてくれるので、本当に（ ）部下だと思う。", options:["頼もしい","たくましい","輝かしい","親しい"], answer:0,
      translation:"Anh ấy làm việc gì cũng không sai sót và hoàn thành đúng hạn, nên tôi nghĩ đúng là một cấp dưới đáng tin cậy.",
      explanation:"頼もしい: đáng tin cậy, làm yên tâm. たくましい (vạm vỡ), 輝かしい (rực rỡ), 親しい (thân thiết) không hợp."},
    { id:"a4-4", passage:"", audioUrl:"", question:"17. 食費を（ ）するために、なるべく外食をしないようにしている。", options:["減量","省略","短縮","節約"], answer:3,
      translation:"Để tiết kiệm chi phí ăn uống, tôi cố gắng không ăn ngoài.",
      explanation:"節約する: tiết kiệm. 減量 (giảm cân), 省略 (lược bớt), 短縮 (rút ngắn) không dùng với 食費 trong nghĩa này."},
    { id:"a4-5", passage:"", audioUrl:"", question:"18. 簡単にお金がもうかるというような話に、すぐ（ ）のはやめたほうがいい。", options:["駆け込む","触れ合う","寄りかかる","飛びつく"], answer:3,
      translation:"Với những chuyện kiểu như 'kiếm tiền dễ dàng', tốt hơn là đừng vội lao vào (nhào vào).",
      explanation:"飛びつく: nhào vào, lao vào một cách hấp tấp. 駆け込む (chạy vào), 触れ合う (giao tiếp), 寄りかかる (dựa vào) không hợp nghĩa."},
    { id:"a4-6", passage:"", audioUrl:"", question:"19. やりたい仕事内容の（ ）があったので、早速応募することにした。", options:["催促","入社","求人","収集"], answer:2,
      translation:"Vì có tuyển dụng (tin tuyển người) đúng công việc mình muốn làm nên tôi quyết định ứng tuyển ngay.",
      explanation:"求人 (きゅうじん): tuyển dụng, tuyển người. 催促 (giục giã), 入社 (vào công ty), 収集 (sưu tầm) không hợp."},
    { id:"a4-7", passage:"", audioUrl:"", question:"20. 友達だと思っていたのに、私のいないところで（ ）と私の悪口を言っていたなんてひどい。", options:["うとうと","こそこそ","ぶるぶる","じろじろ"], answer:1,
      translation:"Tưởng là bạn thân, vậy mà lại lén lút nói xấu tôi lúc tôi không có mặt, thật tệ.",
      explanation:"こそこそ: lén lút, vụng trộm. うとうと (lơ mơ ngủ gật), ぶるぶる (run rẩy), じろじろ (nhìn chằm chằm) không hợp."},
  ]
},
{
  tab: "文字・語彙", section: "問題5 言い換え類義",
  instruction: "＿＿＿の言葉に意味が最も近いものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a5-1", passage:"", audioUrl:"", question:"21. この建物を壊すのは<u>惜しい</u>。", options:["危ない","もったいない","めんどうくさい","難しい"], answer:1,
      translation:"Phá bỏ tòa nhà này thì thật đáng tiếc (phí).",
      explanation:"惜しい = もったいない: đáng tiếc, uổng phí. 危ない (nguy hiểm), めんどうくさい (phiền phức), 難しい (khó) không đúng."},
    { id:"a5-2", passage:"", audioUrl:"", question:"22. きちんと<u>テンポ</u>を合わせてください。", options:["長さ","高さ","大きさ","速さ"], answer:3,
      translation:"Hãy khớp nhịp độ (tempo) cho đúng.",
      explanation:"テンポ = 速さ: nhịp độ, tốc độ. 長さ (độ dài), 高さ (độ cao), 大きさ (độ lớn) không phải nghĩa của tempo."},
    { id:"a5-3", passage:"", audioUrl:"", question:"23. そのニュースは<u>たちまち</u>広まった。", options:["すぐに","次第に","確かに","意外に"], answer:0,
      translation:"Tin đó lan truyền một cách chớp nhoáng.",
      explanation:"たちまち = すぐに: tức thì, ngay lập tức. 次第に (dần dần) trái nghĩa; 確かに (chắc chắn), 意外に (bất ngờ) không hợp."},
    { id:"a5-4", passage:"", audioUrl:"", question:"24. 研究の<u>概要</u>を述べる。", options:["詳しい内容","大体の内容","主な目的","最終的な目的"], answer:1,
      translation:"Trình bày khái quát (tổng quan) về nghiên cứu.",
      explanation:"概要 = 大体の内容: nội dung khái quát, đại cương (không phải chi tiết). 詳しい内容 (chi tiết) trái nghĩa; các lựa chọn còn lại không đúng."},
    { id:"a5-5", passage:"", audioUrl:"", question:"25. あのときは<u>油断</u>していた。", options:["慌てていた","何も覚えていなかった","気を付けていなかった","迷っていた"], answer:2,
      translation:"Lúc đó tôi đã lơ là (không cẩn thận).",
      explanation:"油断する = 気を付けていない: lơ là, mất cảnh giác. 慌てていた (hoảng hốt), 何も覚えていなかった (không nhớ gì), 迷っていた (phân vân) không đúng."},
  ]
},
/* ================= TAB 2: 用法 ================= */
{
  tab: "用法", section: "問題6 用法",
  instruction: "次の言葉の使い方として最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a6-1", passage:"", audioUrl:"", question:"26. 早期",
      options:["夏休みの早期は旅行をして、その後は試験勉強をする予定だ","明日の飛行機は早期の便だから、朝5時に家を出なければならない","一人暮らしの早期は、料理などの失敗も多くて苦労した","医学の進歩によって、病気を早期の段階で見つけられるようになった"], answer:3,
      translation:"Nhờ tiến bộ của y học, người ta có thể phát hiện bệnh ở giai đoạn sớm.",
      explanation:"早期 = giai đoạn sớm (của sự việc). Dùng '早期の段階' (giai đoạn sớm) là hợp lý. Các câu khác dùng sai: 早期 không phải 'đầu kỳ nghỉ', 'chuyến bay sớm' hay 'thời gian đầu sống một mình'."},
    { id:"a6-2", passage:"", audioUrl:"", question:"27. 偉大",
      options:["山川さんのフランス語のスピーチはとても偉大だった","この国には偉大な画家がたくさんいる","あの家は、この辺りでいちばん偉大な家です","あの人は偉大な馬を何頭も飼っている"], answer:1,
      translation:"Đất nước này có rất nhiều họa sĩ vĩ đại.",
      explanation:"偉大 = vĩ đại, to lớn về tầm vóc/tinh thần. Dùng cho danh nhân (偉大な画家) là đúng. Không dùng cho bài phát biểu, ngôi nhà hay con ngựa."},
    { id:"a6-3", passage:"", audioUrl:"", question:"28. 印",
      options:["復習するときのために、大切な単語に赤のペンで印をつけた","係員が旗を上げたのを印に、選手たちは一斉に走りだした","角に病院がありますから、それを印に私の家まで来てください","運転する人は、交通の印の意味を全部知っていなければならない"], answer:0,
      translation:"Để tiện ôn tập, tôi đã đánh dấu những từ quan trọng bằng bút đỏ.",
      explanation:"印 (しるし) = dấu hiệu, dấu đánh dấu. '印をつける' = đánh dấu ✓. Các câu khác dùng sai: 'làm tín hiệu' hay 'biển báo' phải dùng từ khác (合図, 目印, 標識)."},
    { id:"a6-4", passage:"", audioUrl:"", question:"29. 続出",
      options:["昨日からの雪で、転んでけがをする人が続出している","ゆうべはせきが続出して、あまりよく眠れなかった","鈴木アナウンサーは、このテレビ番組に5年間続出している","この映画に関係する本や商品が、来週から続出するらしい"], answer:0,
      translation:"Vì tuyết từ hôm qua, người bị ngã bị thương liên tiếp xuất hiện (xảy ra dồn dập).",
      explanation:"続出する = xuất hiện/xảy ra liên tiếp (nhiều người/vật). 'けがをする人が続出' ✓. Không dùng cho cơn ho, người dẫn chương trình (liên tục xuất hiện → 出演し続ける), hay hàng hóa (発売される)."},
    { id:"a6-5", passage:"", audioUrl:"", question:"30. さまたげる",
      options:["掲示板のポスターが取れそうになっていたので、テープでさまたげた","原材料が高くなったが、製造方法を変えて、製品の値上げをさまたげた","関係のない発言で、会議の進行をさまたげないでください","工場内の事故をさまたげるために、作業の前に安全確認を行う"], answer:2,
      translation:"Xin đừng cản trở tiến trình cuộc họp bằng những phát biểu không liên quan.",
      explanation:"さまたげる (妨げる) = cản trở, ngăn cản sự diễn ra của việc gì. 進行をさまたげる ✓. Câu 1 dùng sai (nên là とめる), câu 2 sai (nên là 防ぐ/抑える), câu 4 nên dùng 防ぐ (phòng ngừa) chứ không phải 'cản trở'."},
  ]
},
/* ================= TAB 3: 文法 ================= */
{
  tab: "文法", section: "問題7 文の文法1",
  instruction: "次の文の（ ）に入れるのに最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a7-1", passage:"", audioUrl:"", question:"31. この小説は、物語が進む（ ）主人公の少年の心理が変化していくのが面白い。", options:["としても","とはいえ","につれて","にあたって"], answer:2,
      translation:"Cuốn tiểu thuyết này thú vị ở chỗ tâm lý của cậu bé nhân vật chính thay đổi theo sự tiến triển của câu chuyện.",
      explanation:"～につれて: càng... càng (thay đổi theo diễn biến). としても (dù rằng), とはいえ (dẫu nói vậy), にあたって (nhân dịp) không hợp nghĩa."},
    { id:"a7-2", passage:"", audioUrl:"", question:"32. 昨日行ったレストランは、味もサービスも最低だった。（ ）行きたくない。", options:["二度と","必ずしも","まさか","あまりに"], answer:0,
      translation:"Nhà hàng hôm qua đi thật tệ cả về vị lẫn dịch vụ. Tôi không muốn đến lần thứ hai nữa.",
      explanation:"二度と～ない: không bao giờ... lần nữa (phủ định mạnh). 必ずしも (chưa hẳn) cần đi với ～ない nhưng không hợp nghĩa; まさか (không thể nào), あまりに (quá mức) sai."},
    { id:"a7-3", passage:"", audioUrl:"", question:"33. 今回のオリンピックで、体操の青木選手は、メダルは獲得できなかった（ ）、素晴らしい演技を見せてくれた。", options:["からといいて","どころか","あげくに","ものの"], answer:3,
      translation:"Tại Olympic lần này, vận động viên thể dục dụng cụ Aoki dù không giành được huy chương nhưng đã cống hiến màn trình diễn tuyệt vời.",
      explanation:"～ものの: dù cho... nhưng (nhượng bộ, trái ngược nhẹ). どころか (chẳng những... mà còn, trái nghĩa hoàn toàn), あげくに (cuối cùng, kết cục xấu) không hợp."},
    { id:"a7-4", passage:"", audioUrl:"", question:"34. 60代の父が、趣味（ ）何歳から始めても遅くないだろうと言って最近ピアノ教室に通い始めた。", options:["としてだけ","としてなら","にとっては","にとっても"], answer:1,
      translation:"Bố tôi ngoài 60 nói \"nếu là sở thích thì bắt đầu ở tuổi nào cũng không muộn\" và gần đây đã bắt đầu đi học lớp piano.",
      explanation:"～としてなら: 'nếu với tư cách là... thì'. 趣味としてなら = nếu nói với tư cách sở thích thì. としてだけ/にとっては/にとっても không tạo câu hợp lý."},
    { id:"a7-5", passage:"", audioUrl:"", question:"35. 約束の時間に友人の家に着いてインターホンを押すと、慌てた様子で友人が玄関に出てきた。（ ）、パジャマ姿のままだった。", options:["起きるところだったら","起きるところらしく","起きたばかりだったら","起きたばかりらしく"], answer:3,
      translation:"Đến nhà bạn đúng giờ hẹn, bấm chuông thì bạn vội vàng ra cửa. Hình như vừa mới ngủ dậy, vẫn còn nguyên bộ đồ ngủ.",
      explanation:"～たばかりらしい: có vẻ vừa mới làm gì (suy đoán từ dấu hiệu: đang mặc đồ ngủ). らしく ở dạng trạng từ nối tiếp câu. ところだったら (nếu sắp...), だったら (nếu) không hợp."},
    { id:"a7-6", passage:"", audioUrl:"", question:"36. 「リマインド」とは、「再確認」の意味を持ち、「会議の日程が近づいてきたので、出席者にリマインドした。」（ ）使用されるビジネス用語である。", options:["というように","というような","ということのように","ということのような"], answer:0,
      translation:"'リマインド' có nghĩa là 'nhắc lại/xác nhận lại', là thuật ngữ kinh doanh được dùng theo cách như: 'Vì ngày họp sắp đến nên tôi đã nhắc lại cho người tham dự.'",
      explanation:"～というように: được dùng khi đưa ra ví dụ cụ thể về cách dùng. というような cần danh từ đứng sau; ということのように/のような thừa こと."},
    { id:"a7-7", passage:"", audioUrl:"", question:"37. 学校や病院では定期的に避難訓練が行われている。避難訓練を（ ）、火災などがあったときに落ち着いて行動できるからだ。", options:["しておくには","しているとしても","しておくことで","しているかというと"], answer:2,
      translation:"Ở trường học, bệnh viện thường xuyên tổ chức diễn tập sơ tán. Vì nhờ tiến hành diễn tập trước, khi xảy ra hỏa hoạn mới có thể hành động bình tĩnh.",
      explanation:"～しておくことで: nhờ việc làm trước (chuẩn bị sẵn) mà... ～ておく = làm trước cho sẵn. には/としても/かというと không tạo câu hợp lý."},
    { id:"a7-8", passage:"", audioUrl:"", question:"38. 明日、友達と映画を見に行くことになった。映画館で映画を見るのは、大学の時以来だから、約5年（ ）だ。", options:["まで","など","きり","ぶり"], answer:3,
      translation:"Mai tôi sẽ đi xem phim với bạn. Xem phim ở rạp lần trước là hồi đại học, nên đã khoảng 5 năm rồi mới xem lại.",
      explanation:"～ぶり: sau khoảng thời gian X (từ lần trước). 5年ぶり = sau 5 năm. まで (đến), など (v.v), きり (chỉ, từ đó về sau) không phù hợp."},
    { id:"a7-9", passage:"", audioUrl:"", question:"39. 睡眠には、体や脳にたまった疲労をとる効果がある。睡眠時間を削ることは、体や脳を回復させる大切な機会を奪うことに（ ）のだ。", options:["ほかならない","欠かせない","すぎない","限らない"], answer:0,
      translation:"Giấc ngủ có tác dụng giải tỏa mệt mỏi tích tụ trong cơ thể và não. Giảm thời gian ngủ chính là tước đi cơ hội quan trọng để phục hồi cơ thể và não.",
      explanation:"～にほかならない: chính là, không gì khác ngoài. ～に欠かせない (không thể thiếu) sai cấu trúc; ～にすぎない (chỉ là), ～に限らない (không chỉ giới hạn ở) sai nghĩa."},
    { id:"a7-10", passage:"", audioUrl:"", question:"40. (会社で)木村「山下さん、先ほどさくら銀行の南さんからお電話がありまして、今日中に連絡してほしい（ ）。」", options:["ことになりました","とのことでした","と助かるのですが","ようにしてください"], answer:1,
      translation:"(Tại công ty) Kimura: \"Anh Yamashita, lúc nãy có điện thoại của anh Minami ngân hàng Sakura, bảo là muốn anh liên lạc trong hôm nay.\"",
      explanation:"～とのことでした: truyền đạt lại lời của người khác (kính ngữ). ことになりました (đã được quyết định), と助かるのですが (sẽ được giúp), ようにしてください (xin hãy) không hợp vì đây là chuyển lời."},
    { id:"a7-11", passage:"", audioUrl:"", question:"41. 駅前に新しくできたカフェに友達を誘って行ってみたら、定休日だった。事前に確認しておく（ ）。", options:["しかなかった","ほどではなかった","べきだった","せいだった"], answer:2,
      translation:"Rủ bạn đến quán cà phê mới mở trước ga thì hóa ra hôm đó nghỉ định kỳ. Đáng lẽ nên kiểm tra trước.",
      explanation:"～べきだった: đáng lẽ nên... (hối tiếc về việc đã không làm). しかなかった (không còn cách nào khác), ほどではなかった (không đến mức), せいだった (tại vì) sai nghĩa."},
    { id:"a7-12", passage:"", audioUrl:"", question:"42. (インタビューで)選手「今回優勝できたのは、多くの方に（ ）。本当にありがとうございました。」", options:["応援してくださったおかげです","応援していただいたおかげです","応援してくださったことだと思います","応援していただいたことだと思います"], answer:1,
      translation:"(Phỏng vấn) VĐV: \"Lần này thắng giải là nhờ nhiều người đã cổ vũ cho tôi. Thật sự cảm ơn mọi người.\"",
      explanation:"～ていただいたおかげ: nhờ ơn (người khác làm cho mình) — いただく thể hiện nhận ơn, phù hợp lời cảm ơn. くださった cũng kính ngữ nhưng おかげ thường đi với いただいた; các lựa chọn với ことだと思います không hợp."},
  ]
},
{
  tab: "文法", section: "問題8 文の文法2 (sắp xếp - ★)",
  instruction: "次の文の★に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a8-1", passage:"", audioUrl:"", question:"43. 隣のクラスの友達とけんかをしてしまい、学校の廊下で ＿＿＿ ★ ＿＿＿ ＿＿＿ なくなってしまった。［1 こと / 2 すら / 3 目を合わせる / 4 すれ違っても］",
      options:["こと","すら","目を合わせる","すれ違っても"], answer:0,
      translation:"Vì cãi nhau với bạn lớp bên, nên đến cả chạm mắt khi lướt qua nhau ở hành lang trường cũng không còn nữa.",
      explanation:"Thứ tự đúng: すれ違っても（4）目を合わせる（3）こと（1）すら（2）→ \"すれ違っても目を合わせることすらなくなってしまった\"。★ vị trí thứ 3 = こと → đáp án 1. ～ことすら～ない: ngay cả việc... cũng không."},
    { id:"a8-2", passage:"", audioUrl:"", question:"44. このソファーは、それなりの大きさはあるが、見た目 ＿＿＿ ★ ＿＿＿ ＿＿＿ 楽に動かせる。［1 ほどの / 2 でも / 3 重さはないため / 4 一人］",
      options:["ほどの","でも","重さはないため","一人"], answer:3,
      translation:"Chiếc sofa này có kích thước khá lớn, nhưng vì không nặng như vẻ ngoài nên một mình cũng dễ dàng di chuyển.",
      explanation:"Thứ tự đúng: ほどの（1）重さはないため（3）一人（4）でも（2）→ \"見た目ほどの重さはないため、一人でも楽に動かせる\"。★ vị trí 4 = 一人 → đáp án 4. ～ほどの～はないため: vì không đến mức như..."},
    { id:"a8-3", passage:"", audioUrl:"", question:"45. 友達にスキー旅行に誘われている。返事を ＿＿＿ ★ ＿＿＿ ＿＿＿ まだ返事ができていない。［1 決まっていなくて / 2 仕事の予定が / 3 しなければ / 4 と思いながらも］",
      options:["決まっていなくて","仕事の予定が","しなければ","と思いながらも"], answer:1,
      translation:"Bạn rủ đi du lịch trượt tuyết. Dù nghĩ phải trả lời nhưng lịch trình công việc chưa chốt được nên vẫn chưa thể trả lời.",
      explanation:"Thứ tự đúng: しなければ（3）と思いながらも（4）仕事の予定が（2）決まっていなくて（1）→ \"返事をしなければと思いながらも、仕事の予定が決まっていなくてまだ返事ができていない\"。★ vị trí 3 = 仕事の予定が → đáp án 2."},
    { id:"a8-4", passage:"", audioUrl:"", question:"46. 私は、美術館では音声ガイドの機械を借りて、説明を聞きながら作品を鑑賞する。作品のどこに ＿＿＿ ★ ＿＿＿ ＿＿＿ その作品をより深く味わえるからだ。［1 わかると / 2 注目して / 3 いいのかが / 4 鑑賞したら］",
      options:["わかると","注目して","いいのかが","鑑賞したら"], answer:2,
      translation:"Ở bảo tàng, tôi thuê máy hướng dẫn âm thanh và ngắm tác phẩm trong khi nghe giải thích. Vì nếu biết nên chú ý vào chỗ nào khi ngắm thì có thể thưởng thức tác phẩm sâu sắc hơn.",
      explanation:"Thứ tự đúng: 注目して（2）鑑賞したら（4）いいのかが（3）わかると（1）→ \"作品のどこに注目して鑑賞したらいいのかがわかると...\"。★ vị trí 3 = いいのかが → đáp án 3. ～たらいいのかがわかる: biết nên làm thế nào."},
    { id:"a8-5", passage:"", audioUrl:"", question:"47. 雪が降っている ＿＿＿ ★ ＿＿＿ ＿＿＿ 風がほとんどないからだろう。［1 わりに / 2 のは / 3 寒く感じない / 4 そんなに］",
      options:["わりに","のは","寒く感じない","そんなに"], answer:2,
      translation:"Có lẽ là vì hầu như không có gió nên dù tuyết rơi vẫn không cảm thấy lạnh đến vậy.",
      explanation:"Thứ tự đúng: わりに（1）そんなに（4）寒く感じない（3）のは（2）→ \"雪が降っているわりに、そんなに寒く感じないのは、風がほとんどないからだろう\"。★ vị trí 3 = 寒く感じない → đáp án 3. ～わりに: tuy... nhưng (tương phản)."},
  ]
},
{
  tab: "文法", section: "問題9 文章の文法 (điền vào đoạn văn)",
  instruction: "次の文章を読んで、文章全体の内容を考えて、48から51の中に入る最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"a9-1", passage:"「香港」とは、香りを楽しむ日本の伝統文化です。私は、友人が香港の体験ができる教室に誘ってくれたのをきっかけに、初めて香港のことを知りました。私は普段から香水などで香りを楽しんでいるので、香港の体験も楽しむことができました。<br><br>香港は、「香木」と呼ばれる木の破片を熱し、その香りを楽しみます。「香木」【48】そのような名前の木がもともと存在するわけではありません。いくつかの種類の木の中で、様々な自然条件のもとで、年月の経過によって香りを発生させるようになった木をそう呼びます。人工的に生産できないため、大変貴重なものと【49】。<br><br>香港には600年以上の歴史がありますが、その存在はあまり知られていません。数に限りがある香木は、香港が広まり需要が増えすぎればなくなるおそれもあります。【50】、香港ではあまり多くの弟子を受け入れませんでした。香港がよく知られていないのは、そういった事情もあるそうです。<br><br>香港では、香りをかいて、じっくりと味わうことを「香りを聞く」と言います。香りに心を傾けて聞くことを基本に、香りを聞きながら古典文学を鑑賞したり、どれがどの香木の香りかを当てて楽しんだりもします。<br><br>繊細な香りを心の中でゆっくり味わうことを通して、私は「香りを聞く」という意味がわかったような気がしました。香水のように手軽ではありませんが、このような香りの楽しみ方も【51】。",
      audioUrl:"", question:"48. 「香木」【48】そのような名前の木がもともと存在するわけではありません。", options:["のように","のほかに","といっても","であっても"], answer:2,
      translation:"'Hương đạo' là văn hóa truyền thống thưởng thức hương thơm của Nhật Bản. Tôi biết đến hương đạo nhờ bạn rủ đến lớp trải nghiệm; vì vốn thích hương thơm như nước hoa nên tôi rất thích trải nghiệm này. Trong hương đạo, người ta hơ nóng mảnh gỗ gọi là 'hương mộc' để thưởng thức hương. Nói là 'hương mộc' nhưng vốn không có loại cây tên như vậy; người ta gọi như thế những cây thuộc nhiều loài khác nhau, qua thời gian và điều kiện tự nhiên đã sinh ra hương thơm. Vì không thể sản xuất nhân tạo nên nó được xem là vô cùng quý giá. Hương đạo có lịch sử hơn 600 năm nhưng ít ai biết đến; vì hương mộc có hạn, nếu hương đạo phổ biến và nhu cầu tăng quá mức thì có thể cạn kiệt. Vì vậy, hương đạo không nhận quá nhiều đệ tử — đó cũng là một lý do khiến nó ít được biết đến. Người ta nói 'nghe hương' (hươngを聞く) để chỉ việc hít hương và thưởng thức chậm rãi, có thể vừa nghe hương vừa thưởng thức văn học cổ hay đoán xem hương thuộc loại mộc nào. Qua việc thưởng thức hương tinh tế trong tâm, tôi cảm giác đã hiểu ý nghĩa của 'nghe hương'. Dù không tiện như nước hoa, nhưng tôi nghĩ cách thưởng hương như thế này cũng là điều tuyệt vời.",
      explanation:"【48】= といっても: 'nói là... nhưng thực ra'. '香木といっても、そのような名前の木がもともと存在するわけではありません' (nói là hương mộc nhưng vốn không có loại cây tên như vậy). のように/のほかに/であっても không hợp."},
    { id:"a9-2", passage:"", audioUrl:"", question:"49. 人工的に生産できないため、大変貴重なものと【49】。", options:["しておきます","されています","しておく点です","されている点です"], answer:1,
      translation:"(Đoạn văn: xem bản dịch ở câu 48) / Vì không thể sản xuất nhân tạo nên nó được xem là vô cùng quý giá.",
      explanation:"【49】= されています: thể bị động + ている, 'được coi là'. '貴重なものとされています' = được xem là quý giá. しておきます/しておく点です/されている点です không tự nhiên."},
    { id:"a9-3", passage:"", audioUrl:"", question:"50. 数に限りがある香木は、香港が広まり需要が増えすぎればなくなるおそれもあります。【50】、香港ではあまり多くの弟子を受け入れませんでした。", options:["一方","ちなみに","ところが","そのため"], answer:3,
      translation:"(Đoạn văn: xem bản dịch ở câu 48) / Vì hương mộc có hạn, nếu hương đạo phổ biến và nhu cầu tăng quá mức thì có thể cạn kiệt. Vì thế, hương đạo không nhận quá nhiều đệ tử.",
      explanation:"【50】= そのため: 'vì vậy' — nối quan hệ nhân quả (vì sợ cạn kiệt nên không nhận nhiều đệ tử). 一方 (mặt khác), ちなみに (nhân tiện), ところが (thế nhưng - trái ngược) không hợp."},
    { id:"a9-4", passage:"", audioUrl:"", question:"51. 香水のように手軽ではありませんが、このような香りの楽しみ方も【51】。", options:["いいものだと思います","いいと思ったのでしょう","よかったはずです","よかったのではありませんか"], answer:0,
      translation:"(Đoạn văn: xem bản dịch ở câu 48) / Dù không tiện như nước hoa, nhưng tôi nghĩ cách thưởng hương như thế này cũng là điều tốt đẹp.",
      explanation:"【51】= いいものだと思います: 'tôi nghĩ đó là điều hay'. Kết bài thể hiện đánh giá tích cực của tác giả ở hiện tại. だった/だったのでしょう không hợp thì và ngữ nghĩa."},
  ]
},
/* ================= TAB 4: 読解 ================= */
{
  tab: "読解", section: "問題10 内容理解・短文",
  instruction: "次の1から5の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b10-1", passage:"はじめから相手に期待することをやめられれば、怒りもイライラも生まれず、穏やかな気持ちで過ごすことができます。人に期待してイライラしながら過ごすか、努力して期待することを手放し穏やかに生きるか、これはあなた自身のことなので、コントロールが可能です。「期待しない」というとなんだかさみしいことをいっているように思う方もいるかもしれませんし、そうではありません。<br><br>多くの場合、周囲の環境や人間というのは、自分自身が変わることで面白いほど変化します。",
      audioUrl:"", question:"52. 筆者の考えに合うのはどれか。",
      options:["自分が変われば、相手も期待どおりに変わってくれる","自分をコントロールできれば、相手も変えられる","穏やかな気持ちで接すれば、相手といい関係が築ける","相手に期待しなければ、穏やかな気持ちでいられる"], answer:3,
      translation:"Nếu ngay từ đầu có thể bỏ việc kỳ vọng vào người khác, thì sự giận dữ hay bực bội cũng không sinh ra, và ta có thể sống với tâm trạng bình thản. Sống bực bội vì kỳ vọng vào người khác, hay nỗ lực buông bỏ kỳ vọng để sống bình thản — đây là chuyện của chính bạn nên có thể kiểm soát. 'Không kỳ vọng' nghe có vẻ buồn, nhưng thực ra không phải vậy. Trong nhiều trường hợp, môi trường và con người xung quanh sẽ thay đổi một cách thú vị khi chính bản thân bạn thay đổi.",
      explanation:"Đáp án 4. Đoạn đầu khẳng định ngừng kỳ vọng thì không sinh ra giận dữ, bực bội và có thể sống bình thản, đồng thời việc này 'có thể kiểm soát'. 1 sai vì bài không nói người khác sẽ đổi theo kỳ vọng của mình; 2,3 không được đề cập."},
    { id:"b10-2", passage:"総務課 ご担当者様<br><br>休憩室について、お願いがあってメールいたしました。<br><br>より多くの人が休憩室を利用できるように、先日テーブルといすを増やしていただきましたが、まだ昼食時に多くの人が利用できず不便を感じています。そのため、昼休みの間は会議室を開放していただけないでしょうか。そうすれば、より多くの人がそこで休憩できるようになると思います。<br><br>ご検討をお願いいたします。<br><br>営業第1グループ 大月友代",
      audioUrl:"", question:"53. このメールで伝えたいことは何か。",
      options:["会議室のテーブルといすをもっと増やしてほしい","昼休みに、会議室を休憩室として使えるようにしてほしい","昼休みには、昼食を取る人に休憩室を優先して使わせてほしい","昼休み以外にも、会議室で休憩できるようにしてほしい"], answer:1,
      translation:"Kính gửi ban Tổng vụ. Tôi gửi mail để nhờ về phòng nghỉ. Trước đây nhờ các anh chị tăng bàn ghế để nhiều người dùng phòng nghỉ hơn, nhưng giờ nghỉ trưa vẫn nhiều người không sử dụng được, thấy bất tiện. Vì vậy, xin hỏi có thể mở phòng họp trong giờ nghỉ trưa không? Như vậy nhiều người sẽ nghỉ được ở đó hơn. Kính mong xem xét. — Daitsuki Tomoyo, nhóm 1 kinh doanh",
      explanation:"Đáp án 2. Nội dung chính của mail là đề nghị mở phòng họp (会議室) làm nơi nghỉ trưa. 1 sai (không xin thêm bàn ghế), 3, 4 không có trong mail."},
    { id:"b10-3", passage:"条件が違えば、勝者が敗者になり、敗者が勝者になるのが自然の生物社会です。どの生物もすべての環境条件で競争の勝者になることはできません。生態学の研究が示すのは多様な環境の重要性です。生物は競争があることで多様な環境の中に自分に適した環境を見つけることができます。<br><br>競争は敗者を排除するプロセスではなく、多様な環境の中にそれぞれの生物の居場所をつくり出すプロセスといってもよいかもしれません。",
      audioUrl:"", question:"54. 生物について、筆者の考えに合うのはどれか。",
      options:["ある環境で競争に負けても、自分に合った別の環境で生き残れる","多様な環境の中で自らを変化させなければ、競争に勝てない","競争に負けた生物は、場所を変えずにそこで生きられるように変化する","競争に勝たなければ、すべての環境条件で生き残れない"], answer:0,
      translation:"Nếu điều kiện khác nhau, kẻ thắng thành kẻ bại và ngược lại — đó là thế giới sinh vật tự nhiên. Không sinh vật nào có thể thắng trong mọi điều kiện môi trường. Nghiên cứu sinh thái học cho thấy tầm quan trọng của sự đa dạng môi trường: nhờ có cạnh tranh, sinh vật tìm được môi trường phù hợp với mình trong môi trường đa dạng. Có thể nói cạnh tranh không phải quá trình loại bỏ kẻ thua, mà là quá trình tạo ra chỗ đứng cho từng sinh vật trong môi trường đa dạng.",
      explanation:"Đáp án 1. Bài nói thua ở môi trường này vẫn có thể sống được ở môi trường khác phù hợp hơn nhờ môi trường đa dạng. 2,3,4 trái với lập luận của tác giả."},
    { id:"b10-4", passage:"高山かおり様<br><br>PC フォレスト西山店の合田です。<br><br>画面の修理のためルニ社製のノートパソコンをお預かりしておりますが、点検したところ電源部分の部品にも問題があり、接続状態が悪くなっていることが分かりました。このままですと急に電源が入らなくなる可能性がありますので、部品の交換をお勧めいたします。<br><br>その場合、追加料金が2万円かかり、お返しは6月10日以降になります。<br><br>画面の修理は6月5日に完了しますので、電源の修理を希望されない場合には、予定どおりお返しできます。<br><br>お忙しいところ恐縮ですが、ご連絡をお待ちしております。<br><br>PC フォレスト西山店 担当：合田 英子 support_hm@peforest.co.jp",
      audioUrl:"", question:"55. このメールで店員が問い合わせていることは何か。",
      options:["電源の状態が悪くなる可能性があるが、画面の修理をするかどうか","追加で料金と時間がかかるが、電源の修理もするかどうか","追加で料金がかかるが、電源の修理を6月5日までに終えるかどうか","6月5日に画面と電源の修理は完了するが、いつ受け取りに来るか"], answer:1,
      translation:"Kính gửi chị Takayama Kaori. Tôi là Gōda ở PC Forest chi nhánh Nishiyama. Chúng tôi đang giữ laptop hãng Rune để sửa màn hình, nhưng khi kiểm tra phát hiện linh kiện phần nguồn cũng có vấn đề, kết nối đang kém. Cứ để vậy có thể máy đột ngột không bật nguồn, nên tôi khuyên nên thay linh kiện. Trong trường hợp đó, phí thêm 2 vạn yên và trả máy sau ngày 10/6. Sửa màn hình sẽ xong ngày 5/6, nếu chị không muốn sửa nguồn thì trả máy đúng hẹn. Xin lỗi vì phiền, mong chị liên hệ lại.",
      explanation:"Đáp án 2. Nhân viên hỏi: có muốn sửa thêm phần nguồn không (sẽ tốn thêm 2 vạn yên và lâu hơn). 1 sai (hỏi về sửa màn hình), 3 sai (không hẹn xong trước 5/6), 4 sai (không hỏi ngày nhận)."},
    { id:"b10-5", passage:"弱い立場にあるという点で、未来の世代ほど弱いものはない。何しろ、どんなにひどいことをされても、まだ生まれていない生命は、抗議の声をあげることもできないのだから。それをいいことに今生きてる世代は、未来の世代が生きていくための絶対条件となる環境を壊し、彼らが利用する分の資源まで使い果たそうとしている。いったいこれ以上、フェアの精神に反することがあるだろうか。",
      audioUrl:"", question:"56. 生きている世代に対して、筆者が言いたいことは何か。",
      options:["今生きている世代があげている反対や怒りの声を聞くべきだ","今生きている世代にも声があげられない人がいることを認めるべきだ","未来の世代が生きていくために、必要な資源を見つけるべきだ","声をあげられない未来の世代のことを考え、行動を改めるべきだ"], answer:3,
      translation:"Xét về vị thế yếu thế, không ai yếu hơn thế hệ tương lai. Vì dù có bị đối xử tệ đến đâu, sinh mệnh chưa ra đời cũng không thể lên tiếng phản đối. Lợi dụng điều đó, thế hệ đang sống đang phá hủy môi trường — điều kiện tuyệt đối để thế hệ tương lai tồn tại — và dùng cạn cả tài nguyên thuộc phần của họ. Còn gì trái với tinh thần công bằng hơn thế nữa?",
      explanation:"Đáp án 4. Tác giả phê phán thế hệ hiện tại chỉ vì người chưa sinh không thể lên tiếng mà phá môi trường, dùng cạn tài nguyên; vì vậy cần nghĩ cho thế hệ tương lai và thay đổi hành vi. 1,2,3 lệch trọng tâm."},
  ]
},
{
  tab: "読解", section: "問題11 内容理解・中文",
  instruction: "次の1から4の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b11-1", passage:"読み聞かせの時には、まず子どもたちに表紙を見せます。そして、ゆっくりと書名と著者や画家の名前を読み上げます。表紙をめくると、見返し紙が出てきて、それは無地の色紙であったり、または本の中身とかかわる絵があったりするのですが、それもゆっくりと見せます。ここは、その本の中身に入る前の気持ちの準備のためのページなのです。それから扉のページがあって、開けるとその本の世界が広がります。<br><br>つまり、すぐに本の中身に飛び込んでゆくのではなく、じっくりと本を見せて、そのお話の世界に子どもたちを案内する。ただ子どもたちがおもしろがればいいのではなく、一人ひとりがその世界に入っていく、そうして自分で何かを感じ取る。それが図書館でのお話し会なのです。<br><br>その時、語り手が主役ではありません。著者が読者に伝えたいことを、その代わりになって伝える仕事ですから、大げさな身振りや声色よりも、ごく自然な話し方と、それに伴う控えめな身振りで、著者の思いを伝えようとします。（中略）<br><br>そこで、司書は、読み聞かせやお話をする前に、その本を何度も読みこんで、この著者が何をいおうとするのかを考え、どこに間を入れたらよいのかを考えます。それから練習に入ります。読み聞かせの場合も、本文をほとんど暗記するほどに読みこむことが必要とされています。子どもと本とを結びつけるのには、そういう配慮と厳しい訓練が必要なのです。",
      audioUrl:"", question:"57. 読み聞かせの前に、語り手は子どもたちに対してどんな工夫をしているか。",
      options:["本の世界に入れるように、時間をかけて表紙から見せていく","本の中身に飛び込めるように、表紙と絵の多いページを見せる","関心を高めるために、表紙を見せながら多くの情報を伝える","自分で何かを感じ取れるように、表紙から自分でめくらせる"], answer:0,
      translation:"Khi đọc truyện, trước tiên cho trẻ xem bìa sách, chậm rãi đọc tên sách và tên tác giả/họa sĩ. Lật bìa là trang giấy lót — có thể trơn hoặc có hình liên quan nội dung — cũng cho xem từ từ. Đây là trang chuẩn bị tâm lý trước khi bước vào nội dung sách. Rồi đến trang tựa, mở ra là thế giới của cuốn sách. Tức là không lao ngay vào nội dung mà chậm rãi giới thiệu sách, dẫn trẻ vào thế giới câu chuyện. Không chỉ đơn giản là trẻ thấy vui, mà từng đứa trẻ tự bước vào thế giới đó và tự cảm nhận điều gì đó — đó mới là buổi đọc truyện ở thư viện. Người kể không phải nhân vật chính; vì đây là công việc truyền đạt thay tác giả điều muốn gửi đến người đọc, nên thay vì cử chỉ hoa mỹ hay giọng điệu cường điệu, người kể truyền tải ý tác giả bằng cách kể tự nhiên và cử chỉ kín đáo. Vì vậy, thủ thư đọc đi đọc lại cuốn sách nhiều lần trước khi kể, suy nghĩ tác giả muốn nói gì, ngắt nghỉ ở đâu rồi mới luyện tập. Kể cả đọc truyện, cần đọc nhuần nhuyễn gần như thuộc lòng. Để kết nối trẻ em với sách cần sự cân nhắc và rèn luyện nghiêm túc như vậy.",
      explanation:"Đáp án 1. Đoạn đầu mô tả thủ thư chậm rãi cho xem từ bìa, giấy lót, trang tựa để 'chuẩn bị tâm lý', dẫn trẻ vào thế giới sách. 2 sai ('lao vào nội dung'), 3 sai (không 'nhiều thông tin'), 4 sai (không cho trẻ tự lật)."},
    { id:"b11-2", passage:"", audioUrl:"", question:"58. 筆者によると、本を読み聞かせるために語り手はどんな準備をしているか。",
      options:["子どもが楽しみながら聞けるように、子どもの興味を知る","著者の思いが伝わるように、声の強弱をつけて読む練習をする","著者の思いを届けるために、何度も読みこんで内容を理解し練習する","著者が何をいおうとしているのかを考え、内容を言い換えられるようにする"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 57)",
      explanation:"Đáp án 3. Đoạn cuối: thủ thư đọc đi đọc lại cuốn sách nhiều lần, suy nghĩ tác giả muốn nói gì, ngắt nghỉ ở đâu, rồi luyện tập đến mức gần thuộc lòng. 1,2,4 không được nhắc đến."},
    { id:"b11-3", passage:"いま、ハーバードやMIT（マサチューセッツ工科大学）、あるいは日本の京都大学でも、授業内容のインターネットでの公開を始めている。せっかく大学に入って授業料も支払っているのに、その内容がインターネットで見られるというのは、どういうことだろう。<br><br>要するに、もはやそこで得られる知識や情報＝コンテンツは世界共有になってしまったのだ。かつては、東京に行かなければ得られない知識、あるいはバリやニューヨークまで行かなければ得られない情報というものが確かにあった。しかし、いまや、どんな情報も知識も、インターネットで簡単に手に入れることができる。そのことを大前提にしつつ、それでも「ここで、共に、学ぶ」ことが重要な時代になってきたのだ。もはや、学校の、少なくとも大学以上の高等教育機関の存在価値は、新しい知識や情報を得る場所としてではなく、共に学び、議論し、共同作業を行うという点だけになった。<br><br>だとするならば、大学側も、どのような学びの共同体をそこに実現するかを、きちんと公表していかなければならない。どんな学生に来て欲しいのかを示すと共に、どんな教職員がそこにいて、そこにどのような「学び」が実現するのかを、はっきりと示していかなければならない。",
      audioUrl:"", question:"59. いまの大学について、筆者の考えに合うのはどれか。",
      options:["授業内容の公開によって、授業料を支払う意味がなくなった","どこにいても学べるようになって、大学を選ぶ必要がなくなった","インターネットの発達で、世界で同じレベルの教育ができるようになった","インターネットの普及で、知識や情報を得る場所としての価値はなくなった"], answer:3,
      translation:"Harvard, MIT hay Đại học Kyoto của Nhật đang bắt đầu công khai nội dung bài giảng trên internet. Đã trả học phí để vào đại học vậy mà nội dung lại xem được trên mạng — là sao? Tóm lại, kiến thức/thông tin (content) thu được ở đó đã trở thành tài sản chung của thế giới. Ngày xưa có những kiến thức phải đến Tokyo, hay đến Bali, New York mới có được; nhưng giờ mọi thông tin kiến thức đều có thể lấy dễ dàng qua internet. Trên nền tảng đó, thời đại mà 'cùng nhau học ở đây' vẫn quan trọng đã đến. Giá trị tồn tại của trường học — ít nhất là các cơ sở giáo dục đại học trở lên — không còn là nơi thu nhận kiến thức mới mà chỉ còn ở điểm cùng nhau học, thảo luận và làm việc chung. Nếu vậy, phía đại học phải công bố rõ ràng mình sẽ hiện thực hóa cộng đồng học tập như thế nào: cho biết muốn sinh viên nào đến, có đội ngũ giảng viên nhân viên nào, và 'việc học' nào được hiện thực ở đó.",
      explanation:"Đáp án 4. Tác giả nói giá trị của trường không còn là nơi thu nhận kiến thức mới (đã có internet) mà chỉ còn là cộng đồng cùng học. 1,2,3 không phải ý tác giả (vẫn cần học phí, vẫn cần chọn trường)."},
    { id:"b11-4", passage:"", audioUrl:"", question:"60. 大学について、筆者が言いたいことは何か。",
      options:["学生が求めている学びの共同体を実現するべきだ","ほかでは得られない情報や知識を提供する必要がある","学びの共同体として、何ができるかを具体的に示す必要がある","どのような学びの共同体を作るかを、学生自身にも考えさせるべきだ"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 59)",
      explanation:"Đáp án 3. Đoạn cuối: trường phải 'công bố rõ ràng' sẽ hiện thực hóa cộng đồng học tập như thế nào — sinh viên nào, giáo viên nào, 'việc học' nào. 1,2,4 không khớp."},
    { id:"b11-5", passage:"自分を見失わないためのコツとして、ぼくは「何でも正直に話をする」ようにしています。<br><br>その場で波風を立てずに、聞き心地がいいことだけを他人に言っていたら、同じようなことを心の中で自分に対しても言うようになってしまいます。長期的に見て、「本心を口にしない」ことの悪影響は、非常に大きいのです。自分についたウソは、気付かないうちにそれがウソか本当かもわからなくなる。自分を慰めるために言っているのか、現実がそうなのか、区別がつかなくなります。これが怖いのです。（中略）<br><br>自分にウソをつかないことのメリットはもう一つあります。「記憶のコスト」が低くなるということです。<br><br>その場の空気で調子を合わせていると、「自分がどこで何を言ったか」を記憶しておかなければならない。たくさんの案件を同時進行で動かしていると、自分がどのような基準で、どう判断したかを記憶することは、すごく大変な作業になります。<br><br>ただ正直ということを最優先していれば、忘れてしまっている案件でも、ほぼ同じ決断に辿り着くことができます。まわりに合わせて自分にウソをついていたりすると、まったく逆のことを言ってしまったりして、判断がぶれるのです。",
      audioUrl:"", question:"61. 筆者によると、自分の本当の気持ちを言わないでいるとどうなるか。",
      options:["自分が本当だと思っていることがわからなくくなる","自分の本当の気持ちを常に隠すようになる","他人と自分の気持ちの区別がつきにくくなる","他人との関係がうまくいかなくなる"], answer:0,
      translation:"Bí quyết để không đánh mất chính mình, tôi luôn 'nói thật mọi điều'. Nếu chỉ nói những điều dễ nghe, không làm sóng gió cho hợp chuyện, thì trong lòng cũng sẽ tự nói với mình những điều tương tự. Về lâu dài, tác hại của việc 'không nói lòng thật' là rất lớn. Lời nói dối với chính mình, không biết từ lúc nào sẽ không phân biệt được là dối hay thật. Không phân biệt được là đang tự an ủi mình hay thực tế đúng như vậy — điều này thật đáng sợ. Lợi ích khác của việc không nói dối bản thân là 'chi phí ghi nhớ' giảm xuống. Nếu cứ xuôi theo không khí thì phải nhớ 'mình đã nói gì ở đâu'; khi xử lý nhiều việc song song, nhớ mình đã đánh giá theo tiêu chuẩn nào là việc rất vất vả. Nhưng nếu đặt sự trung thực lên hàng đầu, dù quên mất vụ việc, ta vẫn đi đến gần như cùng một quyết định. Còn nếu nói dối để hợp với xung quanh thì có thể nói điều trái ngược hẳn, khiến phán đoán dao động.",
      explanation:"Đáp án 1. Đoạn 2: nếu không nói lòng thật, lời nói dối với chính mình khiến không phân biệt được đâu là thật — 'không biết điều mình cho là thật nữa'. 2,3,4 không được nêu."},
    { id:"b11-6", passage:"", audioUrl:"", question:"62. 「記憶のコスト」が低くなるとはどういうことか。",
      options:["判断の基準を覚えていなくても、その場の空気に合わせて判断ができる","判断の基準だけ覚えていれば、正しい決断ができる","自分が言ったことを覚えていなくても、同じ決断ができる","正直に話したことだけを思い出せば、同じ決断ができる"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 61)",
      explanation:"Đáp án 3. 'Chi phí ghi nhớ thấp' = vì luôn trung thực nên dù quên mất vụ việc, vẫn đi đến gần như cùng một quyết định; không cần nhớ mình đã nói gì ở đâu. 1,2,4 sai."},
    { id:"b11-7", passage:"ポートフォリオを作ることには大きく二つの意味がある。まず自分のため、そしてもう一つは他者に見せる（プレゼンテーションする）ためだ。写真を撮り続けるうちに、だんだん自分が何をしようとしているのかが見えてくる。被写体について漠然とした認識しか持てなかったのが、はっきりと焦点が絞られてきて、このやり方でいいのだという自信が芽生えてくる。そうなったらポートフォリオを作ってみるといい。<br><br>よく「形にしてみないとわからない」というが、これは本当だと思う。作品をまとめることで、自信が確信に変わることがよくあるからだ。逆にポートフォリオにしてみると、自分の写真の弱点もよく見えてくる。撮影中には見過ごしていたことが、後で冷静に見直すとくっきりと浮かび上がってくるのだ。欠けていたものを修整することで、作品をさらによくすることができるだろう。<br><br>他人に見せるというのも大事なことだ。写真をどこかで発表したいとか、写真家として仕事をしたいという人は当然だが、そこまで考えていなくてもポートフォリオを人に見せるのはとても有意義だと思う。自分の作品がどれくらいのレベルにあるのか、どの程度のインパクトを持っているのか客観的に判断するきっかけになるからだ。（中略）<br><br>作品は他者にきちんと届いて初めて価値を持つ。自己完結した小さな世界が、受け手とのキャッチボールでより大きなものになっていく。その第一歩としてポートフォリオを誰かに見せてみよう。",
      audioUrl:"", question:"63. 筆者によると、いつポートフォリオを作ってみるのがいいか。",
      options:["自分の写真を他人に見てもらって、自信を持ちたいと思ったとき","自分の撮りたい写真が明確になって、自信がついてきたとき","対象をさまざまな捉え方で撮れるようになったとき","いい写真が撮れて、人に見せたいと思ったとき"], answer:1,
      translation:"Làm portfolio có hai ý nghĩa lớn: một là cho bản thân, hai là để trình bày với người khác. Càng chụp nhiều, ta càng thấy rõ mình đang muốn làm gì; từ nhận thức mơ hồ về đối tượng dần thu hẹp tiêu điểm và nảy sinh tự tin 'làm theo cách này là được'. Khi đó hãy thử làm portfolio. Người ta hay nói 'không làm thành hình thì không hiểu được' — tôi thấy đúng. Vì nhờ tổng hợp tác phẩm, sự tự tin thường chuyển thành niềm tin chắc chắn. Ngược lại, khi làm portfolio, điểm yếu của ảnh mình cũng hiện rõ; những điều bỏ qua lúc chụp, nhìn lại lạnh lùng sau đó sẽ nổi bật rõ rệt. Bù đắp phần thiếu có thể làm tác phẩm tốt hơn. Việc cho người khác xem cũng quan trọng: dù chưa nghĩ đến chuyện xuất bản hay làm nghề, cho người khác xem portfolio rất có ý nghĩa vì là cơ hội để đánh giá khách quan trình độ và sức ảnh hưởng của tác phẩm. Tác phẩm chỉ có giá trị khi đến được với người khác; thế giới nhỏ tự khép kín sẽ lớn hơn nhờ trò chuyện với người nhận. Bước đầu tiên — hãy cho ai đó xem portfolio của mình.",
      explanation:"Đáp án 2. Đoạn đầu: khi 'chủ thể đã rõ ràng và tự tin nảy sinh' ('やり方でいいのだという自信が芽生えてくる') thì nên làm portfolio. 1,3,4 không khớp."},
    { id:"b11-8", passage:"", audioUrl:"", question:"64. 筆者によると、ポートフォリオを他人に見せるといいのはなぜか。",
      options:["自分が写真家になれるレベルかどうかがわかるから","作品を他人が正しく理解したかどうかがわかるから","作品の欠点がわかり、新しい撮り方ができるから","作品に対する他人の評価を知ることができるから"], answer:3,
      translation:"(Bài đọc: xem bản dịch ở câu 63)",
      explanation:"Đáp án 4. Đoạn 3: cho người khác xem là cơ hội 'đánh giá khách quan tác phẩm của mình ở mức nào, có sức ảnh hưởng ra sao' (nhận được đánh giá từ người khác). 1,2,3 không khớp."},
  ]
},
{
  tab: "読解", section: "問題12 統合理解 (đối chiếu 2 văn bản A/B)",
  instruction: "次のAからBの文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b12-1", passage:"【A】会社で働いていれば、部下に仕事を教える立場になることがあるだろう。そんなとき、私はできるだけ社内用語や専門用語を使わずに、誰が聞いても分かる言葉で説明するようにしている。教える側と教えられる側の知識や経験には大きな差があるからだ。<br><br>いずれ覚えなければならないからと思って最初から難しい言葉を使って説明すると、仕事自体が難しいという印象を与え、部下が仕事を理解しようという意欲を失ってしまう。大切なのは、部下の能力に応じた教え方をすることではないだろうか。部下にとって分かりやすい言葉で仕事をしっかり理解させ、やる気を引き出すことは、上司の大事な役目だ。<br><br>【B】部下に仕事を教えるとき、多くの仕事を一気に教え込もうとする人がいる。早く仕事を覚えてほしいという気持ちは理解できるが、仕事を覚える側の負担を考えていないのは問題だ。仕事を正確に覚えてもらうには、部下がどんな知識や経験を持ち、何ができるのかを考えて教えることが大切だ。<br><br>私が実践しているのは、仕事を一度に教えようとしないで、すぐに担当してもらう仕事に絞って教えることだ。教える内容を限定すれば、部下が難しいと感じることは時間をかけて説明したり、部下が得意なことは一人でやらせてみたりして、部下のレベルに合わせた内容やスピードで教えることができる。部下の立場に立って教えることが、確実に仕事を覚えてもらうための近道だ。",
      audioUrl:"", question:"65. AとBは、それぞれ仕事をどのように教えていると述べているか。",
      options:["AもBも、難しい言葉を使わずに簡単な言葉で教えていると述べている","AもBも、部下が担当する仕事と一緒に、関連する仕事も教えていると述べている","Aは部下がすぐに覚えられる仕事を先に教えていると述べ、Bは仕事の内容を絞って教えていると述べている","Aは部下が理解しやすい言葉を使って教えていると述べ、Bは部下が担当する仕事に限定して教えていると述べている"], answer:3,
      translation:"【A】Làm ở công ty, có khi ta ở vị thế dạy việc cho cấp dưới. Khi đó tôi cố không dùng thuật ngữ nội bộ/chuyên môn mà giải thích bằng lời ai nghe cũng hiểu, vì kiến thức & kinh nghiệm giữa người dạy và người học chênh lệch lớn. Nếu ngay từ đầu dùng từ khó vì nghĩ 'rồi cũng phải học', ấn tượng 'công việc khó' sẽ khiến cấp dưới mất hứng thú tìm hiểu. Quan trọng là cách dạy phù hợp năng lực cấp dưới; dùng lời dễ hiểu để họ hiểu rõ việc và tạo động lực là vai trò quan trọng của cấp trên.<br>【B】Có người khi dạy việc cho cấp dưới lại nhồi nhét nhiều việc cùng lúc. Hiểu ý muốn họ học nhanh, nhưng không nghĩ đến gánh nặng của người học là vấn đề. Để học chính xác, phải cân nhắc cấp dưới có kiến thức/kinh nghiệm gì, làm được gì. Tôi thực hành cách không dạy mọi thứ cùng lúc mà chỉ dạy việc họ sẽ được giao phụ trách ngay. Giới hạn nội dung dạy thì có thể giải thích kỹ phần khó, cho tự làm phần họ giỏi, dạy theo nội dung và tốc độ phù hợp trình độ. Dạy đứng ở vị thế cấp dưới là đường ngắn nhất để họ nhớ việc chắc chắn.",
      explanation:"Đáp án 4. A: dạy bằng từ ngữ dễ hiểu, tránh thuật ngữ; B: chỉ dạy giới hạn công việc sẽ được giao. 1 (B không nói về từ ngữ), 2 (ngược lại), 3 (A không nói 'dạy việc dễ trước') sai."},
    { id:"b12-2", passage:"", audioUrl:"", question:"66. 仕事を教える際に重要なこととして、AとBが共通して述べていることは何か。",
      options:["部下のやる気を引き出すこと","部下の長所を見つけて伸ばすこと","部下の能力に合わせて指導すること","部下とのよい関係を維持すること"], answer:2,
      translation:"(Bài đọc: xem bản dịch ở câu 65)",
      explanation:"Đáp án 3. A: '部下の能力に応じた教え方'; B: '部下のレベルに合わせた内容やスピードで教える' — cả hai đều nhấn mạnh dạy theo năng lực cấp dưới. 1,2,4 chỉ có ở một bài hoặc không có."},
  ]
},
{
  tab: "読解", section: "問題13 主張理解・長文",
  instruction: "次の文章を読んで、後の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b13-1", passage:"大きな感動をあたえてくれた場所には、またいきたくなる。できれば、その場所にいつまでも居つづけたい。そう思うのは、人の自然な感情だ。<br><br>宇宙飛行士の毛利衛さんにとっては、「宇宙」が、その場所だった。<br><br>スペース・シャトルでの初めての宇宙飛行から帰還してからは、しばらくは講演活動やマネージメントの仕事をしていたらしいが、そんな生活が、物足りなくてしょうがない。ひとつの夢を果たし終えて、自分の人生まで終わってしまったように思えてくる。「もう一度、宇宙へいきたい」という気持ちがわいてくるのも自然な感情だろう。<br><br>張り詰めた緊張感のある生活を、もう一度送りたい。宇宙から地球を見たときの、その感動を、もう一度味わいたい……<br><br>二度目の宇宙飛行への挑戦を決心したとき、毛利さんはすでに四十八歳になっていた。すでに若くはない人間にとってはつらい訓練でもあったが、どうにか乗り越えて、ふたたび宇宙へ旅立った。<br><br>毛利さんばかりではないように思う。プロ野球選手は、いつまでもグラウンドに立ちつづけたいと思うだろうし、サラリーマンは定年になっても、職場から離れがたく思うものだろう。その場所を去らなければならない「とき」がやってくる。毛利さんも、じつはそのことは、二度目の訓練を受けているときから薄々感じていた。体力も反射神経も、もう若い人にはかなわない。<br><br>宇宙飛行は、希望すればだれでもいけるというものではない。スペース・シャトルには「定員」があるし、選ばれなければ宇宙へはいけない。<br><br>「三度目」はないかもしれない。後ろ髪を引かれるような寂しさはあるが、しかし、いまの毛利さんには、「なにがなんでも、もう一度」という強いこだわりはないのだという。<br><br>それは、新しい「生きがい」を見つけることができたからだそうだ。自分には経験がある。知識もある。いつまでも若い人と競うのではなく、自分が得てきたものを若い人たちに伝えてゆく「喜び」もあるのではないか。<br><br>自分の夢を追い求める人生から、次の世代の人たちの夢の応援する人生へ。たしかに、そのような発想の転換ができれば、新しい「生きがい」を見つけるのも早そうだ。<br><br>次の世代に夢をつなげていくのは、「老兵」の重要な仕事なのである。",
      audioUrl:"", question:"67. 筆者によると、初めての宇宙飛行から帰ってきたあと、毛利さんはどのように感じていたか。",
      options:["宇宙飛行のような大きな夢を持って生活を送りたい","宇宙でやり残したもうひとつの夢を果たしたい","経験したことを生かすために、また宇宙へいきたい","緊張感や感動を得るために、また宇宙へいきたい"], answer:3,
      translation:"Nơi từng cho ta cảm động lớn thì ta lại muốn quay lại, thậm chí muốn ở mãi đó — đó là tình cảm tự nhiên của con người. Với phi hành gia Mōri Mamoru, 'vũ trụ' là nơi như vậy. Sau chuyến bay đầu tiên, ông làm công tác diễn thuyết, quản lý nhưng cuộc sống đó thiếu thốn gì đó không chịu nổi; cảm giác như hoàn thành một giấc mơ rồi cả cuộc đời cũng kết thúc. 'Muốn lên vũ trụ một lần nữa' cũng là cảm xúc tự nhiên. Muốn sống lại cuộc sống căng thẳng nghẹt thở, muốn nếm lại cảm động khi nhìn Trái Đất từ vũ trụ... Khi quyết định thử thách lần hai, ông đã 48 tuổi; huấn luyện gian khổ với người không còn trẻ nhưng ông vượt qua và lên đường lần nữa. Không chỉ Mōri: cầu thủ bóng chày muốn mãi đứng trên sân, nhân viên văn phòng đến tuổi nghỉ hưu vẫn khó rời công sở. Đến 'lúc' phải rời khỏi nơi đó — Mōri cũng linh cảm điều này từ hồi huấn luyện lần hai: thể lực và phản xạ không còn thắng được người trẻ. Vũ trụ không phải muốn là đi; tàu con thoi có hạn chỗ, không được chọn thì không bay được. Có thể không có 'lần thứ ba'. Dù có nỗi buồn luyến tiếc, nhưng hiện tại Mōri không còn sự cố chấp 'bằng mọi giá thêm lần nữa' — vì ông đã tìm được 'lẽ sống' mới: mình có kinh nghiệm, có kiến thức; thay vì mãi tranh đua với người trẻ, chẳng phải có niềm vui truyền lại những gì đã có cho thế hệ trẻ sao? Từ cuộc đời theo đuổi giấc mơ của mình sang cuộc đời ủng hộ giấc mơ của thế hệ kế tiếp — nếu chuyển đổi tư duy như vậy thì tìm lẽ sống mới cũng nhanh. Nối tiếp giấc mơ cho thế hệ sau là việc quan trọng của 'lão binh'.",
      explanation:"Đáp án 4. Đoạn 3–4: sau lần bay đầu, ông cảm thấy cuộc sống thiếu thốn, muốn 'sống lại không khí căng thẳng' và 'nếm lại cảm động' — tức vì muốn có lại cảm giác hồi hộp và xúc động. 1,2,3 không được nêu."},
    { id:"b13-2", passage:"", audioUrl:"", question:"68. 筆者によると、二度目の訓練を受けているとき、毛利さんはどのように感じていたか。",
      options:["自分が輝ける場所をふたたび見つけられないかもしれない","いつかは活躍していた場所から離れなくてはならない","人は自分の体力にあったことをしなければならない","訓練がつらくて、乗り越えられないかもしれない"], answer:1,
      translation:"(Bài đọc: xem bản dịch ở câu 67)",
      explanation:"Đáp án 2. Đoạn giữa: 'その場所を去らなければならない「とき」がやってくる... 毛利さんも、じつはそのことは、二度目の訓練を受けているときから薄々感じていた' — ông linh cảm rồi sẽ phải rời nơi từng hoạt động. 1,3,4 không khớp."},
    { id:"b13-3", passage:"", audioUrl:"", question:"69. 筆者が言いたいことは何か。",
      options:["自分の夢を追い求めたあとは、若い人の夢を応援することが大切だ","夢はひとつだけではないことを若い人に伝えて、応援するべきだ","若い人の夢を応援しながら、自分の夢も追い求めつづけたほうがいい","若い人の夢を応援するには、さまざまな経験や知識が必要だ"], answer:0,
      translation:"(Bài đọc: xem bản dịch ở câu 67)",
      explanation:"Đáp án 1. Kết bài: sau khi theo đuổi giấc mơ của mình, chuyển sang ủng hộ giấc mơ thế hệ sau — đó là 'việc quan trọng của lão binh' và là lẽ sống mới. 2,3,4 không phải luận điểm chính."},
  ]
},
{
  tab: "読解", section: "問題14 情報検索",
  instruction: "右のページは、下の問いに対する答えとして最もよいものを、1・2・3・4から一つ選びなさい。",
  questions: [
    { id:"b14-1", passage:"<b>青水潮自然公園 ハイキングのお勧めコース・ガイドツアーのご案内</b><br><br><b>◆ お勧めコース（合計時間は休憩等を含めた大体の時間）</b><br><table class='info-tbl'><tr><th>コース名</th><th>コース案内</th><th>合計時間</th></tr><tr><td>らくらくコース</td><td>北口から登山鉄道で山頂へ→徒歩で植物園へ→植物園前からボートで北口前へ→徒歩で北口へ</td><td>1時間</td></tr><tr><td>花を楽しむコース</td><td>北口から登山鉄道で山頂→徒歩で植物園へ→植物園前からボートで公園案内所前へ→徒歩で南口へ</td><td>1.5時間</td></tr><tr><td>半周コース</td><td>南口から徒歩で植物園へ→徒歩で山頂へ→徒歩で北口へ</td><td>1.5時間</td></tr><tr><td>一周コース</td><td>南口から徒歩で公園案内所へ→公園案内所前からボートで北口前へ→登山鉄道で山頂へ→徒歩で植物園へ→徒歩で南口へ</td><td>3時間</td></tr></table><br><b>◆ ガイドツアーのご案内</b><br>・「お勧めコース」をガイドが一緒に回って、公園内をご案内します。お申し込みは、ツアーを希望される日の<b>10日前の午後6時まで</b>、電話で受け付けています。<br>・どのコースでも、ガイド料金は参加者1名につき<b>500円</b>です（登山鉄道代、ボート代は別にかかります）。当日の集合時に、ガイドにお支払いください。<br>・1グループの定員は<b>10名</b>です。11名以上でお申し込みの場合、当日複数のグループに分かれていただきます。<br>・出発時間は開園（<b>4月～9月：午前8時30分、10月～3月：午前9時</b>）から午前11時までの間で指定してください。<br>・キャンセルは3日前の午後6時までに電話でお願いいたします。天候不良により、ツアーが中止になる場合は、前日の午後7時までにご連絡いたします。<br>ガイドツアーのご予約：029-123-4568",
      audioUrl:"", question:"70. アニカさんは友達と3人で一緒に、ハイキングに行くことにした。3人の希望に最も合うコースはどれか。［テイエ＝登山鉄道に乗りたい／サナ＝「合計時間」が2時間まで／アニカ＝スタートとゴールは違う場所にしたい］",
      options:["らくらくコース","花を楽しむコース","半周コース","一周コース"], answer:1,
      translation:"Bảng giới thiệu 4 tuyến đường đi bộ có ghi sơ đồ, thời gian tổng cộng; kèm hướng dẫn tour có người dẫn: đăng ký qua điện thoại trước 18h ngày 10 ngày trước ngày muốn đi; phí hướng dẫn 500 yên/người (vé tàu leo núi, thuyền tính riêng); nhóm tối đa 10 người, từ 11 người trở lên phải chia nhóm; giờ xuất phát từ giờ mở cửa (4–9: 8h30, 10–3: 9h) đến 11h; hủy trước 18h 3 ngày.",
      explanation:"Đáp án 2 (花を楽しむコース). Điều kiện: phải có tàu leo núi (テイエ), thời gian ≤2h (サナ), điểm xuất phát ≠ điểm kết thúc (アニカ). 花を楽しむコース: 1.5h, đi tàu leo núi từ Bắc khẩu, kết thúc ở Nam khẩu ✓. らくらく: Bắc→Bắc (trùng điểm). 半周: không có tàu leo núi. 一周: 3h (>2h)."},
    { id:"b14-2", passage:"", audioUrl:"", question:"71. ダンさんは、10月に会社の同僚15人とガイドツアーを利用したいと思っている。申し込みにあたり気をつけなければならないこととして、合っているのはどれか。",
      options:["申し込みはツアーを希望する日の3日前の午後6時までに電話する必要がある","ガイド料金はどの「お勧めコース」を選ぶかによって変わる","申し込みはまとめてできるが、当日は複数のグループに分かれなければならない","出発時間は、午前8時30分から午前11時までの間で指定する必要がある"], answer:2,
      translation:"(Bảng thông tin: xem câu 70)",
      explanation:"Đáp án 3: đăng ký 15 người được làm chung nhưng vì định mức nhóm là 10 người nên ngày hôm đó phải chia thành nhiều nhóm. 1 sai (đăng ký trước 10 ngày; 3 ngày là hạn hủy). 2 sai (phí cố định 500 yên). 4 sai (tháng 10 mở cửa 9h, không phải 8h30)."},
  ]
},
/* ================= TAB 5: 聴解 ================= */
{
  tab: "聴解", section: "問題1 課題理解",
  instruction: "まず質問を聞いてください。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File đề không có audio/transcript → các câu dưới đây chỉ có phần in trên giấy + đáp án theo bảng đáp án trong file.）",
  questions: [
    { id:"c1-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio (bài nghe & câu hỏi) không có trong file đề — file chỉ in phần lựa chọn trên giấy.", audioUrl:"", question:"1番", options:["サークル活動","アルバイトの選び方","勉強の工夫","就職のための準備"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio (không có transcript trong file đề).",
      explanation:"Đáp án theo bảng đáp án file: 3. Nội dung nghe không có trong file → ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c1-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"2番", options:["ねぎを収穫する","雑草をとる","ほうれんそうの種をまく","土をたがやす"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c1-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"3番", options:["ホームページから申し込む","ふりこみ先を確認する","銀行で受講料を支払う","クレジットカードを作る"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c1-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"4番", options:["しょうめい器具の位置","しょうめい器具のそざい","しょうめいの光の強さ","しょうめいの明かりの色"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2 (chất liệu của thiết bị chiếu sáng). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c1-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"5番", options:["机といすをならべる","パソコンを設置する","机に封筒を置く","来場者の案内をする"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題2 ポイント理解",
  instruction: "まず質問を聞いてください。そのあと、問題用紙のせんたくしを読んでください。読む時間があります。それから話を聞いて、問題用紙の1から4の中から、最もよいものを一つ選んでください。（File đề không có audio/transcript.)",
  questions: [
    { id:"c2-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"1番", options:["地域の林業についての講義","山での基本作業の体験","人工呼吸の練習","木材を使った工作"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2 (trải nghiệm thao tác cơ bản trên núi). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c2-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"2番", options:["パンの値段を下げる","閉店時間を早める","ホームページを作る","ちらしに割引券をつける"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 3 (tạo trang web). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c2-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"3番", options:["ほかの保護者と知り合うことができる","ちいきの役に立つことができる","先生たちのことを知ることができる","学校での子供の様子を見ることができる"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 1 (có thể làm quen với các phụ huynh khác). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c2-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"4番", options:["様々な値段から選ぶから","古い物でも古さを感じさせないから","帯や小物との組み合わせが楽しめるから","注目を集めることができる"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 3 (vì có thể thưởng thức sự kết hợp với obi và phụ kiện). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c2-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"5番", options:["ウオーキングコンテストの実施","体操動画の公開","運動用品の支給","食事のアドバイス"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 1 (tổ chức cuộc thi đi bộ). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c2-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần audio không có trong file đề.", audioUrl:"", question:"6番", options:["海の深いところの温度を測ること","海の表面の温度を測る計測器を開発すること","世界各国の協力を得ること","非常に多くのデータを分析すること"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 3 (nhận được sự hợp tác của các nước trên thế giới). ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題3 概要理解",
  instruction: "問題用紙に何も印刷されていません。この問題は、全体としてどんな内容かを聞く問題です。話の前に質問はありません。まず話を聞いてください。それから、質問とせんたくしを聞いて、1から4の中から、最もよいものを一つ選んでください。（File đề không có audio/transcript.)",
  questions: [
    { id:"c3-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 问题用紙に何も印刷されていません (giấy không in gì — nội dung chỉ nằm trong audio, không có trong file đề).", audioUrl:"", question:"1番（選択肢 1〜4 都在 audio, không in trên giấy）", options:["① audio","② audio","③ audio","④ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c3-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"2番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c3-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"3番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c3-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"4番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c3-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"5番（選択肢 1〜4 都在 audio）", options:["① audio","② audio","③ audio","④ audio"], answer:3,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 4. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題4 即時応答",
  instruction: "問題用紙に何も印刷されていません。まず文を聞いてください。それから、それに対する返事を聞いて、1から3の中から、最もよいものを一つ選んでください。（File đề không có audio/transcript.)",
  questions: [
    { id:"c4-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — câu nói & 3 lựa chọn đều nằm trong audio.", audioUrl:"", question:"1番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c4-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"2番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:1,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 2. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c4-3", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"3番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c4-4", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"4番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:2,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 3. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c4-5", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"5番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
    { id:"c4-6", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません.", audioUrl:"", question:"6番（選択肢 1〜3 都在 audio）", options:["① audio","② audio","③ audio"], answer:0,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"Đáp án theo bảng đáp án file: 1. ⚠️ THIẾU DỮ LIỆU TRONG FILE."},
  ]
},
{
  tab: "聴解", section: "問題5 統合理解",
  instruction: "長めの話を聞きます。この問題には練習はありません。問題用紙にメモをとってもかまいません。（File đề không có audio/transcript; bảng đáp án không có đáp án phần này.)",
  questions: [
    { id:"c5-1", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: 問題用紙に何も印刷されていません — nội dung & đáp án đều thiếu.", audioUrl:"", question:"1番（nội dung trong audio）", options:["① audio","② audio","③ audio","④ audio"], answer:null,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có đáp án trong bảng đáp án của file."},
    { id:"c5-2", passage:"⚠️ THIẾU DỮ LIỆU TRONG FILE: Phần 2番 in sẵn câu hỏi & 4 lựa chọn (xem dưới) nhưng không có audio/đáp án.", audioUrl:"", question:"2番（質問1）", options:["『白い雲』","『緑の列車』","『美しい一日』","『旅の空』"], answer:null,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có đáp án trong bảng đáp án của file."},
    { id:"c5-3", passage:"", audioUrl:"", question:"2番（質問2）", options:["『白い雲』","『緑の列車』","『美しい一日』","『旅の空』"], answer:null,
      translation:"Không thể dịch do thiếu nội dung audio.",
      explanation:"⚠️ THIẾU DỮ LIỆU TRONG FILE: không có đáp án trong bảng đáp án của file."},
  ]
},
]
});
